### ISSUE TITLE
create new inbound

### ISSUE THREAD

**Issue by AlirezaBrave** [alireza0/x-ui#1001]
سلام ارادت من از اخرین ورژن استفاده میکنم ، یک inbound هم داخل پنل ساخته شده ، اما برای Inbound دوم چنین خطایی رو میگیم ،  پروتوکل یا اسم هرچیز مختلفی رو هم امتحان کردم

Create Failed: unable to open database file: no such file or directory

**Comment by alireza0** [comment]
درود بر شما
این خطا برای زمانیه که دیتابیس شما پاک شده باشه. داده های بیشتری برای پیدا کردن مشکل شما نیاز دارم
