### ISSUE TITLE
هشدار امنیتی 

### ISSUE THREAD

**Issue by Alij13a** [alireza0/x-ui#1003]
سلام
این ارور امنیتی داخل تنظیمات اومده چیه و چطور باید رفعش کنم!؟

پیکربندی‌های خاصی مستعد حملات سایبری شناسایی شده‌اند، اقدام فوری برای تقویت پروتکل‌های امنیتی و محافظت در برابر نقض‌های امنیتی لازم است
- عمومی URI مسیر

**Comment by wulfric93** [comment]
سرتیفیکیت برای پنل گذاشتید ؟
