### ISSUE TITLE
امکان اضافه کردن کانفیگ فرگمنت در قسمت اوتباند

### ISSUE THREAD

**Issue by hrgh1985** [alireza0/x-ui#1004]
با سلام و احترام
در صورت امکان در قسمت اوتباند (برای استفاده از تانل)
امکان استفاده از کانفیگ فرگمنت (فایل json) هم میسر میسر شود. که بتوان از دامنه فیلتر شده استفاده کرد.
با سپاس

**Comment by alireza0** [comment]
درود بر شما
چشم
توی برنامه هام گذاشتم

**Comment by alireza0** [comment]
امکان استفاده از خروجی فرگمنت با https://github.com/alireza0/x-ui/commit/e3c2b42048ac3cbe9a7d073804c2c46b99281873 به تنظیمات xray اضافه شد.
 برای استفاده از این ویژگی:
 ۱. یک خروجی freedom با تنظیم fragment  ایجاد کنید و برچسب مشخصی مانند `fragment` بهش بدید
۲. در خروجی تانل خودتون با تنظیم dialer Proxy در بخش sockopt  به برچسبی که در بخش قبل درست کردین، میتونید مسیر خروجی تانل رو به خروجی با فرگمنت بفرستید.


این ویژگی در نسخه بعد قابل استفاده خواهد بود.
موفق باشید

**Comment by hrgh1985** [comment]
درود و سپاس
