### ISSUE TITLE
نحوه استفاده از قابلیت فرگمنت

### ISSUE THREAD

**Issue by Mahyar378** [alireza0/x-ui#1006]
با سلام
لطفا در خصوص نحوه استفاده از قابلیت فرگمنت توضیح میدید؟ 

با تشکر

**Comment by alireza0** [comment]
درود بر شما
هنوز نرم افزار های سمت کاربر پشتیانی همه گیری ندارند و برای تست گذاشته شده.
تا زمانی که همه گیر بشه روش ها و آموزش هاش هم ساخته میشه
