### ISSUE TITLE
VLESS+WS+TLS Issue

### ISSUE THREAD

**Issue by Mad880** [alireza0/x-ui#1007]
Hello,

I'm having trouble making a working config with TLS enabled. VLESS+WS works completely fine with, but when I enable TLS it won't work.
My ssl is valid, I use cloudflare's proxied DNS and the port is supported by cloudflare.

All ideas are appreciated.
Thanks.

**Comment by alireza0** [comment]
Hi @Mad880 ,
As you know, cloudflare free ports are separated in HTTP and HTTPS suport.
Please double check if the port is existed in free ports table.
Otherwise, there should be no problem if you configured the inbound in a right way.
