### ISSUE TITLE
routing rules

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/x-ui#1010]
سلام عزیز
اگر بخشی توی routing rules بشه اضافه کرد که بگیم اگر با دامنه x.sample.com داشت به inbound وصل میشد برای مثال بلاک بشه یا از warp خروجی داده بشه خیلی میتونه مفید و کاربردی باشه.

ممنون از وقت با ارزش شما.

**Comment by alireza0** [comment]
درود بر شما
بخش مسیریابی به پنل ربطی نداره و اگر xray-core پشتیبانی کنه میشه اینجا هم گذاشت.
ولی در نهایت این چیزی که میخواید توی دنیای شبکه هم نامفهومه. کسی از دامنه به جایی نمیتونه درخواست بزنه.
توی دنیای اینترنت (TCP/IP) درخواست فقط از آی‌پی به آی‌پی زده میشه

**Comment by emadtoranji** [comment]
یعنی نمیشه متوجه شد مثلا کاربر با دامنه a.sample.com درخواست داده یا b.sample.com ؟

اگر شدنی میشه با یک ساب دامنه مثل warp میشه به کاربر این اختیار رو داد که هم با وارپ متصل بشه هم مستقیم

**Comment by alireza0** [comment]
برای این مدل باید دو اینباند مجزا داشته باشید و هرکدوم رو با یک دامنه راه اندازی کنید.
برای اینکه از یک پورت استفاده کنید باید از نرم افزار های دیگه مثل nginx یا hsproxy استفاده کنید و هر دامنه رو به اینباند درستش بفرسته.
