### ISSUE TITLE
تانل معکوس 

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#1012]
سلام وقتتون بخیر باشه 

در تانل  معکوس انگار ترافیک را دو برابر حساب میکنه درسته ؟؟؟

یا ارائه دهنده سرور ایران مشکل داره ؟؟؟

**Comment by alireza0** [comment]
درود بر شما
این مشکل ربطی به پنل نداره.
مشکل محاسبه ترافیک لوپ بک توسط بعضی سرویس دهندگان هست.
با داده های کافی با اونها مطرح کنید.
