### ISSUE TITLE
تک کاربره کردن

### ISSUE THREAD

**Issue by aghajani82** [alireza0/x-ui#1013]
با سلام و خسته نباشید
در رابطه با تک کاربره کردن کلاینت ها
علیرضا جان این مورد خیلی وقته جا افتاده
اگه واقعا میشه کاریش کرد ممنون میشم این مورد رو هم اضافه کنید
باتشکر

**Comment by ErfanTech** [comment]
https://github.com/alireza0/x-ui/issues/824
