### ISSUE TITLE
کار نکردن وارپ روی متا

### ISSUE THREAD

**Issue by Daniel182713** [alireza0/x-ui#1014]
سلام علیرضا خسته نباشید بابت تمام تلاشت.

من از قسمت basic وقتی گزنیه وارپ متا رو فعال میکنم درست جواب نمیده چون موزیک ها پلی نمیشه و میگه این تو کشور شما در دسترس نیست در صورتی که وقتی یه inbound ساختم و کل ترافیکش رو از روی وارپ عبور دادم موزیک رو پست ها پخش میشه ولی وقتی صرفا متا روشن باشه موزیک ها پخش نمیشه مشکل از کار منه آیا؟

**Comment by Daniel182713** [comment]
من هر کاری بود امتحان کردم‌ فکر کنم قسمت متا مشکل داره زمانی که روشن می‌کنیم روتینگ رول انجام نمیشه من از یه جا سرور تهیه کردم ipv4 میده و ipv6 نمیده برای همین موزیک های اینستاگرام برام باز نمیشه وقتی یک اینباند رو کل ترافیکش رو از وارپ عبور میدم اهنگ ها اینستاگرام پخش میشه ولی وقتی گزینه متا رو از توی پنل روشن میکنم موزیک های رو پست پخش نمیشه.

**Comment by Daniel182713** [comment]
بله موزیک ها روی کشور  های خاص قابل اجرا هست ولی من vpn ریجن امریکا ساختم که مشکلی از اون بابت نیست من تست کردم وقتی یه اینباند رو کل ترافیکش رو از روی warp عبور میدم موزیک بدون مشکل پخش میشه ولی وقتی گزینه متا رو روشن میکنم دیتا اینستاگرام از روی warp عبور نمی کنه من احساس میکنم تمام ip های اینستاگرام روی فایل متای پنل قرار نگرفته از این سایت زیر میشه کل ip ها اینستا گرام روی دید:

https://www.netify.ai/resources/applications/instagram

**Comment by Daniel182713** [comment]
در مورد ipv6 هم من روی اون اینباند که کل ترافکیش رو از روی وارپ عبور دادم از قسمت warp دامین استراتژی رو روی force ipv4 قرار دادم موزیک ها پخش نمیشد ولی وقتی روی force ip قرار میدمکه هم ipv6 و هم ipv4 رو ساپورت میکنه موزیک ها پلی میشه.

**Comment by Daniel182713** [comment]
الان امتحان میکنم

**Comment by Daniel182713** [comment]
انجام نمیشه

**Comment by liamnees** [comment]
> انجام نمیشه

تونستی مشکل موزیک حل کنی؟ منم همین مشکل دارم هر کار هم می کنم درست نمیشه!!!
