### ISSUE TITLE
Error / common/mux: unexpected EOF > and warning common/mux: XUDP hit

### ISSUE THREAD

**Issue by kalilovers** [alireza0/x-ui#1015]
سلام وقت بخیر خسته نباشید دو مورد داخل لاگ هسته دیدم متوجه نشدم 
یکی تو قسمت ارور هست که : 
2024/02/23 17:16:44 ERROR - XRAY: [1099703642] common/mux: unexpected EOF > common/mux: failed to read metadata > common/mux: invalid metalen 18245
2024/02/23 16:29:00 ERROR - XRAY: [3292034152] common/mux: unexpected EOF > common/mux: failed to read metadata > common/mux: invalid metalen 5379
دوتا هم تو قسمت وارن : 
2024/02/23 17:17:57 WARNING - XRAY: [3031181111] common/mux: XUDP hit [157 151 172 36 196 227 131 2] > conflict

2024/02/23 17:20:57 WARNING - XRAY: [3459298302] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp [2002:iheideit:f0bb::1]:443: operation was canceled] > common/retry: all retry attempts failed
وارن دوم میگه وصل نمیشه به ایپی درحالی که داخل سرور پینگ میده و متصله tcp

 پشت سرهم و گهگاه ارسال میشن دلیلش چیه به نظرتون 

پنل اصلی داخل سرور ایران هست و با ریلیتی تانل شده و ایپی لوکال برای تست 

 ورژن هسته 1.8.4

**Comment by Daniel182713** [comment]
پورت دامنه یا پورت اینباند هات نباید باهم یکی باشه اینو چک بکن شاید درست بشه

**Comment by kalilovers** [comment]
> پورت دامنه یا پورت اینباند هات نباید باهم یکی باشه اینو چک بکن شاید درست بشه

ممنون از چنین موردی نیستش همشون جدا هستن فقط اینباند 443 با اوتباند 443(که اینباند 443 خارج هستش) یکی هست که مشکلی نداره

**Comment by kalilovers** [comment]
> فکر کنم توی مسیر یه سری بسته گم می‌شه،‌ یا کانکشن به صورت لحظه‌ای قطع می‌شه. می‌تونه زیر سر ارتباط ناپایدار با خارج باشه. حس می‌کنم از وقتی تونل معکوس زدم، این خطاها کمتر دیده می‌شه. (البته این بار باید توی لاگ سرور خارج دنبال این خطا گشت.)

درسته امکانش هست چون میگه ارتباط قطع میشه و درستم هست موقتا قطع میشه فکر کنم چون pipe میده پشت سرهم پکت دریافت نشه
