### ISSUE TITLE
اضافه کردن فرگمنت به عنوان خروجی

### ISSUE THREAD

**Issue by aboozar1368** [alireza0/x-ui#1016]
سلام وقتتون بخیر
آیا امکان این وجود داره که ما یه فرگمنتو به عنوان خروجی اضافه کنم منظورم فایل جیسون هستش 
ویک اینباند از اون فرگمنت خروجی استفاده کنه 
امیدوارم متوجه منظورم شده باشین

**Comment by arash88** [comment]
#1017 [dialerProxy]
