### ISSUE TITLE
Missing Xray's advanced settings

### ISSUE THREAD

**Issue by arash88** [alireza0/x-ui#1017]
Hi @alireza0 jan,
Some extra parameters make PBR, Chain proxying, TCP optimization, etc a lot easier and are currently missing in X-UI panels.

For **Outbounds**:

**Mux** and **Fragmentation** settings.
**UseIPv4v6** and **UseIPv6v4** as domain strategies.

**For both inbounds and outbounds objects in X-UI:**

**TLSObject** -> disableSystemRoot

and:

**SockoptObject** ->
                              "domainStrategy"
                              "dialerProxy"
                              "tcpKeepAliveInterval"
                              "tcpcongestion"
                              "interface"
                              "tcpMptcp"
                              "tcpNoDelay"

**Comment by alireza0** [comment]
Dear @arash88 ,
Thank you for your kind suggestions.

X-UI is not going to provide all the features of xray-core.
I expect this panel to provide simple solutions for simple users.
Advanced users can do all in xray-core itself.

Regarding features:
- Mux: Is not usefull for server's outbounds and make it more slow! I am thinking to add it to JSON-SUB
- Fragment is implemented a long time ago
- Based on documentation, Domain strategies in routing object has not such these options. Query strategy in DNS has not as well
- disableSystemRoot: Most people don't have any idea about how it works. Adding this feature is not usefull for a big part of users.
- Sockopt is also a kind of advanced option. I am thinking to add some other parts in JSON-SUB


IMHO we should have a balance between providing all options and simplifying usage.
I would like to keep this issue, to add the options for JSON-SUB

**Comment by arash88** [comment]
> Dear @arash88 , Thank you for your kind suggestions.
> 
> X-UI is not going to provide all the features of xray-core. I expect this panel to provide simple solutions for simple users. Advanced users can do all in xray-core itself.
> 
> Regarding features:
> 
> * Mux: Is not usefull for server's outbounds and make it more slow! I am thinking to add it to JSON-SUB
> * Fragment is implemented a long time ago
> * Based on documentation, Domain strategies in routing object has not such these options. Query strategy in DNS has not as well
> * disableSystemRoot: Most people don't have any idea about how it works. Adding this feature is not usefull for a big part of users.
> * Sockopt is also a kind of advanced option. I am thinking to add some other parts in JSON-SUB
> 
> IMHO we should have a balance between providing all options and simplifying usage. I would like to keep this issue, to add the options for JSON-SUB

Thanks a lot, dadashi
Fair enough but please reconsider the Sockopt object, just the dialerProxy brings a lot of new possibilities for the end user!
Other options are amazing too.

**Comment by alireza0** [comment]
I will keep it in my mind.
Thank you for your hint :)

**Comment by alireza0** [comment]
@pulsarice 
Thank you for providing these information.
It is also exists in chinese version of [documentation](https://xtls.github.io/config/outbounds/freedom.html#outboundconfigurationobject) and is added since 1.8.6 as new features.

![image](https://github.com/alireza0/x-ui/assets/12573084/46bb2f7b-bc36-40cc-a58b-756cf924368c)

I will try to deploy it for next version.

**Comment by arash88** [comment]
Thanks again @alireza0 joon,
Another thing is that enabling "External Proxy" for inbounds doesn't actually produce anything inside the xray-core configs, am I correct? I can't find anything about this function in Project X's wiki either. Does this thing actually mimic a genuine TLS connection?

**Comment by alireza0** [comment]
DNS new strategies and outbound sockopt is now added to x-ui and will be available in next version.

**Comment by MK0ltra** [comment]
Some other missing features for freedom outbound that i noticed:
_proxySettings_ and  _sendThrough_

When i try to add this settings with "Add outbound with json" feature, they will be removed from final configuration and won't be saved. The only way i found to add them is through xray template.

**Comment by arash88** [comment]
> Some other missing features for freedom outbound that i noticed: _proxySettings_ and _sendThrough_
> 
> When i try to add this settings with "Add outbound with json" feature, they will be removed from final configuration and won't be saved. The only way i found to add them is through xray template.

+1
Yes and also these options for inbounds are necessary and the developer must decide to implement them. Although some of these options need Autocomplete/Multi-select elements in GUI.

sockopt -> "dialerProxy"
sockopt -> "interface"

Anyway thanks @alireza0 jan

**Comment by alireza0** [comment]
> Some other missing features for freedom outbound that i noticed: _proxySettings_ and _sendThrough_
> 
> When i try to add this settings with "Add outbound with json" feature, they will be removed from final configuration and won't be saved. The only way i found to add them is through xray template.

@MK0ltra 
`sendThrough` is not an option only for `freedom` protocol. I will add it soon for all the outbounds.
`proxySettings` is not recommended due to conflict with `sockopt. dialerProxy` (which is already added).
BTW: If you want to add an advanced config, it is beter to have it in Advanced Template tab.

@arash88 
`sockopt. dialerProxy` is already added and will be available in next release.
I assume that interface is a kind of enterprise usage which could not be useful for most of users. Although you are free to use all available configurations in Advanced Template tab.

**Comment by alireza0** [comment]
Thanks a lot for your suggestions.
I will close this issue and looking forward to hearing more helpful ideas based on common needs in new issues.
