### ISSUE TITLE
Routing rules and tag for core's Built-in DNS Server traffic

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#1018]
Traffic generated by core's built-in DNS can be tagged by inboundTag:
```
{
  "dns": {
    "servers": [],
    "tag": "dns_inbound"
  }
}
```

Then it can be routed like this:
```
  "routing": {
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "dns_inbound"
        ],
        "outboundTag": "direct"
      }
    ]
  }

```
The routing table of web interface does not detect and include internal DNS server's tag in selectable inbounds.
Currently it can be done manually.
![image](https://github.com/alireza0/x-ui/assets/5326305/c60a896b-5e2f-418e-8bea-43bcbac60220)

**Comment by alireza0** [comment]
Please read the documentation with all details:
> Traffic generated by built-in DNS, except for `localhost`, `fakedns`, `TCPL`, `DOHL`, and `DOQL` modes, can be matched with `inboundTag` in routing using this identifier.

I will deploy it to be used in chain of proxies.

**Comment by alireza0** [comment]
This feature is now added and will be available in next version
