### ISSUE TITLE
Password rest admin

### ISSUE THREAD

**Issue by esmaeilifardi** [alireza0/x-ui#1024]
پسورد پنل وقتی از داخل خود پنل تغییر داده میشه دکمه سیو که میزنی پنل رفرش میشه و بالا نمیاد که بتونی ری استارت پنل بزنی بعد حتی از داخل ترمینال هم ریستارت پنل میزنی دیگه بالا نمیاد پنل

**Comment by alireza0** [comment]
رمز رو درست وارد نکردین!
میتونید گزینه تغییر تنظیمات رو انتخاب کنید و داده ها رو ویرایش کنید.
