### ISSUE TITLE
ربات تلگرام 

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#1025]
با عرض سلام 

تانل معکوس که اضافه شده خیلی خوبه اما ربات روی سرور ایران کار نمیکنه امید وارم که به تنظیمات ربات چیزی اضافه کنید که از طریق اینباند پورتال اینترنت بگیره و از سرور خارج استفاده کنه

**Comment by wulfric93** [comment]
از این راهنما استفاده کنید : https://github.com/alireza0/x-ui/issues/252
