### ISSUE TITLE
Development Guide 

### ISSUE THREAD

**Issue by ErfanTech** [alireza0/x-ui#1026]
@alireza0 I've been relying on building the `main.go` file to test changes, but it's limiting, especially without `xray-core`. What's a quicker and more effective way to develop and test?

Also, I think it'd be great to have a straightforward guide for new devs joining the project. It could cover setup, making changes, testing, and contributing. This would be super helpful for us!

**Comment by ErfanTech** [comment]
> I've been relying on building the `main.go` file to test changes, but it's limiting, especially without `xray-core`.
>
I already said i exactly do this but need `xray-core`.

**Comment by Enkidu-6** [comment]
I'm sorry may be I misunderstood but I don't understand what you mean by " need xray-core". Every release or every docker image you build is a complete application and has everything it needs to run including the xray-core. You simply install or run it the same way you do the original version and it works as intended. Am I missing your point?

**Comment by ErfanTech** [comment]
Oh, I don't use docker.
I'll try it.

Thanks

**Comment by Enkidu-6** [comment]
> Oh, I don't use docker. I'll try it.
> 
> Thanks

It's easy to use docker images for your testing but you don't have to. You can build a new release in your own fork on github as well. Just use the existing action under the Actions tab.
