### ISSUE TITLE
xray config Advanced text can no longer be selected

### ISSUE THREAD

**Issue by Enkidu-6** [alireza0/x-ui#1027]
Hi,
After your newest modification to [xray.html](https://github.com/alireza0/x-ui/commit/99e9c27d2f9f7ad69ce9aefd351b0c69877dc6d8#diff-63904d2d38cd130422cc84150cdfe5c611d65d0a7460af72a347fcb6e5ab02c3) on lines 4 and 11 the text in the Advanced configuration of xray can no longer be selected and copied. Is this an intentional feature or an unintended bug?
Thanks.

**Comment by alireza0** [comment]
Hi @Enkidu-6 ,

These changes are related to auto refresh when new version come across.
If you have a problem in your build, just hard-refresh your browser.

Please check your browser console after that and if there is any error, just inform me with proper data.

**Comment by alireza0** [comment]
This `?{{ .cur_ver }}` will add a querystring to the request of that file which will be ignored in webserver.
But the reason behind this change is to update file address to avoid being cached in browser or behind procy caches like Cloudflare.
When you have no problem in console log, there should be no problem in loading the files.

But /ant-design-vue@1.7.8/antd.min.js loading is critical!
And the web-font is not a persian only font. It si multi-language web-font.

**Comment by Enkidu-6** [comment]
Just to give you an update, Merging the rest of the commits ( I'm one commit behind) into my fork solved the problem with text selection in advanced tab.

As for the other browser errors, well, if you can't reproduce them, then it must be something on my end and I'll figure it out. No reason to waste your time with it. Not to mention that it's not related to this topic.

Thanks again for your time.
