### ISSUE TITLE
اضافه کردن TCP Segment به بخش Fragment

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1029]
سلام و خسته نباشید
با توجه به این که همه ی کانفیگ ها TLS دار نیستند و خیلیا بدون TLS استفاده میکنن ، لطفا درصورت امکان TCP Segment  رو هم به بخش Fragment اضافه کنید.
الان فقط از TLS Hello ساپورت میکنه.
اگه مثل ابزار IRCF بتونیم بین روش های فرگمنت انتخاب کنیم عالی میشه و UI هم خیلی شلوغ و پیچیده نمیشه.
ممنون از زحماتتون.

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم

این ویژگی فعلا در حال بررسی است و دلیل اضافه نشدن هم پشتیبانی نشدن توسط کلاینت هاست.
البته در حال تکمیل هم هست و کم کم اضافه میشه. امیدوارم کلاینت ها هم به زودی پشتیبانی کنن

**Comment by alireza0** [comment]
این ویژگی در اضافه شده و در نسخه بعد قابل تنظیم خواهد بود.
