### ISSUE TITLE
SNI is missing in TLS for external proxy

### ISSUE THREAD

**Issue by vendemmia-cpu** [alireza0/x-ui#1030]
سلام؛ ضمن تشکر از سازندگان پنل x-ui به ویژه علیرضای عزیز.
یک درخواست برای تغییر بخش TLS در External Proxy دارم.
این قابلیت استفاده زیادی توی ریورس پروکسی داره و الان کار رو خیلی راحت کرده اما
وقتی که TLS رو در External Proxy انتخاب میکنیم، فقط داخل لینک security=tls قرار میده و چیزی رو برای SNI نمیذاره.
این موضوع برای v2rayNG مشکلی نیست چون اگه SNI خالی باشه خودشون دامین هدر برای SNI هم قرار میده، ولی برای کلاینت های آیفون مشکل پیش میاد که این کار رو نمیکنن و باعث میشه کانفیگ وصل نشه. و uTLS و ALPN هم نمیشه گذاشت.
خواهشی که دارم حداقل قابلیت مشخص کردن SNI وقتی TLS رو فعال میکنی باشه، یا دامنه Request Header رو برای SNI هم قرار بده.
درسته میشه دستی دامین رو توی SNI نوشت ولی این مشکل برای لینک سابسکریپشن هم هست.

پیشاپیش ممنون از پاسخ شما ♥

**Comment by alireza0** [comment]
درود بر شما
حدس میزنم داده های اشتباهی از این ویژگی دارید!
وقتی شما میبایست از حالتی به جز `همسان` استفاده کنید که در نرم افزار دیگری مثل nginx ارتباط رو دریافت میکنید.
در این صورت همه تغییرات رو میتونید همونجا اعمال کنید.

اگر از نرم افزار خارجی استفاده نمیکنید حتما باید از حالت همسان استفاده کنید.

**Comment by alireza0** [comment]
ما به دلیل مشکل جا این آپشن ها رو نمیتونیم جا بدیم.
وگرنه برنامه نویسیش مشکل نیست.
پنل همین الانشم خیلی پر از تنظیمه.

**Comment by alireza0** [comment]
شما میتونید آدرس رو معادل sni بذارید و معمولا نیازی به sni دیگه نیست. مگر اینکه شما اصرار داشته باشید چند sni رو با nginx مدیریت کنید. اینجوری بهتره sni ها رو توی چند externalProxy بذارید.
برای این کاربرد خیلی خاص نمیشه کل پنل رو تغییر داد.
اضافه کردن اتوماتیک، فقط در حالت خاص شما استفاده میشه و بقیه ممکنه این تنظیم رو نداشته باشند و یا نخوان!

**Comment by sinazlf** [comment]
> استفاده از حالت غیرهمسان یک کاربرد داشته برای من. تنظیمات SSL کلادفلر رو گذاشتم روی flexible. کانفیگ سمت یوزر از نوع TLS روی پورت ۴۴۳ هست و تنظیمات سمت سرور بدون TLS و روی پورت ۸۰. گفتم شاید بتونه بار پردازشی سمت سرور رو کمتر بکنه. بیشتر جنبه کنجکاوی داشت البته. البته با توجه به اینکه کدنویسی بلد نیستم، برای درست کردن لینک اشتراک، از chatgpt عزیز کمک گرفتم و برام یه worker نوشت و اون مشکل sni و hostname و uTLS و ... حل شد. شاید همچین روشی به شما هم کمک کنه.

سلام یعنی توستی sni خودت رو سمت یوزر اضافه کنی؟میشه بیشتر توضیح بدی؟
