### ISSUE TITLE
Security Alert| - JSON URI Path

### ISSUE THREAD

**Issue by arp7vpn** [alireza0/x-ui#1033]
این خطا رو چطور باید رفع کرد؟
پنل ssl داره روی دامنه بالا اومده، uri path هم تنظیم شده براش اما هر بار این ارور میاد!!!!

Security Alert
Certain configurations have been identified as susceptible to attacks, prompting immediate action to reinforce security protocols and safeguard against potential security breaches.
- JSON URI Path
![Screenshot 2024-02-26 221330](https://github.com/alireza0/x-ui/assets/130001898/7f667cdb-ba9e-48c4-adf0-aa190d49d70a)

**Comment by alireza0** [comment]
بخش سابسکریپشن json جدید اضافه شده. یه مقدار متفاوت به کلید URI PATH توی اون برگه بدی حل میشه.
مشکل اینه که این path اگر مقدار پیش فرضش (/json/) باشه، توسط اسکنر ها قابل پیدا کردنه.
