### ISSUE TITLE
بهتر شدن فرگمنت

### ISSUE THREAD

**Issue by asadace1** [alireza0/x-ui#1034]
سلام وقت بخیر
طبق تستهایی که بنده انجام دادم کانفیگ فرگمنت بچه های ircf بهتر از خود مال پنل کار میکنه اگه امکانش هست از این روش برای تولید json استفاده کنید و اینکه mux رو بزارید
با تشکر

**Comment by alireza0** [comment]
درود بر شما
من چندین بار توی ایشو های مختلف این مورد رو جواب دادم.
از نظر کانفیگ، این دو روش هردو کانفیگ یکسانی دارند.
با این تفاوت که اونجا همه پروتکل ها رو هنوز ساپورت نمیکنه، در صورتی که پنل همه پروتکل ها رو داره.
در ضمن اگر ساب شما تعداد زیادی کانفیگ داشته باشه، کاربر به صورت اتوماتیک به کانفیگی که کمترین پینگ رو داره وصل میشه.

کانفیگ ها اگر برای همه کلاینت ها به صورت یکسان جواب بده، مشکلی نیست.
ولی فعلا برای تست اضافه شده و هنوز خیلی مشکل هست.
احتمالا برای نسخه جدید xray که آپشن های بهتره گذاشته بشه بهینه تر عمل کرد.

آپشنهای دیگه هم در صورت ساپورت شدن توسط نرم افزار های سمت کاربر اضافه میشه.

**Comment by waxilu** [comment]
I make a vless ws config in xui panel and active fragment in json subscription
I add it to V2rayNG client, its slow yet, fragment didn't solve speed problem
but I put that config in IRCF website with same fragment setting that I set in panel and its work well,
why?

**Comment by alireza0** [comment]
Just compare the results
