### ISSUE TITLE
قطعی چند ثانیه ای روی پنل ریورس 

### ISSUE THREAD

**Issue by kamkamini** [alireza0/x-ui#1035]
سلام اقا علیرضا وقت بخیر
من یه چند روزیه خب قطعی چن ثانیه ای دارم باید برم داخل برنامه خاموش روشن کنم تا اوک شه چن روزه اینجوری شده دلیلش چیه؟

**Comment by hansari1996** [comment]
بنده هم دقیقا همین مشکل رو دارم

**Comment by alireza0** [comment]
درود بر شما
مشکل شما بیشتر فیلترینگه.
ارتباط بین دو xray-core رو پنل نمیتونه حل کنه و مشکل پنل نیست.
لطفا تنظیمات دیگه ای رو تست کنید و سعی کنید بهترین رو انتخاب کنید.

**Comment by hansari1996** [comment]
درود به شما آقای احمدی بزرگوار


یه سوال داشتم خدمتتون

آیا اگه با تانل معکوس به صورت tcp معمولی و vmess یا veles تانل بزنیم سرور ایران سریع فیلتر میشه؟

و ایا ترافیک کلی نت بیشتر tcp هست یا websocket یا grpc و تشخیص کدوم سخت تره؟

**Comment by hansari1996** [comment]
> درود بر شما
> 
> مشکل شما بیشتر فیلترینگه.
> 
> ارتباط بین دو xray-core رو پنل نمیتونه حل کنه و مشکل پنل نیست.
> 
> لطفا تنظیمات دیگه ای رو تست کنید و سعی کنید بهترین رو انتخاب کنید.



درود به شما آقای احمدی بزرگوار

یه سوال داشتم خدمتتون

آیا اگه با تانل معکوس به صورت tcp معمولی و vmess یا veles تانل بزنیم سرور ایران سریع فیلتر میشه؟

و ایا ترافیک کلی نت بیشتر tcp هست یا websocket یا grpc و تشخیص کدوم سخت تره؟

**Comment by alireza0** [comment]
درود بر شما @hansari1996 
به شخصه در این زمینه دانش زیادی ندارم. باید از دوستان دیگری پرس و جو کنید.
