### ISSUE TITLE
Pagination Resets When Table is Re-Rendered

### ISSUE THREAD

**Issue by ErfanTech** [alireza0/x-ui#1037]
When both auto-refresh and pagination are activated, the table is re-rendered properly; however, the pagination resets to default settings.

https://github.com/alireza0/x-ui/assets/108360299/ee0339fd-d40a-4611-a487-01056342d676

**Comment by alireza0** [comment]
It happens because we have only one pageSize defined in the page as default.
After each reloading data, all tables will be re-rendered.
Unnecessary complexity avoid us to store each inbound's pagination in a separate variable.

**Comment by ErfanTech** [comment]
got it, thanks
