### ISSUE TITLE
رفع مشکل پخش موزیک اینستاگرام!

### ISSUE THREAD

**Issue by liamnees** [alireza0/x-ui#1038]
مشکل البته از پنل نیست. قابلیتی به پنل اضافه بشه که مشکل پخش موزیک های اینستاگرام که به دلیل کپی رایت رفع بشه. روی برنامه shadowrocket وقتی حالت کانفیگ روی scene میذاری این مشکل رفع میشه که در اپ های دیگه همچین چیزی ندیدم. اگر پنل این مشکل حل کنه عالی میشه یا اگر راه حل دیگه ای داره کسی راهنمایی کنه ممنون میشم. ضمنا وارپ هم جواب نمیده حتی روی اپ 1.1.1.1 هم موزیک پخش نمیشه.

**Comment by alireza0** [comment]
این مشکل نرم افزار کلاینت میشه و پنل دخالتی نمیتونه توش داشته باشه

**Comment by liamnees** [comment]
نمیگم مشکل از پنل ولی قطعا راه حلی اسکریپتی برای حل این مشکل هست! گفتم شاید کسی بدونه راهنمایی کنه وقتی با تغییرات توی کلاینت میشه از طریق پنل یا کانفیگ ممکنه راهی داشته باشه. همینطور که فرگمنت شد، اینم ممکنه راهی براش باشه. و اون تنظیم هم فقط همون برنامه داره روی هیچ اپ دیگه ای موزیک روی v2ray بالا نمیاد.
