### ISSUE TITLE
فعال سازی تلگرام در سرور های ایرانی

### ISSUE THREAD

**Issue by imanmahdavi** [alireza0/x-ui#1039]
با سلام
علیرضا عزیز
من در تاپیک شما دیدم که به خوبی توضیح دادید. ولی متاسفانه علیرغم آموزش های شما و همینطور تلاش های من امکان انجام برای من محیا نشد.
من در سرور خودم از پورت 443 استفاده می کنم.
همه راه حل ها رو هم تست کردم. ولی در بخش اموزشی شما، به درستی متوجه نشدم و برای من کار نمی کنه.
از انجایی که از سرور های ایرانی هم امیدی به اپ تاپ بودن نیست. این موضوع پشتیبان گیری امر حیاتی هست و من شدیدا به ان نیاز دارم.
ممنون میشم، مجدد راهنمایی کنید.❤️

**Comment by alireza0** [comment]
درود بر شما
اگر از پورت ۴۴۳ استفاده میکنید، بهتره اینباند رو روی آی‌پی سرور محدود کنید که با اینباند تلگرام به مشکل نخورن.
از روش های دیگه مثل فرگمنت و یا TPROXY هم میتونید استفاده کنید.

**Comment by imanmahdavi** [comment]
ممنون از پاسخ شما
ولی من تنظیمات زیر رو انجام میدم نمیشه متاسفانه.
1- سرور ایران دارم
1- سرور خارج دارم

پیش توضیح : کاربران در سرور ایران هستند و از طریق reverse اینترنتی از خارج میگیرن.
پوست های مشغول من 443و2083و2096 و .. به شرح تصویر می باشد.

![Screenshot 2024-03-07 193814](https://github.com/alireza0/x-ui/assets/24840819/bc6d213a-b309-407c-a5cc-2e42fd0d9558)

ابتدا یه docomodo ایجاد کردم به تصویر زیر 

![Screenshot 2024-03-07 200030](https://github.com/alireza0/x-ui/assets/24840819/eb767be4-e981-40a8-8030-85d987e840e2)


سپس تنظیمات زیر رو اعمال کردم.

```
sysctl net.ipv4.conf.all.forwarding=1
ip rule add fwmark 1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -A PREROUTING -d 149.154.160.0/20 -p tcp -j TPROXY --on-port 38591 --on-ip <IP-IRAN> --tproxy-mark 0x1/0x1
iptables -t mangle -A OUTPUT -s <IP-IRAN> -d 149.154.160.0/20 -j MARK --set-xmark 0x1/0xfffff
```

و تنظیمات تلگرام هم انجام میدم و نتیجه ای در بر ندارد.


بیصبرانه منتظر کمک شما هستم.
با تشکر

**Comment by alireza0** [comment]
از اینکه dns سرور شما آدرس درستی رو برمیگردونه مطمئن بشید.
```bash
nslookup api.telegram.org
```

اگر درست بر نمیگرده اون رو به صورت ثابت تعریف کنید:
```bash
echo "149.154.167.220 api.telegram.org" >> /etc/hosts
```

**Comment by imanmahdavi** [comment]
از اینکه به من پاسخ دادید سپاسگزارم

اول ست نشده بود. بعد ست کردم و به شرح زیر شد.
<img width="381" alt="Screenshot 2024-03-08 at 11 28 21 PM" src="https://github.com/alireza0/x-ui/assets/24840819/18013e61-0a71-4005-8451-aa9f6e49ab02">

این هم تلگرام

<img width="801" alt="Screenshot 2024-03-08 at 11 29 11 PM" src="https://github.com/alireza0/x-ui/assets/24840819/98b0f177-4b18-48c2-873d-7fa6b06dbb5b">

این هم خروجی

<img width="503" alt="Screenshot 2024-03-08 at 11 31 17 PM" src="https://github.com/alireza0/x-ui/assets/24840819/f73e4cca-9d9b-491b-bc9b-3ff0b2001032">


این هم عکس کلی پنل 

<img width="724" alt="Screenshot 2024-03-08 at 11 31 42 PM" src="https://github.com/alireza0/x-ui/assets/24840819/62d44bb3-eb0d-42d7-8c3a-af4633b48ba7">


این هم دوکومودو 

<img width="590" alt="Screenshot 2024-03-08 at 11 31 34 PM" src="https://github.com/alireza0/x-ui/assets/24840819/0d4a2edf-960e-42e2-b002-0383d9f9577b">

این هم resolve
توضیح : روی ۱.۱.۱.۱ میذارم کار نمی کنه. پیش فرض اینه

<img width="234" alt="Screenshot 2024-03-08 at 11 32 57 PM" src="https://github.com/alireza0/x-ui/assets/24840819/97241766-ae77-4fff-adc8-bd20a67b0181">

این هم هاست 

<img width="660" alt="Screenshot 2024-03-08 at 11 34 23 PM" src="https://github.com/alireza0/x-ui/assets/24840819/370131aa-3deb-4e2d-9e30-81d50d29e971">


این هم تنظیمات ریورس

![Uploading Screenshot 2024-03-08 at 11.35.12 PM.png…]()

**Comment by alireza0** [comment]
اینباند دوکودمودور inbound-38591 برای اینباندهای ریورس انتخاب نشده.

**Comment by imanmahdavi** [comment]
مهندس جان
ممنون از اینکه وقت گذاشتید.

فرمایش شما درست بود و من در این بخش مسیر دهی نکرده بودم.
ممنون از راهنمایی شما.

این موضوع حل شد.❤️🌹
