### ISSUE TITLE
Bulk Edit

### ISSUE THREAD

**Issue by aliafshany** [alireza0/x-ui#104]
Hello there

Thank you for taking the time and effort to work on this project.

I'd like to know if Is it possible to implement a Bulk Edit option? This would allow users to check a few boxes and then edit the time and date or volume, with a single click applying the changes to the selected accounts.

**Comment by alireza0** [comment]
Hello @aliafshany 
Thank you for your kind suggestion,

It is not easy in this panel UI. I will keep it in my mind if I start another panel ;)
