### ISSUE TITLE
سوال درمورد Balancer

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1040]
سلام و خسته نباشید
تشکر فراوان بابت زحماتی که بی منت برای اینترنت آزاد میکشید.
امکانش هست یکم درمورد Balancer که اخیرا به X-ui اضافه شده توضیح بدید؟
اینکه دقیقا چطور میشه ازش استفاده کرد و کاربرد اصلیش روی سرور به چه شکله.

**Comment by alireza0** [comment]
درود بر شما
سپاسگزام
این ویژگی از سالهای پیش به v2ray افزوده شده و به جهت درخواست هایی که داشتیم به پنل هم افزوده شد.
کار پایه ای این ویژگی سهمیه بندی ترافیک بین خروجی های متفاوته.
