### ISSUE TITLE
امکان مسدود سازی بدافزار و فیشینگ و...

### ISSUE THREAD

**Issue by Alirezamoradi20** [alireza0/x-ui#1041]
سلام خسته نباشید
امکان مسدود کردن بدافزار و کریپتوماینر و فیشینگ و امثالهم در پنل به چه صورت است؟

**Comment by alireza0** [comment]
درود بر شما
تنها راهی که در پنل هست، استفاده از DNS و یا تنظیم خانواده است.

**Comment by Alirezamoradi20** [comment]
استفاده از DNS رو یه توضیح میدین؟کدوم قسمت باید چی اضافه کنم؟

**Comment by alireza0** [comment]
یه سرور dns اضافه کنید و مقدار اون رو به شکل ساده بذارید 1.1.1.2
[لینک](https://en.wikipedia.org/wiki/1.1.1.1)
