### ISSUE TITLE
عوض کردن کشور وارپ warp

### ISSUE THREAD

**Issue by The-Binary-0-1** [alireza0/x-ui#1043]
سلام و ارادت. جناب علیرضا اول خواستم ازتون تشکر کنم. دوم اینکه راهی هست که آی پی وارپ رو عوض کنیم از یه کشور دیگه آی پی بگیره؟

**Comment by alireza0** [comment]
درود بر شما
سپاسگزام
من داده های زیادی در این باره ندارم.
وارپ هم به شکل همگانی ساده به این پنل افزوده شده.
