### ISSUE TITLE
conflict with haproxy

### ISSUE THREAD

**Issue by secpwdip** [alireza0/x-ui#1045]
thanks for your very good project.
I used your xui with haproxy and there is some issues with it and makes cpu usage to very high percentage,
could you fix it or there is any way to fix it?
thanks

**Comment by alireza0** [comment]
Hello @secpwdip 

I don't know clearly what is your problem and which part of application or config consumes high load of CPU.
You should first check your processes, I/O and memory to find out which process is guilty!

As an advice, turn off logs in xray configuration section first and see the results.

**Comment by secpwdip** [comment]
hi @alireza0 
Thank you for the advice.
I should plus that I checked the processes with htopcommand.
After installing Haproxy, two processes Xray and haroxy increase the cpu load. Each of them is placed on the number 30% to 40% .
But as soon as the Haproxy is uninstalled, the usage decreases and is set to 1or 2percent.

**Comment by alireza0** [comment]
I am not sure, but it seams there is a loop in your configuration.
Consult with a System Admin about this problem
