### ISSUE TITLE
Reverse tunnel through cdn

### ISSUE THREAD

**Issue by mahdimirzayi120** [alireza0/x-ui#1047]
سلام علیرضا عزیز
Reverse tunnel پنل شما خيلي عالي كار ميكنه واقعا فوق العده است.
فقط يك نكته اين كه من vless+ws+tls ساختم مشكلي نداشت ولي وقتي ميبرم پشت cdn و پروكسي cloudflare روشن ميكنم handshake انجام نمیشه!!!!
نميدونم مشكل از من است يا اصلا چنين امكاني وجود ندارد كه reverse tunnel از cdn رد شود؟ 🌹
ناگفته نماند از port 443 استفاده كردم.

**Comment by alireza0** [comment]
درود بر شما
شما میتونید تانل معکوس رو از کلادفلر هم عبور بدید و به درستی باید کار کنه.
تنظیمات و بعد از اون محدود نبودن ارتباط کلادفلر با سرورتون رو چک کنید

**Comment by arash88** [comment]
@mahdimirzayi120 @alireza0 
برای آزمایش تست کردم و ترافیک روی تانل معکوس از نوع پرتال و پل از طریق کلادفلر رد نشد. خیلی عجیبه.
