### ISSUE TITLE
آدرس پنل بعد از نصب

### ISSUE THREAD

**Issue by mrmasiha0** [alireza0/x-ui#1049]
سلام و خسته نباشید

من پنل را تازه نصب کردم و میخوام بدونم بعد از نصب پنل آدرسی که باید روی وب باز کنم تا به تنظیمات دسترسی پیدا کنم چی هست.
من پورت رو 2096 گذاشتم و اینجوری آدرس باز کردم ولی درست نبود.

ip:port

**Comment by dreamboxone** [comment]
http://ip:port
