### ISSUE TITLE
باز نشدن سایت یوتویوب در ریورس

### ISSUE THREAD

**Issue by mrmasiha0** [alireza0/x-ui#1052]
سلام و خسته نباشید
من دو کانفیگ زدم یکی به صورت مستقیم و یکی ریورس.
وقتی از کانفیگ های ریروس استفاده می کنم همه سایت ها باز می شوند و به صورت عجیبی یوتویوب باز نمی شود ولی در کانفیگ مستقیم همین سرور، یوتویوب به راحتی باز میشه.
 از دوستان کسی همچین تجربه ای داشته؟

**Comment by ErfanTech** [comment]
https://github.com/alireza0/x-ui/issues/885
