### ISSUE TITLE
Removing port number from generated subscription link and QR code

### ISSUE THREAD

**Issue by ivanvpetrovich** [alireza0/x-ui#1056]
Hello!
Thank you for your hard work!

I use CF for proxeing domain name for subscriptions, but CF can't proxie domain with port number (may be it can on non free plans)
So, x-ui panel generate a link and subscriptions QR code with a port number in it, like https://contoso.com:55055/sub/.....
Can you make a setting where we can disable port number in subscription link, or where can i disable it manually?

Many thanks!

**Comment by alireza0** [comment]
Hello @ivanvpetrovich ,

When you are using HTTPS protocol, port 443 will be used by default and will be removed in final link.
In your use-case, you should consider free ports which CF is supporting.

**Comment by ivanvpetrovich** [comment]
Hi @alireza0 
Yes, you are right, but you told about connection url. But i told about Subscription link.
Cloudflare can't parse any port in domain names, so, if i make subscription port like 60000/tcp my link will be like https://contoso.com:60000/sub/ and Cloudflare can't parse it.
I can make a rule in CF dashboard: 
![Screenshot_6](https://github.com/alireza0/x-ui/assets/154434625/e635f476-6106-40a8-8daa-eb34c0d7d2eb)
and it work when subscription link without port number (e.g. https://contoso.com/sub/) and CF redirect me to https://my_ip_address:60000/sub/
Can you give me a hint where i can change qr and link generation code please? I need to leave the listening port 60000/tcp but change the subscription link without the port number.
Thank you very much!

**Comment by alireza0** [comment]
Hi @alireza0 ,
It was what I mean.
If you want to change the url to sth else, you can use `Reverse Proxy URI`

**Comment by ivanvpetrovich** [comment]
Useing reverse proxy won't help me.
x-ui panel generates subscription links with port number https://contoso.com:60000/sub/... and if i paste it into FoxRay or something else Cloudflare can't proxied this site because it have a port number in URL. I can use only domain name without port number in subscription url. And i can't use port 443 because it is already running, like port 80.
I have to use a rule on Cloudflare - if there is a request on port 443, redirect it to port 60000

Do you know which file is responsible for generating the subscription link?

**Comment by ivanvpetrovich** [comment]
I tried to remove port in this two files, but this did not bring any changes in link generation
file: /web/assets/js/model/xray.js
const link = vless://${uuid}@${address}:${port};

file: /sub/subService.go
link := fmt.Sprintf("vless://%s@%s:%d", uuid, address, port)

**Comment by alireza0** [comment]
Sorry! It is not a related question. Please find your answer in CF documentation

**Comment by ivanvpetrovich** [comment]
OK, sorry for that.
May be anybody else can help me in this easy question. I need a file name in which i can remove port number from generated link and QR code.
Thanks
