### ISSUE TITLE
رفع این هشدار امنیتی

### ISSUE THREAD

**Issue by arp7vpn** [alireza0/x-ui#1057]
![Screenshot 2024-03-04 012124](https://github.com/alireza0/x-ui/assets/130001898/596fe21d-7c24-4254-a967-b616a081638e)
برای رفع این هشدار چیو باید تنظیم کنیم؟
Security Alert
Certain configurations have been identified as susceptible to attacks, prompting immediate action to reinforce security protocols and safeguard against potential security breaches.
- JSON URI Path

**Comment by peyman508** [comment]
تو تنظیمات پنل سابسکریپشن رو فعال کن.تو قسمت سابسکریپشن Json در قسمت URI مسیر و تغییر بده و یه اسم براش بزار

**Comment by peyman508** [comment]
تو تنظیمات پنل سابسکریپشن رو فعال کن.تو قسمت سابسکریپشن Json در قسمت URI مسیر و تغییر بده و یه اسم براش بزار
