### ISSUE TITLE
چند کانفیگ دادن به کاربر و جدا کردن لینک ساب از کانفیگ

### ISSUE THREAD

**Issue by Alirezamoradi20** [alireza0/x-ui#1060]
سلام وقت شما بخیر
۲ تا سوال داشتم اول اینکه چطوری میشه به یک کاربر با یک لینک ساب از دو یا چند اینباند کانفیگ داد؟مثلا یکی تانل باشه یکی cdn یکی مستقیم

و دوم اینکه چطوری میشه دامنه لینک سابسکریپشن رو از دامنه کانفیگ جدا کرد تا درصورت فیلترشدن دامنه کانفیگ نیاز به دادن مجدد لینک ساب نباشه چون روش ترافیکی رد نمیشه

**Comment by alireza0** [comment]
درود بر شما
برای سوال اول از external-proxy استفاده کنید
برای سوال دوم از تنظیم دامنه در تنظیمات سابسکریپشن
