### ISSUE TITLE
قابلیت مشاهده آخرین زمان اتصال کاربر

### ISSUE THREAD

**Issue by Alirezamoradi20** [alireza0/x-ui#1063]
سلام وقت بخیر
اگر قابلیتی اضافه کنید که آخرین زمان اتصال کاربر رو نشون بده خیلی میتونه کاربردی باشه.

**Comment by ramtiny** [comment]
اره این قابلیت خیلی خوبیه

**Comment by alireza0** [comment]
درود بر شما
این داده ها در دیتابیس ذخیره نمیشه. پس قابل نمایش هم نیست.
اضافه کردنش بار زیادی رو به دیتابیس اضافه میکنه که عملا کارایی رو پایین میاره.
به همین دلیل افزودنش به نسبت کارایی اش، به صرفه نیست
