### ISSUE TITLE
Xray Error

### ISSUE THREAD

**Issue by THMaST3R** [alireza0/x-ui#1064]
سلام
از دیروز هسته xray تو پنل ارور میده
 github.com/xtls/xray-core/main/main.go:22 +0x1a5

**Comment by chernyshaw** [comment]
Same with fresh install 1.7.2.
I try install 1.6.4 at docker, then upgrade to 1.7.2 and it works fine.

**Comment by alireza0** [comment]
درود بر شما
برای بررسی باید لاگهای بیشتری رو بفرستید

**Comment by LoicMaster** [comment]
Logs for an exact same exit code
2024/05/10 14:10:34 ERROR - X-UI: Failure in running xray-core: exit status 2
2024/05/10 14:10:34 DEBUG - XRAY: github.com/xtls/xray-core/infra/conf.(*Config).Build(0xc000196a80)
2024/05/10 14:10:34 DEBUG - XRAY: , 0x2b?}, {0xc0000457e8?, 0xc000168890?, 0x0?})
2024/05/10 14:10:34 DEBUG - XRAY: ?
2024/05/10 14:10:34 DEBUG - XRAY: 0xc0000b6c00
2024/05/10 14:10:34 DEBUG - XRAY: ,
2024/05/10 14:10:34 DEBUG - XRAY: ?
2024/05/10 14:10:34 DEBUG - XRAY: 0xc00021ef78
2024/05/10 14:10:34 DEBUG - XRAY: {
2024/05/10 14:10:34 DEBUG - XRAY: (
2024/05/10 14:10:34 DEBUG - XRAY: encoding/hex.Decode
2024/05/10 14:10:34 DEBUG - XRAY: ]:
2024/05/10 14:10:34 DEBUG - XRAY: running
2024/05/10 14:10:34 DEBUG - XRAY: [
2024/05/10 14:10:34 DEBUG - XRAY: 1
2024/05/10 14:10:34 DEBUG - XRAY: goroutine
2024/05/10 14:10:34 DEBUG - XRAY: runtime error: index out of range [8] with length 8
2024/05/10 14:10:34 DEBUG - XRAY: panic:
2024/05/10 14:10:34 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
