### ISSUE TITLE
سرتیفیکیت کلودفلر در x-ui

### ISSUE THREAD

**Issue by soli2413** [alireza0/x-ui#1065]
داخل دستور ایکس یو آی گزینه 17 برای سرتیفیکت کلودفلر هست.قسمت ای پی آی رو از کدوم قسمت کلودفلر باید بگیرم و وارد کنیم؟

**Comment by alireza0** [comment]
منوی سمت راست بالا، گزینه My Profile و بخش API Tokens

https://dash.cloudflare.com/profile/api-tokens

**Comment by habibnajafi** [comment]
وقتی از کلادفلر سرتیفکیت میگیریم کجا ذخیره میشه و اسمش چیه یعنی توی پنل ادرس چی باید بدیم؟ من الان از کلادفلر گرفتم ولی نمیدونم اسم فایل چیه و هرچی میزنم توی تنظیمات پنل خطا میزنه
