### ISSUE TITLE
منتهی ولی کار میکند 

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#1066]
سلام  تانل معکوس زدم کانفیگ تموم شده ولی هنوز استفاده میکنه مشکل چیه یا فقط من اینطوریم

**Comment by alireza0** [comment]
درود بر شما
باید ببینید در زمانی که کاربر به پایان زمان یا حجم میرسه چه لاگی در x-ui دارید.
باید لاگی برای قطع شدن کاربر با سطح DEBUG وجود داشته باشه.
