### ISSUE TITLE
اضافه کردن remark روی فرگمنت

### ISSUE THREAD

**Issue by liamnees** [alireza0/x-ui#1067]
روی فرگمنت remark ایجاد کنید که اکانت ها اسم داشته باشن و اگر بشه کنار ساب فایل json حجم و زمان اکانت بیاد عالی میشه

**Comment by alireza0** [comment]
این ویژگی به همراه ویژگی های دیگه در حال آماده سازیه. ولی هنوز نرم افزار های کلاینت پشتیبانی خوبی ندارند.

**Comment by liamnees** [comment]
> این ویژگی به همراه ویژگی های دیگه در حال آماده سازیه. ولی هنوز نرم افزار های کلاینت پشتیبانی خوبی ندارند.

striesand پشتیبانی می کنه بقیه اپ ها هم کم کم اضافه میشن

**Comment by alireza0** [comment]
در جریان هستم. طبق مکاتبات خود من با برنامه نویس این نرم افزار، چند امکان جدید اضافه شده.
برای اینکه یک بخش اضافه بشه، یک نرم افزار کافی نیست و با نرم افزارهای دیگه مشکل داریم هنوز.
مثلا نرم افزار shadowrocket استاندارد های متفاوتی داره.
