### ISSUE TITLE
Adding the Path entry for Dokodemo-door

### ISSUE THREAD

**Issue by armin567ip** [alireza0/x-ui#1069]
Hi, there is a script that simplifies setting up Nginx + Fallback so that all users can connect through port 443 but there is an inner port inside the server for each inbound (a random port)
this script https://github.com/GFW4Fun/x-ui-pro
You may know what I'm talking about.

So in this case I will have to specify a path for each inbound like this "/{port}/ANYTEXT".

Now here's the feature request?
Well I was tryna do the same with Dokodemo-door for tunneling but I noticed it doesn't have the path entry, Can you add it please.

**Comment by alireza0** [comment]
HI @armin567ip 

This feature is called `Per Path Route` which could be only available in some trasmission types.
Dokodemo-door is not a proper protocol for this feature.
