### ISSUE TITLE
شمارش روز های اشتراک بعد از اولین اتصال

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#107]
سلام
لطفا این قابلیت رو اضافه کنید که تعداد روز های اشتراک کاربر بعد از اولین اتصالش به کانفیگش محاسبه بشه
ممنون

اینو برای 3x-ui هم نوشته بودم و بهش تگ enhancement هم داده بودن، ولی الان دیدم ایشون کلا بخش issues ریپازیتور شون رو حذف کردن برا همین گفتم اینجا بنویسم

**Comment by alireza0** [comment]
درود بر شما
متاسفانه پنل x-ui برای این مدل تغییرات ساخته نشده.
برای این کار میبایست دیتابیس رو تغییر بدیم و این تغییر برای کاربران قدیمی و کسانی که به این نسخه مهاجرت میکنند مشکلات زیادی ایجاد میکنه.
ترجیح میدم وقتم رو برای نوشتن پنل جدید بذارم و این امکانات رو اونجا پایه ریزی کنم.
