### ISSUE TITLE
Bug: a user is inaccessible on panel!

### ISSUE THREAD

**Issue by MJamshidnejad** [alireza0/x-ui#1072]
I has encountered a wired case in the panel. A user had been disabled automatically or manually (I am not sure) and after some days I tried to enable it and gave it a new ID. But after enabling or saving the changes, I get an error:  
`Error: Request failed with status code 404`

The user is disabled and ID and Subscription ID is empty.

Please check and let me know if you need more information.

**information**
 - Platform: Docker
 - Version: 1.7.2

**Comment by alireza0** [comment]
In manual/auto disabling process, there is no code which could delete ID or/and SubID.
ID in vless and vmess protocol is a mandatory key value. If it is empty, then it is not possible to use functions like edit and delete.

If you are using 3rd party apps working with x-ui API, ask the developer to fix the problem.

**Comment by MJamshidnejad** [comment]
> In manual/auto disabling process, there is no code which could delete ID or/and SubID. ID in vless and vmess protocol is a mandatory key value. If it is empty, then it is not possible to use functions like edit and delete.
> 
> If you are using 3rd party apps working with x-ui API, ask the developer to fix the problem.

I don't know the reason but it happened. Please look at this picture: 


![Screenshot 2024-03-10 185957](https://github.com/alireza0/x-ui/assets/65599746/e1b850f6-8fcb-4bd3-b374-8936dc7b4173)

I can't change anything in this page. If I do, I get that error. I can't even change the Email!
I don't use any 3rd party apps. I could provide you any information that can help you to find the reason.

**Comment by MJamshidnejad** [comment]
This code worked for me. I hope be useful for a person.

```
import uuid, json, sqlite3

inbound_id = 2
user_email = "<put_the_problematic_email>"

conn = sqlite3.connect("x-ui.db")
cursor = conn.cursor()
cursor.execute(f"select settings from inbounds where id == {inbound_id}")
tmp = cursor.fetchone()[0]
tmp_json = json.loads(tmp)

idx = -1
for i,c in enumerate(tmp_json['clients']):
	if c["email"] == user_email :
	    idx = i
	    break

tmp_json['clients'][idx]['enable'] =  True
tmp_json['clients'][idx]['id'] =  str(uuid.uuid4())
tmp_json['clients'][idx]['subId'] = "abcd123"

sql = "UPDATE inbounds SET settings = ? WHERE id = ?"
cursor.execute(sql, (json.dumps(tmp_json, indent=2), inbound_id))
conn.commit()
```
