### ISSUE TITLE
آیفون 

### ISSUE THREAD

**Issue by ali90500** [alireza0/x-ui#1073]
سلام
من ریورس پنل به پنل زدم
نوع کانفیگ هم
Vmess+tcp+http
هست و کلاینت هم v2box
که آیفونا قطعی وصلی دارن
ولی اندروید مشکلی نداره

**Comment by Daniel182713** [comment]
Streisand رو نصب کن از قسمت tunnel برو persist tunnel و connect on demand رو فعال کن اوکی میشه
