### ISSUE TITLE
درخواست راهنمایی 

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#1074]
سلام و درود :

با کلود فلر و websocket اینباند درست کردم با http  که با نت سامانتل اوکی ابود همراه اول کند و مشکل داره روی ایرانسل هم کلا متصل نمیشه اما کانفیگ دارم از کسی که دقیق مثل این کانفیگ هستش اما فقط قسمت path اینباند ?ed=2048 و این را سرچ کردم سر از Client Certificates اوردم اما هیچ دانشی بهش ندارم ممنون میشم راهنمایی کنید

**Comment by alireza0** [comment]
https://xtls.github.io/en/config/transports/websocket.html#websocketobject
