### ISSUE TITLE
این پنل تنظیمات رو برای xray-core آماده میکنه و اونجا اجرا میشه.

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#1075]
این پنل تنظیمات رو برای xray-core آماده میکنه و اونجا اجرا میشه.
لینک ارائه شده نشون میده که xray-core ساپورت نمیکنه و برنامه نویسی باید اونور انجام بشه.
شما میتونید از پراکسی های دیگه مثل nginx استفاده کنید و path ها رو به این سرویس متصل کنید.

_Originally posted by @alireza0 in https://github.com/alireza0/x-ui/issues/662#issuecomment-1836918849_
          

آموزشی چیزی هست برای این ؟

**Comment by alireza0** [comment]
آموزش خیلی زیاد هست. هم ویدئو و هم مستند. لطفا جستجو کنید.
نمونه تنظیمات:
https://github.com/XTLS/Xray-examples/tree/main/All-in-One-fallbacks-Nginx
