### ISSUE TITLE
اضافه کردن Hostname به بخش  External Proxy

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1076]
سلام و وقت بخیر
یه موردی توی پنل هست به اسم  External Proxy که میتونی باهاش دامنه و پورت های مخلتفی رو برای یک اینباند ست کنی و برای تانل خوبه.
یه آپشنی هم اگه اضافه بشه خیلی به کمک کنندست ، اونم اضافه کردن Host به بخش External Proxyه. ( بیشتر واسه کانفیگ های Websocket کاربرد داره ) 
به این صورت که مثلا در کنار دامنه و پورت ، یه بخش هم واسه وارد کردن Host باشه. و طبیعاتا اگه خالی بزاریمش هم میاد از همون Host اصلی که وارد کردیم استفاده میشه. ( هاست نیم اصلی هم وارد نکنیم باز مشکل خاصی نیست ، بستگی به نوع کانفیگ داره )
این کار باعث میشه بتونیم چندین دامنه و تانل و  CDN و... رو روی فقط یک اینباند و فقط با یک لینک سابسکریپشن استفاده کنیم که فیلترینگ رو خیلی سخت تر میکنه.
چون باعث میشه از چندین روت مختلف به سرور دسترسی داشته باشیم که به نظرم خیلی کاربردی و عالیه.
امیدوارم توی آپدیت جدید به پنل اضافه بشه.
ممنون از شما.

**Comment by alireza0** [comment]
درود بر شما
روز شما هم به شادی، سپاسگزارم

زمانی که شما مقدار Host رو تغییر میدید، در بعضی از ارتباط ها باعث وصل نشدن ارتباط میشه.
بخش External-Proxy در حد مینیمال ساخته شده و جای زیادی برای اضافه کردن ویژگی های اینچنینی نداره.
شلوغ کردن پنل ارزشش کمتر از ایجاد سلوشن های پیچیده است که مخاطب کمی دارن.

**Comment by Alireza78na** [comment]
ممنون از پاسختون
اگه بشه فقط در حدی باشه که موقع جنریت کردن کانفیگ ، از Host مربوط به External Proxy استفاده کنه تمومه
ینی تغییر خاص و پیچیده ای روی پنل انجام نشه،
 مثل گزینه های Tls هم میشه ایجادش کرد که پنل شلوغ نشه.

ینی Host اصلی و کانفیگ و ... سرجاش میمونه و فقط کانفیگ رو طبق اطلاعات External Proxy ها جنریت میکنه و درواقع Host داخل پنل چندین بار تعریف نمیشه ( فقط داخل کانفیگ کاربر تعریف میشه )

درمورد ارتباط ها ، راستش نزدیک به ۱ ساله به صورت دستی از این روش استفاده میکنم و واقعا تا حالا مشکلی واسم ایجاد نکرده.
این اپشن واسه کسایی که از WS استفاده میکنن خیلی مفیده، چون دستی تست کردیم و خیلی خوب جواب داده ( حتی توی تعداد بالا )

ممنون میشم اگه یه تست کوچیک بزنید ، شاید نظرتون عوض شه.

**Comment by alireza0** [comment]
پنل مرزبان، این کانفیگ ها رو توسط نرم افزار جانبی به یک کانفیگ وصل میکنه. این کار هم پیچیدگی اینجاد میکنه و هم کنترلش برای ارائه همه مدل کانفیگ سخت تر میشه.
کار این پنل کاملا متفاوته و استفاده از نرم افزارهای جانبی فقط با دانش ادمبن میتونه اضافه بشه. در غیر اینصورت نمیشه همه مدل کانفیگی ارائه کرد. اگر دقت کنید پنل های دیگه به همین دلیل، فقط تعداد محدودی مدل کانفیگ میتونن ارائه بدن.
