### ISSUE TITLE
ایا میشه کاری کرد سایت های ایرانی باز نشه؟

### ISSUE THREAD

**Issue by ramtiny** [alireza0/x-ui#1078]
باعرض معذرت بابت باز کردن تاپیک جدید
متاسفانه جوابمو پیدا نکردم
امکانش هست تو تنظیمات پنل بشه کاری کرد که یوزرها نتونن از سایت ها و دامنه های ایرانی دیدن کنند؟

**Comment by alireza0** [comment]
از بخش تنظیمات عمومی ایکس‌ری، بخش مسدود سازی کشور ها میتونید انجام بدید.
نکته ها:
۱. باید این تنظیمات در بخش قوانین مسیریابی در جای درستی قرار بگیرند.
۲. به تنظیمات استراتژی کلی freedom و sniffing هر اینباند باید دقت بشه.
