### ISSUE TITLE
سوال در مورد ریورس 

### ISSUE THREAD

**Issue by mmsh1370** [alireza0/x-ui#1079]
سلام علیرضا 
دمت گرم بابت بروزرسانی پنل
من یه سرور ایران دارم که پنل رو روش نصب کردم
یک سرور ویندوزی که در خارج هست با کلاینت v2rayn چک میکنم با چه پروتوکل و ترنسمیشنی کیفیت ارتباط خوبی میتونم با این سرور بگیرم
که بعد برای کانکشن ارتباط میانی ریورس از اون استفاده کنم
چیز عجیبی که بهش خوردم اینه که ارتباط از جنس ترنسمیشن mKCP سرعت خیلی زیادی بهم میده
حالا پروتکلش vmess,vless,trojan,shadowsocks باشه خیلی تفاوت نمیکنه
ولی مشکلی که بهش برخوردم اینه که وقتی جنس ترنسمیشن رو mKCP میزارم برای "ارتباط میانی ریورس" 
سرور خارج هیچ موقع کانکشن برقرار نمیکنه
در مواردی هم متوجه شدم روی بقیه ارتباط های ریورس در سرور خارج اختلال میندازه
حس میکنم هسته xray نمیتونه فایل کانفیگ رو بخونه گیر میکنه
برقراری ریورس با mKCP با پنل 3x-ui هم امتحان کردم و نتیجه نگرفتم
میشه مشکل من رو برسی کنیدو چاره ای بیاندیشید
با تشکر

**Comment by alireza0** [comment]
درود بر شما
برقراری ارتباط به روش تنظیم شما بستگی داره و در مورد پنل نیست.
در این موارد تجربه خاصی ندارم و بهتره با سعی و خطا و کمک گرفتن از دوستان فعال در این زمینه بهترین روش رو برای خودتون پیدا کنید.
سرعت ارتباط کانفیگ هایی شبیه kcp به دلیل استفاده از UDP بالاست، ولی از طرف دیگه فیلترینگ راحت تر میتونه محدودش کنه.
