### ISSUE TITLE
لینک ساب Clash/ClashMeta

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#108]
سلام
لطفا لینک ساب برای کلش یا کلش متا بزارید.
تو کانفیگ های کلش، سرور از طریق هدر `subscription-userinfo` میزان اعتبار حجمی و زمانی کاربر رو به کلاینت کاربر میفرسته که خیلی خوبه
با تشکر

**Comment by alireza0** [comment]
درود بر شما
متاسفانه پنل x-ui برای این کار ساخته نشده، ولی میشه با محدودیت زیادی این کار رو بهش خوروند.
یکی از مورادی که قراره توی نسخه بعدی این پنل اضافه بشه همینه.
