### ISSUE TITLE
پیشنهاد تغییر در کانفیگ فرگمنت

### ISSUE THREAD

**Issue by hamedm94** [alireza0/x-ui#1080]
سلام

با تغییر کوچک در تنظیمات فرگمت پنل علیرضا،با آی پی فیلتر شده و حتی دامنه فیلتر شده نیز قابل استفاده خواهد بود و نیازی به مبدهای فرگمنت در طرف کانفیگ خروجی کابر نخواهیم داشت.

در کانفیگ فعلی در تگ wsSettings کد زیر وجود دارد:

        "wsSettings": {
          "headers": {},
          "path": "/"
        }

اگر این قسمت به صورت زیر تغییر کند:

        "wsSettings": {
        "path": "/"
        "headers": {"Host": "sni.example.com"}

به طوری که دامنه example.com می تواند دامنه پنل xui ادمین باشد که اصولا SSL هم برای آن فعال است و همچنین در قسمت زیر هم به جای دامنه پنل دامنه speedtets.net و یا zula.ir (آی پی تمیز کلورفلر) درج شود کاربر با کانفیگ دریافتی بدون هیچ مشکلی با دامنه فیلتر شده هم قادر به اتصال خواهد بود:

            "address": "www.speedtest.net",
            "port": 443,
            "users": [

البته می توان مقادیر Address و Port و Host را متغییر در نظر گرفت و در قسمت تنظیمات فرگمنت پنل ادمین فیلد مخصوص آنها قرار داد که کاربر بتواند مقادیر دلخواه را وارد و ذخیره کند. در حال حاضر من این تغییرات را دستی انجام می دهم. امیدوارد از نظر فنی قابل انجام باشد.

با تشکر از علیرضا

**Comment by alireza0** [comment]
درود بر شما
این تنظیمات به صورت خودکار در پنل قابل انجام است.
تنظیم هدر ها در وب‌سوکت و تغییر آدرس در بخش external Proxy همه این تغییرات دلخواه شما رو برآورده میکنه.

**Comment by alireza0** [comment]
کانفیگ فرگمنت در ساب جیسون کاملا تغییر کرده. نسخه جدید رو بزودی ریلیز میکنم با اون تست کنید.
