### ISSUE TITLE
(minor) Bug: Users traffic exceed the limit. 

### ISSUE THREAD

**Issue by MJamshidnejad** [alireza0/x-ui#1083]
Dear Alireza
Thank you for your attention. The problem is clear and the following picture is an example. I know it is not too important but I decided to share it with you.

![Annotation 2024-03-09 122248](https://github.com/alireza0/x-ui/assets/65599746/32495efd-d597-444b-8349-2137aec94b10)

 - Platform: Docker
 - Version 1.7.2

**Comment by alireza0** [comment]
Dear @MJamshidnejad,

It is normal to have extra usage, but I have to enforce Remaining to show Zero or `-` instead.

**Comment by MJamshidnejad** [comment]
Oh good point. I forgot to mention that. :) That problem is also exist in subscription reports. 
Why is it normal? connected connections?
