### ISSUE TITLE
Suggesting some little improvements 

### ISSUE THREAD

**Issue by MJamshidnejad** [alireza0/x-ui#1084]
Dear Alireza,

I hope you're doing well! I just wanted to drop you a quick note to say thank you for your awesome panel and all the work you've put into making it better. I wish to know Golang so I can help out and join in with the project.

While using your panel, I've come across a few small problems that I think could make it even better and easier to use. They might not be super urgent, but I thought it would be helpful to mention them:

1. **Adding Custom GeoIP and Geosite with Automatic Updates:** It would be great if we could easily add custom GeoIP and Geosite data, especially for those of us using Docker where accessing these files can be tricky.

2. **Adding an Empty Option for Routing Table in Outbound and Balancer Lists:** Right now, these lists don't have an empty option .It means we have to go into the advanced settings, which isn't ideal.

3. **Checking Configurations After Saving in Advanced Tab:** It would be really helpful if there was a way to check our configuration after saving it, like the Xray CLI does. This could save us from having to restart everything because of a mistake.

4. **Making Rules in the Routing Table Draggable:** Being able to drag and drop rules in the routing table would make it easier to organize and manage them.

5. **Fixing Fallback for Multi-Outbound Mode:** When using more than one inbound behind a fallback mechanism, it's tricky for the panel to place the right address and SNI. Maybe we could get this information from the External Proxy information of the main inbound or add a new field in fallback to simplify things.

6. **Initial Use Triggered When User Traffic is Reset:** This one's not a big deal, but it would be nice if we could avoid triggering initial use every time user traffic is reset.

Thanks for you attention, Alireza! Keep up the great work on the panel.

Best

**Comment by alireza0** [comment]
Dear @MJamshidnejad ,

Thank you for your sugestions.

> 1. **Adding Custom GeoIP and Geosite with Automatic Updates:** It would be great if we could easily add custom GeoIP and Geosite data, especially for those of us using Docker where accessing these files can be tricky.

Using docker is an advanced usage and for sure, these processes should be also special. It is not fair to remove simplicity which we offer for simple users ( as the aim of this panel ) for advanced users. It is better to wirte a bash script with cron.

> 2\. **Adding an Empty Option for Routing Table in Outbound and Balancer Lists:** Right now, these lists don't have an empty option .It means we have to go into the advanced settings, which isn't ideal.

It is already fixed in [[rule] clearable outbound & balancer](https://github.com/alireza0/x-ui/commit/3bbf83924cfddc3bb6e56fd4754384790c4aef04) as requested in #996 and will be available in next release.

> 3\. **Checking Configurations After Saving in Advanced Tab:** It would be really helpful if there was a way to check our configuration after saving it, like the Xray CLI does. This could save us from having to restart everything because of a mistake.

xray-core has not any code check in command line. The reason I am using json code viewer is to check if any problem in JSON. Otherwise, due to lots of possible problems, it is not sane to check it in panel.

> 4\. **Making Rules in the Routing Table Draggable:** Being able to drag and drop rules in the routing table would make it easier to organize and manage them.

It is already in 3x-ui implemented, but due to using old framework, it has several problems specially in mobile view. I consider using problem-free codes.

> 5\. **Fixing Fallback for Multi-Outbound Mode:** When using more than one inbound behind a fallback mechanism, it's tricky for the panel to place the right address and SNI. Maybe we could get this information from the External Proxy information of the main inbound or add a new field in fallback to simplify things.

When you are using fallback, final links and subscription will use tls/reality/externalProxy settings only from main inbound.

> 6\. **Initial Use Triggered When User Traffic is Reset:** This one's not a big deal, but it would be nice if we could avoid triggering initial use every time user traffic is reset.

It is not so hard to edit <<OFFLINE>> client after reset the traffic and set the start after first use.


I think, there is nothing to implement yet. But thank you for your inquery and suggestion.

**Comment by MJamshidnejad** [comment]
Thank you for your attention and responding in details. 

> xray-core has not any code check in command line. The reason I am using json code viewer is to check if any problem in JSON. Otherwise, due to lots of possible problems, it is not sane to check it in panel

Sorry my bad. This feature is for v2fly not Xray.

> When you are using fallback, final links and subscription will use tls/reality/externalProxy settings only from main inbound.

According to my experience, It is not true. When I addressed an inbound in fallbacks with Unix socket abstract (@ or @@), generated links are created according to the External proxy information of the gateway inbound. When I added two External proxies in gateway inbound, two Qrcodes and links are calculated and provided based on what was set in the gateway inbound not the main inbounds.

**Comment by alireza0** [comment]
It is true! Just naming fallback inbound as `main` and slave inbound as `child`.

Panel will use mentioned configuration from Fallback inbound

**Comment by MJamshidnejad** [comment]
> It is true! Just naming fallback inbound as `main` and slave inbound as `child`.
> 
> Panel will use mentioned configuration from Fallback inbound

So it will be a bit messy when more than one child inbound exists! I think it can be better.

**Comment by alireza0** [comment]
Child should inherit some configuration from Main.
It is not possible to connect client with streamSetting of child inbound.
