### ISSUE TITLE
An option to disable visual effects.

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#1086]
Is it possible to add an option to disable glowing visual effects on menus and users' traffic bar. when the count of users is high, it makes my browser use more CPU and become slow.

**Comment by alireza0** [comment]
I think these visual effects for online users are not necessary.
In orther to make the panel more light-weight, I will remove them in next release.

**Comment by alireza0** [comment]
Done!
In next release it has only menu animation which is only one object.
Onlines will be detectable only with green `online` tag
