### ISSUE TITLE
ریورس

### ISSUE THREAD

**Issue by ali90500** [alireza0/x-ui#1087]
سلام من ریوس تانل  پنل به پنل زدم اما تو استفاده از جمینی مشکل دارم
کل اوتباند رو که میندازم روی وارپ پینگ میره بالا و متصل نمیشه وقتی میزارم رو ipv4 گوگل باز میشه ولی جمینی نه وقتی میزارم روی asls جمینی باز میشه اما گوگل 403 میده

**Comment by alireza0** [comment]
درود بر شما
میتونید قوانین مسیریابی رو بر اساس هر سایت تغییر بدید.
استفاده همه ترافیک از یک مدل خروجی مثل وارپ پیشنهاد نمیشه.

**Comment by ali90500** [comment]
> پیشنهادم اینه دیفالت رو بذار روی freedom ipv4 و زیردامنه gemini و اون‌هایی که مشکل دارن رو بنداز روی وارپ.

زیر دامنه رو انداختم کلا پنل ارور خورد

**Comment by ali90500** [comment]
> درود بر شما میتونید قوانین مسیریابی رو بر اساس هر سایت تغییر بدید. استفاده همه ترافیک از یک مدل خروجی مثل وارپ پیشنهاد نمیشه.

ممنونم فقط یه سوال قوانین مسیر یابی که ایجاد میشن روی اینباند های ریورس هم تاثیر میگذارن یا اونا جداگانه هستن؟

**Comment by ali90500** [comment]
منم روی خارج نصب کردم
کل وارپ رو پاک کردم بعد فقط دامین جمینی رو گذاشتم و آوردم بالای قوانین ریورس اوکی شد
برای یوتیوب هم مشکل هست
یعنی ارور نمیده ولی لود نمیشه اونم بزارم توی وارپ؟
