### ISSUE TITLE
سوال درمورد DNS

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1088]
سلام و خسته نباشید.
یه سوال درمورد DNS داخل پنل داشتم ، اینکه قسمت fake dns کاربردش چیه و چطور باید تنظیم شه؟
و اینکه توی قسمت DNS معمولی ، بخش Domain کاربردش چیه و چطور باید تنظیم شه؟

![image](https://github.com/alireza0/x-ui/assets/144834309/02019abf-3b25-4331-90cb-82632dca9a02)

![image](https://github.com/alireza0/x-ui/assets/144834309/1ff5ba6e-7f93-4931-9c6b-72e1b79808a3)

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم.
از اینجا میتونید داده های بهتری دریافت کنید:

https://xtls.github.io/config/dns.html

https://xtls.github.io/config/fakedns.html
