### ISSUE TITLE
ایمپورت کردن بکاپ

### ISSUE THREAD

**Issue by ARYA-JAVAN** [alireza0/x-ui#109]
سلام
من از بات تلگرام برای بکاپ گرفتن استفاده میکنم
ممکنه بگید این دو تا فایلی که ارسال میشه وقتی میخایم بکاپ بگیریم رو چطوری میتونیم استفاده کنیم وقتی که اطلاعات پنل رو میخایم برگردونیم؟
کجا باید این دو تا فایل رو گذاشت؟

**Comment by alireza0** [comment]
درود بر شما
فایل اصلی پایگاه داده رو توی آدرس زیر بذارید:
```
/etc/x-ui/x-ui.db
```
فایل `config.json` برای کسایی که اون رو ویرایش کردن مفیده. تنظیمات اضافه شده قبلی رو میشه توی بخش تنظیمات xray توی پنل دوباره اضافه کرد.
