### ISSUE TITLE
sub link and  Json sub  BUG !!!!

### ISSUE THREAD

**Issue by Dwnill** [alireza0/x-ui#1090]
سلام خدمت علیرضا عزیز ،

 با توجه به اپدیت پنل به ورژن 1.8.0 ظاهرا بخش ساب و ساب جیسون مشکل جدی داره بخصوص برای کاربران اندروید با برنامه v2rayNG , ولی در برنامه streisand  ای او اس اوکیه . 
باگ به این صورت هست که کاربر لینک رو وارد میکنه، اپدیت لینک رو دریافت میکنه ولی ظاهرا در کد گذاری جیسون در داخل برنامه مشکل داره ولی در ورژن 1.7.2 پنل همچین مشکلی نیست فقط مشکل 1.7.2 عدم نمایش نام کاربر و حجم ... است . بخش فرگمنت که با توجه به اپدیت جدید بسیار کامل شده خیلی کاربردی تر شده .
امیدارم هر چه سریع تر این مشکل در پنل ۱.۸.۰ برطرف بشه چون اپشن های بسیار خوبی رو داره . ممنونم از شما

**Comment by roozbehalamdari** [comment]
> سلام خدمت علیرضا عزیز ،
> 
> با توجه به اپدیت پنل به ورژن 1.8.0 ظاهرا بخش ساب و ساب جیسون مشکل جدی داره بخصوص برای کاربران اندروید با برنامه v2rayNG , ولی در برنامه streisand ای او اس اوکیه . باگ به این صورت هست که کاربر لینک رو وارد میکنه، اپدیت لینک رو دریافت میکنه ولی ظاهرا در کد گذاری جیسون در داخل برنامه مشکل داره ولی در ورژن 1.7.2 پنل همچین مشکلی نیست فقط مشکل 1.7.2 عدم نمایش نام کاربر و حجم ... است . بخش فرگمنت که با توجه به اپدیت جدید بسیار کامل شده خیلی کاربردی تر شده . امیدارم هر چه سریع تر این مشکل در پنل ۱.۸.۰ برطرف بشه چون اپشن های بسیار خوبی رو داره . ممنونم از شما

متاسفانه منم با آپدیت جدید سنایی همین مشکل رو دارم و حسین جان جوابی ندادن هنوز ! ولی مطمین هستم آقا علیرضا جواب میدن چندین بار به مشکل خوردم حل کردن 

علیرضا جان من هم کاربر جدید میسازم روی لینک ساب اسکریپشن که میزنم متاسفانه هی این اررور رو میده :
![image](https://github.com/alireza0/x-ui/assets/131817501/fd52db17-1d1a-48d4-8125-635f9252c582)

حتی خیلی از یوزر هایی که قبلا ساخته شده بودن هم به مشکل خوردن

**Comment by roozbehalamdari** [comment]
https://github.com/MHSanaei/3x-ui/issues/2017#issuecomment-1989627680

**Comment by l3lack-eyes** [comment]
سلام بله درسته
پنل های من هم بعد آپدیت به مشکل خوردن

**Comment by roozbehalamdari** [comment]
> سلام بله درسته پنل های من هم بعد آپدیت به مشکل خوردن


به دلیل تغییرات زیاد و موارد جدید اضافه شده
باید یکبار اینباندهارو اپدیت بزنید یعنی ادیت بزنید و سپس اپدیت ، مشکل حل خواهد شد
موفق باشید

**Comment by l3lack-eyes** [comment]
درست شد . بسیار ممنون از لطف و زحماتتون
