### ISSUE TITLE
استفاده از دکودمو با قابلیت استفاده از یک پورت ثابت مثل بقیه کانفیگ ها و اتصال به چندین سرور دیگه با پورت های متفاوت.

### ISSUE THREAD

**Issue by iPbaz** [alireza0/x-ui#1091]
درود

من میخوام از طریف دکودمو تانل بزنم به سرورهای دیگه. میخوام پورتی که بهم میده رو بتونم یا زیرش کلاینت تعریف کنم و هر کلاینت با پورت 555 مثلا وصل بشه به سرور A با پورت 1 و کلاینت دوم با پورت 555 وصل بشه به سرور B با پورت 1 و یا پورت 2. اما میخوام وقتی کاربر میخواد وصل بشه و مثلا سرور B رو انتخاب کرده دیگه تو سرور A گیر نکنه و رد شه ازش.

میدونم این قابلیت از طریق روتینگ و خروجی هست کم و بیش اما من میخوام به SSH خروجی بدم.

و یا لطفا پروتکل SSH رو به خروجی اضافه کنید.

با تشکر

**Comment by alireza0** [comment]
درود بر شما
این چیزی که میخواید توی پروتکل تعریف نشده.
