### ISSUE TITLE
WebRTC leak

### ISSUE THREAD

**Issue by dark-sady** [alireza0/x-ui#1093]
Hello,
i wanted to know if its possible to route webrtc through xray. as of now its getting leaked and the real ip of the client is shown

**Comment by Alireza78na** [comment]
You should disable it in your browser

**Comment by dark-sady** [comment]
as im not the only one using it it will be kind of hard to do that but the reseasrch i did shows that the xray core doesnt have the capability of obfuscating the RTC.
