### ISSUE TITLE
مشکل در لینک سابسکریپشن

### ISSUE THREAD

**Issue by Alley041** [alireza0/x-ui#1095]
بعد از آپدیت امروز تو لینک سابسکریپشن با خطای  500 HTTP ERROR مواجه شدم، سرتیفیکیت هم درسته و بنظر میاد مشکل از اپدیت جدید باشه

**Comment by Dwnill** [comment]
والا ما هم گفتیم کسی پاسخگو نبود 🤦‍♂️😉

**Comment by Alley041** [comment]
دوستان برای حل این مشکل باید فیلد Authority توی ترنزمیشن GRPC رو خالی نزارید

**Comment by Dwnill** [comment]
> دوستان برای حل این مشکل باید فیلد Authority توی ترنزمیشن GRPC رو خالی نزارید

![F38EDFB2-26F2-4F7A-9FBC-4E50EB6967E1](https://github.com/alireza0/x-ui/assets/40546776/50955ca9-3155-4c78-afb7-feed4b1b099d)



همچین بخشی اصلا نیست😐😂

**Comment by Alley041** [comment]
> > دوستان برای حل این مشکل باید فیلد Authority توی ترنزمیشن GRPC رو خالی نزارید
> 
> ![F38EDFB2-26F2-4F7A-9FBC-4E50EB6967E1](https://private-user-images.githubusercontent.com/40546776/312762393-50955ca9-3155-4c78-afb7-feed4b1b099d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzQwNzMsIm5iZiI6MTcxMDQzMzc3MywicGF0aCI6Ii80MDU0Njc3Ni8zMTI3NjIzOTMtNTA5NTVjYTktMzE1NS00Yzc4LWFmYjctZmVlZDRiMWIwOTlkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxNjI5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzU5M2FjNDkzMjVjM2E4MWNkZjdhZmMwNzEyNWI2MTY0NjlkMzVhMTQ2ZDMzYzJmZGRmNjY3ZmMwMjI3MTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TJzhBnM6LZy22SN611AHQrTWohiLBSg4ot_wxyIGY_Y)
> 
> همچین بخشی اصلا نیست😐😂

حتما اپدیت نکردی
![image](https://github.com/alireza0/x-ui/assets/56191635/2250515a-aa60-4e4b-bd81-8bfc27f529a5)

**Comment by web-elite** [comment]
اره حل شد با این حرکت @Alley041 ❤️
