### ISSUE TITLE
افزودن دوباره انیمیشن آنلاین بودن

### ISSUE THREAD

**Issue by Hadish2001** [alireza0/x-ui#1096]
سلام خسته نباشید اگه میشه انیمیشن آنلاین بودن کاربر رو دوباره به پنل اضافه کنید خیلی کاربردی بود ولی تو نسخه جدید ریمو کردین! ممنون

**Comment by soli2413** [comment]
دقیقا.من خواستم سیستم عامل رو دوباره نصب کنما.چرا غیر فعال شده

**Comment by ErfanTech** [comment]
https://github.com/alireza0/x-ui/issues/1086

**Comment by alireza0** [comment]
درود بر شما
یکم روش کار میکنیم و احتمالا فقط انیمیشن نقطه رو اضافه کنیم.

**Comment by alireza0** [comment]
دوباره افزوده شد

**Comment by soli2413** [comment]
> دوباره افزوده شد

کار نمیکنه.اون نقطه آبی کنار نام کانفیگ خاموش روشن میشد که هنوزم کار نمیکنه.قبلا هر کسی انلاین بود چشمک میزد

**Comment by alireza0** [comment]
من هنوز نسخه جدیدی ریلیز نکردم. آیا شما از آخرین کدها به صورت دستی بیلد گرفتید ؟

**Comment by soli2413** [comment]
> من هنوز نسخه جدیدی ریلیز نکردم. آیا شما از آخرین کدها به صورت دستی بیلد گرفتید ؟

چون گفتین افزوده شد.منم به 1.8.1 اپدیت کردم.دیدم کار نمیکنه

**Comment by alireza0** [comment]
از اینکه درست بیان نکرم پوزش میخوام، من فقط به کدها افزودم.
به زودی نسخه جدید رو ریلیز میکنم و شما میتونید مشاهده کنید.
