### ISSUE TITLE
مشکل قطع و وصلی و بالا رفتن شدید پینگ

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1097]
سلام
من به طور مداوم این ارور رو روی log ها میبینم :
x-ui[699]: 2024/03/14 08:32:27 http: TLS handshake error from 127.0.0.1:45776: remote error: tls: unknown certificate

درحالی که سرتیفیکیت من فقط برای پنل هست ( اینباند بدون Cert و sub فعال نیست ) ، اما این ارور رو بعد از آپدیت به نسخه ی آخر دریافت میکنم و متاسفانه باعث میشه کانفیگ مرتب قطع شه و پینگ شدیدا بالا و پایین میشه ( چون فقط بعد از آپدیت اینجوری شده و از سالم بودن موارد دیگه اطمینان دارم )

سرتیفیکت رو هم یا Letsencrypt گرفتم و پنل هم بدون مشکل با TLS بالا میاد.

البته این ارور مربوط به پنل MHSanaei میشه ، اونجا هم Issue زدم ، ولی ممنون میشم شما هم بررسی کنید.

Mar 14 08:04:12 D2 x-ui[699]: 2024/03/14 08:04:12 http: TLS handshake error from 127.0.0.1:47394: remote error: tls: unknown certificate
Mar 14 08:04:12 D2 x-ui[699]: 2024/03/14 08:04:12 http: TLS handshake error from 127.0.0.1:47408: remote error: tls: unknown certificate
Mar 14 08:04:12 D2 x-ui[699]: 2024/03/14 08:04:12 http: TLS handshake error from 127.0.0.1:47416: remote error: tls: unknown certificate
Mar 14 08:04:12 D2 x-ui[699]: 2024/03/14 08:04:12 http: TLS handshake error from 127.0.0.1:47430: remote error: tls: unknown certificate
Mar 14 08:04:14 D2 x-ui[699]: 2024/03/14 08:04:14 http: TLS handshake error from 127.0.0.1:47440: remote error: tls: unknown certificate

یه سرور دیگه:

Mar 14 07:58:30 Kids x-ui[706]: 2024/03/14 07:58:30 http: TLS handshake error from 216.218.206.67:16016: read tcp 65.109.215.199:443->216.218.206.67:16016: read: connection reset by peer
Mar 14 07:58:31 Kids x-ui[706]: 2024/03/14 07:58:31 http: TLS handshake error from 216.218.206.67:16024: read tcp 65.109.215.199:443->216.218.206.67:16024: read: connection reset by peer
Mar 14 07:58:31 Kids x-ui[706]: 2024/03/14 07:58:31 http: TLS handshake error from 216.218.206.67:16030: read tcp 65.109.215.199:443->216.218.206.67:16030: read: connection reset by peer
Mar 14 07:58:31 Kids x-ui[706]: 2024/03/14 07:58:31 http: TLS handshake error from 216.218.206.67:16038: read tcp 65.109.215.199:443->216.218.206.67:16038: read: connection reset by peer
Mar 14 07:58:32 Kids x-ui[706]: 2024/03/14 07:58:32 http: TLS handshake error from 216.218.206.67:16044: read tcp 65.109.215.199:443->216.218.206.67:16044: read: connection reset by peer
Mar 14 07:58:32 Kids x-ui[706]: 2024/03/14 07:58:32 http: TLS handshake error from 216.218.206.67:16054: tls: client offered only unsupported versions: [302 301]
Mar 14 07:58:32 Kids x-ui[706]: 2024/03/14 07:58:32 http: TLS handshake error from 216.218.206.67:16056: read tcp 65.109.215.199:443->216.218.206.67:16056: read: connection reset by peer
Mar 14 07:58:33 Kids x-ui[706]: 2024/03/14 07:58:33 http: TLS handshake error from 216.218.206.67:16064: read tcp 65.109.215.199:443->216.218.206.67:16064: read: connection reset by peer
Mar 14 07:58:33 Kids x-ui[706]: 2024/03/14 07:58:33 http: TLS handshake error from 216.218.206.67:16078: read tcp 65.109.215.199:443->216.218.206.67:16078: read: connection reset by peer
Mar 14 07:58:33 Kids x-ui[706]: 2024/03/14 07:58:33 http: TLS handshake error from 216.218.206.67:16082: read tcp 65.109.215.199:443->216.218.206.67:16082: read: connection reset by peer

**Comment by alireza0** [comment]
درود بر شما
این خطاها در اینترنت خیلی معمولی هستن و توی پنل جزو خطاهای سطح Error دسته بندی نمیشن.
همینطور که الان موارد امنیتی رو رعایت نکردین و آدرس پنلتون در هتزنر رو به صورت شفاف گذاشتین توی یک ایشو پابلیک، باید انتظار حملات سایبری و یا فیلتر شدن رو داشته باشید.

**Comment by Alireza78na** [comment]
ممنونم از توضیحاتتون و تذکری که دادید.
راستش این سرور تست بود و همون موقع کلا خاموش و حذف شد ، ولی به هرحال باید آیپی مخفی میشد و حق با شماست.
