### ISSUE TITLE
مشکل در کدهای فرگمنت

### ISSUE THREAD

**Issue by hamedm94** [alireza0/x-ui#1098]
در به روزرسانی های اخیر پنل علیرضا متوجه شدم خروجی Json فرگمنت دیگر کار نمی کند. پس از بررسی در فایل json وقتی کروشه  [  ]  را از اول و آخر کدها حذف می کنم کانفیگ شروع به کار کردن می کند. 

![Untitled](https://github.com/alireza0/x-ui/assets/52468773/6928a350-5769-4826-89e4-14045db6b282)

مورد دوم اینکه در برنامهv2rayNG ویندوز وقتی سابسکریشن json را ایمپورت می کنیم قبلا" core type بر روی Xray تنظیم شده بود اما حالا قبل از استفاده باید دستی تغییر داده شود. به صورت پیش فرض بر روی mihomo تنظیم شده است. البته نمی دانم که این مشکل مربوط به خروجی json پنل هست یا به دلیل آپدیت برنامه v2rayNG

![Untitled](https://github.com/alireza0/x-ui/assets/52468773/45d1ec29-3d7b-42b4-ac2f-1f5e900df547)

**Comment by peyman508** [comment]
من هم همین مشکل و داشتم و درستش کردم

**Comment by peyman508** [comment]
علیرضا جان سلام.خسته نباشید.موقع اسکن تو v2rayng هم از طریق qrcode این
پیغام و میده

**Comment by alireza0** [comment]
درود بر شما
بروزرسانی کنید. و اگر از تنظیم دایرکت استفاده میکنید، مطمئن بشید که فایل‌های geo-assets هم بروز باشند

**Comment by peyman508** [comment]
درود.آخرین نسخه است.قبل از به روز رسانی پنل اوکی بود.گرینه mux که تو پنل
اضافه شد و داخل کد اومد از اون موقع اینجوری شد.الان نه میشه به صورت دستی کد
و وارد کرد و نه میشه کد و از طریق qrcode اسکن کرد.

**Comment by alireza0** [comment]
نسخه 1.8.17‌ با گرفتن json مشکل داره و mux رو درست تنظیم نمیکنه. این باگ رو توی 1.8.18 درست کردن که هنوز pre-release هستش.
میتونید بروزرسانی کنید و مشکل حل میشه

**Comment by peyman508** [comment]
به روز رسانی هم کردم.کانفیگ و هم عوض کردم اما همچنان همون خطا کد و میده.چه
به صورت کپی پیست چه به صورت اسکن کردن qr code.پنل و بازم به روز رسانی کردم
اما بازم جواب نمیده.😢

**Comment by alireza0** [comment]
@peyman508 

اگر مشکلتون با Mux هست حذفش کنید. و اگر منظور شما V2rayN بوده که باید بگم باید منتظر نسخه جدیدش باشید.
نرم افزار V2rayNG اندروید نسخه 1.8.18 هیچ مشکلی نداره با این روش.

@hamedm94 

مشکل اینه که هنوز فقط چند نرم افزار از این حالت پشتیبانی میکنن.
حالت فرگمنت بدون اطلاعات دیگه عملا فایده زیادی نداره. وگرنه نرم افزار های زیادی فرگمنت رو دارند.
ما توی این ویژگی دست پیش رو گرفتیم و باید منتظر تغییرات سمت کلاینت ها باشیم.

**Comment by peyman508** [comment]
علیرضا جان داداش اصلا کاری به mux و چیزی دیگه نداره.خطا داره روی کروشه (])
که لاین شروع هست و همچن لاین آخر و ایراد میگیره و میگه کانفینگ صحیح نیست.من
رو کد json که میزنم کپی میشه این خطا رو دارم و همچنین وقتی با qrcode اسکن
میکنم.من آخرین نسخه v2rayng و که تو github هست با ورژن 1.8.18 دانلود
کردم.اصلا تا قبل از این به روزرسانی بدون هیچ مشکلی تمام کانفیگ ها کار
میکرد.به روزرسانی آخر که mux هم اضافه شد این اتفاق افتاده.کروشه که از اول و
آخر حذف میشه اوکی میشه.پس یعنی مشکل تو کد هست نه اپلیکیشن.الان به جز من
خیلی از بچه ها این مشکل و دارن.

**Comment by alireza0** [comment]
@peyman508 

من روی چند تا سرور تست کردم همشون به راحتی با qrcode کانفیگ رو گرفتن و همه کانفیگ های ساب ها بدون مشکل گرفته میشد.
تنظیم چه با کروشه ( شامل یک یا چند تنظیم) و چه بدون اون ( فقط یک تنظیم ) به راحتی اضافه میشه.
