### ISSUE TITLE
باگ در API پنل علیرضا

### ISSUE THREAD

**Issue by hamedm94** [alireza0/x-ui#1099]
توضیح یک باگ در قسمت API
وقتی توسط API یک کلایت ساخته بشه اما مقدار ID خالی ارسال بشه کلاینت ساخته می شود اما به هیچ عنوان در پنل نه می توان آن را حذف کرد و نه می توان آن را آپدیت و مشخصات آن را تغییر داد. به طور خلاصه آن کلاینت قف می شود و هیچ عملیاتی را نیمd توان روی آن انجام داد.

خطای دریافتی هنگام حذف و آپدیت کلانت:   Error: Request failed with status code 404

**Comment by Sky-De** [comment]
@hamedm94  Before creating a new user on the server, it is important to check if their ID already exists. If there is no ID, the server should respond with an error message stating that the ID is required. Additionally, you can make the ID a required field in your schema to ensure it is always present. On the client-side, it's also a good practice to check if the ID is present before sending a request. Lastly, you can implement middleware on your server code to check if the ID exists. This ensures that the ID is always validated and present before creating a new user.

**Comment by alireza0** [comment]
This problem was introduced and fixed in last version only for UPDATE scenario.
Actually this panel has minimum data verification and rely on data verification from Admin side.

First you should know that with API, you can fix it by Update Inbound API.
I will add same check for Add Client as well.

**Comment by alireza0** [comment]
What do you mean by update part?
