### ISSUE TITLE
Check Client Connect Status

### ISSUE THREAD

**Issue by DarkZo0m** [alireza0/x-ui#110]
Salam Age Beshe Ye Navar Kenar Client Ezafe Beshe Ke Betone Vaziat Etesalesho Neshon Bede Ke Motesel Hastesh Ya Kheir Toye Update Haye Beaadi Ke Awli Mishe

**Comment by alireza0** [comment]
درود بر شما
اتصالات proxy کاملا stateless هستند. وضعیت اتصال قابل رویت نیست.
از روی لاگ میشه فهمید که بسته ای فرستاده یا نه، ولی اول اینکه الزاما دلیل اتصال نیست، و دوم اینکه این کار مستلزم آپدیت شدن خودکار صفحه است و باعث سنگین شدن پنل میشه.
