### ISSUE TITLE
اتصال مستقیم کشور

### ISSUE THREAD

**Issue by soli2413** [alireza0/x-ui#1100]
کاربرد اتصال مستقیم کشور در قسمت ساب جیسون چی هست؟

**Comment by Dwnill** [comment]
وقتی لینک ساب جیسون بدی به کاربرت بخش دایرکت کانتری یا همون اتصال مستقیم فعال باشه 
سایت ها و دامنه های ایران رو با ایپی خود کاربر باز میکنه 
مثل همراه بانک …. اینا 
قبلا این بخش داخل خود نرم افزار ها بود داخل مسیریابی … حالا میتونی داخل فایل جیسون بذاری تحویل بدی

**Comment by soli2413** [comment]
بروزرسانی ساب میزنم داخل برنامه خطا میزنه

**Comment by soli2413** [comment]
![Screenshot_20240315-001039_1](https://github.com/alireza0/x-ui/assets/162466292/20ee55e6-7238-4e1c-83b9-88a53a27f610)

**Comment by Dwnill** [comment]
> ![Screenshot_20240315-001039_1](https://private-user-images.githubusercontent.com/162466292/312989801-20ee55e6-7238-4e1c-83b9-88a53a27f610.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODEwMTYsIm5iZiI6MTcxMDQ4MDcxNiwicGF0aCI6Ii8xNjI0NjYyOTIvMzEyOTg5ODAxLTIwZWU1NWU2LTcyMzgtNGUxYy04M2I5LTg4YTUzYTI3ZjYxMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQwNTMxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDQ3ODc0ZjdjZmUyZmI2NmVlZjY3Y2EyYzhmMWIwMjlmZDkyOGM0MjhmYjQ4NmZkZjgxOGFlMTZjYTYxN2E0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jRNRiDQLHIS5dRfk0HGovaBflwrgbgBMsr06Q-mX8rs)

این بخش رو میگن نباید خالی بذاری منم فعلا تست نکردم تست کن میگن اوکی میشه
![178C8807-C0B1-4A3D-93EF-4D70337AA3DC](https://github.com/alireza0/x-ui/assets/40546776/5c74af01-7d14-4ab9-97b8-e883b0f0394e)

**Comment by naserchaman2138** [comment]
> > ![اسکرین شات_20240315-001039_1](https://private-user-images.githubusercontent.com/162466292/312989801-20ee55e6-7238-4e1c-83b9-88a53a27f610.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODEwMTYsIm5iZiI6MTcxMDQ4MDcxNiwicGF0aCI6Ii8xNjI0NjYyOTIvMzEyOTg5ODAxLTIwZWU1NWU2LTcyMzgtNGUxYy04M2I5LTg4YTUzYTI3ZjYxMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQwNTMxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDQ3ODc0ZjdjZmUyZmI2NmVlZjY3Y2EyYzhmMWIwMjlmZDkyOGM0MjhmYjQ4NmZkZjgxOGFlMTZjYTYxN2E0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jRNRiDQLHIS5dRfk0HGovaBflwrgbgBMsr06Q-mX8rs)
> 
> این بخش رو میگن نباید خالی بذاری منم فعلا تست نکردم تست کن میگن اوکی میشه ![178C8807-C0B1-4A3D-93EF-4D70337AA3DC](https://private-user-images.githubusercontent.com/40546776/313078672-5c74af01-7d14-4ab9-97b8-e883b0f0394e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDYzMDAsIm5iZiI6MTcxMDU0NjAwMCwicGF0aCI6Ii80MDU0Njc3Ni8zMTMwNzg2NzItNWM3NGFmMDEtN2QxNC00YWI5LTk3YjgtZTg4M2IwZjAzOTRlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQyMzQwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzBjZWY3ZTg3MjY0ZGU2ZjQxMTI1ZGRhMGZlNDM0ODI1ZDdmNGRiZDJmYmEzNmEyZDIwYjU2MGZmNmNkMDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rAYUy2qRXqanr4du7EOwP8HGJQbXTOVORhHpPrUSV2o)

**Comment by naserchaman2138** [comment]
سلام منم مشکل داشتم الان اکی شد
