### ISSUE TITLE
فایل yaml به جای Json در فرگمنت

### ISSUE THREAD

**Issue by hamedm94** [alireza0/x-ui#1101]
چرا پنل در قسمت سابسکریپت فرگمنت، کانفیگ با فایل .Yaml میده به جای Json. ؟

قبلا خروجی Json بود بعد از آپدیتهای اخیر فقط  با پسوند yaml فایل فرگمنت رو طرف کاربر آپدیت می کنه. مشکل از تنظیمات بنده هست یا مشکلی پیش اومده؟

**Comment by alireza0** [comment]
سابسکریپشن جدید میتونه با یک لینک تعدادی کانفیگ json ارسال کنه.
این ویژگی با V2rayN که هنوز فقط یک کانفیگ میتونه بگیره تداخل داره.
ولی استاندارد همینه و فقط همون نرم افزار مشکل تفسیرش رو داره.
لطفا از سمت نرم افزار کلاینت پی گیری کنید.

**Comment by siamakmu** [comment]
سلام وقت بخیر.
برای ویندوز نرم افزاری هست که از این قابلیت پشتیبانی کنه؟
