### ISSUE TITLE
گزارش مشکل در اتصال پنل به پنل   

### ISSUE THREAD

**Issue by ghost** [alireza0/x-ui#1104]
سلام خسته نباشید نمی دونم این باگ هست یا خیر امیدوارم وتی جسارت خطاب نکنید فقط تجربه کاربری هست گفتم با شما به اشتراک بگذارم 

1-در تانل پنل به پنل وقتی از QUIC و mKCP و grpc استفاده می کنم هسته xray درست سر دو دقیقه متوقف و بعد از 5 ثانیه روشن میشه
  آیا این موضوع دلیل خاصی دارد ؟

**Comment by alireza0** [comment]
درود بر شما
لطفا شواهد کافی مانند لاگ و تنظیمات رو بفرستید.
