### ISSUE TITLE
Subscription update not working after upgrading from 1.7.2 to 1.8.0

### ISSUE THREAD

**Issue by PatrickstarWritesCode** [alireza0/x-ui#1105]
Subscription updates on client devices fail on v1.8.0, client log reports that server has reported error code 500. I've tested this on V2RAYNG and V2RAYN. Reverting to 1.7.2 resolves the issue.

Can't find any relevant logs on this, Maybe I'm not looking at the right place, any ideas?

My other server on 1.8.0 is working fine.

**Comment by alireza0** [comment]
Please always provide logs and relevant evidences.
It works fine on all of my tests! To find the problem, I have to know in wich situation it may happen.

**Comment by MH140000** [comment]
I have this problem. I test on many servers but doesn't work

**Comment by PatrickstarWritesCode** [comment]
> Please always provide logs and relevant evidences. It works fine on all of my tests! To find the problem, I have to know in wich situation it may happen.

Problem is I can't find any relevant logs on the issue:

Server is running as error 500 suggests and the log is:
Mar 17 20:33:22 X-UI_SERVER /usr/local/x-ui/x-ui[17779]: INFO - X-UI: sub server run https on 127.0.0.2:443

Client error:
X-UI_SERVER ->Response status code does not indicate success: 500 (Internal Server Error).
X-UI_SERVER->The remote server returned an error: (500) Internal Server Error.
X-UI_SERVER->The remote server returned an error: (500) Internal Server Error.
X-UI_SERVER->Invalid subscription content

**Comment by alireza0** [comment]
Please provide me your configuration of the inbound/user which you tied to fetch the reated sub.

**Comment by PatrickstarWritesCode** [comment]
> Please provide me your configuration of the inbound/user which you tied to fetch the reated sub.

This is extracted configuration from V2RAYN export
```
{
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "domain.name",
            "port": 443,
            "users": [
              {
                "id": "33d9cbd0-d629-4ff0-ab94-ad48e63ee417",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "grpc",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "sni.redacted",
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "fingerprint": "chrome",
          "show": false
        },
        "grpcSettings": {
          "serviceName": "service.name.redacted",
          "multiMode": true,
          "idle_timeout": 60,
          "health_check_timeout": 20,
          "permit_without_stream": false,
          "initial_windows_size": 0
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    }
```

**Comment by alireza0** [comment]
The problem is in GRPC authority filed which is added in new Xray-core 1.8.9.
It is mandatory to fill it out.

**Comment by PatrickstarWritesCode** [comment]
This solved the problem, for some reason the other server had no issues with this field being empty.

Thanks

**Comment by PatrickstarWritesCode** [comment]
Closing this
