### ISSUE TITLE
tg bot in iran panel

### ISSUE THREAD

**Issue by Ali48311** [alireza0/x-ui#1106]
با توجه به راهنمایی های علیرضای عزیز روی سرور ایران یه کانفیگ dokodemo-door ساختم و ترافیک هم اپلود میکنه اما همچنان ربات تلگرام کار نمیده

![dokodemo-door](https://github.com/alireza0/x-ui/assets/144976267/da563fb9-a325-4f47-8c8d-e06c19bce6f6)

در سرور ایران سایت api.telegram.org رو هم بصورت دستی تغییر دادم با این دستور 
`echo "127.0.0.43 api.telegram.org" >> /etc/hosts`

![image](https://github.com/alireza0/x-ui/assets/144976267/58ef43f0-0a3c-41e4-96b7-753811b3837b)
جالبه برام که ترافیک هم ازش رد شده
کسی ایده ای داره مشکل از کجا میتونه باشه؟

**Comment by alireza0** [comment]
باید دقت کنید آیا خروجی این اینباند درست تنظیم شده باشه.
بهتره قبل از ایجاد ایشو، در ایشو های قبل جستجو کنید #957

**Comment by Ali48311** [comment]
بله عذر میخوام 
مرسی از راهنماییتون ❤️
