### ISSUE TITLE
[BUG] URI convrter

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#1107]
Hi @alireza0 .
I found some bugs for you to work with in your free time.

1 - URI Converter is working fine with vmess and vless but fails on ShadowSocks.
you can test with this:
```link
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp1MTdUM0J2cFlhYWl1VzJj@serial.com:443#fgg
```

2 - The Converted Port is String. although I believe it will be fixed when inserted into xray config, but it is better to have it as int16 from start.

**Comment by alireza0** [comment]
Hello @X-Oracle 

Thank you for your feedback.
Actually it assumes that you will provide at least a `type` in QueryStrings. I don't know if any link provider will provide you a pure link like this. If so, It should takes care of absense of this mandatory parameter.
Port will be also an interger in existing coverting process.

You should try this link:

```
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp1MTdUM0J2cFlhYWl1VzJj@serial.com:443#fgg
```

**Comment by X-Oracle** [comment]
Hi @alireza0 .

> Actually it assumes that you will provide at least a `type` in QueryStrings. I don't know if any link provider will provide you a pure link like this. If so, It should takes care of absense of this mandatory parameter.

I understand about the type but I copied the ss link from a reliable source which updates regularly and it works fine in v2rayNG.

And the link I provided to you was actually copied from v2rayNG. So even v2rayNG doesn't provide a default value for ss type. So I think we could have default or empty value instead of giving invalid ss link.


> Port will be also an interger in existing coverting process.

I don't know about ss URIs since I couldn't try it .

The related problem was about vmess URIs.
It seems it is not a problem in vless.

isn't it better to convert it to int regardless of the previous type ?

What is mean is :
Int -> int
String -> int

**Comment by X-Oracle** [comment]
Hi @alireza0 .

> Actually it assumes that you will provide at least a `type` in QueryStrings. I don't know if any link provider will provide you a pure link like this. If so, It should takes care of absense of this mandatory parameter.

I understand about the type but I copied the ss link from a reliable source which updates regularly and it works fine in v2rayNG.

And the link I provided to you was actually copied from v2rayNG. So even v2rayNG doesn't provide a default value for ss type. So I think we could have default or empty value instead of giving invalid ss link.


> Port will be also an interger in existing coverting process.

I don't know about ss URIs since I couldn't try it .

The related problem was about vmess URIs.
It seems it is not a problem in vless.

isn't it better to convert it to int regardless of the previous type ?

What is mean is :
Int -> int
String -> int

**Comment by X-Oracle** [comment]
And I think the converter tool is a great feature and it is a waste to only have it in outbound settings.

Isn't it a good idea to have "Tools" section which provides standalone version of these?

The online tools are not reliable or not complete.

**Comment by alireza0** [comment]
Regarding Vmess link, I assume that correct encoded json should be passed to the script.

I will 
1- convert vmess port to number
2- fix ss link to assume type=tcp if it is not present.

Regarding tool, I could add new tool in github.io we pages.
