### ISSUE TITLE
  نشان ندادن افراد آنلاین در اپدیت جدید (مرورگر گوشی)

### ISSUE THREAD

**Issue by navid221** [alireza0/x-ui#1108]
سلام وقت بخیر. در اپدیت جدید وقتی با گوشی وارد پنل میشم کنار اسم کاربرها چراغ انلاین بودن انها چشمک نمیزند در حالی که افراد زیادی انلاین هستن لطفا بررسی فرمایید. تشکر از زحمات شما

**Comment by alireza0** [comment]
#1086
