### ISSUE TITLE
تفاوت محیط وب در دو سرور

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#111]
با سلام و ممنون بابت پنل زیبا و کاربردیتون
من رو دو سرور نصب کردم ولی تو دو تا محیط کلا رنگ و لعاب تفاوت فاحش دارن علت از چی میتونه باشه؟

**Comment by aliamg1356** [comment]
![11](https://user-images.githubusercontent.com/124570423/228077707-a924ddc8-a2a9-4fc2-a409-97b83715bf80.jpg)
![12](https://user-images.githubusercontent.com/124570423/228077717-22213779-9906-486e-9792-daf556aa5d1e.jpg)

**Comment by alireza0** [comment]
درود بر شما
این مشکل میتونه مربوط به مرورگر باشه و پاک نشدن اطلاعات صفحه لاگین و استفاده از اون توی صفحه های بعدی.
لطفا hard-refresh کنید
