### ISSUE TITLE
باگ امنیتی

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1113]
سلام و وقت بخیر
یگ باگ امنیتی پیدا شده روی پنل ، هم پنل شما و هم سنایی و مرزبان و ... ، لطفا چک میکنید ببینید چطور میشه حلش کرد؟
این باگو من پیدا نکردم ، فقط دیدم درموردش صحبت میکنن ، خواستم اینجا بهتون اطلاع بدم که بررسی کنید ، ممنون از شما

https://en.fofa.info/result?qbase64=Ym9keV9oYXNoPSIxOTUzMTU2OTg5Ig%3D%3D

اینطور که من متوجه شدم ، باگ اینه که listen باید روی 127.0.0.1 باشه که روی 0.0.0.0 هست که باعث میشه به راحتی با یهKeyword پنل ها و ایپیشونو شناسایی کرد.

**Comment by Alireza78na** [comment]
https://twitter.com/Nima__Nikjoo/status/1770167097361932487?t=ihyGJgUP7fHuSdoahJLFzw&s=19

لینک توییتر

**Comment by alireza0** [comment]
درود بر شما
روز شما هم به شادی

مشکل این متخصصین تازه کار اینه که تفاوت امنیت سرور و امنیت ارتباط با نرم افزار رو نمیدونن.
و امنیت کد از هردو اینها جداست. ولی خب اینها برای اهداف شخصی با استفاده از ضعف دانش مردم غیر متخصص منتشر میشن.

برای اینکه شناسایی سرور توسط اسکنر ها سخت تر بشه (دقت کنید: سخت تر و نه غیر ممکن)، از نسخه های اولیه x-ui، امکان تعریف مسیر پیش فرض پنل وجود داشته و ما خیلی بعد از اون شروع به توسعه کردیم. پس این امکان از اول بوده و اینکه کاربران دانسته و یا نادانسته ازش استفاده نمیکنن، مشکل پنل نیست!

نکته اصلی اینه که این امکانات امنیتی وجود داره تا کاربر بتونه سرور رو ( و نه پنل رو ) امن کنه. اینکه پنل امن نیست گزاره اشتباهیه.
امنیت سرور و ارتباط با نرم افزار به عهده خود استفاده کننده است.
نرم افزار باید امکان فقط امن کردن رو ارائه بده و امنیت کد رو داشته باشه. و اگر هم نداشته باشه، باز هم وظیفه ادمین اینه که از حملات جلوگیری بشه.

راه های امن کردن سرور بسیار زیاد هستند و بستگی به استفاده کاربر داره. بهتره قبل از هر صحبتی در موردش بیشتر بدونیم.
به عنوان نمونه، پخش کردن این لینک هایی که شما اینجا در یک رپو عمومی و پر بازدید گذاشتید، به شدت غیر امن هست و به اهداف توزیع کننده کمک کردید.
