### ISSUE TITLE
[BUG] logs

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#1114]
Hi @alireza0 

Some times x-ray core doesn't have a proper error handling in some sections , especially if threr is a new feature implanted.

Logs only report the x-ray and x-ui standard logs but it won't record exception and exception tracebacks so I'm forced to run the config manually to ses errors and report them.

X-ui seems to catch it when exception occurres but it only display the final message and only when hovered on x-ray button in main menu.

So I think you could add x-ray exception tracebacks to logs when it occurs.

Think about it in your free time.

Best of luck.

**Comment by alireza0** [comment]
All the outputs of xray will be captured and writing as log.
But exit error which almost always is "exit code 23" could not be in logs. I have added it as detected X-UI logs.

**Comment by X-Oracle** [comment]
Hi @alireza0 

Thanks for the commit and reply. 

I have a question.

Will it capture the error tracebacks as well ?
Since sometimes It is an unhandle error and we need error traceback to report it.

**Comment by alireza0** [comment]
It depends!
The `xray-core` will write the error ( and access ) to `stdout` if it is not defined to write it in a file in log configuration.
All `stdout` logs will be captured by `x-ui` including tracebacks.
If these tracebacks are not in output, it is not possible to see it in `OS` or caller app like `x-ui` as well.
The only remaining part was about an error which returns from exitted app, will be captured by this commit.

**Comment by X-Oracle** [comment]
I understand.
Thanks for reply.🙏
