### ISSUE TITLE
استفاده از فرگمنت با دامین مسدود در اکسترنال پروکسی

### ISSUE THREAD

**Issue by analysisgen** [alireza0/x-ui#1115]
سلام وقتتون بخیر و عیدتون مبارک

من یه دامین داشتم که مسدودش کردن و کانفیگ هایی که داشتم از کار افتاد برای چند نفر ولی خودم بعد چند ساعت تونستم بهشون وصل بشم ولی اون چند نفر دیگه نه

من از vless ws tls استفاده کردم و اکسترنال پروکسی تعریف کرده بودم با ساب دامین همون دامین مسدود و ای پی تمیز کلود هم بود پشت دامین ها.

و ساب دامین هام همشون تیک پروکسی روشن داخل کلود رو دارن

الان وقتی ای پی تنها میذارم همه وصل میشن ولی خودم با همون ساب دامین ها هم میتونم وصل بشم.

1)میخواستم بدونم ایا فرگمنت روی اکسترنال پروکسی اثر گذاره ؟ و ساب دامین های اکسترنال پروکسی رو هم فرگمنت میکنه؟

2)و اگر نمیکنه ایا راهی هست که فرگمنت روی اکسترنال پروکسی هم اثر بذاره؟ و نمیشه به پنل اضافه کرد؟

3)و اینکه دلیل اینکه من با همون ساب دامین ها میتونم وصل بشم چیه؟

4)و اگر من با یه دامین سالم دیگه بیام ساب دامین و ای پی تمیز تعریف بکنم و اون ها رو بذارم توی اکسترنال پروکسی دامین مسدود بازم احتمال مسدود شدن دامین سالم هست؟ 

(من به خاطر این دارم این موضو رو مطرح میکنم که کاری با مسدود شدن ای پی ندارم و میخوام دامینی که ساب دامین میگیرم ازش برای ای پی تمیز های اکسترنال پروکسی ،دامینش رو مسدود نکنن)

(و یه چیزی فهمیدم وقتی شما یه vpn ssh معمولی بدون تی ال اس میزنید و ترافیک https یا http نمیشه که از داخل دامین رد بشه. (پورت اتصال کاربر ها مثلا 8888 یا 54345 باشه) به این دلایل چون میتونن ای پی رو بزنن کاری با دامین ندارن و کاربر ها انگار ترافیکشون دامین رو تاچ میکنه فقط و ترافیک ازش رد نمیشه انگار.(

میخواستم با این چیزایی که مطرح کردم منو راهنمایی کنید.

ممنون

**Comment by alireza0** [comment]
درود بر شما
نوروز شما هم خجسته

فرگمنت روی اولین پکت ها تاثیر میذاره، هر دامینی که کاربر باهاش داره ارتباط میگیره ( دامین external proxy توسط کاربر استفاده میشه )
برای اتصال به دامنه اول باید توسط DNS تبدیل به IP بشه. دامین های فیلتر شده، به آدرس اشتباهی تبدیل میشن.
اگر روی کلاینت شما هنوز کار میکنه، دلیلش اینه که سرور DNS شما اون آدرس رو درست تبدیل میکنه.
امکان فیلتر شدن دامنه و IP همیشه هست، مهم اینه که روش استتارتون اونقدر قوی باشه که دیرتر شناخته بشن.

**Comment by analysisgen** [comment]
@alireza0 
منظورتون رو دقیق نفهمیدم ما الان دو تا ساب دامین داریم مثلا s2.shopp.com , s1.shopp.com  که به یکیش ادرس اصلی سرور و پنلمون وصله که s1 باشه و s2 روی اکستنرنال پروکسی ثبت شده و پشتش ای پی تمیزه .
حالا اینجا ما دامین اصلیمون فیلتر میشه ولی فرگمنت با کد هایی که الان هست که میان فرگمنت سازی رو انجام میدن فقط روی ساب دامین s1 اثر میذاره و اینو تست کردم ولی روی s2 اثر نمیذاره و حتما باید از دامین تیز یا ای پی تمیز استفاده کرد

حالا میخواستم بدونم راهی هست که روی s2 یا دامین هایی که روی اکسترنال پروکسی ست میشن فرگمنت سازی رو انجام داد یا خیر؟مثلا با اجرای rule routing در کد json؟ و یه دامین یا ip مسدود شده متصل شد در اکسترنال پروکسی؟

و یه سوال دیگه هم داشتم اگر از یه دامین تمیز دیگه مثلا s1.shopp2.com بیایم فقط و فقط توی اکسترنال پروکسی که کاربر میخواد متصل بشه استفاده کنیم و از دامین مسدود شده s1.shopp.com برای دامین اصلی سرور و ای پی اصلیمون استفاده کنیم، باز هم ممکنه دامین  shopp2.com رو مسدود کنن؟حتی اگر zero trust و ... روش انجام بدیم؟

چون من الان دقیق نمیدونم ترافیک کاربر از اکسترنال پروکسی رد میشه یا فقط از دامین اصلی سرورمون رد میشه

**Comment by alireza0** [comment]
در مورد وریسش نخست:‌ مفاهیم فرگمنت، پراکسی و قوانین مسیریابی در جاهای متفاوتی اعمال میشن و نمیشه به راحتی به هم ارتباط داد.
فرگمنت روی ارتباط اولیه کاربر تا هسته تاثیر میذاره و ربطی به دامنه های متفاوت نداره.
تنظیماتتون رو باید عوض کنید و تست کنید، چون آدرس تمیز با/بدون فرگمنت متصل میشه همیشه!

سوال دوم در مورد نحوه فیلتر شدن دامنه است که من در موردش داده کافی ندارم.

**Comment by analysisgen** [comment]
@alireza0 
احتمال مسدود شدن ای پی تمیز نیست؟
من میخوام جای ای پی تمیز در اکسترنال پروکسی ساب دامین قرار بدم که بتونم اگر ای پی تمیز رو زدن از سمت خودم ای پی رو عوض کنم و مجبور به تغییری از سمت کاربر نباشه . یعنی میگید من اگر تنظیمات رو تغییر بدم میشه با دامین مسدود شده در بخش اکسترنال پروکسی بازم میشه متصل شد؟
حالا به توجه به چالشی که دارم شما پیشنهاد خاصی دارید؟

**Comment by alireza0** [comment]
بله، استفاده از دامنه به همین دلیله که اگر IP فیلتر شده بشه عوضش کرد.
استفاده از فرگمنت هم بیشتر برای دامنه فیلتر شده است و نه IP فیلتر شده.

**Comment by analysisgen** [comment]
@alireza0 
توی جواب هایی که دادید متوجه نشدم دامین تمیزی که در بخش اکسترنال پروکسی (جای ای پی تمیز استفاده میشه) باز هم ممکنه فیلتر بشه؟
