### ISSUE TITLE
نحوه صحیح استفاده از استراتژی «لیست لود» در بالانسر

### ISSUE THREAD

**Issue by PatrickstarWritesCode** [alireza0/x-ui#1116]
متاسفانه پس از خوندن issueها و discussionها در گیت‌هاب xray core و همچنین گشتن داخل داکیومنتیشن نحوه کارکرد دقیق استراتژی جدید leastload در کنار observatory و burstobservatory رو متوجه نشدم.

کسی می‌تونه کمک کنه؟

**Comment by PatrickstarWritesCode** [comment]
[این ایشو](https://github-com.translate.goog/XTLS/Xray-core/pull/2999?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp) اطلاعات خوبی داره ولی یسری پارامترها مثل baseline و cost رو توضیح نداده.

**Comment by PatrickstarWritesCode** [comment]
[این](https://github-com.translate.goog/v2fly/v2ray-core/pull/589?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp) هم خوبه

**Comment by alireza0** [comment]
هسته در مدت زمان های مشخص شده، ارتباط با یک url رو چک میکنه و بر اساس اون، اطلاعات لازم برای استفاده لودبالانسر رو تامین میکنه.

**Comment by PatrickstarWritesCode** [comment]
متوجه شدم که observatory همراه leastPing و burstObservatory همراه leastLoad باید استفاده شه. فرق این‌ها رو [اینجا ](https://github-com.translate.goog/XTLS/Xray-core/discussions/3138?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)فهمیدم. بعدش متوجه شدم که `[اینجا ](https://github-com.translate.goog/XTLS/Xray-core/pull/2999?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)`هم بطور ضمنی این مورد اشاره شده.

**Comment by PatrickstarWritesCode** [comment]
بهتر هست که صبر کنیم نسخه جدید release بشه ظاهرا یکسری مشکلات داره که در آخرین بیلدها حل شده ولی release نشده
