### ISSUE TITLE
IP approval for panel access through Telegram

### ISSUE THREAD

**Issue by armin567ip** [alireza0/x-ui#1117]
No, Not related to a problem

This is just a security feature for Telegram bot.
I think it would be great if the server administrator could insert his/her IP address through Telegram bot every time he/she wants to login to the panel, So that the panel port will only accept that IP address. So that the panel port is not always open to public.

**Comment by alireza0** [comment]
It may cause a problem in combination with external proxies.
This panel is not such a security base software to have these kind of complexity.
Lots of solutions could be implemented by the Admin which are more secure than this method.
