### ISSUE TITLE
Small enhancement in json sub

### ISSUE THREAD

**Issue by AliBelali** [alireza0/x-ui#1118]
Dear Alireza,

Thank you for your dedicated work. I'd like to address a couple of points regarding the configuration:

1. **Geosite in Sub JSON Format**:
   Most v2ray clients lack a robust domain name database and often have better coverage of IP addresses. Additionally, many clients do not support the "geosite:**category-**" format, rendering the JSON config unusable in certain applications. To enhance compatibility, I recommend either removing the "geosite" section from the sub JSON format or making it optional.

2. **GeoIP Database with "IPIfNonMatch"**:
   The GeoIP database plays a crucial role in ensuring reliable IP handling. By setting "IPIfNonMatch", as configured in [this location](https://github.com/alireza0/x-ui/blob/03dd392a39e3a4cb3d981539df972e6e19cdd8f0/sub/default.json#L77), you've taken a step toward improving IP multi routing accuracy.

Once again, thank you for your efforts, and I appreciate your attention to these details.

Best regards

**Comment by alireza0** [comment]
Dear @AliBelali ,

Thank you for your comment and exposing your opinion.
Actually, this service is quite new and I am waiting for all these recommendations which are based on field practices.
Also, it is important to wait for other client applications to support this new method of subscription.

Although it is true that we could have a lot of enhancements, but waiting for other apps is more important for me.
