### ISSUE TITLE
مشکل نبود گزینه ی IP Limit

### ISSUE THREAD

**Issue by aref-abdemohammadi** [alireza0/x-ui#1119]
![Screenshot (101)](https://github.com/alireza0/x-ui/assets/24923643/a395ef78-eded-49d4-9510-4c18992a44a4)
همانطور که در تصویر مشاهده میکنید در قسمت Client  گزینه ای به اسم ip limit وجود ندارد که بتونیم محدودیت کاربر برای گانفیگ ایجاد کنیم 
بعد از ایجاد کانفیگ هم توی بخش add client همچین گزینه ای نمیاد 
من چند ورژن دیگه هم تست کردم و اونجا هم همچین گزینه ای برام نمیومد 
الان چطور میتونم برای یک کانفیگ محدودیت کاربر بزارم ؟

**Comment by wulfric93** [comment]
کلا پنل علیرضا از این قابلیت پشتیبانی نمیکنه

**Comment by aref-abdemohammadi** [comment]
تشکر ❤️
