### ISSUE TITLE
نمایش کاربران کانکشنهای هم نوع

### ISSUE THREAD

**Issue by rbakhshi72** [alireza0/x-ui#112]
سلام، وقتی که ما دوتا کانکشن مثلاً از نوع تروجان داشته باشیم که یکی از نوع TCP و دیگری از نوع GRPC باشه،زمانی که روی مثلاً روی کانکشن تروجان TCP هم کلیک میکنیم، لیست کاربرهای کانکشن تروجان GRPC هم به ما به ترتیب ساخته شدن در میان هر دو کانکشن نمایش داده میشه ولی به نظرم فقط باید کاربرهای همون کانکشنی که من رویشون کلیک کردم رو نشون بده. حتی اگه مه چیزشون یک سان باشه و پروتشون متفاوت باشه.
  آیا این مسأله قابل حل است؟

**Comment by alireza0** [comment]
این مشکل رو کجا دیدید؟
