### ISSUE TITLE
آپدیت بکاپ  از دیتابیس

### ISSUE THREAD

**Issue by solidwar** [alireza0/x-ui#1120]
سلام عرض شد جناب مهندس . امیدوارم سال جدید به خوبی و خوشی و بدون ناراحتی بگذره براتون
- یک موردی که جدیدا مهم هست اینه که ممکنه هزار و یک اتفاق برای دیتابیس بیوفته و بکاپی که داشته باشیم هم شاید خراب شده باشه. حالا اگر که بشه برای هر اینباند بکاپ خودکار در نظر گرفت بسیار عالی میشه . و خب به نظرم 99 درصد استفاده کننده ها دارن از یک پورت در پنل استفاده میکنن که از این ویژگی خیلی ها میتونن استفاده کنن

**Comment by wulfric93** [comment]
ایده خوبی هست 
البته اگر عملی باشه که تصمیم گیرنده علیرضا جان هستن

**Comment by alireza0** [comment]
درود بر شما
نوروز شما هم خجسته و شاد

برای بکاپ گرفتن فقط دیتابیس رو به صورت فایل انتقال میدیم.
اگر قرار باشه اتفاقی براش بیافته، بسیار نادره. پیشنهاد میکنم بکاپ رو از طریق تنظیم تلگرام داشته باشید که هرچندوقت یکبار این کار رو براتون انجام بده.

برای پشتیبان گرفتن از هر اینباند میتونید از کپی اینباند استفاده کنید و اون رو توی یک فایل متنی ذخیره کنید.
