### ISSUE TITLE
اپدیت کلاینت تروجان از طریق api  در پنل xui

### ISSUE THREAD

**Issue by zifulx** [alireza0/x-ui#1123]
درود 
سال نو مبارک
من از طریق api یک پنل مدیریتی برای پنلای خودم ساختم منتهی توی اپدیت کلاینت تروجان مشکل دارم،همونطور ک خودتون و اقای سنایی توی داکیومنت گفتید  از پسوورد بجای ایدی در  اپدیت کلاینت تروجان استفاده میکنیم اما همچنان با خطا مواجه میشیم،هرجور تلاش کردیم به نتیجه نرسیدیم حس میکنم یک باگی داره اولش برای اقای سنایی گیت گذاشتم حتی ایمیل هم زدم اما متاسفانه جواب ندادن وقتی دیدم شما جواب دوستان رو توی گیتهاب میدین امیدوار شدم شاید شما  کمکم کنید،  واقعا ممنون میشم اگر منو بتونید راهنمایی کنید من لاگ رو هم براتون به اشتراک میزارم:
{
"success": false,
"msg": "Something went wrong! Failed: empty client ID\n",
"obj": null
}

**Comment by alireza0** [comment]
درود بر شما
نورزتان شاد

برای اینکه آپدیت کلاینت باید پارامتر آی‌دی رو توی مسیر درخواست بذارید:
```
POST /xui/API/inbounds/updateClient/<clientId>
```

به دلیل اینکه ممکنه این پسورد شامل کاراکتر های خاص باشه، بهتره اون رو با urlencode تبدیل به رشته مناسب کنید.
