### ISSUE TITLE
X-ui for windows server

### ISSUE THREAD

**Issue by mmdjvdad** [alireza0/x-ui#1124]
سلام مهندس اگه راه داره برای ویندوز سرور هم یه ریلیز بدین. دو تا نسخه تو گیتهاب هست ولی ورژن ایکس ری قدیمیه و اپدیت نمیشن

**Comment by mmdjvdad** [comment]
ممنون عزیزم همین رو عرض کردم قدیمی هست ریلیتی نداره

**Comment by Dwnill** [comment]
> ممنون عزیزم همین رو عرض کردم قدیمی هست ریلیتی نداره

how to compile form source :
download mingw[w64devkit] and extract to C:\
add "C:\w64devkit\bin" to path
download and install Go 1.19.3
add "C:\Program Files\Go\bin" to path
download and extract xui-windows source
cd to xui-windows directory and run :
go build -o main.exe main.go
rename main.exe to xui-main.exe

شما مواردی که گفته رو نصب کنی میتونی باهاش پروژه های سنایی و علیرضا رو کامپایل کنی

**Comment by mmdjvdad** [comment]
ممنون به این دقت نکرده بودم. یه چک میکنم

**Comment by mmdjvdad** [comment]
بزرگوار ساخته شد ولی اجرا نمیشه. این کاربزرگانه کار ما نیست...

**Comment by mmdjvdad** [comment]
> > ممنون عزیزم همین رو عرض کردم قدیمی هست ریلیتی نداره
> 
> how to compile form source : download mingw[w64devkit] and extract to C: add "C:\w64devkit\bin" to path download and install Go 1.19.3 add "C:\Program Files\Go\bin" to path download and extract xui-windows source cd to xui-windows directory and run : go build -o main.exe main.go rename main.exe to xui-main.exe
> 
> شما مواردی که گفته رو نصب کنی میتونی باهاش پروژه های سنایی و علیرضا رو کامپایل کنی

شما تونستی این کارو کنی؟

**Comment by mmdjvdad** [comment]
> پنل 3x-ui نسخه ویندوزی داده اخیرا. یه امتحانی بکن. علیرضا هم جزو همکاران اون پنله و امکانات مشابهی دارن.

ممنونم
