### ISSUE TITLE
wireguard end point for local 

### ISSUE THREAD

**Issue by The13east** [alireza0/x-ui#1125]
سلام اقا علیرضا 
من دارم پنل رو برای وصل شدن به شبکه داخلی خودم استفاده میکنم ! و مشکلی که دارم اینه وایرگارد شما و دوستان دیگه امکان گذاشتن دامنه به صورت دستی رو نداره ! الان من با استفاده از qr یا کپی کردن کد بخوام کانفیگ ببرم ای پی local توی کانفیگ هست و qr هم عملا غیر قابل استفاده هست ! 
میشه پنل رو روی اینترنت گذاشت و با همون دامنه وارد شد ولی خب هر پورت که باز میشه برای شبکه ریسکه ! اگر یه دکمه مثل external proxy بقیه پروتکل ها توی وایرگارد بزارید عالی میشه !

**Comment by alireza0** [comment]
درود بر شما
پروتکل وایرگارد ویژگی های لازم برای external proxy رو نداره. بهتره پنل رو با اسم اصلی خودش باز کنید.

**Comment by alireza0** [comment]
میتونید با تعریف دامنه در hosts سیستم عامل اون رو برای خودتون تغییر بدید.
