### ISSUE TITLE
پنل سنایی

### ISSUE THREAD

**Issue by mrafieefard** [alireza0/x-ui#1129]
چه اتفاقی برای پنل سنایی افتاده چرا کلا اکانتشون نیست آیا قراره همین اتفاق برای همین پنل بیوفته؟

**Comment by mmdh-ir** [comment]
بله منم همین سوالو داشتم اومدم ازینجا جویا بشم

**Comment by mrafieefard** [comment]
> اکانتشون توسط گیتهاب ساسپند شده و میبایست منتظر موند ببینیم چی میشه
خب اگر واسه اون پنل این اتفاق افتاده پس چرا واسه این پنل اینجوری نشده

**Comment by mrafieefard** [comment]
اوکی مرسی
