### ISSUE TITLE
Can't "Change Xray Version" on IR server

### ISSUE THREAD

**Issue by PatrickstarWritesCode** [alireza0/x-ui#1130]
اخیرا امکان تغییر نسخه XRAY رو در سرور ایران ندارم راهکاری هست؟

[X-UI 1.8.1] Xray 1.8.9
Log:
2024/03/30 19:44:22 WARNING - X-UI: Install xray Failed: open Xray-linux-64.zip: no such file or directory
2024/03/30 19:42:46 WARNING - X-UI: Install xray Failed: zip: not a valid zip file

**Comment by MK0ltra** [comment]
Probably Xray-linux-64.zip file not downloaded correctly. Your VPS may have blocked access to GitHub, you can start with checking that. Also can be related to DNS issues.

**Comment by PatrickstarWritesCode** [comment]
دانلود از گیت‌هاب مشکلی نداره، geofileـها و یا خود x-ui آپدیت میشن. پس قاعدتا نباید مسئله بلاک شدن یا dns باشه. البته روی IPv6 بلاک بود که با تغییر تنظیمات لینوکس موقع ریزالو شدن IPv4 رو ارجحیت دادم. خود xray-core رو هم با wget می‌تونم دانلود کنم.

آیا پنل از resolver دیگه‌ای استفاده می‌کنه؟ ممکنه پنل همچنان سعی کنه با IPv6 ارتباط بگیره؟

**Comment by PatrickstarWritesCode** [comment]
ظاهرا از تنظیمات dns داخل پنل استفاده می‌کنه. موقتا روی use IPv4 گذاشتم آپدیت شد. ممنون.
