### ISSUE TITLE
اضافه کردن حالت Bypass به Routing

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1131]
سلام و خسته نباشید
منظورم از حالت Bypass برای Routing اینه که بتونیم قانون رو اینجوری تعیین کنیم که تمام ترافیک سرور از Warp یا وایرگاردی که به جای Warp تنظیم کردیم عبور کنه ، غیر از یه سری سایت ها.

مثلا تمام ترافیک از Warp رد بشه ، فقط ترافیک Youtube یا Instagram مستقیم بره.

دلیل درخواستم هم اینه که اینجوری هم جلوی خیلی از نشتی ها و .... گرفته میشه
هم اینکه امنیت سرور بالاتر میره و باعث میشه ایپی سرور لو نره یا حداقل سخت تر لو بره.
علت بایپس کردن بعضی سایت ها و ... هم افزایش سرعت و کاهش پینگه و واقعا نیازی هم نیست مثلا ترافیک Youtube از وارپ رد بشه.

واقعا عالی میشه اگه این موردم به پنل ارائه بشه یا اگه الانم هست ، ممنون میشم اگه راهنمایی کنید باید چیکار کنیم.

**Comment by alireza0** [comment]
درود بر شما
قوانین مسیریابی به ترتیب اعمال میشه و اگر قانونی بالاتر قرار بگیره و match بشه، بقیه قوانین بررسی نمیشن.
با پیکربندی این بخش میتونید تنظیم دلخواهتون رو انجام بدید.

افزودن گزینه ای برای استثناها در هر قانون، در تنظیمات xray-core قابل انجام نیست
