### ISSUE TITLE
continue v2rayN Fork

### ISSUE THREAD

**Issue by APT-ZERO** [alireza0/x-ui#1133]
سلام
توی پروژه v2rayN جدا از اینکه PR شما رو نپذیرفتن و فقط یه بخشی شو به پروژه اضافه کردن
برنامه نویسش به زور تمام کانفیگ های Xray-core رو تبدیل به Sing-Box میکنه برای حالت Tun که همین باعث شده وقتی Tun فعال میشه رسما وی پی ان از کار بیافته و فقط رو حالت پروکسی قابل استفاده باشه (نسخه های بعد از v6.23)
زبان و رول های پیش فرض شم برای چین هستن، دی ان اس دیفالت سینگ باکس شم رو سرور چینی 223.5.5.5 هست
اگر فرصت شو داشتید لطفا اینا رو فیکس کنید و ریلیز بدید تا همه از فورک شما استفاده کنیم
با تشکر

**Comment by alireza0** [comment]
درود بر شما
متاسفانه من وقت زیادی برای پرداختن به همه پروژه ها ندارم.
این مهم هم به تنهایی قابل انجام نیست.
از طرفی محیط ویندوز برای طراحی و تست ندارم و این کارم رو سخت تر میکنه.
ولی چشم، اگر وقت اجازه بده و امکانش باشه اون پروژه رو هم میتونم فعال کنم و با تغییر نام اون، برای کاربران ایرانی بهینه سازی کنم.
