### ISSUE TITLE
Fragment config in server outbound

### ISSUE THREAD

**Issue by armin567ip** [alireza0/x-ui#1135]
Hi, how can I configure fragment settings for the server's outbound?
The 'Direct' and 'Blocked' tags each have a checkbox for fragmentation, but I'm unsure of its purpose. simply want to set up a fragment configuration for the server's outbound. Any help would be appreciated.

**Comment by PatrickstarWritesCode** [comment]
```json
  {
    "tag": "fragment",
    "protocol": "freedom",
    "settings": {
      "domainStrategy": "UseIPv4",
      "fragment": {
        "packets": "tlshello",
        "length": "20-40",
        "interval": "5-10"
      }
    }
  }
```
or
```json
  {
    "tag": "fragment",
    "protocol": "freedom",
    "settings": {
      "domainStrategy": "UseIPv4",
      "fragment": {
        "packets": "1-3",
        "length": "20-40",
        "interval": "5-10"
      }
    }
  }
```

**Comment by alireza0** [comment]
Hi @armin567ip 
You can define it in advanced tab as well as @PatrickstarWritesCode mentioned.

Or add a `freedom` outbound with proper fragment configuration in GUI modal (mind the `tag`).
And then on your desired outbound, you can simply enable `sockopt` option and set `Dialer Proxy` to the `tag` of recently added `freedom` outbound.
