### ISSUE TITLE
مشکل در سابسکرپشن

### ISSUE THREAD

**Issue by zarvan9** [alireza0/x-ui#1136]
سلام دوستان من یک مشکل توی سابسکرپشن دارم.

لینک های ساب بدون مشکل کار میکنن ولی دامنه کانفیگ رو عوض میکنن
یعنی من وقتی لینک ساب درست میکنم ، لینک دامنه کانفیگ عوض میشه و میشه دقیقا لینک سابسکرپشن.
 در صورتی که من از یک دامنه دیگه برای خود پنل و یک دامنه متفاوت برای سابسکرپشن استفاده کردم.

چطور میشه مشکل رو حل کرد؟

**Comment by roozbehalamdari** [comment]
درود ، از قسمت external proxy استفاده کنید مشکلتون حل میشه
