### ISSUE TITLE
Question: IOS xray Client that support json sub + fragmentation 

### ISSUE THREAD

**Issue by AliBelali** [alireza0/x-ui#1137]
Hi
Sorry for asking here but is there any xray client for IOS that supports json sub + fragmentation?

**Comment by roozbehalamdari** [comment]
درود بله این برنامه بهترینش هست : 
https://apps.apple.com/us/app/streisand/id6450534064?platform=iphone

**Comment by AliBelali** [comment]
> درود بله این برنامه بهترینش هست : https://apps.apple.com/us/app/streisand/id6450534064?platform=iphone

Thanks
