### ISSUE TITLE
عدم نمایش وضعیت آنلاین بودن کار بر در موبایل

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#1140]
با درود و خسته نباشید
در دو ورزن اخیر در گوشی موبایل مو۱عیت آنلاین بودن یوزر رو که با چراغک چشمک رن نشون میداد کار نمیکنه انگاذ
در کامپیوتر مشکلی مشاهده نمیشه در این مورد

**Comment by Alireza78na** [comment]
اون انیمیشن رو حذف کردن ، گفتن قراره توی اپدیتای بعدی دوباره فعالش کنن
