### ISSUE TITLE
مشکل با لینک ها

### ISSUE THREAD

**Issue by sinayazdan** [alireza0/x-ui#1141]
سلام خسته نباشید داداش
من یک مشکل خیلی اعصاب خورد کنی دارم و نمیتونم جوتبی براش بیدا کنم.
کانفیگم درست متصله و در برنامه ایکس به عنوان مثال صفحه رفرش میشه بدون هیچ مشکل. اما لینک های موجد توی برنامه را باز نمیکنه. منظورم آدرس سایت هایی هست که به صورت t.co در تویتتر باز میشه.

**Comment by Alireza78na** [comment]
این مشکل ۲ تا علت داره:
۱. بلاک بودن ایپی
۲.‌ کامل Routing اجرا نمیشه

با اجرای یه VPN دیگه مشکل کاملا حل میشه
