### ISSUE TITLE
spotify doesn't work with warp

### ISSUE THREAD

**Issue by AliMajidi1** [alireza0/x-ui#1144]
سلام
یکی دوهفته ای هست که اسپاتیفای دیگر با رد کردن ترافیک از وارپ متصل نمی‌شود، تنها راه ممکن برای حل این موضوع از سمت سرور رد کردن کل ترافیک سرور از وارپ است که قاعدتا کار درستی نیست، اگر ممکنه این مورد رو برسی کنید.
البته بعد از فعال کردن fake dns از سمت کلاینت به نظر مشکل حل می‌شود، سوالی که داشتم این است که در آپدیت‌های جدید پنل بخش fake dns اضافه شده است که البته کانفیگ و استفاده از آن حداقل برای من مبهم است، خواندن داک xray-core هم کمکی به موضوع نکرد، اگر ممکنه نحوه کانفیگ درست fake dns از سمت سرور را شرح دهید.

**Comment by alipour66m** [comment]
من هم همین مشکل را دارم و تایید میکنم.

**Comment by Alireza78na** [comment]
این مشکل اخیرا به وجود اومده و حدس میزنم فایل های geosite و geoip و ... دارن مشکل ساز میشن

**Comment by Alireza78na** [comment]
> مشکل از geo database نیست. مشکل اینجاست که sniffing نمی‌تونه درخواست‌های spotify رو درست تشخیص بده و باعث می‌شه routing بعضی‌هاشون رو جای وارپ بفرسته به دایرکت. اینجا #1019 یه توضیحاتی دادم که چطور بدون اینکه کاربر fakedns رو فعال کنه، توی خود سرور مشکل رو حل کنیم. ضمنا پیشنهاد می‌کنم از geo برای اسپاتیفای استفاده نکنی. فقط دامنه spotify.com رو بفرست سمت وارپ. من وقتی از geosite:spotify استفاده می‌کردم، ترافیک کلاب‌هاوس هم می‌رفت روی وارپ و مشکل درست می‌شد.

مرسی توضیحاتت ، من اون issue که اشاره کردید رو خوندم ، فقط متوجه نشدم کدی که نوشتید رو کجا اضافه کنم. باید جایگزین بخشdns توی تنظیمات xray بشه؟

**Comment by Alireza78na** [comment]
> اون تنظیمات رو نمی‌شه با یه کپی و پیست ساده اعمال کرد. باید با تنظیمات خودتون ادغامش کنید. یعنی هر بخشش رو جداگانه کپی کنید و جای درستش توی بخش advanced پیست کنید. میتونید کل کانفیگ بخش advanced رو کپی کنید و اطلاعات خصوصیش رو حذف کنید و بقیه‌شو اینجا بذارید تا من ویرایش کنم براتون.

```
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "log": {
    "access": "***",
    "dnsLog": ***,
    "error": "***",
    "loglevel": "***"
  },
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
    {
      "tag": "warp",
      "protocol": "wireguard",
      "settings": {
        "mtu": ***,
        "secretKey": "***",
        "address": [
          "***"
        ],
        "workers": *,
        "domainStrategy": "***",
        "peers": [
          {
            "publicKey": "***",
            "allowedIPs": [
              "0.0.0.0/0",
              "::/0"
            ],
            "endpoint": "***",
            "keepAlive": ***
          }
        ],
        "kernelMode": ***
      }
    },
    {
      "tag": "IPv4",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true,
      "statsOutboundDownlink": true,
      "statsOutboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "***"
        ]
      },
      {
        "type": "field",
        "domain": [
          "***"
        ],
        "outboundTag": "IPv4"
      },
      {
        "type": "field",
        "outboundTag": "warp",
        "domain": [
          "***"
        ]
      }
    ]
  },
  "stats": {},
  "dns": {
    "servers": [
      "***"
    ],
    "queryStrategy": "UseIP",
    "tag": "dns_inbound"
  },
  "fakedns": null
}
```

خدمت شما
فقط اگه ممکنه تغییرات رو علامت گذاری کنید که یادبگیرم دقیقا باید چیکار کنم
ممنونم

**Comment by Alireza78na** [comment]
> اون بخش fakedns آخرو کلا می‌شه ننوشت به شرطی که اون ,"fakedns": null رو هم از کانفیگ خودتون حذف کرده باشید.

ممنون.
دمت گرم

فقط آخرش این ارور میاد نمیزاره Save کنم:
![image](https://github.com/alireza0/x-ui/assets/144834309/f0ca72a9-84ac-4911-91f9-286946fe8718)

اینم چک میکنی بی زحمت ، خودم سعی کردم ولی درست نشد

**Comment by Alireza78na** [comment]
> خیلی باید دقت کنی، یدونه کاما کم و زیاد باشه نمی‌ذاره سیو کنی. من چیزی که برات کپی کردم رو با حذف CHANGEDها امتحان کردم و اجازه سیو می‌ده. احتمالا موقع اعمال کردن به کانفیگ اصلی یه جایی اشتباه کردی.

داداش دمت گردم
مشکلو Save نشدن حل شد
مرسی از وقتی که گذاشتی

ولی درنهایت مشکل Spotify حل نشد ، و کلا Youtube هم از کا افتاد.
فقط درصورتی که Fake DNS داخل V2rayNG روشن باشه درست میشه

**Comment by hamed0mh** [comment]
> خیلی باید دقت کنی، یدونه کاما کم و زیاد باشه نمی‌ذاره سیو کنی. من چیزی که برات کپی کردم رو با حذف CHANGEDها امتحان کردم و اجازه سیو می‌ده. احتمالا موقع اعمال کردن به کانفیگ اصلی یه جایی اشتباه کردی.

لطفا داخل تلگرام یه پیام بهم بدین منم هر کاری کردم نتونستم
@hamedb021

**Comment by Alireza78na** [comment]
> خیلی باید دقت کنی، یدونه کاما کم و زیاد باشه نمی‌ذاره سیو کنی. من چیزی که برات کپی کردم رو با حذف CHANGEDها امتحان کردم و اجازه سیو می‌ده. احتمالا موقع اعمال کردن به کانفیگ اصلی یه جایی اشتباه کردی.

آقا دمت گرم ، من مجددا نشستم اینارو با دقت بیشتری تنظیم کردم ، مشکل رفع شد.
خواستم اطلاع بدم که بقیه هم استفاده کنن از این روش
