### ISSUE TITLE
encountered a blank white screen after opening the panel in browser via ip address 

### ISSUE THREAD

**Issue by fariba-ghorbani** [alireza0/x-ui#1147]
سلام وقت به خیر
من پنل های مختلف مدیریت هسته v2ray رو امتحان کردم (مثل پنل چینی، انگلیسی، پنل سنایی و پنل شما). یک مشکل مشترک در همه این پنل ها داشتم و اونم اینه که بعد از نصب پنل، موقع باز کردن صفحه لاگ این در مرورگر مطابق آدرس رو به رو `http://ip:port` صفحه کاملا سفید بوده و فقط خود تب باز شده در حالت loading باقی میممونه (مطابق عکس). روی CentOS و Debian و Ubuntu هم امتحان کردم و فرقی نکرد. 
حتی از طریق firewall management منوی دستور x-ui هم سعی کردم پورت 2053 رو باز کنم ولی تغییری ایجاد نشد. جداگانه با ufw هم این کارو انجام دادم و باز هم فرقی نکرد. 
این قضیه رو با پورت های مختلف هم امتحان کردم.
قضیه اینجاست من سه ماه پیش پنل انگلیسی رو روی یک سرور دیگه (ارائه دهنده سرور در هر دو مورد یکی است)، نصب کردم و اصلا این مشکل رو نداشتم و پنل بصری کاملا بدون مشکل در مرورگر باز میشد ولی الان روی سرور جدید، همونطور که توضیح دادم همه پنل ها و حتی پنلی که قبلا استفاده کردم هم این مشکل رو داره.
![shia](https://github.com/alireza0/x-ui/assets/64582600/542dcec7-946d-4b40-8e4b-29b22e6218ad)

همچنین از تب نتوورک من status فایل های request زده رو در آوردم و این دو تا فایل هستن که روی pending موندن.

![fpiqh](https://github.com/alireza0/x-ui/assets/64582600/ff54bce4-f249-44e7-b217-1399ea8718ee)

و بعد از چند دقیقه هم به این حالت در اومد:

![oifhc](https://github.com/alireza0/x-ui/assets/64582600/8ac641d5-fdf8-4fb3-b08c-79a8a049f82f)

**Comment by Alireza78na** [comment]
به نظر میرسه ایپی فیلتره
یبار با کوکی ها و ... رو پاک کن یا با حالت پراویت و روشن بودن vpn  تست کن
اگه مشکل حل شه ، احتمالا ایپی فیلتر شده

**Comment by fariba-ghorbani** [comment]
> به نظر میرسه ایپی فیلتره یبار با کوکی ها و ... رو پاک کن یا با حالت پراویت و روشن بودن vpn تست کن اگه مشکل حل شه ، احتمالا ایپی فیلتر شده

سلام
آیپی رو از طریق سایت هایی مثل host tracker و check host چک کردم و فیلتر نبوده.

**Comment by Alireza78na** [comment]
این محدودیت چند ماهی هست که ایجاد شده
سرور عملا سالمه و ssh هم میخوره
ولی دقیقا وقتی که ترافیک میخواد به هر نحوی عبور کنه محدودیت مشخص میشه.
بنابراین تست ssh و check host و ... نمیتونه نتیجه ی درست بده
پس یکبار مواردی که بالاتر گفتم رو تست کنید، اگه مشکل رفع شد یعنی این که ایپی محدود شده و مشکلی از پنل و ... ندارید

**Comment by Alireza78na** [comment]
یه روش دیگه هم انداختن IP پشت دامنه و CDN و با TLS هست
اگه به این صورت و با دامنه پنل باز بشه دیگه قطعا مشکل از ایپیه

**Comment by fariba-ghorbani** [comment]
> این محدودیت چند ماهی هست که ایجاد شده سرور عملا سالمه و ssh هم میخوره ولی دقیقا وقتی که ترافیک میخواد به هر نحوی عبور کنه محدودیت مشخص میشه. بنابراین تست ssh و check host و ... نمیتونه نتیجه ی درست بده پس یکبار مواردی که بالاتر گفتم رو تست کنید، اگه مشکل رفع شد یعنی این که ایپی محدود شده و مشکلی از پنل و ... ندارید

خیلی ممنون. دقیقا وقتی آیپی رو با فیلترشکن روی موبایل باز میکنم مشکل حل میشه و وقتی inbound ساختم و استفاده کردم، آیپی فیلتره و هیچ سایتی باز نمیشه. توی پنل سرویس دهنده سرور تیکت زدم و گفتن مشکلی از آیپی نیست!!!! و دقیقا سایت host tracker رو به عنوان منبع حرفشون پیوست کردن.

**Comment by Alireza78na** [comment]
> > این محدودیت چند ماهی هست که ایجاد شده سرور عملا سالمه و ssh هم میخوره ولی دقیقا وقتی که ترافیک میخواد به هر نحوی عبور کنه محدودیت مشخص میشه. بنابراین تست ssh و check host و ... نمیتونه نتیجه ی درست بده پس یکبار مواردی که بالاتر گفتم رو تست کنید، اگه مشکل رفع شد یعنی این که ایپی محدود شده و مشکلی از پنل و ... ندارید
> 
> خیلی ممنون. دقیقا وقتی آیپی رو با فیلترشکن روی موبایل باز میکنم مشکل حل میشه و وقتی inbound ساختم و استفاده کردم، آیپی فیلتره و هیچ سایتی باز نمیشه. توی پنل سرویس دهنده سرور تیکت زدم و گفتن مشکلی از آیپی نیست!!!! و دقیقا سایت host tracker رو به عنوان منبع حرفشون پیوست کردن و گفتن از اینترنت دیگه ای استفاده کنم. به عنوان سرویس دهنده نباید این الزام رو داشته باشن که آیپی تمیز و سالمی رو ارائه بدن فارع از نوع ISP؟

بستگی به سایت و قوانینش داره
معمولا باید آیپی درست بدن ولی خب ایران کلا قاعده و قانونش با کل دنیا فرق داره.
یه مشکل دیگه مطرح کنید و بگید بهشون آیپی رو عوض کنن

**Comment by fariba-ghorbani** [comment]
> > > این محدودیت چند ماهی هست که ایجاد شده سرور عملا سالمه و ssh هم میخوره ولی دقیقا وقتی که ترافیک میخواد به هر نحوی عبور کنه محدودیت مشخص میشه. بنابراین تست ssh و check host و ... نمیتونه نتیجه ی درست بده پس یکبار مواردی که بالاتر گفتم رو تست کنید، اگه مشکل رفع شد یعنی این که ایپی محدود شده و مشکلی از پنل و ... ندارید
> > 
> > 
> > خیلی ممنون. دقیقا وقتی آیپی رو با فیلترشکن روی موبایل باز میکنم مشکل حل میشه و وقتی inbound ساختم و استفاده کردم، آیپی فیلتره و هیچ سایتی باز نمیشه. توی پنل سرویس دهنده سرور تیکت زدم و گفتن مشکلی از آیپی نیست!!!! و دقیقا سایت host tracker رو به عنوان منبع حرفشون پیوست کردن و گفتن از اینترنت دیگه ای استفاده کنم. به عنوان سرویس دهنده نباید این الزام رو داشته باشن که آیپی تمیز و سالمی رو ارائه بدن فارع از نوع ISP؟
> 
> بستگی به سایت و قوانینش داره معمولا باید آیپی درست بدن ولی خب ایران کلا قاعده و قانونش با کل دنیا فرق داره. یه مشکل دیگه مطرح کنید و بگید بهشون آیپی رو عوض کنن

با این که قانع نشده بود آیپی مشکل داره اما آیپی رو عوض کردن
اما متاسفانه هنوز مشکل برقراره به جز این قسمت که پنل xui بدون فیلترشکن بالا میاد. اما هیچ کدوم از inbound های ساخته شده کار نمیکنن (پورت های inbound ها هم با پورت اصلی فرق داره).
مثلا پنل log برنامه v2ray توی ویندوز دائما این پیام ها رو نشون میده:

![lscnkdz](https://github.com/alireza0/x-ui/assets/64582600/6e0d8e19-d3bb-467e-869f-1d4b7c11596c)

![kacz](https://github.com/alireza0/x-ui/assets/64582600/2885fa8b-32cc-43dd-9461-ffd56435a1d2)
