### ISSUE TITLE
مشکل سرتیفیکیت و زیر دامنه جدید

### ISSUE THREAD

**Issue by alirezani** [alireza0/x-ui#1148]
سلام من در کلود فلر زیر دامنه جدید با ای پی سرورم ثبت می کنم ولی موقعه باز کردن با زیر دامنه جدید می گوید فقط با یک زیر دامنه اصلی که سرتیفیکیت دارد می توانید به سایت دسترسی داشته باشید.

Did Not Connect: Potential Security Issue

Firefox detected a potential security threat and did not continue to t.example.com because this website requires a secure connection.

What can you do about it?

t.example.com has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for x.example.com:2053. The certificate is only valid for t.example.com

**Comment by Alireza78na** [comment]
HSTS رو خاموش کنید

**Comment by alirezani** [comment]
اگه منظور شما در کلود فلر هست .این گزینه خاموشه
![ssl](https://github.com/alireza0/x-ui/assets/124591607/bc6fc493-53a6-459f-8375-ed7affd0073d)

**Comment by alireza0** [comment]
درود بر شما
دوست گرامی
لطفا از طرح مشکلات نامربوط و خارج از پنل خودداری کنید
