### ISSUE TITLE
Bug with response type section in Outbounds configuration

### ISSUE THREAD

**Issue by theahz** [alireza0/x-ui#1149]
When I'm trying to specify a response type in outbounds configuration for "blackhole" protocol, I cannot select http as response type. More clearly, when I choose http as response type, the "Save" button at the top-left of the panel doesn't turn blue and as result the configuration doesn't get saved. This issue only occurs when I try to choose http as response type and the other option which is "none" works as expected. I'm using the latest version of panel.
If there are some dependencies needed for this option to be able to work properly, I would like to know.

**Comment by alireza0** [comment]
It might be related to your browser.
In my tests, everuthing works fine. You can check the advanced tab to make sure that new outbound is well added.

Otherwise, these information is not enough! Please check your browser console for an error and send me some pictures.

**Comment by theahz** [comment]
You are right, what actually was happening is in Outbounds section, the response type doesn't show what value it is already using, and the text field is always blank no matter what is set to (either none or http). Since my blackhole protocol response type was already set to http, there were no changes with Outbounds rules and therefore the Save button wouldn't light up. It would be a good feature to be able to see protocol response type without checking out advanced settings.

**Comment by alireza0** [comment]
You are right. It was a bug and fixed now.
