### ISSUE TITLE
عدم اتصال روی حالت  دستیTime Zone

### ISSUE THREAD

**Issue by meysamaliani** [alireza0/x-ui#1150]
عرض ادب
روی گوشی (آیفون تست شده) وقتی ساعت رو روی حالت دستی تغییر میدیم کانفیگ متصل نمیشه.
ولی وقتی روی اتوماتیک ست میکنیم متصل میشه

**Comment by MJamshidnejad** [comment]
> عرض ادب روی گوشی (آیفون تست شده) وقتی ساعت رو روی حالت دستی تغییر میدیم کانفیگ متصل نمیشه. ولی وقتی روی اتوماتیک ست میکنیم متصل میشه
این به خاطر طراحی پروتکل هست مشکل پنل نیست.
