### ISSUE TITLE
مشکل در balancer روی مد lowest ping

### ISSUE THREAD

**Issue by alirezarm78** [alireza0/x-ui#1151]
تعدادی outbound اضافه شده و به یک balancer اضافه شدند
اما در مد lowest ping ارتباط برقرار نمیشه و inbound نمیتونه ترافیک رو عبور بده

**Comment by alireza0** [comment]
مشکل شما با داده های کمی که نوشتید قابل حدس نیست.

پنل با ترافیک شما کاری نداره و تنها پیکربندی هسته رو درست میکنه.
با این وجود این کمک ها رو به شما میتونم بکنم.
برای Lowest Ping باید تنظیمات Observatory رو داشته باشید.
برای اینکه inbound ترفیک رو به بالانسر مشخص بفرسته باید قوانین مسیریابی رو درست پیکربندی کنید

**Comment by milad73n** [comment]
سلام 
مهندس لینکی هست که بشه در مورد بالانسر بیشتر فهمید؟

**Comment by alireza0** [comment]
@milad73n 

درود بر شما
اگر دنبال اطلاعات کلی هستید بهتره جستجو کنید.
این مفهوم برای ادمین سیستم و ادمین های شبکه روشنه و بهتره از اون منابع استفاده کنید.
