### ISSUE TITLE
اتصال مستقیم دامنه ها و آی پی ایران

### ISSUE THREAD

**Issue by sajjad2001** [alireza0/x-ui#1152]
سلام علیرضا جان.خیلی ممنونم از زحمات بی دریغت
مشکلی که من بهش برخوردم اینه که گزینه اتصال مستقیم به سایت ها و دامنه های ایرانی در روش تانل دکودمودور برام کار نمیکنه،روی سرور ایران هم این گزینه رو فعال میکنم.توی قوانین مسیریابی چندین بار حالت های مختلف رو تست کردم و جواب نداده، یعنی وقتی وارد سایت ها یا اپ های ایرانی میشم آی پی خارج رو نشون میده...البته روی ریورس تانل به خوبی کار میکنه.ولی روی دکودمودور اصلا.چرا روی دکو جواب نمیده؟اگه میشه یه توضیح یا راه حلی در موردش بگین.تشکر.

**Comment by alireza0** [comment]
درود بر شما
روش دوکودمودور برای انتقال «اتصال» کاربر به سرور دوم استفاده میشه و ترافیک کاربر از سرور دوم در قوانین مسیریابی قابل استفاده است.
این روش به صورت عمومی با ipatbles فرقی نداره.
تنها حالتی که میتونه در دوکودمودور مفید باشه اینه که در خروجی از قابلیت فرگمنت استفاده کنید.
