### ISSUE TITLE
HTTPUpgrade host field

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#1154]
There's something wrong in HTTPUpgrade host field parsing that deletes host after editing an existing outbound.

To recreate the bug:
1. add an outbound using xray-outbounds menu.
2. set transmission to HTTPUpgrade and fill the fields, including the Host field and press Sure button.
3. check xray-advanced-outbounds json: Host field and host header are set.
4. now go back to xray-outbounds menu and edit the newly created outbound. Host field is now empty.
5. If you press sure, the Host settings will be also deleted from xray-advanced-outbounds json.

By the way, I'm not sure that putting "Host" field in "headers" is necessary
```
      "httpupgradeSettings": {
        "path": "/path",
        "host": "somehost",
        "headers": {
          "Host": "somehost"
        }
```

**Comment by X-Oracle** [comment]
Hi @alireza0 .
Is this backward compatibality with older version of x-ray cores like 1.8.4? Or we have to use 1
8.10+ in next next panel version?

**Comment by alireza0** [comment]
It has backward compatibility.
But in x-ui, using links and qr-code will be affected.

**Comment by alireza0** [comment]
@X-Oracle I have added a kind of backward compatibility to support both.
