### ISSUE TITLE
نصب پنل

### ISSUE THREAD

**Issue by hootansadafi** [alireza0/x-ui#1155]
سلام من تازه کارم توی قضیه ساخت پنل و از روش زیر استفاده میکنم
apt update && apt upgrade -y

apt install curl socat –y

curl https://get.acme.sh | sh

~/.acme.sh/acme.sh --set-default-ca --server letsencrypt

~/.acme.sh/acme.sh --register-account -m "Personal email address"

~/.acme.sh/acme.sh --issue -d turk.mahdi-usa.site --standalone

~/.acme.sh/acme.sh --installcert -d turk.mahdi-usa.site --key-file /root/private.key --fullchain-file /root/cert.crt

bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) 

لازمه این مراحل رو برم و دستور اخر رو با ماله شما جایگزین کنم یا فقط دستور موجود تو صفحه شما رو بزنم و تمومه؟

**Comment by alireza0** [comment]
درود بر شما
دستور اول و آخر رو فقط نیاز دارید.
بقیه کار میتونه از طریق دستور x-ui انجام بشه.
