### ISSUE TITLE
لینک ساب برای چند فایل json

### ISSUE THREAD

**Issue by sarahtuska** [alireza0/x-ui#1156]
راهی هست برای اضافه کردن چند json با سرور های مختلف و دامنه های مختلف در یک لینک سابسکریپشن ؟

 برای مثال در حال حاضر من چند سرور دارم که هر کدام پروتکل های مختلفی روشون دارم. همه این لینک ها رو در یک فایل ساب گداشتم و همه با اپدیت لینک . 

کل کانقیگ های مختلف از سرورهای مختلف دسترسی پیدا می کنن . چون فرگمنت خوب جواب می ده و من بخوام به صورت ساب چند فایل json رو که درست کردم یکجا با یک لینک ساب بگیره .

 آیا راهی برای این کار هستش ؟ ممنون از تلاش همه دوستان مه برای اینترنت ازاد تلاش می کنن

**Comment by sarahtuska** [comment]
> اگر کلاینت پشتیبانی کنه میتونید از آرایه ای از جیسون ها استفاده کنید.

مرسی 

پس فعلا فکر نکنم برنامه ای ساپورت کنه .چه اندروید و چه ای او اس؟

**Comment by sarahtuska** [comment]
ارایه رو ساختم با چند  Json  . خیلی راحت توی V2rayN  ویندوز جواب می ده . ولی در V2rayNg  جواب نداد . خطاشم اینه :
Config malformed Exposed BEGIN_OBJECT but was BEGIN_ARRAY at line 1 coloumn 2 path $
که فکر کنم فعلا ارایه ساپورت نمی شه . باید این رو توی گیتهاب  V2rayng  ریکوئست  بزنم . درسته ؟

**Comment by alireza0** [comment]
باید بروزرسانی کنید. از نسخه 1.8.18 به بعد کاملا پشتیبانی میکنه

**Comment by sarahtuska** [comment]
> باید بروزرسانی کنید. از نسخه 1.8.18 به بعد کاملا پشتیبانی میکنه

اما من 1.8.19 رو دارم و این خطا رو می ده . فایل Json  استفاده شده برای ویندوز و اندروید یکی هست . ولی 1.8.19 خطا رو می ده

**Comment by alireza0** [comment]
اگر مشکل داره براشون ایشو باز کنید و تنظیم رو براشون بفرستید

**Comment by sarahtuska** [comment]
مرسی . حتما براشون می زارم
