### ISSUE TITLE
ربات کلاینت

### ISSUE THREAD

**Issue by mohamadn69** [alireza0/x-ui#1157]
سلام ببخشید این سوال را اینجا مطرح میکنم
داخل github سنایی issues غیر فعال شده و نمیشه باهاش ارتباط گرفت. قطعا شما باهاشون در ارتباط هستین
داخل نسخه آخر  پنل سنایی ربات کلاینت ها کار نمیکنه و پیغام اولیه را میده و میگه با مدیر شبکه تماس بگیرید . اگه میشه بهشون اطلاع بدین یا حد اقل گروه تلگرامی چیزی معرفی کنید تا بتونیم مشکلات را اعلام کنیم

**Comment by alireza0** [comment]
درود بر شما
متاسفانه عدم رعایت آداب طرح مشکل توسط کاربران رپو باعث دلسردی و حذف این منو شده.
ایشون از مشکلات آگاه میشن و حتما به موقع بررسی میکنن.

@MHSanaei

**Comment by mohamadn69** [comment]
ممنون بابت پاسختون  .بهشون ایمیل زدم  جواب دادن
