### ISSUE TITLE
مشکل در Sniffing برخی دامنه ها

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1159]
سلام و وقت بخیر
مشکلی که میخوام مطرح کنم قبلا به شکل های مختلفی بیان شده و متاسفانه راه حل جامعی واسش پیدا نشده و پراکنده هم هست.
من این مشکل رو به صورت کلی تر مطرح میکنم ، امیدوارم راه حلی واسش پیدا شه

**مشکل:** 
در قسمت Warp ، وقتی بعضی از وبسایت ها و سرویس ها مثل Spotify یا لینک های داخل X ( توییتر سابق ) ، بعضی API ها گوگل و ... قرار میگیره ، بخشی از دامنه ها به شکل صحیح و کامل Route نمیشن و به صورت Direct رد میشن.
از اونجایی که این سرویس ها به طور مداوم آیپی های VPN ها رو مسدود میکنن ( به صورت کلی هست و محدود به V2ray نمیشه ) ، بنابراین به صورت Direct و با ایپی اصلی سرور باز نمیشن و اینجا اهمیت استفاده از Warp مشخص میشه.
مشکلی که پیش میاد اینه که وبسایت هایی که مثال زده شدن ( قطعا از این تعداد بیشتر هستن ) به طور کامل Route نمیشن و باعث میشه از دسترس خارج ( مثل دامنه ی t.co ) یا به طور کامل لود نشن ( مثل Spotify )

**راه حل**

به نظر میرسه مشکل در بخش Sniffing هست و با فعال کردن Fake DNS در سمت کلاینت مشکل برطرف میشه ، ام اینکار باعث میشه مشکلات دیگه ای برای کاربر به وجود بیاد و بهتره از سمت سرور حل بشه.
یک نمونه کانفیگ که قبلا داخل Issue ها برای حل مشکل ارائه شده به همراه توضیحات اینجا قرار میدم

#1144 
#1019 

ممنون میشم اگه پیگیری کنید این مشکل رفع بشه.

**Comment by Alireza78na** [comment]
اینم اضافه کنم که این مشکل برای Spotify در داخل نرم افزار ها اتفاق میوفته
مثلا Spotify توی نرم افزار های ویندوز ، اندروید و... مشکل پیدا میکنه و در وبسایتش مشکلی نداره.

برای api گوگل هم ، معمولا در لاگین ها اینجوری میشه ، چیزی که خودم تجربه کردم بخش های Login و Sign up سرویس Wordtune بود.

دامنه ی t.co هم که برای لینک های توییتر هست هم به همین شکل

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی شما
من توی این متن چیزی به که بشه به عنوان باگ در نظر گرفت ندیدم.
این تجربیات شما ارزشمنده و کاربرها میتونن استفاده کنن.
ولی لطفا بفرمایید ما در پنل چطور میتونیم کمک کنیم تا سمت کاربر این مشکل بوجود نیاد.

**Comment by Alireza78na** [comment]
> درود بر شما سپاسگزارم از همراهی شما من توی این متن چیزی به که بشه به عنوان باگ در نظر گرفت ندیدم. این تجربیات شما ارزشمنده و کاربرها میتونن استفاده کنن. ولی لطفا بفرمایید ما در پنل چطور میتونیم کمک کنیم تا سمت کاربر این مشکل بوجود نیاد.

زنده باشید و پایدار
راستش توی Issue هایی که رفرنس دادم راه حلش گفته شده برای پنل که میومد Fake DNS رو از طریق قوانین Routing برای دامنه های خاصی مثل Spotify فعال میکرد
هدف از این issue بررسی همین موارد بود ، چون پراکنده بود ، گفتم شاید اینجوری بهتر بررسی شه.
عذرخواهی میکنم اگه لیبل اشتباه برای issue انتخاب کردم

**Comment by hamed0mh** [comment]
> درود بر شما سپاسگزارم از همراهی شما من توی این متن چیزی به که بشه به عنوان باگ در نظر گرفت ندیدم. این تجربیات شما ارزشمنده و کاربرها میتونن استفاده کنن. ولی لطفا بفرمایید ما در پنل چطور میتونیم کمک کنیم تا سمت کاربر این مشکل بوجود نیاد.

درود 
منم تست کردم تقریبا تمام برنامه های موبایل که نیاز به وارپ دارن باز نمیشه و فقط روی مرورگر وارپ اعمال میشه 

فقط یه سری از برنامه ها از جمله اسپاتیفای با fakedns داخل v2rayng باز میشن و
مثلا برنامه truecaller فقط باید کل ترافیک سرور رو ببری روی وارپ تا کار کنه
ممنون میشم راهنمایی کنین راه حل چیه

**Comment by Alireza78na** [comment]
> > درود بر شما سپاسگزارم از همراهی شما من توی این متن چیزی به که بشه به عنوان باگ در نظر گرفت ندیدم. این تجربیات شما ارزشمنده و کاربرها میتونن استفاده کنن. ولی لطفا بفرمایید ما در پنل چطور میتونیم کمک کنیم تا سمت کاربر این مشکل بوجود نیاد.
> 
> درود منم تست کردم تقریبا تمام برنامه های موبایل که نیاز به وارپ دارن باز نمیشه و فقط روی مرورگر وارپ اعمال میشه
> 
> فقط یه سری از برنامه ها از جمله اسپاتیفای با fakedns داخل v2rayng باز میشن و مثلا برنامه truecaller فقط باید کل ترافیک سرور رو ببری روی وارپ تا کار کنه ممنون میشم راهنمایی کنین راه حل چیه

این مشکل متاسفانه بخاطر روتینگ ناقص اتفاق میوفته ، درواقع بعضی از دامنه که اگه اشتباه نکنم غالبا مربوط به api ها میشه درست  route نمیشه و درصورتی که ایپی اصلی سرور بلاک شده باشه ، عملا از این سرویس ها نمیشه استفاده کرد

**Comment by alireza0** [comment]
عملیات روتینگ توسط پنل انجام نمیشه و هسته انجام میده.
پنل فقط تنظیمات رو برای شما ساده میکنه.
اگر فکر میکنید دامنه ای باید به روتینگ اضافه بشه امکانش وجود داره.

**Comment by alireza0** [comment]
> با سلام و تشکر بابت وقتی که برای این پنل و پاسخگویی به کاربرها می‌ذارید، راستش فعال کردن fakedns به تنهایی هیچ کار خاصی انجام نمی‌ده. حتما باید ترافیک dns رو intercept کرد و فرستادش سمت dns داخلی xray تا عملا تغییری ایجاد کنه. من توی این issue #1019 توضیح داده بودم. خودم دستی این کارها رو انجام می‌دم. شاید بد نباشه با فعال کردن fakedns در پنل، اون تنظیمات مربوط به route شدن ترافیک پورت ۵۳ به dns داخلی هم به صورت خودکار همزمان انجام بشه.

درود بر شما
سپاسگزارم از انتقال تجربه ارزشمندتون
اینکه اتوماتیک انجام بشه ممکنه برای کاربرهای دیگه و کاربران دیگه مشکل ایجاد کنه.
