### ISSUE TITLE
How about the difference with 3x-ui

### ISSUE THREAD

**Issue by yfdoor** [alireza0/x-ui#1161]
Sorry, could you pls let me know the difference with 3x-ui? they look same from Ui design and functions..... maybe just I donot catch it

**Comment by alireza0** [comment]
3x-ui : More features + tgbot + IP limit + 2x Dark Theme
x-ui: Foundomental enhancements, stable, light weight ( emphasis on personal usage )

**Comment by yfdoor** [comment]
> 3x-ui : More features + tgbot + IP limit + 2x Dark Theme x-ui: Foundomental enhancements, stable, light weight ( emphasis on personal usage )

thanks for your reply, I try your  x-ui and s-ui recently. I think custom management function in s-ui is a good idea. And subscribe link is maintained by user. So we can get all node info for one user with one link. It's more userful than x-UI

**Comment by alireza0** [comment]
Yes! Unfortunately we have lots of limitations in x-ui old design.
S-UI deployed by a modern frameworks and database design is based on updated market needs.

**Comment by yfdoor** [comment]
> Yes! Unfortunately we have lots of limitations in x-ui old design. S-UI deployed by a modern frameworks and database design is based on updated market needs.

It's a good project, hope new release coming soon with more great function!!
