### ISSUE TITLE
The issue of the subscription link after the domain name (CDN) is bound

### ISSUE THREAD

**Issue by yfdoor** [alireza0/x-ui#1162]
I setup my server as below:
 1. DNS resolve "x.123.xyz" in CF to my host IP (Proxied-true)
 2. Set Reverse Proxy the domain name "x.123.xyz" to “127.0.0.1:1234” in my host server
 3. x-ui setting: panel port ~ 1234; sub port~4567
 
Now I can access x-ui panel by http://x.123.xyz， but Subscription URL http://x.123.xyz:4567/sub/cfdffehagk68gnhk9czpxh0m?nahsme=caghksh68gnk9czphhx0m is not work.

**Comment by alireza0** [comment]
If you have free version of CF and enabled the proxy, you can only use limited number of ports
