### ISSUE TITLE
Outbound Fragment

### ISSUE THREAD

**Issue by HamedX2Z** [alireza0/x-ui#1163]
is there a difference between enabling fragmentation in outbound (server side) or sub json?
![Screenshot 2024-04-11 190432](https://github.com/alireza0/x-ui/assets/104461689/a78d41b0-2d52-461e-a12e-75ea2fd28686)

**Comment by alireza0** [comment]
In subJson, you will enable fragment in client side, but in outbounds, you will enable it for server's outgoing traffics

**Comment by alireza0** [comment]
Yes, it is.
Inbounds has no fragment option.
If you mean providing link with fragment option, there is no standard way to do it except using subJson

**Comment by ali-de7** [comment]
If you add fragment in the link with any format, it will work in one client but not all clients. 
I don't think it breaks any client. 
It's all least better than not having the option IMHO.
