### ISSUE TITLE
Disk getting full

### ISSUE THREAD

**Issue by armin567ip** [alireza0/x-ui#1165]
Hi, Since I started my server, Server's disk is getting filled up rapidly, What to do?
I've disabled all 3 logs in Xray settings, Does that cause any problem?, Plus I need the system to keep record of users & Inbound traffics.

**Comment by alireza0** [comment]
If you disabled xray logs, it is not related to the panel or core. Please ask a SystemAdmin to help
You can use `du` command to find where is the huge folders

```bash
df -h
du -sh /*
du -sh /var/*
du -sh /var/log/*
```
