### ISSUE TITLE
ایمپورت نشدن ساب اسکریپشن در نرم افزار streisand

### ISSUE THREAD

**Issue by nsa14** [alireza0/x-ui#1167]
سلام خدمت اقا علیرضا و عزیزانی ک واقعا  زحمت کشیدن

تو نرم افزار ‏streisand
وقتی لینک‌ ساب اسکریپشن رو وارد میکنم خطا میده ولی تو نرم افزار V2box وارد میشه بدون خطا
کسی میدونه مشکل جیه؟
عنوان خطاشم اینه:
subscription does not contain valid configuration

کسی از عزیزان میدونه مشکل چیه ؟
ممنونم

**Comment by alireza0** [comment]
درود بر شما
اگر مدل کانفیگتون رو بفرمایید میتونیم تست کنیم و نتیجه رو بگیم.
اگر مشکل از پنل باشه تصحیح میشه و اگر از کلاینت باشه میتونیم گزارش کنیم

**Comment by nsa14** [comment]
این نمونه کد ساب هست از پنل برداشتم

‏http://xxxxxxxxxxxxxxx:2096/gsub/9euvxbnyba4kmpxc

ادرس ip رو تغییر دادم

اینم نمونه کد‌ کانفیگش

vless://16e32942-a12d-4d2f-9cc7-8f8d0fa67522@football1.digishoping.com:8080/?type=tcp&security=none#%F0%9F%91%BB-user001-simple

**Comment by alireza0** [comment]
ساب و کانفیگ شما مشکلی نداره. فقط اینکه سرویس ساب شما باید https باشه. خیلی از نرم افزار ها با http مشکل دارند.

**Comment by nsa14** [comment]
مرسی اقا علیرضا
با کرفتن ssl برای پنل مشکل حل شد

یک دنیا ممنون استاد
