### ISSUE TITLE
/getClientTraffics always return "enable": true

### ISSUE THREAD

**Issue by megoRU** [alireza0/x-ui#1168]
`/getClientTraffics` always return "enable": true

**Comment by alireza0** [comment]
We have two types of disabled user!
First one is in inbound's config and another one is in client's traffic.

Inbound client's enable option: to disable client even if it still has time/volume.
Client's traffic enable option: it shows time/volume is now finished

**Comment by megoRU** [comment]
it's very confusing, it's not easier for developers to add an endpoint with the client status enabled or not

**Comment by alireza0** [comment]
In the endpoint you are using `/getClientTraffics` it is clear that it is about client's traffic.
If you want to know about user's enable config in inbound, you should use `getInbound` method.
We have no separate client table in database, therefore you should check it inside inbound's settings.

Some part of application process need this separation and two types of `enable` option.
