### ISSUE TITLE
مشکل قطع شدن xray

### ISSUE THREAD

**Issue by mrcodebaz** [alireza0/x-ui#1169]
سلام 
متاسفانه چند روزیه که هرچند ساعت یکبار خودکار اتصال یوزرها به کانفیگ قطع میشه ، وقتی xray رو ریستارت میکنم از داخل پنل مجدد اوکی میشه و متصل میشن

دو پنل دارم روی سرورهای مختلف یکی علیرضا یکی ثنایی
ثنایی قبلا این مدلی بود و حالا حل شده!
اما الان پنل علیرضا  اینجوری شده

لطفاً راهنمایی کنید ببینیم مشکلش چیه

این عکس موقعی که قطع شده بود

![IMG_20240413_161154_763](https://github.com/alireza0/x-ui/assets/155746341/72860c67-01ff-4135-a2d2-2af2d4839a49)

اینم عکس لاگ چند ساعت اخیر
![IMG_20240413_162902_370](https://github.com/alireza0/x-ui/assets/155746341/816d8832-4c52-432a-9f39-435bf430c156)

اون Killing process بخاطر کرون جابی هست که خودم زدم هر ساعت ریستارت کنه بلکه کاربرا قطع نشن
اما اینم باز راه حل مناسبی نبود!

**Comment by alireza0** [comment]
درود بر شما
عکس اول نشون میده که داده ها رو از سرور نمیتونید بگیرید.
این میتونه به خاطر ناپایداری های اینترنت باشه.
توی لاگها چیزی نمیبینم که ناپایداری درست کنه

**Comment by mrcodebaz** [comment]
> درود بر شما عکس اول نشون میده که داده ها رو از سرور نمیتونید بگیرید. این میتونه به خاطر ناپایداری های اینترنت باشه. توی لاگها چیزی نمیبینم که ناپایداری درست کنه

درود، بله مشکل عکس اول برطرف شد و اطلاعات رو گرفت
ولی مشکل اصلی اینه که با اینکه توی لاگ ها هیچ خطاییی چیزی وجود نداره
اما مدام چند ساعت یکبار قطع میشه و باید دستی ریستارت کنم

هیچ دلیل مشخصی هم نداره، یهو اینطور شده
