### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by hamed0mh** [alireza0/x-ui#1170]
درود

من وارپ داخل پنل رو فعال کرده بودم و  داخل قسمت outbounds اورده بودمش بالاترین‌ و اوکی داشت کار میکرد
الان تنظیمات پنل رو ریست کردم و میخواستم دوباره فعالش کنم .
 عین همون کار سری قبل رو انجام دادم ولی تا وارپ رو فعال میکنم کل سرور قطع میشه 
ممنون میشم راهنمایی کنین مشکل از کجاست

**Comment by hamed0mh** [comment]
فکر میکنم پنل زمان ریست یه چیزی رو به حالت اولیه بر نمیگردونه که این مشکل پیش اومده

**Comment by hamed0mh** [comment]
یه چیزی الان فهمیدم 
لایسنس اکانت +warp باگ خورده 
چون کد لایسنس که میدم هیچ چیز تغییر نمیده
راهی هست پاکش کنم ؟

**Comment by alireza0** [comment]
درود بر شما
برای تغییر لایسنس، گزینه گذاشتیم.
از اون استفاده کنید

**Comment by hamed0mh** [comment]
ببخشید من روی پنل سنایی هستم  فقظ گزینه update و more information  هست
 که وقتی لایسنس جدید میدم بهش چیزی از Account Information تغییر  نمیکنه

**Comment by alireza0** [comment]
وقتی لایسنس رو آپدیت میکنید، یکبار پنجره تنظیمات وارپ رو ببندید و دوباره باز کنید، باید تغییرات رو به شما نشون بده

**Comment by hamed0mh** [comment]
همه جوره تست کردم  توی Account Information تغییر نمیده 
پنل باگ خورده

**Comment by alireza0** [comment]
توی این پنل بدون بستن پنجره هم بلادرنگ بروز میشه.
مگر اینکه کلید اشتباهی رو بهش بدین.
میتونید لاگ های پنل رو چک کنید

**Comment by hamed0mh** [comment]
> توی این پنل بدون بستن پنجره هم بلادرنگ بروز میشه. مگر اینکه کلید اشتباهی رو بهش بدین. میتونید لاگ های پنل رو چک کنید

این مشکل برطرف شد ممنون 
فقط الان مشکلی که هست زمانی که توی routing هر کدوم از گزینه های وارپ رو فعال میکنم (حتی دامین دستی هم بهش دادم) قطع میکنه اون قسمت رو

**Comment by alireza0** [comment]
احتمالا ارتباط سرورتون با کلادفلر برقرار نمیشه! میتونید توی لاگهای xray ببینید.
توی این بخش پنل کار خاصی نمیتونه برای شما انجام بده
