### ISSUE TITLE
پسورد در فایل کانفیگ

### ISSUE THREAD

**Issue by jamiekarvans** [alireza0/x-ui#1171]
با سلام پسورد رو چگونه میشه از فایل کانفیگ درآورد؟
بنده پسورد سرور و پنل رو عوض کردم و یکی گزاشتم حالا یادم نمیاد اما فایل بکاپ رو دارم که داره هنوز برام توی تلگرام پشتیبان گیری میشه هر روز و اخرین پسورد عملا روشه
اما توش که نگاه کردم پسورد اولیم رو نشون میده نه اخری لطفا بگید چطور و کجا باید پسورد رو از فایل های پشتیبان ربات تلگرام که میفرسته پیدا کنم
این فایل دیتابیس که امشب گرفتم
[x-ui.txt](https://github.com/alireza0/x-ui/files/14969181/x-ui.txt)

**Comment by alireza0** [comment]
درود بر شما
باید فایل دیتابیس رو با نرم افزار ویرایش دیتابیس باز کنید. رمز ورود پنل در جدول users وجود داره.
رمز آخر رو باید از دیتابیس بعد از دستکاری پیدا کنید.

برای تغییر رمز سرور از یک متخصص SystemAdmin کمک بگیرید و یا در اینترنت جستجو کنید.
بعد از بازیابی رمز سرور، شما میتونید رمز پنل رو با دستور x-ui عوض کنید
