### ISSUE TITLE
Warp  Routing 

### ISSUE THREAD

**Issue by hamed0mh** [alireza0/x-ui#1174]
درود آیا توی آپدیت جدید مشکل حل شد #1159

**Comment by alireza0** [comment]
درود بر شما
این مشکل به پنل ربطی نداره و فقط یک تجربه از دوستان بوده.
بعضی سرویس ها به استفاده از پراکسی و تانل حساس هستند.

**Comment by Alireza78na** [comment]
> درود بر شما این مشکل به پنل ربطی نداره و فقط یک تجربه از دوستان بوده. بعضی سرویس ها به استفاده از پراکسی و تانل حساس هستند.

ببینید مربوط به پراکسی و ... نمیشه ، این مشکل توی اپدیت جدید به وجود اومده.
از طرفی من تست های مختلفی کردم و مطمئنم این قضیه مربوط به ایپی نمیشه ، چون من از Warp استفاده نمیکنم و از کانفیگ های Wireguard دیگه استفاده میکنم.
بنابراین وقتی دقیقا با همون کانفیگ و ایپی وایرگارد به صورت مستقیم وصل میشم هیچ مشکلی وجود نداره و وقتی روی V2ray استفاده میکنم مشکل پابرجا هست.
پس لطفا این مورد رو بررسی کنید ، اگه لازم دونستید من حاضرم تمام مستندات و کارهایی که انجام شده رو خدمتتون ارسال کنم

**Comment by gakingtel** [comment]
سلام دوستان
اول یه تشکر کنم از علیرضا بابت زحماتی که بابت پنل شون کشیدن

این مشکل رو من هم بهش بر خوردم
قبلا مشکل باز نشدن اسپاتیفای و همچین سایت هایی که به vpn حساسن بخاطر dns leak بوجود میومد
و فقط کافی بود شما dns کارت شبکه سرور و xray core رو یکی ست میکردی
مثلا هر دو گوگل یا کلادفلر
مشکل با این حل میشد
من با ست کردن doh کلادفلر توی xray configuration بدون وارپ مشکل همه وب سایت های که باز نمیشد رو حل کرده بودم 

توی xray 1.8.9 این مشکل dns leak حل شده
کامیت هارو چک کنید دو مورد هست
یکی مربوط مشکل leak و یکی dns

اما بعد این آپدیت مشکلی بوجود اومده که حتی وقتی dns leak ندارید بعضی cdn ها آی پی رو بلاک میکنن و سایت های روی اونا باز نمیشه

**Comment by Alireza78na** [comment]
> سلام دوستان اول یه تشکر کنم از علیرضا بابت زحماتی که بابت پنل شون کشیدن
> 
> این مشکل رو من هم بهش بر خوردم قبلا مشکل باز نشدن اسپاتیفای و همچین سایت هایی که به vpn حساسن بخاطر dns leak بوجود میومد و فقط کافی بود شما dns کارت شبکه سرور و xray core رو یکی ست میکردی مثلا هر دو گوگل یا کلادفلر مشکل با این حل میشد من با ست کردن doh کلادفلر توی xray configuration بدون استفاده از وارپ مشکل همه وب سایت های که باز نمیشد رو حل کرده بودم
> 
> توی xray 1.8.8 این مشکل leak حل شده فک میکنم مربوط به این کامیت باشه [XTLS/Xray-core@cae9457](https://github.com/XTLS/Xray-core/commit/cae94570df467d6073f791a80bafc5f3f36773f9)
> 
> اما بعد این آپدیت مشکلی بوجود اومده که حتی وقتی dns leak ندارید بعضی cdn ها آی پی رو بلاک میکنن و سایت های روی اونا باز نمیشه

بله دقیقا بعد از اپدیت این مشکل پیش اومده و روی نسخه های قبلی وجود نداشت ، ولی با این حال ظاهرا مشکل توی این issue حل نمیشه و تاجایی که متوجه شدم اگه باگی هم باشه مربوط به Xray Core میشه که خارج از مسائل پنل هست ، مگر اینکه راه حل خاصی باشه که دوستان بخوان راهنمایی کنن.
به نظرم بهتره این مسئله رو مستقیما از xray هم پیگیری کنیم که اگه واقعا باگی هست برطرف شه.
چون طیف گسترده ای از برنامه ها از جمله Spotify , Gemini , true Caller , بعضی api ها و خیلی چیزای دیگه رو تحت تاثیر قرار داره.
متاسفانه نه میشه به طور کامل حلش کرد و نه میشه نادیدش گرفت.
من یه issue واسه تیم xray هم زدم ، اگه ممکن بود مشکل رو شما هم واسشون توضیح بدید شاید بشه یه جوری حلش کرد.

**Comment by gakingtel** [comment]
> > سلام دوستان اول یه تشکر کنم از علیرضا بابت زحماتی که بابت پنل شون کشیدن
> > این مشکل رو من هم بهش بر خوردم قبلا مشکل باز نشدن اسپاتیفای و همچین سایت هایی که به vpn حساسن بخاطر dns leak بوجود میومد و فقط کافی بود شما dns کارت شبکه سرور و xray core رو یکی ست میکردی مثلا هر دو گوگل یا کلادفلر مشکل با این حل میشد من با ست کردن doh کلادفلر توی xray configuration بدون استفاده از وارپ مشکل همه وب سایت های که باز نمیشد رو حل کرده بودم
> > توی xray 1.8.8 این مشکل leak حل شده فک میکنم مربوط به این کامیت باشه [XTLS/Xray-core@cae9457](https://github.com/XTLS/Xray-core/commit/cae94570df467d6073f791a80bafc5f3f36773f9)
> > اما بعد این آپدیت مشکلی بوجود اومده که حتی وقتی dns leak ندارید بعضی cdn ها آی پی رو بلاک میکنن و سایت های روی اونا باز نمیشه
> 
> بله دقیقا بعد از اپدیت این مشکل پیش اومده و روی نسخه های قبلی وجود نداشت ، ولی با این حال ظاهرا مشکل توی این issue حل نمیشه و تاجایی که متوجه شدم اگه باگی هم باشه مربوط به Xray Core میشه که خارج از مسائل پنل هست ، مگر اینکه راه حل خاصی باشه که دوستان بخوان راهنمایی کنن. به نظرم بهتره این مسئله رو مستقیما از xray هم پیگیری کنیم که اگه واقعا باگی هست برطرف شه. چون طیف گسترده ای از برنامه ها از جمله Spotify , Gemini , true Caller , بعضی api ها و خیلی چیزای دیگه رو تحت تاثیر قرار داره. متاسفانه نه میشه به طور کامل حلش کرد و نه میشه نادیدش گرفت. من یه issue واسه تیم xray هم زدم ، اگه ممکن بود مشکل رو شما هم واسشون توضیح بدید شاید بشه یه جوری حلش کرد.

من ترجیحم اینه که بدون استفاده از وارپ مشکل حل بشه

**Comment by Alireza78na** [comment]
> > > سلام دوستان اول یه تشکر کنم از علیرضا بابت زحماتی که بابت پنل شون کشیدن
> > > این مشکل رو من هم بهش بر خوردم قبلا مشکل باز نشدن اسپاتیفای و همچین سایت هایی که به vpn حساسن بخاطر dns leak بوجود میومد و فقط کافی بود شما dns کارت شبکه سرور و xray core رو یکی ست میکردی مثلا هر دو گوگل یا کلادفلر مشکل با این حل میشد من با ست کردن doh کلادفلر توی xray configuration بدون استفاده از وارپ مشکل همه وب سایت های که باز نمیشد رو حل کرده بودم
> > > توی xray 1.8.8 این مشکل leak حل شده فک میکنم مربوط به این کامیت باشه [XTLS/Xray-core@cae9457](https://github.com/XTLS/Xray-core/commit/cae94570df467d6073f791a80bafc5f3f36773f9)
> > > اما بعد این آپدیت مشکلی بوجود اومده که حتی وقتی dns leak ندارید بعضی cdn ها آی پی رو بلاک میکنن و سایت های روی اونا باز نمیشه
> > 
> > 
> > بله دقیقا بعد از اپدیت این مشکل پیش اومده و روی نسخه های قبلی وجود نداشت ، ولی با این حال ظاهرا مشکل توی این issue حل نمیشه و تاجایی که متوجه شدم اگه باگی هم باشه مربوط به Xray Core میشه که خارج از مسائل پنل هست ، مگر اینکه راه حل خاصی باشه که دوستان بخوان راهنمایی کنن. به نظرم بهتره این مسئله رو مستقیما از xray هم پیگیری کنیم که اگه واقعا باگی هست برطرف شه. چون طیف گسترده ای از برنامه ها از جمله Spotify , Gemini , true Caller , بعضی api ها و خیلی چیزای دیگه رو تحت تاثیر قرار داره. متاسفانه نه میشه به طور کامل حلش کرد و نه میشه نادیدش گرفت. من یه issue واسه تیم xray هم زدم ، اگه ممکن بود مشکل رو شما هم واسشون توضیح بدید شاید بشه یه جوری حلش کرد.
> 
> من ترجیحم اینه که بدون استفاده از وارپ مشکل حل بشه

متاسفانه تنها راهش تغییر آیپیه که یکی از روش هاش warp هست. که به هرحال لازمه از routing استفاده شه و وفتیم استفاده میشه این مشکلات به وجود میان.

**Comment by gakingtel** [comment]
فک میکنم این باگ DNS leak در اندروید 14 باعث بشه آی پی روی بعضی cdn ها بلاک بشه
 و باز نشدن اسپاتیفای یا بعضی سرویس های گوگل مثل Gemini بخاطر همین هست

https://mullvad.net/en/blog/dns-traffic-can-leak-outside-the-vpn-tunnel-on-android

**Comment by Alireza78na** [comment]
> فک میکنم این باگ DNS leak در اندروید 14 باعث بشه آی پی روی بعضی cdn ها بلاک بشه و باز نشدن اسپاتیفای یا بعضی سرویس های گوگل مثل Gemini بخاطر همین هست
> 
> https://mullvad.net/en/blog/dns-traffic-can-leak-outside-the-vpn-tunnel-on-android

فک نمیکنم موضوع این باشه ، چون روی ایفون و ویندوز هم همین مشکلات وجود دارن.
اینطور من متوجه شدم ( از درست بودنش مطمئن نیستم ) یک سرویس خاصی از گوگل هست که بعضی وبسایت ها از جمله اسپاتیفای دارن ازش استفاده میکنن و همون یدونه رو هیچ جوره نمیشه توی routing اوردش.
تنها چیزی که واسم جواب داد ، Routing کلی بدون در نظر گرفتن دامنه هست

**Comment by gakingtel** [comment]
> > فک میکنم این باگ DNS leak در اندروید 14 باعث بشه آی پی روی بعضی cdn ها بلاک بشه و باز نشدن اسپاتیفای یا بعضی سرویس های گوگل مثل Gemini بخاطر همین هست
> > https://mullvad.net/en/blog/dns-traffic-can-leak-outside-the-vpn-tunnel-on-android
> 
> فک نمیکنم موضوع این باشه ، چون روی ایفون و ویندوز هم همین مشکلات وجود دارن. اینطور من متوجه شدم ( از درست بودنش مطمئن نیستم ) یک سرویس خاصی از گوگل هست که بعضی وبسایت ها از جمله اسپاتیفای دارن ازش استفاده میکنن و همون یدونه رو هیچ جوره نمیشه توی routing اوردش. تنها چیزی که واسم جواب داد ، Routing کلی بدون در نظر گرفتن دامنه هست


اگر آی پی بخاطر کاربر های اندروید بلاک بشه
با همه سیستم عامل ها نمیشه مثلا اسپاتیفای رو آورد

تا وقتی مشکل حل نشده میشه از وارپ استفاده کرد
ولی راه حل اصولی اینه که بدون وارپ همه حل بشه
چون این مشکل باعث شده لوکیشن واقعی کاربر لو بره

**Comment by gakingtel** [comment]
> > > فک میکنم این باگ DNS leak در اندروید 14 باعث بشه آی پی روی بعضی cdn ها بلاک بشه و باز نشدن اسپاتیفای یا بعضی سرویس های گوگل مثل Gemini بخاطر همین هست
> > > https://mullvad.net/en/blog/dns-traffic-can-leak-outside-the-vpn-tunnel-on-android
> > 
> > 
> > فک نمیکنم موضوع این باشه ، چون روی ایفون و ویندوز هم همین مشکلات وجود دارن. اینطور من متوجه شدم ( از درست بودنش مطمئن نیستم ) یک سرویس خاصی از گوگل هست که بعضی وبسایت ها از جمله اسپاتیفای دارن ازش استفاده میکنن و همون یدونه رو هیچ جوره نمیشه توی routing اوردش. تنها چیزی که واسم جواب داد ، Routing کلی بدون در نظر گرفتن دامنه هست
> 
> اگر آی پی بخاطر کاربر های اندروید بلاک بشه با همه سیستم عامل ها نمیشه مثلا اسپاتیفای رو آورد
> 
شاید مشکل ربطی به اون نداشته باشه

> بحرهال تا وقتی مشکل حل نشده میشه از وارپ استفاده کرد ولی راه حل اصولی اینه که بدون وارپ همه حل بشه چون این مشکل باعث شده لوکیشن واقعی کاربر لو بره

**Comment by gakingtel** [comment]
> سلام دوستان اول یه تشکر کنم از علیرضا بابت زحماتی که بابت پنل شون کشیدن
> 
> این مشکل رو من هم بهش بر خوردم قبلا مشکل باز نشدن اسپاتیفای و همچین سایت هایی که به vpn حساسن بخاطر dns leak بوجود میومد و فقط کافی بود شما dns کارت شبکه سرور و xray core رو یکی ست میکردی مثلا هر دو گوگل یا کلادفلر مشکل با این حل میشد من با ست کردن doh کلادفلر توی xray configuration بدون استفاده از وارپ مشکل همه وب سایت های که باز نمیشد رو حل کرده بودم
> 
> توی xray 1.8.8 این مشکل leak حل شده فک میکنم مربوط به این کامیت باشه [XTLS/Xray-core@cae9457](https://github.com/XTLS/Xray-core/commit/cae94570df467d6073f791a80bafc5f3f36773f9)
> 
> اما بعد این آپدیت مشکلی بوجود اومده که حتی وقتی توی سایتای تست dns leak چیزی نشون نمیده بعضی cdn ها آی پی رو بلاک میکنن و سایت های روی اونا باز نمیشه


چیزی که باعث شد فک کنم مشکل از dns leak در اندروید هست
این تجربه قبلیم بود
راه حل موقتی که mullvad ارائه داده هم همین fake dns هست
