### ISSUE TITLE
مشکل ws بعد از آپدیت به xray 1.8.10

### ISSUE THREAD

**Issue by alipour66m** [alireza0/x-ui#1176]
درود خدمت علی رضا
بعد از آپدیت به xray 1.8.10 تمامی کانفیگ های ws +CDN از کار میفته
دقیقا چه تنظیمی باید انجام داد تا مانند گذشته بشه با ws و CDn کد ساخت؟
آیا راهی هست که کدهای فعلی به کار بیفته؟

**Comment by liamnees** [comment]
> درود بر شما تغییرات هسته باعث این داستان شده. بهتره تنظیم هاست رو از هدر ها به پارامتر جدید هاست منتقل کنید و تست بگیرید.
اینجوری هم من تست گرفتم ولی 1.8.10 روی وب سوکت و cdn از کار می افته!

**Comment by liamnees** [comment]
> درود بر شما تغییرات هسته باعث این داستان شده. بهتره تنظیم هاست رو از هدر ها به پارامتر جدید هاست منتقل کنید و تست بگیرید.

روی ساب عادی کار می کنه روی ساب فرگمنت کار نمی کنه احتمالا اونجا نیاز به تغییراتی داره

**Comment by liamnees** [comment]
> درود بر شما تغییرات هسته باعث این داستان شده. بهتره تنظیم هاست رو از هدر ها به پارامتر جدید هاست منتقل کنید و تست بگیرید.

من تست کردم روی آپدیت جدید در فرگمنت کار نمی کنه. هاست عملا روی فرگمنت نمیاد. باید تغییراتی در فرگمنت داده بشه که هاست جدید را شناسایی کنه

**Comment by alireza0** [comment]
ممکنه به دلیل استفاده کلاینت از هسته قدیمی باشه

**Comment by dev-ehsan-babaei** [comment]
منم این مشکلو دارم. همه چی آپدیته. هاست رو از هدر برمیدارم میذارم تو هاست ولی بازم EOF میگیرم.
