### ISSUE TITLE
مشکل با کانفیگ ws و پروکسی کلودفلر 

### ISSUE THREAD

**Issue by HosseinAfshar** [alireza0/x-ui#1177]
سلام خسته نباشید 
من کانفیگی گه چند ماهی بود استفاده میکردم ولی یه دفعه روی ایرانسل و adsl به مشکل خورده 
کونفیگ به این صورت بود 
Vless 
ws 
 port cloudflare set 
 ssl فقط روی دامنه برای پنل فعال هست 
و پورتی که ست شده برای http هست (کلودفلر) بدون ssl مثل پورت 2052 

این کانفیگ روی همراه کار میکنه  ولی ایرانسل نه

**Comment by alireza0** [comment]
درود بر شما
اینگونه پرسش ها در مورد پنل نیست. خواهشمندم از گروه ها و فوروم های پیگیری کنید.
