### ISSUE TITLE
ترافیک روی لینک سابسکریپشن

### ISSUE THREAD

**Issue by saemasgari** [alireza0/x-ui#1178]
عرض ادب و احترام خدمت علیرضا عزیز .
 ضمن تقدیر از زحمات شما خواستم بدونم چطوری باید ترافیک رو روی کل لینک سابسکریپشن بدم ؟؟؟
در حال حاضر مثلا اگه کاربرم کانفیگ ۵۰ گیگی بخواد من بناچار روی هر کانفیگ ۱۰ گیگ میزارم که با ۵ تا کانفیگ جمعا ۵۰ گیگ داره . اینطوری کابرم مجبوره از هر کشور ۱۰ گیگ مصرف کنه
من میخوام این ۵۰ گیگ رو روی کل لینک سابسکریپشنی که میدم دستش استفاده کنه . اگه خواست از اون ۵ تا کشور و کانفیگ از یکیش کل ۵۰ گیگ رو هم استفاده کنه بتونه !!!
ممنون میشم راهنمایی کنید
سپاس فراوان

**Comment by alireza0** [comment]
درود بر شما
این ویژگی با ساختار x-ui سازگار نیست و تلاشهای ما برای اجرای این مدل تا الان موفق نبوده.
