### ISSUE TITLE
Can't add fallbacks without TLS/xTLS enabled

### ISSUE THREAD

**Issue by arash88** [alireza0/x-ui#118]
Using the latest version I can't add fallbacks without any TLS/xTLS being enabled. So one can't benefit from nginx/caddy as a reverse proxy and Xray as a dispatcher/etc.
But Vaxilu's and FranzKafka's versions support these scenarios

**Comment by alireza0** [comment]
Regarding to the documents, fallback works only in TCP+tls ( or xtls ).
Did you test if it works fine ?
I couldn't !

**Comment by arash88** [comment]
> Regarding to the documents, fallback works only in TCP+tls ( or xtls ). Did you test if it works fine ? I couldn't !

You are correct, but when you have nginx as reverse proxy + web, then you already set your tls stuff at nginx side and then at x-ui side you turn tls off

**Comment by alireza0** [comment]
It seems you are using nginx for fallback. Therefore you should use nginx for other fallbacks as well.

It is not a good idea to enable both nginx and xray fallbacks in a row.

**Comment by alireza0** [comment]
لطفا جوابها رو کامل بخونید.
قابلیت فالبک فقط روی tcp+tls قابل اجراست
