### ISSUE TITLE
آپدیت ربات تلگرامی

### ISSUE THREAD

**Issue by soli2413** [alireza0/x-ui#1181]
سلام.در صورت امکان ربات تلگرامی رو هم یه بروزرسانی انجام بدید.ربات آقای ثنایی امکانات بیشتری داره.ممنون

**Comment by alireza0** [comment]
درود بر شما
پنل 3x-ui ماژول مجزایی برای این کار دارن.
البته قرار نیست امکانات دو پنل یکی باشند و استفاده از اون پنل برای امکانات بیشتر مناسب تره.
