### ISSUE TITLE
باگ آپدیت API

### ISSUE THREAD

**Issue by hamedm94** [alireza0/x-ui#1182]
وقتی قصد استفاده از API برای آپدیت یک کلاینت را  با متد Post داریم اگر در URL ارسالی آی دی کلاینت نوشته نشده باشد عملیات آپدیت را برای اولین کاربری که در پنل از قبل ساخته شده انجام می دهد. این باگ امنیتی نیست و اهمیت چندانی ندارد اما برای بهبود پنل علیرضا بهتر است که رفع شود و در صورت عدم ارسال آی دی عملیات آپدیت برای کاربر دیگری انجام نشود.

**Comment by alireza0** [comment]
سپاسگزارم از گزارشتون
برطرف شد و در نسخه بعد این مشکل وجود نخواهد داشت.
