### ISSUE TITLE
نشان ندادن ترافیک و آنلاین یا آفلاین بودن یوزرها

### ISSUE THREAD

**Issue by iceplus1981** [alireza0/x-ui#1184]
در حالت ریورس تانل، ترافیک استفاده شده و آنلاین و آفلاین بودن یوزرها رو نشون نمیده
![image](https://github.com/alireza0/x-ui/assets/167519397/7b07f934-5b8d-41a7-a2d6-5d2f966db8cd)

**Comment by alireza0** [comment]
https://github.com/alireza0/x-ui/issues/911#issuecomment-1919819844

**Comment by iceplus1981** [comment]
سلام ممنون از پاسختون من api رو به اول لیست منتقل کردم اما باز هم مشکل حل نشد
![image](https://github.com/alireza0/x-ui/assets/167519397/09f39af4-8cb6-472d-bd51-7c363769baee)
![image](https://github.com/alireza0/x-ui/assets/167519397/94f2e10f-63ac-4e5d-b444-be53a29dd396)
