### ISSUE TITLE
 بدرستی عمل نمیکندXui ای پی لیمیت در پنل

### ISSUE THREAD

**Issue by Behtash007** [alireza0/x-ui#1185]
سلام 
همه ی فرایند برای ای پی لیمیت فعال فعال کردم و همچنان با تعداد چند ای پی به سرویس وصل میشوند مشکل از کجاست

**Comment by Alireza78na** [comment]
اگه اشتباه نکنم این پنل کلا ایپی لمیت نداره
پنل جناب سنایی هم با فعال بودن fali2ban میشه از ip limit استفاده کرد ، البته access log هم باید فعال باشه.

کلا چون محدودیت بر اساس IP هست نمیشه به طور دقیق و کامل محدودیت ایجاد کرد ، محدودیت اگه بر اساس تعداد دستگاه بود مثل OpenVPN خیلی بهتر عمل میکرد که اونم فک نمیکنم امکان اجرا کردن روی xray رو داشته باشه.

**Comment by Behtash007** [comment]
> اگه اشتباه نکنم این پنل کلا ایپی لمیت نداره پنل جناب سنایی هم با فعال بودن fali2ban میشه از ip limit استفاده کرد ، البته access log هم باید فعال باشه.
> 
> کلا چون محدودیت بر اساس IP هست نمیشه به طور دقیق و کامل محدودیت ایجاد کرد ، محدودیت اگه بر اساس تعداد دستگاه بود مثل OpenVPN خیلی بهتر عمل میکرد که اونم فک نمیکنم امکان اجرا کردن روی xray رو داشته باشه.

بله ، پنل سنایی نصب کردم ، fail2ban فعال کردم ،  در اپدیت جدید لاگ بصورت خودکار در پنل اضافه شده ، چون بصورت ای پی های مختلف وصل میشن میخواستم دو ای پی همزمان فعال بشه که بدرستی عمل نمیکنه ، لاگ چک میکنم خالیه درصورت که تنظیمات بدرستی انجام دادم
