### ISSUE TITLE
امکان اضافه کردن چند host در Request header

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1186]
عرض سلام و خسته نباشید
یه سوالی داشتم ، امکان اضافه کردن چندین host توی قسمت request header برای WS وجود داره ( مثلا 2 یا 3 تا ) ؟

چون این امکان از طریق گزینه ی + روی پنل هست اما وقتی 2 تا یا بیشتر تعریف میشه ، آخرین host رو برای اتصال درنظر میگیره و تمام کانفیگ هایی که host متفاوتی با آخری دارن قطع میشن.

قبلا به این صورت بود که قسمت host header خیلی حساس نبود و میشد با host های مختلف و متفاوت با چیزی که توی پنل بود به راحتی متصل شد ولی الان امنیت بالاتر رفته و فقط با host تعریف شده در پنل میشه وصل شد. ( که خب خیلی عالیه )

بنابراین با توجه به اینکه امکان تعریف چندین host در پنل وجود داره ،  خواستم بدونم انجام این کار کلا امکان پذیر هست ؟

**Comment by Alireza78na** [comment]
کاربردش اینه که ( ممکنه کاربرد های دیگه ای هم داشته باشه ) فرض کنید من یک اینباند WS دارم ، روی CDN کلودفلر با دامنه ex1.com به سرور وصل میشم و روی CDN آمازون با دامنه ex2.com که هر دو 2 به یک سرور و کانفیگ وصل میشن اما با hostname های متفاوت.
قبلا به راحتی و بدون هیچ مشکلی هر دو وصل میشدن و hostی که توی اینباند ثبت شده بود تاثیری توی روند اتصال نداشت و انگار اصلا چک نمیشد.
اما الان فقط میشه با یکی از دامنه ها متصل شد.
اگه امکان تعریف چند host وجود داشته باشه ، دوباره میشه این قابلیت رو با امنیت بالاتر برگردوند. به نظرم اینجوری حتی شناسایی هم سخت تر میشه.

**Comment by Alireza78na** [comment]
منظورم از استفاده از چند host اینه که یک host به عنوان پارامتر اصلی باشه و توی کانفیگ ها و ... هم کلا اون انتخاب شه ، host های بعدی که تعیین میشن حکم white list داشته باشن و سرور اجازه اتصال بده

**Comment by alireza0** [comment]
درود بر شما
همینطوری که در[ توضیحات xray](https://xtls.github.io/en/config/transports/websocket.html#websocketobject) اومده،‌ توضیح شما درسته. برای اینکه هر مقداری برای هاست رو بتونید استفاده کنید باید اون رو توی سرور خالی بذارید.

![image](https://github.com/alireza0/x-ui/assets/12573084/15d7c00f-3201-4404-b4ba-d7a9c31fbe32)
