### ISSUE TITLE
درخواست اموزش فرگمنت

### ISSUE THREAD

**Issue by micpet1993** [alireza0/x-ui#1188]
درود فراوان

این v2ray به اندازه کافی پیچیده هست دیگه فرگمنتش دیوانم کرد، لطفا بگین چطوری فرگمنت بزنم
تا الان تانل میکروتیک و softether استفاده میکردم ولی هزینه vps ایران خیلی زیاد شده، 3 میلیون در ماه

**Comment by Alireza78na** [comment]
سلام
واسه فرگمنت باید کانفیگتونو از نوع WS یا GRPC باشه و نیاز به یک دامنه دارید که به ایپی سرور اشاره کنه و پشت cdn باشه.
تنظیمات فرگمنت رو با ازمون و خطا اعمال میکنید.
درنهایت متصل میشد.
نیاز به ایپی یا دامنه ی تمیز هم دارید

**Comment by apktopsblog** [comment]
فرگمنت با دامنه فیلتر شده هم وصل میشه
یه کانفیگ از نوع vless ws tls بسازید
پروکسی کلادفلر روشن باشه
کانفیگ رو توی سایت های تبدیل به فرگمنت مثل irfc.space کپی کنید و کانفیگ یا فایل فرگمنت رو بگیرید و استفاده کنید.

**Comment by micpet1993** [comment]
موفق شدم دوستان، ممنونم
