### ISSUE TITLE
null مشکل اضافه شدن 

### ISSUE THREAD

**Issue by ramram2020** [alireza0/x-ui#1189]
سلام.
بعد نصب ورژن جدید و آوردن بکاپ ها . در قسمت هاست بعد اسکن روی گوشی کلمه null اضافه میشه در حالی که روی پنل خالیه این قسمت ! لطفا بررسی بفرماید چون در دادن کانفیگ جدید کارمون سخت شده و باید دستی پاکش کنیم از سمت گوشی. ممنون میشم بررسی بفرمایید

**Comment by ramram2020** [comment]
البته این اتفاق روی  پنل هایی که کانفیگ ساده  vless دارن افتاده و اونی که vmess هست این باگو نداره

**Comment by alireza0** [comment]
درود بر شما
نکته اول اینه که نصب نسخه جدید و سپس آوردن کانفیگ کار اشتباهیه. نه فقط در این نرم افزار بلکه توی همه نرم افزارها.
هر بکاپ برای نسخه خودش مناسبه. پس اگر میخواید به سرور جدید برید، اول نسخه معادل سرور قبلی برید و بعد بروزرسانی کنید.

اگر هاست رو خالی گذاشتید، با یکبار ویرایش و ذخیره اینباند مشکلتون حل میشه.

**Comment by ramram2020** [comment]
علیرضا جان این مشکل حتی در سرور خام و پنل خام هم دیده شد ! من از دو ورژن هم شکل هم انتقال دادم . میتونید یه کانفیگ ساده  vless بسازید و چک کنید

**Comment by ramram2020** [comment]
و عجیب اینکه وقتی به جای آدرس از ip استفاده میکنم با وجود پر بودن قسمت هاست با کلمه (null) روی گوشی باز هم وصل میشه و مشکلی نداره !!! پس شما هم لطفا با دامنه روی سرور خام چک کنید و متوجه این موضوع یعنی قرار گرفتن عبارت null در قسما هاست بعد اسکن در گوشی میشوید. سپاس از شما

**Comment by ramram2020** [comment]
علیرضا جان من روی سه تا سرور خام دیگه هم تست کردم.  جالب اینجاست تا زمانی که از ip برای اتصال استفاده میکنید با وجود اضافخ شدن کلمه null در گوشی به مشکل نمیخورید !! پس خواهشمندم با دامنه چک بفرمایید. 
بنده میتونم در صورت امکان دسترسی بدم به همه سرور ها مشاهده بفرمایید

**Comment by ramram2020** [comment]
روی یه سرور دیگه هم باز تست کردم. کانفیگ ویلس ساده با وب سوکت بعد اسکن روی گوشی قسمت هاست کلمه (null) میاد ! حالا اگه با ip وصل بشی مشکلی نداره ولی اگه دامنه داشته باشی حتما باید قسمت هاست روی گوشی دستی پاک بشه وگرنه کانفیگ جدید کانکت نمیشه در برنامه v2rayng ,
محبت کنید بررسی بفرمایید . و اینکه امکان دانگرید هست مهندس ؟

**Comment by alireza0** [comment]
مشکل رو متوجه شدم و حل شد.
اگر از هاست در کل استفاده نمیکنید میتونید به نسخه قبلی برگردید.

**Comment by ramram2020** [comment]
سلام مجدد. مرسی بابت زحماتتون . متاسفانه الان روی سرور جدید مجدد نصب کردم و کانفیگ ساده وی لس و وب سوکت ساختم. بازهم در قسمت هاست نول اضافه میشه و کانفیگ جدید در صورت داشتن دامنه کانکت نمیشود .

**Comment by alireza0** [comment]
سپاسگزارم از گزارشتون.
برای استفاده از آخرین تغییرات، با باید دستی بیلد بگیرید و یا منتظر نسخه بعد باشید.

**Comment by aliamg1356** [comment]
> سپاسگزارم از گزارشتون. برای استفاده از آخرین تغییرات، با باید دستی بیلد بگیرید و یا منتظر نسخه بعد باشید.

با چه نرم افزارهایی از سورستون خروجی بگیریم

**Comment by aliamg1356** [comment]
رای استفاده از امکانات جدید در تغییرات اعمال شده و هم برای بیلد ورژن مخصوص ویندوز
با سپاس

**Comment by alireza0** [comment]
https://go.dev/doc/tutorial/compile-install

**Comment by aliamg1356** [comment]
> https://go.dev/doc/tutorial/compile-install
با درود مجدد
فایل کامپایل شد و یک فایل 65 مگی ساخته شد اما اجرا نمیشه
برنامه نویسی بلد نیستم اما برای یک کاری به ورژن ویندوز این پنل نیاز دارم اگه ممکن هست راهنمایی بیشتری بفرمایین
با تشکر

**Comment by aliamg1356** [comment]
> https://go.dev/doc/tutorial/compile-install

با درود مجدد
فایل کامپایل شد و یک فایل 65 مگی ساخته شد اما اجرا نمیشه
برنامه نویسی بلد نیستم اما برای یک کاری به ورژن ویندوز این پنل نیاز دارم اگه ممکن هست راهنمایی بیشتری بفرمایین
با تشکر
