### ISSUE TITLE
مشکل عجیب قعطی به صورت رندوم

### ISSUE THREAD

**Issue by mahdisalehivand** [alireza0/x-ui#1191]
سلام 
مشکلی که دارم به صورت رندم تو v2ray دیگه پینگ نمیده ولی پنل میاد و میشه وصل شد و تلگرام هم وصل میشه ولی اینستا و واتز اپ وصل نمیشه اگه دست نزنم 5 دقیقه بعد وصل میشه اگه داخل پنل x-ui رو ریست کنم همون لحظه درست میشه دوتا سرور دارم یدونه یوزر کم یدونه زیاد تو جفتش این اتفاق میفته

**Comment by alireza0** [comment]
درود بر شما
این مشکل شما به پنل ارتباطی نداره.

**Comment by tezget** [comment]
این مشکل رو منم دارم
