### ISSUE TITLE
Traffic Limits.

### ISSUE THREAD

**Issue by vanotaras** [alireza0/x-ui#1192]
Traffic Limits.
Hello! I'm a beginner. I'm using google translator. I use [3x-ui 2.0.2](https://github.com/MHSanaei/3x-ui) (https://github.com/MHSanaei/3x-ui), but I couldn't create a requester there, so I'm writing here. In my clients I have set a traffic limit. When does the traffic limit reset? I need to reset the limit once a month. Do I have to reset the limit myself?

**Comment by alireza0** [comment]
When you enable the expiration time in client edit modal, an input box will appear called "Auto renew". Set 30 (days) and expect to have defined traffic volume on each 30 days.
