### ISSUE TITLE
Is Mux supported?

### ISSUE THREAD

**Issue by To-Azamat** [alireza0/x-ui#1193]
Judging by the Wiki:
“ Mux only needs to be enabled on the client side, and the server side automatically adapts “

Having a running server I enabled Mux on Streisand and Shadowrocket. Both do not transmit traffic after that.

**Comment by To-Azamat** [comment]
I use vless+tcp+reality and can't make it work. Do I need anything specific in Inbounds setup?
Also, what flow you use for clients? Mine is xtls-rprx-vision

**Comment by alireza0** [comment]
@pulsarice ,

Thank you for your report. I will check and implement it soon.

**Comment by alireza0** [comment]
It is now implemeted with force to disable if vision is selected for flow
