### ISSUE TITLE
users Traffic sort  (مرتب کردن ترافیک یوزرها)

### ISSUE THREAD

**Issue by AliShFar** [alireza0/x-ui#1196]
سلام و درود
امکانش هست که در نسخه‌های بعدی قسمت ترافیک یوزرها (حجم مصرفی یوزرها در هر اینباند)  هم قابل سورت‌کردن باشه؟
الان فقط کلاینک رو میشه سورت کرد.

**Comment by alireza0** [comment]
درود بر شما
فیلد اسم کلاینت یه دیتای ساده متنی میشه و بقیه فیلد ها ترکیبی هستن و از متد های مختلف استفاده میشه.
ساختش باعث سنگین شدن صفحه میشه و به همین دلیل فقط بر اساس اسم اضافه شد.

**Comment by AliShFar** [comment]
خیلی ممنون از پاسخت علیرضا جان
یه سوال دیگه
آیا از نظر فنی امکانش هست که تنظیمات فرگمنت به داخل یوزر یا حداقل به داخل اینباند منتقل بشه
یعنی بشه برای هر یوزر یا هر اینباند فرگمنت خاص خودش رو اعمال کرد

اگر اینجوری بشه خیلی خوبه. چون میشه یک کانفیگ رو با فرگمنت‌های متفاوت خروجی گرفت
