### ISSUE TITLE
How to set the European date format?

### ISSUE THREAD

**Issue by muxoc** [alireza0/x-ui#1198]
I have a question about the date and year on Internet resources.
The year 1400 is displayed everywhere for me. As I understand it, this is the Iranian calendar.
How to set the European date format?
Thank you in advance!

**Comment by Enkidu-6** [comment]
Panel Settings -> General -> Time Zone

**Comment by muxoc** [comment]
> Panel Settings -> General -> Time Zone

unfortunately I tried this, but it didn't help. As I understand it, this setting is responsible only for the time of scheduled tasks on the server.
I checked this first.

**Comment by Enkidu-6** [comment]
What do you mean by 

> The year 1400 is displayed everywhere for me

?
Because I don't see dates displayed anywhere on the Panel. Are you talking about your Operating system's Time zone?

**Comment by muxoc** [comment]
> ? Because I don't see dates displayed anywhere on the Panel. Are you talking about your Operating system's Time zone?

This can be most clearly seen in search queries on Google

![CleanShot 2024-04-25 at 15 37 13@2x](https://github.com/alireza0/x-ui/assets/61200059/79cdbd8e-7b42-4fa7-babd-76144a252a88)

**Comment by Enkidu-6** [comment]
Is the computer you're browsing with set to Iran's region? I don't think this is related to time zone but the region and locale

Open a terminal to your Server and type:
```
timedatectl
```
And paste it here.  Also type:
```
date
```
and tell us what you see. 

Finally type:
```
locale
```
and paste the result here

**Comment by muxoc** [comment]
> and paste the result here

```
*****@*****:~$ timedatectl
Local time: Thu 2024-04-25 18:38:55 MSK
Universal time: Thu 2024-04-25 15:38:55 UTC
RTC time: Thu 2024-04-25 15:38:56
Time zone: Europe/Moscow (MSK, +0300)
System clock synchronized: yes
NTP service: active
RTC in local TZ: no
```

```
*****@******:~$ date
Thu 25 Apr 2024 06:39:04 PM MSK
```

```
*****@*****:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by muxoc** [comment]
> Everything seems to be in order on your system. I don't see any reason why it should show you the Persian Calendar date format and I can't reproduce it either.
> 
> Did you install X-UI yourself or did you buy it from someone from Iran? How about the VPS?

I rented a VPS personally from a European country. I also set up the panel myself using this script 
```
bash <(curl -Ls https://raw.githubusercontent.com/alireza0/x-ui/master/install.sh)
```
Immediately after installing and configuring the first connection I had dates displayed in Persian calendar.

When I started looking for the problem - I came across the section you wrote about above: Panel Settings -> General -> Time Zone. But it didn't help.

Then I tried to find even the slightest mention of changing the calendar or something similar in instructions and guides, but that didn't help either.

I tried searching for similar issues on github under “issues”, but that didn't work either.

It was only after all this that I decided to try asking this question myself. I didn't change anything in the configuration files after the standard installation - that's how it works from the beginning. 
Before that I installed the same panel on another server - the dates were the same, but I did not pay attention to it.

But anyway, thank you for trying to help!

**Comment by Enkidu-6** [comment]
Well, not sure why this is happening to you. I changed my server's time zone from UTC to Asia/Tehran, I changed my Time zone to Tehran in the panel settings, As a last resort I even changed the time zone and region on my Windows laptop to Iran and even with all three of them combined I couldn't reproduce the problem you're having. Searching Google for videos would never show the Persian dates for me.

**Comment by muxoc** [comment]
> Well, not sure why this is happening to you. I changed my server's time zone from UTC to Asia/Tehran, I changed my Time zone to Tehran in the panel settings, As a last resort I even changed the time zone and region on my Windows laptop to Iran and even with all three of them combined I couldn't reproduce the problem you're having. Searching Google for videos would never show the Persian dates for me.

I agree, it's very strange. When I first saw it, I thought it was a bug. But when I re-installed the system a second time and encountered the same thing, I was confused. I assumed it was a feature of this panel, so I decided to ask a question.
Maybe I've found this bug that needs to be fixed)))

**Comment by Enkidu-6** [comment]
How about your inbound configurations. Are they default configurations made by the panel or have you added extra modifications of your own?

**Comment by muxoc** [comment]
> How about your inbound configurations. Are they default configurations made by the panel or have you added extra modifications of your own?

A completely clean installation of the panel on a freshly created fresh Debian 11 image. All connections were added manually via the web panel.

I have suspicions that the VPS provider is not telling me something, maybe the servers are not really in Europe. Because my external ip in some services is displayed as USA and in some as Finland, although I bought it as Finland.

**Comment by Enkidu-6** [comment]
> I have suspicions that the VPS provider is not telling me something, maybe the servers are not really in Europe. Because my external ip in some services is displayed as USA and in some as Finland, although I bought it as Finland.

Geoip is not always accurate. My servers are all in Finland and Google would always show my IPV4 to be in Helsinki which is exactly where it is but for the past few days Google is giving me the Russian version for the IPv4 and German version for the IPV6.

Also interestingly enough for the IPV4 the date format is showing as for example 25 April 2024 but for the German version it shows 24.04.2023. So yes, Google is doing something funky with the date depending on where it thinks the IP is coming from.

Perhaps it's considering your IP to be from Iran and that is not far fetched as a lot of Iranian ISPs lease their IPs from either Russia or Turkey and when you look at the subnets, they're sometimes quite close.

I suggest you try to send google traffic through IPV6, if your server has one and see the result. At least temporarily.

```
      {
        "type": "field",
        "outboundTag": "IPv6",
         "domain": [
	   "geosite:google"
        ]
      },

```
You may get a different location.

**Comment by Enkidu-6** [comment]
P.S.

Modern Linux systems prioritize IPV6 over IPV4. So if you have IPV6 and no specific routing rules, a lot of your traffic go out through IPV6. So try sending it once through IPV4 and once through IPV6 and see if you can see a difference between locations.

**Comment by Enkidu-6** [comment]
open an SSH terminal to your server and type:
```
ping google.com
```
If the reply shows an IPV6 address, the OS prioritizes IPV6 and I can tell you that if you haven't modified the system, I'll bet you'll get an IPV6 response.

As for routing Google through IPV4, it's easy.:

Xray Configs -> Basics -> IPV4 Routing and click on Google.

For IPV6 Routing, I believe you need to add the code I mentioned above to your Xray Configs -> Advanced -> Routing rules or use Xray Configs -> Routing Rules and add Rule for IPV6.

Also try typing:
```
curl ip-api.com
```
and see what's your IP's location is.

**Comment by muxoc** [comment]
To understand the situation, would such conclusions be appropriate?

IPV4
```
curl ipinfo.io/---.---.---.---
{
  "ip": "---.---.---.---",
  "city": "Helsinki",
  "region": "Uusimaa",
  "country": "FI",
  "loc": "60.1695,24.9354",
  "org": "AS26383 Baxet Group Inc.",
  "postal": "00100",
  "timezone": "Europe/Helsinki",
  "readme": "https://ipinfo.io/missingauth"
}%
```

IPV6
```
curl ipinfo.io/----:e---:7::-:---
{
  "ip": "----:e---:7::-:---",
  "city": "Helsinki",
  "region": "Uusimaa",
  "country": "FI",
  "loc": "60.1695,24.9354",
  "org": "AS26383 Baxet Group Inc.",
  "postal": "00100",
  "timezone": "Europe/Helsinki",
  "readme": "https://ipinfo.io/missingauth"
}%
```

**Comment by muxoc** [comment]
> open an SSH terminal to your server and type:
> 
> ```
> ping google.com
> ```

```
ping google.com
PING google.com (216.58.211.238) 56(84) bytes of data.
64 bytes from mad01s24-in-f14.1e100.net (216.58.211.238): icmp_seq=1 ttl=60 time=2.57 ms
64 bytes from mad01s24-in-f14.1e100.net (216.58.211.238): icmp_seq=2 ttl=60 time=2.49 ms
64 bytes from mad01s24-in-f14.1e100.net (216.58.211.238): icmp_seq=3 ttl=60 time=2.66 ms
```

**Comment by Enkidu-6** [comment]
P.S. 
By the way the home IP address doesn't matter. Even if you only have an IPV4 at home, the server can still send the data through IPV6 and then send it back to you in IPV4 format that your home PC can understand.

**Comment by muxoc** [comment]
I'm very much surprised, but it actually worked! I never would have thought it would have an effect. Thank you so much!

![CleanShot 2024-04-25 at 21 23 26@2x](https://github.com/alireza0/x-ui/assets/61200059/8b37d4fc-32cf-4ce5-ac8e-106802e06581)
![CleanShot 2024-04-25 at 21 24 58@2x](https://github.com/alireza0/x-ui/assets/61200059/0ae4ff7f-c7c6-4fbe-8c45-904ba5a6b5f6)

**Comment by muxoc** [comment]
> the server can still send the data through IPV6 and then send it back to you in IPV4 format that your home PC can understand.

I didn't know that, I'll keep that in mind. It's quite possible I could use it. 
Thanks again for your time.

**Comment by Enkidu-6** [comment]
Cool. I love a good mystery. So your system was prioritizing IPV6 after all.

To change that priority system-wide for all traffic, type:
```
nano /etc/gai.conf
```
If they file exists, you'll see the content and if it doesn't exist, it will create one. If you see the contents, look for 

```
precedence ::ffff:0:0/96  10
```
and change 10 to 100 and get rid of the hashtag if there is one before it and save. If the file is empty, paste:
```
precedence ::ffff:0:0/96  100
```
into the file and save.

You don't have to do this. I'm just telling you for future reference. And it doesn't mean IPV6 stops working. It simply means your server will try to connect using IPV4 first.

Good luck.
