### ISSUE TITLE
timeout for Dokodemo-Door

### ISSUE THREAD

**Issue by APT-ZERO** [alireza0/x-ui#1200]
سلام
توی ورودی Dokodemo-Door یه آپشن timeout هست که خوبه ادش کنید به پنل

https://xtls.github.io/Xray-docs-next/en/config/inbounds/dokodemo.html#dokodemo-door

تشکر

**Comment by alireza0** [comment]
درود بر شما
برای افزودن انتخاب شد و در زمان مناسب انجام میشه

**Comment by alireza0** [comment]
کد اضاقه شد و در نسخه بعد قابل استفاده خواهد بود
