### ISSUE TITLE
Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

### ISSUE THREAD

**Issue by KvizadSaderah** [alireza0/x-ui#1202]
i'm currently facing issue: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

i have 2 instance, using one bot API key for notifications
currently logged to one of them, and changed port
nothing serious, but in logs i've got spam of this error

```
2024/04/25 18:42:19 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024/04/25 18:42:19 Failed to get updates, retrying in 3 seconds...
```

everything was latest version

and with current port change second instance failed with same error. 
I edit `x-ui.db` set to `false` tg bot, and removed API key, restarted, but this didn't help.

any ideas the what is happening?

**Comment by KvizadSaderah** [comment]
aha, with db changed port back, second instance become active. :|

not sure how tg bot and panel port is connected, but it is how it is

**Comment by alireza0** [comment]
Each panel should use separated tg api.
Please first stop the first one and then start the new one if you want to change the server
