### ISSUE TITLE
Editing “Listening IP” without access to the control panel.

### ISSUE THREAD

**Issue by poznavatel** [alireza0/x-ui#1203]
I added “127.0.0.1” to the “Listening IP” line in the control panel with the intention of connecting through localhost via SSH, but it didn’t work (I don’t know why). Right now I can't return an empty field. Does anyone know how to do this via SSH by editing the files? I didn't find the "Listening IP" parameter in the files.

**Comment by alireza0** [comment]
Edit the database with proper application like sqlite3 (cli) or an app with GUI.
Alter the `settings` table and change the proper value directly. Then restart the x-ui

**Comment by poznavatel** [comment]
> Edit the database with proper application like sqlite3 (cli) or an app with GUI. Alter the `settings` table and change the proper value directly. Then restart the x-ui

More detailed instructions?
Where is the *.db file located?

**Comment by alireza0** [comment]
```bash
/etc/x-ui/x-ui.db
```
