### ISSUE TITLE
ریورس پنل به پنل 

### ISSUE THREAD

**Issue by rezahaddady** [alireza0/x-ui#1208]
سلام و عرض ادب
ریورس پنل به پنل زدم همه چی خوبه
ولی تو اینستا ویدیو ها لگ دارن و فریز میشه ویدیو
کانفیگ پورتال بهترین روشش چیه
من vmess tcp http header
زدم کانفیگ پورتال رو
میشه بگین بهترین کانفیگ پورتال چطوری باید
زده شه؟؟!

**Comment by alireza0** [comment]
درود بر شما
این پرسش شما در مورد پنل نیست و باید روش های مختلف رو تست کنید.
مشکلات اینچنینی مربوط به نحوه تنظیم هسته است و در گروه ها و فوروم های دیگه جوابشون رو میتونید پیدا کنید.
