### ISSUE TITLE
ساخته نشدن کوکی session

### ISSUE THREAD

**Issue by mahdi14541380** [alireza0/x-ui#1209]
سلام 
تو ورژن جدید کوکی session ساخته نمیشه و کتابخونه pyxui دیگه نمیتونه پنل شمارو ارائه بده 
چجوری میتونم این مشکلو حل کنم؟

**Comment by alireza0** [comment]
درود بر شما
کتابخونه مورد استفاده شما باید با تغییرات جدید بروزرسانی بشه. کوکی جدید با اسم x-ui در سمت کاربر ساخته میشه

**Comment by mahdi14541380** [comment]
اخه کوکی x-ui اطلاعات ذخیره نمیکنه و تو بخش login میمونه

**Comment by mahdi14541380** [comment]
> درود بر شما کتابخونه مورد استفاده شما باید با تغییرات جدید بروزرسانی بشه. کوکی جدید با اسم x-ui در سمت کاربر ساخته میشه

اخه کوکی x-ui اطلاعات ذخیره نمیکنه و تو بخش login میمونه
