### ISSUE TITLE
ارور database is locked

### ISSUE THREAD

**Issue by amirzare021** [alireza0/x-ui#1210]
سلام وقتتون بخیر

چند روزه من داخل پنل ارور database is locked میگیرم و هرکاری میکنم برطرف نمیشه
سرور عوض کردم بک اپ اوردم بالا بازم ارور داد
سرور جدید ساختم اینباند هارو تک تک انتقال دادم بازم روز بعد ارور داد
لاگس سرور هم الان خدمتتون ارسال میکنم

ممنونم میشم راهنمایی بفرمایید
![image](https://github.com/alireza0/x-ui/assets/54991185/cf19a7b8-ef5d-4fcd-8de8-03cb498f26ec)

**Comment by amirzare021** [comment]
![image](https://github.com/alireza0/x-ui/assets/54991185/5e2458ad-df86-4b75-b161-3163eda3fa2c)
اینم مشخصات پلنه
داخل گیت هاب 3x-ui نتونستم ایشو باز کنم و گروه مشکلاتشون هم گویا بسته شده

**Comment by alireza0** [comment]
درود بر شما
سرعت هارد دیسک سرور شما مشکل داره و برای امکانات و حجم کاربرهای شما مناسب نیست.

**Comment by amirzare021** [comment]
سلام مجدد
با افزایش هارد دیسک مشکل حل میشه آیا؟

**Comment by alireza0** [comment]
سرعت با افزایش حجم درست نمیشه.
اگر از دیتاسنتر شلوغی استفاده میکنید، بهتره نوع هارد رو NVME و یا حداقل SSD انتخاب کنید

**Comment by amirzare021** [comment]
ممنونم از راهنمایی شما
