### ISSUE TITLE
خطای ۵۰۰ روی سرویس سابسکریپشن

### ISSUE THREAD

**Issue by mohsen1365bo** [alireza0/x-ui#1211]
سلام و وقت بخیر
روی سرویس سابسکریپشن کاربر ها خطای ۵۰۰ میگیرن ولی لینک جیسون سابسکریپشن بدون مشکل کار میکند
هیچ ایده ای دارید که مشکل از کجا میتونه باشه
لاگ خاصی هم روی سرور نمیبینم که باشه در رابطه با این خطای ۵۰۰
تشکر

**Comment by mohsen1365bo** [comment]
ببخشید لیبل رو به نظر اشتباه انتخاب کردم باید لیبل سوال را انتخاب میکردم

**Comment by alireza0** [comment]
درود بر شما
اگر از نسخه جدید استفاده میکنید و اینباند شما از قدیم مونده، تنظیمات لازم برای grpc و ws رو انجام بدید.
برای نمونه، authority در grpc الزامیه و اگر نباشه این خطا رو داریم.

**Comment by mohsen1365bo** [comment]
خیلی ممنون
مشکلم حل شد
