### ISSUE TITLE
اضافه کردن حالت ساده و پیشرفته به پنل

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1212]
عرض سلام و خسته نباشید.
با توجه به اینکه خیلی از کاربر ها درخواست تنظیمات پیشرفته داشتن و همچنین با توجه به نظر شما درمورد اینکه پنل ساده و برای عموم قابل استفاده باشه ،این ایده به ذهنم رسید که هر دو اینها روی پنل باشن
به این صورت که پنل یه حالت ساده و یک حالت پیشرفته داشته باشه
با فعال کردن گزینه ی پیشرفته ، تنظیمات خاص و پیشرفته مربوط به اون بخش ظاهر بشه و با غیرفعال بودنش ، پنل به شکل فعلی و با تنظیمات ساده تری ظاهر شه و حالت پیش فرض هم رو حالت ساده باشه.
اینجوری دیگه پنل هم شلوغ و پیچیده نمیشه.
در اخر تشکر میکنم از زحمات شما ، میدونم که گفتن اینا به حرف سادست و اجرا کردنش قطعا زمان بر هست.
فقط صرفا ایده هامون رو میگیم ، شاید اینجوری بتونیم کمکی کنیم.

**Comment by alireza0** [comment]
درود بر شما
ایده تون جالبه و میشه بهش فکر کرد.
ولی در حال حاضر این پنل به شدت جزئیات داره و برای ساده سازیش هیچ منطقی توی ذهنم نمیتونم بیارم.
اگر بتونم حتما ایده شما رو در نظر میگیرم.
سپاسگزارم
