### ISSUE TITLE
سرتیفیکیت کلودفلر

### ISSUE THREAD

**Issue by alirezani** [alireza0/x-ui#1214]
سلام خسته نباشید 

چرا سرتیفیکیت هایی که به صورت 15 ساله از کلودفلر گرفته میشود و به سرور منتقل می کنیم جواب نمی دهد.حتی تمام مسیر ها درست انجام میشود

**Comment by Alireza78na** [comment]
دقت کنید که فایل ها با فرمت .pem ذخیره شن.
همچنین فایل های publickey و privatekey به درستی تنظیم شن

**Comment by alirezani** [comment]
ممنون میشم راهنمایی بیشتری کنید
