### ISSUE TITLE
Recursively sort Xray config before saving

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [alireza0/x-ui#1218]
سلام و تشکر از زحمات ارزشمند علیرضای عزیز،

پیشنهادی داشتم و اون اینکه آیا خوب نیست جهت مقایسه راحتتر و سریعتر کانفیگهای مختلف و ملاحظه راحتتر تغییرات در قسمت  Xray Config، به محض فشردن دکمه save،  کل کانفیگ که یه nested json object هست، بصورت recursive (یعنی تا سطح فیلدها) و  بصورت الفبایی  مرتب سازی بشه و بعد save بشه.

اینطوری تقدم و تاخیر دستکاری اِلِمان های کانفیگ از طریق واسطه کاربری در فرمت کانفیگ نهایی تاثیری نخواهد داشت. البته میدونم که از لحاظ کارکردی/functional مثلن برای هسته xray  اینکار تاثیری نداره، ولی شکل کانفیگ بصورت استاندارد درمیاد و مقایسه/diff  آسونتر میشه که در کم باگ تر شدن کانفیگ ها فکر کنم موثر باشه.

فکر کنم قابلیت ارزشمندی هست که نسبتا راحت و بصورت کم باگ قابلیت پیاده سازی داره.

با تشکر.

**Comment by alireza0** [comment]
درود بر شما
زنده باشید

ممنونم از پیشنهادتون.
با توجه به مدل json که ترکیبی از Object ها و Array هاست این کار پروسس زیادی میخواد.
سود اینکار فقط زیباییه و تاثیر خواصی نداره. این کار نه تنها باگ رو کم نمیکنه بلکه روند مرتب سازی ممکنه باگ اضافه کنه.
برای مقایسه بهتره از ابزارهای مقایسه json استفاده کنید.
