### ISSUE TITLE
مشکل لود نشدن عکس و ویس در واتساپ با ip6

### ISSUE THREAD

**Issue by aboozar1368** [alireza0/x-ui#1222]
سلام مهندس وقتی با ip6 با متصل میشم مشکل لود شدن ویس و عکس در واتساپ دارم نمی تونم عکس بفرستم نه می تونم دانلود کنم باید چکار کنم ممنون 
از vless tcp استفاده میکنم

**Comment by aboozar1368** [comment]
شما خیلی انسان بزرگواری هستید ممنونم از اینکه جواب دادید
    On Friday, May 3, 2024 at 03:42:45 PM GMT+3:30, pulsarice ***@***.***> wrote:  
 
 


یه پارامتر workers هم داره که می‌گن بهتره مساوی تعداد هسته پردازنده باشه. سرور من ۲ تا هسته داره. با ۱ و۲ تست کردم، فرق چندانی ندیدم.
اینم تست سرعت منه، با warp zerotrust و یکبار هم مستقیم بدون وارپ
***@***.***:~# curl -w '%{speed_download}\n' -o /dev/null http://speed.cloudflare.com/__down?bytes=300000000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  286M    0  286M    0     0   240M      0 --:--:--  0:00:01 --:--:--  240M
252100840
***@***.***:~# curl -w '%{speed_download}\n' -o /dev/null --socks5-hostname 127.0.0.1:10808 http://speed.cloudflare.com/__down?bytes=300000000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  286M    0  286M    0     0  72.5M      0 --:--:--  0:00:03 --:--:-- 72.6M

**Comment by Mad880** [comment]
با سلام

راهی هست که فقط واتساپ و اینستاگرام از IPv4 استفاده کنن؟ لطفا راهنمایی کنید ممنون میشم

**Comment by Mad880** [comment]
> بله. اول یک outbound درست کنید به این شکل ![image](https://private-user-images.githubusercontent.com/5326305/327871223-3c67249c-90f3-4451-84c3-434bb05fb8f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3Njc2NTQsIm5iZiI6MTcxNDc2NzM1NCwicGF0aCI6Ii81MzI2MzA1LzMyNzg3MTIyMy0zYzY3MjQ5Yy05MGYzLTQ0NTEtODRjMy00MzRiYjA1ZmI4ZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMjAxNTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjc3ZDRmYzc3M2Q5M2Y5NzE4M2FjZDU1OWFkZDNhZGU5MzMwMDZjNmIyMDQzYjI5ZGY2MTJjZDRhZWEyYmVmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8TuO4M-yspQx-Dj8YSfj-Ab89xk0cjhliYhSiBwOVoY)
> 
> ```
>   {
>     "tag": "direct-ipv4",
>     "protocol": "freedom",
>     "settings": {
>       "domainStrategy": "UseIPv4"
>     }
>   }
> ```
> 
> بعد توی routing اینو اضافه کنید ![image](https://private-user-images.githubusercontent.com/5326305/327871453-9672fb29-d1fb-4cfa-bbe6-f48b63213a02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3Njc2NTQsIm5iZiI6MTcxNDc2NzM1NCwicGF0aCI6Ii81MzI2MzA1LzMyNzg3MTQ1My05NjcyZmIyOS1kMWZiLTRjZmEtYmJlNi1mNDhiNjMyMTNhMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMjAxNTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU1NGE1MTAyYzM3NDY5MDQzZjkyOWRhOTdhZmM4NWRlOGNkZTU4ZmU0ZjE0NjQyMTFiZmVjYTQ5NzQzOTg1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KQ0pkclNUz1BvTUOWLm1CqFuwtfs8QE_ppLo-O6vORU)
> 
> ```
>   {
>     "type": "field",
>     "domain": [
>       "geosite:instagram",
>       "geosite:whatsapp"
>     ],
>     "outboundTag": "direct-ipv4"
>   }
> ```
> 
> محل این قاعده روتینگ هم مهمه. یه جایی اون بالاها بعد از api باشه خوبه.

ممنون از جوابتون. من اینکارو انجام دادم ولی باز هم مشکل داره.

![Screenshot 2024-05-04 000030](https://github.com/alireza0/x-ui/assets/69681529/b6499b16-6422-4629-b02d-8fd1404fcd7d)

![Screenshot 2024-05-04 000053](https://github.com/alireza0/x-ui/assets/69681529/e49bda6b-f7a3-4e0a-a47d-cccbcc12f227)

![Screenshot 2024-05-04 000114](https://github.com/alireza0/x-ui/assets/69681529/1d1d06c1-ccfe-41e3-a3b4-0ddf09b04387)

![Screenshot 2024-05-04 000146](https://github.com/alireza0/x-ui/assets/69681529/2d890883-8379-44af-be46-fb0c6226a012)


مشکل چیه؟

**Comment by Mad880** [comment]
ممنون از پیشنهادتون ولی `/usr/local/x-ui/access.log` اصلا وجود نداره! 

![image](https://github.com/alireza0/x-ui/assets/69681529/853b8839-cb44-4694-aaa2-73c148f4aa39)

**Comment by Mad880** [comment]
بله چک کردم اما هیچ اروری نبود حتی ایپی فیسبوک رو هم accepted زده بود. نمیدونم مشکل چیه پیام رد و بدل میشه ولی عکس و استیکر مشکل داره.
لازمه بگم که اینستاگرام هیچ مشکلی نداره فقط واتساپ داره اذیت میکنه.

**Comment by Mad880** [comment]
نه نوشته نشده بود که به چه اوتباندی رفته. مشکل چی میتونه باشه؟

**Comment by Mad880** [comment]
بله sniffing روشنه و v2ray هم تنظیم کردم 

`accepted tcp:www.google.com:443 [inbound-27079 -> IPv4] email: gwfl3a6tq
accepted udp:1.1.1.1:53 email: gwfl3a6tq
accepted tcp:157.240.251.61:443 email: gwfl3a6tq
accepted udp:1.1.1.1:53 email: gwfl3a6tq
accepted udp:178.215.228.24:123 email: gwfl3a6tq
accepted tcp:157.240.251.60:443 email: gwfl3a6tq`

**Comment by Mad880** [comment]
من داشتم از tcp برای کانفیگ ها استفاده میکردم اومدم امتحانی از کانفیگ websocket استفاده کردم مشکل به طور کلی برطرف شد. 

در کل میخواستم از شما تشکر کنم بابت وقتی که گذاشتید ممنونم واقعا

**Comment by Mad880** [comment]
بله

**Comment by Mad880** [comment]
پس حتما tls رو فعال میکنم

**Comment by Aryas78** [comment]
چجوری باید فعال کرد؟
