### ISSUE TITLE
حذف اکانتها

### ISSUE THREAD

**Issue by hamedm94** [alireza0/x-ui#1224]
اگر امکانش هست لطفا" قابلیت حذف کلاینت ها را  به صورت یکجا و انتخابی به طوری که چندین کلاینت همزمان بتوان حذف کرد را به پنل اضافه کنید. برای مثال حذف 20 اکانت باید 20 بار کلیک و به صورتی تکی حذف شوند. اگر تعداد اکانتها بیش از این باشد این کار بسیار مشکل خواهد بود.

**Comment by alireza0** [comment]
متاسفانه با ساختار و پلتفرم قدیمی این فریمورک نمیشه کار رو استیبل درآورد. قبلا تلاش شده براش و به نتیحه درستی نرسیده.
