### ISSUE TITLE
سرور سایت Gcore

### ISSUE THREAD

**Issue by MoeinNS** [alireza0/x-ui#1225]
سلام وقت بخیر
من از سایت Gcore سرور گرفتم پنل نصب میشه ولی بالا نمیاد اصلا برای پنل ثنایی هم به همین صورته
اگه نیاز باشه اطلاعات سرور رو میفرستم براتون

**Comment by Alireza78na** [comment]
چک کنید ایپیتون فیلتر نباشه ( مثلا باVPN وارد شید) و به تست پینگ بسنده نکنید
و اینکه چ کنید پورت مورد نظر روی سرور باز باشه
فک نمیکنم مشکلی از سمت پنل باشه
