### ISSUE TITLE
وارپ

### ISSUE THREAD

**Issue by ali90500** [alireza0/x-ui#1226]
سلام
وقت به خیر
ببخشید من میخوام یک اپ اندروید (اپ pi network) رو داخل قوانین وارپ قرار بدم
میشه بگین چی باید بنویسم؟

**Comment by Alireza78na** [comment]
باید اول از طریق نرم افزارهایی که ترافیک رو نشون میدن چک کنید از چه دامنه یا ایپی هایی استفاده میکنه
یا اگه وبسایت خاصی داره ، معمولا با قرار دادن دامنه وبسایت مشکل حل میشه
یا اینکه اگه سرویس معروفی هست ، ممکنه توی Geosite ها باشه.
میتونید از گوگل و ابزار های انلاین هم کمک بگیرید.

درهرصورت باید دامنشو پیدا کنید.
