### ISSUE TITLE
فعال نشدن کزینه های route only و meta data

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#1227]
با سلام
گزینه های route only و meta date only در قسمت اسنایفینگ رو وقتی فعال میکنی و ذخیره میکنی بعد باز گشت دیده میشه فعال نشده
چندین بار در چند سرور تست شد و مشکل پا برجا بود
با تشکر

**Comment by ckn4** [comment]
Can't use these features either. I try to open these options, but when I close the opt panel, switches change to default.

**Comment by ckn4** [comment]
> https://github.com/ckn4/x-ui/commit/42acdd641ae201068e5fdd43b3a0aefafc9d091a
There's a little problem here.

**Comment by alireza0** [comment]
@ckn4 It is fixed now. Re-released in 1.8.3 
Please update
@aliamg1356

**Comment by alireza0** [comment]
There is another bug in showing these configuration.
It is now fixed and  will be available in next version

**Comment by aliamg1356** [comment]
> There is another bug in showing these configuration. It is now fixed and will be available in next version

ممنونم
پس منتظر آپدیت بعدی باشیم
چون فرموده بودین دوباره آپدیت کنیم من آپدیت زدم تغییری پیدا نکرد 
بعد دیدم فرمودین برای آپدیت بعدی صبر بشه
