### ISSUE TITLE
How to install x-ui using docker + nginx reverse proxy?

### ISSUE THREAD

**Issue by flightlover** [alireza0/x-ui#123]
Hi. I've installed nginx on my server for doing reverse proxy. When I install x-ui with docker method I get this error:

`Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use.
`
or
`Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use.
`

That is because nginx uses 443 and 80 port. [screenshot of terminal:]

<img width="515" alt="1" src="https://user-images.githubusercontent.com/125610584/228954705-24bcf6b5-ac80-4172-b7a4-5c16538128ea.png">

What should I do? I definitely want to set port 443 in my v2ray configs not every other https ports e.g. 2053 or ... .

**Comment by alireza0** [comment]
Hello @flightlover 
It is not clear what you are going to do!
If you want to use nginx for doing reverse proxy toward xray, you should bind them to separate IP address:
nginx: `PublicIP:443`
xray: `127.0.0.1:443`

**Comment by flightlover** [comment]
Thanks.
Yes I want to use nginx for doing reverse proxy toward xray. The problem is herer: in installing using docker, the container needs to use 443 port but this port is used by nginx in advance and it signals an error

**Comment by alireza0** [comment]
@flightlover 
Please read more about docker and nginx or use ChatGPT ;)
Provided code is a simple example only.
Documentations are available widely!
