### ISSUE TITLE
how to use rest api ?

### ISSUE THREAD

**Issue by scriptvpskita** [alireza0/x-ui#1230]
i try to login with

_curl -X POST -d '{"username": "my user", "password": "my pass"}' http://my_domain:my_port/login_

but its shown an error
_{"success":false,"msg":"Username is required","obj":null}_

**Comment by dmitriykara** [comment]
You need to use x-www-url-encoded-form

`curl --location 'http://<host>:<port>/login' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'username=<your user>' \
--data-urlencode 'password=<your pass>`
