### ISSUE TITLE
باز کردن سایت

### ISSUE THREAD

**Issue by mahdisalehivand** [alireza0/x-ui#1231]
دو تا سرور از هتزنر بدون وارپ یکی spotify میاره یکی نمیاره داستان چیه؟
تمام تنظیمات پنل و اینباند هم مثل همه

**Comment by mahdisalehivand** [comment]
> آی پی یکیشون از قبل توسط اسپاتیفای بلاک شده. عجیب نیست. سرور منم اوایل بدون وارپ اسپاتیفای رو باز می‌کرد. الان نه.

وارپ هم میزنم x-ray کرش میکنه ارور نمیده ولی پینگ handshake نمیده insta و whatsapp باز نمیشه ولی تلگرام باز میشه یا بعد از 5 دقیقه یا 10 دقیقه خودش درست میشه یا همون لحظه x-ray رو reset کنم درست میشه

وارپ هم نزنیم youtube music با spotify باز نمیشه!!!!

**Comment by Alireza78na** [comment]
فعلا این اسپاتیفای کلا داستان درست کرده واسه همه
علت باز نشدنش اینه که این سرویس ها استفاده از vpn واسشون قابل قبول نیست و بعد یه مدتی معمولا ایپی سرور هارو بلاک میکنن
تنها راهش تغییر ایپیه ( وارپ و ... ) که اونم فعلا مشکلات خودشو دارعه
