### ISSUE TITLE
Wireguard Peer limitation

### ISSUE THREAD

**Issue by newman222** [alireza0/x-ui#1232]
سلام علیرضا جان
خدا قوت

یه درخواست داشتم ، 

امکانش هست برای وایرگارد ، مثل V2ray  روی یک اینباند بیایم چندین Peer تعریف کنیم و برای هر کدوم تاریخ انقضا و کنترل حجم خودشو بزاریم ؟
و اینکه برای add کردن peer به وایرگارد با API دستوری پیدا نکردم

خوشحال میشم راهنماییم کنید 

یک دنیا ممنون

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم
مدل کار وایرگارد متفاوته. این موضوع توسط هسته پشتیبانی نمیشه.
بهتره برای این کار برای هر peer یک اینباند مجزا بسازید.
