### ISSUE TITLE
iptables tunnel ipv6

### ISSUE THREAD

**Issue by amirzare021** [alireza0/x-ui#1233]
با سلام و احترام
یه سوال داشتم
چجوری میتونم با iptables تونل ipv6 بزنم
 sysctl net.ipv4.ip_forward=1
 iptables -t nat -A PREROUTING -p tcp --dport 22 -j DNAT --to-destination*
 iptables -t nat -A PREROUTING -j DNAT --to-destination *
iptables -t nat -A POSTROUTING -j MASQUERADE
با این تنظیمات میشد تونل ipv4 زد و ترافیکو به سرور خارج فرستاد از سرور ایران
ولی چون در این روش ای پی سرور خارج که فیلتر شده رو نمیشه استفاده کرد
میخوام تونل ipv6 بزنم
چجوری امکانش هست؟
یه سری دستورات هوش مصنوعی داد که متاسفانه کار نکرد
 ip6tables -t nat -A PREROUTING -p tcp --dport 22 -j DNAT --to-destination*
 ip6tables -t nat -A PREROUTING -j DNAT --to-destination *
ip6tables -t nat -A POSTROUTING -j MASQUERADE

و
ip -6 route add * via * dev eth0

این دو دستور رو هوش مصنوعی داد و متاسفانه کار نکرد
شما روشی بلد هستین جناب غلیرضا؟

**Comment by alireza0** [comment]
درود بر شما
این موضوع ربطی به پنل نداره
لطفا با یک کارشناش شبکه مشورت کنید
