### ISSUE TITLE
پنل عالی s-ui

### ISSUE THREAD

**Issue by nsa14** [alireza0/x-ui#1235]
اقاعلیرضا سلام و خداقوت مَرد

پنل s-ui که زحمتش رو کشیدی
 واقعا بینظیره
روش ساخت کانفیگ هاش عالیه . لطفا ادامه بده و تکمیلش کن
خیلی بهتر از این پنله

هر کمکی از دست ماهم بر بیاد با جان دل درخدمتیم همراهت هستیم استاد

**Comment by alireza0** [comment]
درود بر شما
چشم
در حال انجامه
سپاسگزارم
