### ISSUE TITLE
کار نکردن اینباند های قدیمی روی 1.8.10 به بعد

### ISSUE THREAD

**Issue by rezakhosh78** [alireza0/x-ui#1236]
سلام وقت بخیر و خسته نباشید. اینباندهای قدیمی روی ورژن 1.8.10 به بعد کار نمیکنن در صورتی که روی 1.8.9 به پایین کار میکنن. جالبه که اینباند جدید که میسازی روی 1.8.10 کار میکنه ولی اینباندهایی که قبلا وجود داشتن نه. مشکل چطور حل میشه؟ تشکر

**Comment by emadtoranji** [comment]
اگر حداقل نسخه xray برنامتون 1.8.10 متصل میشه.

**Comment by alipour66m** [comment]
باید هاست و دامنه اصلی هم نام باشن
اگر دامنه جدیدی بذاری قبول نمیکنه

**Comment by ramram2020** [comment]
مشکل از اضافه شدن null بعد از کانفیگ از سمت کاربر هست. میتونید دستی پاکش کنید درست میشه. البته در ورژن جدید این باگ رفع شده

**Comment by ramram2020** [comment]
یعنی اشتباها در قسمت path پر میشه از سمت کاربر . ورژن جدید نصب کنید درست میشه مشکل. یا اینکه دستی قسمت path را خالی کنید
