### ISSUE TITLE
تغییر در پنل

### ISSUE THREAD

**Issue by mr-bz** [alireza0/x-ui#1237]
سلام چطور میتونم توی بک اند یا فرانت پروژه تغییر ایجاد کنم ، نمیخام درگیر کامپایل گو بشم برا همین اگه راهنمایی کنید چطور میتونم html سایتو تغییر بدم

**Comment by mr-bz** [comment]
واقعا من نیاز به ادیت دارم لطفاً یه راهنمایی کن

**Comment by alireza0** [comment]
بخش فرانت این نرم افزار داخل خود فایل اجراییه.
برای تغییر باید کد رو بتونین روی کامپیوتر خودتون بیارید و بیلد دستی بگیرید

**Comment by mr-bz** [comment]
خیلی ممنون ،برای بیلد کردنش اموزشی موجود نیست؟

**Comment by alireza0** [comment]
لطفا جستجو کنید.
آموزش و ویدیو های زیادی برای هر بخش موجوده.
ولی کار یک آموزش و یک شب نیست و مطالب زیادی رو باید بخونید.

**Comment by mr-bz** [comment]
شما چقدر هزینه میگیرید یک ای پی ای رو و دکمه شو حذف کنید 
اگه ممکنه ای دی تلگرام بدید بیام پی پی صحبت کنیم
