### ISSUE TITLE
باگ لینک سابسکرپشن بعد ار نسخه 2.2.6 سنایی

### ISSUE THREAD

**Issue by iamomid1997** [alireza0/x-ui#1241]
با درود و خداقوت
من تا نسخه 2.2.6 سنایی میتونستم با یه ساب آیدی دوتا کانفیگ تانل (vless+http) و سی دی ان (vless+ws+tls) رو روی v2rayNG یا هر کلاینت دیگه ای دریافت کنم ولی از نسخه 2.2.6 به بعد سنایی وقتی یه ساب آیدی رو به دوتا کلاینت تانل و سی دی ان میدم دیگه لینک ساب کار نمیکنه و ارور failed رو ‌v2rayNG نمایش میده.
وقتی هم پنل رو برمیگردونم به ورژن 2.2.6 دوباره لینک ساب کار میکنه.
لطفا این ارور رو به Developer پنل سنایی اطلاع بدید من سر این موضوع نمیتونم پنل رو آپدیت کنم

**Comment by alireza0** [comment]
درود بر شما
پروتکل ها تغییرات زیادی داشتن. باید اینباند هاتون رو ویرایش و بروز رسانی کنید.
