### ISSUE TITLE
نصب پنل روی داکر

### ISSUE THREAD

**Issue by navid85a** [alireza0/x-ui#1243]
سلام 
چرا وقتی پنل شما یا ثنایی رو روی داکر نصب میکنم ووارد پوشه داکر میشم نمیتونم کامند لاین رو بالا بیارم . برای پنل شما اصن امکان پذیر نیست و با پنل ثنایی هم ارور نصب os alpine  میده. مشکل از کجاست ؟؟؟؟ چرا وقتی پنل ها روی داکر میان بالا اصلا نمیشه 2 تا کامند x-ui/3x-ui اجرا کرد. 
ضمنا پنل گرافیکی به درستی بالا میاد...
ممنون میشم راهنمایی کنید.

**Comment by alireza0** [comment]
درود بر شما
چون این اسکریپت برای نسخه داکر ارائه نشده.
اگر به صورت پیشرفته دارید استفاده میکنید و میخواید حتما داکر رو داشته باشید، بقیه کار ها رو باید به شکل دیگه ای مدیریت کنید.
