### ISSUE TITLE
fallbackTag for balancer objects

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#1244]
Hi
It would be nice to have a fallbackTag for balancer object in UI (specially when using leastLoad/leastPing)
If no fallbackTag is set and none of the outbounds specified by selector are available, the requests will go to the first outbound (usually freedom/Direct).

https://xtls.github.io/config/routing.html#balancerobject

```
{
  "tag": "balancer",
  "selector": [],
  "fallbackTag": "outbound",
  "strategy": {}
}
```

**Comment by alireza0** [comment]
Hi,
Thank you for your suggestion.
This feature is now added and will be available in next release
