### ISSUE TITLE
xray exit code 2

### ISSUE THREAD

**Issue by LoicMaster** [alireza0/x-ui#1248]
**Describe the bug**
Xray server halts after adding an inbound, restarts crash with the following message "github.com/xtls/xray-core/main/main.go:22"

**To Reproduce**
1. Go to Inbounds
2. Create a Vless - xtls inbound
3. Try to connect (Connection refused)
4. Restart xray server (error message)

**Expected behavior**
Inbound should accept connections

**Additional context**
Latest release from dockerhub

**Logs**
2024/05/10 14:10:34 ERROR - X-UI: Failure in running xray-core: exit status 2
2024/05/10 14:10:34 DEBUG - XRAY: github.com/xtls/xray-core/infra/conf.(*Config).Build(0xc000196a80)
2024/05/10 14:10:34 DEBUG - XRAY: , 0x2b?}, {0xc0000457e8?, 0xc000168890?, 0x0?})
2024/05/10 14:10:34 DEBUG - XRAY: ?
2024/05/10 14:10:34 DEBUG - XRAY: 0xc0000b6c00
2024/05/10 14:10:34 DEBUG - XRAY: ,
2024/05/10 14:10:34 DEBUG - XRAY: ?
2024/05/10 14:10:34 DEBUG - XRAY: 0xc00021ef78
2024/05/10 14:10:34 DEBUG - XRAY: {
2024/05/10 14:10:34 DEBUG - XRAY: (
2024/05/10 14:10:34 DEBUG - XRAY: encoding/hex.Decode
2024/05/10 14:10:34 DEBUG - XRAY: ]:
2024/05/10 14:10:34 DEBUG - XRAY: running
2024/05/10 14:10:34 DEBUG - XRAY: [
2024/05/10 14:10:34 DEBUG - XRAY: 1
2024/05/10 14:10:34 DEBUG - XRAY: goroutine
2024/05/10 14:10:34 DEBUG - XRAY: runtime error: index out of range [8] with length 8
2024/05/10 14:10:34 DEBUG - XRAY: panic:
2024/05/10 14:10:34 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json

**Comment by alireza0** [comment]
@LoicMaster
Please provide more information.
Which configuration do you use and by which version of x-ui/xray ?
Which type of configuration did you try to add ?
