### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by mostafa5804** [alireza0/x-ui#125]
سلام و خسته نباشید
یه درخواست داشتم
امکانش هست favicon اضافه کنید ؟ ( درخواست فانتزی هست و ضروری نیست البته ولی اون کره کنار دامین نباشه بهتره)

ظاهرا باید در مسیر 
x-ui/web/html/common/head.html
تگ 
`<link rel="icon" type="image/png" href="{{ .base_path }}assets/favicon.png" />`

اضافه بشه که میشه
```
{{define "head"}}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/favicon.png">
    <link rel="stylesheet" href="{{ .base_path }}assets/ant-design-vue@1.7.2/antd.min.css">
    <link rel="stylesheet" href="{{ .base_path }}assets/element-ui@2.15.0/theme-chalk/display.css">
    <link rel="stylesheet" href="{{ .base_path }}assets/css/custom.css?{{ .cur_ver }}">
    <style>
        [v-cloak] {
            display: none;
        }
    </style>
    <title>{{ i18n .title}}</title>
</head>
{{end}}
```

وقتی favicon.png رو تو root بذارم درست بشه
اثرات chatgpt هست این درخواست😄 
تشکر

**Comment by alireza0** [comment]
درود بر شما

در واقع این قابلیت لاکچری برای وب سایت ها بیشتر استفاده میشه و نه برای پنل های راهبری.

ولی دم شما گرم! به چه چیزهایی توجه میکنید!
