### ISSUE TITLE
IR-ISP-Blocker

### ISSUE THREAD

**Issue by solidwar** [alireza0/x-ui#1250]
درود و سلام فراوان به جناب مهندس عزیز

توی تلگرام مشاهده کردم که یک ایرانی با شناسه @kiya6955 در کانال https://t.me/savechannelkiya6955 خودش خبر از افزونه بلاک isp داده که در گیت هابش https://github.com/Kiya6955/IR-ISP-Blocker میتونید امنیت و یا کار کردن این اسکریپت رو بفهمین( بنده که سوادشو ندارم...) 

لطفا اگر دیدید آپشن خوبی هست به پنل اضافه کنید

باتشکر ❤️

**Comment by alireza0** [comment]
درود بر شما
هر کسی این کار رو میتونه به روش خودش انجام بده.
دلیلش رو نمی فهمم!‌ به نظرم خیلی هم مفید نیست!
