### ISSUE TITLE
[FR] Modify port and security settings in subscriptions if X-UI is behind a TLS reverse proxy

### ISSUE THREAD

**Issue by vnxme** [alireza0/x-ui#1253]
Hi,

It is a known feature that one can connect to a VPN/proxy service provided by Xray Core and managed by X-UI both directly and indirectly, i.e. via a reverse proxy. Given the reverse proxy listens on port 443, the letter case may provide additional security (the VPN connection is visually identical to a regular website browsing), speed gains (traffic to/from 443/TCP is often prioritised compared to other irregular TCP and UDP traffic) and concentration (many connections served from single port accessible from the outside). A good example of how to make X-UI work behind nginx and provide WS/GRPC services is [here](https://github.com/GFW4Fun/x-ui-pro).

Subscription is yet another very useful feature of X-UI - no need to manually modify connections over and over on multiple apps and devices. However, if we combine the reverse proxy feature with the subscription feature, there is a problem: subscriptions can only deliver settings for direct connections and know nothing about the reverse proxy. In other words, to make the connections delivered by the subscription feature work behind the reverse proxy, one has to manually modify each connection and adjust a) port to 443, b) security settings to TLS, c) fingerprint source to one's preferred option. These required modifications defeat the original intention of the subscription feature - automation.

**UPDATE:** Please read [below ](https://github.com/alireza0/x-ui/issues/1253#issuecomment-2120638239)a bit more detailed explanation with screenshots.

I suggest there could be a checkbox in the connection (inbound) settings "run behind a TLS reverse proxy". If checked, a few additional input boxes could be shown including a reverse proxy port, a reverse proxy host, a fingerprint source. Finally, the subscription controller could take these settings into account for both sub and json streams.

Regards,

**Comment by X-Oracle** [comment]
@vnxme 

It is already implanted in subscription settings.

**Comment by vnxme** [comment]
@X-Oracle Hi, would you please be more precise on where to find such settigs?

I have X-UI v1.8.3. On Panel Settings -> Subscription there are the following inputs: Enable, Encode, Show Usage Info, Listen IP, Listen Domain, Listen Port (these listen directives aren't relevant to what I'm talking about above since they are used for subscription service binding, but not for proxy/VPN configuration), URI Path, Public Key Path, Private Key Path, Reverse Proxy URI and Update Intervals. On Panel Settings -> Subscription Json there are the following inputs: URI Path, Reverse Proxy URI, Fragmentation, Mux, Direct Country.

**Comment by X-Oracle** [comment]
Hi @vnxme,

 What I'm getting is that you want your configs to have different port than your original x-ray config.

In that case you should use `external proxy` option in inbound settings.

- Enable external proxy
- Then add your domain and reverse port in it.

- If you want you can add another proxy and add direct port to connect via direct too.

**Comment by vnxme** [comment]
@X-Oracle, very nice, thanks! 

I didn't know the external proxy feature is related to subscriptions. While this feature enables me to set both port number and security TLS, it doesn't allow to set serverName (expected it to be equal to the external proxy host by default) and fingerprint (I don't know whether it makes any difference to set or leave blank).

**Comment by X-Oracle** [comment]
> >I didn't know the external proxy feature is related to subscriptions
> 
> It was originally made for CDN based configs where we need diffrent port and address but we can use it to configure reverse proxy too.
> 
> 
> > it doesn't allow to set serverName (expected it to be equal to the external proxy host by default)
> 
> X-UI structure does not allow it.
> 
> We might need to have multiple configs in x-ray for multiple sni  (As single x-ray config does not allow multi sni).
> 
> In that case, user management will be difficult and might raise system resources for no reason.

**Comment by vnxme** [comment]
@X-Oracle, thank you very much for your detailed explanations!
