### ISSUE TITLE
لود بالانسر

### ISSUE THREAD

**Issue by aboozar1368** [alireza0/x-ui#1254]
سلام وقتتون بخیر لود بالانسر در پنل سنایی فقط در حالت رندوم کار میکنه در بقیه حالت ها درست کار نمیکنه

https://youtu.be/baPjx-YkP4E

**Comment by alirezani** [comment]
توی پنل علیرضا هم روی یکی از سرور ها گیر می کند حتی اگر لودبالانسر و رولی که نوشتی در قوانین مسیر یابی را پاک کنی .

**Comment by alireza0** [comment]
این کار اتوماتیک انجام میشه وقتی حالت leastPing یا leastLoad داشته باشیم. میتونید با انتخاب دکمه مریوطه زیر لودبالانسرها، تنظیمش رو هم عوض کنید
