### ISSUE TITLE
رنگ تم تیره

### ISSUE THREAD

**Issue by madar54** [alireza0/x-ui#1256]
با سلام خدمت بزرگان پنل چنانچه عالیجنابان رنگ پنل v2ray را به رنگ پنل sui تغییر دهند بسیار زیباتر خواهد شد و شکل و شمایل تم رم‌افزارهای شرکت ادوبی را خواهد داشت که جلوه زیباتری دارد با سپاس فراوان

**Comment by alireza0** [comment]
درود بر شما
برای انتخاب تم ها محدودیت از طرف فریمورک هست
