### ISSUE TITLE
محل ذخیره config.json

### ISSUE THREAD

**Issue by MR-Amoori** [alireza0/x-ui#126]
با سلام
موقعی که درخواست فایل بکاپ از ربات میدم همراه فایل دیتابیس یه فایل config.json هم ارسال میشه
میخواستم بدونم امکانش هست بجای اینکه فایل دیتابیس رو برای اینکه یکسری تغییرات دسته جمعی بدیم از این فایل config.json استفاده کنیم؟ چون فرمت json فرمت ساده تر و خوانایی بالایی داره.
و همچنین من فایل دیتابیس رو یه بار با نوت پد باز کردم و فقط یه سری تغییرات در قسمت ایمیل های یسری یوزر انجام دادم در همون فرمت اما مجدد وقتی در مسیر اصلی جایگذاری کردم و ریستارت کردم پنل رو ارور داد.
و اینکه اگر امکانش هست فایل json رو به جای فایل دیتابیس تغییر داد ، مسیرش در پروژه کجا هست؟

**Comment by alireza0** [comment]
درود بر شما
برای تغییر توی دیتابیس حتما باید از نرم افزار های ویرایش مخصوص که کار با sqlite رو ساپورت میکنن استفاده کنید.
فایل config.json فقط برای کسانیه که تنظیمات حرفه ای رو توی بخش تنظیمات xray-core اضافه کردند و میدونند چطور ازش استفاده کنند.
امکان استفاده این دو فایل به جای هم وجود نداره. کاربر هرکدوم جداست.
