### ISSUE TITLE
Duplicate UUID in Inbounds

### ISSUE THREAD

**Issue by sharif221** [alireza0/x-ui#1260]
**Describe the Bug**
The panel allows you to create two clients with the same UUID in one inbound.

**To Reproduce**
1. Create two clients with the same UUID in one inbound.

**Expected Behavior**
There should be a check for UUIDs within each inbound to prevent the creation of a new client with the same UUID as other clients within that inbound.

**Additional Context**
I discovered this issue while testing the API. I guess 3x-ui exhibits the same behavior.

**Comment by alireza0** [comment]
It is on the shoulder of Panel Admin.
It is not a public available website which is affordable to implement lots of checks.
