### ISSUE TITLE
مشکل قطع نشدن کاربر

### ISSUE THREAD

**Issue by ardev0** [alireza0/x-ui#1265]
علیرضا جان سلام امیدوارم خوب باشی. 
من چند مدل یوزر(client) بدون تاریخ و یا با تاریخ  و با محدودیت حجم 100m و 500m و 1g و 2g تعریف کردم توی پنل که حجم تموم میشه یوزر غیرفعال نمیشه.
بعد پنل دستی ریست میکنم یوزر قطع میشه ولی بازم توی پنل ایکونش فعال هست دکمه (button switch) منظورم هست.
اخرین ورژن پنل و وژن قبلی و xray
روی هر جفتش این مشکل هست  یعنی یورر حجمش تموم یشه قطع نمیشه و از اینور زمانشم تموم میشه قطع نمیشه .

داخل داکر هست روی حالت  network_mode: host یورز زمان بندی expire میشه ولی توی پنل همچنان دکمه enable هست و با حالت حجم درست لاگ نمیشه و خیلی کمتره  و البته به اون حجم هم میرسه بازم مشکل هست و قطع نمیشه

در حالتی که network_mode: host  کلا نباشه و پورت پنل و پورت mother inbound رو مپ کنیم هیچ کدوم غیر فعال نمیشه ولی حجم درست محاسبه میشه

علیرضای عزیز من تا 20 دقیقه هم منتظر موندم هیچ قطعی اتفاق نیفتاد. یوز قدیمی همچنان وصل هست و session ها بسته نمیشه .
دستی از توی پنل با دکمه سوییج غیر فعال میشه.

**Comment by alireza0** [comment]
درود بر شما
سویچ غیر فعال سازی با اتمام حجم/زمان در این پنل متفاوته و کاربرد جدایی داره.
اینکه کاربر قطع نمیشه مشکل هسته است. دستور ارسال شده به api هسته در این حالت اعمال نمیشه و کاربر به کار خودش ادامه میده تا زمانی که هسته session  رو ببنده.
حتی سویچ غیر فعال سازی هم همین روند رو انجام میده.
این مدت زمان در پروتکل های مختلف متفاوته، و برای حلش کار خاصی نمیتونیم انجام بدیم.
