### ISSUE TITLE
Inbound SockoptObject

### ISSUE THREAD

**Issue by APT-ZERO** [alireza0/x-ui#1267]
سلام
توی ورودی ها، قسمت sockopt وجود داره که قابلیت های خوبی داره
https://xtls.github.io/config/transport.html#sockoptobject
اگه میشه لطف کنید این بخش رو بصورت json بزارید که ادیت کنیم برای هر ورودی (از جمله ورودی دوکودمو)

میدونم در حال حاضر برخی از آپشن های sockopt برای برخی از ورودی ها موجود هست
اما اولا که تمام آپشن ها از جمله dialerProxy موجود نیست
دوما هیچ کدوم از همون آپشن ها برای dokodemo-door قرار ندادید
و در آخر اینکه اگر بصورت json باشن ui خلوت و تمیز تر میشه

با تشکر

**Comment by alireza0** [comment]
درود بر شما
استفاده از JSON فعلا در دست بررسیه. ولی پیشنهاد من به دوستانی که با json بلدن کار کنن اینه که بدون پنل هسته رو مدیریت کنن.
نمیدونم از ویژگی dialerProxy چه استفاده ای میخواید بکنید! ولی این ویژگی در خروجی ها پیاده سازی شده و معنی داره.

ویژگی‌هایی که معنی دارن و کاربرد عمومی داره ارائه شده و هدف بیشتر سادگی بوده.
استفاده از JSON نیازمند اطلاعات زیادیه که دانشنامه xray همه رو توضیح نداده.
