### ISSUE TITLE
امکان جدید در ربات تلگرام

### ISSUE THREAD

**Issue by MR-Amoori** [alireza0/x-ui#127]
با سلام
یک امکان دیگر اگر در ربات فعال کنید خیلی خوب میشه اینکه شخصی علاوه بر اینکه میتونه اطلاعات کانفیگ هایی که با یوزر نیم اون ساخته شده رو ببینه ، بتونه لینک کانفیگ هم بگیره

**Comment by alireza0** [comment]
درود بر شما
بله، توی نسخه جدید امکان ارائه لینک توسط backend نوشته شده ولی توسط بات هنوز قابل ارائه نیست.
در نسخه جدید با این قابلیت، امکان ارائه subscription اضافه شده.

با توجه به اینکه هدف کلی بات، فقط ارائه اطلاعات مصرف بوده ، اضافه کردن این قابلیت کمی محاسبات اضافه داره که باید بررسی کنم.

**Comment by smblue07** [comment]
سلام خسته نباشید. لطفا مواردی که قراره روی ربات اضافه بشه رو توی پنل تنظیناتشو قرار بدید که قابل فعال یا غیرفعالسازی باشه
شاید همه نیاز نداشته باشن که یوزر بتونه لینکشو بگیره 
ممنون از شما

**Comment by aliamg1356** [comment]
در ورژن جدید امروز یک باگ رو دیدم  قبلا طبق تنظیمات نزدیک به اتمام حجم یا مدت کاربر در ربات پیام میداد ولی در نسخه آخر برای من نداد و امروز متوجه شدم یکی از کاربران حجمش تموم شده  ربات در حاله کاره و بکاپ و اطلاعات سرور رو راحت میده ولی در مورد کانکشنها و اینباندها اصلا

**Comment by MR-Amoori** [comment]
> درود بر شما بله، توی نسخه جدید امکان ارائه لینک توسط backend نوشته شده ولی توسط بات هنوز قابل ارائه نیست. در نسخه جدید با این قابلیت، امکان ارائه subscription اضافه شده.
> 
> با توجه به اینکه هدف کلی بات، فقط ارائه اطلاعات مصرف بوده ، اضافه کردن این قابلیت کمی محاسبات اضافه داره که باید بررسی کنم.

درود، خسته هم نباشید
تشکر از تلاش شما
ممنون میشیم در آپدیت بعدی هم این موضوع پیاده سازی شود

**Comment by dev-ir** [comment]
یک مشکل این موضوع داراست 
ساب که ارائه میشه از دامنه و یا ای پی فعلی ارائه میشه و در صورتی که ایپی شما و یا دامنه شما هم توی لیست ( به ترتیب ) قرار بگیره عملا ساب هم از کار میوفته باید بخشی داشته باشیم که فرضا از ایپی جایگزین و یا دامنه جایگزین برای subscription استفاده کنه
