### ISSUE TITLE
اکانت تنظیم حجم و زمان برای کاربران ساکس و http

### ISSUE THREAD

**Issue by t-51** [alireza0/x-ui#1272]
سلام وقت بخیر 
اول اینکه میخواستم بدونم امکانش هست برای پروکسی های ساکس و HTTP حالت تعیین حجم و اینا موارد رو اضافه کنید ؟
چون به صورت پیش فرض فقط برای اینباند میشه محدودیت تعیین کرد نه کلاینت

**Comment by alireza0** [comment]
درود بر شما
هسته xray گزارش مصرف این کاربرها رو نمیفرسته و در نتیجه پنل نمیتونه محاسبه کنه.
میتونید از هسته sing-box با پنل s-ui استفاده کنید.

**Comment by t-51** [comment]
تداخل با x-ui نداره اگه باهم نصب کنیم؟

**Comment by alireza0** [comment]
مراقب پورت های تکراری باشید، تداخلی نداره.
