### ISSUE TITLE
آخرین وضعیت آپدیت اشتراک از سمت کلاینت

### ISSUE THREAD

**Issue by solidwar** [alireza0/x-ui#1273]
سلام جناب مهندس خداقوت @alireza0  
 درخواست یک ویژگی رو داشتم که نمیدونم امکان پذیر هست یا نه
این هست که کنار هر آیدی که یوزر باشه تایم آخرین آپدیت سابسکریپشن از سمت مشتری رو بنویسه

**Comment by alireza0** [comment]
درود بر شما
امکانش وجود داره ولی به صرفه نیست.
هزینه زیاد و کارایی کمی داره.
