### ISSUE TITLE
باگ در هسته xray

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#1274]
با سلام
در ورژنهای 1.8.12 و 1.8.13 هسته xray وقتی وایرگارد استفاده میشه با اتصال کاربر هسته به ارور میخوره و استوپ میشه
در گیت هاب مربوطه گزارش شد و جهت اطلاع دوستان اینجام میذارم
![Screenshot 2024-05-24 205012](https://github.com/alireza0/x-ui/assets/124570423/1e35aeb4-b4f0-4f7b-94fc-9e44eae442a8)

**Comment by AliBelali** [comment]
> با درود دوباره من فکر میکردم این از باگ هسته باشه اما امروز اتفاقی یک اوتباند وایرگارد روی ثنایی و پنل شما زدم باز پنل شما ارور داد و مجبورا ورژن رو آوردم رو 1.8.11 اما پنل ثنایی بدون مشکل کار کرد پس این مورد عملا یک باگ در پنل شماست ممنون

مشکل از هسته هست میتونید به لینک پایین مراجعه کنید
https://github.com/XTLS/Xray-core/issues/3388
