### ISSUE TITLE
سلام ایجاد اکانت با api موفق برمیگردونه اما ایجاد نمیشه (آبجکت نال)

### ISSUE THREAD

**Issue by moradpoor** [alireza0/x-ui#1275]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alireza0** [comment]
اکثر جواب های موفق بخش obj شون خالی میشه!
مشکلی نداره

**Comment by moradpoor** [comment]
مشکل این هستش که اکانت روی پنل اضافه نمیشه

**Comment by alireza0** [comment]
آیا داده های لازم رو دادین ؟
با استفاده از api داده های همون اینباند رو بگیرید و چک کنید
