### ISSUE TITLE
مشکل گرفتن سرتیفیکیت

### ISSUE THREAD

**Issue by Miladch2023** [alireza0/x-ui#1276]
با سلام. وقتی پنل نصب میشه و میخوام سرت بگیرم 
/usr/bin/x-ui: line 514: /root/.acme.sh/acme.sh: No such file or directory
/usr/bin/x-ui: line 515: /root/.acme.sh/acme.sh: No such file or directory
[ERR] issue certs failed,please check logs
این ارور ها رو دریافت میکنم

**Comment by alireza0** [comment]
درود بر شما
توی مراحل اول گرفتن گواهی، این فایل ایجاد میشه. مگر اینکه دستور رو رد کرده باشین!
یا مشکل دسترسی به سایت acme رو داشتین. دوباره تلاش کنید و لاگ کامل رو بفرستید.
