### ISSUE TITLE
پروکسی تلگرام http 

### ISSUE THREAD

**Issue by MoSi8160** [alireza0/x-ui#1277]
من پروتوکل http و socks رو امتحان کردم برای اینکه بتونم از پروکسی تلگرام استفاده کنم ولی امکان پذیر نیست.

**Comment by apktopsblog** [comment]
اصلا این قسمت تو تنظیمات  telegram bot حذف شده! قبلا ازش استفاده میکردم و لینک پروکسی میزدم کار میکرد الان فیلد SOCKS Proxy اصلا نیست ولی تو پنل ثنایی هست.

**Comment by alireza0** [comment]
این تنظیم از اول در این پنل نبوده. فقط پنل ثنایی چنین امکانی داره.

**Comment by MoSi8160** [comment]
من زیاد اطلاعاتی در مورد پنل ها و نتورک ندارم 
من میخواستم با تلگرام اندروید پراکسی http یا socks استفاده منم. از چی استفاده کنم؟

**Comment by alireza0** [comment]
پراکسی های socks/http از داخل ایران به بیرون فیلتره.

**Comment by MoSi8160** [comment]
آخه کتاب خونه python telegram bot فقط از همین دوتا استفاده میکنن
راهی داره بشه ربات تلگرام روی سرور ایران آورد بالا؟

**Comment by alireza0** [comment]
راهش پین شده توی ایشو ها

**Comment by apktopsblog** [comment]
داشت من خودم استفاده میکردم! تو اپدیت جدید حذف شده
