### ISSUE TITLE
io: read/write on closed pipe

### ISSUE THREAD

**Issue by hossein114** [alireza0/x-ui#128]
سلام و عرض ادب
من طبق دستورات نصب شما پیش رفتم و سرویس  با موفقیت نصب میشه هم با داکر و هم مستقل
کانکشن وی پی ان ایجاد کردم 
تلنت داشتم 
ولی کلاینت ها ارور زیر رو میگرفتن:
io: read/write on closed pipe

**Comment by hossein114** [comment]
نمونه لینک تولید شده:
vless://707f02e7-63d5-4b19-a22f-98181bef88ed@xxxx:443?type=tcp&security=xtls&alpn=&flow=#2ivadwo2

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و گزارشتون.
این مورد در واقع باگ نرم افزار نیست! کد های ارائه شده برای داکر، فقط یک نمونه ساده برای اجرا و تست پنل میتونه باشه.
برای اینکه بتونید راحت روی داکر این مدل رو قابل استفاده کنید، بهتره اطلاعات بیشتری در مورد port-forward و شبکه در داکر کسب کنید.
پیشنهاد من عدم استفاده از مدل `network_mode: host` و مشخص کردن پورت های استفاده شده است. [مثال](https://github.com/alireza0/x-ui/issues/58#issuecomment-1468400665)

**Comment by hossein114** [comment]
خیلی ممنون بابت پاسخگویی
ولی یه نکته رو دقت کنید که من گفتم روی هر دو حالت .. هم با داکر و هم بصورت معمولی این مشکل وجود داشت.
من ابتدا بصورت عادی نصب کردم به این مشکل خوردم و بعدش با داکر هم این مشکل وجود داشت.
حالت هاست هم برای نتورک مود ست نکردیم.
اگر ایشو رو نمی بستید بهتر بود.
ممنون از همکاری شما.

**Comment by alireza0** [comment]
اطلاعاتتون ناقصه و ایشو ربطی به پنل نداره. به همین دلیل بسته شد.
اکر تازه نصب کردید، اصولا نسخه xray-core 1.8.0 نصب میشه. این نسخه دیگه xtls رو ساپورت نمیکنه.
لطفا با نسخه 1.7.5 تست کنید.

**Comment by hossein114** [comment]
من کانفیگ های مختلفی تست کردم .. تنها xtls نبود .
اگر اطلاعات بیشتری نیاز هست بفرمایید که خدمتتون بدم.
من دقیقا طبق روالی که فرمودید پیش رفتم.
روی یه نسخه اوبونتو ۲۲ خام هم نصب کردم.

**Comment by alireza0** [comment]
این خطا خیلی قدیمیه و بیشتر توی گوشی های اندروید قدیمی دیده شده.
جدید رو اطلاعای ندارم.
باید با چند نرم افزار و محیط مختلف تست کنید.
بهتره تنظیمات ساده ای استفاده کنید. مثل vmess ws، یا vless ws.
برای تست tls بهتره از trojan و vless با انتقال tcp یا ws استفاده کنید

**Comment by hossein114** [comment]
بله ممنون از لطف شما.
