### ISSUE TITLE
socks5 for telegram bot

### ISSUE THREAD

**Issue by apktopsblog** [alireza0/x-ui#1282]
سلام لطفا قابلیت پروکسی ساکس 5 رو برای ربات تلگرام مجدد فعال کنید.
این قابلیت تو اپدیت های جدید غیر فعال شده و قبلا بخوبی کار میکرد.

**Comment by alireza0** [comment]
درود بر شما
این قابلیت در این پنل در کل وجود نداشت و با پکیج هایی که استفاده میکنیم این قابلیت وجود نداره

**Comment by alihosseinii67** [comment]
> درود بر شما این قابلیت در این پنل در کل وجود نداشت و با پکیج هایی که استفاده میکنیم این قابلیت وجود نداره

سلام راه حلش چیه منم ریورس زدم رو سرور ایران نمیتونم رباط فعال کنم
