### ISSUE TITLE
ECH Support

### ISSUE THREAD

**Issue by Generator20** [alireza0/x-ui#1283]
درود

آیا امکان استفاده از کتابخانه های غیر رسمی SSL مانند BoringSSL یا  wolfSSL در پانل xui وجود دارد؟
این نگارش های SSL از قابلیت ECH یا Encrypted.Client.Hello پشتیبانی میکنند و کار DPI رو برای تشخیص آدرس مقصد اگر نگیم غیرممکن دستکم دشوار می کنند. ضمنا احتمالا ما رو از Fragment هم بی نیاز خواهند کرد.

**Comment by alireza0** [comment]
درود بر شما
توی هسته هنوز چنین قابلیتی وجود نداره.
هر وقت اضافه بشه، میتونیم به پنل اضافه کنیم
