### ISSUE TITLE
HA

### ISSUE THREAD

**Issue by DocuDevCraft** [alireza0/x-ui#1285]
Is there anyway to HA X-UI to prevent downtime and also have load balancing (on the panel not the ourbounds) on it?

**Comment by DocuDevCraft** [comment]
Can we convert this to a feature request or something?

**Comment by alireza0** [comment]
Proxy servers are not trying to be stable and outages could not be harmful.
At least this panel is not designed for this kind of usages.

For these kind of advanced features, you should create a complex solution using 3rd parties or panel's API.
