### ISSUE TITLE
مشکل اپلود و دانلود عکس و تصویر در واتساپ

### ISSUE THREAD

**Issue by Aryas78** [alireza0/x-ui#1286]
سلام دوست عزیز  
با اینترنت ایرانسل عکس آپلود و دانلود نمیشه از vless  استفاده میکنم راه حلی هست؟

**Comment by MoSi8160** [comment]
من هم همین مشکل داشتم . پروتوکل vmess و trojan جواب داد برام
یک سوالی هم که داشتم چطور میشه برای یک یوزر، چند پروتوکل مختلف ساخت و ارسال کرد؟ 
راه حل ساده میخوام وگرنه دستی داخل inbound اضافه کردن خیلی طول میکشه

**Comment by mrmasiha0** [comment]
بله من هم با ایانسل و  vless  همین مشکل رو داشتم با vmess اوکی میشه. با vless و اینترنت ایرانسل سایت هایی مثل توییتر و فیسبوک هم کار نمی کنند.
برای اینکه یک یوزر بتونه از چند پروتکل استفاده بکنه راهش اینه که در اینباند جدید یک یوزر با هر اسمی بسازین(غیر تکراری باشه یوزر آی دی) ولی باید کدی که برای سابسکریپشن یوزر جدید میذارین رو از همون یوزر در پروتکل قبلی کپی کنید.
