### ISSUE TITLE
سابسکریپشن

### ISSUE THREAD

**Issue by mrmasiha0** [alireza0/x-ui#1288]
سلام و تشکر از زحمات شما

من دو تا دومین دارم یکیش برای پنل و یکی را هم میخواهم برای سابسکریپشن استفاده کنم که در صورت فیلتر شدن دومین پنل و یا سرور آن، دوستان بتونند با آپدیت سابسکریپشن به سرور جدید وصل بشند ولی هر دومینی در قسمت سابسکریپشن ست می کنم همون رو هم به عنوان دومین ساب و هم دومین اتصال در نرم افزارهایی مثل v2rayng نشون میده.نمیدونم کجای کار را اشتباه میرم.ممنون میشم راهنمایی کنید.

**Comment by alireza0** [comment]
درود بر شما
باید توی اینباندهاتون از external proxy استفاده کنید.
