### ISSUE TITLE
افزودن یک کاربر به چند ورودی

### ISSUE THREAD

**Issue by eclipsssss** [alireza0/x-ui#1289]
سلام و درود و تشکر از تمام زحمات شما

من چند inbound با کانفیگ های متفاوت دارم و میخوام به کاربرام از همه این انواع کانفیگ بدم 
اگر ممکنه امکانی قرار بدین تا بجای افزودن کابر به هر inbound به صورت جداگانه 
بشه یکجا کاربر رو به همه inbound ها اضافه کرد 
و اینکه اگر ممکنه ترافیک این کاربر در مجموع inbound ها هم یکجا حساب بشه
در حال حاضر این کانفیگ هارو با سابسکریپشن یکجا به کاربر میدم

میدونم انجام دادنش برا شما زحماتی داره و متشکرم اگر روش فکر کنید

**Comment by wulfric93** [comment]
امکان پذیر نیست به گمانم...

**Comment by alireza0** [comment]
درود بر شما
این ویژگی چندین بار درخواست شده و جواب هم دادیم. لطفا قبل از سوال، جستجو کنید.
این پنل برای این کار طراحی نشده و از پایه امکانپذیر نیست.
هرچند چند بار تلاش کردیم که به نحوی اجرا کنیم، ولی مشکلات زیادی برای پنل ایجاد میکنه.
از طرفی نمیشه به راحتی پایه پنل رو تغییر داد و ترجیح من طراحی پنل جدید به جای این کار بود.
