### ISSUE TITLE
Adding a limit Enabled users to the x-ui panel

### ISSUE THREAD

**Issue by arashammm** [alireza0/x-ui#129]
سلام. لطفا اگر میشه در ورژن های آینده امکان اضافه کردن محدویت تعداد یوزر فعال رو در قسمت بک اند پنل قرار بدید. به این صورت که ادمین پنل  .نتونه بیشتر از تعدادی مشخص یوزر فعال در پنل داشته باشه و  تنها راه افزایش این عدد در بک اند سرور باشه
به این صورت اگر پنل دست شخص واسطه‌ای قرار بگیره مدیریت بر منابع سرور و تعداد یوزر ها قابل پیاده سازی هست.

اگر هم امکان اضافه کردن همچین امکانی رو ندارید لطفا به قسمتی از سورس کد که قابلیت پیاده سازی همچین چیزی رو داره اشاره کنید که خودم تغییرات رو اعمال کنم و در اختیار شما و دیگران بذارم.

**Comment by alireza0** [comment]
درود بر شما
متاسفانه هیچ جای این کدها این بررسی رو نداریم.
به صورت کلی، هرگونه تجاری سازی با اهداف ارائه پنل همسو نیست.
