### ISSUE TITLE
یه پیشنهاد

### ISSUE THREAD

**Issue by MoeinNS** [alireza0/x-ui#1292]
امکان اضافه کردن فرگمنت به قسمت outbound هست ؟!
و کاری که sockopt میکنه چیه دقیقا من نتونستم توضیحی راجب این آپشن پیدا کنم

**Comment by alireza0** [comment]
فرگمنت خیلی قبل از سابسکریپکش به خروجی اضافه شده بود.
بخشی که اشاره کردین شامل چندین تنظیمه که هر کدوم کار متفاوتی انجام میدن. اگر پیش زمینه ندارید بهتره تغییرش ندین.
