### ISSUE TITLE
Customized blackhole http response page

### ISSUE THREAD

**Issue by theahz** [alireza0/x-ui#1296]
I was wondering, is it possible to customize or redirect a user to a webpage by using blackhole outbound? Right now, blackhole outbound can only return an empty http page (or none), which could to lead to confusions since user may face similar response if the target web server is down or misconfigured or other issues such as misfunctioning DNS server. I do think a customized webpage that informs users about the fact that this address is blocked by admin would come handy. Should this be done on panel side or core side, or both?

**Comment by alireza0** [comment]
It should be done in xray-core.
