### ISSUE TITLE
Executing Outbounds in the Core | اجرای خروجی ها در هسته

### ISSUE THREAD

**Issue by ahmadipiralvan** [alireza0/x-ui#1298]
علیرضا @alireza0 عزیز؛

سلام

امیدوارم اوقات خوشی داشته باشی.

یادمه ماه ها یا سال های گذشته
مشکلی در Inbound های پنل وجود داشت.

این بود که با هر بار تغییر،
هسته xray ری استارت، و باعث reconnecting تمام اتصالات می‌شد.

به نظر میرسه الان بیش از هر چیز،
به این نیاز داشته باشیم که Outbound ها هم،
به سایدبار کناری منتقل بشه،
و داخل خود هسته اجرا بشه،
که هر بار نیاز به Save و Restart پنل برای اعمال و اجرای تغییرات جدید نباشه.

هم یک بروزرسانی و ارتقای مهم به حساب میاد.
و هم بهینه سازی مهمی صورت میگیره.

البته میدونم که این مورد به هسته xray برمیگرده،
اما اگه بشه پیاده اش کرد خیلی کمک بزرگی می کنه.

در آخر ممنونم از همه زحماتت

**Comment by alireza0** [comment]
درود بر شما
بله این مورد از قدیم پشتیبانی میشده و در نسخه های جدید هسته، بخش قوانین هم پشتیبانی میشه.
ولی نکته اصلی اینه که این پنل خیلی قدیمیه و تنظیمات خروجی فقط توی template ها ذخیره میشه. پس به راحتی قابل ردگیری نیست.
در ضمن تغییرات در خروجی و قوانین به ندرت انجام میشه و به همین دلیل بخش جدایی براش در نظر گرفته نشده.
