### ISSUE TITLE
Download traffic not being monitored

### ISSUE THREAD

**Issue by Nipoto** [alireza0/x-ui#13]
hi
Download traffic not being monitored

**Comment by alireza0** [comment]
Hi,
You are right!
Updating `gorm` package causes some issues related to unsupported methods like `db.Update(...).Update(...)` theme.
I am updating all these usages in the methods listed below:
- InboundService.AddTraffic
- InboundService.AddClientTraffic
- InboundService.ResetClientTraffic
- UserService.UpdateUser

It will fix ResetClientTraffic and monitoring traffic as well.

Thank you for your report and appologize for mistake

**Comment by alireza0** [comment]
Version 0.2.4 is now rebuilt. Closing this issue...

**Comment by shahrooz1349** [comment]
Dear developer, thank you for your efforts This is the best version of xui 🙏🌹
