### ISSUE TITLE
oneclick renewal 

### ISSUE THREAD

**Issue by Vahidno13** [alireza0/x-ui#130]
سلام و خسته نباشید

اولا تشکر بابت تمام زحماتتون

یه درخواست داشتم اگه امکانش هست این قابلیت به دکمه ریست ترافیک برای یوزر رو اضافه کنید که با زدن همین دکمه تاریخ مصرف یوزر هم ۳۰ روز تمدید بشه یعنی از لحظه زدن دکمه تاریخ هم به مدت ۳۰ روز از همون لحظه شروع بشه.

اگه امکان پذیر باشه خیلی ممنون میشم.

با تشکر مجدد

**Comment by alireza0** [comment]
درود بر شما
سپاس ازهمراهی و پیشنهادتون
این درخواست خیلی شخصی میشه و نمیشه حالت عمومی پیدا کنه.
شما میتونید به راحتی از طریق ویرایش کاربراین کار رو انجام بدید.
