### ISSUE TITLE
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: lookup region.freemyip.com: no such host]

### ISSUE THREAD

**Issue by XKMEXX** [alireza0/x-ui#1300]
Please help me figure out this error
This problem only occurs on [nekoray](https://github.com/MatsuriDayo/nekoray/releases) 
There is no such thing on [v2rayN](https://github.com/2dust/v2rayN/releases/tag/6.45)

**Comment by alireza0** [comment]
It is not related to this panel.
Please ask in nekoray repository

**Comment by XKMEXX** [comment]
Actually, it is relevant, since neko and v2rey just serve to connect, so there is no need to close the issue so abruptly
