### ISSUE TITLE
مشاهده ورژن پنل نصب شده

### ISSUE THREAD

**Issue by alihosseinii67** [alireza0/x-ui#1301]
سلام من خیلی وقت پیش پنل علیرضا رو نصب کردم الان رو سرور جدید نصب کردم اخرین نسخه نصب شد میخوام بفهمم رو سرور ورژن اون پنل چنده چجوریه و میخوام رو سرور جدید همون وؤژن قدیمی نصب بشه

**Comment by alireza0** [comment]
درود بر شما
نسخه پنل توس صفحه اصلی پنل نمایش داده میشه

**Comment by alihosseinii67** [comment]
ممنون
