### ISSUE TITLE
دو کاربره کردن کلاینت

### ISSUE THREAD

**Issue by mrafieefard** [alireza0/x-ui#1302]
یادمه قبلا میشد تغریف کرد که چند کاربره باشه کانفیگ گزینش عوض شده یا من دارم اشتباه میکنم

**Comment by alireza0** [comment]
این رپوزیتوری هیچوقت چنین ویژگی نداشته.
احتمالا از [3x-ui](https://github.com/MHSanaei/3x-ui) استفاده میکنین.
