### ISSUE TITLE
 Wrong reporting of IN/OUT server traffic data in the panel (OVERVIEW page) (گزارش ترافیک دو برابر!)

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [alireza0/x-ui#1303]
سلام و با تشکر از زحمات تون.

شبهه ای برام پیش اومده که آیا اطلاعات ترافیک ورودی و خروجی سرور که در صفحه OVERVIEW پنل گزارش میشه نادرست باشه؟! احتمال میدم که به غیر از اینترفیس اصلی سیستم که مثلا eth0 یا ens5 هست، ورودی و خروجی روی اینترفیس loopback هم داره به این اعداد اضافه میشه و باعث میشه که ترافیک ورودی و خروجی واقعی سیستم، گاها (و نه همیشه) بیشتر و حتی دو برابر، گزارش بشه!

این اتفاق مخصوصا وقتی که به خاطر روتینگ xray اطلاعات بین اینباوندها و اوتباوندهای داخلی یک سرور سیستم تبادل میشه (مثلا در سناریوی ریورس پراکسی) ممکنه بسیار چشمگیر بشه.
من اخیرا به علت اینکه در حال توسعه اسکریپتی شخصی بودم و اطلاعات ترافیکی رو استخراج میکردم با این موضوع مواجه شدم.
راه حل تقریبا درست و آسونتر اینه که مجموع ترافیک خروجی و ورودی رو همه اینترفیس ها تجمیع بشه و سپس ترافیک loopback یا lo ازش کم بشه تا ترافیک خروجی/ورودی واقعی سرور (که دیتاسنتر هم همون رو گزارش میکنه) بدست بیاد.

پ.ن.: لازم به توضیح هست که من این باگ رو اولین بار در صفحه پنل جناب ثنایی گزارش کرده بودم (چون فعلا از اون استفاده میکنم و در همون پنل هم این رو باگ مشاهده کردم). اما چون هم شما بطور منظم  به issue ها رسیدگی میکنید و هم احتمال دادم که این پنل هم دچار همون مشکل باشه اینجا هم گزارش کردم.

با تشکر.

**Comment by alireza0** [comment]
درود بر شما
نمیدونم به چه دلیل برچسب باگ رو انتخاب کردین. ولی چیزی که شما مطرح میکنید باگ نیست.
اول اینکه ترافیک معکوس توی loopback نمیره، مگر اینکه خودتون تنظیم خاصی انجام داده باشید.
نکته بعدی اینه که اینترفیس های loopback به راحتی توی همه سیستم ها قابل شناسایی نیستن که بشه حذفشون کرد.
برای سیستم شما شاید از اسمش مشخص باشه، ولی هر سیستم عامل و تنظیمات شخصی، این اسم متفاوته.
متدی که استفاده میشه معادل دستور netstat -ibdnW توی سیستم عامل هست و توی کد ها ترافیک مجموع رو ازش میگیریم.

قبلا پیشنهاد شده بود که به تفکیک اینترفیس ها ارائه بشه. اینجوری از نظر کد خیلی هم پیچیده نمیشه.
دلیل رد شدنش هم اینه که نمیخواستیم سادگی رو فدای یه ویژگی بکنیم که شاید برای درصد کمی از افراد قابل استفاده باشه و بقیه سردرگم بشن.

دیتاسنترها از خود ماشین این اطلاعات رو نمیگیرن و از Hypervisor میگیرن.
اگر شما راه حلی دارید میتونید برای کدهاتون رو پیشنهاد بدین.
سپاسگزارم
