### ISSUE TITLE
WireGuard kernel mode error

### ISSUE THREAD

**Issue by theahz** [alireza0/x-ui#1304]
When I enabled kernel mode for my WireGuard configuration and then tried to restart the xray service, I faced an error which is as follows:
![Screenshot from 2024-06-09 13-43-34](https://github.com/alireza0/x-ui/assets/68293923/d03bff5e-f077-4b83-a3b8-4e2d78090a3b)
I'm using the lastest version of XUI and Xray core, however this error persist in previous versions as well. I tried to do the same thing on a few other servers and got the same results. If there is a certain condition or configuration to use this feature, I would like to know.

**Comment by theahz** [comment]
> I'm sorry, I meant kernel mode on wireguard **outbound**.
> Are you using it on **Inbound**? It seems that inbound doesn't support kernel mode. https://github.com/XTLS/Xray-core/issues/2849#issuecomment-1896162733

Yes, I was trying to set up kernel mode for inbound since using kernel mode leads to better performance and latency. But if the option isn't supported wouldn't be better to remove this option from outbound configuration?

**Comment by alireza0** [comment]
It in not related to the panel. Please ask upstream provider.
