### ISSUE TITLE
امکان Disable شدن کانفیگ ها همزمان با Expire شدن

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1305]
عرض سلام و خسته نباشید

مشکل:
یه مشکلی که الان پنل داره اینه که وقتی یه کانفیگ منقضی میشه ( حجم یا زمان ) وضعیتش به Ended تغییر میکنه و با اینکه Xray و یا کلا سرور Restart میشه اما همچنان کاربران با کانفیگ های منقضی شده میتونن متصل بشن ( چون وضعیت کلیشون همچنان فعاله ) ، حتی پنل نشون میده که آنلاین هستن!

راه حل:
با توجه به تست هایی که کردم ، وقتی وضعیت کانفیگ از حالت فعال به غیرفعال تغییر میکنه ( به صورت دستی ) دیگه کانفیگ متصل نمیشه.
من issue قبلی رو خوندم و تا جایی که میدونم این مورد بررسی نشده بود.
بنابراین اگر همزمان با تغییر وضعیت کانفیگ بعد از منقضی شدن به Ended ، پنل کانفیگ رو Disable هم کنه این مشکل به طور کامل برای همه حل میشه.

با تشکر از شما.

**Comment by alireza0** [comment]
درود بر شما
این مشکل رو خیلی زیاد بررسی کردیم و اینکه کجا به مشکل میخوره دقیق مشخص نیست.
البته این مورد هیچ ربطی به پنل نداره و هسته نمیتونه درست عمل کنه.

اینکه کاربر منقضی، غیر فعال هم بشه با کاربرانی که ریست اتوماتیک دارن تداخل داره.
این کاربرها اگر غیرفعال بشن، روال ریست اتوماتیک براشون فعال نمیشه.

در ضمن روال حذف کاربر در زمان منقضی شدن و غیرفعال شدن یکسانه.
هردو از یک متد تعریف شده در xray-api استفاده میکنن و اگر خطا بگیرن، هسته اتوماتیک ریستارت میشه.
اینکه خطایی نداشته باشیم یعنی دستور رو هسته گرفته و اعمال کرده. و اگر کاربر قطع نمیشه باگ هسته است.

در ضمن، آنلاین بودن کاربر فقط بر اساس داشتن ترافیک از سمت هسته است و این بررسی هر ده ثانیه یکبار انجام میشه.
در زمان قطع کردن حداکثر ۱۹ ثانیه طول میکشه که کاربر آفلاین نمایش داده بشه.
اگر این کاربر بعد از این مدت هنوز آنلاین نشون داده میشه، پس هنوز توی هسته ترافیک داره.

پ.ن: نمایش آنلاین همیشه نشونه وصل بودن کاربر نیست.

**Comment by alireza0** [comment]
#771

**Comment by Alireza78na** [comment]
ممنون از توضیحاتتون
این مورد رو به Xray Core هم گزارش میکنم حتما.
این توضیحم اضافه کنم که سرور و Xray از طریق Cronjob روزانه حداقل 1 بار ری استارت میشن، اما کاربرانی که مثلا بیش از 10 روزه منقضی شدن ( گاها ) هنوز به حجم ترافیک مصرفیشون اضافه میشه ینی اتصالشون برقراره و درحد ارسال درخواست به سرور نیست.
حتی چند مورد رو من خودم تست کردم و متصل شدم و با اینکه کانفیگ منقضی بود اما به خوبی کار میکرد !

فقط چندتا پیشنهاد دارم ، امیدوارم قابلیت اجرا کردن داشته باش:
1. درمورد غیرفعال کردن ، اگه بشه یه استثنا قرار بدید که مثلا درصورتی که Auto Renew فعال بود ، کانفیگ غیرفعال نشه و اگر نه ، غیرفعالش کنه.

2. یک آپشن مشابه Auto Renew اضافه بشه ، به این صورت که اگه کانفیگ بیش از یک تایم قابل تنظیم ( مثلا 10 روز ) منقضی موند ، اون کانفیگ حذف بشه  اینجوری سرور هم خلوت تر میشه.
این گزینه رو میشه به بخش ساخت اینباند اضافه کرده که با تنظیمش به صورت پیش فرض برای تمام کاربران اون اینباند اعمال بشه یا اینکه مثل Auto Renew برای هرکاربر جداگانه باشه که اینجوری بهترم هست.


تشکر از توجه و زحماتتون.

**Comment by alireza0** [comment]
هروقت شما هسته و یا کلا پنل رو ریستارت میکنید، تنظیمات ازنو نوشته میشه و امکان اتصال کاربر نیست.
نشتی شما احتمالا از تنظیماتتونه. مثلا اگر uuid تکراری داشته باشید و یا ایمیل تکراری ساخته شده با api.
دو مورد پیشنهادی شما عملیات پیچیده تری داره و امکان باگ خوردن رو بیشتر میکنه

**Comment by zifulx** [comment]
سلام علیرضا جان امیدوارم که حالت خوب باشه،ممنون از وقتی ک میزاری و سعی میکنی به همه راهنمایی کنی.
من داشتم میخوندم پیامای بالارو و  برام سوال شد:
اینکه ما توی دوتا اینباند مختلف یک uid داشته باشیم مشکل ایجاد میکنه؟
