### ISSUE TITLE
اضافه شدن اتوماتیک اینباند به Revers Tunnle

### ISSUE THREAD

**Issue by rbsdotnet** [alireza0/x-ui#1306]
درود به علیرضا جان عزیز
یه سوال داشتم در مورد ریروس تانل:
آیا امکانش هست زمانی که اینباندی اضافه میشه به صورت اتوماتیک در صورت داشتن ریروس تانل به این بخش اضافه بشه؟
وقتی از ریات استفاده میشه الان باید به صورت دستی بریم و اینباند رو به ریورس اضافه کرد
اگر بشه در پنل در قسمت اینباند گزینه افزودن به ریورس اضافه بشه خیلی عالی میشه
یعنی با این کار این بخش به صورت اتوماتیک اتفاق می افته
یا در api بخشی باشه بشه تنظیمات revers رو مدریت کرد

چه جوری میشه این پروژه رو دیباگ کرد؟ با VS Code میشه؟ و پیش نیازهاش چی هست

**Comment by alireza0** [comment]
درود بر شما

این درخواست شماست و ممکنه هرکسی این نیاز رو نداشته باشه. ( البته منطقیه )
بخش های ورودی‌ها و تنظیمات هسته کاملا جدا هستند و تغییراتشون به راحتی نمیشه با هم انجام بشه.

**Comment by rbsdotnet** [comment]
امکانش هست در مورد نحوه دیباگ و اجرای پروژه توی ویندوز کمک کنید؟

**Comment by alireza0** [comment]
این پروژه با golang نوشته شده و میتونید نحوه های اجرا و دیباگ رو جستجو کنید.
برای این کار اینجا نمیشه راهنمای کامل نوشت
