### ISSUE TITLE
Json config does not work with Streisand

### ISSUE THREAD

**Issue by waxilu** [alireza0/x-ui#1309]
Why json configs that made by Xui panel does not work in Streisand for iPhone,
Streisand already work with Json and Fragment, it works easy with another Json links but not work with Xui Json configs,

**Comment by alireza0** [comment]
It is not true.
Streisand developers were so kind to accept our changes and needs.
One of my important tests is always using this app.
Please provide me more information about configuration which you use.
Also test it with other types of configuration to find out what is the exact problem.

**Comment by waxilu** [comment]
yes, problem is not from Streisand,

I check output of Json and found a problem

In XUI panel, when add host and path in specific place something happens like this:

```
        "wsSettings": {
          "headers": {
          },
          "host": "my.domain.com",
          "path": "/"
        }
```

but when add host and path in header part its ok and work and json output is like this:

```
        "wsSettings": {
          "headers": {
            "host": "my.domain.com",
            "path": "/"
          }
        }
```


Streisand ignored host value outside of headers and make problem and I thought problem is Streisand

**Comment by alireza0** [comment]
1st: Path could not be a header value.
2nd: They should update the app according to xray core specification.
3rd: you can use host header instead.

**Comment by waxilu** [comment]
Thanks for response, I use host in two places for sure and it work in two apps.

**Comment by waxilu** [comment]
Thanks for response, I use host in two places for sure and it work in two apps.
