### ISSUE TITLE
Add Reality inbound

### ISSUE THREAD

**Issue by DarkZo0m** [alireza0/x-ui#131]
https://github.com/qist/xray-ui

In Panel Az Panelaye Dige Fork Gerefte Va Reality Ro Ezafe Karde Khastam Bebinm Age Beshe Ke Be Panel Ezafe Konid 🙏

**Comment by DarkZo0m** [comment]
https://gitlab.com/Misaka-blog/x-ui-msk

**Comment by ircfspace** [comment]
پنل کافکا هم Reality رو اضافه کرده

**Comment by alireza0** [comment]
این قابلیت روش کار شده، ولی از اونجایی که هنوز خیلی ساپورت نمیشه، کار روی مشکلات دیگه رو توی اولویت گذاشتم.
به زودی نسخه جدید با قابلیت tls  و Reality اضافه میشه.

**Comment by m0000hamad** [comment]
اموزش استفاده از ریلیتی رو لطف میکنید
من فقط روشن میکنم از اینباند ولی اکانتش وصل نمیشه توی گوشی

**Comment by dev-ir** [comment]
میشه گفت اکثر پنل ها این اضافه کردن ، مثل کافکا و سنایی و... ولی مشکلات زیادی داره 
اما این مورد توی کلاینت ها هم اپدیت هاشون اومده و فیچر که باید در نظر گرفت اضافه کرد

**Comment by alireza0** [comment]
اضافه شد
