### ISSUE TITLE
پینگ 

### ISSUE THREAD

**Issue by ali90500** [alireza0/x-ui#1310]
سلام
من ریورس پنل به پنل زدم
بعد یه مدت که میشه کانفیگ پینگ نمیده و ارور tls میده
ولی ارتباط دو سرور برقراره، و این موقع کانفیگ مستقیم از روی سرور خارج هم وصل نمیشه و یک بار که ری استارت ایکس ری روی سرور خارج میزنم درست میشه!

**Comment by alireza0** [comment]
درود بر شما
این مشکل فیلترینگه و ربطی به پنل نداره.
باید بررسی کنید که توی چه حالتی میتونه پایدار بمونه.
