### ISSUE TITLE
ربات تلگرام 

### ISSUE THREAD

**Issue by Mahan0101** [alireza0/x-ui#1311]
سلام علیرضا جان
خسته نباشی خدا قوت
داخل پنل یه تنظیمی هست برای حداقل حجم و روز برای اطلاع به یوزر ها، اون بخش ها کار نمیکنن من حجم و روز رو روی 1 گذاشتم.
من باید تنظیماتی رو ست کنم یا این مشکل وجود داره؟

**Comment by alireza0** [comment]
درود بر شما
این بخش هایی که میفرمایید برای اطلاع به کاربر نیست.
هیچ روالی برای اطلاع رسانی به کاربر به صورت اتوماتیک نداریم.
کاربر باید هربار درخواست بده تا اطلاعاتش رو بگیره
