### ISSUE TITLE
مشکل سابسکریپشن در اندروید 

### ISSUE THREAD

**Issue by mreza0007** [alireza0/x-ui#1312]
سلام مخلصم 
من سابسکریپشن که در گوشی های اندروید ایمپورت میکنم ارور میده و نمیخونه، رو برنامه های مختلف هم تست کردم ولی برای آیفون مشکلی وجود نداره !!!
مسیر کلید هم همون اصلی پنل رو گذاشتم 
به نظر شما مشکل از کجاست ؟

**Comment by alireza0** [comment]
درود بر شما
اینکه چه مدل تنظیمی شما دارید و چه نسخه ای استفاده میکنید ارتباط مستقیم داره با عملکرد اون.
بدون ارائه این اطلاعات هیچکس نمیتونه به شما کمکی بکنه.
