### ISSUE TITLE
امکان انتخاب و اعمال تغییرات گروهی

### ISSUE THREAD

**Issue by Alireza78na** [alireza0/x-ui#1313]
عرض سلام و خسته نباشید.

امکانش هست این آپشن اضافه بشه که بتونیم یوزر ها رو ( که در یک اینباند هستن ) انتخاب کنیم و موارد انتخاب شده رو به صورت گروهی تغییر بدیم؟
مثلا 20 تا کانفیگ رو انتخاب کنیم و حذفشون کنیم.
یا اینکه مثلا ترافیک این 20 مورد رو ریست کنیم
یا کلا تغییراتی مثل تمدید ، فعال و غیرفعال کردن و ....

البته الان بعضی امکانات مثل حذف همه ی  کانفیگ های منقضی شده و ... وجود داره اما این امکان وجود نداره که فقط برای یه سری کانفیگ و یوزر خاص این اتفاق بیوفته.

**Comment by alireza0** [comment]
درود بر شما
این امکان در زمان تغییر قالب پنل کاملا تست شد ولی به دلیل عدم هماهنگی با ساختار پنل، قابل اضافه کردن نبود.
در حال حاضر فقط امکان ایجاد گروهی وجود داره که مشکلی با ساختار نداره.
