### ISSUE TITLE
اضافه کردن نصب وردپرس

### ISSUE THREAD

**Issue by alipour66m** [alireza0/x-ui#1314]
با سلام و احترام
در حال حاضر ما برای نصب وردپرس برای مخفی سازی از xpanel استفاده میکنیم
لطفا مانند xpanel این امکان را اضافه کنید.
و روش های مخفی سازی دیگری که خودتان بیشتر اطلاع دارید هم اضافه کنید.

**Comment by alireza0** [comment]
درود بر شما
این کار خیلی عمومی نیست و هرکسی راه حل خودش رو داره
