### ISSUE TITLE
1.8.4 Can't access panel if setupped Listen URL parametr

### ISSUE THREAD

**Issue by UdoChudo** [alireza0/x-ui#1329]
**Describe the bug**
After upgrading x-ui image from 1.8.3 to 1.8.4 i can't access to my panel 

My setup:
INTERNET -> NGINX with https://example.com/x-ui/ > http://ip:port/x-ui/

**To Reproduce**
1. Setup x-ui to listen Domain (example.com)
![image](https://github.com/alireza0/x-ui/assets/4757891/e6152083-37a6-4f6f-a052-fd64847124b5)

3. Setup x-ui URI path 
![image](https://github.com/alireza0/x-ui/assets/4757891/ab0e4958-6fef-4e61-9168-4d129298a5af)

5. Setup nginx with example.com/x-ui/ location
Nginx Config 
```        
location /x-ui/ {
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 52w;
        proxy_pass http://ip:port/x-ui/;
        }
```
6. Get access error
![image](https://github.com/alireza0/x-ui/assets/4757891/d4c625c4-f27c-4909-aa09-2eef05db8108)

**Comment by alireza0** [comment]
Using `Listen Domian` is to limit access to the panel only by this domain.

If you have problem, you should debug the proxy and receved requests.
You can test it simply by a curl command:

```bash
curl -H "Host: example.com" http://ip:port/x-ui
```

**Comment by alireza0** [comment]
OK! I have found it.
It happened after this change: https://github.com/alireza0/x-ui/pull/1252/commits/6c36c19af60d825c64341965dfd055fa8015752b

It seems gin package has an issue with this from long time ago.
I will role it back.

**Comment by alireza0** [comment]
This problem is now solved and will be available in next release
