### ISSUE TITLE
بلاک سایت های ایرانی با یک کلیک

### ISSUE THREAD

**Issue by Morghak963** [alireza0/x-ui#133]
سلام مهندس
یک پیشنهاد داشتم ،همینطور که در قسمت تنظیمات با یک کلیک می‌توان bittorrent را غیر فعال نمود،لطفا گزینه ای اضافه شود که بدون تغییر دستی در قسمت xray configuration با فعال کردن آن سایت های ایرانی بسته گردد. برای مثال گزینه ای تحت عنوان:

Block iranian domain and site and messenger 

برای این مسئله هم پیشنهادم ترکیب پروژه hope خصوصا گام پنجم آن با کدهای پنل هست ، چرا که در گام پنجم از دومنبع جداگانه سایت ها و دامین های ایرانی گرفته می شود و این منابع بصورت فعال و هفتگی در حال آپدیت هستند (با مطالعه مستندات میتونید آپدیت هارو ببینید) و تقریبا هیچ سایت و نرم افزاری نیست که زیر دست ادمین پنل در بره 

https://github.com/iranxray/hope/blob/main/routing.md

درمرحله بعد می‌توان در همان قسمت حتی یک text box نیز باز کرد که ادمین پنل سایت هایی که می‌خواهد جدای از این پروزه بن شود تایپ کند و با زدن تیکی جداگانه آن ها نیز بن گردد

مشتکرم

**Comment by ImanIranNejad** [comment]
اره این قابلیت باشه خیلی عالی میشه
