### ISSUE TITLE
باز نشدن پنل

### ISSUE THREAD

**Issue by persiannova** [alireza0/x-ui#1332]
من پنل رو تازه نصب کردم . راحت نصب شد و فعال نشونش میده اما آی پی رو که میزنم و پورت  صفحه پنل بالا نمیاد اصلا. فیروال رو هم خاموش کردم تاثیری نداشت.

**Comment by misagh72** [comment]
پنل path داره از توی سرور پیداش کن

**Comment by persiannova** [comment]
> پنل path داره از توی سرور پیداش کن
اون رو هم زدم . جالب اینجاست که پنل Alireza هم بالا نمیاد رو این سرور ولی هیدیفای بالا میاد. با فیلترشکن هم بالا نمیاد. یه چیز عجیب دیگه اینکه بدون فیلترشکن ssl میزنم بهش ولی بدون فیلترشکن پینگ نداره.

**Comment by misagh72** [comment]
> > پنل path داره از توی سرور پیداش کن
> > اون رو هم زدم . جالب اینجاست که پنل Alireza هم بالا نمیاد رو این سرور ولی هیدیفای بالا میاد. با فیلترشکن هم بالا نمیاد. یه چیز عجیب دیگه اینکه بدون فیلترشکن ssl میزنم بهش ولی بدون فیلترشکن پینگ نداره.

پس اپی سرور فیلتر

**Comment by persiannova** [comment]
> > > پنل path داره از توی سرور پیداش کن
> > > اون رو هم زدم . جالب اینجاست که پنل Alireza هم بالا نمیاد رو این سرور ولی هیدیفای بالا میاد. با فیلترشکن هم بالا نمیاد. یه چیز عجیب دیگه اینکه بدون فیلترشکن ssl میزنم بهش ولی بدون فیلترشکن پینگ نداره.
> 
> پس اپی سرور فیلتر

فیلتر نیست. به هیچ کشوری پینگ نمیده. فیلتر هم باشه باید با فیلترشکن بیاد بالا ولی نمیاد
