### ISSUE TITLE
BurstObservatory and Observatory subjectSelectors are filled wrong

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#1333]
**Describe the bug**
When I add a balancer with `leastLoad` or `leastPing` strategy, x-ui automatically creates related `BurstObservatory` or `Observatory` objects.
But the `subjectSelector` part is filled with `balancerTags` instead of outbounds.

**To Reproduce**
1. Create a `test` balancer with either leastLoad or leastPing strategy and add some outbounds to them.
2. Check created BurstObservatory/Observatory. subjectSelector is `test` instead of the list of outbounds
3. Test the balancer created in previous steps. All the traffic goes to the first default outbound (direct).

**Expected behavior**
subjectSelector should be the list of outbounds specified in "selector" part of the balancer.

**Additional context**
tested on x-ui version 1.8.4

This is the balancer created by x-ui:
```
    "balancers": [
      {
        "tag": "test",
        "selector": [
          "proxy-fl",
          "proxy-us"
        ],
        "strategy": {
          "type": "leastLoad"
        }
      }
    ]
```
and this is the burstObservatory created by x-ui:
Here subjectSelector should be `"proxy-fl","proxy-us"`
```
"burstObservatory": {
    "subjectSelector": [
      "test"
    ],
    "pingConfig": {
      "destination": "http://www.google.com/gen_204",
      "interval": "30m",
      "connectivity": "http://connectivitycheck.platform.hicloud.com/generate_204",
      "timeout": "10s",
      "sampling": 2
    }
  }
```
**Screenshots**

![image](https://github.com/alireza0/x-ui/assets/5326305/2ca8522d-3207-4f54-9ad9-3b27824bab11)

**Comment by alireza0** [comment]
Thank you for your report.
I expect everyone who needs that could change the selector as they want.
For instance, if you have two or more loadbalancer, then it is somehow complex to add an unique list of outbounds.
I will try to do it automatic and will keep this issue open till proper time.

**Comment by alireza0** [comment]
Solution is already applied to other objects.
It could find all related balancers and creates unique list of outbounds

**Comment by alireza0** [comment]
It is now fixed and you can use it from next version.
