### ISSUE TITLE
v1.8.4 domain name is removed from the title of panel's web page

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#1335]
Updated from v1.8.3 to v1.8.4
Panel web page now doesn't display domain name in the title.
For example in v1.8.3 the title was `domain.name-Overview`,
but now in v1.8.4 the title is `-Overview`

The problem is that if we open multiple panels on a browser, It's not easy to distinguish them by the title.

**Comment by alireza0** [comment]
There is no change in page title.
Please hard refresh your browser after each upgrade
