### ISSUE TITLE
Serious BUG

### ISSUE THREAD

**Issue by admin8800** [alireza0/x-ui#1338]
### After multiple tests, it was found that the randomly generated Short ID in the reality protocol may have defects, causing xray to fail to start.

![image](https://github.com/alireza0/x-ui/assets/153331261/5792af81-a442-4aa2-9404-13b4b9dea442)

**Comment by alireza0** [comment]
It is correct and expected behavior. Based on documentation, shortID could be zero length string. It could not make any issue.
If there is, then report xray-core

**Comment by alireza0** [comment]
If it does not accept, it should fail immediately. It seems it is a bug in XTLS
![image](https://github.com/alireza0/x-ui/assets/12573084/75fb33c2-b71f-415a-839a-5a72e6607194)

**Comment by alireza0** [comment]
@pulsarice Thank you for your accurate debug. I am going to fix it ASAP.

**Comment by alireza0** [comment]
By [this committed change](https://github.com/alireza0/x-ui/commit/3e5660e1afce5c88d35836d7299e094a51eb0bd2), we will have always zero length string first and 23 other strings with up to 16 characters length.
You can find the fix in next release
