### ISSUE TITLE
قابلیت fake tls

### ISSUE THREAD

**Issue by aboozar1368** [alireza0/x-ui#1339]
سلام وقتتون بخیر 
زمانی که ما یه کانفیگ روی CDN مثل Gcore میسازیم فقط داخل نرم افزار V2rayn می تونیم Tls رو فعال کنیم آیا این قابلیت میشه به x-ui اضافه بشه که از داخل پنل اینکارو انجام داد؟

**Comment by aboozar1368** [comment]
در واقع منظورم اینه بدون SSL گرفتن اینکارو کرد چون مثلا من خود Gcore میذارم به عنوان SNI

**Comment by alireza0** [comment]
درود بر شما
میشه با تنظیم External Proxy و انتخاب Force TLS این کار رو انجام داد.
ولی در حال حاضر تغییر SNI رو پشتیبانی نمیکنه.
