### ISSUE TITLE
duplicate UUID

### ISSUE THREAD

**Issue by straymail** [alireza0/x-ui#1344]
سلام مهندس
وقت بخیر و خسته نباشید

بخاطر استفاده از API و حذف یا تغییر لوکیشن یک کلاینت از یک پنل و برگشتن دوباره کلاینت به پنل فعلی یا ثبت چند باره یک کانفیگ توسط کاربر، بعضی وقت ها UUID تکراری داخل اینباند بوجود میاد. به اینصورت که مثلا 2 یا چند UUID یکسان هست و باعث کرش کردن پنل، و اختلالاتی میشه.
در نسخه های قبلی که UUID روبروی هر کلاینت نوشته شده بود، میشد تکراری هارو یافت و حذف کرد.( سطر UUID )
الان که UUID از این قسمت حذف شده نمیشه فهمید کدوم کلاینت ها UUID تکراری دارند.

لطفا برای این مشکل ایجاد UUID تکراری، راه حلی مثل:

- خودکار سازی حذف تکراری ها و باقیماندن فقط یکی از آنها
- یا گزارش تکراری ها توسط پنل
- یا اینکه برگشتن دوباره سطر UUID داخل اینباند رو در آپدیت بعدی قرار بدید

سپاس

**Comment by alireza0** [comment]
درود بر شما
ادمین باید مراقب استفاده تکراری از uuid باشه.
اگر از api  استفاده میکنید، نویسنده api باید مراقب باشه و هربار یک داده متمایز استفاده کنه.
