### ISSUE TITLE
How to change the ID of inbounds

### ISSUE THREAD

**Issue by AquaSimulacra** [alireza0/x-ui#1346]
![image](https://github.com/alireza0/x-ui/assets/98635189/3a0c9055-23ec-4e49-9911-db08becf45d7)

**Comment by alireza0** [comment]
Install sqlite3 in your server and run these commands after replacing `<old_id>` as old id and `<new_id>` for new ID:
```bash
X=<old_id> && Y=<new_id> && sqlite3 /etc/x-ui/x-ui.db "UPDATE inbounds SET `id`=$Y WHERE `id`=$X; UPDATE client_traffics SET `inbound_id`=$Y WHERE `inbound_id`=$X"
```
