### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by AndreyRz** [alireza0/x-ui#1348]
Suddenly, problems with the vpn started today with vless+realty protocol, such errors appeared in the logs every time you tried to connect:

> Jul 05 16:54:38 **** x-ui[509]: 2024/07/05 16:54:38 http: TLS handshake error from ***.***.***.***:57163: remote error: tls: unknown certificate

> Jul 05 16:54:38 **** x-ui[509]: 2024/07/05 16:54:38 http: TLS handshake error from ***.***.***.***:57159: remote error: tls: unknown certificate

Personal data is hidden behind ***, I use x-ui 1.8.2 on debian 11 on 5.10.162-1, latest version of nekoray on windows and necobox 1.3.1 from android. Here is my config file
[config.json](https://github.com/user-attachments/files/16113749/config.json)

I can ping my server and all used ports accessible from my pc, I try to rerole keys, change port, change xray version, restart xray and all server.

**Comment by AndreyRz** [comment]
Upd, the problem was due to problems with accessibility to the site that is listed as sni. But the error still appears in the logs, who can tell you what it is related to?

**Comment by alireza0** [comment]
It is about someone tryed to access your panel without SNI. If you are using cloudflare it is a common message comming from a lot of services which tryes to scan your service.
If not, it is a simple scanner.
