### ISSUE TITLE
ip limit bug

### ISSUE THREAD

**Issue by amirzare021** [alireza0/x-ui#1350]
با سلام و خسته نباشید خدمت جناب علیرضا

اقا یه باگی داخل ای پی لیمیت هست اونم اینه که وقتی تعداد کاربرای متصل به سرویس بیشتر از 5 نفر باشن نمیتونه جلوی اتصالشون رو بگیره و بن کنه

زیر این تعداد رو مشکلی نداره و بن میکنه ولی بالای این تعداد راحت وصل میشن بدون حتی یک بار بن شدن یک کاربر
مهمم نیست تعداد ای پی لیمیت رو چندوارد کنید

**Comment by alireza0** [comment]
This repo has no ip limit
