### ISSUE TITLE
لودبالانسر

### ISSUE THREAD

**Issue by Masouddhojaei** [alireza0/x-ui#1352]
درود وقت بخیر
آیا راهی برای لودبالانس یک سرور خارج و دو سرور ایران در روش ریورس پنل به پنل وجود داره ؟ و اگر بله میشه لطفا روشش رو توضیح بفرمایید من با آزمون و خطا به نتیجه درستی نرسیدم، فقط با اضافه کردن بالانسر و روتینگ رول تونستم به دو سرور ایران متصل کنم اما آیپی ایران رو برمیگردونه و ریورس تانل به خوبی انجام نمیشه.
هدف از این کار هم تجمیع پهنای باند دو سرور ایران هست، اگر راه بهتری وجود داره برای این امر لطفا من رو راهنمایی کنید.

**Comment by alireza0** [comment]
درود بر شما
راه رو دارید اشتباه میرید. دلیلی برای استفاده از بالانسر نیست!
ترافیک هر سرور با دامنه تعریف شده توی تنظیم تانل معکوس شناخته میشه.

تجمیع پهنای باند به چه دردی میخوره ؟ این پنل به شما ترافیک خروجی ها رو نشون نمیده که بخواید نتیجه بگیرید.
به جای این کار میتونید هر دو تانل رو به خروجی direct جداگانه بفرستید.

**Comment by Masouddhojaei** [comment]
ارادت
برای مثال دو سرور ایران با پهنای باند محدود داریم و میخوایم با تجمیع اونها سرعت رو بهبود بدیم.
میشه لطفا توضیح بیشتری برای خروجی direct جداگانه بفرمایید ؟ با این کار چه اتفاقی میوفته؟ و روشش رو یکم اگر امکانش هست روشن تر کنین.

**Comment by alireza0** [comment]
من هنوز متوجه نشدم تجمیع و ترافیک محدود چه ارتباطی با تانل معکوس و لودبالانس داره؟!
یه جایی شاید داده ها رو اشتباه دادین: 
ارتباط کاربر رو میخواید بین دو سرور ایران لود بالانس کنید؟
دو سرور خارج دارید و میخواید یک سرور ایران بین اون دوتا لود بالانس بشه؟

**Comment by Masouddhojaei** [comment]
ببینید من دو سرور ایران با پهنای باند 20 مگابیت دارم و یک سرور خارج، اینهارو به روش تانل معکوس پنل به پنل ارتباطشون رو برقرار کردم یعنی دوتا بخش ریورس در سرور خارج ایجاد کردم که هر کدوم به یک سرور ایران میرن، حالا هدف من اینه که من بیام این ارتباط رو بصورت لودبالانسینگ یا هر روشی که بتونه ترافیک رو بین دو سرور ایران پخش کنه برقرار کنم تا کانفیگ تانل من بجای 20 مگابیت ، 40 مگابیت پهنای باند ارائه کنه! 
یکی از کارهایی که تست کردم این بود که اومدم بالانسر رو برای این دو ریورس تعریف کردم و در بخش روتینگ رول ها قبل از رول های مربوط به ریورس اون بالانسر رو قرار دادم و نتیجش این شد که ترافیک بین دو سرور ایران پخش شد و هر دفعه که my ip میگرفتم آیپی متفاوت سرورهای ایران رو نشون میداد، مشکل این بود که این ارتباط با دیگه ارتباط بین الملل نداشت و از سرور خارج آیپی نمیداد .

**Comment by alireza0** [comment]
همونطور که حدس میزدم تعریفتون اشتباه بوده.
سرور خارج ترافیک ایجاد نمیکنه بلکه کاربرها هستند که ترافیک ایجاد میکنن.
به روش تانل معکوس نباید دست بزنید و برای هر سرور تانل مجزا با دامنه مجزا ایجاد کنید.
برای تقسیم ترافیک، کاربرها رو تقسیم کنید و یا اگر از دامنه استفاده میکنید، ip های دو سرور ایران رو در یک دامنه تعریف کنید. با این روش کاربرها ترافیک رو‌بین دو سرور تقسیم میکنند و میفرستند.

**Comment by Masouddhojaei** [comment]
درسته متوجه شدم سپاس از راهنماییتون
یعنی یک دامنه که به دو آیپی سرور ارجا داده شدن رو به بخش ریورس تانل اضافه کنم ؟ یا بعد از برقرار کردن ریورس تانل این دامنه رو در کانفیگ ها قرار بدم ؟

**Comment by Masouddhojaei** [comment]
و مورد دیگه اینکه مثلا کلاینت Hiddifyng در اندروید ، با قابلیت لود بالانس میتونه همزمان به دو کانفیگ متصل بشه و دقیقا همین هدف من که تجمیع پهنای باند دو سرور ایران هست رو انجام میده.

**Comment by alireza0** [comment]
> درسته متوجه شدم سپاس از راهنماییتون
> 
> یعنی یک دامنه که به دو آیپی سرور ارجا داده شدن رو به بخش ریورس تانل اضافه کنم ؟ یا بعد از برقرار کردن ریورس تانل این دامنه رو در کانفیگ ها قرار بدم ؟

نه ریورس هر هرکدوم جداگونه باید متصل بشن

**Comment by alireza0** [comment]
> و مورد دیگه اینکه مثلا کلاینت Hiddifyng در اندروید ، با قابلیت لود بالانس میتونه همزمان به دو کانفیگ متصل بشه و دقیقا همین هدف من که تجمیع پهنای باند دو سرور ایران هست رو انجام میده.

بله
استفاده از هیدیفای هم میتونه مفید باشه
