### ISSUE TITLE
تنظیمات کانفیگ سرور

### ISSUE THREAD

**Issue by mfniaki** [alireza0/x-ui#1353]
سلام خسته نباشید
من میخواستم سمت کانیفگ json پنل ست کنم که فقط مثلا وبسایت youtube.com رو از طریق vpn باز کنه و بقیه سایت ها و دامنه هارو به صورت دایرکت باز کنه. ایا همچین تظیماتی میشه ست کرد؟

**Comment by alireza0** [comment]
درود بر شما
اعمال محدودیت در سمت کاربر به راحتی قابل دور زدنه.
بهتره از سمت سرور محدود کنید
