### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#1354]
علیرضای عزیز
سلام و تشکر 
گاهی به نکته‌هایی برمی‌خورم که شاید به درد بقیه هم بخوره و قاعدتاً جاش توی بخش issues نیست.
می‌خواستم بدونم دلیل خاصی داره که بخش discussions نداریم اینجا؟

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی و پیشنهادتون.
بله، متاسفانه وقتی برای مدیریت اون بخش ندارم.

**Comment by alireza0** [comment]
متاسفانه تجربه خوبی نداشتیم و کامیونیتی ها بیشتر دنبال سود شخصی و فروش هستند به جای اینکه مشکلات رو حل کنند.
جا انداختن فرهنگ استفاده کار ما نیست و مدیریت خیلی سخت میشه.
به جاش میتونید از گروه های تلگرامی موجود استفاده کنید.
