### ISSUE TITLE
Fragmentation per Inbound

### ISSUE THREAD

**Issue by ali-de7** [alireza0/x-ui#1358]
**Is your feature request related to a problem? Please describe.**

Right now we can set the Fragmentation in the Subscription Json. However, this setting will be applied to all the inbounds. Therefore, all the inbounds will share the same Fragmentation values. 
This is not ideal as in many cases you need to have different Fragmentation values to cater to different mobile networks. 

**Describe the solution you'd like**
Adding a Fragmentation section in each inbound could solve this problem IMO. 
Something like:
<img width="518" alt="Screenshot 2024-07-12 at 13 35 40" src="https://github.com/user-attachments/assets/085f6bc9-529a-4a5a-baed-cfa5a6979328">

**Describe alternatives you've considered**
I tried to alter the values for each inbound using CloudFlare worker. However, this will require to have CloudFlare proxy ON. 

**Additional context**
I am aware that currently there is no standard way of defining Fragmentation for non-Json URLs. However, enabling this feature would greatly help to pass through the GFW.

**Comment by alireza0** [comment]
Fragmentation is not a part of inbound configuration and could not help in this regard.
As you already mentioned, there is no standard way of producing Fragmentation on link.
As far as having this limitation (+ lots of other limitations), and solutions could be applied only in JsonSub, this idea could not be take place.

If I find a way I will implement it ASAP.
