### ISSUE TITLE
Exhaustion traffic threshold

### ISSUE THREAD

**Issue by smblue07** [alireza0/x-ui#136]
سلام این قسمت Exhaustion traffic threshold نه توی ربات و نه توی پنل (از ورژن 0.4.0 به بعد) مشکل داره
یعنی وقتی این مقدار 1GB در نظر گرفته میشه ، یوزهایی که حجمشون کمتر از 1 گیگ مونده رو نمایش نمیده . بنظرم یه بررسی کنید و مشکل حل بشه عالیه
با تشکر

**Comment by smblue07** [comment]
سلام مجدد
در pre release قسمت حجم کاربر هم مشکل داره و کاربری که تازه ایجاد میشه حجمش محاسبه نمیشه و روی صفر ثابت می‌مونه!

**Comment by alireza0** [comment]
این تنظیمات در بخش policy درست هستند.
لطفا تنظیمات کاربر رو هم ارسال کنید

**Comment by smblue07** [comment]
داداش یوزر دارم روی پنل مجبور شدم داونگرید کنم به نسخه قبلی پنل
اون مورد انقضای ترافیک بررسی ای انجام دادید قربان؟

> قسمت Exhaustion traffic threshold نه توی ربات و نه توی پنل (از ورژن 0.4.0 به بعد) مشکل داره
> یعنی وقتی این مقدار 1GB در نظر گرفته میشه ، یوزهایی که حجمشون کمتر از 1 گیگ مونده رو نمایش نمیده . بنظرم یه بررسی کنید و مشکل حل بشه عالیه
> با تشکر
