### ISSUE TITLE
Change in the database is not applied

### ISSUE THREAD

**Issue by MJamshidnejad** [alireza0/x-ui#1361]
Dear Alireza

I tried to increment the expiration time of all users by changing the database. I got the db file from the "panel, backup section" and restored the changed db with the panel. But the change was not applied in the panel (the remaining time was not changed).
My script just changes the expiry_time column in clients_traffic. I checked the database file before and after the change, and the script works correctly.

**Desktop (please complete the following information):**
 - Platform: Docker
 - Panel Version 1.8.4

**Comment by MJamshidnejad** [comment]
I noticed something wired!

![2024-07-13_09-51-09](https://github.com/user-attachments/assets/cb83fabf-b4ef-43db-a695-9357ec3ca389)

**Comment by alireza0** [comment]
Dear @MJamshidnejad ,
Changing database is not recommended when the panel is running. It may cause several problems.
As @pulsarice mentioned, there are lots of dependencies which should be considered.
You can use API instead

**Comment by MJamshidnejad** [comment]
> Dear @MJamshidnejad , Changing database is not recommended when the panel is running. It may cause several problems. As @pulsarice mentioned, there are lots of dependencies which should be considered. You can use API instead

I was aware of that. I replaced the changed one with the old one and then restarted the compose file.

**Comment by MJamshidnejad** [comment]
> User traffic cap and expiry times are also written in this part of database in json format: `inbounds table, settings column`. I was trying to change user traffic caps by editing client_traffics table, but it was being reverted back to previous values. Then I found out that this part should to be modified:
> 
> ```
> {
>   "clients": [
>     {
>       "email": "username",
>       "enable": true,
>       "expiryTime": 0,
>       "flow": "",
>       "id": "UUID",
>       "reset": 0,
>       "subId": "",
>       "tgId": "",
>       "totalGB": traffic_cap
>     },
> ...
> ```

Thanks for your help. So just the JSON part has to be changed, right? or both, JSON and client_traffics?

**Comment by alireza0** [comment]
Simply check what panel is doing in browser's developer mode.
