### ISSUE TITLE
"Empty" address in subscription

### ISSUE THREAD

**Issue by pebalk** [alireza0/x-ui#1362]
In the subscription `"outbounds":` section `"address": ""` is left empty which cause to fail subscription service:
```json
    "outbounds": [
      {
        "protocol": "shadowsocks",
        "...": "..."
          },

        "settings": {
          "servers": [
            {
              "...": "...",
              "address": "",
              "port": 12345,
              "...": "..."
            }
          ]
        }
      
```
Instead while checking generated URL and link via `Inbounds-Details` all is generated correctly using the `hostname` provided.

It might be the issues with [https://github.com/alireza0/x-ui/blob/main/web/assets/js/model/xray.js#L1284](url) and similar functions as later `address` is used to generate link instead of `host` variable:
```js
genSSLink(address='', port=this.port, forceTls, remark='', clientPassword) {
//...
 let link = `ss://${safeBase64(settings.method + ':' + password.join(':'))}@${address}:${port}`;
//...
}
```

**Comment by alireza0** [comment]
It might be related to your configuration in External Proxy.
genSSLink is a function for generating link and not related to the json Sub!
Link generator is already uses more complex usage of host: https://github.com/alireza0/x-ui/blob/main/web/assets/js/model/xray.js#L1513
