### ISSUE TITLE
Periodic unplanned x-ui/x-ray Restarts

### ISSUE THREAD

**Issue by shayan775** [alireza0/x-ui#1364]
im facing a serious problem here, i have about 15 servers each with a seprate panel installed. when i check them, none of them have an xray-core uptime of more than 5 minutes!

when i monitor some of them with lower count of cpu cores, usually this happens because of CPU overload, but the overload is not caused by xray core, rather by the x-ui panel itself! what is it that the x-ui do periodicly that causes such a massive CPU usage?

even in my servers with higher CPU core count this happens but this time not because of the CPU overload, rather by x-ui crashing, when you are in the panel "overview" screen, suddenly it crashes for a second and when it comes back up the xray uptime is 0s.
i have a telegram robot in back, using the apis to modify the clients, can it be that the robot sending buggy requests ( like a client add request with  wrong fields data type, for example a null email address) causes the panel to crash or cpu overload?

**Comment by alireza0** [comment]
In this panel, xray-core is running as a part of x-ui. Some reports will be deceptive due to this fact.
I am not in your server and not aware of your solution. You did not mention it as well.
Please consult a system engineer.

**Comment by shayan775** [comment]
Thanks for your response, I finally found the problem and decided to report it to you because i think it might help.
i have huge number of clients, 4 Inbounds each with about 5K clients.

The problem here is the `/xui/inbound/updateClient/` api! it consumes so much CPU when you have large number of clients! it doesn't matter how many CPU cores your server has, it only takes few subsequent `updateClient` request to make the server's CPU overwhelm and crash the xray. 

it would be great to optimize the algorithem of this api.

and i also have to mention that i only make `updateClient` requests to disable or enable a client most of the times, it can also come handy if enabling or disabling clients had its own fast api route.
