### ISSUE TITLE
فعال کردن فرگمنت برای اینباند منتخب در بخش ساب اسکریپشن جیسون

### ISSUE THREAD

**Issue by rasa68** [alireza0/x-ui#1367]
سلام و خسته نباشید.
امکانش هست در تنظیمات پنل، بخش Subscription Json وقتی Fragmentation رو فعال میکنیم این امکان باشه که از بین Inbound های پنل انتخاب کنیم که Fragmentation برای کدوم فعال باشه؟

**Comment by alireza0** [comment]
درود بر شما
تنظیمات فرگمنت به شکل محدود به ساب جیسون اضافه شده.
نظرات و ایده های زیادی در این زمینه داریم و هیچکدوم رو نمیشه جوری اضافه کرد که بقیه درخواست ها رو هم شامل بشه.
اگر به حالت کلی رسیدم که بتونه همه درخواست ها رو جواب بده و برای بقیه مشکلی ایجاد نکنه اضافه میشه.
