### ISSUE TITLE
باگ در ورژن پری ریلیز 0.5.0

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#137]
بنده به ورژن پری ریلیز 0.5.0 آپدیت کردم ولی یک باگ دیدم  در ایجاد کاربر وقتی حالت  شروع با اولین اتصال روشن میشه نمیشه هیچ عددی وارد کرد در تعداد روزها و فقط 0 وارد میشه و بقیه اعداد غیرفعاله
five icon هم که اد نشده  من که چیزی ندیدم چند بار هارد دیفرش هم کردم
لینک سابسکریشن هم درست کار نمیکنه و پورت پنل رو اد نمیکنه تو لینک و باید دستی اد کرد تا کار کنه

**Comment by alireza0** [comment]
سپاس از گزارشتون.
من توی سرور ها مشکلی برای تغییر تعداد روزها ندیدم.
اگر ممکنه عکسش رو بفرستید.
لینک ساب رو حتما درست میکنم 🙏🏻

**Comment by aliamg1356** [comment]
> سپاس از گزارشتون. من توی سرور ها مشکلی برای تغییر تعداد روزها ندیدم. اگر ممکنه عکسش رو بفرستید. تصویر favicon رو آپدیت کردم و درست شده لینک ساب رو حتما درست میکنم 🙏🏻
![Untitled](https://user-images.githubusercontent.com/124570423/229885191-b1aeea79-2f51-4989-9cc5-8230edd22360.jpg)
برای من فقط صفر هست و فقط صفر نوشته میشه

**Comment by alireza0** [comment]
اول ببینید با علامت های کم و زیاد میتونید اضافه کنید ؟
کیبوردتون حتما باید روی انگلیسی باشه.
اگر نشد خطای کنسول مرورگر رو چک کنید

**Comment by aliamg1356** [comment]
> اول ببینید با علامت های کم و زیاد میتونید اضافه کنید ؟ کیبوردتون حتما باید روی انگلیسی باشه. اگر نشد خطای کنسول مرورگر رو چک کنید

نه با علامتهای کم و زیاد و نه هیچ جوری عدد اضافه نمیشه  تو مرورگر های متفاوت و تو سیستم دیگه هم تست شد

**Comment by alireza0** [comment]
مشکل رو دیدم.
این مشکل فقط توی ایجاد کاربر جدید هست. بعد از ایجاد میتونید تغییر بدید. توی انبوه سازی هم درست کار میکنه.
برای ریلیز حتما حل میکنم
سپاسگزارم

**Comment by alireza0** [comment]
https://github.com/alireza0/x-ui/releases/tag/0.5.0
