### ISSUE TITLE
هنگ کردن

### ISSUE THREAD

**Issue by ali90500** [alireza0/x-ui#1371]
سلام 
من چند روزه یکی از سرورام 15 دقیقه یه بار کل کانفیگا قطع میشه و پنل ریست میشه
لاگ هم اینه
2024/07/16 11:52:23 WARNING - X-UI: [iplimit] fail2ban is not installed. IP limiting may not work properly.
2024/07/16 11:52:18 DEBUG - X-UI: Failed to fetch Xray traffic:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/07/16 11:52:18 DEBUG - X-UI: Failed to query Xray stats:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/07/16 11:52:18 DEBUG - X-UI: Failed to fetch Xray traffic:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/07/16 11:52:18 DEBUG - X-UI: Failed to query Xray stats:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/07/16 11:52:12 WARNING - X-UI: [iplimit] fail2ban is not installed. IP limiting may not work properly.
2024/07/16 11:52:08 WARNING - X-UI: [iplimit] fail2ban is not installed. IP limiting may not work properly.
2024/07/16 11:52:07 DEBUG - X-UI: Failed to fetch Xray traffic:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/07/16 11:52:07 DEBUG - X-UI: Failed to query Xray stats:rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by MHSanaei** [comment]
شما iplimit  فعال دارید ولی fail2ban نصب نکردید
یا غیرفعال کنید و یا پیشنیاز رو رعایت کنید
در صورت غیرفعال کردن ای پی لیمیت از داخل تنظیمات اکسس لاگ هم بردارید چرا که فشار زیادی به سرور وارد میکنه
