### ISSUE TITLE
Please add an option to exclude specific IPs for BOT notification

### ISSUE THREAD

**Issue by Amir-Ali-GH** [alireza0/x-ui#1374]
Please add an option to exclude specific IP addresses from bot login notifications. For example, IP addresses like loopback (::1).

---

If you need any adjustments or additional details included, let me know!

**Comment by alireza0** [comment]
It is not what users realy needs.

It could be only problematic when you have a bot which uses api and is doing login before each request.
This usage is wrong!
To fix it, developer needs to get cookies after login and takes care of expiration time.
On each request it needs only to use this cookie.
