### ISSUE TITLE
درخواست یک ویژگی کاربردی

### ISSUE THREAD

**Issue by straymail** [alireza0/x-ui#138]
سلام و خسته نباشید

لطفا امکان محدودیت سرعت گذاشتن برای کانفیگ ها را قرار دهید(یکی از پنل های مشابه x-ui این ویژگی را دارد ولی فقط پنل تروجان است)

(به این دلیل که برخی کانفیگ ها با اینترنت پرسرعت و فیبرنوری که در اختیار دارند اکثر سرعت سرور را اشغال می کنند، با ویژگی بالا میتوان کیفیت اتصال هر کانفیگ را تضمین کرد)

با احترام

**Comment by alireza0** [comment]
درود بر شما
متاسفانه این امکانات با اهداف این پنل همخونی نداره و بهتره از نرم افزارهای کمکی استفاده کنید
