### ISSUE TITLE
مشکل در ریست کردن ترافیک کلاینت

### ISSUE THREAD

**Issue by CRVCKheAD-Blz** [alireza0/x-ui#1380]
AxiosError: Request failed with status code 404
وقتی ترافیک یک کلاینت رو به یکی از inbounds اضافه شده ریست میکنم این ارور رو‌میده

**Comment by alireza0** [comment]
این مشکل عدم ارتباط با سرور میتونه باشه.
بدون اطلاعات کافی نمیشه روش کار کرد
