### ISSUE TITLE
[FR] Separate inbounds and clients.

### ISSUE THREAD

**Issue by deepsm0ke** [alireza0/x-ui#1385]
Hello Mr.Alireza . My request is that, if it is possible, it should be done like marzban or hiddify panel, so that inbounds and clients are separated from each other, so that a client can use several inbounds.
for example: configurations that are created may be successfuly used on one ISP but, not to use successfuly on another ISP! And the problems that arise are that if two clients are created for one person, both consumption volumes cannot be controlled and there is a possibility of misuse!

If this possibility is implemented, it can help a lot for better management.

also 3x-ui (MHSanaei).

Tnx.

**Comment by alireza0** [comment]
Hello @deepsm0ke,

Unfrtunately the base of this app could not support this feature
