### ISSUE TITLE
external proxy+header

### ISSUE THREAD

**Issue by alihosseinii67** [alireza0/x-ui#1386]
سلام وقت بخیر میشه چند اکسترنال پروکسی وارد کرد که هرکدام هدر متفاوتی داشته باشه؟

**Comment by alireza0** [comment]
درود بر شما
این ویژگی فعلا در پنل وجود نداره.
امکانش هست ولی به دلایل مختلف نمیشه سودش رو بیشتر از ضررش در نظر گرفت
