### ISSUE TITLE
new admin

### ISSUE THREAD

**Issue by abbasand** [alireza0/x-ui#1388]
سلام مهندس اگه میشد یک ادمین دیگه با دسترسی محدود تر مثلا امکان حذف ویرایش و ... کلاینت هارو  رو نداشت خیلی عالی میشد

**Comment by dev-ir** [comment]
bash <(curl -Ls https://raw.githubusercontent.com/dev-ir/xui-assistant/master/installer.sh)

> سلام مهندس اگه میشد یک ادمین دیگه با دسترسی محدود تر مثلا امکان حذف ویرایش و ... کلاینت هارو رو نداشت خیلی عالی میشد
