### ISSUE TITLE
ویژگی های ابدیت در پنل من اظافه نشد

### ISSUE THREAD

**Issue by masoud-gb** [alireza0/x-ui#139]
درود و عرض خسته نباشید علیرضا جان عزیز❤
ممنون از زحماتی که در توسعه این پنل کشیدی و میکشی
من به اخرین نسخه ابدیت کردم اما هیچ کدام از ویژگی های داخل اسکرینشات در پنل اظافه نشد.
با احترام

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهیتون. هنوز نسخه در حالت pre-release هست و منتظر تست ها هستم.
میتونید با اسکریپت دستی رائه شده توی راهنما، ورژن رو 0.5.0 بزنید:
```
bash <(curl -Ls https://raw.githubusercontent.com/alireza0/x-ui/master/install.sh) 0.5.0
```
لطفا خطا ها رو گزارش کنید تا بتونم نسخه نهایی رو public کنم.

سپاسگزارم

**Comment by shahrooz1349** [comment]
بسیار عالی حتما نصب میکنم اگر مشکلی پیدا شد قطعا خدمتتون عرض میکنم
ارادت عزیزم

**Comment by arsoltani72** [comment]
سلام و عرض ادب 
نمیشه تعداد روز رو ست کرد عدد قبول نمیکنه

**Comment by Vahidno13** [comment]
سلام و خسته نباشید
مقدار حجم مصرفی رو هم توی ورژن جدید ثبت نمیکنه

**Comment by alireza0** [comment]
درود بر شما @arsoltani72 
بله تایید میکنم.
این مشکل فقط توی ایجاد کاربر جدید هست. بعد از ایجاد میتونید تغییر بدید. توی انبوه سازی هم درست کار میکنه.
برای ریلیز حتما حل میکنم
سپاسگزارم

**Comment by alireza0** [comment]
https://github.com/alireza0/x-ui/releases/tag/0.5.0

**Comment by shahrooz1349** [comment]
@alireza0 
علیرضا عزیز خسته نباشی ابدیت 40 دقیقه پیش رو هم نصب کردم تنها مشکل در نمایش ترافیک و تاریخ که بعد از استارت اکانت ایجاد نمیشه 
ممنونم از این کار ارزشمند 🙏🌹

**Comment by alireza0** [comment]
@shahrooz1349 
درود بر شما
تایید میکنم این باگ رو. تصحیح کردم و دارم دوباره 0.5.0 تصحیح شده رو جایگذاری میکنم

**Comment by arsoltani72** [comment]
الان مشکل حل شده ؟

**Comment by alireza0** [comment]
بله. آپلود و پابلیک شده. میتونید تست کنید.

**Comment by shahrooz1349** [comment]
در ابدیت جدید ایکسری ارور میده نصب مجدد انجام دادم به بعد از انتقال بکاپ و ریبوت سرور مجدد ایکسری ارور میده

**Comment by shahrooz1349** [comment]
در اخرین ابدیت همه چیز عالی کار میکند تنها مشکل استفاده از گزینه جدید ثبت تاریخ پس از اولین استفاده است که ایکسری را دچار خطا میکند
با احترام 🌹

**Comment by alireza0** [comment]
@shahrooz1349 
لطفا خطا رو برای من ارسال کنید

**Comment by shahrooz1349** [comment]
@alireza0 
علیرضا جان خسته نباشی به لطف زحمات شما پنل بدون کوچکترین مشکلی با تمام ویژگی ها کار میکنه 🙏🌹

**Comment by arsoltani72** [comment]
دوستان کسی سرور ایران معرفی میکنه 
واقعا نمیدونم از کجا سرور بگیرم پول بالا نکشه
