### ISSUE TITLE
مشاهده حجم مصرفی

### ISSUE THREAD

**Issue by mehrzad7394** [alireza0/x-ui#1390]
salam,man panel ro update kardam va dg hajm masrafi user neshan dade nemishe,va hamishe sabet hast.
hata user online ham to panel neshan dade nemishe.
log:

X-UI: get xray traffic failed:rpc error: code = Unknown desc = app/stats/command: QueryStats only works its own stats.Manager.

lotfan rahnami konid chikar bayad bokonam.mamon az shoma

![image](https://github.com/user-attachments/assets/ab371987-73cd-4363-af59-166aae6a6825)

**Comment by RuMoradi** [comment]
دقیقا منم این مشکل رو دارم.  بعد از اپدیت اینجوری شده. البته الان دیگ مجبورم نسخه های قبلی رو نصب کنم ببینم کدومشون درست کار میکنه دیگ اپدیت نکنم

**Comment by alireza0** [comment]
درود بر شما
برای اینکه سوال شما بتونه پاسخ داشته باشه، باید اطلاعات بیشتری رو ارائه بدید.
هیچکسی نمیتونه اینجوری کمکی بکنه
