### ISSUE TITLE
ریورس پنل به پنل

### ISSUE THREAD

**Issue by alihosseinii67** [alireza0/x-ui#1392]
سلام من از روش ریورس پنل به پنل دارم استفاده میکنم .میشه تو قسمت خروجی تنظیم کرد مثل وارپ چندتا سایت مشخص به ایپی یه سرور دیگه وصل بشه

**Comment by alihosseinii67** [comment]
من سرور اصلیم ایرانه سرور خارجم از فنلاند.الان باید تو سرور المان پرتال بسازم و تو سرور ایران بریج دوباره درسته؟

**Comment by alihosseinii67** [comment]
البته یه مشکل دیگه هم هست سرور باید خام باشه؟ چون سرور المانم خودش به یه سرور ایران دیگه وصله

**Comment by oops10101** [comment]
https://youtu.be/jCg6Yci7a5U اینجا آموزش کامل هست
