### ISSUE TITLE
پنل همکاری

### ISSUE THREAD

**Issue by JustPooya** [alireza0/x-ui#1394]
سلام و عرض تشکر و خسته نباشید
ی پیشنهاد داشتم برای پنل ، اگر بشه یوزری ک توسط کنسول تعریف میشه به عنوان یوزر روت باشه و یوزر روت بتونه یوزر های مختلفی با سطح دسترسی های مختلفی رو در پنل ایجاد کنه
ب عنوان مثال آقای ایکس یوزر روت هستش ، برای آقای ایگرگ یوزری تعریف میکنه و دسترسی فقط به صفحه اصلی و تک اینباند مخصوص اون یوزر رو میده ، یا فقط دسترسی به اینباند تنها بدون اینکه بقیه صفحه ها یا تنظیمات پنل و ایکس ری رو بتونه ببینه میده
اگر بشه این دسترسی رو جوری تعریف کرد ک مثلا فقط تک اینباند خاصی رو مشاهده کنه ک عالی میشه ، یا دسترسی های مختلف گذاشته بشه و یوزر روت هر بخش رو میخاد تیک بزنه برای اون یوزر جدید
اگر این قابلیت ایجاد بشه مطمئنا کمک بسیار بزرگی در جهت فروش همکاری خواهد بود .
متشکرم

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی و پیشنهاد شما
این پنل برای کارهای تجاری ساخته نشده و این مدل ویژگی ها هیچ اولویتی برای ما نداره.
جدا از اینکه ساختار این پنل اجازه چنین کاری رو نمیده و ما سعیمون اینه که به ساده ترین شکل ممکن بتونه ارائه بشه
