### ISSUE TITLE
هسته Xray

### ISSUE THREAD

**Issue by dani96102** [alireza0/x-ui#1395]
باسلام
لطفا اگر امکانش ویژگی ری استارت اتوماتیک هسته xray همراه با تایمر به پنل خودتون و ثنایی اضافه کنید
در بعضی موارد مثل اضافه کردن وارپ به پنل وقتی بار ترافیکی زیاد میشه هسته دچار کندی میشه و نیاز هست که مثلا بزاریم هر نیمساعت ری استارت بشه تا کیفیت اتصال ها حفظ بشه و دچار کندی و قطعی نشن

**Comment by JustPooya** [comment]
الان با ی کرون جاب میتونی این کار رو انجام بدی
ی کرون جاب نیم ساعته بنویس ک بیاد دستور زیر رو اجرا کنه
x-ui restart
