### ISSUE TITLE
Panel goes out of access after installing self signed certificate

### ISSUE THREAD

**Issue by BSarmady** [alireza0/x-ui#1396]
Panel goes out of access after installing self signed certificate

after installing a self-signed certificate (successful) panel cannot be reached, no connection can be made to it.

Is there any other setting that I need to change?

I can reset the settings and then change back port to my custom port to access it without SSL

**Comment by alireza0** [comment]
It depends on your configuration and access way. Please consult with a system admin.

**Comment by BSarmady** [comment]
@alireza0 I'm the system admin!

**Comment by alireza0** [comment]
Then find the system problem and fix it. There is no evidence which shows that this problem is related to the panel
