### ISSUE TITLE
Reduce size of panel

### ISSUE THREAD

**Issue by BSarmady** [alireza0/x-ui#1397]
**Is your feature request related to a problem? Please describe.**
On a slow connection that is caused by internet access blockage, having to download about 15Mb to access panel is kind of huge.

**Describe the solution you'd like**
reduce the size of CSS, Javascript and html of the pages (as simple as possible) . I believe using vue to create the panel to just make it look beautiful is too much. in some cases I believe size of panel can be reduced to below 500k

**Describe alternatives you've considered**
You could add this feature during setup to allow users to choose between simple and fancy panel

**Additional context**
N/A

**Comment by alireza0** [comment]
It is not dial-up age and 90th.
Working on size is not necessary and will avoid us to provide more features.
Also it is not a public page. But only an admin page which should be opened and managed by only admins.

**Comment by BSarmady** [comment]
@alireza0, it is still 90s in Iran.
I assume you haven't lived in Iran for very long time. In here, the difference between a page functioning correctly or completely fail is just a few KB. 

Also I'm the admin trying to set it up from Iran. I shouldn't need to use a proxy to setup a proxy. 

Anyway, I've built a local copy, picked up the config and dropped it in the server without UI and it works.

**Comment by alireza0** [comment]
BTW: It is in my plan to change the API. But with lower priority.
After that, loading will be more efficient specially for helping panels which have more users.
