### ISSUE TITLE
مشکل در اضاف کردن کانفیگ ها در اپدیت جدید Nv با استفاده از QR CODE

### ISSUE THREAD

**Issue by Moh4mm4d1989** [alireza0/x-ui#1401]
درود
در اپدیت جدید پنل 1.8.5 متاسفانه هنگام اضاف کردن کانفیگ ها از طریق QR CODE در داخل نرمافزار NV از طریق اسکن وارد نمی شوند البته روی نوع VMESS اما روی VLESS وارد میشود اما کار نمیکند
همچنین FAVICON هم نیست در این اپدیت!!!
تشکر

**Comment by alireza0** [comment]
درود بر شما
مشکل از بروز نبودن نرم افزار سمت کاربره.
لطفا از اونها پیگیری کنید و یا از نسخه های پایین تر پنل استفاده کنید
