### ISSUE TITLE
Restarting the panel when activating the disabled user

### ISSUE THREAD

**Issue by sssagsag** [alireza0/x-ui#1406]
hello and thanks for x-ui panel  there is a problem in the xui panel that has been there for a long time.
When a user is in disabled or depleted status and we activate it, the panel and xraycore will be restarted, and if the server traffic is high, it will cause the xraycore to be in stop status for about 15 seconds.
please fix this problem

![xui](https://github.com/user-attachments/assets/5753d4dd-d85b-465b-8d15-155bc37fb31a)

**Comment by alireza0** [comment]
Thank you for your report.
It is fixed now and will be available in next version

**Comment by sssagsag** [comment]
> Thank you for your report. It is fixed now and will be available in next version

thanks dear alireza
