### ISSUE TITLE
اضافه کردن فیک tls

### ISSUE THREAD

**Issue by v2rayirani** [alireza0/x-ui#1408]
سلام علیرضا جان با توجه به محبوبیت CDN هایی مثل fastly و gcore تقاضا دارم که بشه از داخل پنل SNI اضافه کرد می دونم که سرتون شلوغه می دونم که کارتون دشواره ازتون تشکر میکنم
کلا به نظرم این اگه اضافه بشه جالب هستش توی قسمت اکسترنال پروکسی میشه TLS اضافه کرد ولی نمی شه تو SNI باشه اون آدرس
خلاصه بی سوادی مارو ببخش چون من مانند شما رفقا سواد ندارم

**Comment by alireza0** [comment]
درود بر شما
متاسفانه مشکل شلوغی زیاد و کاربر کم رو داشتیم وگرنه در همون زمان انجام شد.
بین سادگی و فیچر بیشتر، این مدل رو انتخاب کردیم.

**Comment by v2rayirani** [comment]
همین که جواب امثال منو میدین از بزرگواری شماست 
وگرنه می دونم شما صرفاً دلی کارو جلو میبرید
