### ISSUE TITLE
last version 0.5 adding user vless-vision resets fallback settings

### ISSUE THREAD

**Issue by lk29** [alireza0/x-ui#141]
{
	"POST": {
		"scheme": "https",
		"host": "xxxxxxx",
		"filename": "/xxxxx/xui/inbound/addClient",
		"remote": {
			"Адрес": "x.x.x.x:xxx"
		}
	}
}

id=1
settings={
  "clients": [
    {
      "id": "e97a46ab-de25-4a63-e5f9-d4eee0ceeb40",
      "flow": "xtls-rprx-vision",
      "email": "uuigq8n",
      "totalGB": 0,
      "expiryTime": 0,
      "enable": true,
      "tgId": "",
      "subId": ""
    },
    {
      "id": "e5550765-f2a8-404f-8b39-f570ad03f7a8",
      "flow": "xtls-rprx-vision",
      "email": "lg5kx55ei",
      "totalGB": 53687091200,
      "expiryTime": 1682340744000,
      "enable": true,
      "tgId": "66666",
      "subId": "66666"
    },
    {
      "id": "1aa4363d-36b2-4111-837d-70e9e59c1862",
      "flow": "xtls-rprx-vision",
      "email": "8h8tvtyl2u",
      "totalGB": 0,
      "expiryTime": 1681254297681,
      "enable": true,
      "tgId": "",
      "subId": ""
    }
  ],
  "decryption": "none",
  "fallbacks": [
    {
      "name": "",
      "alpn": "",
      "path": "",
      "dest": "",
      "xver": 0
    },
    {
      "name": "",
      "alpn": "",
      "path": "",
      "dest": "",
      "xver": 0
    }
  ]
}

**Comment by lk29** [comment]
I will try to repeat the experiment

**Comment by lk29** [comment]
tried to repeat but has not yet found a dependency, it is added normally

**Comment by alireza0** [comment]
I tried it several times! It never affects!
But it might be related to old configuration from old database. Isn't it ?

**Comment by alireza0** [comment]
@lk29 Could you please provide me a part of the `config.json` which contains this vless configuration( before update )?

**Comment by lk29** [comment]
Later

**Comment by lk29** [comment]
the problem is taking place, repeated the experiment several times.

**Comment by lk29** [comment]
`{
  "log": {
    "loglevel": "debug",
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/xray-error.log"
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "dns": null,
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "streamSettings": null,
      "tag": "api",
      "sniffing": null
    },
    {
      "listen": null,
      "port": 7777,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "email": "7777x3ex",
            "flow": "xtls-rprx-vision",
            "id": "8e194ee5-7777-4fb0-94bd-484303491b64"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "alpn": "",
            "dest": "/dev/shm/default.sock",
            "name": "",
            "path": "",
            "xver": 1
          },
          {
            "alpn": "h2",
            "dest": "/dev/shm/h2c.sock",
            "name": "",
            "path": "",
            "xver": 2
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "serverName": "",
          "minVersion": "1.2",
          "maxVersion": "1.3",
          "cipherSuites": "",
          "certificates": [
            {
              "certificateFile": "/etc/ssl/v2ray/fullchain.pem",
              "keyFile": "/etc/ssl/v2ray/privkey.pem"
            }
          ],
          "alpn": [],
          "settings": [
            {
              "allowInsecure": false,
              "fingerprint": "chrome",
              "serverName": ""
            }
          ]
        },
        "tcpSettings": {
          "acceptProxyProtocol": false,
          "header": {
            "type": "none"
          }
        }
      },
      "tag": "inbound-7777",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "transport": null,
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "stats": {},
  "reverse": null,
  "fakeDns": null
}`

**Comment by alireza0** [comment]
I did it several times with simulating same previus data as yours. It never happened! Weird!
```
id: 1
settings: {
  "clients": [
    {
      "id": "8e194ee5-7777-4fb0-94bd-484303491b64",
      "flow": "xtls-rprx-vision",
      "email": "7777x3ex",
      "totalGB": 0,
      "expiryTime": 0,
      "enable": true,
      "tgId": "",
      "subId": ""
    },
    {
      "id": "08bd8f0b-4466-468c-f33f-849a77f4f2fa",
      "flow": "xtls-rprx-vision",
      "email": "xsl6aynp",
      "totalGB": 53687091200,
      "expiryTime": 1685787598704,
      "enable": true,
      "tgId": "666",
      "subId": "666"
    }
  ],
  "decryption": "none",
  "fallbacks": [
    {
      "name": "",
      "alpn": "",
      "path": "",
      "dest": "/dev/shm/default.sock",
      "xver": 1
    },
    {
      "name": "",
      "alpn": "h2",
      "path": "",
      "dest": "/dev/shm/h2c.sock",
      "xver": 2
    }
  ]
}
```
And edit had no problem as well!
```
d: 1
settings: {
  "clients": [
    {
      "id": "8e194ee5-7777-4fb0-94bd-484303491b64",
      "flow": "xtls-rprx-vision",
      "email": "7777x3ex",
      "totalGB": 0,
      "expiryTime": 0,
      "enable": true,
      "tgId": "",
      "subId": ""
    },
    {
      "id": "08bd8f0b-4466-468c-f33f-849a77f4f2fa",
      "flow": "xtls-rprx-vision",
      "email": "xsl6aynp",
      "totalGB": 53687091200,
      "expiryTime": 1685787598704,
      "enable": true,
      "tgId": "6666",
      "subId": "6666"
    }
  ],
  "decryption": "none",
  "fallbacks": [
    {
      "name": "",
      "alpn": "",
      "path": "",
      "dest": "/dev/shm/default.sock",
      "xver": 1
    },
    {
      "name": "",
      "alpn": "h2",
      "path": "",
      "dest": "/dev/shm/h2c.sock",
      "xver": 2
    }
  ]
}
```

It is about interoperability with other/old database.
If in your tests, you have same error, it would be nice if you can send me the database ( email it to me ).

**Comment by lk29** [comment]
I will try to recreate the database, if it happens again then I will send

**Comment by alireza0** [comment]
It is fixed by this commit:
[Fix vless inbounds problem "decryption" set to null](https://github.com/alireza0/x-ui/pull/183/commits/2be3df59bef1bee51307e6c2505bae4c887768c3)

**Comment by lk29** [comment]
I'll check in the next few days but yes it looks like it was exactly that.
