### ISSUE TITLE
ساخت سرور کاهش پینگ با x-ui 

### ISSUE THREAD

**Issue by Phcayber** [alireza0/x-ui#1410]
سلام . من میخواستنم بدونم میشه از پنل x-ui برای ساخت سرور کاهنده پینگ بر بستر سرور ایران کرد ؟ 
ترنسمیشن  روی kcp و کانکشن هم udp باشه . 
من وقتی پنل رو با udp داخل کانتاینر ابر اروان نصب میکنم بالا نمیاد ولی وقتی به tcp تعغیرش میدم فعال میشه و درست کار میکنه .
لطفا منو راهنمایی کنید تا بتونم یک سرور کاهنده پینگ با ترنسمیشن kcp  و نوع اتصال udp  ایجاد کنم ممنون .

**Comment by alireza0** [comment]
درود بر شما
اینکه چه مدل تنظیمی میتونه به شما کمک کنه از تجربه من خارجه و باید از دوستان مجرب در گروه ها و کانال های مختلف نظرسنجی کنید.
