### ISSUE TITLE
A bug and a missing feature

### ISSUE THREAD

**Issue by MK0ltra** [alireza0/x-ui#1411]
1- By adding HttpOnly attribute to cookie https://github.com/alireza0/x-ui/commit/84ecdae7ca322c818d026ab9c1a4ecff5d708d00, login session are not persistent anymore and login needed everytime users try to access the panel. (document.cookie can't get cookies from client-side).

2- Not a bug but in freedom outbound should be a "redirect" field [based on document](https://xtls.github.io/config/outbounds/freedom.html#outboundconfigurationobject). It can be useful in some cases.

**Comment by alireza0** [comment]
1. Due to security issues, HttpOnly added. If you need to remain login, it is better to expans session-time value in Panel Settings.
2. Yes, it is. But is very complex. I will try to add it as well.

**Comment by alireza0** [comment]
Redirect is now added. You can find it in next release
