### ISSUE TITLE
Add get client config to api

### ISSUE THREAD

**Issue by AboutErfan** [alireza0/x-ui#1412]
سلام علیرضا جان خوبی؟
ببین API سیستمی که برای پنل در نظر گرفتی خیلی نواقص زیادی داره برای مثال نمیشه کانفیگ یوزر هارو از طریقش به دست آورد سر همین عملا صرفا بدرد این میخوره که بتونیم باهاش کانفیگ بسازیم و در اختیارشون بزاریم به صورت اتوماتیک برای همین بنظرم اگر این امکان هم اضافه کنی عالی میشه

همچنین دایکومنت خیلی ناقصی داره اصلا ارائه نشده چه دیتایی باید پاس بشه به پارامتر های پست صرفا فقط نوشته شده این دستورات هست بنظرم روی این قضیه نیاز هست کار کنی 
با تشکر ازت

**Comment by alireza0** [comment]
درود بر شما
بله این پنل اهداف دیگه ای داره و رایگاه ارائه میشه. نمیشه از این بابت بهش یه نرم افزار کامل گفت.
امکان گرفتن کانفیگ از طریق سابسکرپشن وجود داره، ولی دلیلی نداره کسی که کانفیگ رو از api میتونه بگیره، محاسبات ساده ساخت لینک رو نتونه انجام بده.
کدهاش هم موجوده.

کار داکیومنت بیشتر به دوستان دیگه بلاگر سپرده شده و بخشی از اون که در توانم بود رو [اینجا](https://alireza0.github.io/fa/docs/) گذاشتم
