### ISSUE TITLE
routing rules via subscription

### ISSUE THREAD

**Issue by FranchukAndrei** [alireza0/x-ui#1414]
I'm using x-ui for family vpn service. There are about 10 clients. I so config every client to direct connection for my country resources via domain suffix and geoip. I have to manually configurate routing settings on every client. I'm using subscriptions to transfer x-ray config to client. It would be grate, if i could update client routing config via subscription too.

**Comment by alireza0** [comment]
You can use json subscription. It supports some direct rules for specific countries.
Unfortunately due to client app shortage, we are not encouraged to expand it yet.
