### ISSUE TITLE
logout شدن بعد از زمان کوتاه

### ISSUE THREAD

**Issue by mahdi271** [alireza0/x-ui#1415]
تو نسخه های جدید بعد از لاگین شدن بعد مدت کوتاهی Logout میشه و باز باید مجدد ورود کرد و رو تعداد سرور بالا خیلی ازار دهنده هست، با اینکه از تو تنظیمات هم مثل قبل عددی واسه سشن در نظر گرفته نشده ،

**Comment by MHSanaei** [comment]
وقتی مقدار صفر ست هر یه ساعت پنل خارج میشه اگر مقدار دیگه ای نیاز دارید داخل تنظیمات به دقیقه قرار بدید
و از همه مهمتر سوالات خودتون رو برای علیرضا قرار ندید

**Comment by RuMoradi** [comment]
> وقتی مقدار صفر ست هر یه ساعت پنل خارج میشه اگر مقدار دیگه ای نیاز دارید داخل تنظیمات به دقیقه قرار بدید و از همه مهمتر سوالات خودتون رو برای علیرضا قرار ندید

سلام آقا من هم رو پنل خودتون و هم نسخه علیرضا این مشکل رو دارم که حجم مصرفی کاربرها محاسبه نمیشه و همه اش 0 میزنه. پنل هارو پاک کردم کامل دوباره اخرین نسخه رو نصب کردم و بکاپ وارد کردم حجم هارو حتی ریست کردم کاربر جدید هم ساختم ولی بازم مشکل حل نشد برای یوزرهای جدید هم اصلا محاسبه نمیکنه حجم مصرفی رو . بیزحمت راهنمایی کنید

**Comment by MHSanaei** [comment]
@RuMoradi
 مشکل از تنظیمات شما هست و داخل xray configs دکمه ریست رو بزنید و مجدد تنظیم کنید
