### ISSUE TITLE
udp random ports??

### ISSUE THREAD

**Issue by oops10101** [alireza0/x-ui#1418]
hey there so I'm like 90 percent sure I'm just misunderstanding something here but I had to report this I'm using socks5 as outbound and everytime x-ray wants to dial the socks server it sends the request to a random port which I assume its why it fails (guessing this is why I'm not receiving any DNS requests and having to use local DNS ) but TCP connections get the port perfect every single time .... I'm genuinely so confused can someone explain this?

a part of the logs: (12324 is the right port and all the others are wrong ports)

2024/08/20 20:29:10 [Debug] [1703179829] transport/internet: dialing to tcp:92.61.107.63:12324
2024/08/20 20:29:10 [Debug] [2003518696] transport/internet: dialing to udp:92.61.107.63:17264
2024/08/20 20:29:10 [Info] [2437312862] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > proxy/vless/encoding: failed to read packet length > websocket: close 1000 (normal)
2024/08/20 20:29:10 [Debug] [2894699288] transport/internet: dialing to udp:92.61.107.63:55072
2024/08/20 20:29:10 [Debug] [1770784502] transport/internet: dialing to udp:92.61.107.63:30019
2024/08/20 20:29:10 [Info] [1179826809] proxy/vless/inbound: firstLen = 79
2024/08/20 20:29:10 [Info] [1179826809] proxy/vless/inbound: received request for udp:1.1.1.1:53
2024/08/20 20:29:10 [Info] [1179826809] app/dispatcher: default route for udp:1.1.1.1:53
2024/08/20 20:29:10 [Info] [1179826809] transport/internet/tcp: dialing TCP to tcp:92.61.107.63:12324
2024/08/20 20:29:10 [Debug] [1179826809] transport/internet: dialing to tcp:92.61.107.63:12324
2024/08/20 20:29:10 [Info] [1934701621] proxy/vless/inbound: firstLen = 61

my x-ray configuration

{
"api": {
"services": [
"HandlerService",
"LoggerService",
"StatsService"
],
"tag": "api"
},
"inbounds": [
{
"listen": "127.0.0.1",
"port": 62789,
"protocol": "dokodemo-door",
"settings": {
"address": "127.0.0.1"
},
"tag": "api"
}
],
"log": {
"loglevel": "debug",
"access": "/home/ll.log",
"error": "/home/bb.log"
},
"outbounds": [
{
"tag": "tttag",
"protocol": "socks",
"settings": {
"servers": [
{
"address": "92.61.107.63",
"port": 12324,
"users": [
{
"user": "redacted or smthing",
"pass": "same"
}
]
}
]
}
},
{
"protocol": "freedom",
"settings": {
"domainStrategy": "UseIP"
},
"tag": "direct"
},
{
"protocol": "blackhole",
"settings": {},
"tag": "blocked"
}
],
"policy": {
"levels": {
"0": {
"statsUserDownlink": true,
"statsUserUplink": true
}
},
"system": {
"statsInboundDownlink": true,
"statsInboundUplink": true
}
},
"routing": {
"domainStrategy": "AsIs",
"rules": [
{
"type": "field",
"sourcePort": "443",
"inboundTag": [
"inbound-443"
],
"protocol": [
"tls"
],
"outboundTag": "tttag"
},
{
"inboundTag": [
"api"
],
"outboundTag": "api",
"type": "field"
},
{
"ip": [
"geoip:private"
],
"outboundTag": "blocked",
"type": "field"
},
{
"outboundTag": "blocked",
"protocol": [
"bittorrent"
],
"type": "field"
}
]
},
"stats": {},
"dns": {
"servers": [
"198.18.0.0/16",
"localhost"
],
"queryStrategy": "UseIP",
"tag": "dns_inbound"
},
"fakedns": [
{
"ipPool": "198.18.0.0/16",
"poolSize": 65535
},
{
"ipPool": "198.18.0.0/16",
"poolSize": 65535
}
]
}
any help or possible explanation would be greatly appreciated and please don't snap at me if I miscategorized the issue please accept my apologies in advance

**Comment by MK0ltra** [comment]
Did you use xray to run a socks5 proxy? If yes try adding `"udp": true` in [inbound configuration](https://xtls.github.io/config/inbounds/socks.html#inboundconfigurationobject).

**Comment by oops10101** [comment]
> Did you use xray to run a socks5 proxy? If yes try adding `"udp": true` in [inbound configuration](https://xtls.github.io/config/inbounds/socks.html#inboundconfigurationobject).

hey there appreciate the help but no I don't use x-ray to run the proxy I only want to use it as my outbound proxy is from a third party which I have no control over their server-side operation but it seems to have no problem with UDP in other client softwares that I'm using to connect to their proxy

**Comment by MK0ltra** [comment]
I see. There's no inbound in your configuration and based on logs i can say there's a vless websocket as an inbound right? Just wanna make sure what you trying to do. You want some part of traffic going through socks5 outbound or all of it?

**Comment by oops10101** [comment]
> I see. There's no inbound in your configuration and based on logs i can say there's a vless websocket as an inbound right? Just wanna make sure what you trying to do. You want some part of traffic going through socks5 outbound or all of it?

yeah I have made a rule for the inbound port 443s traffic (vless websocket) to go through socks5 proxy outbound and the result is udp packets specially DNS lookups not getting through and the resulting connection not being able to open any websites in chrome(DNS lookups are sent with udp) but working just fine using apps with no need for DNS lookups like telegram.
if it helps to understand the objective here the socks outbound part has nothing to do with my ability to get through irans gfw

**Comment by MK0ltra** [comment]
There's no need to that routing rule since first outbound is socks5, all outgoing traffic will go through your socks5.
I've removed the fakedns, change dns resolvers to 8.8.8.8, 1.1.1.1 and add `"domainStrategy": "UseIP"` to socks5 outbound. Please add your inbound and socks5 outbound details to following config and see if it's works:

```
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "log": {
    "loglevel": "debug",
    "access": "/home/ll.log",
    "error": "/home/bb.log"
  },
  "outbounds": [
    {
      "tag": "tttag",
      "protocol": "socks",
      "settings": {
        "domainStrategy": "UseIP",
        "servers": [
          {
            "address": "92.61.107.63",
            "port": 12324,
            "users": [
              {
                "user": "redacted or smthing",
                "pass": "same"
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {},
  "dns": {
    "servers": [
      "8.8.8.8",
      "1.1.1.1"
    ],
    "queryStrategy": "UseIP",
    "tag": "dns_inbound"
  }
}
```

**Comment by oops10101** [comment]
> There's no need to that routing rule since first outbound is socks5, all outgoing traffic will go through your socks5. I've removed the fakedns, change dns resolvers to 8.8.8.8, 1.1.1.1 and add `"domainStrategy": "UseIP"` to socks5 outbound. Please add your inbound and socks5 outbound details to following config and see if it's works:
> 
> ```
> {
>   "api": {
>     "services": [
>       "HandlerService",
>       "LoggerService",
>       "StatsService"
>     ],
>     "tag": "api"
>   },
>   "inbounds": [
>     {
>       "listen": "127.0.0.1",
>       "port": 62789,
>       "protocol": "dokodemo-door",
>       "settings": {
>         "address": "127.0.0.1"
>       },
>       "tag": "api"
>     }
>   ],
>   "log": {
>     "loglevel": "debug",
>     "access": "/home/ll.log",
>     "error": "/home/bb.log"
>   },
>   "outbounds": [
>     {
>       "tag": "tttag",
>       "protocol": "socks",
>       "settings": {
>         "domainStrategy": "UseIP",
>         "servers": [
>           {
>             "address": "92.61.107.63",
>             "port": 12324,
>             "users": [
>               {
>                 "user": "redacted or smthing",
>                 "pass": "same"
>               }
>             ]
>           }
>         ]
>       }
>     },
>     {
>       "protocol": "freedom",
>       "settings": {
>         "domainStrategy": "UseIP"
>       },
>       "tag": "direct"
>     },
>     {
>       "protocol": "blackhole",
>       "settings": {},
>       "tag": "blocked"
>     }
>   ],
>   "policy": {
>     "levels": {
>       "0": {
>         "statsUserDownlink": true,
>         "statsUserUplink": true
>       }
>     },
>     "system": {
>       "statsInboundDownlink": true,
>       "statsInboundUplink": true
>     }
>   },
>   "routing": {
>     "domainStrategy": "AsIs",
>     "rules": [
>       {
>         "inboundTag": [
>           "api"
>         ],
>         "outboundTag": "api",
>         "type": "field"
>       },
>       {
>         "ip": [
>           "geoip:private"
>         ],
>         "outboundTag": "blocked",
>         "type": "field"
>       },
>       {
>         "outboundTag": "blocked",
>         "protocol": [
>           "bittorrent"
>         ],
>         "type": "field"
>       }
>     ]
>   },
>   "stats": {},
>   "dns": {
>     "servers": [
>       "8.8.8.8",
>       "1.1.1.1"
>     ],
>     "queryStrategy": "UseIP",
>     "tag": "dns_inbound"
>   }
> }
> ```

Hey man thank you so much.
I still don't know what I was doing wrong in my routing that caused UDP packets to drop (I know I was making it unnecessarily complicated) idk maybe it was the "domainStrategy": "UseIP", I'll try to figure it out but anyway this fixed it right up. 
Absolute LEGEND.
thank you
