### ISSUE TITLE
Traffic calculation for users does not get updated

### ISSUE THREAD

**Issue by ariandcir** [alireza0/x-ui#142]
Neither in the panel nor via the telegram bot, you would be able to see the updated traffic usage for new users, would imagine it’s the same for old users.

this happened after upgrading to v0.5

**Comment by alireza0** [comment]
Hello @ariandcir 
Thank you for this report. It is only calculates the first traffic sent by xray-core.
It is fixed now. I will update the version 0.5.0 in an hour
