### ISSUE TITLE
Update x-ui and have ERROR exit status 23

### ISSUE THREAD

**Issue by Zombiehamser** [alireza0/x-ui#1421]
Hi. I update my x-ui installation and now I have  ERROR - X-UI: Failure in running xray-core: exit status 23:
![image](https://github.com/user-attachments/assets/779769c6-ee58-490f-9056-4fc013c7b3f2)

![image](https://github.com/user-attachments/assets/9a4f15ae-b249-4f53-a6b3-fb75c4808cb7)

![image](https://github.com/user-attachments/assets/b5270740-480b-4549-bd91-f2fbe907edb6)

![image](https://github.com/user-attachments/assets/b019e12d-a6ed-46dd-b9c5-df5c558e0a2e)

>  failed to load config files: [bin/config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: ext:iran.dat:ads > infra/conf: failed to load external sites: ads from iran.dat > infra/conf: failed to load file: iran.dat > infra/conf: failed to open file: iran.dat > open /usr/local/x-ui/bin/iran.dat: no such file or directory

I dont understand where I have problem, but I dont need Iran  data, because use it in Russia.

**Comment by sssagsag** [comment]
its xray core bug , update to 1.8.24

**Comment by alireza0** [comment]
Hi,
You can reset your xray config, or just delete related block rule ( block iran's advertisement )

**Comment by Zombiehamser** [comment]
> Hi, You can reset your xray config, or just delete related block rule ( block iran's advertisement )

Thank you, it was easy!
