### ISSUE TITLE
کراش شدن پنل

### ISSUE THREAD

**Issue by shayan775** [alireza0/x-ui#1422]
سلام علیرضا جان امیدوارم حالت خوب باشه. 

من یه مشکلی که خیلی وقته دارم و قبلا هم  [اینجا](https://github.com/alireza0/x-ui/issues/1364) گفتم اینه که همه ده پونزده تا پنلم یهویی هر ۵ دقیقه یکبار کراش میشه. به خاطر اورلود منابع سیستم هم نیست. من احتمال میدم به خاطر تعداد بالای درخواست هاییه که از طرف رباتم به پنل ارسال میشه. حالا داستان اصلی اینه که من الان فقط میخوام لوگ پنل رو ببینم تا پیگیر داستان بشم ببینم چرا این اتفاق میوفته چون واقعا آزار دهنده شده. متیونی کمک کنی چطور لوگ دیباگ پنل رو ببینم تا مشکل رو پیدا کنم؟

چیزی که قبلا امتحان کردم و جواب نداد:
```
export XUI_LOG_LEVEL=debug
export XUI_DEBUG=true
x-ui restart 
journalctl -f -xu x-ui

```
اما لوگ خاصی نمایش نمیده همون در حد INFO و Warning , اررو
اگه این مودر رو توی ایشوی دیگه ای توضیح دادی من معذرتخواهی میکنم چون ندیدمش، ممنون میشم ارجاعم بدی

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم
با دستور آخری که نوشتید اصولا باید همه لاگ ها برای شما نوشته بشه.
اگر به نکته خاصی برخوردید به اشتراک بذارید تا بتونیم بررسی کنیم
