### ISSUE TITLE
multi inbound for a single user ( one traffic usage to rule them all :) .

### ISSUE THREAD

**Issue by SomeBytee** [alireza0/x-ui#1425]
Is it possible to have multiple inbounds for a single user?
for example, imagine we have 3 inbounds ( with different ports -8080-8081-8082, and I assign client-number-1 to each of them with the same UUID,
but the problem is since the port is different on each inbound if the inbound-number-1 reach his limit, the other two inbounds still functional.

I used Fallback but the problem with that is I can't use different protocols like GRPC anymore.
the base template I want is going to be like this, if I use the subscription to import the configs
I want the FIRST CONFIG to show the days and traffic remaining, and then the other configs to be just right there without showing anything . so whenever the client connect to each inbound share the same traffic usage with another inbound.

long story short
I want a single user to be manageable with a single inbound, not in all inbounds with different usages.
let me know if I had to make a child inbound or something or have a routing rule for this, this will help a lot

Thanks in Advance!

**Comment by alireza0** [comment]
This panel is desined on a way that you cannot have one user with many inbounds.
Also some parts of your desired system could not be defined simply with xray-core or other types of protocols.
It might be possible with combination of nginx/haproxy with a controlling app beside the panel.

**Comment by SomeBytee** [comment]
i need to add something to the topic as well
in my tests :
1- all the data routed through the Netherlands , or the Main inbound which is for controlling inbound would not work anyway 
2- couldn't route traffics to Netherlands server but all configs were going through the Main inbound which is for controlling the traffics and expiration date 

the key is i want the inbound still can control the traffic and route the traffic based on what client is connecting with . like how i can separate it when it's going through one inbound for 2 different inbound?
