### ISSUE TITLE
 انبوه سازی توسط اعداد رندم

### ISSUE THREAD

**Issue by madar54** [alireza0/x-ui#1428]
بسیار متشکر از بزرگان پنل سنایی و علیرضا و دیگر بزرگان پیشنهاد دیگری داشتم که در پنل‌ها برای انبوه سازی چندین گزینه موجود است ولی یک گزینه که بیشتر کاربرد دارد به نظر من کاراکترهای رندم  ۵ رقمی یا ۶ رقمی  گزینه مناسبی است جهت ارسال کانفیگ به خصوص سابسکریشن برای فروشنده راحت‌تر است تا کاراکترهای حرفی رندم با سپاس از همه بزرگان این عرصه متشکرم
![add method](https://github.com/user-attachments/assets/5d87e6b7-85b4-4ce7-8ade-db0d212aa7a8)

**Comment by alireza0** [comment]
سپاسگزارم از پیشنهادتون
این مورد باعث باگ امنیتی میشه.
بیشتر برای کسانی که کار عمده میکنن پیشنهاد میکنم از api استفاده کنند
