### ISSUE TITLE
Show outbound traffic in outbounds table

### ISSUE THREAD

**Issue by pvolkov** [alireza0/x-ui#1429]
**Describe the solution you'd like**
Please add the display of information for outbound. Similar functionality is available in 3X-UI (https://github.com/MHSanaei/3x-ui/pull/1711). I tried to port it, but currently, I am facing an issue with the absence of a table in the database.

**Comment by alireza0** [comment]
I did not add it because outbound traffic is a read-only value here. We can not add featrures like limitation.
