### ISSUE TITLE
How do I assign a specific IP address to a subscription or client?

### ISSUE THREAD

**Issue by MyTestPerson** [alireza0/x-ui#1430]
My virtual server has several IP addresses. How do I assign a specific IP address to a subscription or client?

I don't know how to do this, if anyone knows, please tell me.

I assume this needs to be done in routing, but I can't figure out how to do it.

**Comment by lyohich812** [comment]
Hello. I have a simiral problem. 
Im trying to use additional IP address of my server. 
I created new inbound (ss) and set up my additional ipv4 address as "IP port" for it. 
Also tried setting in it as External Proxy settings.
Inbound is working I can access it but however, when Im checking my ip address it is showing up as my old ip address. 
Any ideas how it should work?
