### ISSUE TITLE
How to limit the number of simultaneous connections for one client?

### ISSUE THREAD

**Issue by skl256** [alireza0/x-ui#1432]
How to limit the number of simultaneous connections for one client?
For example, by IP address.
I have encountered such functionality in other panel implementations, but I did not find it in x-ui:1.8.6.

**Comment by abdollahim** [comment]
> It's not implemented in this panel. You might want to try 3x-ui

I didn't see that feature in 3x-ui
Are you sure about it?

**Comment by skl256** [comment]
> You might want to try 3x-ui

Yes, I saw this functionality in the 3x-ui panel, but this panel has one bug (not related to the functionality described above), which does not allow me to use it for my purposes

**Comment by skl256** [comment]
> I didn't see that feature in 3x-ui

@abdollahim in `ghcr.io/mhsanaei/3x-ui`
![image](https://github.com/user-attachments/assets/b6d1d25a-0f2d-468e-9e2b-fff79482835d)

**Comment by 5k1t2** [comment]
Will this be implemented in this panel?
Very useful feature

**Comment by web-elite** [comment]
> Will this be implemented in this panel?
> Very useful feature

Since IP addresses are not static in Iran, this is not practical and causes interruptions for the user.

**Comment by abdollahim** [comment]
> > Will this be implemented in this panel?
> > Very useful feature
> 
> Since IP addresses are not static in Iran, this is not practical and causes interruptions for the user.

We mean limit "simultaneous connections for one client at a time" not one static ip address to limit the user to connect only from that ip address!
For example set it to 1,2, or 3 to allow limit user connections at a same time.

**Comment by 5k1t2** [comment]
> > > Будет ли это реализовано в этой панели? 
> > > Очень полезная функция
> > 
> > 
> > Поскольку в Иране IP-адреса не являются статическими, это непрактично и вызывает перебои в работе пользователя.
> 
> Мы имеем в виду ограничение "одновременных подключений для одного клиента за раз", а не один статический IP-адрес, чтобы ограничить пользователя, чтобы он подключался только с этого IP-адреса! Например, установите его на 1,2 или 3, чтобы ограничить количество подключений пользователей одновременно.

Yes, thanks for the clarification.

**Comment by abdollahim** [comment]
> > I didn't see that feature in 3x-ui
> 
> @abdollahim in `ghcr.io/mhsanaei/3x-ui` ![image](https://private-user-images.githubusercontent.com/111241000/365433553-b6d1d25a-0f2d-468e-9e2b-fff79482835d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODg4NjMsIm5iZiI6MTcyNzU4ODU2MywicGF0aCI6Ii8xMTEyNDEwMDAvMzY1NDMzNTUzLWI2ZDFkMjVhLTBmMmQtNDY4ZS05ZTJiLWZmZjc5NDgyODM1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwNTQyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjU3N2Y5NzQxOThmZjYzNTE0ZGZmY2E1YWEzMThhNWE4NjY3OTY5NWE3YzRmMmYzMDRlYzU3MTI2Y2Q3YmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wWFq2NYaqFUCfKFPYFAGqQGfVcHhhnBl-lfjxuptABs)

Hello again,
This is what I see in the latest 3x-ui i just installed (version 2.4.2)
There isn't anything about IP limit.
![Screenshot 2024-09-29 090810](https://github.com/user-attachments/assets/3d78b927-70c6-414e-a869-57ac981e1854)

It might has been removed from 3x-ui !

**Comment by 5k1t2** [comment]
In any case, such a feature would be very useful to many users.
It would be great if it were implemented in the X-UI panel

**Comment by alireza0** [comment]
This panel removed the feature from the begining of forking repository.
There is no plan to implement this feature.
P.S. There is no complete solution for proxies like v2ray/xray models. Don't waste your time!

@abdollahim  This feature could be applied when you enable access logs in 3x-ui panel setting.
