### ISSUE TITLE
https otbound to squid?

### ISSUE THREAD

**Issue by alexpebody** [alireza0/x-ui#1433]
Hello

https otbound to squid? this is possible? thx! )

{
  "tag": "squid",
  "protocol": "https",
  "settings": {
    "servers": [
      {
        "address": "quid server ip",
        "port": 3129,
        "users": [],
        "tlsSettings": {
          "certificateFile": "/etc/ssl/certs/squid.crt",
          "keyFile": "/etc/ssl/certs/private/squid.key"
        }
      }
    ]
  }
}

**Comment by alireza0** [comment]
There isn't any protocol like https in xray-core's outbound
