### ISSUE TITLE
انتقال کلاینت ها از چند اینباند به یک اینباند 

### ISSUE THREAD

**Issue by mzc1993** [alireza0/x-ui#1434]
درود اقا علیرضای عزیز

امکان داره راهنمایی بفرمایید که که بنده بخوام کلاینت ها رو که از ۵ اینباند با پورت مختلف هست انتقال بدم به یک اینباند که پورت ۸۰ هست امکانش وجود داره یا نه؟ 

تشکر از شما

**Comment by alireza0** [comment]
درود بر شما
میتونید از ویژگی استخراج اینباند استفاده کنید و توی یه ادیتور همه رو با هم ترکیب کنید.
انتقال کاربر به سادگی امکانپذیز نیست.
