### ISSUE TITLE
استاپ شدن ایکسری روی شدوساکس

### ISSUE THREAD

**Issue by straymail** [alireza0/x-ui#1437]
سلام مهندس
رو شدوساکس بعد از چنتا کانفیگ ساختن پنل استاپ میشه و باید کانفیگ هارو پاک کرد تا راه بیفته

**Comment by alireza0** [comment]
درود بر شما
لطفا با اطلاعات کامل ایشو ایجاد کنید.
کسی با این داده های کم نمیتونه حدس بزنه مشکلتون کجاست
