### ISSUE TITLE
Telegram bot does not return a usage report to a user (non admin)

### ISSUE THREAD

**Issue by ariandcir** [alireza0/x-ui#144]
Hi there, 

The concept of having a separate field to put the telegram id of the user for his/her benefit in order to check his/her usage on TG is great though it does not work. As in even though the telegram id has been put on the connection, the bot apparently cannot identify the record on db to return.

**Comment by alireza0** [comment]
Hello @ariandcir
Did you use `telegram ID` or `Telegram username` ?
Please send me more info

**Comment by ariandcir** [comment]
Telegram username similar to how it was before.

**Comment by ariandcir** [comment]
If now we should supply the actual id then that’s fine. Just need to know that so I could update

**Comment by ariandcir** [comment]
Oh works for me now. Just tested without @ in the username

**Comment by ariandcir** [comment]
all good
