### ISSUE TITLE
نمایش ندادن حجم و ترافیک مصرف شده

### ISSUE THREAD

**Issue by RuMoradi** [alireza0/x-ui#1441]
سلام من هر نسخه ای زو نصب میکنم از پنل و بکاپ رو وارد میکنم اخرش حجم و ترافیک مصرف شده رو نمایش نمیده. این خطارو هم تو لاگ نشون میده؛
 WARNING - get xray traffic failed: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"

**Comment by alireza0** [comment]
درود بر شما
قانون api روچک کنید که اولین قانون مسیریابی باشه.
غیر از این نمیشه حدس زد شما چه تنظیمی کردید که این مشکل بوجود اومده.
