### ISSUE TITLE
چجوری پنلی که با  داکر نصب شده آدرس سرت رو بخونه

### ISSUE THREAD

**Issue by solidwar** [alireza0/x-ui#1445]
سلام. ابتدا یک سرور دارم که طریق bash نصب شده و سرتفیکت کلودفلر هم داره (از طریق فایل)
حالا با داکر یک پنل دیگه نصب کردم اما در هرجا که آدرس سرت میدم نمیتونه بخونه فایل های سرتفیکیت رو
ممنون میشم کمک کنید. 
![image](https://github.com/user-attachments/assets/34d115e7-66f4-4bee-8676-7da6ce6b6a37)

**Comment by mhsenpc** [comment]
> حالا با داکر یک پنل دیگه نصب کردم اما در هرجا که آدرس سرت میدم نمیتونه بخونه فایل های سرتفیکیت رو

Docker به صورت پیش‌فرض ایزوله شده است و هر کانتینر محیط مخصوص به خود را دارد. این ایزوله‌سازی یکی از مهم‌ترین ویژگی‌های Docker است که باعث می‌شود محیط‌های مختلف بدون تداخل با یکدیگر اجرا شوند. دلایلی که Docker نمی‌تواند به فایل‌های موجود در هاست (مثلاً مسیر `/root/3x-ui/private.key`) دسترسی داشته باشد به شرح زیر است:

### 1. **ایزوله‌سازی فایل‌سیستم (Filesystem Isolation)**
هر کانتینر یک فایل‌سیستم مستقل دارد که از فایل‌سیستم هاست جدا است. این ایزوله‌سازی کمک می‌کند که محیط داخلی کانتینر مستقل از سیستم عامل هاست و دیگر کانتینرها باشد. به همین دلیل کانتینرها نمی‌توانند به فایل‌های موجود در سیستم هاست بدون اجازه دسترسی داشته باشند.

### 2. **محدودیت‌های امنیتی**
Docker به دلایل امنیتی طراحی شده است تا کانتینرها فقط به فایل‌هایی که صراحتاً از طریق ابزارهای مثل `docker cp` یا `docker run` با استفاده از **volume mounts** مشخص شده‌اند دسترسی داشته باشند. این محدودیت کمک می‌کند که یک کانتینر نتواند به منابع و فایل‌های حساس سیستم هاست دسترسی پیدا کند و باعث آسیب یا نشت اطلاعات شود.

### 3. **لزوم استفاده از Volume Mounts برای دسترسی مشترک**
اگر نیاز دارید که کانتینر به فایل‌های موجود در هاست به صورت مستقیم دسترسی داشته باشد، باید از مکانیزمی به نام **Volumes** یا **Bind Mounts** استفاده کنید. این کار به شما اجازه می‌دهد یک دایرکتوری از هاست را با کانتینر به اشتراک بگذارید. اما به صورت پیش‌فرض، دسترسی مستقیم به فایل‌های هاست ممکن نیست مگر این که این مسیرها به صورت واضح mount شوند.

برای مثال، برای دسترسی به فایل‌های خاصی از هاست بدون نیاز به کپی، می‌توانید دایرکتوری یا فایل‌های خاصی را با استفاده از `-v` (برای volume mounts) به کانتینر متصل کنید:

```bash
docker run -v /root/3x-ui:/etc/ssl/private my_container
```

اینجا:
- `/root/3x-ui`: مسیر روی هاست.
- `/etc/ssl/private`: مسیر داخل کانتینر که به مسیر هاست mount می‌شود.

این روش به کانتینر اجازه می‌دهد که بدون کپی کردن فایل‌ها، به آن‌ها دسترسی داشته باشد.

**Comment by mhsenpc** [comment]
> ممنون میشم کمک کنید.

برای کپی کردن فایل‌های موجود در مسیر `/root/3x-ui/private.key` از سرور به یک Docker container، مراحل زیر را دنبال کنید:

### 1. بررسی دسترسی‌ها
ابتدا مطمئن شوید که دسترسی به فایل‌های مورد نظر را دارید و می‌توانید آن‌ها از دایرکتوری سرور بخوانید:

```bash
ls -l /root/3x-ui/private.key
```

اگر به مشکل دسترسی برخوردید، دسترسی‌های لازم را تنظیم کنید.

### 2. شناسایی نام یا ID کانتینر
لیست کانتینرهای در حال اجرا را ببینید و نام یا ID کانتینر مورد نظر را پیدا کنید:

```bash
docker ps
```

به عنوان مثال، فرض کنید نام کانتینر شما `my_container` است.

### 3. کپی کردن فایل‌ها از سرور به کانتینر
برای کپی کردن فایل‌های خصوصی به کانتینر Docker، از دستور `docker cp` استفاده می‌شود. این دستور به شما امکان می‌دهد فایل‌ها را از هاست (سرور) به داخل کانتینر کپی کنید.

#### مثال:
```bash
docker cp /root/3x-ui/private.key my_container:/path/in/container/
```

اینجا:
- `/root/3x-ui/private.key`: مسیر فایل در سرور.
- `my_container`: نام یا ID کانتینر شما.
- `/path/in/container/`: مسیری که فایل باید در داخل کانتینر کپی شود. مثلاً: `/etc/ssl/private/`.

### 4. بررسی کپی شدن فایل
بعد از کپی، برای اطمینان از اینکه فایل‌ها به درستی کپی شده‌اند، وارد کانتینر شوید:

```bash
docker exec -it my_container /bin/bash
```

سپس به مسیری که فایل‌ها کپی کرده‌اید بروید و وجود فایل را بررسی کنید:

```bash
ls -l /path/in/container/
```

این تمام مراحل برای کپی کردن فایل‌های خصوصی از سرور به داخل کانتینر Docker است.
