### ISSUE TITLE
panel doesnt load after a while

### ISSUE THREAD

**Issue by LoneStalkerz** [alireza0/x-ui#1449]
hi there, i have 8 VPS and im using your x-ui panel on all of them, but one of them stops working even i change the vps , everything looks fine, i can ssh to server , x-ui command works, but the panel doesnt load, i checked the log and i got these messages, please check and help 

i appreciate that  

best regards

![IMG_3909](https://github.com/user-attachments/assets/fb64ff8e-9d85-44f9-9381-cd330179ed73)

**Comment by alireza0** [comment]
Hello @LoneStalkerz,
This panel is not using telego package.

**Comment by LoneStalkerz** [comment]
Hi there, i cant use chat gpt while im using xui panel config , the app detects that im using vpn, i tried with vpn apps like hotspot shield and didnt have same problem, im using AMAZON AWS VPS , Germany location , is any changes needed on user config , panel or vps to solve this issue? Appreciate your help
