### ISSUE TITLE
Shared "Total flow" across a subscription

### ISSUE THREAD

**Issue by ariandcir** [alireza0/x-ui#145]
Hey buddy,

Not sure whether this is already possible somehow, but given the concept of subscription has been introduced and people are able to have access to retrieve multiple connections at once attached to a single sub, I think it would be an interesting feature to set a pool of "total flow" for example 30 gigs to be used across all the connections available to the sub, whether the end user wants to use only one of the connections or all of them I guess it could be up to them.

**Comment by alireza0** [comment]
Hello @ariandcir ,
Subscriton concept has some concepts which are not available in all client apps.
All possible abilities considering abilities and concepts of `x-ui` are now added.

Maybe new panel with modern implementation will do better!
