### ISSUE TITLE
ارور 404 روی برخی وب سایت ها

### ISSUE THREAD

**Issue by babakazizigithub** [alireza0/x-ui#1451]
درود و عرض ادب جناب علیرضا

یکی از مواردی که برام پیش اومده ارور 404 روی برخی سایت ها مثل account.ninjatrader.com هست 

جالب اینجاست که این مشکل فقط زمانی هست که با حالت Tun Mode ( هم v2rayهم nekoray  متصل میشیم و در حالت proxy کاملا اوکی هست و سابت باز میشه 
ممنون میشم اگه راه حلی داره راهنمایی بفرمایید

تصویر ضمیمه شد
![ninjatrader](https://github.com/user-attachments/assets/4b13cdd5-058f-4e23-b2d6-afa74cc8a290)

**Comment by alireza0** [comment]
مشکل مربوط به هسته و کلاینت میشه
