### ISSUE TITLE
بستن دسترسی به یک سایت

### ISSUE THREAD

**Issue by mrmasiha0** [alireza0/x-ui#1452]
سلام
من استفاده ام به صورت خانوادگی هست و به خاطر بچه های کوچکی که دارم میخوام دسترسی به یوتویوب رو در سرورم ببندم. از طریق قوانین مسیریابی domain رو گذاشتم youtube.com و outband tags رو هم گذاشتم روی blocked.
الان از طریق مرورگر سایت یوتویوب باز نمیشه ولی اپلیکشین این برنامه در گوشی بدون مشکل کار می کنه. ممنون میشم راهنمایی کنید.

**Comment by MK0ltra** [comment]
Add this domain: `youtubei.googleapis.com`

**Comment by mrmasiha0** [comment]
> Add this domain: `youtubei.googleapis.com`

ممنونم درست شد.
