### ISSUE TITLE
کانفیگ نادرست برای splithttp در حالت h3 h2 http/1.1

### ISSUE THREAD

**Issue by ahmad0489** [alireza0/x-ui#1453]
برای splithttp در xray دو نوع کانفیگ هست ، سمت سرور و یا کاربر (که می تونن متفاوت باشن) فقط h3 باشه یا h2, http/1.1 و اگه هر ۳ تا باشه به معنی h2 هست 

~~بهتره سمت سرور یعنی پنل ۳ حالت داشته باشه :~~
~~۱- حالت tcp یعنی h2 و http/1.1~~
~~۲- حالت udp یعنی فقط h3~~
~~۳- اگر apln شامل h3 و h2 و http/1.1 بشه روی سرور حالت tcp یعنی h2 و http/1.1 باشه ولی **برای کاربر ۲ نوع کانفیگ بده یکیش فقط h3 و یکیشم h2 و http/1.1**~~

با تشکر از آقای علیرضا

@alireza0

**Comment by ahmad0489** [comment]
> برای splithttp در xray دو نوع کانفیگ هست ، سمت سرور و یا کاربر (که می تونن متفاوت باشن) فقط h3 باشه یا h2, http/1.1 و اگه هر ۳ تا باشه به معنی h2 http/1.1 هست
> 
> بهتره سمت سرور یعنی پنل ۳ حالت داشته باشه : ۱- حالت tcp یعنی h2 و http/1.1 ۲- حالت udp یعنی فقط h3 ۳- اگر apln شامل h3 و h2 و http/1.1 بشه روی سرور حالت tcp یعنی h2 و http/1.1 باشه ولی **برای کاربر ۲ نوع کانفیگ بده یکیش فقط h3 و یکیشم h2 و http/1.1**
> 
> با تشکر از آقای علیرضا
> 
> @alireza0

این مشکل در پنل MHSanaei هم هست 
@MHSanaei

**Comment by ahmad0489** [comment]
> برای splithttp در xray دو نوع کانفیگ هست ، سمت سرور و یا کاربر (که می تونن متفاوت باشن) فقط h3 باشه یا h2, http/1.1 و اگه هر ۳ تا باشه به معنی h2 http/1.1 هست
> 
> ~بهتره سمت سرور یعنی پنل ۳ حالت داشته باشه :~ ~۱- حالت tcp یعنی h2 و http/1.1~ ~۲- حالت udp یعنی فقط h3~ ~۳- اگر apln شامل h3 و h2 و http/1.1 بشه روی سرور حالت tcp یعنی h2 و http/1.1 باشه ولی **برای کاربر ۲ نوع کانفیگ بده یکیش فقط h3 و یکیشم h2 و http/1.1**~
> 
> با تشکر از آقای علیرضا
> 
> @alireza0

سلام 
ساختار بهتر این هست که alpn رو ۲ تا کنید 
server_alpn
client_alpn
اینجوری میشه روی سرور h2 + http/1.1 ساخت ولی به کاربر h3 داد.

**Comment by alireza0** [comment]
درود بر شما
برای ساختار پیشنهادیتون هیچگونه منبعی ارائه نکردید.
به صورت پیشفرض همونطوری که توی [مستندات](https://xtls.github.io/config/transports/splithttp.html#xmuxobject) هست، و با توجه به [توضیح رفتار](https://xtls.github.io/config/transports/splithttp.html#http-%E7%89%88%E6%9C%AC) این پروتکل، تا زمانی که شما در سرور h3 رو فعال نکرده باشید، سرور روی udp شنودی انجام نمیده.

**Comment by ahmad0489** [comment]
> درود بر شما برای ساختار پیشنهادیتون هیچگونه منبعی ارائه نکردید. به صورت پیشفرض همونطوری که توی [مستندات](https://xtls.github.io/config/transports/splithttp.html#xmuxobject) هست، و با توجه به [توضیح رفتار](https://xtls.github.io/config/transports/splithttp.html#http-%E7%89%88%E6%9C%AC) این پروتکل، تا زمانی که شما در سرور h3 رو فعال نکرده باشید، سرور روی udp شنودی انجام نمیده.

با تشکر از این که پاسخ دادید ، چیزی که مهم هست و منظورم همون بود اینه که خیلیا دوست دارن سمت سرور http/1.1 و h2 باشه ولی به کاربر h3 بدن (با کلودفلر) ولی پنل در ساب عادی و json چیزی که قرار میده همون چیزی هست که تعریف شده 
مثلا اگر من در پنل h3 قرار بدم سمت سرور در حالت udp شنود انجام میده و به کاربر هم h3 میده ولی وقتی کلودفلر باشه کلودفلر از کاربر h3 میگیره و تبدیل می کنه به http/1.1 و وصل نمیشه 
بر اساس این مثال [مثال h3](https://github.com/XTLS/Xray-examples/tree/main/VLESS-TLS-SplitHTTP-H3)
Xray client <--- HTTP3 ---> CDN <--- HTTP2 or HTTP/1.1 ---> Xray server
این چیزی هست که من می خواهم بسازم و تنها راهش تفکیک alpn سرور از alpn هست که در ساب به کاربر داده میشه پس باید ۲ تا alpn باشه 
سرور که http/1.1, h2 و کاربر h3 
پس server apln و client alpn نیاز هست
@alireza0

**Comment by alireza0** [comment]
ما نمیتونیم برای عده ای که از یک مدل پیچیده استفاده میکنن، پنل رو بیش از حد شلوغ کنیم و از کارایی اش کم کنیم.
این مدل میتونه با خالی گذاشتن alpn انجام بشه. اینجوری اگر کلاینت ساپورت کنه، ارتباط h3 انجام میشه و کلادفلر با ارتباطی که سرور پشتیبانی میکنه باهاش صحبت میکنه.
به هرحال با فعال کردن h3 سمت سرور، مشکل خاصی در سرور هم بوجود نمیاد. یعنی برای سرور پشت کلادفلر مهم نیست که h3 نداشته باشه!
شاید درست متوجه نشدم که چرا حتما اصرار دارید که h3 خاموش باشه سمت سرور

**Comment by ahmad0489** [comment]
> ما نمیتونیم برای عده ای که از یک مدل پیچیده استفاده میکنن، پنل رو بیش از حد شلوغ کنیم و از کارایی اش کم کنیم. این مدل میتونه با خالی گذاشتن alpn انجام بشه. اینجوری اگر کلاینت ساپورت کنه، ارتباط h3 انجام میشه و کلادفلر با ارتباطی که سرور پشتیبانی میکنه باهاش صحبت میکنه. به هرحال با فعال کردن h3 سمت سرور، مشکل خاصی در سرور هم بوجود نمیاد. یعنی برای سرور پشت کلادفلر مهم نیست که h3 نداشته باشه! شاید درست متوجه نشدم که چرا حتما اصرار دارید که h3 خاموش باشه سمت سرور

بر اساس چیزی که [اینجا](https://github.com/XTLS/Xray-core/issues/3587) گفته شده 
手动指定内部请求版本仅在alpn数组只有一项的时候生效 不然遵循核心自带逻辑
ترجمه : تعیین دستی نسخه درخواست داخلی تنها زمانی اعمال می شود که آرایه alpn فقط یک آیتم داشته باشد، در غیر این صورت، از منطق خود هسته پیروی می کند.

یعنی وقتی یک آیتم داشته باشه همون اعمال میشه ولی اگر چند آیتم داشته باشه پیش فرض اعمال میشه یعنی عملا 
http/1.1, h2, h3 
معادل h2 در سمت کاربر و http/1.1 + h2 در سمت سرور هست
طبق چیزی که [اینجا](https://xtls.github.io/en/config/transports/splithttp.html#http-versions) گفته شده 
client:
If the value is not set, h2 (prior-knowledge) is assumed when TLS is enabled, and http/1.1 without TLS

server:
The server listens to HTTP/1.1 and h2 by default

یعنی به طور کلی اگر alpn فقط یک آیتم باشد همان اعمال می شود ولی اگر ۲ یا ۳ آیتم باشد سمت سرور http/1.1, h2 و سمت کاربر h2 اعمال میشود 

اگر بخواهیم سمت سرور http/1.1 و h2 باشه ولی کاربر h3 باشه باید alpn کاربر و سرور متفاوت باشه از طرفی در شرایط فعلی h3 با کلودفلر بازدهی خوبی داره کلودفلر هم h3 میگیره و تبدیل می کنه به http/1.1 و به سرور میفرسته
@alireza0

**Comment by ahmad0489** [comment]
خالی نمیشه گذاشت چون خالی هم معادل پیش فرضه 
مشکلی در اتصال کاربر نیست (یعنی میشه در پنل خالی گذاشت یعنی پیش فرض و کاربر می تونه خودش عوض کنه به h3) مشکل در ساب هست که پنل میده یعنی ساب عادی و json 
ننیشه ساب ساخت که پنل h2 و http/1.1 باشه ولی به کاربر h3 بده

**Comment by alireza0** [comment]
وقتی alpn رو چند مقدار تعیین میکنید، اولین گزینه اولویت میشه. نه اینکه همیشه h2 اول باشه.
کلمه پیشفرض رو برای جایی به کار میبرن که شما alpn  رو تعریف نکرده باشید.

در طول tls handshake پروتکل انتخاب میشه. وقتی شما با اولویت h3 و بعد h2 دارید، این اولویت مذاکره میشه و اگر h3 نشد، با h2 ادامه میدن.

انتخاب دستی در متنی که به شما جواب دادن، یعنی دوطرف مجبور به استفاده از h3 بشن. اگر نشد ارتباط برقرار نشه!

**Comment by ahmad0489** [comment]
> وقتی alpn رو چند مقدار تعیین میکنید، اولین گزینه اولویت میشه. نه اینکه همیشه h2 اول باشه. کلمه پیشفرض رو برای جایی به کار میبرن که شما alpn رو تعریف نکرده باشید.
> 
> در طول tls handshake پروتکل انتخاب میشه. وقتی شما با اولویت h3 و بعد h2 دارید، این اولویت مذاکره میشه و اگر h3 نشد، با h2 ادامه میدن.
> 
> انتخاب دستی در متنی که به شما جواب دادن، یعنی دوطرف مجبور به استفاده از h3 بشن. اگر نشد ارتباط برقرار نشه!

این درست نیست سمت سرور چند آیتم باشه معادل h2, http/1.1 هست (یعنی سرور h2 انتخاب می کنه مگر این که alpn دریافتی فقط شامل http/1.1 باشه مثلا ارتباط کلودفلر تا xray) و سمت کاربر چند آیتم باشه معادل h2 هست و اگر وصل نشد تغییر به آیتم دوم و ... نداره
یعنی اگه 
```
[ "h3", "h2" ]
or
[ "h2", "http/1.1" ]
or
[ "h3", "http/1.1" ]
or
[ "h3", "h2", "http/1.1" ]
```

باشه در سمت سرور معادل :
```
[ "h2", "http/1.1" ]
```
و سمت کاربر معادل :
```
[ "h2" ]
```
حتی من در [اینجا](https://github.com/XTLS/Xray-core/issues/3880) خواسته بودم وقتی کاربر `[ "h2", "http/1.1" ]` باشه هر چیزی که سرور انتخاب کرد همون وصل بشه و تبدیل نشه به `[ "h2" ]` ولی گفتن نمی تونن

we are running into limitations of the golang ecosystem (or rather, utls) where we are unable to read the server's NextProtocol response and have it be respected in golang's HTTP stack.

**خلاصه این که وقتی alpn تک آیتم نباشه سمت سرور h2, http/1.1 و سمت کاربر h2 میشه و هیچ گونه اولویت دهی و ... نیست مثلا کاربر `[ "h3", "h2" ]` باشه بازم با h2 وصل میشه و اولویت h3 نیست و اصلا اینجوری نیست که اول با h3 وصل بشه اگه نشد با h2 !**

در نهایت می خوام به عنوان مطلب اضافه به [این](https://github.com/XTLS/Xray-core/issues/3596) که hiddify-com در xray گزارش باگ داده بود و جواب RPRX که [این](https://github.com/XTLS/Xray-core/issues/3573#issuecomment-2241934194) و [این](https://github.com/XTLS/Xray-core/pull/3583#issuecomment-2246146466) بود هم اشاره کنم

تا می تونستم کامل توضیح دادم و مستندات خودمو ارائه کردم
@alireza0

**Comment by alireza0** [comment]
شما در تمامی این لینکهایی که ارسال کردید در مورد h2 و http/1.1 صحبت کردید که در تمامی موارد همه جواب ها درست بودند! اینکه h3 رو هم وارد اون جوابها میکنید اشتباهه.
باید به ذات اون تنظیماتتون دقت کنید. مثلا شما اگر انتقال ws داشته باشید، برای برقراری ارتباط همه تنظیمات alpn نادیده گرفته میشه و ارتباط فقط با http/1.1 برقرار میشه!

اگر غیر از قوانینی که گفتم اجرا بشه، باگ هسته است!
توی همه جوابها مقایسه ها منطقی و جواب سرور منطقی بوده. حتی اینکه با تنظیم fingerprint باید تنظیم alpn نادیده گرفته بشه، دلایل مخصوص خود پروتکل ها رو داره.
ولی در صورتی که alpn تنظیم بشه و چیزی (مثل fingerprint) اون رو تغییر نده، اولویت بررسی میشه (ولی تضمین نمیشه)!

**Comment by ahmad0489** [comment]
> شما در تمامی این لینکهایی که ارسال کردید در مورد h2 و http/1.1 صحبت کردید که در تمامی موارد همه جواب ها درست بودند! اینکه h3 رو هم وارد اون جوابها میکنید اشتباهه. باید به ذات اون تنظیماتتون دقت کنید. مثلا شما اگر انتقال ws داشته باشید، برای برقراری ارتباط همه تنظیمات alpn نادیده گرفته میشه و ارتباط فقط با http/1.1 برقرار میشه!
> 
> اگر غیر از قوانینی که گفتم اجرا بشه، باگ هسته است! توی همه جوابها مقایسه ها منطقی و جواب سرور منطقی بوده. حتی اینکه با تنظیم fingerprint باید تنظیم alpn نادیده گرفته بشه، دلایل مخصوص خود پروتکل ها رو داره. ولی در صورتی که alpn تنظیم بشه و چیزی (مثل fingerprint) اون رو تغییر نده، اولویت بررسی میشه (ولی تضمین نمیشه)!

مجبورم ساختاری کلی alpn رو بگم طبق [این](https://github.com/XTLS/Xray-core/pull/3583#issuecomment-2246146466) 

1. if it is websocket, the ALPN is always h1

2. if it is set via fingerprint, the ALPN is from the fingerprint

3. otherwise, it is taken from the alpn setting

یعنی اگر ارتباط ws باشد alpn فقط http/1.1 هست در غیر این صورت اگر fingerprint باشد توسط آن انتخاب می شود ولی اگر fingerprint نباشد توسط بخش alpn در json تنظیم می شود.

هر fingerprint هم لیست مشخصی از alpn ها داره که می تونم لینکشو بدم کدشو بررسی کنید ولی چیزی که مشخصه اینه که تقریبا همشون h2 و http/1.1 دارن.

طبق ساختار splithttp در اصل alpn نقش انتخاب پروتکل ارتباط داره حتی وقتی fingerprint باشه ولی alpn واقعی کاربر توسط fingerprint انتخاب میشه یعنی splithttp در اصل ۳ حالت برای اتصال دارد که توسط بخش alpn در json انتخاب می شود ولی این جدا از alpn درخواستی هست که کاربر میفرستد (میشه گفت splithttp به تنهایی ۳ پروتکل مختلفه و بخش alpn در json میگه که درخواست ها چه نوع به سرور ارسال بشه) برای این که این ۲ قاطی نشن از real alpn و protocol alpn استفاده می کنم
نوع درخواست کلاینت به سرور (چیزی که در json هست) = protocol alpn
اون alpn واقعی کلاینت که در tls درخواست کاربر هست = real alpn

برای ارتباط tcp چون real alpn توسط fingerprint انتخاب میشه و تقریبا تمام fingerprint ها شامل h2, http/1.1 هستند پس انتظار میرود که h2 انتخاب شود بخاطر همین پیش فرض protocol alpn برای splithttp هم h2 انتخاب کردن
 
حالت های کلی برای protocol alpn اینجوریه که وقتی تک آیتم باشه همون اعمال میشه ولی اگه خالی باشه یا چند آیتم باشه h2 اعمال میشه (اگر فقط h3 باشد ارتباط udp می شود که real alpn توسط fingerprint انتخاب می شود ولی اگر چند آیتم باشد که حتی یکی از آن ها h3 باشد در این حالت نوع ارتباط tcp (h2) انتخاب می شود)

معلومه که اگر fingerprint باشه real alpn توسط اون انتخاب میشه ولی اگر نباشه real alpn = protocol alpn یعنی چیزی که در json هست

در مورد alpn سرور هم اگه فقط یک آیتم تعریف بشه همونو انتخاب می کنه مثلا اگه h3 باشه پورت udp شنود می کنه و اگه هر چیزی غیر h3 باشه tcp شنود می کنه یعنی به طور کلی ساختار اینه که اگه یک آیتم باشه همونو انتخاب می کنه ولی اگه چند آیتم باشه یا خالی باشه پیش فرض h2, http/1.1 یعنی انتخاب اصلیش h2 هست ولی اگه درخواستی که به سرور میرسد فقط شامل http/1.1 باشد آن را رد نمی کند و http/1.1 انتخاب می کند 
اگر هم alpn سرور h3, h2, http/1.1 همزمان udp و tcp شنود نمی کند و فقط tcp شنود می کند چون معادل h2, http/1.1 هست

در نهایت انتخاب این که ارتباط udp باشد یا tcp توسط کاربر انجام می شود این که alpn کاربر فقط h3 باشد (udp) یا هر چیزی غیر آن باشد (tcp) ولی انتخاب این که ارتباط h2 باشد یا http/1.1 توسط کاربر نیست چون با fingerprint در اصل real alpn شامل h2, http/1.1 هست و این سرور یا cdn هست که انتخاب می کند کدام باشد ولی کاربر باید دقیقا همانی قرار دهد که انتظار میرود سرور یا cdn انتخاب کند مثلا اگر سرور یا cdn انتخاب کند http/1.1 باشد ولی کاربر h2 گذاشته باشد وصل نمی شود و برعکس اگر سرور یا cdn انتخاب کند h2 باشد ولی کاربر http/1.1 گذاشته باشد باز هم وصل نمی شود یعنی دقیقا [همین](https://github.com/XTLS/Xray-core/issues/3596) مشکل !

@alireza0

**Comment by ahmad0489** [comment]
دیگه بیشتر از این توضیح نمیدم چون معتقدم این کامل ترین توضیح alpn هست 
امیدوارم به این نتیجه که وقتی alpn این باشد
```
[ "h3", "h2", "http/1.1" ]
``` 
در سمت سرور فقط tcp شنود می شود و کاربر هم با h2 وصل می شود رسیده باشید و به لزوم تفکیک alpn کاربر و سرور هم پس برده باشید چون alpn کاربر نقش alpn ندارد و نقش این را دارد که http/1.1 وصل شود یا h2 و یا h3 و چند آیتم بودن هم مفهومی ندارد و معادل h2 می شود

**Comment by alireza0** [comment]
نمیدونم از چه دنیایی صحبت میکنید.
ولی اینجا و تمام جاهایی که معرفی کردین دنیای واقعیه. خبری از real/protocol نیست!
کدهای splithttp هم خیلی نرماله و طبق استانداردهای gotls کار میکنه.
این مستند اصلی splithttp رو مطالعه کنید:
https://xtls.github.io/en/config/transports/splithttp.html#http-versions

هیچ جایی من ندیدم که به دنیای متصور شما حتی اشاره ای شده باشه.
در مورد پراکسی های بین راه مثل cdn داستان به دو بخش تقسیم میشه و اونجا هم نمیتونه به تصورات شما نزدیک باشه.

مستند rfc7301 بخش alpn:
https://datatracker.ietf.org/doc/html/rfc7301#section-3

**Comment by ahmad0489** [comment]
> اگر بخشی از کد و یا مقاله ای خوندید که من نخوندم خوشحال میشم لینکش رو بفرستین تا مطالعه کنیم و کمی یاد بگیریم

من شخصی نیستم که حرف مفت بزنم و اگه واقعا دنبال مستند هستید مشکلی نداره

سرور :
 [اینو](https://github.com/XTLS/Xray-core/blob/main/transport/internet/splithttp/hub.go#L266) بررسی کنید به سطر 290 و 301 و 324 دقت کنید 

کلاینت : 
[اینو](https://github.com/XTLS/Xray-core/blob/main/transport/internet/splithttp/dialer.go#L81) بررسی کنید و به سطر 83 و 84 و 120 و 170 و 178 دقت کنید 
سطر 83 و 84 رو من خودم اینجا میارم 
``` go
	isH2 := tlsConfig != nil && !(len(tlsConfig.NextProtocol) == 1 && tlsConfig.NextProtocol[0] == "http/1.1")
	isH3 := tlsConfig != nil && (len(tlsConfig.NextProtocol) == 1 && tlsConfig.NextProtocol[0] == "h3")
```
دقیقا این چیزیه که من اسم گذاشتم براش و گفتم protocol alpn چون این چیزیه که در json قرار میگیره ولی وقتی fingerprint باشه alpn واقعی کاربر نیست اما در createHTTPClient تاثیر داره !

بعد از این واقعا دیگه من حرفی برای گفتن ندارم تشکر می کنم از این که رسیدگی کردید 
@alireza0

**Comment by ahmad0489** [comment]
> هیچ جایی من ندیدم که به دنیای متصور شما حتی اشاره ای شده باشه.

دلیل و مستند کافی پیدا کردم و آوردم ولی دقت نکردید و الان کد آوردم و امیدوارم این کافی باشه.

**Comment by alireza0** [comment]
من این کدها رو الان مطالعه کردم و مستندات ارائه شده اصلا منطبق با این کدها نیست!
اینکه isH2  و isH3 دوتا متغیر هستند که بر اساس اون نوع ارتباط به سه مدل تقسیم میشه کاملا منطقیه!

در سمت کلاینت اگر h3 تنها و یا h2 تنها باشه، توسط پکیج های مخصوص مدیریت میشه و در غیر اینصورت به پکیج استاندارد crypto.tls میره و بر اساس استاندارد مذاکره انجام میگیره. این بخش، مولتی alpn رو پشتیبانی میکنه.

در سمت سرور، عدم پشتیبانی از h3 و h2 همزمان دیده میشه که هیچ جا مستند نشده و فقط با بررسی کد میشه فهمید. این عدم پشتیبانی مربوط به هسته است و دور زدنش به پنل ربطی نداره. در صورت گزارش، در آینده ممکنه پشتیبانی بشه.
ولی چیزی که مشهوده اینه که برنامه نویس این پروتکل رو برای مولتی alpn ننوشته.

در نهایت، اگر شما [h3,h2,http/1.1] رو سمت سرور تنظیم کنید، و از واسطی مثل کلادفلر استفاده کنید، ارتباط h3 تا کلادفلر و از اونجا تا سرور با h2 میتونه برقرار میشه.
من متنهای قبلی شما رو با نتیجه جدید مقایسه کردم. بعضی ها رو الان متوجه شدم و خیلی از اونها رو مرتبط ندیدم. به نظر میرسه تجربه شما و دوستان هیدیفای توی تنظیم به یه ایرادات دیگه ای رسیده که از نظر هسته تست شما مشکل داشته و نه کدها.

به هر حال همونطوری که قبلا گفتم تنظیمات مجزا برای سمت کلاینت و سرور به دلایل مختلف قابل اجرا روی پنل نیست.

**Comment by ahmad0489** [comment]
> در نهایت، اگر شما [h3,h2,http/1.1] رو سمت سرور تنظیم کنید، و از واسطی مثل کلادفلر استفاده کنید، ارتباط h3 تا کلادفلر و از اونجا تا سرور با h2 میتونه برقرار میشه. من متنهای قبلی شما رو با نتیجه جدید مقایسه کردم. بعضی ها رو الان متوجه شدم و خیلی از اونها رو مرتبط ندیدم. به نظر میرسه تجربه شما و دوستان هیدیفای توی تنظیم به یه ایرادات دیگه ای رسیده که از نظر هسته تست شما مشکل داشته و نه کدها.

متاسفانه بازم دقت نکردید !
``` go
isH2 := tlsConfig != nil && !(len(tlsConfig.NextProtocol) == 1 && tlsConfig.NextProtocol[0] == "http/1.1")
```
در اینجا به این دقت کنید :
``` go
!(len(tlsConfig.NextProtocol) == 1 && tlsConfig.NextProtocol[0] == "http/1.1")
```
این یعنی اگه یک آیتم نبود یا یک آیتم بود ولی آیتم اول http/1.1 نبود پس isH2 توضیحات بیشتر : 
``` go 
(len(tlsConfig.NextProtocol) == 1 && tlsConfig.NextProtocol[0] == "http/1.1")
```
یعنی طول آرایه NextProtocol برابر با ۱ باشد و اولین عنصر آن "http/1.1" باشد ولی وقتی اولش ! بیاید یعنی برعکس همین یا نقیض همین که میشه `طول آرایه NextProtocol برابر با ۱ نباشد یا اگر برابر با ۱ است، اولین عنصر آن "http/1.1" نباشد.`
حالا چرا اینجا http/1.1 آورده ولی h3 نه ؟ چون بررسی با h3 شروع میشه یعنی درسته که اگه alpn فقط "h3" باشه هم isH3 میشه و هم isH2 ولی چون شرط اول if isH3 اجرا میشه پس else if isH2 اجرا نمیشه پس ارتباط h3 میشه
``` go
if isH3 {

// http3

} else if isH2 {

// http2

} else {

// http/1.1

}
```

**خلاصه این که سمت کلاینت [h3,h2,http/1.1] میشه isH2 پس با h2 وصل میشه نه h3**

@alireza0

**Comment by ahmad0489** [comment]
بر اساس همین کد بازم تاکید می کنم :
`اگر alpn یک آیتم باشد همان اعمال می شود ولی اگر چند باشد h2 اعمال می شود.`

**Comment by ahmad0489** [comment]
>ساختار بهتر این هست که alpn رو ۲ تا کنید
server_alpn
client_alpn
اینجوری میشه روی سرور h2 + http/1.1 ساخت ولی به کاربر h3 داد.

فکر کنم به این نتیجه رسیده باشید

**Comment by alireza0** [comment]
> البته یه روش دیگه هم هست که اول این issue گفتم اونم اینه که وقتی روی سرور alpn این باشد [h3,h2,http/1.1] برای کاربر کانفیگی دهد که فقط h3 هست یعنی [ "h3" ]

همونطوری که خودتون توضیح دادید، اگر روی سرور multi-alpn باشه روی tcp  گوش میده. پس وقتی کانفیگ کاربر بره روی h3 عملا متصل نمیشه.
سمت سرور رو دقت کنید:
```go
	l.isH3 = len(tlsConfig.NextProtos) == 1 && tlsConfig.NextProtos[0] == "h3"

	if port == net.Port(0) { // unix
                 ...
	} else if l.isH3 { // quic
		...
	} else { // tcp
		...
	}
```
پس طبق همون صحبتی که انجام شد، فقط با یک واسط مثل کلادفلر میتونید این کار رو انجام بدید.

لطفا عدم تطابق رو با خود هسته پیگیری کنید و دنبال تغییرات سمت پنل نباشید. اگر مشکلی نداشت انجام میدادم. ولی الان خیلی پارامتر های واجب تر هست مثل تغییر SNI که تا الان نتونستم اعمال کنم. نه اینکه نشه، بله اضافه کردنش سرباری داره که به ساختار پنل و سادگی کار صدمه میزنه.

**Comment by ahmad0489** [comment]
> 
> ```go
> 	l.isH3 = len(tlsConfig.NextProtos) == 1 && tlsConfig.NextProtos[0] == "h3"
> 
> 	if port == net.Port(0) { // unix
>                  ...
> 	} else if l.isH3 { // quic
> 		...
> 	} else { // tcp
> 		...
> 	}
> ```
> 

بله درسته سمت سرور همونجوریه که گفتید ولی سمت کاربر اینجوریه : 
``` go
isH2 := tlsConfig != nil && !(len(tlsConfig.NextProtocol) == 1 && tlsConfig.NextProtocol[0] == "http/1.1")

isH3 := tlsConfig != nil && (len(tlsConfig.NextProtocol) == 1 && tlsConfig.NextProtocol[0] == "h3")

if isH3 {

// http3

} else if isH2 {

// http2

} else {

// http/1.1

}
```

و تاکید من به isH2 بود که دقت کنید چون اون ! داره این یعنی هر alpn که فقط http/1.1 (یک آیتم و اونم http/1.1) نبود جزو isH2 هست خود h3 هم isH2 هست (در بخش کلاینت توضیح میدم)

**سمت سرور :**
```
[ "h2" ]
[ "h2", "http/1.1" ]
[ "h3", "h2" ]
[ "h3", "h2", "http/1.1" ]
```
طبق چیزی که شما خودتون هم گفتید l.isH3 نمیشن و ارتباط tcp میشه پس اینجوری شد 
`اگر alpn سمت سرور یک آیتم باشد همان اعمال می شود ولی اگر چند آیتم باشد tcp یا همان [ "h2", "http/1.1" ] اعمال می شود.`

**سمت کلاینت :**
```
[ "h2" ]
[ "h2", "http/1.1" ]
[ "h3", "h2" ]
[ "h3", "h2", "http/1.1" ] 
and also [ "h3" ]
```
طبق این دستور که بهش اشاره کرده بودم
isH2 := tlsConfig != nil && !(len(tlsConfig.NextProtocol) == 1 && tlsConfig.NextProtocol[0] == "http/1.1")
همه اون موارد isH2 میشن ولی فقط [ "h3" ] هست که isH3 هم میشه و پس فقط [ "h3" ] هست که ارتباطش h3 هست بقیه ارتباطش h2 میشه و اینجوری شد :
`اگر alpn سمت کاربر یک آیتم باشد همان اعمال می شود ولی اگر چند  آیتم باشد h2 اعمال می شود.`

@alireza0

**Comment by ahmad0489** [comment]
> لطفا عدم تطابق رو با خود هسته پیگیری کنید و دنبال تغییرات سمت پنل نباشید. اگر مشکلی نداشت انجام میدادم.

بله درسته با تغییر این در بخش کلاینت
``` go
isH3 := tlsConfig != nil && (len(tlsConfig.NextProtocol) == 1 && tlsConfig.NextProtocol[0] == "h3")
```

به این 

``` go
isH3 := tlsConfig != nil && tlsConfig.NextProtocol[0] == "h3"
```
درست میشه چون در این صورت هر alpn که اولین آیتم آن h3 باشد isH3 شناسایی میشه ولی حتی اگه من بگم فکر نکنم تغییرش بدن !
