### ISSUE TITLE
why `email` should be unique

### ISSUE THREAD

**Issue by caikun233** [alireza0/x-ui#1458]
Xray seems fully support using the same `email` in different `inbounds`, but why x-ui require me to fill in a **unique** email?
![图片](https://github.com/user-attachments/assets/f4ecdab0-5396-46e0-ab5e-f269fd1b4b41)

**Comment by alireza0** [comment]
Because xray does not using database.
It is about a design from the beginning of this project.
Changing the database is not migratable.
