### ISSUE TITLE
Noises

### ISSUE THREAD

**Issue by Wolf6470** [alireza0/x-ui#1461]
سلام و خدا قوت بابت تمامی زحماتی که میکشید.اگر امکانش هست درباره noises که در قسمت ساب جیسون اضافه شده یک توضیح بدهید.که برای چیست و چگونه کار میکنه؟ وقتی روشنش میکنم کانفیگ در v2rayNG کانکت نمیشه و خطا میده.

**Comment by alireza0** [comment]
درود بر شما
توضیحاتش توی مستندات xray-core هست.
بهتره تا زمانی که کلاینت بروز نشده و مطمئن نیستید که پشتیبانی میشه، اضافه اش نکنید.
