### ISSUE TITLE
باگ غیر فعال نشدن بعد از اتمام حجم

### ISSUE THREAD

**Issue by ghojaei1995** [alireza0/x-ui#1462]
سلام خسته نباشید مهندس من اخیرا در اپدیت جدید بعضی مواقع یه  مشکلی میخورم که فکر کنم باگ هست
یوزرهایی که  حجمشون زودتر از تاریخ انقضا که مشخص کردیم تموم میشه متاسفانه برخی بصورت خودکار  قطع نمیشه و وصل میمونه 
من چندین مرتبه این مورد را دیدم گفتم مطمئن بشم بعد بهتون بگم لطفا این مورد را بررسی کنید  
همین چند دقیقه پیش دوباره به اون مشکل خوردم
به کاربر ۲۰ گیگ حجم ۳۰ روزه زده بودم چندین روزه حجمش تموم شده بود و از تاریخ انقضا مونده بود ۳۰ گیگ مصرف کرده بود که متاسفانه بصورت خودکار قطع نشده بود مجبورم شدن دستم غیر فعال کنم 
چندین مرتبه این مشکل برایم بوجود اومده

این مشکل در پنل ثنایی بنده دارم چون در اونجا نمیشد  پیام گذاشت  و راه ارتباط دیکه با ایشون نداشتم اینجا گفتم لطفا بهشون اطلاع بدهید ممنون

**Comment by alireza0** [comment]
درود بر شما
در این مورد ایشو های زیادی ایجاد شده. لطفا قبل از ایجاد ایشو جدید، جستجو کنید.
در حال حاضر مشکل اصلی اینه که با قطع شدن کاربری که در هسته وجود نداره، هسته ریستارت میشه.
این چیزی که شما میبینید بعد از دیسیبل کردن خارج میشه، در واقع نقطه باگ پنل در حال حاضره.

اینکه کاربر بعد از اتمام حجم، درجا بیرون نمیافته کاملا طبیعیه. لطفا توضیحات من رو در ایشو های دیگه مطالعه کنید.
