### ISSUE TITLE
Split binaries and variable data (like db/configs) locations

### ISSUE THREAD

**Issue by andrico21** [alireza0/x-ui#1466]
**Is your feature request related to a problem? Please describe.**
No any functional issues, the only concern is security.
The best is to make x-ui-container's filesystem read-only (i.e. immutable) and mount container's /var/... to volume, but now application also uses /bin for storing its variable-data - so no way to make it immutable with standard container-related features.
Many peoples runs this amazing software on their VPS hosts with some other payload - no one wants to get his VPS host compromised due to container escape.
Sure it's possible to bind single config.json to writable file outside of container like it's done for logfiles, but there are some additional stuff app likes to write also - better to have separate dir.

**Describe the solution you'd like**
Create new config option like appdatapath and split binary location path with variable data's paths, changeable data should be placed in separate directory with noexec-option and so on. With different paths we can easily proceed with readonly root fs + volume for /var/x-ui/ like:
```bash
podman run --read-only -v x-ui-data:/var/x-ui/:nosuid,noexec --cap-drop=SYS_CHROOT,CHOWN,SETFCAP,SETPCAP,FOWNER,FSETID,SETGID,SETUID,DAC_OVERRIDE .....skipped....
```

**Additional context**
now all functions like GetConfigPath(), GetGeositePath(), GetGeoipPath(), GetBlockedIPsPath() rely on GetBinaryPath() and all the stuff placed in single directory
![image](https://github.com/user-attachments/assets/eeb2ab07-fa59-4e0a-9ce9-d4676f47f02a)

**More to improve***
is to sort what capabilities are actually need for application because by default it has "CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,NET_BIND_SERVICE,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT" and in fact it works without any problem only having KILL,NET_BIND_SERVICE (I guess KILL is needed for panel to manage xray process)
```bash
podman top x-ui hpid pid huser user capeff groups hgroups
HPID        PID         HUSER       USER        EFFECTIVE CAPS         GROUPS                                                        HGROUPS
140695      1           1051        root        KILL,NET_BIND_SERVICE  root,bin,daemon,sys,adm,disk,wheel,floppy,dialout,tape,video  1001,165536,165537,165538,165539,165541,165545,165546,165555,165561,165562
140701      5           1051        root        KILL,NET_BIND_SERVICE  root,bin,daemon,sys,adm,disk,wheel,floppy,dialout,tape,video  1001,165536,165537,165538,165539,165541,165545,165546,165555,165561,165562
140710      14          1051        root        KILL,NET_BIND_SERVICE  root,bin,daemon,sys,adm,disk,wheel,floppy,dialout,tape,video  1001,165536,165537,165538,165539,165541,165545,165546,165555,165561,165562
```

**Comment by alireza0** [comment]
Thank you for your suggestion.
But I guess this fact is not considered in your solution that files in bin folder are fully under the control of the panel and may change by panel itself. There is no read-only file.
Another point is that number of files which panel will use are less enough to store it as simple as possible in one folder.
