### ISSUE TITLE
xtls-segaro-vision (Suggestion)

### ISSUE THREAD

**Issue by Phoenix-999** [alireza0/x-ui#1468]
**FYI**
@alireza0 
@MHSanaei

جریان ( Flow ) به اسم xtls-segaro-vision که ویژگی هاش اینجا توضیح داده شده:
خلاصه بحث گذشته: https://github.com/XTLS/Xray-core/pull/3738

به فورکی از هسته xray اضافه شده + پنل و کلاینت
روی tcp-reality, h2-reality, grpc-reality قابل استفاده هست

هسته: https://github.com/LuckyLuke-a/Xray-core

پنل: https://github.com/LuckyLuke-a/3x-ui

کلاینت: https://github.com/LuckyLuke-a/v2rayNG

![xtls-segaro-vision-01](https://github.com/user-attachments/assets/97b4502c-ddef-4e17-ab7e-354b4fdde4ab)
![xtls-segaro-vision-02](https://github.com/user-attachments/assets/4434c3cb-dcb7-4f3d-a86e-5302c8755ab5)

**Comment by popularteam** [comment]
My VPS is blocked in Iran, will this method make it work again?@Phoenix-999

**Comment by popularteam** [comment]
@Phoenix-999 

Hello, thank you for your reply

We have our own product, I don't use Xray, I use a protocol that I buy from someone else. Has been used stably. Starting in 2024, many Iranian users reported to me that after the connection was successful, the device had no network. I looked at some logs, DNS resolution, and UDP data sending failed.

**Comment by popularteam** [comment]
So I need a more powerful protocol to evade the censorship of IranGFW. Because I am not a professional programmer, I don't have this ability.

I see that RPRX has been discussing a solution to this problem, so I'm wondering if there is a mature way to solve this problem now.

I'm willing to pay.

**Comment by popularteam** [comment]
OK
@Phoenix-999 
Telegram: https://t.me/Wirevpnsupport
