### ISSUE TITLE
ترجمه ربات تلگرام به فارسی

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#147]
اگه امکانش هست سورس ربات تلگرام پنل رو برای بنده بفرستین تا نسبت به ترجمه آن به فارسی اقدام کنید تا در آپدیت بعدی اعمال گردد

**Comment by alireza0** [comment]
این امکان به سلیقه شخصی کاربر بستگی داره. با این امکانات پاییه ای بهتره به صورت عمومی به زبان انگلیسی باشه.
امکانات API اضافه شده میتونه به برنامه نویس کمک کنه که سرویس خودش رو با مدل های مختلف روی بات خودش اجرا کنه.
