### ISSUE TITLE
Function of blocking Russian ip diaposons and domain zones does not work

### ISSUE THREAD

**Issue by theakopov** [alireza0/x-ui#1471]
Hello, thank you for your work!
My problem is that after standard panel installation and enabling blocking of IP range and Russian domain zone - it is still possible to access all Russian sources (e.g. ok.ru, vk.ru).
So, for example, if you block access to Chinese sources - then everything really works, unlike Russian sources

_Perhaps this issue will seem too abstract without any specifics, but I really don't know what else to point out. I installed on a clean OC, I installed different versions and didn't change anything in the configuration and the logs are fine._

**Comment by alireza0** [comment]
In our tests, it works fine. Please check your routing rules and packet flow.
Important point is: To use domain blocker, you have to enable Sniffing in your inbound configuration.
