### ISSUE TITLE
X-UI panel not worked after install

### ISSUE THREAD

**Issue by muffintime77** [alireza0/x-ui#1474]
**Describe the bug**
After installing the panel and specifying the connection data, the username password and port are not applied. Resetting will help, but the panel is also not available, browser error "File not found"

**To Reproduce**
1. git clone https://github.com/alireza0/x-ui/
2. cd ./x-ui/
3. ./install.sh
4.  set creads
5. x-ui --- 9
5. See error

**Expected behavior**
panel worked with inputed creads

**Screenshots**
![изображение](https://github.com/user-attachments/assets/2857e9e8-aa43-495c-b3a4-52099ce192bd)
![изображение](https://github.com/user-attachments/assets/ac66c623-4b45-46ec-bcda-c1b9e03fca49)

**Desktop (please complete the following information):**
 ~ OS: [Ubuntu server 22.04]
 - Browser [chrome, firefox]
 - Version X-UI [1.8.6]

**Smartphone (please complete the following information):**
 - not actual

**Additional context**
The problem is relevant only on 1 of my stands. appeared after installing and removing the 3x-ui panel. checked possible residual files, listening port via ss, systemd status. I suspect the problem is that:
1 listens ipv6
2 base path url panel is truncated

**Comment by alireza0** [comment]
We are going to release a new version and it may cause some errors in normal installation during update time.
Please reinstall the panel after upgrading to the new version.
