### ISSUE TITLE
پنل به هیچ عنوان کار نمیکند

### ISSUE THREAD

**Issue by Moh4mm4d1989** [alireza0/x-ui#1475]
سلام
بعد از نصب پنل به هیچ عنوان بالا نمیاد حتی ورژن های قبلی هم نصب میشن کار نمیکنند
ممنون

**Comment by alireza0** [comment]
درود بر شما
در حال بروز رسانی پنل هستیم، ممکنه مشکلات نصب داشته باشید که برای نسخه جدید آماده شده.

**Comment by Moh4mm4d1989** [comment]
در نسخه جدید بلاک کردن ای پی و دامنه کشورهای ایران روسیه چین وجود نداره!
تشکر از زحمات شما دوست عزیز
