### ISSUE TITLE
آپدیت پنل

### ISSUE THREAD

**Issue by eclipsssss** [alireza0/x-ui#1476]
سلام . ممنون از تمام زحمات شما آقا علیرضا
لطفا اگر ممکنه در پنل دکمه ای قرار بدید برای آپدیت پنل 
در حال حاضر صرفا از طرق سرور امکان پذیر هست
منظورم این آپدیت هست
x-ui ( command )
select => 2

**Comment by alireza0** [comment]
درود بر شما
قبلا این درخواست رو دوستان دادن ولی کار درستی نیست.
مشکلات امنیتی زیادی داره و به هردلیل مشکلی بوجود بیاد ممکنه قابل جبران نباشه.
