### ISSUE TITLE
مشکل در آپدیت 1.8.7

### ISSUE THREAD

**Issue by rasa68** [alireza0/x-ui#1477]
ممنون از امکانات خوبی که در آپدیت آخر به کمک مهندس ثنایی قرار دادید.
در آپدیت 1.8.7 در بخش Subscription Json و قسمت Direct Connection که امکان جدا فعال کردن ip و دامین ها را قرار دادید، اگر در قسمت Direct IPs گزینه ای انتخاب کرده باشیم ولی در قسمت Direct Domains گزینه ای فعال نکرده باشیم کانفیگ json کاربر دچار مشکل میشه و در کلاینت سمت کاربر کلا کانکت نمیشه. 
فکر کنم مشکل از قسمتیه که داخل عکس مشخص کردم.
![photo_2024-10-10_20-09-37](https://github.com/user-attachments/assets/b0f34d1e-7d70-4da8-9a3a-359ddd60c4f5)

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از گزارشتون.
برای حل این مشکل لطفا چک کنید آیا با تغییر مقدار enabled به false مشکل حل میشه؟
در این صورت میتونم به کد ها این پچ رو اضافه کنم.
```json
{
    "type": "field",
    "outboundTag": "direct",
    "domain": [],
    "enabled": false
}
```

تا حل مشکا در نسخه بعدی بهتره یک کشور در بخش دامنه ها داشته باشید.

**Comment by rasa68** [comment]
مقدار enabled رو هم به false تغییر دادم ولی بازم کانکت نمیشه.
فقط وقتی اون قسمتی رو که داخل عکس مشخص کردم به طور کامل حذف میکنم مشکل حل میشه.

**Comment by alireza0** [comment]
توی تست های ما هم همینطور بود.
روش رو عوض کردم. توی نسخه بعد اعمال میشه.
