### ISSUE TITLE
SpiderX and Dest + SNI

### ISSUE THREAD

**Issue by muffintime77** [alireza0/x-ui#1478]
Greetings! thank you for your work, and please tell me:
when redirecting to Google, Yahoo, etc. It opens 404 - is this normal?
when redirecting to microsoft and etc. The camouflage site does not open at all
under unknown circumstances, the browser displays the message "SSL_ERROR_NO_CYPHER_OVERLAP"

What is SpiderX used for? I feel like it doesn't change anything at all

what is SNI in the case of this panel? What does this setting affect? 

I would like to know how to select sites for masking (I think it is important to have this in the repository instructions)

I'm incredibly grateful, thank you again!

**Comment by alireza0** [comment]
Hello @muffintime77,

I don't understand what do you mean by redirecting!

AFAIK SpiderX is a path like url path which helps to normalize traffic content from GFW view.
SNI is the name of server which your traffic is hidden on behind. GFW will see the traffic to this SNI.
Masking is not related to reality and inbounds. It is only configurable via routing rules
