### ISSUE TITLE
درخواست بهبود وارپ 

### ISSUE THREAD

**Issue by hamid-vip** [alireza0/x-ui#1479]
درود و وقت بخیر
خسته نباشید
لطفاً در صورت امکان بخش مربوط به فعال‌سازی وارپ از طریق ساکس را مجدداً به پنل مدیریتی اسکریپت در ترمینال سرور اضافه کنید. این روش امکان استفاده از وارپ به‌صورت پایدارتر و بهینه‌تر از گزینه موجود در خود پنل را فراهم می‌کند. وارپی که در حال حاضر در پنل قرار دارد، پس از مدت کوتاهی قطع می‌شود، اما وقتی از طریق ساکس وارپ فعال می‌کردم، بسیار پایدار بود و هیچ قطعی نداشت و منابع کمتری از سرور مصرف می‌کرد.  این مورد در نسخه‌های جدید پنل علیرضا و ثنایی حذف شده

**Comment by alireza0** [comment]
درود بر شما
استفاده از اسکریپت خارجی هیچوقت در این پنل فعال نبوده و توصیه نمیشه.
استباط و استفاده شما به نظر درست نمیاد. مشکل قطعی کع اخیرا بوجود اومده مربوط به خود کلادفلر میشه و با اسکریپت هم مشکل وجود داره.

اگر شما با مدل اسکریپت راحت تر هستید، ویدیو ها و مطالب آموزشی زیادی وجود داره که میتونید اون رو جداگونه نصب و راه اندازی کنید.

**Comment by hamid-vip** [comment]
درود و وقت بخیر، خسته نباشید.

ممنون از توضیحاتتون. به نظر می‌رسه کمی سوءتفاهم پیش اومده. منظور من اسکریپت خارجی نبود. در نسخه‌های قبلی پنل شما، وقتی دستور x-ui رو در ترمینال سرور وارد می‌کردیم، گزینه‌ای به نام "وارپ" در میان آیتم‌های پنل وجود داشت که از طریق پروتکل ساکس فعال می‌شد. متأسفانه در آپدیت‌های اخیر این گزینه حذف شده، در حالی که قبلاً بخشی از سورس پنل بود.

من مدت زیادی از این روش استفاده می‌کردم و واقعاً خیلی پایدار بود؛ حتی با ترافیک‌های بالا، فشار کمی به سرور وارد می‌شد و قطعی‌ها هم به ندرت پیش می‌اومد. متأسفانه، وارپی که اکنون داخل پنل قرار گرفته، منابع سرور رو بیش از حد درگیر می‌کنه. وقتی ترافیک وارپ زیاد می‌شه، CPU و RAM به سرعت به ۱۰۰٪ می‌رسن، در حالی که با روش ساکس و همون میزان ترافیک، منابع سرور به مراتب کمتر مصرف می‌شد.

با تشکر از شما.

**Comment by alireza0** [comment]
این مدل فقط در پنل ثنایی انجام میشد و بعدا حذف شد. در این پنل اصلا وجود نداشت.
اگر این مورد مصرف شما رو بالا میبره باید تنظیماتش رو تغییر بدید.
مسیریابی ترافیک زیاد برای تانل وارپ در هر صورت ممکنه مشکل ایجاد کنه.
بهتره فقط ترافیک های خاص از اون مسیر منتقل بشه.
