### ISSUE TITLE
affer update 1.8.7, I can't open admin panal without webBasePath anymore ????🤦‍♂️

### ISSUE THREAD

**Issue by Elshepl** [alireza0/x-ui#1480]
LOG......
Oct 11 17:15:57 v2ray /usr/local/x-ui/x-ui[2779]: WARNING - XRAY: core: Xray 1.8.24 started
Oct 11 17:15:57 v2ray x-ui[2779]: Tgbot connected!
Oct 11 17:15:57 v2ray /usr/local/x-ui/x-ui[2779]: INFO - Starting Telegram receiver ...
Oct 11 17:20:25 v2ray /usr/local/x-ui/x-ui[2779]: INFO - Stop Telegram receiver ...
Oct 11 17:20:25 v2ray systemd[1]: Stopping x-ui Service...
Oct 11 17:20:25 v2ray systemd[1]: x-ui.service: Killing process 2791 (xray-linux-arm6) with signal SIGKILL.
Oct 11 17:20:25 v2ray systemd[1]: x-ui.service: Succeeded.
Oct 11 17:20:25 v2ray systemd[1]: Stopped x-ui Service.
-- Reboot --
Oct 11 17:20:53 v2ray systemd[1]: Started x-ui Service.
Oct 11 17:20:56 v2ray x-ui[885]: 2024/10/11 17:20:56 x-ui 1.8.6
Oct 11 17:20:56 v2ray /usr/local/x-ui/x-ui[885]: INFO - web server run http on [::]:1919
Oct 11 17:20:58 v2ray /usr/local/x-ui/x-ui[885]: INFO - XRAY: infra/conf/serial: Reading config: &{Name:bin/config.json Format:json}
Oct 11 17:20:58 v2ray /usr/local/x-ui/x-ui[885]: INFO - Tg notify enabled,run at @daily
Oct 11 17:21:02 v2ray /usr/local/x-ui/x-ui[885]: WARNING - XRAY: core: Xray 1.8.24 started
Oct 11 17:21:02 v2ray x-ui[885]: Tgbot connected!
Oct 11 17:21:02 v2ray /usr/local/x-ui/x-ui[885]: INFO - Starting Telegram receiver ...
Oct 11 17:27:53 v2ray systemd[1]: Stopping x-ui Service...
Oct 11 17:27:53 v2ray /usr/local/x-ui/x-ui[885]: INFO - Stop Telegram receiver ...
Oct 11 17:27:53 v2ray systemd[1]: x-ui.service: Succeeded.
Oct 11 17:27:53 v2ray systemd[1]: Stopped x-ui Service.
Oct 11 17:27:53 v2ray systemd[1]: Started x-ui Service.
Oct 11 17:27:53 v2ray x-ui[2712]: 2024/10/11 17:27:53 x-ui 1.8.6
Oct 11 17:27:53 v2ray /usr/local/x-ui/x-ui[2712]: INFO - web server run http on [::]:1919
Oct 11 17:27:53 v2ray /usr/local/x-ui/x-ui[2712]: INFO - Tg notify enabled,run at @daily
Oct 11 17:27:53 v2ray /usr/local/x-ui/x-ui[2712]: WARNING - XRAY: core: Xray 1.8.24 started
Oct 11 17:27:54 v2ray x-ui[2712]: Tgbot connected!
Oct 11 17:27:54 v2ray /usr/local/x-ui/x-ui[2712]: INFO - Starting Telegram receiver ...
Oct 11 17:28:00 v2ray systemd[1]: Stopping x-ui Service...
Oct 11 17:28:00 v2ray /usr/local/x-ui/x-ui[2712]: INFO - Stop Telegram receiver ...
Oct 11 17:28:00 v2ray systemd[1]: x-ui.service: Succeeded.
Oct 11 17:28:00 v2ray systemd[1]: Stopped x-ui Service.
Oct 11 17:28:00 v2ray systemd[1]: Started x-ui Service.
Oct 11 17:28:00 v2ray x-ui[2844]: 2024/10/11 17:28:00 x-ui 1.8.6
Oct 11 17:28:00 v2ray /usr/local/x-ui/x-ui[2844]: INFO - web server run http on [::]:1919
Oct 11 17:28:01 v2ray /usr/local/x-ui/x-ui[2844]: INFO - Tg notify enabled,run at @daily
Oct 11 17:28:01 v2ray /usr/local/x-ui/x-ui[2844]: INFO - XRAY: infra/conf/serial: Reading config: &{Name:bin/config.json Format:json}
Oct 11 17:28:01 v2ray /usr/local/x-ui/x-ui[2844]: WARNING - XRAY: core: Xray 1.8.24 started
Oct 11 17:28:01 v2ray x-ui[2844]: Tgbot connected!
Oct 11 17:28:01 v2ray /usr/local/x-ui/x-ui[2844]: INFO - Starting Telegram receiver ...
Oct 11 17:31:23 v2ray /usr/local/x-ui/x-ui[2844]: INFO - Stop Telegram receiver ...
Oct 11 17:31:23 v2ray systemd[1]: Stopping x-ui Service...
Oct 11 17:31:23 v2ray systemd[1]: x-ui.service: Succeeded.
Oct 11 17:31:23 v2ray systemd[1]: Stopped x-ui Service.
Oct 11 17:31:46 v2ray systemd[1]: Started x-ui Service.
Oct 11 17:31:46 v2ray x-ui[4047]: 2024/10/11 17:31:46 x-ui 1.8.7
Oct 11 17:31:46 v2ray /usr/local/x-ui/x-ui[4047]: INFO - web server run http on [::]:1919
Oct 11 17:31:46 v2ray /usr/local/x-ui/x-ui[4047]: INFO - Tg notify enabled,run at @daily
Oct 11 17:31:46 v2ray /usr/local/x-ui/x-ui[4047]: WARNING - XRAY: core: Xray 24.9.30 started
Oct 11 17:31:46 v2ray x-ui[4047]: Tgbot connected!
Oct 11 17:31:46 v2ray /usr/local/x-ui/x-ui[4047]: INFO - Starting Telegram receiver ...

**Comment by MHSanaei** [comment]
No you can't

**Comment by Elshepl** [comment]
> No you can't

Why bro, what is the solution?

**Comment by sharif221** [comment]
> > No you can't
> 
> Why bro, what is the solution?

There is a security risk, there is no admin panel in any other app that don't have webpath, this url is a not something that a random person be able to easily find it, Thay should not be able to even reach the login page.

This change help the community to have more secure panels, of course you can use older versions or even fork the latest version and revert this change
