### ISSUE TITLE
سوال در مورد sniffing

### ISSUE THREAD

**Issue by rezhacker** [alireza0/x-ui#1481]
سلام. یک سوال داشتم. علت اصلی اینکه در ورژن جدید هنگام ساختن اینباند، به صورت پیش فرض sniffing خاموش هست چیه؟ باگ داره، کند میکنه یا مشکل خاصی داره فعال بودنش؟

**Comment by alireza0** [comment]
درود بر شما
به دلیل مشکلات امنیتی ایجاد شده توسط کاربرانی که نمیدونن این بخش چیکار میکنه، غیر فعال شده.
کاربرانی که کاربردش رو میدونن میتونن در زمان تعریف اینباند، فعال کنند.
