### ISSUE TITLE
امکان تغییر پروتوکل 

### ISSUE THREAD

**Issue by Shellgate** [alireza0/x-ui#1482]
سلام و عرض ادب و خسته نباشید

چند مورد هست که میشه به پنل اضافه کرد

مورد اول پروتوکل freedoom  و ترنس میشن udp به قسمت ورودی ها که میشه به عنوان ورودی یا تانل چند پنل استفاده کرد

همچنین با قابلیت هایی مانند سابکریت میتوان پروتوکل های مختلف رو برای کاربران در صورت نیاز تغیر داد
میخواستم مانند گذشته این محدودیت  پروتوکل برداشته شود یا تجدید نظر هایی اعمال گردد 
به عنوان مثال سویچ کردن بین vless/vmess

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم

مورد اول رو اصلا متوجه نشدم. پروتکل freedom برای ورودی ها وجود نداره. udp transmission هم وجود نداره. میتونید از kcp به جاش استفاده کنید.
قابلیت مولتی اینباند از پایه توی پنل x-ui دیده نشده بود و اضافه کردنش باعث دردسر های زیادی میشه.
