### ISSUE TITLE
تغییر کرون جاب بکاپ تلگرام به زمان کمتر از یک ساعت

### ISSUE THREAD

**Issue by M3hr413** [alireza0/x-ui#1483]
درود علیرضا جان 
ربات تلگرام امکان تنظیم کرون جاب کمتر از یکساعت را نمیدهد
یعنی وقتی تنظیم میکنم کمتر از یکساعت ارسال نمیکند
ایا این مشکل از تنظیمات بنده بوده یا از پنل است؟

**Comment by hamid-vip** [comment]
درود و وقت بخیر،

برای اجرای یک کران در فواصل زمانی مشخص می‌توانید از فرمت زیر استفاده کنید:
`@every 8h`

به عنوان مثال، اگر می‌خواهید کران هر 30 دقیقه اجرا شود، از عبارت زیر استفاده کنید:
`@every 30m`
