### ISSUE TITLE
مشکل خروجی کد Qr در vmess

### ISSUE THREAD

**Issue by Shellgate** [alireza0/x-ui#1485]
سلام و عرض ادب 
در خروجی کدی توسط پنل تولید میشود ایراد دارد به این صورت که توسط نرم افزار هایی مانند fairvpn ارور میدهد
ولی توسط v2rayng خوانده و کار میکند سپس از خروجی v2rayng میتوان در fair و نرم افزار های مشابه استفاده کرد
احتمالا کدی تولیدی ناقص یا دارای ایرادی هست که برنامه هایی مانند fair انرا قبول نمیکنند و برنامه v2rayng انرا اصلاح می‌کند

**Comment by sharif221** [comment]
میتونید یک نمونه کد خروجی از پنل و کد خروجی از v2rayNG رو بفرستید که هردو مال یک لینک باشد.
در این صورت یکی با fair خونده میشه و یکی ارور میده.

**Comment by alireza0** [comment]
درود بر شما
نرم افزار fair سالهاست که به تاریخ پیوسته!
برای vmess این نرم افزار منتظر پارامتر alterId است که توی بروزرسانی های هسته حذف شده.
لطفا از نسخه های قدیمی استفاده کنید و یا به شکل دستی برای هر لینک تغییر بدین.
