### ISSUE TITLE
Traffic calculation bug, wrong Unit

### ISSUE THREAD

**Issue by sharif221** [alireza0/x-ui#1486]
_At first, I should note that I'm using the `MHSanaei/3x-ui 2.4.4` but I guess implementation of traffic calculation is the same._

## There are 2 problems:

- First the Unit GB TB MB is wrong it's actually GiB TiB MiB, so I think there is no explanation needed here.
For example in API we have `"down": 1084419029 ` its unit is Byte we know that. In panel, we have 1.1GB this is wrong it should be 1.1GiB (binary) because it's pretty clear that this value is 1.084GB (decimal) so it's somewhat miss leading for calculations.
It seems my example is not the best, but we can do conversion for 5.2TB for example, you see it's a TiB not TB as shown.

- Second: this is the actual problem, I'm using nekoray windows (v2ray-client) with the protocol of vless TCP HTTP, I have 2 numbers, one in the nekoray client one in x-ui panel:  (this is clean traffic reset speed test, also network between client and server is about 14ms ping without any meaningful packet loss)

> nekoray : `164.72 MiB upload `  `162.49 MiB download`
> x-ui panel: `164.74 MB upload `   `176.49 MB download`

By using the wrong Unit bug that we discussed in the First bug, we can assume MB in x-ui is MiB so we can compare values.

I want you (if it's possible) to clarify how traffic get calculated in x-ui so we can hunt this mismatch data down, until finding the root cause.

I'm using complex setup:
- client --> x-ui --> rathole reverse TLS tunnel --> x-ui 2

**Comment by sharif221** [comment]
## Files that participate in conversion:

- https://github.com/alireza0/x-ui/blob/3582876b823f9f0a088e759675f9461272d29eee/util/common/format.go#L7-L21
- https://github.com/alireza0/x-ui/blob/3582876b823f9f0a088e759675f9461272d29eee/web/assets/js/util/common.js#L1-L22

All conversions use 1024^n so it's clear that we should put KiB MiB GiB .....
I know it might be common sense to use GB instead of GiB but in large numbers it's a real difference

**Comment by alireza0** [comment]
First please be informed that these two questions are not Bugs!

The first conclusion is correct, but as I answer previous claims repeatly, it is a common mistake and we are not about a professional academic provider. It is based on what end user knows about traffic and abreviations.

For 2nd question: Panel gets the statistics from core. But obviously your miss-assumption is related to some facts:
1.  Tunnels are encapsulating the traffic and it will be calculated. Your extra tunnel is rathole reverse TLS tunnel
2. Between servers we have always a lot of controlling traffics.
3. Server traffic includes all other packets which may randomly come from internet and also your server needs to check some services via internet.
4. If you measure your packet loss from a ping, you are not calculating normal tcp process which may have some packet loss in internet.
5. Nekoray ( and all clients ) may calculate the traffic received by client and not sent traffic ( or not aware of receved traffic in server).

Overall, calculation is not a part of panel and it shows you only the facts.
