### ISSUE TITLE
WARNING - X-UI: add traffic failed:database is locked

### ISSUE THREAD

**Issue by NotSBad** [alireza0/x-ui#1488]
2024/10/16 19:04:36 WARNING - X-UI: add traffic failed:database is locked

Version: X-UI 1.8.7 - Xray 24.9.30

**Comment by alireza0** [comment]
Your resources is not good enough to handle amount of requests. Specially this error is related to HDD leackage.
But Don't worry, it is not a bad sign and you can continue working and ignoring this error.

My recommendation is to use proper resources ( not too much shared resources or using SSD or nvme ).
