### ISSUE TITLE
باگ در ورژن 0.5.0

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#149]
در ورژن جدید یک باگ خطرناک برخوردم  وقتی با تعداد روز کاربر ساختم برای تست مشاهده کردم که کاربر مصرفش محاسبه نمیشه  وقتی کار بر رو پاک کردم متافانه پنل به ارور خورد و خطای لود فایل config.jason رو داد و دیگه نه کاربر اضافه میشد نه پنل کار میکرد خوشبختانه از صبح بکاپ داشتم برگردوندن بعد دانگرید  این مورد رو تست کنید

**Comment by MA7** [comment]
من هم همین مشکل رو دارم و مصرف کاربر (اکانت های ساخته شده در یک پوررت زیر یک این باند) محاصبه نمیشه متاسفانه

**Comment by MA7** [comment]
در لاگ هم به این صورت مکرر داره لاگ میندازه :

Apr 05 13:23:01 FR-sev1 x-ui[764225]: 2023/04/05 13:23:01 WARNING - record not found bn4
Apr 05 13:23:01 FR-sev1 x-ui[764225]: 2023/04/05 13:23:01 WARNING - record not found bn3
Apr 05 13:23:01 FR-sev1 x-ui[764225]: 2023/04/05 13:23:01 WARNING - record not found t9luskjr9b

**Comment by aliamg1356** [comment]
> من هم همین مشکل رو دارم و مصرف کاربر وقتی میزنیم شروع بعد از n روز محاسبه بشه (اکانت های ساخته شده در یک پورت زیر یک این باند) محاسبه نمیشه متاسفانه

<html>
<body>


Apr 05 14:09:02 germany1 x-ui[4442]: 2023/04/05 14:09:02 WARNING - record not found irc-germany1-18
--
2 | Apr 05 14:09:02 germany1 x-ui[4442]: 2023/04/05 14:09:02 WARNING - record not found nazari1
3 | Apr 05 14:09:02 germany1 x-ui[4442]: 2023/04/05 14:09:02 WARNING - record not found Yaser
4 | Apr 05 14:09:02 germany1 x-ui[4442]: 2023/04/05 14:09:02 WARNING - record not found nazari2
5 | Apr 05 14:09:02 germany1 x-ui[4442]: 2023/04/05 14:09:02 WARNING - record not found mahmud
6 | Apr 05 14:09:02 germany1 x-ui[4442]: 2023/04/05 14:09:02 WARNING - record not found mina
7 | Apr 05 14:09:02 germany1 x-ui[4442]: 2023/04/05 14:09:02 WARNING - record not found nazari4
8 | Apr 05 14:09:02 germany1 x-ui[4442]: 2023/04/05 14:09:02 WARNING - record not found Nazanin
9 | Apr 05 14:09:02 germany1 x-ui[4442]: 2023/04/05 14:09:02 WARNING - AddClientTraffic update data UNIQUE constraint failed: client_traffics.email
10 | Apr 05 14:09:12 germany1 x-ui[4442]: 2023/04/05 14:09:12 WARNING - record not found Yaser
11 | Apr 05 14:09:12 germany1 x-ui[4442]: 2023/04/05 14:09:12 WARNING - record not found nazari4
12 | Apr 05 14:09:12 germany1 x-ui[4442]: 2023/04/05 14:09:12 WARNING - record not found shovalieh
13 | Apr 05 14:09:12 germany1 x-ui[4442]: 2023/04/05 14:09:12 WARNING - record not found mahmud
14 | Apr 05 14:09:12 germany1 x-ui[4442]: 2023/04/05 14:09:12 WARNING - record not found kazem
15 | Apr 05 14:09:12 germany1 x-ui[4442]: 2023/04/05 14:09:12 WARNING - record not found alimodem
16 | Apr 05 14:09:12 germany1 x-ui[4442]: 2023/04/05 14:09:12 WARNING - record not found irc-germany1-18
17 | Apr 05 14:09:12 germany1 x-ui[4442]: 2023/04/05 14:09:12 WARNING - record not found nazari1
18 | Apr 05 14:09:12 germany1 x-ui[4442]: 2023/04/05 14:09:12 WARNING - record not found nazari2
19 | Apr 05 14:09:12 germany1 x-ui[4442]: 2023/04/05 14:09:12 WARNING - record not found mina


</body>
</html>
این قسمتی از لاگ خطا بود

**Comment by alireza0** [comment]
لطفا مجددا آپدیت کنید و تست کنید.
این مشکل از ریلیز دیشب بوده، ولی چند ساعت پیش نسخه جدیدی رو جایگزین کردم که این مشکل توی حل شده

**Comment by aliamg1356** [comment]
> لطفا مجددا آپدیت کنید و تست کنید. این مشکل از ریلیز دیشب بوده، ولی چند ساعت پیش نسخه جدیدی رو جایگزین کردم که این مشکل توی حل شده

![Untitled](https://user-images.githubusercontent.com/124570423/230129326-954cd962-f835-4784-bcfe-6ffa9a45500d.jpg)
مشکل پابرجاست

**Comment by alireza0** [comment]
دم شما گرم. کلیت موضوع نرم افزارهای باز با همین روش پیشرفت میکنن.
من هم به همین علت بخش issue رو اضافه کردم.

اگر بتونید فایل config.json بخش مربوط به این vless که مشکل دار میشه ( اونی که fllback داره )رو برای من بفرستید عالی میشه.
به نظر میاد وقتی از پنل دیگه ای مهاجرت میشه به این مشکل میخوره.

**Comment by alireza0** [comment]
> این هم هست اگر کمکی میکنه : Apr 05 13:32:01 FR-sev1 x-ui[764225]: 2023/04/05 13:32:01 WARNING - AddClientTraffic update data UNIQUE constraint failed: client_traffics.email

@MA7 
من این مشکل رو امروز صبح دیدم و تصحیح کردم. لطفا مجددا بروزرسانی کنید و تست کنید

**Comment by MA7** [comment]
> > این هم هست اگر کمکی میکنه : Apr 05 13:32:01 FR-sev1 x-ui[764225]: 2023/04/05 13:32:01 WARNING - AddClientTraffic update data UNIQUE constraint failed: client_traffics.email
> 
> @MA7 من این مشکل رو امروز صبح دیدم و تصحیح کردم. لطفا مجددا بروزرسانی کنید و تست کنید

سپاس فراوان از شما

**Comment by aliamg1356** [comment]
> دم شما گرم. کلیت موضوع نرم افزارهای باز با همین روش پیشرفت میکنن. من هم به همین علت بخش issue رو اضافه کردم.
> 
> اگر بتونید فایل config.json بخش مربوط به این vless که مشکل دار میشه ( اونی که fllback داره )رو برای من بفرستید عالی میشه. به نظر میاد وقتی از پنل دیگه ای مهاجرت میشه به این مشکل میخوره.

دقیقا  این فایل رو چجوری بفرستم؟

**Comment by aliamg1356** [comment]
با سپاس فراوان  بله مشکل از فایل کانفیگ بود و متاسفانه هر چه ویرایش کردم رفع نشد مجبورا پاک و دوباره نصب کردم و یزرها رو مجدد ساختم  مشکل حل شد.فقط یه پیشنها دیگهدر ربات ئر ورژنهای قبلی قبل از اتمام زمان یا حجم کاربر اطلاع رسانی نمیکرد ولی این امکان مدتیست از پنل شما حذف شده.آیا امکان بازگرداندن آن هست؟

**Comment by alireza0** [comment]
@aliamg1356 
اگر بتونید ایمیل کنید عالی میشه. حتی اگر دیتابیس رو بفرستید دیگه بهتر میتونم تست بگیرم.
سعی من اینه که بتونم با بقیه پنل ها هم سازگار نگهش دارم.



> با سپاس فراوان بله مشکل از فایل کانفیگ بود و متاسفانه هر چه ویرایش کردم رفع نشد مجبورا پاک و دوباره نصب کردم و یوزرها رو مجدد ساختم مشکل حل شد.فقط یه پیشنها دیگه در ربات در ورژنهای قبلی قبل از اتمام زمان یا حجم کاربر اطلاع رسانی میکرد ولی این امکان مدتیست از پنل شما حذف شده.آیا امکان بازگرداندن آن هست؟

من چنین آپشنی یادم نمیاد. ولی الان هم میتونید گزارش رو زمان بندی کنید و توی اون گزارش کاربرهای در حال اتمام گزارش داده میشن
<img width="344" alt="image" src="https://user-images.githubusercontent.com/12573084/230359556-d57b45f1-0a33-4c06-868a-678d0283d60f.png">

**Comment by aliamg1356** [comment]
> @aliamg1356 اگر بتونید ایمیل کنید عالی میشه. حتی اگر دیتابیس رو بفرستید دیگه بهتر میتونم تست بگیرم. سعی من اینه که بتونم با بقیه پنل ها هم سازگار نگهش دارم.
> 
> > با سپاس فراوان بله مشکل از فایل کانفیگ بود و متاسفانه هر چه ویرایش کردم رفع نشد مجبورا پاک و دوباره نصب کردم و یوزرها رو مجدد ساختم مشکل حل شد.فقط یه پیشنها دیگه در ربات در ورژنهای قبلی قبل از اتمام زمان یا حجم کاربر اطلاع رسانی میکرد ولی این امکان مدتیست از پنل شما حذف شده.آیا امکان بازگرداندن آن هست؟
> 
> من چنین آپشنی یادم نمیاد. ولی الان هم میتونید گزارش رو زمان بندی کنید و توی اون گزارش کاربرهای در حال اتمام گزارش داده میشن <img alt="image" width="344" src="https://user-images.githubusercontent.com/12573084/230359556-d57b45f1-0a33-4c06-868a-678d0283d60f.png">
> 
> البته محل تنظیم عوض شده و به صفحه اصلی تنظیمات اومده. دیگه توی تلگرام تنها کاربرد نداره و توی پنل هم استفاده میشه

با درود مجدد متاسفانه با وجود نصب پاک دیشب و ساخت دوباره یوزرها و راه اندازی پنل ،متاسفانه امروز بعد ساخت یک یوزر باز پنل از کار افتاد و ایندفع با دانگرید هم کار نکرد و مجبور به دوباره ساختن یوزرها کردم  ربات هم اصلا بکاپی ارسال نکرده بود با وجود تنظیم ارسال بکاپ روی 8 ساعت.این باگ خیلی مشکلدار شد و باید روی یک سرور تست کار کنیم چون دیگه حوصله ساخت یوزرها رو ندارم.
ممنون

**Comment by aliamg1356** [comment]
> @aliamg1356 اگر بتونید ایمیل کنید عالی میشه. حتی اگر دیتابیس رو بفرستید دیگه بهتر میتونم تست بگیرم. سعی من اینه که بتونم با بقیه پنل ها هم سازگار نگهش دارم.
> 
> > با سپاس فراوان بله مشکل از فایل کانفیگ بود و متاسفانه هر چه ویرایش کردم رفع نشد مجبورا پاک و دوباره نصب کردم و یوزرها رو مجدد ساختم مشکل حل شد.فقط یه پیشنها دیگه در ربات در ورژنهای قبلی قبل از اتمام زمان یا حجم کاربر اطلاع رسانی میکرد ولی این امکان مدتیست از پنل شما حذف شده.آیا امکان بازگرداندن آن هست؟
> 
> من چنین آپشنی یادم نمیاد. ولی الان هم میتونید گزارش رو زمان بندی کنید و توی اون گزارش کاربرهای در حال اتمام گزارش داده میشن <img alt="image" width="344" src="https://user-images.githubusercontent.com/12573084/230359556-d57b45f1-0a33-4c06-868a-678d0283d60f.png">
> 
> البته محل تنظیم عوض شده و به صفحه اصلی تنظیمات اومده. دیگه توی تلگرام تنها کاربرد نداره و توی پنل هم استفاده میشه

آپدیت که میکنم اصلا این گزینه در ربات برای من کار نمیکنه در حالی که بر میگردونم به ورژن قبلی کار میکنه  پ
چند بار باز پنل رو نصب کردم ولی تا یه یوزر اد میکنم و حذف میکنم ارور میره پنل  حتی وقتی پنل رو خام نصب میکنم.
جالبتر اینکه در سرور خودم در خونه اوبونتو نصب کردم و روی اون اوکیه و alpn h3 رو هم نشون میده ولی رو وی پی اس نه  مشکل جالبی برام پیش اومده
![Untitled](https://user-images.githubusercontent.com/124570423/230388514-da7445e2-b047-416e-92b8-38cdea4cc225.jpg)

**Comment by alireza0** [comment]
متاسفانه با این اطلاعات نمیتونم مشکل رو پیدا کنم.
این ایشو رو میبندم و اگر مشکل رو پیدا کردید، مستندات رو توی یک ایشو دیگه بفرستید و یا همین ایشو رو مجددا باز کنید.

سپاسگزارم

**Comment by Erfan1384sh19** [comment]
من روی هر پورت که اینجوری باگ خورده بود یه کانفی
 اضافه میکنم و اونو خاموش میکنم اکی میشه گفت بگم شاید توی حل مشکل تاثیر 
گذارباشه
