### ISSUE TITLE
مشکل در ارتباط با API

### ISSUE THREAD

**Issue by sara990099** [alireza0/x-ui#1490]
تا نسخه 2.3.5 سنایی با API راحت می شد ارتباط گرفت اما تو نسخه های اخیر نمی تونم ارتباط بگیرم و حتی ربات هایی که برای این کار طراحی شده بودند از کار افتادند. مجبوریم از نسخه های قدیم پنل استفاده کنیم.

**Comment by sara990099** [comment]
امروز متوحه این موضوع شدم و دلیلشو نمی فهمم. طی آخرین تستی که گرفتم لاگین شدم اما با cookie  که دریافت شده نتونستم برای مثال لیست اینباند ها را دریافت کنم و 404 میگرفتم. علاوه بر اون این تغییرات باعث شده ربات هایی که از قبل نوشته شده بودند از کار بیافتند. راهی وجود داره این متغیر را مجدد تغییر نام بدیم به session؟

**Comment by sharif221** [comment]
در مرحله اول اگر رباتی از قبل دارید که سورسش در اختیارتون هست اونجا مقدار session رو با 3x-ui عوض کنید خیلی راحت تر و بهینه تر هست.
راه دوم اینه که یا از نسخه های قدیمی پنل استفاده کنید یا سورس پنل رو با تغییرات خودتون compile کنید.

من خودم به شخصه چون سورس ربات شخصی در اختیارم بود اونجا صرفا یک migration روی API پنل انجام دادم مشکل حل شد.
ولی برای اینکه بعضی API ها مقدار 404 بدن اون با قبل فکر میکنم فرقی نداشته  و من در اون مورد مشکلی نخوردم.
