### ISSUE TITLE
Warp routing for Spotify is not working well

### ISSUE THREAD

**Issue by mmrabbani** [alireza0/x-ui#1492]
سلام

وقتی که با استفاده از پنل spotify رو از خروجی warp عبور می‌دهیم، دامنه های geosite:spotify از خروجی warp عبور میکند. ولی اتصال هایی هم به تعدادی از IP ها با پورت 4070 برقرار میشه که این قانون چون با دامنه ای ارتباط نداره، اون رو پوشش نمیده. پس اگر اسپاتیفای سرور رو بلاک کرده باشه، با این Routing از بلاک خارج نمیشه.
منبع:
https://community.spotify.com/t5/Desktop-Windows/Spotify-Firewall-Settings-amp-IP-Address-Range/td-p/1090179
https://community.spotify.com/t5/Desktop-Mac/Port-4070-blocked-Why-Spotify-won-t-connect-to-port-80/td-p/994975

https://github.com/XTLS/Xray-core/issues/3289#issuecomment-2209404260

برای حل این مشکل باید پورت 4070 هم باید از warp عبور کنه. من با پنل خودم که اسپاتیفای اون رو بلاک کرده بود، این راه حل رو اجرا کردم و مشکل حل شد. گفتم اگه در پنل حل بشه مشکل همه کاربرها حل میشه
    "rules": [
      {
        "type": "field",
        "port": "4070",
        "outboundTag": "warp"
      },
    ]

این مشکل هم در این پنل وجود داره، هم در پنل 3x-ui وجود داره @MHSanaei

آپدیت: اگر فکر میکنید تغییر روتینگ یک پورت به وارپ خوب نیست، یک پیشنهاد دیگر هم دارم. منبع اول که در بالا قرار دادم، ۳ تا رنج آی پی برای اسپاتیفای معرفی کرده. من چک کردم تغییر روتینگ رنج ها هم مشکل اسپاتیفای رو حل میکنه. حتی چک کردم که مالکیت اون آی پی ها با اسپاتیفای باشه و عوض نشده باشه. ولی خب ممکنه رنجی اضافه شده باشه و ما ندونیم. با توجه به اینکه وارپ هم عملا آی پی سرور رو لو نمیده، هر راهی که فکر میکنید بهتر هست رو انجام بدهید. راه اول همه ترافیک اسپاتیفای رو از وارپ رد میکنه ولی شاید ترافیک سرویس دیگه ای رو هم رد بکنه (به شرطی که پورت ۴۰۷۰ باشه) راه دوم مطمئن هستیم که چیزی به جز اسپاتیفای رو از وارپ رد نکردیم. ولی خب احتمالا بعضی سرورهای اسپاتیفای رو ندیدیم و در نتیجه گاهی اپلیکیشن اسپاتیفای کار نکنه.
78.31.8.0/21
193.182.8.0/21
194.68.28.0/22
193.235.232.0/24

**Comment by alireza0** [comment]
درود بر شما
خواهش میکنم به این نکته دقت کنید که این مورد باگ پنل نیست.
اضافه کردن یک پورت به صورت کامل هم کار درستی نیست.
اگر geosite:spotify مشکل داره، لطفا به سازنده خودش گزارش کنید.
سپاسگزارم
