### ISSUE TITLE
نحوه ساخت اکانت وایرگارد از طریق API

### ISSUE THREAD

**Issue by rbsdotnet** [alireza0/x-ui#1494]
درود علیرضا جان وقت بخیر
من میخوام با API اکانت وایرگارد بسازم اطلاعات زیر ور چه جوری مثل پنل تولید کنم؟
secretKey
privateKey
publicKey

و اینکه شما برای تولید این سه کلید از چه کتابخانه ای استفاده کردید؟

ممنون میشم راهنمایی کنی سپاس ار لطفت

**Comment by alireza0** [comment]
درود بر شما
این مخزن متن بازه، میتونید از کدهای پنل پیداش کنید:
https://github.com/alireza0/x-ui/blob/main/web/assets/js/util/utils.js#L300
