### ISSUE TITLE
ثبت حجم به صورت مگابایت

### ISSUE THREAD

**Issue by rbsdotnet** [alireza0/x-ui#1496]
درود وقت بخیر

آیا امکان ثبت خحم به صورت مگ هست
مثلا 200 مگ
در ساختار به صورت 0.2 میزنم 0.19GB میزنه و حدودا روی 213 مگ توقف کرد
آیا امکانش هست روی عدد 200 مگ اکانت تموم بشه؟

**Comment by alireza0** [comment]
#771
