### ISSUE TITLE
مشکل عدم برقراری اتصال مجدد در صورت عدم پایداری و یا قطع لحظه ای اینترنت سرور ایران در اتصال ریورس

### ISSUE THREAD

**Issue by mmsh1370** [alireza0/x-ui#1497]
سلام وقتتون بخیر
خیلی ممنون بابت پنل خوبتون
من از اتصال ریورس پنل و ترکیبش با دکومودور خیلی استفاده میکنم
یه مشکلی دارم اینه که اگر سرور ایران ریستارت بشه یا با توجه به اختلالات اخیر اینترنتش قطع بشه
اتصال سرور خارج به ایران قطع میشه و حتما باید هسته ایکس ری سرور خارج رو ریستارت کرد
آیا امکانش هست امکانی فراهم کنید که این اتصال پیوسته چک بشه و در صورت لزوم سازوکار اتصال مجدد به صورت خودکار فراهم بشه
با تشکر

**Comment by sssagsag** [comment]
> سلام وقتتون بخیر خیلی ممنون بابت پنل خوبتون من از اتصال ریورس پنل و ترکیبش با دکومودور خیلی استفاده میکنم یه مشکلی دارم اینه که اگر سرور ایران ریستارت بشه یا با توجه به اختلالات اخیر اینترنتش قطع بشه اتصال سرور خارج به ایران قطع میشه و حتما باید هسته ایکس ری سرور خارج رو ریستارت کرد آیا امکانش هست امکانی فراهم کنید که این اتصال پیوسته چک بشه و در صورت لزوم سازوکار اتصال مجدد به صورت خودکار فراهم بشه با تشکر

This problem is due to the lack of health check in the xray core . Until it is added to the xray core ,  you can restart your server x-ui every hour via cronjob.


crontab -e

0 * * * * systemctl restart x-ui
