### ISSUE TITLE
self sign SSL if you use İP instead of domain

### ISSUE THREAD

**Issue by ysfnsrv** [alireza0/x-ui#1498]
Hello!
I use IP instead of domain name  http://192.168.77.100:54321/Q1Oyv9XVCQGa1pY
How can I add pem and key file path for secure https via terminal

In UI  add here Panel setting > General and  this field Public Key Path | Private Key Path

Public Key Path
The public key file path for the web panel. (Begins with ‘/‘)
Private Key Path
The private key file path for the web panel. (Begins with ‘/‘)

![image](https://github.com/user-attachments/assets/41af36c2-4503-46ac-8778-f8e8231a1c9c)

**Comment by sssagsag** [comment]
1-make crt and key self sign 
2-upload in your root directory 
3-set /root/crt.crt to public key path in panel settings
4-set /root/key.pem to private key path in panel settings

**Comment by ysfnsrv** [comment]
@sssagsag I know this ))
If you read, " **How can I add pem and key file path for secure https via terminal** " I want put crt on ubuntu via terminal (CLI) not GUI
