### ISSUE TITLE
مشکل فراخوانی API ها

### ISSUE THREAD

**Issue by miladkardgar** [alireza0/x-ui#1499]
در فراخوانی ای پی ها دچار مشکل هستم و صرفا وب سرویس login کار میکنه
سایر وب سرویس ها خطای 404 میده

دامنه پورت و path درست ست شده

و صرفا login در درست کار میکنه
![1](https://github.com/user-attachments/assets/36e33677-a743-4d74-8c24-642d9cd44bd9)
![2](https://github.com/user-attachments/assets/22fb0627-7b37-4402-9192-9c31d2151b51)

**Comment by MHSanaei** [comment]
getClientTrafficsById/{uuid}

**Comment by MHSanaei** [comment]
getClientTrafficsById/{uuid}
uuid 55? 
عع

**Comment by MHSanaei** [comment]
getClientTrafficsById/{uuid}
uuid 55?

**Comment by MHSanaei** [comment]
hamaro k 404 mide linket kolan eshtebahe on path ro dorost nazadi

**Comment by MHSanaei** [comment]
dar kon in moshkel az samte shomas bug nadarim dar in mored

**Comment by MHSanaei** [comment]
برادر شما اول باید پیام success بگیرید از لاگین بعد برید بقیه قسمت هارو تست کنید که کوکی وجود داشته باشه در داخل برنامه
چیزی که شما گذاشتید یوزر پسورد اشتباهه

**Comment by meysamamarlou** [comment]
> hamaro k 404 mide linket kolan eshtebahe on path ro dorost nazadi

منم امتحان کردم با آی دی کار نمیکنه فقط با ایمیل میاره
