### ISSUE TITLE
Constant database is locked error

### ISSUE THREAD

**Issue by ariandcir** [alireza0/x-ui#150]
Not sure what the cause is but after upgrading to the latest v0.5 (it was fine on v0.5 that was released yesterday) it started to be like this and prevent the admin from doing any changes after a couple of minutes have been passed from a x-ui reboot.
The only solution is to reboot x-ui and do changes quickly before it gets locked again.
WARNING - add traffic failed: database is locked
WARNING - something worng!Fail:  database is locked
WARNING - disable invalid Client err: database is locked
WARNING - add traffic failed: database is locked
WARNING - disable invalid inbounds err: database is locked
WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
WARNING - disable invalid Client err: database is locked
WARNING - add traffic failed: database is locked
WARNING - disable invalid inbounds err: database is locked

**Comment by alireza0** [comment]
Did you test new one ?
It was one of the first critical bugs in new version which I replaced 0.5.0 release with fixed one.
If not, please send me more information and if possible send me an email containing your example database.

Thanks

**Comment by alireza0** [comment]
No answer after a while.
I am gonig to close this issue. Please re-open it if you have new related results
