### ISSUE TITLE
Xray 24.10.31 cannot work in X-UI 1.8.7

### ISSUE THREAD

**Issue by jullyl8** [alireza0/x-ui#1501]
**Describe the bug**
Xray 24.10.31 cannot work in X-UI 1.8.7

**To Reproduce**
Updated from 24.10.16 to 24.10.31 in x-ui panel, X-ray status error, cannot resume after reboot. Have to use back 24.10.16.

**Screenshots**

![image](https://github.com/user-attachments/assets/024b90e2-3e71-4d44-a88f-097af69e2ee9)

**Comment by wulfric93** [comment]
Please provide logs

**Comment by jullyl8** [comment]
Please close this issue, it works fine when updating xray to the latest version 24.11.5, so looks like an issue for xray, not x-ui.
