### ISSUE TITLE
مولتی سرور با یک اینباند مادر

### ISSUE THREAD

**Issue by hamid-vip** [alireza0/x-ui#1505]
سلام و عرض ادب،
به‌طور معمول، می‌دانم که می‌توان از طریق تعریف یک قانون در پنل xui که در سرور ایران نصب شده ، تمام ترافیک را به یک اینباند خاص منتقل کرد که همان روش "تانل پنل به پنل" معروف است. اما سوال اصلی من این است که آیا می‌توان در پنلی که در سرور ایران نصب کرده‌ام، به‌طور مشخص تعریف کرد که هر درخواستی که به پورت 2020 می‌آید، به‌طور مستقیم به اوتباند A هدایت شود و هر درخواستی که به پورت 3030 می‌رسد، به اوتباند B منتقل شود؟

برای روشن‌تر شدن این موضوع، مثالی می‌زنم: فرض کنید در پنل ایران یک اینباند ساخته‌ام، و در بخش External Proxy دو بخش با پورت‌های 2020 و 3030 تعریف می کنم . به طوری که کاربر با اتصال به هر یک از این پورت‌ها، در واقع به سرورهای مختلف به‌صورت همزمان دسترسی پیدا کند، در حالی که تنها یک اینباند وجود دارد و حجم مصرفی کاربران به صورت یکپارچه محاسبه می‌شود.

آیا چنین تنظیمی ممکن است؟ من هر کاری کرده‌ام، موفق به انجام آن نشدم.

سپاسگزارم از توجه و راهنمایی شما.

**Comment by sssagsag** [comment]
yes you can redirect each inbound to each outbound .
using routing rules

![{E1C24E58-DF34-4EAA-B21C-4026194F2AFF}](https://github.com/user-attachments/assets/4ba69f02-6fcb-4c83-bd89-13e4e7575f12)
