### ISSUE TITLE
How can I share port 443 Xray|x-ui to work in docker with other services/sites?

### ISSUE THREAD

**Issue by rexen-pro** [alireza0/x-ui#1507]
I have launched x-ui in Docker with the recommended settings. And I got the error: "443 already in use". I have other web-services and sites running in other Docker-containers. I do the routing using Nginx-Proxy-Manager, which is also running in a container (I have no any proxy at host). And at the my domain name registrar, I manage the A-records of the subdomains of my domain. What are the options to avoid container conflicts - because port 443 is needed for Nginx? How do I use my own site (running in a nearby container) as a DEST?

**Comment by sssagsag** [comment]
Use nginx reverse proxy feature


location / {

        if ($http_upgrade != "websocket") {

            return 404;

        }

        location ~ / {

            if ($request_uri ~* "([^/]*$)" ) {

                set $port 8080;

            }

            proxy_redirect off;

            proxy_pass http://127.0.0.1:$port/;

            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;

            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        return 404;

    }
