### ISSUE TITLE
[Q] -- Please do not remove XTLS --

### ISSUE THREAD

**Issue by PalmTamino** [alireza0/x-ui#1508]
I am a heavy user of XTLS-RPRX-VISION, my server hasn't been blocked in 2 years now.

I saw in the latest version of 3x-ui, that it got removed. Please don't do the same, for me, and probably many others, xtls is an important feature.

Thank you.

**Comment by MHSanaei** [comment]
It was the security XTLS that was removed, not the XTLS-RPRX-VISION flow you mentioned

**Comment by PalmTamino** [comment]
> It was the security XTLS that was removed, not the XTLS-RPRX-VISION flow you mentioned
i think it confused me, normal tls does not work in your ui?

https://github.com/user-attachments/assets/4210a127-827d-42a2-b2e7-83eeb3801116

**Comment by MHSanaei** [comment]
Since you enabled TLS, you must set a path for the public and private keys.

**Comment by PalmTamino** [comment]
> Since you enabled TLS, you must set a path for the public and private keys.

Thank you a lot, that fixed it, i hope you can catch the error and not let xray crash, normally i wasn’t used to configure it, maybe it was done automatically before, on the terminal program
