### ISSUE TITLE
Setting up tls will result in an error / 设置 TLS 会导致错误

### ISSUE THREAD

**Issue by PalmTamino** [alireza0/x-ui#1509]
[Chinese/中文](https://paste.gg/p/anonymous/ac39736e39e6491ba60e316242c54231/files/39026b1cd97443708527b01f5537c035/raw)
**Describe the bug**
If i set up tls, it will result in the problem, that xray cannot even be started

**To Reproduce**
1) create new vless proxy
2) just select tls
3) save and check if xray is still up and running

**Expected behavior**
not running

**Video**

https://github.com/user-attachments/assets/38e3d656-dd86-484a-86e5-9da583460aaa

**Desktop (please complete the following information):**
 - OS: Everywhere, web
 - Browser Firefox, Safari
 - Version 

**Smartphone (please complete the following information):**
 - Version Firefox 132.0.1

**Additional context**
maybe i would need to select a certificate, but that it will be completely broken is unexpected, why does it even let me continue without, and where to get one?

**Comment by sssagsag** [comment]
You want to add TLS without public and private keys, which is not correct and contradicts the nature of TLS.
