### ISSUE TITLE
امکان گرفتن بکاپ از طریق پنل

### ISSUE THREAD

**Issue by ircfspace** [alireza0/x-ui#151]
سلام

ضمن تشکر از شما،

از [نحوه گرفتن بکاپ دیتابیس](https://telegra.ph/X-UI-Database-Backup-03-24) آگاهم؛ همینطور از اینکه ربات تلگرام این امکان رو میده.

اما آیا امکانش هست گزینه گرفتن بکاپ رو به پنل هم اضافه کنین؟

**Comment by alireza0** [comment]
درود بر شما
سپاس از پیشنهادتون.
بله این امکان رو ارزیابی کرده بودم. برای بروزرسانی بعدی اضافه میکنم.

**Comment by alireza0** [comment]
این قابلیت اضافه شد.
شما میتونید به صورت دستی کمپایل کنید و یا منتظر نسخه جدید باشید.
