### ISSUE TITLE
What’s “sniffing”

### ISSUE THREAD

**Issue by PalmTamino** [alireza0/x-ui#1510]
What exactly is sniffing, and where is the “sniffed” information at?
![IMG_1605](https://github.com/user-attachments/assets/dfca9d52-4468-47f9-84ef-a7bd67052acd)

my goal is not to sniff on traffic of others, just to monitor my own.

**Comment by sssagsag** [comment]
> What exactly is sniffing, and where is the “sniffed” information at? ![IMG_1605](https://private-user-images.githubusercontent.com/36358673/385449104-dfca9d52-4468-47f9-84ef-a7bd67052acd.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MTAyNzcsIm5iZiI6MTczMTYwOTk3NywicGF0aCI6Ii8zNjM1ODY3My8zODU0NDkxMDQtZGZjYTlkNTItNDQ2OC00N2Y5LTg0ZWYtYTdiZDY3MDUyYWNkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxODQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODBlZmM0NDEzMjJlNjk5NzJkYzEzNTg5MmExZDc3YjgyYmJkMzdhMTc4NGFmZDdkZjZiNzBhMjhlNmY0ZTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JrbIqR-kPWAnlE3r54Sow0C-TIDYWgJhTDiyTaGLSv8)
> 
> my goal is not to sniff on traffic of others, just to monitor my own.

The sniffing feature checks DNS or IP packets and if you have routing, it redirects them to the desired destination. For example, if you route Spotify to Warp in the routing, sniffing if enabled, checks user packets and forwards them to the Warp routing.
