### ISSUE TITLE
سوال درخصوص Subscription link

### ISSUE THREAD

**Issue by ircfspace** [alireza0/x-ui#152]
سلام و خسته نباشید

اول اینکه امکانش هست برای Subscription link یه لینک slug خودکار جنریت بشه؟ وارد کردن نام با در نظرگرفتن شرایط حدس زدن اسامی، باعث میشه لینک کانفیگ در دسترس افراد غیر قرار بگیره

دوم اینکه تقریبن کسی دیگه از لینکهای پنل به صورت عادی استفاده نمیکنه و بعد از ویرایش، توسط IPهای تمیز مورد استفاده قرار میگیره. یعنی Subscription link فعلی پنل کاربرد خاصی نداره حداقل روی اپراتورهای موبایلی. امکانش نیست کمی بشه کاستومایزش کرد یا محدودیتهای پنل این اجازه رو نمیده؟

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهیتون

برای اینکه لینک ساب رو نشه حدس زد میتونید فیلد ایمیل رو کپی کنید و یا از عبارات ساختگی استفاده کنید.

برای اضافه کردن IP تمیز و یا Domain به لینک میتونید از تنظیم Domain name استفاده کنید.
![image](https://user-images.githubusercontent.com/12573084/230361094-fa5aa5b7-9c36-4878-bb5b-69e37fc9be0d.png)

**Comment by Nipoto** [comment]
> 

ضمن تشکر، استفاده از عبارات ساختگی کمی کار رو سخت میکنه

نمیشه حداقل همون آدرس ایمیل به شکل base64 یا نحوه مناسب‌تری بعد از آدرس ساب قرار بگیره؟

**Comment by ircfspace** [comment]
تشکر از پاسختون

استفاده از عبارات ساختگی فکر نمیکنم چندان جالب باشه. 
امکان encode کردن hashId+email (یا حالت مشابه بهتر) جهت جنریت خودکار آدرس وجود نداره؟

**Comment by alireza0** [comment]
وجود داره، ولی هرکسی سلیقه خودش رو داره و نمیشه به همه تحمیل بشه.
این مشکل هم وجود داره که بعضی ها دوست دارند چند آدرس رو به یک subscription  اختصاص بدن.
بعضی ازکاربر ها هم نمیخوان که این آپشن رو داشته باشند.
در این صورت نمیشه یه راه حل پیش فرض بذاریم.

**Comment by ircfspace** [comment]
ضمن تشکر از پاسختون، به نظرم دارین سخت میگیرین. خصوصن در این‌رابطه که بعضی‌ها نمیخوان این‌آپشن رو داشته باشن؛ چون هرکی نخواد ازش استفاده نمیکنه. معتقدم توی این‌پنلتون کارای سخت‌تری رو به نحو احسن انجام دادین (مثلن همون حالات مختلفی‌که برای ساخت گروهی یوزر درنظر گرفتین) و این‌موارد سلیقه‌ای پیش اون پیش‌پاافتاده‌س

بهرحال تشکر

**Comment by alireza0** [comment]
این که «هرکسی نخواد استفاده نمیکنه» و گذاشتن پیشفرض برای این گزینه مغایرت دارن.
وقتی به صورت پیش فرض خالی میگذاریم، در واقع تا زمانی که تنظیم نشن قابل استفاده نیستند.
شاید درخواستتون رو درست متوجه نشدم

**Comment by ircfspace** [comment]
این‌طور که من دیدم هرکسی بخواد از این‌قابلیت استفاده کنه باید بره یه فیلدی رو تکمیل کنه تا Url براش تولید بشه. من صحبتم این‌بود که اینSlug به‌صورت دستی تولید نشه و با encode کردن hashId+email (یا حالت مشابه بهتر) صورت بگیره. موارد دیگری هم هستن که همیشه استفاده نمیشن، مثل QrCode یا ...، اما متناسب با نیاز داریم ازشون استفاده میکنیم.

آیا اینکه هر یوزری به صورت پیشفرض یه لینک ساب داشته باشه فشاری روی دیتابیس وارد میکنه؟
نکته ای هست که متوجهش نشده باشم؟

**Comment by Amirbazz** [comment]
سلام @alireza0 خسته نباشید
مرسی بابت قابلیتای جدید پنل
امکانش نیس در قسمت domain name چند ای پی گذاشته بشه و چند لینک برای کاربر جنریت شه
همونطور که میدونین هر اپراتور ای پی تمیز جداگانه داره
![IMG_20230410_102201.jpg](https://user-images.githubusercontent.com/120129395/230845247-50bed9cc-09da-482b-a84f-1dbf4a196e1f.jpg)

**Comment by alireza0** [comment]
@ircfspace 
نکته ای که عرض کردم همین بود که این مواردی که شما فرمودین، کاربردها و نیازهای شماست و نمیشه جمع بست برای همه استفاده کننده ها. در مورد qrcode هم همینطور.

@Amirbazz 
ارائه لینک ساب با ساده ترین روش ممکن اجرا شده و قرار نیست پیچیده باشه.
برای عملیات پیچیده بهتره از اسکریپت های خارج از این پنل استفاده بشه.

**Comment by Morghak963** [comment]
مهندس جان قابلیت پیچیده ای نیست 
صرفا اگر بشه یک‌ کادر باز بشه زیر قسمت subscription link و توی این قسمت بشه برای مثلا چندین آی پی تمیز کلاو وارد کرد و پنل از اون کانفیگ به تعداد آی پی ها لینک جنریت کنه بسیار قابلیت خوبی هست خصوصا برای کسانی که چندین لینک با آی پی آدرس های متفاوت برای روز مبادا میدن به یوزر
و این مسئله تضمین کننده اتصال کاربر به اینترنت آزاد میتونه باشه

**Comment by alireza0** [comment]
@Morghak963 
از این بخش استفاده های دیگه ای هم میشه. مخصوصا برای تولید لینک و qrcode.
این پنل اصلا جنبه تجاری نداره و کاربرد شخصی برای من مهمتره.
قابلیت subscription به صورت محدود ارائه شده و فعلا قرار نیست پیچیده تر بشه.
تنوع درخواست ها زیاده و هرکسی به درخواست خودش به عنوان بهترین روش نگاه میکنه. ترجیح میدم وقتم رو صرف گزینه های بهتر کنم.

متن شما رو متوجه نشدم متاسفانه.
نمیدونم منظورتون از پیچیده نبودن چیه. منظورتون اینه که ادمین پنل کارش راحت میشه ؟
منظورتون از «تضمین» رو هم متوجه نمیشم.
