### ISSUE TITLE
add in web button copy cert path for vless(vision) from  panel certificate

### ISSUE THREAD

**Issue by lk29** [alireza0/x-ui#155]
here
![FR-Inbounds-cert](https://user-images.githubusercontent.com/12291632/230231652-9756e14a-4cc8-4c67-a582-5f19b645f212.png)

take data from
Panel setting ->Panel Configuration
[Panel certificate public key file path]
[Panel certificate key file path]

**Comment by alireza0** [comment]
Nice idea!
I am thinking if it is better to initialize it with the data that exists in Panel settings.
If anyone needs, it could be replaced by new one.

Isn't it better ?

**Comment by lk29** [comment]
Good!

**Comment by dreamboxone** [comment]
very good idea. thanks

**Comment by alireza0** [comment]
Done!
Will be added to the next version
