### ISSUE TITLE
0.5.0.0 - alpn bug [ "" ] 

### ISSUE THREAD

**Issue by lk29** [alireza0/x-ui#156]
when creating!
if alpn is not enabled, "alpn" is added to the config: 
```
    "alpn": [
      ""
    ],
```
and xray no connection

if, after creation, open for editing and mark alpn and then uncheck sends the correct data
`    "alpn": [],
`

**Comment by alireza0** [comment]
Nice job. I have found it as well!
The problem is about initializing `vlessStream` in`xray.js`.
Due to javascript change, I should add it to a new release soon.

Just waiting for other bug reports.
Sincerely thanks for your nice findings :)

**Comment by lk29** [comment]
need return 
Inbound.VLESSSettings.Fallback = class extends XrayCommonClass {
    constructor(name="", **alpn='',** path='', dest='', xver=0) {

otherwise in fallback
alpn ... []
and this is not true.

you overdid it.

**Comment by alireza0** [comment]
It is correct base on [XTLS documentation](https://xtls.github.io/en/config/features/fallback.html#fallbacks-configuration)

**Comment by lk29** [comment]
yes! and you overdid in 91b453f
![изображение](https://user-images.githubusercontent.com/12291632/231015366-ebd673df-f05d-4605-8458-556d989751fb.png)
:)

![изображение](https://user-images.githubusercontent.com/12291632/231015571-2dde7430-4a53-4549-8f3e-4b5a1487c7a5.png)

**Comment by alireza0** [comment]
It is not an overriding these values. It is just about initializing if there is no value have been sent by Form.
But you are right. I have to rollback it for Fallback
