### ISSUE TITLE
alpn h3

### ISSUE THREAD

**Issue by dreamboxone** [alireza0/x-ui#157]
سلام ممنون از زحمات شما مهندس 
علی رغم اپدیت به اخرین نسخه اما من alpn h3 رو نمی بینم
میشه راهنمایی کنید؟
ضمنا من وقتی لینک اشتراک درست میکنم و میبرم داخل v2rayN کار نمی کنه. دلیلش چی میتونه باشه؟ (فقط از VMESS استفاده میکنم)

ممنونم

**Comment by alireza0** [comment]
درود بر شما
سوالاتتون واضح نیست.
۱. کجا alpn h3  رو نمیبینید ؟
۲. لینک اشتراک رو میتونید با مرورگر تست کنید.
اگر مشکلی هست برای من تنظیمات و شرایط رو بفرستید

**Comment by AmoAlireza** [comment]
سلام
علیرضا جان این مشکل برای افرادی هستش که پنل از قبل داشتن و آپدیت کردن الان و گزینه alpn h3 براشون نیست.
![1](https://user-images.githubusercontent.com/79990596/230771809-d23d9a9c-233a-4525-bfce-9866c1291009.PNG)

**Comment by lk29** [comment]
need flush cache you browser, or useprivate

**Comment by alireza0** [comment]
@AmoAlireza 
همه چیز بستگی به نوع تنظمیات پنل و nginx داره.
البته مشکل basepath توی نسخه آخر وجود داره که برای نسخه جدید حلش کردم.
ولی با nginx میشه راحت درستش کرد
