### ISSUE TITLE
How to use Rest Api

### ISSUE THREAD

**Issue by MA7** [alireza0/x-ui#158]
there is any document ar sample for  use api ?
fo example 
i need to know json body sample of xui/API/inbounds/addClient/ POST request

**Comment by AliM1988** [comment]
maybe useful. see https://github.com/HexaSoftwareTech/x-ui/pull/51

**Comment by mostafa9112** [comment]
این مال ورژن های قدیمیه
علیرضا جان دمت گرم واسه اپدیت فقط اگه داکیومنت کامل api رو بدی ممنونت میشم مثلا چه مقادیری میخواد

**Comment by alireza0** [comment]
Hello @MA7 ,
You can find it when you want to add a client in web panel with developer mode of your browser.
As you can see [here](https://github.com/alireza0/x-ui/blob/main/web/html/xui/inbounds.html#L574-L580), you need to send the `inbound.id` and a string contains all old client settings plus all new clients' settings.
Example:
old settings of inbound with id=1:
```
{
  "clients": [
    {
      "id": "aebe8315-6f71-43c1-b52d-b86c030ae814",
      "alterId": 0,
      "email": "3iyts8w",
      "totalGB": 0,
      "expiryTime": 0,
      "enable": true,
      "tgId": "",
      "subId": ""
    }
  ],
  "disableInsecureEncryption": false
}
```
Then you can send the new client(s) with this information:
```
id: 1,
settings: {
  "clients": [
    {
      "id": "aebe8315-6f71-43c1-b52d-b86c030ae814",
      "alterId": 0,
      "email": "3iyts8w",
      "totalGB": 0,
      "expiryTime": 0,
      "enable": true,
      "tgId": "",
      "subId": ""
    },
    {
      "id": "a90ae89e-6709-4c34-ab9f-f879b379712c",
      "alterId": 0,
      "email": "siocbk1b04",
      "totalGB": 0,
      "expiryTime": 0,
      "enable": true,
      "tgId": "",
      "subId": ""
    }
  ],
  "disableInsecureEncryption": false
}
```

**Comment by alireza0** [comment]
@mozilla-firefox 
برای فعال بودن کاربر.
برای شروع شدن با اولین اتصال، کافیه یک عدد مفنی به expiryTime بدین. این عدد معادل میلی ثانیه زمانی میشه که میخواید در اولین اتصال به زمان اضافه بشه.
