### ISSUE TITLE
عدم نمایش حجم مصرف شده کلاینت

### ISSUE THREAD

**Issue by iamfarhad** [alireza0/x-ui#160]
سلام و وقت بخیر

حجم وصرف شده کلاینت نشاد داده نمیشود. نمیدونم مشکل نمایش هست یا محاسبه؟ ورژن 0.5.0

**Comment by iamfarhad** [comment]
همچنین ترافیک یوزیج هم داخل بات برای کلاینت عدد غیرمرتبط میاره

**Comment by IranianCypherpunks** [comment]
من هم از بعد از آپدیت ورژن ۵ همین مشکل رو دارم یوزیج کاربرها محاسبه نمیشه !!

**Comment by IranianCypherpunks** [comment]
روی ۴ سرور متفاوت ورژن ۰.۵.۰ رو نصب کردم و در دوتا خوب کار میکنه و در ۲ تای دیگه بعضی وقتا یوزیج کاربرهارو محاسبه نمیکنه و بعضی مواقع با ریست کردن هسته مشکل حل میشه و بعضی مواقع به هیچ عنوان حل نمیشه، یکی از سرورها که تازه نصب کردم h3 فعال شده ولی بقیه رو آپدیت کردم و h3 فعال نیست ! در کل رفتار عجیبی داره فعلا، ممنون از زحماتتون

**Comment by alireza0** [comment]
این تاپیک تکراری است.
لطفا بروزرسانی کنید، مشکل حل شده
