### ISSUE TITLE
0.5.0 bug - "decryption":"none"

### ISSUE THREAD

**Issue by MA7** [alireza0/x-ui#161]
سلام 
پس از آپدیت به نسخه 0.5 سه بار تا حالا این خطا به وجود اومده به صورت خودکار و یهویی بدون تغییر خاصی.
Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 linux/amd64)

A unified platform for anti-censorship.

2023/04/07 09:51:43 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: VLESS settings: please add/set "decryption":"none" to every settings

توی دیتابیس  جدول inbounds  فیلد settings مقدار decryption یکی از inbound ها به این مقدار تغییر کرده خودکار که موجب خطا شده : 
  "decryption": null,
  
  و با تغییرش به 
    "decryption": "none",

حل میشه

چه کنیم این خطا مجد به وجود نیاد ؟

**Comment by alireza0** [comment]
درود بر شما
این مشکل بیشتر به دلیل استفاده از دیتابیس های قدیمی، توس حالت خاصی بوجود میاد.
اگر دیتابیس قدیمی رو دارید که حتما این مشکل براش بوجود میاد، برای من ایمیل کنید. تا الان نتونستم دقیق پیداش کنم.

راه حل ساده اش هم یکبار ویرایش و ذخیره inboud مربوطه است.

**Comment by masoud-hidden** [comment]
سلام ممنون از زحماتتون.
این مشکل برای من هم اتفاق میوفته دیتابیس رو بررسی کردم مواقع عادی داخل همه inbound های VLESS نوشته "decryption":"none" ولی در مواقع خاص بصورت دیگه ای در دیتابیس ذخیره میشه "decryption": null و هم داخل دیتابیس هم کانفیگ xray اینطور میشه. که البته با ویرایش inbound درست میشه.
اینطور که بررسی کردم وقتی حجم کلاینی از inbound مورد نظر تموم میشه یا تاریخش تموم میشه یا تنظیمات اصلی پنل رو تغییر میدم اینطور میشه.
بررسی کردم حتی بعد از تغییرات امروزتون هم این مشکل پابرجاست.

**Comment by alireza0** [comment]
@masoud-hidden 
ممنونم از توضیحاتتون
توی تغییرات دیروز که برای #164 انجام شد، اختلال مربوط به ذخیره فایل `config.json` برطرف شده.
اگر خودتون به صورت دستی کمپایل میکنید، لطفا این موضوع رو تست کنید.
یا در صورت امکان یک سناریو تست شده (که در هرصورت به این مشکل میخوره) به صورت کامل به من بدید تا خودم کامل debug کنم.
سپاسگزارم

**Comment by masoud-hidden** [comment]
@alireza0 
تغییرات جدیدتون رو امتحان کردم مشکل داشت. اینطور که فهمیدم مشکل در JS هست و در فایل xray.js این مشکل به وجود میاد.
در #173 این مشکل رو حل کردم و از دیشب تا الان چنین مشکلی ندیدم. البته #173 یک مشکل دیگه هم حل میکنه که مربوط به محاسبه حجم کلاینت های در حال اتمام هست، این مشکل اینطور بود که کلاینت هایی که حجمشون در حال اتمام بود رو در ربات یا پنل نشون نمی داد.

**Comment by MA7** [comment]
> درود بر شما این مشکل بیشتر به دلیل استفاده از دیتابیس های قدیمی، توس حالت خاصی بوجود میاد. اگر دیتابیس قدیمی رو دارید که حتما این مشکل براش بوجود میاد، برای من ایمیل کنید. تا الان نتونستم دقیق پیداش کنم.
> 
> راه حل ساده اش هم یکبار ویرایش و ذخیره inboud مربوطه است.

دیتابیس جهت بررسی دقیق تر ارسال شد به ایمیل تون 

با تشکر فراوان از شما

**Comment by MA7** [comment]
این خطا زمان اتفاق اش هم دقیقا میشه وقتی که کاربری حجمش تموم میشه و سیستم میخواد غیر فعالش کنه اتومات

**Comment by masoud-hidden** [comment]
@alireza0 
این مشکل زمانیکه تاریخ انقضای کلاینت بر اساس اولین اتصال ثبت میشد بوجود می اومد. با #183 مشکل رفع شده و با ۲۰۰ تا یوزر کاملا امتحانش کردم.

**Comment by alireza0** [comment]
@masoud-hidden 
متوجه مشکل شدم.
تغییرات شما اضافه شد.
سپاسگزارم

**Comment by masoud-hidden** [comment]
@alireza0 
متاسفانه یک مشکل دیگه بوجود اومده، برای کلاینت های براساس اولین اتصال تاریخ انقضا ثبت نمیشه. فکر میکنم بخاطر همین تغییرات جدید هست.

**Comment by alireza0** [comment]
تصحیح شد
