### ISSUE TITLE
امکان کوچ کردن از پنل صناعی به پنل شما

### ISSUE THREAD

**Issue by amir323b** [alireza0/x-ui#163]
سلام و احترام . 
ممنونم از زحماتتون 
میخواستم بدونم امکان کوچ کردن از پنل صناعی به پنل شما هست ؟
مشکلی برا یوزرها پیش نمیاد ؟
حجم مصرفی یوزرها بهم نمیریزه ؟
اگه میشه . آیا باید پنل صناعی رو پاک کنم بعد پنل  شما رو نصب کنم ؟ ، یا اینک همین الان پنل شما رو نصب کنم اوکیه ؟

**Comment by forkeer** [comment]
Hi
First backup the x-ui.db in /etc/x-ui/ folder .

Then run bash <(curl -Ls https://raw.githubusercontent.com/alireza0/x-ui/master/install.sh)
and when install Do you want to continue with the modification [y/n]? : choose n 

Migration is complated .

Thanks

**Comment by forkeer** [comment]
@alireza0 
Please Close

**Comment by amir323b** [comment]
thanks.

i should choose: n ???
