### ISSUE TITLE
ازکار افتادن پنل با دیسیبل کردن یوزر 

### ISSUE THREAD

**Issue by arash1959** [alireza0/x-ui#164]
با سلام و خسته نباشید مشکل از کار افتادن پنل با دیسیبل کردن یوزر  هست نصب به صورت سرور خام بوده نه آپگرید تایم و ترافیک پنل رو  دو تنظیم شده و به محض دیسیبل کردن یوزر پنل اررو میده

**Comment by MA7** [comment]
> با سلام و خسته نباشید مشکل از کار افتادن پنل با دیسیبل کردن یوزر تاریخ و حجم دار هست نصب به صورت سرور خام بوده نه آپگرید تایم و ترافیک پنل رو دو تنظیم شده و به محض دیسیبل کردن یوزر پنل اررو میده

از خطایی که دریافت کردید عکس یا جزییات قرار بدید که بشه متوجه جزییات خطا شد.

**Comment by arash1959** [comment]
xray Status: error

**Comment by MA7** [comment]
> xray Status: error

روی اون علامت ! موس رو نگه دارید تا جزییات رو نشون بده

**Comment by arash1959** [comment]
![22](https://user-images.githubusercontent.com/124699859/230674407-4471ccc9-277d-428c-b7ad-b2502557f35a.png)

**Comment by arash1959** [comment]
در صورتی که هر اسمی میزنم میگه already exists رو پورت دیگه ali دارم اینجا میزنم ali2  فقط به یوزر هشتم گیر میده هر چی باشه

**Comment by arash1959** [comment]
البته وقتی یوزر حجم و تاریخ دار بالاییش رو دیسیبل میکنم نکنم مشکلی نداره

**Comment by arash1959** [comment]
متوجه شدم فقط حجم دار نیست هر یوزری دیسیبل میشه ارور میده

**Comment by masoud-gb** [comment]
من هم متاسفانه همین مشکل رو دارم در ابدیت جدید

**Comment by alireza0** [comment]
درود بر شما
مشکل رو تست کردم و مورد تاییده.

**Comment by aliamg1356** [comment]
خوشبختانه دارم میبینم این مشکل ارور پنل رو پیدا کردید و فیکس کردید  ولی کامپایل نکردید  چطور میشه کامپایل کرد ؟با چه نرم افزترهایی؟ برای ویندوز چطور؟

**Comment by alireza0** [comment]
کمپایل شده و بعد از تست های اولیه از حالت pre-release خارج میشه و میتونید به راحتی آپدیت کنید.
https://github.com/alireza0/x-ui/releases/tag/0.5.1

**Comment by masoud-gb** [comment]
@alireza0 
درود علیرضا عزیز و سپاس از زحماتت
بعد از روشن کردن Start after first use هنوز با اولین disable شدن یوزر xray stop میشه با اینکه همیشه اخرین ابدیت را دریافت میکنم
با احترام
