### ISSUE TITLE
subscription

### ISSUE THREAD

**Issue by AmoAlireza** [alireza0/x-ui#165]
سلام خدمت علیرضا جان @alireza0 
تشکر بابت قابلیت های جدید و پیشرفته پنل.
اگر امکانش هست یه توضیحی در مورد استفاده از سابسکرایب بدین و چطوری کار میکنه.
توی آپدیت بعدی اگر بشه این لینک سابسکرایب کاستوم کرد مثل قسمت domain name داخل inboubnd ها مثلا لینک و پورت پنل استفاده نکنه و هر چیزی که داخل فیلد مخصوصش گزاشته بشه از اون دامین استفاده کنه نمونش:
subdomain.example.com/subs/USER1

**Comment by alireza0** [comment]
درود بر شما
این مدل پیاده شده ساده ترین مدلی بود که میشد به خورد پنل x-ui داد.
در واقع خیلی راحت نمیشه همه جوره پیاده سازی کرد. بخصوص امکان دستکاری.
ولی نیازهای شما در این مدل کاملا قابل اجراست.
اگر میخواید از پورت پنل استفاده نکنه پیشنهاد میکنم از proxy_pass در nginx استفاده کنید:
```
http {
    server {
        listen 8080;
        servername = subdomain.example.com;
        location /subs/ {
            proxy_pass http://x-ui_server.example.com:54321/sub/;
        }
    }
}
```
