### ISSUE TITLE
اضافه کردن reality 

### ISSUE THREAD

**Issue by Prot0nX** [alireza0/x-ui#166]
سلام مهندس اینو دیشب دیدم که تونسته پروتکل جدید و به پنل اضافه کنه گفتم برای شما هم بفرستم بررسیش کنید

[لینک آموزش](https://blog-misaka-rest.translate.goog/2023/04/08/x-ui-reality/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)

**Comment by alireza0** [comment]
درود بر شما
با روش اجرای و بروزرسانی این مدل آشنایی دارم.
این مدل طراحی اش فقط با اضافه کردن به پنل تمام نمیشه و کلی عملیات پشت زمینه و تنظیمات نیاز داره که باعث میشه هرکسی نتونه انجام بده.
هدف پنل ساده سازی بوده و با این روش پیچیدگی بیشتر میشه.
همچنان روش کار میکنم که بتونم ساده تر اجراش کنم.
