### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by voono** [alireza0/x-ui#170]
سلام ممکنه در مورد نحوه کار API یه توضیحی بدید یا آموزش یا مثالی ازش توی صفحه قرار بدید؟

**Comment by alireza0** [comment]
درود بر شما
پروژه به اندازه ای کوچک هست که به راحتی بتونید از کد ها روش ارسال رو پیدا کنید.
متدهای قابل استفاده رو هم توی [README.md](https://github.com/alireza0/x-ui#api-routes) گذاشتم:
