### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by MobinFNE** [alireza0/x-ui#174]
Hello and thank you for this excellent panel you've done
I have a problem with this Database is locked error
what I should do for this ?

**Comment by alireza0** [comment]
Hello @MobinFNE 
I have no idea with this general question without any explanation.
But my experiences showed that this problem may happen when you have weak CPU or I/O problem in HDD.

**Comment by ariandcir** [comment]
I think there is something that is causing this. I am also having this issue again with 0.5.1
I had no such issues when using 0.4.3.

Apr 12 17:02:49  2023/04/12 17:02:49 WARNING - something worng!Fail:  database is locked
Apr 12 17:02:59  2023/04/12 17:02:59 WARNING - something worng!Fail:  database is locked
Apr 12 17:03:04  2023/04/12 17:03:04 ERROR - restart xray failed: database is locked
Apr 12 17:03:04  2023/04/12 17:03:04 WARNING - disable invalid Client err: database is locked
Apr 12 17:03:07  2023/04/12 17:03:07 WARNING - something worng!Fail:  database is locked
Apr 12 17:03:09  2023/04/12 17:03:09 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:03:14  2023/04/12 17:03:14 WARNING - something worng!Fail:  database is locked
Apr 12 17:03:24  2023/04/12 17:03:24 WARNING - something worng!Fail:  database is locked
Apr 12 17:03:34  2023/04/12 17:03:34 WARNING - disable invalid Client err: database is locked
Apr 12 17:03:34  2023/04/12 17:03:34 WARNING - something worng!Fail:  database is locked
Apr 12 17:03:39  2023/04/12 17:03:39 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:03:49  2023/04/12 17:03:49 WARNING - something worng!Fail:  database is locked
Apr 12 17:04:05  2023/04/12 17:04:05 WARNING - disable invalid Client err: database is locked
Apr 12 17:04:08  2023/04/12 17:04:08 WARNING - add traffic failed: database is locked
Apr 12 17:04:10  2023/04/12 17:04:10 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:04:15  2023/04/12 17:04:15 WARNING - something worng!Fail:  database is locked
Apr 12 17:04:25  2023/04/12 17:04:25 WARNING - something worng!Fail:  database is locked
Apr 12 17:04:36  2023/04/12 17:04:36 WARNING - something worng!Fail:  database is locked
Apr 12 17:04:36  2023/04/12 17:04:36 WARNING - disable invalid Client err: database is locked
Apr 12 17:04:38  2023/04/12 17:04:38 WARNING - add traffic failed: database is locked
Apr 12 17:04:41  2023/04/12 17:04:41 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:05:03  2023/04/12 17:05:03 WARNING - disable invalid Client err: database is locked
Apr 12 17:05:04  2023/04/12 17:05:04 WARNING - Get settingFail:  database is locked
Apr 12 17:05:04  2023/04/12 17:05:04 WARNING - ObtainFail:  database is locked
Apr 12 17:05:08  2023/04/12 17:05:08 WARNING - add traffic failed: database is locked
Apr 12 17:05:08  2023/04/12 17:05:08 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:05:18  2023/04/12 17:05:18 WARNING - something worng!Fail:  database is locked
Apr 12 17:05:33  2023/04/12 17:05:33 WARNING - disable invalid Client err: database is locked
Apr 12 17:05:33  2023/04/12 17:05:33 WARNING - Get settingFail:  database is locked
Apr 12 17:05:33  2023/04/12 17:05:33 WARNING - ObtainFail:  database is locked
Apr 12 17:05:38  2023/04/12 17:05:38 WARNING - add traffic failed: database is locked
Apr 12 17:05:38  2023/04/12 17:05:38 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:05:41  2023/04/12 17:05:41 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:05:48  2023/04/12 17:05:48 WARNING - add traffic failed: database is locked
Apr 12 17:05:51  2023/04/12 17:05:51 WARNING - something worng!Fail:  database is locked
Apr 12 17:06:04  2023/04/12 17:06:04 WARNING - disable invalid Client err: database is locked
Apr 12 17:06:04  2023/04/12 17:06:04 WARNING - something worng!Fail:  database is locked
Apr 12 17:06:08  2023/04/12 17:06:08 WARNING - add traffic failed: database is locked
Apr 12 17:06:09  2023/04/12 17:06:09 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:06:15  2023/04/12 17:06:15 WARNING - something worng!Fail:  database is locked
Apr 12 17:06:25  2023/04/12 17:06:25 WARNING - something worng!Fail:  database is locked
Apr 12 17:06:35  2023/04/12 17:06:35 WARNING - something worng!Fail:  database is locked
Apr 12 17:06:35  2023/04/12 17:06:35 WARNING - disable invalid Client err: database is locked
Apr 12 17:06:45  2023/04/12 17:06:45 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:07:04  2023/04/12 17:07:04 WARNING - disable invalid Client err: database is locked
Apr 12 17:07:08  2023/04/12 17:07:08 WARNING - add traffic failed: database is locked
Apr 12 17:07:09  2023/04/12 17:07:09 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:07:34  2023/04/12 17:07:34 WARNING - disable invalid Client err: database is locked
Apr 12 17:07:38  2023/04/12 17:07:38 WARNING - add traffic failed: database is locked
Apr 12 17:07:39  2023/04/12 17:07:39 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:08:04  2023/04/12 17:08:04 WARNING - disable invalid Client err: database is locked
Apr 12 17:08:08  2023/04/12 17:08:08 WARNING - add traffic failed: database is locked
Apr 12 17:08:09  2023/04/12 17:08:09 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:08:12  2023/04/12 17:08:12 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:08:33  2023/04/12 17:08:33 WARNING - disable invalid Client err: database is locked
Apr 12 17:08:38  2023/04/12 17:08:38 WARNING - add traffic failed: database is locked
Apr 12 17:08:38  2023/04/12 17:08:38 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:08:40  2023/04/12 17:08:40 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:08:51  2023/04/12 17:08:51 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:09:06  2023/04/12 17:09:06 WARNING - disable invalid Client err: database is locked
Apr 12 17:09:08  2023/04/12 17:09:08 WARNING - add traffic failed: database is locked
Apr 12 17:09:11  2023/04/12 17:09:11 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:09:12  2023/04/12 17:09:12 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:09:17  2023/04/12 17:09:17 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:09:22  2023/04/12 17:09:22 WARNING - AddClientTraffic update data  database is locked
Apr 12 17:09:37  2023/04/12 17:09:37 WARNING - disable invalid Client err: database is locked
Apr 12 17:09:38  2023/04/12 17:09:38 WARNING - AddClientTraffic update data  database is locked
Apr 12 17:09:38  2023/04/12 17:09:38 WARNING - add traffic failed: database is locked
Apr 12 17:09:42  2023/04/12 17:09:42 WARNING - something worng!Fail:  database is locked
Apr 12 17:09:42  2023/04/12 17:09:42 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:09:43  2023/04/12 17:09:43 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:09:58  2023/04/12 17:09:58 WARNING - AddClientTraffic update data  database is locked
Apr 12 17:10:03  2023/04/12 17:10:03 WARNING - disable invalid Client err: database is locked
Apr 12 17:10:08  2023/04/12 17:10:08 WARNING - add traffic failed: database is locked
Apr 12 17:10:08  2023/04/12 17:10:08 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:10:13  2023/04/12 17:10:13 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:10:34  2023/04/12 17:10:34 WARNING - disable invalid Client err: database is locked
Apr 12 17:10:38  2023/04/12 17:10:38 WARNING - add traffic failed: database is locked
Apr 12 17:10:39  2023/04/12 17:10:39 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:10:43  2023/04/12 17:10:43 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:11:04  2023/04/12 17:11:04 WARNING - disable invalid Client err: database is locked
Apr 12 17:11:08  2023/04/12 17:11:08 WARNING - add traffic failed: database is locked
Apr 12 17:11:09  2023/04/12 17:11:09 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:11:20  2023/04/12 17:11:20 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:11:36  2023/04/12 17:11:36 WARNING - disable invalid Client err: database is locked
Apr 12 17:11:41  2023/04/12 17:11:41 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:12:05  2023/04/12 17:12:05 WARNING - disable invalid Client err: database is locked
Apr 12 17:12:08  2023/04/12 17:12:08 WARNING - add traffic failed: database is locked
Apr 12 17:12:10  2023/04/12 17:12:10 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:12:10  2023/04/12 17:12:10 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:12:36  2023/04/12 17:12:36 WARNING - disable invalid Client err: database is locked
Apr 12 17:12:36  2023/04/12 17:12:36 WARNING - AddClientTraffic update data  database is locked
Apr 12 17:12:38  2023/04/12 17:12:38 WARNING - add traffic failed: database is locked
Apr 12 17:12:41  2023/04/12 17:12:41 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:12:51  2023/04/12 17:12:51 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Apr 12 17:13:08  2023/04/12 17:13:08 WARNING - disable invalid Client err: database is locked
Apr 12 17:13:08  2023/04/12 17:13:08 WARNING - add traffic failed: database is locked
Apr 12 17:13:13  2023/04/12 17:13:13 WARNING - disable invalid inbounds err: database is locked
Apr 12 17:13:24  2023/04/12 17:13:24 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email



I checked my CPU, there are 2 vcpus and none of them max 70% let alone reaching an overall of 100%.
It is important to note that this issue didn't exist in 0.4.3
