### ISSUE TITLE
database\model\model.go ..form ... or from ?

### ISSUE THREAD

**Issue by lk29** [alireza0/x-ui#176]
`type Client struct {
	ID         string ....
	Password   string ...
	Flow       string ....
	AlterIds   uint16 ....
	Email      string ....

	TotalGB    int64  json:"totalGB" form:"totalGB"
	ExpiryTime int64 json:"expiryTime" form:"expiryTime"

	Enable     bool   json:"enable" from:"enable"
	TgID       string json:"tgId" from:"tgId"
	SubID      string json:"subId" from:"subId"

}

`
👀

**Comment by alireza0** [comment]
`Form` is correct :D
