### ISSUE TITLE
اصلاح سرویس های مربوط به کلاینت

### ISSUE THREAD

**Issue by aliaasl** [alireza0/x-ui#177]
عرض سلام و خسته نباشید
سرویس های مربوط به کلاینت ها مانند (ایجاد و حذف) لیست تمامی کلاینت ها رو میفرستن به سرور! در صورتی که مثلا موقع ایجاد فقط باید کلاینت جدید ارسال بشه، یا برای حذف فقط باید شناسه ی کلاینتی که باید حذف بشه ارسال بشه.

مشکلی که این مسئله بوجود میاره اینه که فرض کنید تو دو تا سیستم با سرور کار کنن، تو یک سیستم لیست رو باز میکنیم و تا بیایم مشخصات یک کلاینت رو بزنیم، تو سیستم دیگه یه کلاینتی ایجاد بکنن، حالا اگر ما بزنیم کلاینتمون ایجاد بشه، کلاینتی که تو اون یکی سیستم ایجاد شده بود حذف میشه! چون تو لیستی که مرورگر من به سرور فرستاد اون کلاینت نبود!

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و طرح مساله شما
کاملا حق با شماست و متاسفانه این مساله وجود داره و به دلیل اینکه نمیشه از پایه همه چیز رو عوض کرد، مجبور به انتخاب این روش شدیم.
کاربرها در دیتابیس به همراه دیتاهای دیگه توی یک فیلد متنی ذخیره میشن و هربار باید کلی محاسبه بشه تا بتونیم اضافه و کم کنیم.
بهترین راه از نظر من فدا کردن بخش کم ارزش بود.
البته احتمال رخداد مساله ایراد شده توسط شما بسیار پایینه و با توجه به ساختار دیتابیس، احتمال ایجاد باگ های زیاد در روش ارسال اطلاعات مینیمم، به شدت زیاده.
