### ISSUE TITLE
مستندات api

### ISSUE THREAD

**Issue by mostafa9112** [alireza0/x-ui#178]
علیرضا جان میشه مستندات api رو بدی؟
مثلا برای addclient چه مواردی باید ارسال بشه و به چه روشی؟

**Comment by alireza0** [comment]
پروژه به اندازه کافی کوچک و باز هست که بتونید از کد ها اون رو پیدا کنید.
[لینک متد ها](https://github.com/alireza0/x-ui#api-routes)

**Comment by mostafa9112** [comment]
دقیقا این متد ها توی فایل api.go هم هست اما مشکل اینجاست مقادیری که باید post بشه چی باید باشه اونو پیدا نکردم

**Comment by alireza0** [comment]
شبیه اون رو توی پنل دارین. میتونید از اونجا ببینید چه دیتایی ارسال میشه.
یکم دیگه دیتاش رو بهینه میکنم. الان باید کل inbound.settings ارسال بشه.
توی هر بروزرسانی، تغییرات رو حتما دنبال کنید.
