### ISSUE TITLE
تانل دو سرور ایران و خارج | Tunnel between two servers

### ISSUE THREAD

**Issue by Mammad3861** [alireza0/x-ui#180]
خیلی دنبال راه برای تانل کردن دوتا سرورم گشتم فقط iptables برای حدودا چند ساعت جواب داد بعد هم قطع شد
کسی راهی داره با کانفیگوریشن خود x-ui بتونم تانل بزنم؟

**Comment by alireza0** [comment]
https://github.com/MHSanaei/3x-ui/issues/151
