### ISSUE TITLE
Searching bug

### ISSUE THREAD

**Issue by Shjpr9** [alireza0/x-ui#181]
سلام وقتتون بخیر
من بعد از نصب پنل، دیتابیس یوزر ها رو از یه پنل دیگه وارد کردم و هر یوزر رو یک بار روی پنل ادیت زدم و الان درست کار میکنه
ولی وقتی یه ایمیل رو سرچ میکنم علاوه بر اون یوزر های دیگه رو هم میاره و وقتی رو + میزنم میزنه No Data . خواستم بدونم این مشکل از کجا میتونه باشه؟

![image](https://user-images.githubusercontent.com/67644313/230924171-0cc9bb92-1061-4627-b8ef-eb5fb83e7f72.png)

**Comment by alireza0** [comment]
درود بر شما
این موضوع باگ نیست و امکانات خاص جستجو محسوب میشه.
شما وقتی یک عبارت رو جستجو میکنید، سیستم توی تمام جزئیات inbound ها و client ها میگرده (‌نه فقط قسمتی که شما میبینید).
اگر فقط inbound جواب شما بود، حتما نتیجه جستجو توی جزئیات inbound دیده شده و هیچ client ای با این جستجو تطبیق نداشته.
