### ISSUE TITLE
بالا بردن امنیت پنل

### ISSUE THREAD

**Issue by Morghak963** [alireza0/x-ui#185]
سلام
خسته نباشید مهندس جان
پیشنهادی داشتم جهت بهبود امنیت پنل

همینطور که می‌دانید بات تلگرام ورود موفق و ناموفق به پنل رو اطلاع رسانی میکنه ،و این مدت متوجه شدم تلاش های زیادی برای ورود به پنلم انجام شده که مشخص هست بصورت دستی نبوده برای مثال در یک ثانیه ۳۰ بار با یوزرنیم و پسورد های متفاوت تلاش برای ورود به پنل شده ،درصورتی که پنل کاملا شخصی و خانوادگی هست
پرس و جو کردم و دیدم خیلی از دوستان که حتی پنل های شخصی داشتند دچار این مشکل شدند

همچنین چند وقت پیش در یکی از گروه ها عینا مشاهده کردم که یکی از کاربران از طریق لینک تستی که داخل گروه بود موفق به ورود به پنل صاحب لینک شده بود و نکته حائز اهمیت این هست که یوزرنیم و پسورد اون پنل هم پیش فرض نبود که حدسش به سادگی باشه

با توجه به دو تجربه بالا میخواستم این پیشنهاد رو بدم که در صورت امکان،قابلیت تایید دو مرحله ای برای پنل پیش بینی بشه حالا چه به وسیله نرم افزار های واسط مثل
 google authenticatior
و یا حتی از طریق ارسال ایمیل به صاحب پنل

یا هر قابلیت امنیتی دیگری که شما صلاح بدونید و در جهت بالا بردن امنیت پنل موثر باشه

باتشکر

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و پیشنهادتون
در این مورد خیلی صحبت و فکر شده و روشهای زیادی وجود داره که بشه امنیت رو بالا برد.
ولی از اونجایی که تاکید ما روی سادگی پنل بوده و هست، پیشنهاد میکنم از روش های جایگزین استفاده کنید:
۱. پورت پنل رو از حالت پیشفرض تغییر بدید
۲. مسیر پیش فرض رو از / تغییر بدید
۳. از محدودیت IP روی پنل توی بخش تنظیمات استفاده کنید
۴. از طریق iptables دسترسی ها رو محدود کنید
۵. اگر بتونید با اتصال به لاگ ها، fil2ban رو تنظیم کنید خیلی خوبه
۶. با استفاده از کلادفلر و یا nginx میتونید محدودیت های بیشتری رو اعمال کنید.
۷. تا اونجایی که میشه آدرس فعالیت پنل رو از آدرس اتصال کاربر ها جدا کنید.

موارد بسیار زیادی هست که میتونید رعایت کنید و در عین سادگی، امنیت مناسبی برای شما داره.

**Comment by Morghak963** [comment]
![IMG_20230414_142410_539](https://user-images.githubusercontent.com/127750712/232026377-b0147f0b-eea0-4d1b-8fcf-78d2286d7abe.jpg)

سلام مجدد
مهندس جان این عکس رو ببینید
یک پنل چینی دیدم که در گروهش مدعی شده بود که در نسخه بعدی قابلیت کپچا رو به صفحه لاگین اضافه میکنه
و این خودش خیلی میتونه کمک کننده باشه برای جلوگیری از یکسری حملات به پنل

لینک گین هاب پنل
https://github.com/sing-web/x-ui
