### ISSUE TITLE
user exist error

### ISSUE THREAD

**Issue by darianBaba** [alireza0/x-ui#187]
سلام
من با این مشکل مواجه میشم
چرا؟

Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 linux/amd64)

A unified platform for anti-censorship.

2023/04/11 14:59:27 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to create server > proxy/vmess/inbound: failed to initiate user > proxy/vmess/inbound: User علی already exists.

اگر یوزر رو غیرفعال کنم، درست میشه اما دوباره بعد 24 ساعت، یوزر جدید هم ارور میده

**Comment by alireza0** [comment]
درود بر شما
این مشکل مربوط به باگ نسخه 0.5.0 بود که برطرف شده.
لطفا به آخرین نسخه بروزرسانی کنید. مشکل حل میشه.
