### ISSUE TITLE
data base lock

### ISSUE THREAD

**Issue by aliafshany** [alireza0/x-ui#19]
Hello there
i am experiencing this error since a long time ago.
this issue is related  to IP Limit function which causes the problem.
for example in MHSane's panel I don't experience such a thing.
would you mind please investigate this one?
i tried `sudo chmod --preserve-root 644 /etc/x-ui/x-ui.db`

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/40741745/220414632-d090080e-9c0b-44de-9c33-448951adf0e7.png">

**Comment by aliafshany** [comment]
@alireza0 
i run my commands on root access level so there is no problem at executing these commands.

ehre are the results for the written commands:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/40741745/220740057-4b2da6fa-8d09-4e21-88ef-0cb81a0c36a1.png">

FYI, I have tested `chown root /etc/x-ui/x-ui.db
` and `sudo chmod --preserve-root 644 /etc/x-ui/x-ui.db` as it was mentioned by Niduka.

no luck at all.
do you have other ideas how this might be happening?

best

**Comment by alireza0** [comment]
In this picture, x-ui service is not running! Please check your service.
Regarding permissions, everything sounds Okey. If the service is also normal and your x-ui is running by root, I recommend you to open your database manually and check everything inside.

**Comment by aliafshany** [comment]
@alireza0 
i couldn't find any issues in the database.
also can email my db to you if you'd like, so you can check it for yourself.
i know it's a bug. an annoying one for sure.
would you mind investigating it, plaese?

**Comment by alireza0** [comment]
> @alireza0 i couldn't find any issues in the database. also can email my db to you if you'd like, so you can check it for yourself. i know it's a bug. an annoying one for sure. would you mind investigating it, plaese?

Send it to my email. I will check it for you
