### ISSUE TITLE
Multi CDN IP's for subscriptions

### ISSUE THREAD

**Issue by arash88** [alireza0/x-ui#190]
Hey @alireza0 jan,
Is it possible to have multiple domain names per inbounds which should have results in multiple links in subscriptions?

Thanks a lot dadashi

**Comment by AmoAlireza** [comment]
علیرضا جان اگر امکانش هست روی این موضوع کار کنید من با اینکه استفاده شخصی میکنم و کلا 30 تا اشتراک دارم نیازه برای ایرانسل ای پی تمیز جداگانه بزارم.
اگر میشه یه باکس مخصوص قسمت سابسکرایب بزارین که به تعداد ای پی تمیز یا دامین یدونه کانفیگ بسازه.

**Comment by alireza0** [comment]
Hello @arash88 
This possibility will cut the chain of X-UI panels. I am trying to keep it interoperable.
But it is possible to use domains with more than one IP, to overcome these needs.
It might be implemented in the future in other places which is possible ( considering my limitations )

@AmoAlireza 
کار کردن روی ویژگی هایی که قابلیت اجرا با راه های دیگه دارن، هم روند توسعه رو کند میکنه و هم پنل رو سنگین میکنه.
پیشنهاد من استفاده از نام های چند رکورده توی دامنه است که میتونه این کار رو برای شما انجام بده.
در ضمن کلاینت معمولا از یک اینترنت استفاده میکنه و بر اساس نیازش میتونه روی اینباندهایی که روی سرویس های متفاوت هستند باشه.
با ارائه اسم ساب مشترک برای کاربرهای متفاوت توی سرویس های متفاوت میتونید ساب چند کانفیگه داشته باشید. این ویژگی کاملا پیاده سازی شده.

**Comment by EarlVadim** [comment]
> Hey @alireza0 jan, Is it possible to have multiple domain names per inbounds which should have results in multiple links in subscriptions?
> 
> Thanks a lot dadashi

Yes, it's possible. I have this configuration..
