### ISSUE TITLE
Reality Protocol

### ISSUE THREAD

**Issue by DoctorsPlague** [alireza0/x-ui#192]
Dear Alireza
I'd like to express my sincere appreciation and also I have a request. as you might know a new protocol has recently been added to X-ray core v1.8.0. Its name is Reality. I have no knowledge about its functions but it works properly on MTN and MCI and all other ISPs.
please provide this new feature on you awesome panel.
On other panels it's only works through VLESS TCP. Please provide more options if it's possible. It would be great if we could use this new feature with Trojan WS.
Thanks for your time.

**Comment by alireza0** [comment]
Duplicate #131
