### ISSUE TITLE
بات تلگرام برای کاربر چطور فعال میشه ؟

### ISSUE THREAD

**Issue by javadbahmani1372** [alireza0/x-ui#193]
سلام.
بات تلگرام برای کاربران کار نمیکنه! کلا بات هیچ پاسخی نمیده. فقط بکاپ رو میفرسته.همین.لطفا یه داکیومنت واضح و کامل از طریقه فعال سازی و استفاده از بات رو بذارید.
ممنون از زحماتتون ...

**Comment by mahdihavoc** [comment]
دوست عزیز برو مطالب رو کامل بخون 
که نگید بات درست کار نمیکنه 
با کاربر ادمین وارد میشید طبیعتن چیزی برنمیگردونه 
با کاربر عادی وارد بشید یعنی یک اکانت تلگرام دیگر که ادمین نباشد

**Comment by javadbahmani1372** [comment]
خب مسئله اینه من تمامی مطالب رو خوندم. کد های این پنل رو هم خوندم. جایی ننوشته چه کامند هایی باید برای ارتباط با بات باید استفاده بشه و این که ادمین هم قابل کنترل هست توسط بات و کامند های خاص خودشو داره اما به هیچکدوم پاسخ نمیده. شما یه زحمت بکش مطالبی که میفرمایید رو لینک بدید من بخونم.من چیزی پیدا نکردم.ممنون میشم ازتون.

**Comment by javadbahmani1372** [comment]
@mahdihavoc 
مشکل حل شد.
داستان از این قرار بود که توکن تلگرام وقتی از قبل در تنظیمات موجود باشه هرچی پنل رو ری استارت کنین فرقی نداره.بات فعال نمیشه توی قسمت مدیریت از طریق بات و منو های بات نشون نمیده.چه برای کاربر و چه برای ادمین.راه حلش اینه توکن بات رو عوض کنین.وقتی تغییر کنه قسمت مدیریت از طریق بات فعال میشه.یه جورایی باگه. علتش چیه رو نمیدونم. @alireza0

**Comment by alireza0** [comment]
لطفا لاگ سرور رو چک کنید.
زمانی که پنل ریستارت میشه، بات تلگرام ( در صورت فعال بودن ) اجرا میشه و لاگ میزنه
```
INFO - Tg notify enabled,run at @daily
```
اگر خطا داشته باشین هم اعلام میکنه
