### ISSUE TITLE
باگ در پنل ورژن 0.5.1

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#195]
به ورژن جدید آپدیت کردم ولی یه موردی برخوردم و خطای اکانت هم نام میداد و اکانت جدید ذخیره نمیکرد بعد از باز کردن دیتا بیس دیدم اکانتی رو پاک کنی یا تغییر نام بدیم در دیتا بیس اون حذف نمیشه  
![Untitled](https://user-images.githubusercontent.com/124570423/231576846-4d004c91-5e7a-4c0b-a1d2-dc48f437a5de.jpg)
دقت کنید من در این کانت نام اکانت رو از User11_p_mci-f به User12_p_mci-f تغییر دادم ولی اکانت با اسم اول حذف نشده  اگر لازمه دیتا بیس رو براتون ایمیل کنم

**Comment by dev-ir** [comment]
اتفاقا این موضوع منم بهش برخوردم ولی به سبک دیگری : 
یک کلاینت ساخته شد و بعدش ویرایش شد و دوباره که خواستم به قبل برگردونم خطا بالا داد و دیگه اجازه ساخت با همون نام نداشتم

**Comment by alireza0** [comment]
زمانی که کاربر در حال استفاده است، تغییر ایمیلش یه اشتباه بزرگه! چرا باید این کار رو انجام بدید ؟
سعی میکنم جلوش رو بگیرم، ولی این کار رو هیچ وقت انجام ندید!
توضیح:
ترافیک کاربر با ایمیل شناخته میشه و هر ۱۰ ثانیه چک میشه و به دیتابیس اضافه میشه.
توی این ۱۰ ثانیه اگر ایمیل تغییر کنه، دوتا ترافیک خواهیم داشت. یکی با ایمیل اول و دیگری با ایمیل جدید. نرم افزار اون ایمیل قبلی رو هم رو با اشتباهاتش ( شامل اینکه نمیدونه کدوم سرویس رو داره ) ثبت میکنه.
اگر بخوایم ترافیک کاربر در زمان تعویض رو دور بریزیم هم اون ترافیک محاسبه نمیشه. پس لطفا هیچ وقت این کار رو نکنید

**Comment by aliamg1356** [comment]
> زمانی که کاربر در حال استفاده است، تغییر ایمیلش یه اشتباه بزرگه! چرا باید این کار رو انجام بدید ؟ سعی میکنم جلوش رو بگیرم، ولی این کار رو هیچ وقت انجام ندید! توضیح: ترافیک کاربر با ایمیل شناخته میشه و هر ۱۰ ثانیه چک میشه و به دیتابیس اضافه میشه. توی این ۱۰ ثانیه اگر ایمیل تغییر کنه، دوتا ترافیک خواهیم داشت. یکی با ایمیل اول و دیگری با ایمیل جدید. نرم افزار اون ایمیل قبلی رو هم رو با اشتباهاتش ( شامل اینکه نمیدونه کدوم سرویس رو داره ) ثبت میکنه. اگر بخوایم ترافیک کاربر در زمان تعویض رو دور بریزیم هم اون ترافیک محاسبه نمیشه. پس لطفا هیچ وقت این کار رو نکنید

اوکی  الان ما هنگام تغییر نام کاربر یرویس xray رو استوپ کنیم باز این مشکل پیش میاد؟

**Comment by alireza0** [comment]
> اوکی الان ما هنگام تغییر نام کاربرسرویس xray رو استوپ کنیم باز این مشکل پیش میاد؟

نه! البته نیازی به اون کار هم نیست. کافیه کاربر رو غیرفعال کنید و حداقل ۲۰ ثانیه صبر کنید و بعد ویرایش کنید.
توی ویرایش کاربر میتونید همزمان با تغییر ایمیل، فعالش کنید و ذخیره کنید.

یه نسخه باگ فیکس جدید میزنم که از بوجود اومدن این مشکل جلوگیری کنه. ولی حداقل ایرادش اینه که ترافیک اون ۱۰ ثانیه کاربر حساب نمیشه دیگه.
پس بهتره ایمیل کاربر رو تغییر ندید. در صورت لزوم، حتما قبلش غیرفعال شده باشه.

**Comment by aliamg1356** [comment]
> > اوکی الان ما هنگام تغییر نام کاربرسرویس xray رو استوپ کنیم باز این مشکل پیش میاد؟
> 
> نه! البته نیازی به اون کار هم نیست. کافیه کاربر رو غیرفعال کنید و حداقل ۲۰ ثانیه صبر کنید و بعد ویرایش کنید. توی ویرایش کاربر میتونید همزمان با تغییر ایمیل، فعالش کنید و ذخیره کنید.
> 
> یه نسخه باگ فیکس جدید میزنم که از بوجود اومدن این مشکل جلوگیری کنه. ولی حداقل ایرادش اینه که ترافیک اون ۱۰ ثانیه کاربر حساب نمیشه دیگه. پس بهتره ایمیل کاربر رو تغییر ندید. در صورت لزوم، حتما قبلش غیرفعال شده باشه.

ترافیک حداکثر کاربر در این ۱۰ ثانیه حداکثر میتونه ۲۰ مگابایت و در این حدود میتونه باشه و زیاد مهم نیست

**Comment by alireza0** [comment]
دوتا تغییر دادم برای این مشکل:
۱. ترافیک هایی که ایمیلشون توی جدول ترافیک موجود نیست ثبت نشه!
[remove traffics of edited emails](https://github.com/alireza0/x-ui/commit/6a18ba48aac4d451e6a69dca2e78ed536b024c66)

۲. ترافیک هایی که ایمیلشون توی جدول inbound ها نیست حذف بشه! ( مشکلات اومده از پنل های دیگه ) یعنی قبلا کاربر حذف شده ولی ترافیکش مونده.
[[migration] Remove Orphaned Traffics](https://github.com/alireza0/x-ui/commit/fb1524803024521c61865c75a48906df48873a58)
