### ISSUE TITLE
کپی اتوماتیک مشخصات پنل در کانفیگ 

### ISSUE THREAD

**Issue by Morghak963** [alireza0/x-ui#196]
سلام مهندس جان
خسته نباشید و عرض خداقوت بابت تلاش هاتون 
مهندس عزیزم همینطور که در آپدیت های اخیر قابلیت کپی سرت از پنل در کانفیگ رو اضافه کردید 
اگر بتونید این رو برای sni هم اضاف کنید عالی میشه
چون معمولا در کانفیگ های روتین همون ساب دامین پنل رو که روش ssl فعال هست جای sni کپی میشه خصوصا در کانفیگ هایی که متصل به کلادفلر هست

**Comment by alireza0** [comment]
درود بر شما
درخواست شما شخصیه و تنظیمات رو شلوغ میکنه. بهتره دستی اضافه کنید
