### ISSUE TITLE
تغییر آدرس در کانفیگ خروجی

### ISSUE THREAD

**Issue by DrSaeedHub** [alireza0/x-ui#198]
درود بر شما مهندس عزیز
خواستم ایده ای بدم که نمیدونم قابل اجراست یا خیر و اونم اینه که اگر ممکنه به قسمت اینباند ها یه فیلدی اضافه بشه که توی اون فیلد یه 
دامین به دلخواه بنویسیم و موقع خروجی گرفت از کانفیگ یا در لینک سابسکریپشن اون دامین جای آدرس سرور بیاد
برای این میگم که من مثلا میخوام لینک سابسکریپشن بدم به کسی و از سی دی ان استفاده میکنم ، توی تنظیمات اینباند sni و request host رو تنظیم میکنم اما در کانفیگ خروجی ، آدرس همچنان آدرس خود سرور هست در صورتی که باید ساب دامینی باشه که برای آیپی تمیز کلاد فلیر استفاده میشه و خب درحال حاضر کاربر مجبوره بعد از هر آپدیت ساب زدن خودش به صورت دستی قسمت آدرس رو عوض کنه.
ممنون بابت تمام زحمات❤️

**Comment by alireza0** [comment]
این ویژگی رو توی تنظیمات tls/xtls با عنوان domain name داریم.
![image](https://user-images.githubusercontent.com/12573084/231745248-ca4f0bce-c2d9-4fdd-a303-1982f2249e93.png)
