### ISSUE TITLE
حجم مصرفی هر یوزر

### ISSUE THREAD

**Issue by aliabsharii** [alireza0/x-ui#199]
![Untitled](https://user-images.githubusercontent.com/128394863/231732838-a7dfe010-256a-468c-97ba-44452c88159e.png)
حجم یوزرارو نشون نمیده

**Comment by aliabsharii** [comment]
کانفیگ 100 مگی ساختم تا الان 500 مگ دانلود کردم قطع نکرده از کانفیگ اصلی حجم میگیره لطفا بررسی کنید تشکر

**Comment by MHSanaei** [comment]
قسمت لاگ صفحه اصلی پنل ببینید کدوم اکانت record not found زده اونو حذف کنید

**Comment by alireza0** [comment]
دوست عزیز @aliabsharii 
اطلاعاتتون ناقصه
لطفا سوالات در نظر گرفته شده در شروع ایجاد issue رو جواب بدید تا بتونیم بهتر راهنمایی کنیم و اگر مشکلی هست متوجه بشم.
نسخه استفاده شده
تنظیمات
آخرین لاگ ها

**Comment by sajjad5221** [comment]
> 

این مشکل چرا به وجود میاد؟ من هربار میرم پاک میکنم اکانتی که این خطا رو داده ولی باز هم این خطا رو نمایش میده

**Comment by sajjad5221** [comment]
> قسمت لاگ صفحه اصلی پنل ببینید کدوم اکانت record not found زده اونو حذف کنید

این مشکل چرا به وجود میاد؟ من هربار میرم پاک میکنم اکانتی که این خطا رو داده ولی باز هم این خطا رو نمایش میده

**Comment by alireza0** [comment]
تنظیمات اشتباه، و باگهایی که توی پنل‌های قدیمی مدیریت نشدن.
مدیریتشون توی بروزرسانی های جدید مشکلاتشون رو نشون میده

**Comment by sajjad5221** [comment]
> تنظیمات اشتباه، و باگهایی که توی پنل‌های قدیمی مدیریت نشدن. مدیریتشون توی بروزرسانی های جدید مشکلاتشون رو نشون میده

راهی هست که بشه این مشکل حل کرد؟( به جز پاک کردن اون اکانت) چون وقتی اکانت پاک میشه مشکل از بین میره ولی برای یه اکانت دیگه ممکنه این مشکل به وجود بیاد. و همین هم مثل اینکه باعث این میشه که مدیریت حجم مصرفی درست کار نکنه

**Comment by alireza0** [comment]
در نسخه جدید این مهاجرت ها در نظر گرفته شده و ایرادها با اولین استفاده حل میشه.
