### ISSUE TITLE
مشکل در نمایش ترافیک

### ISSUE THREAD

**Issue by iamfarhad** [alireza0/x-ui#200]
سلام

وقت بخیر

از اخرین ورژن دارم استفاده میکنم اما توی نمایش ترافیک کلاینت ها مشکل داره
اگه یک اینباند ۱۰ تا کلاینت داشته باشه فقط اولی رو نشون میده اونم اشتباه

من یوزر دارم حداقل ۲ گیگ مصرف کرده اما کیلوباید نمایش میده

![Screenshot_20230413_150555_Chrome](https://user-images.githubusercontent.com/1936147/231747312-0c477053-f679-43d8-af13-d0c90321ebe8.jpg)

**Comment by alireza0** [comment]
درود
پنل توی ترافیک هیچ دستکاری نمیکنه و هرچی بهش داده میشه رو ذخیره و نمایش میده.
لطفا لاگ ها رو بررسی کنید.

**Comment by iamfarhad** [comment]
مشکل میتونی از این باشه که از پنل کافکا مایگریت کردم؟

**Comment by alireza0** [comment]
مهاجرت بین پنل ها زیاد جالب نیست و مطمئنا عواقب داره، ولی خوبیش اینه که قابل حله.
میتونه از تنظیمات باشه.
بعضی از دوستان، کاربرهاشون رو از اول میسازن تا همه چی مرتب جلو بره.

**Comment by iamfarhad** [comment]
جالبیش اینکه که کاربر های جدیدی که ساختم هم‌این مشکل رو دارن
