### ISSUE TITLE
Nekoray issues 

### ISSUE THREAD

**Issue by herecOward** [alireza0/x-ui#204]
سلام توی اپدیت جدید کانفیگ هایی که می‌سازم برای نرم افزار های واسطه کانفیگ توی ویندوز مثل nekoray جواب نمیده و وصل نمیشه. دامین بجای ایپی عددی ثبت هست برای سرور من . کانفیگ ها توی گوشی بدون مشکل وصل میشه اما توی سیستم بعد از زدن روی vpn mode و استارت کردن کانفیگ نت کلا قطع میشه. مشکل چیه ؟

**Comment by dev-ir** [comment]
دلایل زیادی داره که کلاینت هایی مثل Nekoray جواب ندن از ساعت و تاریخ سیستم میتونه باشه تا خیلی از موارد دیگه

اگر هم میخواهید کانفیگ هاتون با دامنه باشه و ای پی نباشه کافیه با دامنه وارد پنل بشید تا کانفیگ ها با دامین خودتون بسازه
