### ISSUE TITLE
قابلیت محدود سازی آی پی

### ISSUE THREAD

**Issue by hooman0711** [alireza0/x-ui#207]
سلام. این پنل قابلیت محدود سازی تعداد آی پی متصل به هر کلاینت رو نداره؟

**Comment by Morghak963** [comment]
سلام خیر

**Comment by dev-ir** [comment]
این یک موضوع به نظرم لازمه بشه کلاینت لیمیت کرد بر اساس ای پی اما

**Comment by alireza0** [comment]
قابلیت های محدود سازی مغایر سیاست کلی نرم افزار بوده و خود xray-core چنین امکانی نداره.

https://github.com/alireza0/x-ui/issues/68#issuecomment-1471839859
