### ISSUE TITLE
افزودن حل کپچا به صفحه ورود برای افزایش امنیت

### ISSUE THREAD

**Issue by Morghak963** [alireza0/x-ui#208]
![IMG_20230414_142410_539](https://user-images.githubusercontent.com/127750712/232027110-40668719-fbe8-46b9-b302-55664141979c.jpg)

سلام 
مهندس جان این عکس رو ببینید
یک پنل چینی دیدم که در گروهش مدعی شده بود که در نسخه بعدی قابلیت کپچا رو به صفحه لاگین اضافه میکنه
و این خودش خیلی میتونه کمک کننده باشه برای جلوگیری از یکسری حملات به پنل که بصورت رباتیک انجام میشه و با اسکریپت های مخصوص

لینک گین هاب پنل
https://github.com/sing-web/x-ui

لطفا در صورت امکان یک بررسی بفرمایید قابلیت خوبی هست

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از لطفتون
اصولا این موضوع مربوط به وب سایت هایی میشه که به صورت عمومی باز هستند.
شما میتونید کل این وب رو ببندید بدون اینکه برای اتصالات مشکلی بوجود بیاد. برای امنیت شما میتونید مدلهای خیلی زیادی رو پیاده سازی کنید که موضوع اصلی پنل نیست.
اولویت من سادگی و سبک بودن پنله.
