### ISSUE TITLE
آدرس کانفیگ

### ISSUE THREAD

**Issue by hamed0mh** [alireza0/x-ui#212]
توی کانفیگ اگه  tls رو فعال کنیم میتونیم Domain name  رو تغییر بدیم و توی آدرس کانفیگ همون رو نمایش میده

ولی اگه  tls  **غیر فعال** باشه دیگه نمیشه Domain name  رو تغییر داد

اگه این فیلد رو توی قسمت ساخت کانفیگ پنل بزارین دیگه مجبور نیستیم برای ساخت اکانت ، دوباره توی کانفیگ خروجی اصلاح آدرس بزنیم
.
 
فعلا سبکی که جواب میده ip تمیز هست و مجبوریم برای هر کانفیگ تغییر توی آدرس بدیم

**Comment by alireza0** [comment]
پنلتون ر‌و با دامینی که میخواید لینک بر اساس اون درست بشه باز کنید.
