### ISSUE TITLE
اضافه کردن بخش Flow در Add Bulk

### ISSUE THREAD

**Issue by aliabsharii** [alireza0/x-ui#213]
سلام خسته نباشید اگه این قابلیت رو تو بالک ادد هم اضافه کنید ممنوتون میشم برای tles xtless

**Comment by aliabsharii** [comment]
![IMG_20230415_135920](https://user-images.githubusercontent.com/128394863/232208638-5312f978-247d-471f-b190-50369353c449.jpg)

**Comment by aliabsharii** [comment]
![IMG_20230415_140504](https://user-images.githubusercontent.com/128394863/232208923-42495edd-ce0f-424e-83e8-d206a7b09856.jpg)

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و پیشنهادتون
در نسخه بعد حتما اضافه خواهد شد
