### ISSUE TITLE
امکانات اختصاصی

### ISSUE THREAD

**Issue by mhosseint** [alireza0/x-ui#215]
سلام وقت بخیر
دوست عزیز میخواستم بپرسم برای پنل x-ui اگر امکانات اختصاصی بخواهیم میتونید بهش اضافه کنید و هزینش رو تقدیمتون کنیم؟
لطفا در این صورت id تلگرام جهت ارتباط بیشتر ارسال بفرمایید.

**Comment by dev-ir** [comment]
چه امکاناتی شاید به درد خورد در نسخه اضافه بشه

**Comment by mhosseint** [comment]
پنل آقای صناعی عزیز (3x-ui) چون باگ و مشکلات زیادی داره بنده نمیخوام از اون استفاده کنم و امکاناتی که خدمتتون عرض میکنم رو میخواستم روی این پنل داشته باشم.
۱- محدودیت تعداد کاربر و اتصال میخواستم که دقیق هم کار کند.
۲- خود صفحه لاگین پنل میخواستم ویرایش بشه و با ظاهر داخل پنل مطابقت داشته باشه
۳- گزینه email میخواستم به name تغییر کند.
۴- میخواستم از ورژن های قدیمی xray هم به پنل اضافه بشه
۵- میخواستم امنیت پنل کمی تقویت بشه اینکه اگر هرکس به پنل لاگین کرد برای همیشه همونجا لاگین نمونه و مثلا با تغییر پورت پنل یا رمز پنل نشست ها غیرفعال بشه و مجدد نیاز به ورود داشته باشه و اینکه مثل اکثر سایت ها مدت خاصی نشست لاگین بمونه و بعد اون مدت از لاگین خارج بشه
۶- بنده میخواستم قابلیت Auto reset traffic داشته باشیم که برای هر کاربر تاریخ دوره اون رو مشخص کنیم.
۸- یه ویژگی دیگه اینه مثلا یک اسمی برای Inbound بزاریم و بعد هر اسمی که برای کاربر ها مشخص میکنیم بعد از اسم اصلی Inbound داخل کد اضافه بشه
۷- و نهایتا قابلیت دیگه ای میخواستم این هست که بتوانم برای هر کابر دامنه خاص مشخص کنیم به طوری وقتی کد کانفینگ رو دریافت میکنیم کد اون کاربر با اون دامنه مشخص شده باشه

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و پیشنهاداتتون
این پنل رایگان ارائه میشه و برای مقاصد تجاری مناسب نیست.
من سعی میکنم درخواست هایی که ساده و عمومی هستند رو اضافه کنم.
به درخواست هایی که از طریق issues و ایمیل ارسال میشه تا انداره ای که بتونم و بلد باشم جواب میدم.
