### ISSUE TITLE
Multiple port for 1 inbound

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#216]
سلام، چطور میتونم دوتا پورت رو برای یک inbound فعال کنم؟ اگر ممکن نیست لطفا این قابلیت رو اد کنید برای زمانی که رو یه پورت خاص اختلال هست میشه از پورت دیگه استفاده کرد.

**Comment by alireza0** [comment]
درود بر شما
میتونید از قابلیت fallback استفاده کنید.
لطفا در موردش مطالعه کنید و بعد اجرا کنید

**Comment by alireza0** [comment]
این ویژگی فقط برای vless و  trojan روی شبکه tcp و tls فعال میشه
