### ISSUE TITLE
افزودن هدر subscription-userinfo به لینک سابسکریپشن

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#217]
سلام، لطفا هدر subscription-userinfo رو به لینک سابسکریپشن اضافه کنید، نرم افزار هایی مثل Nekoray و برخی از دیگر کلاینت ها ساپورتش میکنن، برنامه نویس ها هم میتونن ازش استفاده کنن برای ساخت ابزار جانبی
`subscription-userinfo: upload=125829120;download=926941184;total=107374182400000;expire=1704067200`
تو بخش دانلود/آپلود میزان مصرف فعلی کاربر به byte نوشته شده، قسمت total هم میزان کل حجم، تو expire هم تاریخ اتمام اعتبار بصورت unix timestamp هست، اگر تاریخ اعتبار بینهایت بود میشه 0 گذاشت جاش، برای یوزر هایی که هنوز شمارش اعتبار شون شروع نشده میشه هم میشه تاریخ اتمام در صورت شروع رو گذاشت

**Comment by alireza0** [comment]
یه مشکلش اینه که ممکنه یه لینک شامل چند تا اکانت مختلف باشه.
اینجوری محاسبه تاریخ انقضا سخته

**Comment by alireza0** [comment]
میتونم روش کار کنم.
ایده خوبیه.
اگر تاریخ های انقضا مشابه بود هم میشه اضافه کرد.

**Comment by alireza0** [comment]
اضافه شد!
منتظر ریلیز جدید باشید

**Comment by alireza0** [comment]
این هدر رو الان نرم افزارهای دیگه هم ساپورت میکنن و هرکدوم به شکل خودشون نمایش میدن.
لطفا اگر مستنداتی دارید لینکش رو برای من بگذارید

**Comment by alireza0** [comment]
بر اساس [این مستند](https://github.com/crossutility/Quantumult/blob/master/extra-subscription-feature.md) تنظیم شد

**Comment by Prot0nX** [comment]
آقا این کاربردش کجاست چجوری میشه ازش استفاده کرد؟
راهنمایی کنید برا این قابلیت

**Comment by omidmir88** [comment]
چجوری این قابلیت فعال کنیم ؟ تو قسمت sub باید  چیزی نوشته بشه ؟
