### ISSUE TITLE
بهینه کردن پنل با استفاده از API جدید

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#218]
سلام، با توجه به اینکه API ساختید برای پنل که خیلی هم خفنه، اگر از همین برای پنل وب هم استفاده کنید خیلی بهتر میشه، چون در حال حاضر برای ساخت یه یوزر جدید باید دیتای کل inbound رو توی یک پکت بزرگ ارسال کنیم به سرور! که خیلی عجیبه

**Comment by alireza0** [comment]
درود بر شما
دیتای پنل و API یکی هستند!

**Comment by alireza0** [comment]
نه متاسفانه.
فعلا اینجوری نیست.
ساختار دیتابیس برای اینکار درست نیست.
تللش کردم جدا کنم، ولی درست کار نمیکنه.
شاید توی نسخه های بعدی درستش کردم.

**Comment by alireza0** [comment]
دارم روش کار میکنم.
اگر اوکی شد اضافه میکنم به نسخه جدید.

**Comment by alireza0** [comment]
اضافه شد.
منتظر نسخه جدید باشید.

**Comment by aliaasl** [comment]
سلام دوست عزیز ممنون از بایت این تغییر
فقط فکر کنم برای اضافه کردن و ویرایش کلاینت این تغییر اعمال شده، ممنون میشم برای حذف کلاینت هم اعمال کنید

**Comment by alireza0** [comment]
حذف کلاینت دیتا نمیخواد!

**Comment by aliaasl** [comment]
من همین الان هم تو پنل تست کردم، موقع حذف کلاینت تو بادی شناسه inbound و لیست کلاینت ها داره ارسال میشه، یعنی میگید میشه که بادی رو خالی ارسال کرد؟

**Comment by alireza0** [comment]
بله من اشتباه کردم.
الان یادم اومد که مشکل داشتم با اینکه کلاینت هایی که ایمیل ندارند نمیشه پاکشون کرد.
فعلا باید برای اینکه باگ نداشته باشیم همینجوری باشه.
استفاده از index هم خودش مشکل داره.
میتونم تبدیلش میکنم به inbound_id

**Comment by alireza0** [comment]
بدون نیاز به دیتا، تصحیح شد:
```
"/:id/delClient/:index"
```

**Comment by alireza0** [comment]
متاسفانه این پنل برای این مدل کارها مخصوصا چند کاربره بودن طراحی نشده.
هیچ راه بهتری نداریم در حال حاضر.
فیلد UID برای trojan وجود نداره.
فیلد ایمیل هم اجباری نیست!
هیچ چاره ای نداریم.
نمیشه همه چیز رو فدای خواسته ای کرد که اصلا پنل نمیتونه ارائه بده.
متاسفانه تست دیتا توی backend اصلا‌اضافه نشده و فقط frontend میتونه دیتای درست رو بفرسته. پس API حتما باید این تست ها رو قبلش انجام بده.
اضافه کردن تست فیلد ها برای backend هم اصلا جزو اهداف نیست.
در واقع این پنل برای راحت شدن کار تنظیم xray-core نوشته شده و حتی ارائه API هم اصلا کار درستی نیست.
کسی که میتونه api بزنه، بهتره با خود xray-core به صورت مستقیم کار کنه.

**Comment by alireza0** [comment]
مجددا تصحیح شد:
```
"/:id/delClient/:clientId"
```
برای trojan ، فیلد clientId  باید شامل password باشه و برای vmess  و vless ، این فیلد رو با UID پر کنید.
فیلد id هم که باید inbound id باشه

**Comment by staliox** [comment]
> مجددا تصحیح شد:
> 
> ```
> "/:id/delClient/:clientId"
> ```
> 
> برای trojan ، فیلد clientId باید شامل password باشه و برای vmess و vless ، این فیلد رو با UID پر کنید. فیلد id هم که باید inbound id باشه

xui/API/inbounds/1/delClient/5d3d1bac-49cd-4b66-8be9-a728efa205fa

404 error

**Comment by aliaasl** [comment]
خدا خیرت بده برادر
ان شا الله که هم برا edit هست هم برای delete

________________________________

**Comment by alireza0** [comment]
> xui/API/inbounds/1/delClient/5d3d1bac-49cd-4b66-8be9-a728efa205fa

متد رو دقت کنید حتما POST باشه


> خدا خیرت بده برادر ان شا الله که هم برا edit هست هم برای delete

برای بروز رسانی بعدی میرسونمش

**Comment by alireza0** [comment]
> پست هست

```
xui/API/inbounds/1/delClient/3f73c1b8-b38f-474d-f4b2-be3d2137e720

{
"success": true,
"msg": "Client deleted Success",
"obj": null
}
```
همه مدله تست کردم و درست بوده. لطفا از صحت اطلاعات ارسالی تون مطمئن بشید.

**Comment by alireza0** [comment]
متد Update هم آماده شد.
با نسخه بعدی ارائه میشه.
