### ISSUE TITLE
favicon leak

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#219]
سلام، من path پنل رو عوض کردم، وقتی سایت رو با پورت پنل باز میکنم بدون path باز میکنم، به درستی ارور 404 میده، اما مشکل اینه که favicon مربوط به x-ui نشون داده میشه که باهاش میشه فهمید که رو این سرور پنل x-ui نصب هست
![image](https://user-images.githubusercontent.com/41063376/232345224-29efccfb-c6b8-4b4a-92b1-41692edf158d.png)

**Comment by alireza0** [comment]
درود بر شما
بهتره این کار رو با nginx یا مدلهای reverseproxy دیگه درست کنید.

**Comment by alireza0** [comment]
به صورت کلی favicon از روت وبسایت دیده میشه نه روت  path
