### ISSUE TITLE
محاسبه ترافیک کاربر در داکر

### ISSUE THREAD

**Issue by trytopassgfw** [alireza0/x-ui#220]
من از نسخه داکر 0.5.2 استفاده کردم و به پنل یک outbound دستی اضافه کردم. روند به صورت کلی درست کار میکنه ولی حجمی که استفاده میشه برای کاربر محاسبه نمیشه. از طرفی داخل صفحه اصلی پنل، حجم اضافه میشه.
این اخطار هم داخل لاگ‌ها هست.
 WARNING - get xray traffic failed: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"

**Comment by alireza0** [comment]
[اینجا](https://github.com/alireza0/x-ui/issues/58) توضیح داده بودم که مشکل از شبکه داکر روی سرورتونه.

> پیشنهاد من اینه که از حالت `--network=host` در بیاری و یکی یکی پورتها رو map کنی. مثال زیر پورت های 80 و 443 رو به علاوه 54321 به کانتینر میفرسته


```
docker run -itd \
    -p 54321:54321 -p 443:443 -p 80:80 \
    -e XRAY_VMESS_AEAD_FORCED=false \
    -v $PWD/db/:/etc/x-ui/ \
    -v $PWD/cert/:/root/cert/ \
    --name x-ui --restart=unless-stopped \
    alireza7/x-ui:latest
```

**Comment by trytopassgfw** [comment]
این کار رو انجام دادم.
پورت های 80و443و62789و54321و53 رو مپ کردم.
```
    {
      "listen": "0.0.0.0",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "0.0.0.0"
      },
      "sniffing": null,
      "streamSettings": null,
      "tag": "api"
    }
```
 
متغیرهای listen و  address رو هم هم 0.0.0.0 و هم 127.0.0.1 تست کردم.
از ایمیج teddysun/xray که استفاده میکردم باید inbound  رو 0.0.0.0 ست میکردم تا کار کنه.
فقط این رو XRAY_VMESS_AEAD_FORCED ست نکردم که چون vless میخوام ران کنم نیازی ندیدم.

**Comment by alireza0** [comment]
چون xray-core و x-ui توی یک کانتینر میاد بالا، نیازی به مپ کردن پورت 62789 و تغییر این سرویس ندارید
ولی به هر حال باید درست کار کنه.

ایمیج های xray فقط شامل xray-core هستند و متفاوت تنظیم شدن!

لطفا دقیق تر بنویسید چطور اجرا کردید که بتونم توی شرایط مشابه تست کنم

**Comment by trytopassgfw** [comment]
من دارم از سرویس دهنده pass (همروش) استفاده میکنم.
ایمیج ورژن 0.5.2 رو  ران کردم.
تمام پورت ها رو هم از تنظیمات پنل مپ کردم.
برای تانل هم از outbound استفاده کردم.
این اخرین تنظیمات inbound من هست.
```
"inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "0.0.0.0"
      },
      "sniffing": null,
      "streamSettings": null,
      "tag": "api"
    },
    {
      "listen": null,
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "email": "hmbe",
            "flow": "",
            "id": "3f6bcda1-....-1023a4558fb2"
          },
          {
            "email": "test",
            "flow": "",
            "id": "fb02009f-.....-1b9a15fadc70"
          }
        ],
        "decryption": "none",
        "fallbacks": []
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "acceptProxyProtocol": false,
          "headers": {},
          "path": "/"
        }
      },
      "tag": "inbound-443"
    }

```
برای outbound هم 
```
"outbounds": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": ".........",
            "port": 443,
            "users": [
              {
                "encryption": "none",
                "id": "9.....................fc5"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "serverName": "...................."
        },
        "wsSettings": {
          "headers": {
            "Host": "....................."
          },
          "path": "................."
        }
      },
      "tag": "out_443"
    }
  ]
```
با routing هم in و out رو مدیریت میکنم.

**Comment by alireza0** [comment]
منظور من روش اجرای داکر بود

**Comment by trytopassgfw** [comment]
راستش کار خاصی من نمیکنم. پشت سرویسی که ران میشه kubernet هست. من فقط میتونم از طریق پنل دسترسی داشته باشم. پورتها، env و امثال این ها رو ست کنم. خودش ایمیج رو میگیره و ران میکنه.

**Comment by alireza0** [comment]
این نرم افزار و ایمیج برای استفاده در Kubernetes مناسب نیست
