### ISSUE TITLE
دیدن لاگ در داکر

### ISSUE THREAD

**Issue by trytopassgfw** [alireza0/x-ui#222]
وقتی که داخل پنل داکر با نسخه 0.5.2 روی log میزنم این ارور رو میده:
Fail: exec: "journalctl": executable file not found in $PATH

**Comment by alireza0** [comment]
مشکل در مدل شبکه host میتونه باشه.
https://github.com/alireza0/x-ui/issues/58#issuecomment-1472043171

**Comment by trytopassgfw** [comment]
من ۴تا پورت 80و443و54321و53 رو دستی map کردم.
ولی تنظیمات host رو نمیدونم چجوری باید تغییر بدم.

**Comment by alireza0** [comment]
من درست متوجه نشده بودم. عذر میخوام.
دکمه لاگ فقط برای سرورهای لینوکس که journalctl دارند، اطلاعات درستی میاره.
برای داکر نمیتونید از این گزینه استفاده کنید.
