### ISSUE TITLE
نمایش یوزر ها در چندین صفحه و قابلیت چینش

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#223]
سلام
وقتی تعداد زیادی یوزر اد میشه توی یه inbound و مدیر وارد بخش یوزر ها میشه
مرورگر خیلی سنگین کار میکنه و اکثر قابلیت های موجود از کار میافته
اگر یوزر ها توی چندین صفحه مجزا نمایش داده بشن خیلی بهتره
و اینکه قابلیت sort کردن هم اگر باشه خیلی بهتره، تا از این طریق بشه یوزر هایی که تایم یا حجم کمتری از اشتراک شون مونده رو ببینیم به ترتیب
تشکر

**Comment by alireza0** [comment]
درود بر شما
مدل این پنل این امکان رو نداره. همه دیتای کاربرها اول لود میشه و با هر تغییری دوباره همه اطلاعات بازخوانی میشه
امکان جستجو به همین دلیل اضافه شد که نیازی به چند صفحه شدن و چیدمان نداشته باشیم.
این امکانات تست شده و به دلیل قدیمی بودن نسخه فرانت اند، بسیار نامطلوب میشه
