### ISSUE TITLE
Minify / Compress JSON

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#225]
سلام
اگر دیتا هایی که ادمین از پنل دریافت میکنه و میفرسته رو Minify کنید ارتباط ادمین با سرور خیلی سریعتر و بهتر میشه
حجم دیتابیس هم نصف میشه اگر به همونصورت دیتا ذخیره شه تو دیتابیس
اگر هم قابلیت gzip, deflate فعال شه که خیلی بهتر هم میشه

**Comment by alireza0** [comment]
درود بر شما
محاسباتتون کمی دقیق نیست. این پنل بسیار ساده تر از اونه که لازم باشه براش فشرده سازی رو فعال کرد.
بزرگترین دیتابیسی که یکی از کاربرها فرستاد، ۱.۱ مگ بود.
