### ISSUE TITLE
Upgrade the API

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#231]
درود
1 - در حال حاضر updateClient در API هست که زیاد به کار ماها نمیاد چون با index کار میکنه
لطفا یچی مشابه بزارید که بر اساس Email و UUID/Password کار کنه
البته چون پسورد تروجان میتونه با ایمیل یکی از کاربرا یکی باشه باید دوتا متد متفاوت براشون باشه

"/updateClient/index/:index"
"/updateClient/email/:email"
"/updateClient/identifier/:uuid-or-passwd"

2 - دریافت اطلاعات کاربر خاص / getClient با استفاده از Index/UUID/Password

3 - حذف یوزر با استفاده از UUID/Password

با تشکر

**Comment by alireza0** [comment]
درود بر شما
میتونید اطلاعات رو یکبار بگیرید و جستجو رو سمت خودتون انجام بدید و بعد بر اساس اونها، درخواست رو بفرستید.
