### ISSUE TITLE
[BUG] Multiple users with same UUID/Password!

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#232]
سلام
در حال حاضر میشه چندین یوزر با UUID/Password یکسان ساخت!
وقتی دوتا یوزر با UUID/Password یکسان ساخته میشه فقط حجم برا یکی شون نوشته میشه

**Comment by alireza0** [comment]
درود بر شما
لطفا اطلاعات بیشتر از جمله نسخه رو اعلام کنید
