### ISSUE TITLE
اد نشدن کانفیگ ریلیتی در برنامه wings

### ISSUE THREAD

**Issue by hamihastam** [alireza0/x-ui#233]
کانفیگ توی برنامه وینگز ایفون اد نمیشه و ارور میده.
![IMG_0682](https://user-images.githubusercontent.com/120744411/233009641-f7ca4b97-df53-4485-beb0-801352124cdd.jpeg)
![IMG_0683](https://user-images.githubusercontent.com/120744411/233009661-2b5e560f-639b-4ce2-b91d-c06d13b83adc.jpeg)
![IMG_0684](https://user-images.githubusercontent.com/120744411/233009673-fbe5439f-8bad-462b-a8ff-792d3220cfa4.jpeg)

**Comment by ircfspace** [comment]
توی v2Box البته اد میشه به راحتی

**Comment by hamihastam** [comment]
سرعتش خیلی بده v2box

**Comment by alireza0** [comment]
تصحیح شد. لینک : [[reality] fix fingerprint issue](https://github.com/alireza0/x-ui/commit/7fec1dd5cf56c74bd7babac1381b913f711c7194) https://github.com/alireza0/x-ui/issues/236
