### ISSUE TITLE
امکان حذف شدن خودکار کلاینت ها

### ISSUE THREAD

**Issue by ach1992** [alireza0/x-ui#234]
سلام
لطفا امکانی در نظر بگیرید کلاینت هایی که 3 روز از تاریخ انقضا اونها می گذرد بشود خودکار حذف شوند (اینکه 3 روز باشد یا یه عدد دیگه رو بشه مثلا توتنظیمات تعیین کرد)
مهمه که بر اساس تاریخ انقضا باشه و نه حجم
البته میشه فیچر حذف اکانت در صورتی که حجم تموم شده بود هم گذاشت که به نظرم لازم نیست
با تشکر از شما

**Comment by razikazeminezad** [comment]
سلام این پیشنهاد خیلی خوبه ولی اگر تمامی کلاینت های فعال از تمامی کلاینت های غیر فعال کلا جدا بشن (در تب های متفاوت) خیلی عالی تر میشه و حتی بشه روی کلاینت ها عمل های گروهی انجام داد عالی میشه

**Comment by alireza0** [comment]
این امکان به صورت دستی در پنل تعبیه شده.

**Comment by ach1992** [comment]
> این امکان به صورت دستی در پنل تعبیه شده.

نه دیگه مشکل اینه که دستی یا میشه همه اونایی که تموم شده رو حذف کرد یا باید تک تک حذف کنی و نمیشه یه تعداد خاص با شرایط خاص رو مشخص کرد و حذف کرد.
من الان میخوام فقط اونهایی که 5 روز از تاریخ اتمامشون گذشته رو حذف کنم بین 300 تا اکانت تموم شده باید تک تک دنبال اینا بگردم و حذف کنم و راه دیگه ای نیست ممنون میشم فقط در صورتی که این امکان قرار نیست اضافه بشه issue رو close کنید در غیر اینصورت در نظر بگیرید که در آینده اضافه بشه 
با تشکر

**Comment by asadace1** [comment]
جناب علیرضای عزیز به این مورد همه نیاز داریم که پاک سازی و تمیز بشه
موقع ساختن اکانت به آپشن مثل auto renew برای این مورد باشه
مثلا auto remove تایم رو بزاریم رو ۳ روز که بعد از تمام شدن تایم اکانت، اکانت خودکار پاک بشه
تشکر
من الان دارم هر چند وقت یه بار با api پاک سازی میکنم اسکریپتی‌ نوشتم ک هر چند وقت بار باید اجرا کنم تا پاکسازی انجام بشه اگر میشد پنل خودکار پاک کنه عالی میشد
