### ISSUE TITLE
امکان نصب warp از طریق اسکریپت

### ISSUE THREAD

**Issue by ach1992** [alireza0/x-ui#235]
سلام 
لطفا امکانی رو ایجاد کنید که بشه با همین اسکریپت ورپ رو هم نصب کرد و مشکل سایت های مثل گوگل، chat gpt و این طور سایت ها حل بشه 
در صورتی که warp نصب شد کانفیگ xray به صورت خودکار ویرایش بشه و دیتای لازم اضافه بشه
همچین خیلی خوبه که بشه کل سایت های ایرانی رو به کمک ریپازیتوری iran hosted domain بلاک کرد که هیچ سایت ایرانی با VPN باز نشه
ممنون میشم اینارو بذارید تو برنامه 
با تشکر

**Comment by alireza0** [comment]
درود بر شما
اجرای warp باعث کم شدن کارایی سیستم میشه که پیشنهاد نمیکنم.
در مورد مشکلات ipv6 راه حل زیاده، ولی [این راه حل](https://twitter.com/ircfspace/status/1648613288261943298) رو بهتر میدونم.
امکانات سلیقه ای مثل بلاک کردن سایتها و ip های ایرانی به صورت on/off مد نظر من نیست. ولی به زودی یه راه حل جامع براش درست میکنم.

**Comment by aliaasl** [comment]
عرض سلام و خسته نباشید
مشکل خطای خود سایت گوگل با این روشی که در توییتر پیشنهاد شده بود حل میشه، اما متاسفانه برای من تو گوگل پلی هم نمیشه چیزی دانلود کرد! ممنون میشم اگر راهی برای حل این مشکل هست هم بفرمایید
