### ISSUE TITLE
باگ و رفع مشکل پنل

### ISSUE THREAD

**Issue by mhosseint** [alireza0/x-ui#237]
سلام وقت بخیر
تعدادی باگ در پنل هست که ممنون میشم لطفا برطرف بفرمایید:

۱- در بخش Panel Setting فیلد قسمت Panel Port کوچیک شده و دارای آیکون کم و زیاد کردن عدد هست که برای فیلد پورت این نباید وجود داشته باشه و همچنین اینکه الان پورت و عدد قابل تغییر و ویرایش نیست. وقتی هم از طریق ssh پورت رو تغییر میدیم پنل دچار مشکل میشود و دیگه کار نمیکند.

۲- در همان بخش Panel Setting فیلد های Exhaustion time threshold و Exhaustion traffic threshold کار نمیکنند و عدد آن قابل تغییر نیست. همچنین همین مشکل در فیلد CPU percentage alert threshold در بخش TG Reminder Related Settings نیز وجود دارد.

۳- یه مورد دیگری که وجود دارد البته باگ نیست ولی یک مشکل ظاهری هست که بهتره اصلاح بشه؛ در هنگام اضافه یا ویرایش کردن Inbound فیلد قسمت Transmission در یک ردیف نیست و وسط صفحه قرار میگیرد که ظاهر آن خوب دیده نمیشود و اغلب بنده گمش میکنم. اگر میشود یکم فیلد آن را به سمت چپ ببرید که با بقیه فیلد ها در یک راستا و ردیف قرار بگیرد خیلی عالی تر میشود.

باتشکر و سپاس فراوان

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و گزارشتون
انجام شد.
