### ISSUE TITLE
اضافه کردن امکانات

### ISSUE THREAD

**Issue by mhosseint** [alireza0/x-ui#239]
سلام وقت بخیر
چند مورد پیشنهاد ویرایش و اضافه شدن امکانات داشتم که ممنون میشم برسی بفرمایید:

۱- اگر امکان داشته ظاهرصفحه لاگین پنل رو با مطابق با ظاهر داخل ویرایش کنید که اون طرح سفید و آبی را داشته باشد و دیگه رنگارنگ نباشد خیلی زیبا میشود.

۲- لطفا در صورت صلاحدید گزینه email را name تغییر دهید چون اصلا پنل اصلی هم عنوانی به اسم ایمیل ندارد و صرفا نام کاربر است و همچنین اینکه این گزینه به اسم email کاربر اضافه کردن ایمیل ندارد و بهتر است به گزینه name تغییر کنید.

۳- اگر امکان داشته باشد که قابلیت Auto reset traffic داشته باشیم که برای هر کاربر و اینباند تاریخ دوره اون رو مشخص کنیم خیلی عالی میشود چون همانطور که اطلاع دارید ماهیت پنل بر همین اساس است و میزان ترافیک ها هم به صورت ماهانه تخصیص میشود و در این وضعیت فعلی مجبور هستیم هر ماه به صورت دستی آن را ویرایش کنیم.

۴- یه ویژگی مهم اینکه الان قابلیت Subscription وجود دارد اما مشکلی که هست لینک آن با هر آدرسی که وارد پنل شده باشیم قرار میگیرد و خوب شاید ما تمام open port های https را استفاده کرده باشیم و مخصوصا پورت 443 و دیگر پورتی برای قرار دادن پنل نداشته باشیم اما دامنه ssl داشته باشیم که بتواند با https باز شود. بنابرین اگر امکان داشته باشد بتوانیم برای Subscription درس دامنه مشخص خیلی خوب میشود. اینجوری یه دامنه مخصوص میزاریم که یه موقع فیلتر هم نشود و همیشه در دسترس باشد.

۵- لطفا گزینه reset all inbounds traffic به گزینه reset all inbounds & clients traffic تغییر کند چون اینکه به صورت کلی هست بهتر است همه ترافیک اینباند ها و کاربر ها را ریست کند. و کار هم راحت تر میشود و دیگر نیاز نیست برای هر اینباد یک بار هم دکمه ریست کاربران را وارد کرد.

۶- اگر بتوانیم برای هر کاربر دامنه خاص tls مشخص کنیم به طوری وقتی کد کانفینگ رو دریافت میکنیم کد اون کاربر با اون دامنه مشخص شده باشد اینجوری میتوانیم با یک پورت در چند دامنه مختلف کاربران را تقسط کنیم.

۷- اگر امکان داشت امنیت پنل کمی تقویت بشه اینکه اگر هرکس به پنل لاگین کرد برای همیشه همونجا لاگین نمونه و مثلا با تغییر پورت پنل یا رمز پنل نشست ها غیرفعال بشه و مجدد نیاز به ورود داشته باشه و مثل اکثر سایت ها مدت خاصی نشست لاگین بماند و بعد اون مدت از لاگین خارج شود.

از زحمات شما بابت توسعه پنل بسیار تشکر میکنم.

**Comment by alireza0** [comment]
درود بر شما دوست عزیز
از وقتی که گذاشتید و پیشنهادتون سپاسگزارم
مدت زمان زیادی روی این پیشنهادات کار شده و تقریبا همه اونهایی که میشد انجام بدیم رو انجام دادیم.
مواردی که نیاز به توضیح داره:
۲. پنل x-ui بیشتر کانفیگ های xray-core رو نمایش میده و اونجا فیلد email وجود داره و name وجود نداره. اضافه کردن فیلد name به نظر بهتر میاد.
۳. اطلاعات شما در مورد اساس ساخت پنل صحیح نیست و اضافه کردن ریست ماهیانه برای همه مناسب نیست.
۴. راهکار های زیادی برای این مدل ها وجود داره. از جمله استفاده از nginx .
۶. تنظیم tls مخصوص سرویس هست و برای هر کاربر نمیشه متفاوت باشه.

سپاسگزارم
