### ISSUE TITLE
editing a searched client is buggy

### ISSUE THREAD

**Issue by ariandcir** [alireza0/x-ui#24]
Hi team, when you have an inbound with multiple users, and you want to edit one that is not at the top of the list, after writing down the id of the user in the search bar, the panel would show the found options, when you try to edit one of the found options, it brings up the edit panel for the first user at the top of the list of the inbound instead of the user of interest.

**Comment by alireza0** [comment]
Thank you for your report.
It is fixed now and version 0.3.1 is rebuilded. Please update.
