### ISSUE TITLE
لطفا فرمان نصب دستی رو بزارین 

### ISSUE THREAD

**Issue by mostafacpr** [alireza0/x-ui#240]
لطفا دستور نصب دستی رو بزارین با تشکر

**Comment by trytopassgfw** [comment]
این؟
https://github.com/alireza0/x-ui#install--upgrade-to-latest-version

**Comment by mostafacpr** [comment]
آقا ممنون پیداش کردم 
cd /root/
rm x-ui/ /usr/local/x-ui/ /usr/bin/x-ui -rf
tar zxvf x-ui-linux-amd64.tar.gz
chmod +x x-ui/x-ui x-ui/bin/xray-linux-* x-ui/x-ui.sh
cp x-ui/x-ui.sh /usr/bin/x-ui
cp -f x-ui/x-ui.service /etc/systemd/system/
mv x-ui/ /usr/local/
systemctl daemon-reload
systemctl enable x-ui
systemctl restart x-ui
