### ISSUE TITLE
افزودن قابلیت ip limit

### ISSUE THREAD

**Issue by mhosseint** [alireza0/x-ui#241]
سلام وقت بخیر
آقا لطفا قابلیت ip limit رو اضافه کنید بخدا هیچ مشکلی نداره نمیدونم چرا این قابلیت به این مهمی رو حذف کردید؟
پنل 3x-ui خودش کلا باگ و مشکلات زیاد داره تمایل نداریم از اون استفاده کنیم. فقط اگه یه ip limit به پنل شما اضافه بشه عالی میشه
عدم وجود محدودیت کاربر باعث میشه از کانفینگ ها سوء استفاده بشه و مثلا برای یکبار که ۴۰ گیگ حجم برای مصرف خودش تعیین کردین در عرض چند روز تموم میشه و درخواست میکنه حجمش اضافه بشه که دیتاسنتر و سرور های ایران هم حجم اضافه نمیدن. درضمن متصل شدن تعداد زیاد کاربر به یک کانفینگ بار سرور رو شلوغ و سرعت رو پایین میاره کلا مشکل ساز هست.
خواهسا قابلیت ip limit رو اضافه کنید.

**Comment by ach1992** [comment]
ip limit
کلی باعث مصرف سی پی یو میشه به نظرم بهتره همون 3x-ui رو به توسعه دهنده بگید که رفع کنید و این پنل بمونه برای بدون محدودیت آی پی چون واقعا مصرف منابع رو تعداد یوزر بالا دردسر هست.
شما قیمت رو طوری بدید به مشتری که حجم اضافه می خرند سود باشه برای شما 
اصلا درستش هم همینه که شما دوست داشته باشی اونا بیشتر مصرف کنند که بیشتر بخرند!

**Comment by ach1992** [comment]
برای استفاده شخصی چه نیازی هست این پنل رو استفاده کنید؟
نسخه پنل هگزا یا همون اسدی یا نیدوکا رو نصب کنید اوکی هست و نیازی نیست این رو استفاده کنید اونها هم همه امکانات این رو دارند بجز این مواردی که مربوط به مدیریت دسته جمعی هست
نه اینطور نیست که تعداد کمتر وصل میشن cpu کاهش پیدا میکنه بلکه سیستم مجبور ریکوئست ها رو تک تک بررسی کنه و این باعث میشه cpu درگیر بشه و کلی مصرف منابع میره بالاتر و تقریبا چند برابر میشه

**Comment by razikazeminezad** [comment]
اتفاقا من از این پنل به عنوان تجاری استفاده میکنم
اگر قرار بر این باشه که ایپی لیمیت به سی پیو فشار بیشتر از 5 درصد وارد کنه نباشه بهتره از نظر من

**Comment by mhosseint** [comment]
نه آقا اونجوری که فکر میکنید بار cpu اضافه نمیشه. خود پنل اصلی HexaSoftwareTech این قابلیت رو داره و میبینید که هیچ فشاری هم رو سرور نیست.
دوست عزیز حالا اگر این قابلیت باشه چه فرقی به حال شما میکنه؟ شما غیرفعال کنید و استفاده نکنید. و هرکی هم نیاز داره استفاده بکنه

**Comment by razikazeminezad** [comment]
به نظرم چیز های بهتر و مهمتری از ایپی لیمیت هست مثلا سابسکریپشن لینک خیلی جا برا کار کردن داره مثلا پنل مرزبان یا هایدیفای واقعا خیلی پیشرفته تر هستن ولی من باهاشون حال نمیکنم خیلی خوب میشه اگه اضافه شه سابسکریپشن که کمی اوتوماتیک تر باشه و حجم برای هر سابسکریپت محاسبه شه
