### ISSUE TITLE
دسترسی به وب سایت های داخلی 

### ISSUE THREAD

**Issue by tebpna** [alireza0/x-ui#243]
با سلام 
اگر امکانش هست یه امکانی بزارید دسترسی به ای پی های داخلی را به صورت مستقیم ارسال کنه

**Comment by alireza0** [comment]
درود بر شما
اتصال مستقیم باید توی نرم افزار سمت کاربر تنظیم بشه نه سمت سرور.
سمت سرور هم میتونید با تنظیم route این کار رو انجام بدید
