### ISSUE TITLE
افزودن ریست کردن ترافیک به ویرایش کاربر

### ISSUE THREAD

**Issue by ach1992** [alireza0/x-ui#244]
سلام کاش به بخش ویرایش کاربرهم دکمه ریست ترافیک اضافه بشه
الان وقتی میخوای یکی رو ادیت کنی باید یکبار تاریخ رو ادیت بزنی و یکبار ترافیکش رو ریست کنی که کلی وقت میره سرش ولی اگر تو همون ادیت کلاینت باشه خب میشه هر دو رو باهم انجام داد
تصویر رو پیوست کردم که منظورم کجا هست
![image](https://user-images.githubusercontent.com/58507994/233314907-df1e1325-3fa1-4aff-944a-dba29ea188a1.png)

**Comment by mhosseint** [comment]
سلام اره واقعا به نظرم منم این گزینه واقعا نیازه و راحت تر میشه ترافیک رو هم ریست کرد. امیدوارم این حتما اضافه بشه

**Comment by alireza0** [comment]
درود بر شما
اضافه شد
