### ISSUE TITLE
افزودن چک باکس انتخاب چند کلایت و ویرایش یا حذف

### ISSUE THREAD

**Issue by ach1992** [alireza0/x-ui#245]
سلام
کاش یه چک باکس کنار هر کلاینت و کنار اینباند بود که میشد یکباره تعداد زیادی کلاینت رو انتخاب کرد و اعمال مختلف مثل حذف، ویرایش، ریست ترافیک و اینجور چیزا رو انجام داد
تو تصویر مشخص کردم که کجا هست منظورم
باتشکر
![image](https://user-images.githubusercontent.com/58507994/233315641-b497ca1c-74eb-4dc0-b4ef-84b548d5c61b.png)

**Comment by alireza0** [comment]
درود بر شما
درخواست های مشابه بوده. لطفا قبل از ایجاد درخواست به تاریخچه توجه کنید.

متاسفانه frontend framework استفاده شده خیلی قدیمیه و این امکان رو به ما نمیده.
