### ISSUE TITLE
مشکل توقف ایکسری

### ISSUE THREAD

**Issue by masoud-gb** [alireza0/x-ui#246]
وقت بخیر علیرضای عزیز خسته نباشی ممنون از زحماتت
در نسخه 0.5.2 هیچگونه مشکلی وجود ندارد اما با ابدیت به نسخه 1 بلافاصله ایکسری متوقف میشود.
با احترام

**Comment by alireza0** [comment]
وقت بخیر
لطفا لاگ سرور ( آیکون ؟ ) رو چک کنید
احتمالا:
۱. از xtls استفاده میکنید
۲. تنظیمات کاربر برای استفاده از flow های قدیمی وجود داره

**Comment by masoud-gb** [comment]
فرمودید چک کردم لاگ خاصی از ارور وجود نداره
xtls استفاده نمیکنم
flow قدیمی هم ندارم قربان

**Comment by alireza0** [comment]
وقتی xray با خطا متوقف میشه ، آیکون ؟ کنارش میاد. وقتی موس رو روش میبرید خطا رو نشون میده.
برای پیدا کردن flow ها میتونید config.json رو بررسی کنید

**Comment by masoud-gb** [comment]
سپاس از توضیحات چشم چک میکنم

**Comment by masoud-gb** [comment]
لاگ که فرمودید

**Comment by masoud-gb** [comment]
![Screenshot_20230420_155019_com android chrome_edit_610121051112631](https://user-images.githubusercontent.com/87688187/233368136-97418f7e-113f-4d48-8b88-28af8c099165.jpg)
 فایل لاگ که فرمودید

**Comment by masoud-gb** [comment]
> مشخصه دیگه، داری از فلو قدیمی استفاده میکنی فلو xtls-rprx-direct ساپورت نمیشه تو نسخه جدید Xray

اگر ممکنه بفرمایید چطور مشکل رو رفع کنم

**Comment by masoud-gb** [comment]
![Screenshot_20230421_075327_com android chrome_edit_642799768121707](https://user-images.githubusercontent.com/87688187/233540765-0b5b7b36-6dec-4729-97e0-d0577efd330d.jpg)
 دوستان این یوزرها توسط ربات ایجاد شده در اطلاعات xtls نوشته شده اما نه در اینبوند روشن شده و نه در کانفیگ گوشی میاد
من در کانفیگ بات فقط از vless و ws استفاده کردم بدن xtls 
ایا راهی برای حذف وجود داره تا بتونم پنلم رو ابدیت کنم به نسخه جدید 
با احترام

**Comment by alireza0** [comment]
میتونید inbound رو به tcp tls تغییر بدید و بعد flow هر‌ کاربر رو جداگونه تغییر بدید.
ولی بهتره دستکاری رو با نرم افزار های ویرایش دیتابیس انجام بدید

**Comment by masoud-gb** [comment]
سپاسگذارم چشم

**Comment by masoud-gb** [comment]
@alireza0 
این مشکل مربوط به رباتی میشه که به سرور متصل کردم اگر امکان داشت در ابدیتهای بعدی 1.75 به لیست ایکسری اظافه بشه من هم امکان استفاده از ابدیت رو پیدا میکنم 
با احترام 🙏🌹

**Comment by alireza0** [comment]
اضافه کردن این نسخه باعث مشکل توی پنل میشه.
توی نسخه بعد این flow ها در زمان نصب اتوماتیک حذف میشن

**Comment by masoud-gb** [comment]
بسیار عالی سپاسگذارم 🙏🌹
