### ISSUE TITLE
مشکل با آپدیت مرتبط با xtls-rprx-direct

### ISSUE THREAD

**Issue by ach1992** [alireza0/x-ui#249]
سلام وقتی پنل رو به ورژن آخر آپدیت کنیم یک سری یوزر قدیمی داشتیم که xtls-rprx-direct براشون تعریف شده بوده و چون روی 1.8.0و 1.8.1 انگار این دیگه وجود نداره پنل به مشکل میخوره 
مشکل اصلی اینه که الان روی پنل هیچ جوره نمیشه یوزر رو ادیت کرد و این بخشش رو پاک کرد که بعدش بتونیم ارتقا بدیم
ممنون میشم یه راه حلی برای این بگین که ما این چند تا یوزر رو ادیت کنیم و این بخش که تعریف شده رو حذف کنیم و جدید بدیم بهشون
حجمشون هم ریست نشه با این ادیت شدن (uuid دستی که میزنی حجم ریست میشه)
![image](https://user-images.githubusercontent.com/58507994/233460778-69529502-7b34-44b1-a36b-3bf18445570c.png)

با تشکر

**Comment by MHSanaei** [comment]
transmission ro ruie tcp bezarid flow baraie client faal mishe bad on client ro edit mikonid va flow ro ruie none mizarid

**Comment by masoud-gb** [comment]
اگر علیرضای عزیز در نسخه های جدید  ایکسری 1.75 رو هم قرار بدن مشکل رفع خواهد شد.
