### ISSUE TITLE
Deletion of users does stuff up the database schema

### ISSUE THREAD

**Issue by ariandcir** [alireza0/x-ui#25]
In my situation: I have an inbound with the following setting : vless + ws + tls. When I delete a user from this inbound, the panel does correctly try to enforce the proper DB schema on all the users of the inbound though it forgets to add "decryption": "None" for vless. hence I do get the error below after deleting users: 
Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: VLESS settings: please add/set "decryption":"none" to every settings

I would imagine similar situations might happen in other settings but I am not aware of as I do not deal with them

**Comment by alireza0** [comment]
Yesterday I replaced the lat version with fixed bug version. Did you update it?

**Comment by ariandcir** [comment]
yes I did

**Comment by alireza0** [comment]
Then you need to just edit the inbound and save it ( even without change )
And it will fix the problem. Isn't it?

**Comment by ariandcir** [comment]
Just tried saving the inbound with no changes and it worked, though is it a normal behaviour?

**Comment by alireza0** [comment]
No, it was about a bug in golang or modules which made some problems in last version.
This problem remained in your database till something like save changes in the correct way happens.
It is fixed now in last version and if any problem exists in databade from last version affetcs, it will fix it automatically by edit and save.

**Comment by alireza0** [comment]
@ariandcir New release is ready.
Please check and feedback.

Thanks again
