### ISSUE TITLE
addClient

### ISSUE THREAD

**Issue by mewhrzad** [alireza0/x-ui#250]
سلام مهندس لطفا در خصوص افزودن کاربر به inbound بیشتر توضیح بدید که چه پارامتر هایی لازم هست.

**Comment by ach1992** [comment]
برای افزودن کاربر شما تنها لازمه سه بخش زیر رو بر اساس نیازتون پر کنید:


Total flow(GB) 
Start after first use
Expire date


اولی حجمی هست که میخواهید یوزر داشته باشه
دومی برای اینه که بعد از اولین اتصالش زمان اکانت محاسبه بشه
و سومی هم زمان اکانت هست که چقدر تایم داره که استفاده کنه
اگر اینها رو تنظیم نکنید نامحدود در نظر گرفته میشه

**Comment by mewhrzad** [comment]
از طریق api باید چه پارامتر هایی داد بهش؟

**Comment by staliox** [comment]
برای اینکه با API بتونید کلاینت اضافه کنید به این صورت باید دیتا رو با متهد پست به `xui/API/inbounds/addClient` بفرستید:

`{
    "id": 1,
    "settings": "{\n  \"clients\": [\n    {\n      \"id\": \"593b2d24-b8bf-4583-a38f-33b4a41ffcde\",\n      \"email\": \"youremail@email.com\",\n      \"limitIp\": 0,\n      \"expiryTime\": 0\n    }\n  ]}"
}`

همینقدر ساده ^-^

**Comment by staliox** [comment]
> از طریق api باید چه پارامتر هایی داد بهش؟

برای اینکه با API بتونید کلاینت اضافه کنید به این صورت باید دیتا رو با متهد پست به `xui/API/inbounds/addClient` بفرستید:

`{
    "id": 1,
    "settings": "{\n  \"clients\": [\n    {\n      \"id\": \"593b2d24-b8bf-4583-a38f-33b4a41ffcde\",\n      \"email\": \"youremail@email.com\",\n      \"limitIp\": 0,\n      \"expiryTime\": 0\n    }\n  ]}"
}`

همینقدر ساده ^-^
