### ISSUE TITLE
ترافیک بر اساس UUID

### ISSUE THREAD

**Issue by linehman** [alireza0/x-ui#253]
با سلام و خسته نباشید،  تشکر فراوان از زحمات شما.
در حال حاضر ترافیک بر اساس ایمیل کاربران شناسایی می شود. با توجه به وجود چندین inbound برای کانفیگ های مختلف و محدودیت استفاده از ایمیل یکتا در  پنل ، نیاز است در هر inbound یک کاربر جدید تعریف شود و مثلا دو کلاینت مختلف به یک کاربر داده شود تا به هر دو کانفیگ دسترسی داشته باشد. در این حالت محاسبه ترافیک در این دو کانفیگ هماهنگ نمی شود و عملا دو ترافیک مجزا بر اساس دو ایمیل تعریف شده خواهیم داشت.

در صورت امکان اگر محاسبه ترافیک بر اساس UUID باشد ، می توان چند کاربر با ایمیل های مختلف اما UUID های یکسان در تمام inbound ها ایجاد کرد و به طور هماهنگ ترافیک محاسبه شود.

به نظر می رسد این ویژگی در فورک پنل توسط  NidukaAkalanka وجود داشته باشد.
https://github.com/NidukaAkalanka/x-ui-english/issues/15

باز هم تشکر از امکانات عالی که اضافی کردید.

**Comment by alireza0** [comment]
درود بر شما
محاسبه ترافیک توسط پنل انجام نمیشه و xray انجام میده. پنل فقط ترافیک رو میگیره و محاسبه میکنه.
این ترافیک بر اساس inbound-tag و email انجام میشه.
برای اینکه بتونید کاربر مشترک بسازید، ساختار x-ui به شما این اجازه رو نمیده.
بهتره از پنل هایی مثل مرزبان استفاده کنید
