### ISSUE TITLE
حذف سوکت قبل از شروع یا شروع مجدد ایکس ری

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#255]
سلام
وقتی از سوکت استفاده میکنیم برای ریورس پروکسی، قبل از اینکه ایکس‌ری شروع به کار کنه باید فایل سوکت حذف بشه
لطفا تنظیم کنید فایل های سوکت که توی بخش Listen در Inbound ها هست حذف بشه قبل از شروع Xray
بعد از نام سوکت ممکنه پرمیشن هم نوشته بشه، اگر اون هم لحاظ بشه خوبه
example path: `/usr/xray.sock`
example path + perm: `/usr/xray.sock,666`
example path + perm: `/usr/xray.sock,777`
تشکر

**Comment by alireza0** [comment]
فعلا برنامه ای برای تغییرات اینچنینی ندارم. بهتره به صورت اسکریپ یا تغییرات خودتون مدیریتش کنید

**Comment by alireza0** [comment]
@mozilla-firefox 
وقتی از سوکت داخل خود xray استفاده کنید ( با استفاده از ‍`@` ) ، خودش اتوماتیک حذف میشه.
ولی مدل فایل به راحتی پاک نمیشه، مگر اینکه ثابت باشه و توی اسکریپت ها بذاریم. با سرویس چیزی درست نمیشه.
مدل x-ui هم اینجوری طراحی شده که xray رو توی خودش اجرا کنه. تبدیلش به سرور مستلزم کلی تغییره که هم یه سری امکانات رو از دست میدیم و هم کلی باگ اضافه میشه.

**Comment by alireza0** [comment]
چرا کار رو پیچیده میکنید؟ اونکار هم منطق سیستم عاملی نداره و هم باعث مشکلات توی نرم افزارهایی میشه که به اون سوکت وصل هستند. مثل nginx.
علت رو دقیق میدونم کجاست. اونجایی که ما پردازش xray رو به زور SIGKILL میندازیم بیرون.
اگر این کار رو نکنیم گاهی کاربرها به مشکل میخورند. الان هم که انجام داده میشه، برای ریسورس هایی مثل سوکت مشکل داریم.
برنامه نویس اصلی بین مشکل کاربران و مشکل یه طیف کاربر مثل این حالت، گزینه اول رو انتخاب کرده

**Comment by alireza0** [comment]
با توجه به بهبود هایی که توی روند اجرا دادیم،‌به نظر میرسه به اندازه کافی پایدار هست که بتونیم xray رو به صورت نرمال ببندیم.
کمی تست میگیرم اگر مشکلی نداشت اعمال میکنم.
