### ISSUE TITLE
سی پی یو کشیدن

### ISSUE THREAD

**Issue by darianBaba** [alireza0/x-ui#256]
من دوتا سرور با مشخصات یکسان دارم که روی دوتاش هم نسخه 1.0.1 پنل نصبه. با اینکه روی سرور 1 تعداد یوزرهام تقریباً یک و نیم برابر سرور 2 هست، اما سرور 1 میانگین 20% پردازنده مصرف میشه، اما روی سرور 2 چند روزی هست که تا 100% پردازنده هم مصرف میشه که بعضیا قطع میشه (میانگین مصرف پردازنده بین 70 تا 85% هست برای سرور 2).
این اتفاق چه دلیلی داره؟
حتی ربات تلگرام سرور 2 رو هم خاموش کردم.
تشکر

**Comment by alireza0** [comment]
لطفا برای مطرح کردن سوالات مربوط به پنل ازاین بخش استفاده کنید. این سوالات پایه ای و در زمینه سیستم هست که پارامتر های زیادی باید بررسی بشه.
تنها نکته ای که میدونم و میتونم بهتون کمک کنم اینه که کانفیگ های tls پردازش زیادی لازم داره.
