### ISSUE TITLE
Operations done during a searched view do end up being buggy

### ISSUE THREAD

**Issue by ariandcir** [alireza0/x-ui#26]
Hi buddy,

I think if you have time, it would be good to go over all types of behaviour (e.g addition/deletion/modification etc) when in a searched view.

For example another scenario I encountered when searching for a particular pattern in the email and trying to add new users in that view, it does not preserve clients with non matching patterns and deletes them after adding the new user. I would imagine there could be similar behaviour in other scenarios. like resetting traffic in a searched view could also be buggy? not sure

**Comment by alireza0** [comment]
Hello,
Thank you for this report.
I think I should change the search scenario fundamentally...

**Comment by alireza0** [comment]
Done!
Please build manually or wait for new release.

Thanks again.
