### ISSUE TITLE
جدا سازی اسم و ایمیل

### ISSUE THREAD

**Issue by ZakariaRasoli** [alireza0/x-ui#264]
اسم از ایمیل جدا بشه واقعا بهتره

**Comment by staliox** [comment]
> اسم از ایمیل جدا بشه واقعا بهتره

عام ضروری نیست اما خودتم میتونی فقط عنوانشو دستی عوض کنی، هر زبانی که میخوای تو این دایرکتوری انتخاب میکنی:
https://github.com/alireza0/x-ui/tree/main/web/translation

قسمت [pages.inbounds] هر زبان و در آخر Email

**Comment by staliox** [comment]
> > > اسم از ایمیل جدا بشه واقعا بهتره
> > 
> > 
> > عام ضروری نیست اما خودتم میتونی فقط عنوانشو دستی عوض کنی، هر زبانی که میخوای تو این دایرکتوری انتخاب میکنی: https://github.com/alireza0/x-ui/tree/main/web/translation
> > قسمت [pages.inbounds] هر زبان و در آخر Email
> 
> نه منظورمو اشتباه فهمیدی من میخوام کلا ادمین به ایمیل دسترسی نداشته باشه و یه فیلد جدا برای اسم کانفیگ ها بزارن

فکر کنم الانشم اینطوریه ها، لازم نیست حتما ایمیل بدی

**Comment by ZakariaRasoli** [comment]
> > > > اسم از ایمیل جدا بشه واقعا بهتره
> > > 
> > > 
> > > عام ضروری نیست اما خودتم میتونی فقط عنوانشو دستی عوض کنی، هر زبانی که میخوای تو این دایرکتوری انتخاب میکنی: https://github.com/alireza0/x-ui/tree/main/web/translation
> > > قسمت [pages.inbounds] هر زبان و در آخر Email
> > 
> > 
> > نه منظورمو اشتباه فهمیدی من میخوام کلا ادمین به ایمیل دسترسی نداشته باشه و یه فیلد جدا برای اسم کانفیگ ها بزارن
> 
> فکر کنم الانشم اینطوریه ها، لازم نیست حتما ایمیل بدی

میدونم ولی اون ایمیل که خودت بهش ندادی باز میاد تو اسم کانفیگ Remark باید یچیز دلخواه باشه نه ایمیلی که زدی
