### ISSUE TITLE
ثابت بودن هدر

### ISSUE THREAD

**Issue by Prot0nX** [alireza0/x-ui#265]
سلام و خداقوت خدمت آقا علیرضا
من یه پیشنهاد داشتم اونم اینکه اگه میشه قسمت جستجو و هدر کلاینت توی اسکرول کردن ثابت باشن مخصوصا توی موبایل که کاربرا زیاد میشن بالا رفتن و پایین رفتن زیاد میشه، اینجوری این دو قسمت ثابت باشن بنظرم بهتر میشه، نمونه عکس هم میزارم قسمت ها مشص باشه که باید ثابت باشن. میشه گفت هر زیر مجموعه ای یا اینباندی باز شد همون فقط هدرش حالت فیکس بگیره و ثابت باشه توی اسکرول. مثلا من یدونه دارم و زیر مجموعه بیشتر از 100 نفر

![Fixed](https://user-images.githubusercontent.com/11087483/234028409-cc7e8ec1-25d3-4191-9742-a1d35c878948.png)

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و پیشنهادتون
من توی این مدت روی این موضوع کار کردم و متاسفانه قدیمی بودن فریمورک این پنل اجازه خیلی از کارها رو نمیده.
همچنین، روشی که ما برای نمایش همه سرویس و کاربرها در یک صفحه بکار گرفتیم مزایا و معایبی داره که این بخش هم جزو معایبش هست

**Comment by Prot0nX** [comment]
خب امکان صفحه بندی هم نیست مثلا هر 50 تا یوزر توی یه صفحه ؟!
مشکل پنل توی تعاد بالای یوزرهاست که دقیقا از 100 تا بالاتر میره کند میشه لود کردن یوزرها

**Comment by alireza0** [comment]
متاسفانه حتی اگر بخوایم توی چند صفحه نشون بدیم باید همه اطلاعات رو لود کنیم

**Comment by Prot0nX** [comment]
پس عملا هرکاری کنیم اطلاعات کامل لود میشه، هیچ راهی نداره برای بهینه کردن عملکرد لود اطلاعات بقول معروف بکوبی از اول طراحی کنی بهینه تر

**Comment by alireza0** [comment]
سعی من این بوده که فقط تصحیح کنم. نکات مثبت و منفی زیاد داره.
پنل x-ui عملا تمامی چک ها و عملیات ها رو به فرانت واگذار کرده و مسلما باید تمام اطلاعات هر بخش لود بشه.
برای کوبیدن و از اول ساختن ترجیح میدم پنل دیگه ای از اول طراحی کنم.

**Comment by Prot0nX** [comment]
این ینی باید منتظر یه پنل بهینه تر باشیم ازت مهندس؟!

**Comment by Prot0nX** [comment]
خبر خوبی بود
