### ISSUE TITLE
مشکل بهم ریختگی تاریخ انقضا بعد از آپدیت نسخه اخر

### ISSUE THREAD

**Issue by ach1992** [alireza0/x-ui#267]
سلام بعد از اینکه پنل رو به آخرین نسخه آپدیت کردیم برخی تاریخ ها خودکار تغییر کردند
یکی بود که رفته بود برای سال 1970!
یک سری هم به صورت زیر شدند
![image](https://user-images.githubusercontent.com/58507994/234397797-17e13c4e-a145-42ca-8037-e53c003ae97d.png)

**Comment by ach1992** [comment]
الان من دقت کردم مشکل خیلی جالب تر هم هست فقط چند تا نیستند که بهم ریخته 
هربار که پنل لود میکنی اینا تغییر می کنند ممکنه یکی درست بشه یکی خراب!

**Comment by aliamg1356** [comment]
> سلام بعد از اینکه پنل رو به آخرین نسخه آپدیت کردیم برخی تاریخ ها خودکار تغییر کردند یکی بود که رفته بود برای سال 1970! یک سری هم به صورت زیر شدند ![image](https://user-images.githubusercontent.com/58507994/234397797-17e13c4e-a145-42ca-8037-e53c003ae97d.png)

بله این مشکل هست  بیشتر برای اکانتهایی که از ورژن 1 به بالا ساخته شده اند.اکانتهایی گه وضعیت تاریخشون تغییر میکنه بعضیاشون متصل نمیشوند و باید حتما تاریخ رو دستی ست کر تا درست بشه

**Comment by alireza0** [comment]
درود بر شما
میشه لطفا نسخه ای که ازش بروزرسانی کردید رو بفرمایید ؟
واینکه بعد از بروزرسانی و یا نصب اینجوری میشه و یا بعد از هر restart ؟

**Comment by ach1992** [comment]
ببینید من از نسخه 5 پنل سنایی اومدم روی نسخه 0.5.2 شما بعدش اومدم نسخه 1.0.0 بعد به 1.0.1 و الان به 1.1.0 آپدیت کردم که آخرین هست.
هربار که صفحه ریلود میشه اینایی که این مشکل رو دارند عوض میشن!
دستی هم اصلاح کنی همون لحظه درست هستند ولی دوباره برمیگردند به حالت قبلی
فکر میکنم به این صورته که اگر کاربر در حال استفاده باشه برای لحظه ای درست میشن ولی همین که استفاده نکنه دوباره برمیگرده به همین حالت
هم اکانت های جدید و هم قدیمی که وجود داشتند و ایجاد شدند این اتفاق براشون افتاده و فرقی نمی کنه

**Comment by aliamg1356** [comment]
> مشکل رو پیدا کردم و برطرف شد. سپاس از گزارشتون. آقای ثنایی هم الان بروزرسانی میکنن. لطفا بروزرسانی کنید

آپدیت جدید پری ریلیز هست درسته؟؟؟

**Comment by alireza0** [comment]
معمولا قبل از ریلیز نهایی تست روش انجام میدم و بعد تبدیل به ریلیز میکنم.
این نسخه فقط چند دقیقه توی این حالت بود و بعد ریلیز شد.
