### ISSUE TITLE
Get info of a user by clientId

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#268]
سلام
تشکر از @alireza0  و @MHSanaei عزیز بابت افزودن قابلیت ادیت کاربر یا حذف کاربر با clientId
خواهشا این قابلیت رو هم بزارید که بتونیم اطلاعات کلاینت مورد نظر مون رو با clientId بگیریم
اگر دیتای دریافتی ما از getClient به همون فرمت updateClient باشه خیلی عالی و کارآمد میشه
تشکر مجدد

**Comment by alireza0** [comment]
درود بر شما
متاسفانه ساختار کنونی برای ذخیره دیتای مصرف کاربر از email استفاده میکنه.
بدون ایمیل هم هیچ ترافیکی از سمت xray نمیاد و نمیشه این فیلد رو عوض کرد.

**Comment by alireza0** [comment]
شما میتونید از متد "/get/:id" استفاده کنید و خوددتون کاربر ها رو پردازش کنید.
اضافه کردن این متد سمت سرور، به جز تکراری بودن، اصلا به صرفه نیست.
