### ISSUE TITLE
حذف چند کلاینت

### ISSUE THREAD

**Issue by Prot0nX** [alireza0/x-ui#269]
سلام مهندس خداقوت
پیشنهاد اضافه کردن انتخاب چند کلاینت برای حذف کردن رو خواستم اگه امکانش باشه به پنل اضافه کنی من یکم با تغییر کدهای html css سعی کردم نشون بدم چطور میشه توی پنل باشه (درحد پایه ام)

![image](https://user-images.githubusercontent.com/11087483/234495531-a9dd1d76-1089-4b79-beba-6754b068961e.png)

**Comment by alireza0** [comment]
درود بر شما
این صفحه واقعا برای گزینه های جدید جا نداره.
البته اختلاف این کار با کلیک روی دکمه حذف برای هر کلاینت زیاد نیست. برای حذف باید بیشتر احتیاط کرد.

در ضمن در نسخه آخر حذف همه کاربران منقضی شده اضافه شده.
