### ISSUE TITLE
سوال در مورد آپشن جدید

### ISSUE THREAD

**Issue by Cjxer** [alireza0/x-ui#270]
سلام وقتتون بخیر

من نسخه 1.0.1 هستم و میخواستم به جدید ترین نسخه یعنی 1.1.1 آپدیت کنم اما توی فیوچرهای اضافه شده دیدم که نوشته شده :
Delete depleted clients
میخواستم بدونم این برای چی هستش؟
کاربرانی که حجم و یا تایمشون تموم شده اتومات دیلیت میشن یا چیز دیگه ای ؟
و یا اگر اتومات پاک میشن امکانش هست که غیرفعالش کنم ؟
ممنون

**Comment by alireza0** [comment]
درود بر شما
کاملا دستی با انتخاب از منو انجام میشه
