### ISSUE TITLE
درخواست اضافه کردن فیوچر برای مدیریت ترافیک

### ISSUE THREAD

**Issue by Cjxer** [alireza0/x-ui#271]
سلام وقتتون بخیر 🌹
خیلی ممنون بابت امکانات فوق العاده ای که پیاده سازی کردین ❤️✌️

امکانش هست که در صفحه inbound ها ، اون قسمت بالا که Total uploads/downloads هست
حالا در کنار یا جلوش یا جای دیگه ای ، میزان ترافیک در بازه خاص که خودمون تعیین میکنیم
یا به صورت ۳۰ روزه از تایمی که در نظر داریم نمایش بده؟

مشکل من این هست که سرورم توی پنل ( سایتی که خریدم ) نمایش نمیده که چه مقدار مصرف شده و محدودیت ۱ ترابایت در ماه دارم
میخوام یه تاریخی که مثلا اول ماه هست یا تاریخی که سرور رو تمدید میکنم
به عنوان روز اول ثبت کنم و از اون تاریخ به بعد ثبت بشه که چه میزان ترافیکی رد و بدل شده و بتونم یه مانیتوری از حجم مصرفی در مدتی که میخوام داشته باشم

بازم ممنون از شما 🙏❤️

**Comment by alireza0** [comment]
درود بر شما
ممنون از همراهی و پیشنهادتون
در حال حاضر اطلاعات سرور و تاریخ ترافیک اصلا ذخیره نمیشه. متاسفانه دیتابیس هم برای اینکار به شدت ضعیفه.
