### ISSUE TITLE
قطع و وصلی هنگام add client

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/x-ui#272]
سلام عزیز وقتت بخیر
ممنون بابت وقتی که برای این پروژه میزاری.

میخواستم بدونم امکانش هست وقتی add inbound و یا add client میکنیم اتصال کاربر های قدیمی قطع و وصل نشه؟

**Comment by alireza0** [comment]
درود بر شما
متاسفانه نرم افزار xray-core چنین امکانی نداره. هربار که تغییری رخ میده باید یکبار این دستور ریستارت رو براش بفرستیم تا اعمال بشه
