### ISSUE TITLE
Access.log

### ISSUE THREAD

**Issue by Philipname** [alireza0/x-ui#273]
func GetAccessLogPath() string {

config, err := os.ReadFile("bin/config.json")
checkError(err)
jsonConfig := map[string]interface{}{}
err = json.Unmarshal([]byte(config), &jsonConfig)
checkError(err)
if(jsonConfig["log"] != nil) {
jsonLog := jsonConfig["log"].(map[string]interface{})
if(jsonLog["access"] != nil) {

  accessLogPath := jsonLog["access"].(string)

  return accessLogPath
}
}
return ""

}
سلام وقتتون بخیر
با توجه به کد پنل access.log  پاک میشه.(هر ادرسی
به access داده بشه پاک میشه).

من نیاز دارم کل فایل access.log داشته باشم تا به صورت دستی روش تحلیل انجام بدم و پاکش کنم(خیلی راحت میشه با اکسس لاگ یوزرهایی که بیشتر از یک ایپی وصل شدن پیدا کرد و کار محدودیت ای پی راحت تر حل میکنه)
امکانش هست که توی قسمت ستینگ پنل یه سویچ اضافه بشه که بتونم NewCheckClientIpJob رو فعال یا غیر فعال کنم؟

**Comment by alireza0** [comment]
درود بر شما
فکر میکنم آدرس رو اشتباهی اومدین.
این پنل به صورت پیشفرض این فایل رو تولید نمیکنه. اگر شما اضافه کنید هم هیچوقت پاک نمیکنه.

در پنل هایی که IP limit دارند برای پردازش اطلاعات IP کاربر ها از این فایل استفاده میکنند
