### ISSUE TITLE
settings.clients and clientStats  array do not match

### ISSUE THREAD

**Issue by SadraRahmani** [alireza0/x-ui#274]
**Describe the bug**
Sometimes(on some servers) when calling /xui/API/inbounds/ to get all inbounds, or getting a single one using /xui/API/inbounds/get/2, the number of  items in clientStats does not match settings.clients or clientStats is null 

**To Reproduce**
I cannot force it to be reproduced, after installation on one of my servers it happened, but other servers are fine

**Expected behavior**
I guess the expected behaviour should be that the clientStat always match the settings.clients with extra properties?

**Screenshots**
I uploaded a zip file containing 2 json files directly copied from browser by calling mentioned api.
[sample-jsons.zip](https://github.com/alireza0/x-ui/files/11350594/sample-jsons.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: No phone
 - OS: No phone
 - Browser No phone
 - Version No phone

**Additional context**
I will be availble for further investigation
Panel version I'm using is 1.1.1

**Comment by SadraRahmani** [comment]
I understand but I guess this is a bug, related to the bug I was talking about
![image](https://user-images.githubusercontent.com/19726427/235298111-2b50a466-f9b9-4eaa-bf0d-a64cc57cfe2c.png)

as you can see total usage of the clients are 2GB but sum of all clients(client stats) in the system  is less than 71MB!
I also didn't delete any clients from the installation of xui, Only adding
so that 2 gigabytes are not cached from deleted clients

if I'm doing something wrong please guide me

**Comment by alireza0** [comment]
It seams you confused about this numbers. I could explain it here:
1. Inbound's traffic is not about sum of all clients. You can see `up` and `down` fields in each inbound.
2. Inbound traffics are collecting from xray-core each time separately.
3. This inbound is using famous port 443 which may attack and used by lots of internet-wide checks. This packets might be considered!
4. If you add a fallback in this inbound, all traffics which passes from this inbound will be considered.

Personally I recommend to avoid using traffic limitation in inbounds like this.

**Comment by SadraRahmani** [comment]
I'm sorry
I really do not want to bother, your panel is AWESOME and your work is very well appreciated ❤
but all of my clients(not too many, about 11) are on this panel and I'm TOO sure there is something not right here. 
I will demonstrate it, and test the functionallity like this
first, I changed the testing port to 8443
BEGINNING OF THE TEST
![image](https://user-images.githubusercontent.com/19726427/235309125-e53b2133-2b20-4855-be77-21c895b7a658.png)

then I copied 752d916ed41f4aef9ae2d882a82e5b0d Client (first client in the picture) config and downloaded exactly 100MB
then I did the test with second one 5f8385d679ce49bfaac43085ac30d24d Client id and downloaded exactly 100MB
THE RESULT AFTER THAT
![image](https://user-images.githubusercontent.com/19726427/235309230-11a6dc0d-bef8-400c-845c-e77b9c21b775.png)
as you can clearly see, the traffic for the first one (the one that is not showing in the clientstat field) is not changed even a byte
but the second one (the one that DOES show in the client stat) had changed exactly 100MB

json of the request captured from _fiddler_: 
`{
      "id": 3,
      "up": 219529774,
      "down": 6596036134,
      "total": 0,
      "remark": "1ce52b0f3c RLT2",
      "enable": true,
      "expiryTime": 0,
      "clientStats": [
        {
          "id": 3,
          "inboundId": 3,
          "enable": true,
          "email": "5f8385d679ce49bfaac43085ac30d24d",
          "up": 849681,
          "down": 182767612,
          "expiryTime": 1686647404243,
          "total": 322122547200
        }
      ],
      "listen": "",
      "port": 8443,
      "protocol": "vless",
      "settings": "{\"clients\":[{\"id\":\"9de2d732-7b57-4c00-b9c7-3f4d9f290174\",\"flow\":\"xtls-rprx-vision\",\"email\":\"752d916ed41f4aef9ae2d882a82e5b0d\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0},{\"id\":\"85a8d049-fb4d-47dd-95fe-52c5e98d465f\",\"flow\":\"xtls-rprx-vision\",\"email\":\"5f8385d679ce49bfaac43085ac30d24d\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0},{\"id\":\"49293f6c-637b-4708-9289-44d9b39f3bd1\",\"flow\":\"xtls-rprx-vision\",\"email\":\"a86a7b6f08b4431c9ae3b44118dcad15\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0},{\"id\":\"6a9753db-5673-458d-9a72-faa1975eeb00\",\"flow\":\"xtls-rprx-vision\",\"email\":\"07383b41eec041ef98962dfef5706ad9\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0},{\"id\":\"a5478740-aa29-4e96-94e6-093006748c16\",\"flow\":\"xtls-rprx-vision\",\"email\":\"54d27710c0e2491cb0af1e9a5e403aca\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0},{\"id\":\"edf6a6c7-2c55-4774-8fc2-ef4f538807d1\",\"flow\":\"xtls-rprx-vision\",\"email\":\"5e5ccc390aab40018bcfb8081675f145\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0},{\"id\":\"49f10fee-a5e9-4ba4-b997-e428bcba012f\",\"flow\":\"xtls-rprx-vision\",\"email\":\"df7f50396c93421fa45c1875df4fa4f1\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0},{\"id\":\"1229e06a-40d9-4441-881a-16d1a8ef0bdb\",\"flow\":\"xtls-rprx-vision\",\"email\":\"67d6045f516c450aa1888aabd7ee27f6\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0},{\"id\":\"8114a19c-dcc8-4cea-be1e-d31053e1fa4a\",\"flow\":\"xtls-rprx-vision\",\"email\":\"feda4a43a09649b4865a3173f98ff9ba\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0},{\"id\":\"acc06ab0-927f-4724-8640-2dd5fe86f8ab\",\"flow\":\"xtls-rprx-vision\",\"email\":\"eded3f307f014f0b869211f4093e098c\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0},{\"id\":\"e2643200-79bf-44f9-b3a0-e2202cb42681\",\"flow\":\"xtls-rprx-vision\",\"email\":\"5f7d313ad81d465ba9848cafcc25ef92\",\"limitIp\":2,\"enable\":true,\"totalGB\":322122547200,\"expiryTime\":0}],\"decryption\":\"none\",\"fallbacks\":[]}",
      "streamSettings": "{\"network\":\"tcp\",\"security\":\"reality\",\"tcpSettings\":{\"acceptProxyProtocol\":false,\"header\":{\"type\":\"none\"}},\"realitySettings\":{\"show\":false,\"xver\":0,\"dest\":\"xbox.com:443\",\"serverNames\":[\"xbox.com\",\"www.xbox.com\"],\"privateKey\":\"eC5CSBHAWkoETS16KolFTuHMtvJmqcjRycVI3f53_10\",\"minClient\":\"\",\"maxClient\":\"\",\"maxTimediff\":0,\"shortIds\":[\"98c8fb79\"],\"settings\":{\"publicKey\":\"1fqH0gAH4NBFSTMCg24kFh-9e5K5S25nS7r4a7Td2T4\",\"fingerprint\":\"chrome\",\"serverName\":\"hfkwop.segstar.info\",\"spiderX\":\"/\"}}}",
      "tag": "inbound-8443",
      "sniffing": "{\"enabled\":true,\"destOverride\":[\"http\",\"tls\"]}"
    }`

so

**Comment by alireza0** [comment]
I reckon that it is related to a migrated panel!
Could you please update it and share the result then ?

**Comment by SadraRahmani** [comment]
I did not migrate it
The first panel version I used and installed on this server 2 days ago is 1.1.1

i actually can provide you with the exact time I executed the panel script the first time! 
2023-04-27 18:03:32.293 UTC

BTW

Now I deleted the panel completly and installed it again
this seems to solve the problem(but not permanently)

I noticed after some time this part would crash again
FIXED IMAGE:
![image](https://user-images.githubusercontent.com/19726427/235310620-f48f6a6f-2ec8-4bdd-aaa6-4ad6de3ee1c8.png)

JSON
json after fresh panel installation and creating all the inbounds again
[xui-inbounds-list_FIXED.zip](https://github.com/alireza0/x-ui/files/11359534/xui-inbounds-list_FIXED.zip)

**Comment by SadraRahmani** [comment]
> Now I deleted the panel completly and installed it again this seems to solve the problem(but not permanently)

Because yesterday I did the same action(deleting and installing the panel again) but after a day it broke so I did it again now

**Comment by alireza0** [comment]
It should be sth in `client_traffic` table in database.
I asked you if it is related to the old database, due to some bugs caused deleting traffic row of client in this table.
But it was fixed in migration script added in [1.1.0](https://github.com/alireza0/x-ui/commit/8bc16b020b68139ff88954fcc4b169d92f3ee414).

If you have previous database, you can manually run migration and test again:
```
/usr/local/x-ui/x-ui migrate
```

P.S. JSON files is not helpful in this regard. If it helps, please send a backup from your previous database to my email for more investigations.

**Comment by SadraRahmani** [comment]
Sure, Happy to help
If the issue happened again I send you a backup of the DB

Though as I mentioned the first panel I installed on the server was 1.1.1 

Thanks again, AWESOME JOB

**Comment by SadraRahmani** [comment]
Hi
It happened again
Sent you the email

**Comment by alireza0** [comment]
I have sent you the result by email with problem explanation
