### ISSUE TITLE
 Custom panel path + Option to stop the panel Interface

### ISSUE THREAD

**Issue by elrazez** [alireza0/x-ui#275]
It would be great to have an option to change the `/xui/` url path to a custom path since i think the default path is a reason for the IPs getting banned.
also if there was a Terminal option to fully turn off/stop the UI after configuration (and keep the core running), it would be highly useful and appreciated.

_with REALITY being the fastest and most reliable protocol rn, i think it's even more important to make the servers not stand out. blocking the SSH port has been proven useful, i think these options will be the same._

Thank you

**Comment by alireza0** [comment]
There is no good reason to ban HTML page which contains path. Specially when you have SSL encapsulation!
Although, you can change your prefix in setting as well.
Other solutions could be:

1. Using nginx or other reverse proxy services.
2. Copy your final `config.json` and run a xray-core directly.
3. Use `iptables` or other firewalls to ban source ip addresses from accessing this port.
4. Add different IP to the panel and store it in settings.
5. VPS providers are usually provide /64 range of IPv6. Assign different IPv6 to the panel.
6. Use loopback and open it only with SSH tunnel

**Comment by elrazez** [comment]
`There is no good reason to ban HTML page which contains path. Specially when you have SSL encapsulation!`

if i understand this sentence correctly, you're saying since we're connecting to the panel via SSL, there is no need to do this, but what about a reality setup where you do not set any SSL for anything?

as for the rest of the solutions, thank you

**Comment by alireza0** [comment]
Reality is a kind of ssl connection
