### ISSUE TITLE
Sniffing Customization

### ISSUE THREAD

**Issue by PatrickstarWritesCode** [alireza0/x-ui#276]
**Is your feature request related to a problem? Please describe.**
Many sites use QUIC, to my current understanding sniffing on inbounds only enables this feature for TLS and HTTP.

**Describe the solution you'd like**
The ability to specify what goes into sniffing configuration:

`"sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
`

**Describe alternatives you've considered**
Blocking QUIC in routing rules (suboptimal)

**Additional context**
Check boxes of possible protocols under sniffing radio button or a field for comma separated list

**Comment by alireza0** [comment]
Thanks. It is added now.
But limited to add quic. Other options may cause ambiguity.
