### ISSUE TITLE
sub links

### ISSUE THREAD

**Issue by AmoAlireza** [alireza0/x-ui#277]
سلام
علیرضا جان تو نسخه جدید یه باگی افتاده روی لینک های سابسکرایب که اگر از یک اسم مشخص قسمت subscription روی چند inbound استفاده کنی اون لینک ساب وقتی واردش میشی ارور HTTP ERROR 500 میگیری ولی اگر فقط روی یدونه inbound اون اسم استفاده کنی لینک ساب کار میکنه.

**Comment by AmoAlireza** [comment]
***آپدیت***
مشکل با روشن کردن allow insecure و H2 , H3 حل شد.

**Comment by burjuyz** [comment]
I have the same problem.
Where do i need to turn on allow insecure?
