### ISSUE TITLE
Bulk Export/Import feature

### ISSUE THREAD

**Issue by aliafshany** [alireza0/x-ui#28]
Hello
it would be so nice if you could add such a feature that you can add more than one user at once in an inbound.
or  you can export the whole inbound's links at once and get it in a txt or csv file. or a pop-up window containing those links.

thanks in advance for your efforts and time you put to this project.

![image](https://user-images.githubusercontent.com/40741745/221443072-b8fe456a-bc75-451f-95cc-529ff8cd9b25.png)

**Comment by alireza0** [comment]
Done!
Please build it manually or wait for new release.

Thanks again 👍
