### ISSUE TITLE
Client Usage

### ISSUE THREAD

**Issue by Sinahunter** [alireza0/x-ui#280]
سلام علیرضا جان
ممنون بابت پنل خوبی که در اختیار ما گذاشتی.
اینو همه جوره تست کردم ولی خطا داره
مصرف ترافیک کاربر با مقدار واقعی مصرف شده خیلی تفاوت داره مثلا 10M دانلود میکنم ولی usage رو میزنه 65
ممنون میشم بررسی بفرمایید.
با تشکر

**Comment by koohsaran** [comment]
سلام
منم همین مشکل رو دارم، راه حلی براش نیست؟

**Comment by koohsaran** [comment]
> برا من تو System status دو سه برابر مینویسه چون اونجا حجم جابجا شده تو کل سرور رو مینویسه، حتی ارتباطات لوکال سرورو حساب میکنه حتی سرعت رو هم چند برابر مینویسه، اما توی حساب کتاب حجم مصرفی هر کاربر من خطایی ندیدم شما منظورتون کدوم بخش هست؟ کجا مشکل دارید @Sinahunter @koohsaran

توی جدول برای هر کلاینت جداگانه، مخصوصا زمانی که از اینترنت دانلود منیجر استفاده میکنم حجم دانلود و آپلود به طرز عجیبی چندین برابر محاسبه میشه
