### ISSUE TITLE
reality on vmess

### ISSUE THREAD

**Issue by straxico** [alireza0/x-ui#282]
i need make vmess with reality from panel 

like this
sn://vmess?eNoVzbuKAjEUgOH4JvsCOZBk5iQp1wsoXvDGipWMMwmKg5FMZgS7eRitttjGt_BddsFGsFkt_vLjJ4QQxYFhDDEC_jw_CDlzqSIlhabSIKcRE4pqmwmqhUpQaIzWuE7K8PuyJKR_Ib9figODku4hPcHBuww2rggFOLfLk8L4ynjYm1DXxG69se7xPWLdrF3150FP5GQc59qPV_Z48lzgrL1YDmfVl-lkLVY2hwaFTCRXyppYivT6vjZe9aafo1ZncKvrf-hHPSQ

please test on nekobox client

**Comment by alireza0** [comment]
XTLS still has not release reality on vmess yet!
If I am wrong please point me to the documentation or configuration.
