### ISSUE TITLE
Bug: VLESS flow doesn't support xtls-rprx-direct in this version

### ISSUE THREAD

**Issue by har4s** [alireza0/x-ui#283]
سلام من وقتی پنل رو آپدیت میکنم یا ورژن xray رو به 8 به بالا آپدیت میکنم با این ارور مواجه میشم
در حال حاضر از این نسخه ها استفاده میکنم
x-ui: 0.5.2 xray: 1.7.5
![photo_2023-05-02_00-50-18](https://user-images.githubusercontent.com/8129659/235533446-d2dace66-c345-4bf7-a55b-e211cbf46863.jpg)

**Comment by nasiriscript** [comment]
این باگ نیست ورژن 1.8 به بعد دیگه فلو direct نداره چون منسوخ شده دیگه.

**Comment by har4s** [comment]
درسته ولی توی پنل گزینه ای نیست تا بتونم ویرایش کنم این گزینه رو

**Comment by MHSanaei** [comment]
پنل رو به نسخه اخر اپدیت کنید flow ها حذف میشن
