### ISSUE TITLE
باگ کارنکردن دکمه دیلیت در کاربر

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#285]
با سلام درنسخه جدید یعنی 1.3.0دکمه دیلیت برای کاربر کار نمیکنه و بقیه دکمه ها اوکی هستن

**Comment by alireza0** [comment]
درود بر شما
دکمه disable هم کار نمیکنه
دارم هات فیکس میزنم

**Comment by alireza0** [comment]
نسخه جدید آماده شد. لظفا بروزرسانی کنید.
