### ISSUE TITLE
نحوه استفاده از بات تلگرام

### ISSUE THREAD

**Issue by trytopassgfw** [alireza0/x-ui#286]
سلام
نمیدونستم باگ هست یا نه. لیبل سوال زدم.
من طبق تصویر زیر تنظیمات پنل رو اعمال کردم. هم یوزر ادمین تعریف کردم و هم برای یکی از کاربرای تلگرام یوزر ادد کردم ولی هیچ کدوم وقتی داخل بات start میزنم جوابی نمیده. پنل رو هم ریستارت کردم.
ورژن 0.5.2 هم استفاده میکنم
![imageedit_2_4680629126](https://user-images.githubusercontent.com/125186696/235871480-beea2ec0-08ae-4715-94f0-603813e4c262.png)

**Comment by alireza0** [comment]
درود بر شما
بخش chatIds باید id باشه و بدون `@`
برای پیدا کردن telegram chatID از بات `@getidsbot` استفاده کنید:

**Comment by trytopassgfw** [comment]
مرسی درست شد.
به نظرم اگر یه مقدار نمونه پیش فرض قرارداده بشه که این اشتباه رخ نده میتونه خوب باشه.
