### ISSUE TITLE
ریست ترافیک کلی

### ISSUE THREAD

**Issue by dreamboxone** [alireza0/x-ui#289]
سلام
دکمه ریست ترافیک کلی رو در نسخه ۱.۲.۱ زدم. اما هیچ کدام از اکانتها رو ریست ترافیک نکرد.
با تشکر

**Comment by alireza0** [comment]
درود بر شما
توی این نسخه دومدل ریست کلی داریم. ریست ترافیک کاربران و ریست سرویس ها.
هردو در آخرین تست ها برای من درست کار میکرد.
لطفا اطلاعات دقیقتری شامل لاگ و نوع خطا ( درصورت وجود) برای من بفرستید.

**Comment by dreamboxone** [comment]
من دکمه ریست ترافیک کل سرویسها را فشار دادم . فکر می کردم ترافیک کاربران را صفر (ریست) میکند. اما الان دقت کردم و دیدم گزینه ریست ترافیک کاربران هم وجود دارد.
تشکر
