### ISSUE TITLE
Multiple SSL certificates per Inbound

### ISSUE THREAD

**Issue by arash88** [alireza0/x-ui#290]
Hey @alireza0 jan,
Xray has the ability to attach multiple ssl certs to inbounds. It's an awesome feature to face the heavy SNI/Domain filtering.
Thanks

**Comment by alireza0** [comment]
Hello @arash88 
How about combining two certificates or add new cert to the old one ?
```
certbot certonly --standalone -d server1.exaple.com -d server2.example.com -d ...
```

**Comment by arash88** [comment]
Hi @alireza0 ,
I've already done that, I'm afraid it's not applicable for wildcard* certs. It's the only way to have single-port & multi-domain configs.

**Comment by alireza0** [comment]
Hello @arash88,

It is now added to the codes. You can compile it manually or wait for next release.

**Comment by arash88** [comment]
Thank you so much dadashi,
Best Xray-core panel ever!
