### ISSUE TITLE
مشکل ناپدید شدن برخی از کلاینت ها

### ISSUE THREAD

**Issue by razikazeminezad** [alireza0/x-ui#291]
با سلام،
من الان از ورژن 1.1.2 استفاده میکنم و 1032 تا کلاینت دارم با 17.36T حجم مصرفی بعد از نصب نسخه جدید 1.2 دیدم تعداد کلاینت ها زیر 800 تا شد و ترافیک مصرفی هم پایین اومد دوباره ورژن 1.1.2 رو نصب کردم مشکل برطرف شد.
امروز مورژن 1.2.1 که دادید رو باز هم چک کردم و مشکل همچنان هست و تعداد زیادی از کلاینت ها از دیتا بیس لود نمیشه

**Comment by alireza0** [comment]
درود بر شما
با این اطلاعات کم چطور میتونم مشکل رو پیدا کنم؟
لطفا اطلاعات بیشتری بذارید. این مشکل فقط برای شما رخ داده و احتمال داره برای عدم رعایت یک سری اصول باشه.
لطفا قبل از بروزرسانی، به مواردی که اضافه یا تصحیح شده دقت کنید.
