### ISSUE TITLE
ss-2022 add ws support in future version

### ISSUE THREAD

**Issue by cwyin7788** [alireza0/x-ui#294]
Dear developer,

1.2 / 1.2.1 shadowsocks 2022, "ws" option was gone, can u add this function back in future version？ because if ws support,  I can use cf http port (such as 8880) pass through the cf CDN or I can use nginx (port 80) as reverse proxy.

here is the screen capture from 1.1.3

<img width="485" alt="螢幕截圖 2023-05-04 上午9 12 11" src="https://user-images.githubusercontent.com/53026952/236084859-f380a3ae-c388-4811-be02-c98ef690afe3.png">

thanks for hear me.

**Comment by alireza0** [comment]
Done!
Please wait for next release or compile it manually.

**Comment by cwyin7788** [comment]
> Done!
> 
> Please wait for next release or compile it manually.

thank you developer.
