### ISSUE TITLE
مشکل کندی کلافه کننده در پنل 

### ISSUE THREAD

**Issue by ssmetall** [alireza0/x-ui#295]
سلام و با تشکر از امکانات خوبی که ارائه میدین ، متاسفانه در حالت تک پورت بالای 500 یوزر پنل به طرز وحشتناکی کند میشه و تقریبا غیر قابل استفاده هستش ، در صورت امکان ایراد را شناسایی و رفع نمایید با سپاس
ارور مربوطه در مرورگر pale moon 
https://s8.uupload.ir/files/dfhfh_uj1c.jpg

**Comment by razikazeminezad** [comment]
با سلام
ایراد از CPU شما هست برادر
1250 کاربر دارم زمان لود 6 ثانیه

**Comment by megasoheilsh** [comment]
> با سلام ایراد از CPU شما هست برادر 1250 کاربر دارم زمان لود 6 ثانیه

مشخصات سیستم شما چیست ، سیپیوی من 12400 هستش ، با 900 تا یوزر حدودا 40 ثانیه طول میکشه تا پنل باز بشه

**Comment by razikazeminezad** [comment]
طبق عکس شما پنل سنایی رو داری پنلت مال علیرضا نیست که

**Comment by megasoheilsh** [comment]
> طبق عکس شما پنل سنایی رو داری پنلت مال علیرضا نیست که

پنل اقای علیرضا و ثنایی کاملا شبیه به هم دارن دولوپ میشن و ضمن اینکه با پنل علیرضا خان هم همین وضعه

**Comment by megasoheilsh** [comment]
> 8 x 2.4Ghz Intel چند تا هسته داری

مدل دقیق سیپیو شما چیه ؟ 
برای من ۶ هسته ۴.۲ گیگاهرتز
