### ISSUE TITLE
all  client status  

### ISSUE THREAD

**Issue by aliafshany** [alireza0/x-ui#30]
سلام
خسته نباشید بابت زحماتی که میکشید
این پیام رو یکی از دوستان دادند تا براش ایشو بزنم و ایشو خود من نیست.
مرسی
--------------

قابلیت دوم که اگر اد بشه عالی هست 
اینکه تعداد یوزرهای ساخته شده ، فعال و غیر فعال داخل اکانت نمایش داده بشه
در پنل اصلی چینی چون روی هر پورت فقط یک اکانت میشد ساخت در نتیجه تعداد inbound ها برابر بود با تعداد کاربر ها و صاحب پنل به راحتی میتونست متوجه بشه چندتا یوزر داره
ولی در پنل شما که روی هر اینباند و پورت میشه چندین یوزر تعریف کرد عملا تعداد اینباند ها با تعداد یوزرها برابر نیست و اگر کسی بخاد آماری از پنل داشته باشه باید دستی بشینه شمارش کنه 
اگر قابلیتی به شکل زیر تعریف بشه عالی میشه :

All user :

تعداد کل یوزرهای ساخته شده روی تمامی پورت ها

Active user :
یوزرهایی که فعال هستند 

Disabled user :

یوزرهای که به هر علت غیرفعال هستند ،چه به علت سر رسیدن تاریخ انقضای اکانت و چه به علت اتمام حجم
یا اگر پیشنهاد اول رو هم اعمال کردید میتونید یوزرهای که ساخته شده ولی هنوز اکانتشون شروع نشده و متصل نشدن هم در این قسمت بیارید یا اصلا یک قسمت جدا براش ایجاد کنید

برای مثال فرض کنید من روی پنل ۱۰ تا یوز ساختم که دوتاش حجمش تموم شده و غیرفعال هست :

All user : 10
Active user : 8
Disabled user : 2

ممنون میشم به این دو مورد فکر کنید
با تشکر از لطفتون و وقتی که میزارید

**Comment by alireza0** [comment]
Done!
Please build your own or wait for new release

**Comment by Nipoto** [comment]
small Changes :

[web.zip](https://github.com/alireza0/x-ui/files/10880512/web.zip)
