### ISSUE TITLE
چندتا پیشنهاد

### ISSUE THREAD

**Issue by Prot0nX** [alireza0/x-ui#301]
سلام خداقوت مهندس
- مورد اول اینکه وقتی کاربر حجمش قبل از مدت زمانی که ثبت شده مصرف میشه، یجوری نشون بده که مثلا این کاربر چند روز حجمش تمام شده!
مثلا 10 روز از تاریخش مونده ولی حجمش زودتر مصرف کرده و از روزی که حجمش تمام شده، شروع کنه به محاسبه که بگه چند روز از اتمام حجمش گدشته!
- مورد دوم اینکه امکان فیلترکردن بین کاربران فعال که در حال مصرف هستن و کاربرانی که حجمشون یا تاریخشون تمام شده فیلتر کرد صفحه رو و فقط همون گروه ها نمایش داده بشن!

تشکر بابت زحماتی که میکشید

**Comment by alireza0** [comment]
درود بر شما
از همراهی و پیشنهادتون سپاسگزارم
۱. در حال حاضر این پنل تاریحچه استفاده کاربران رو ذخیره نمیکنه. به همین دلیل نمیشه تاریخ اتمام رو پیدا کرد.
۲. گزینه فیلتر اضافه شد.

**Comment by Prot0nX** [comment]
دست خوش مهندس :)
