### ISSUE TITLE
امکاناتی جدید 

### ISSUE THREAD

**Issue by arsoltani72** [alireza0/x-ui#304]
سلام و عرض ادب 
چند تا پیشنهاد داشتم 
اول این که این امکان باشه که به صورت یکجا به همه کاربر ها بشه چند روز اضافه کرد 
دوم این که آنلاین بودن کاربر رو هم پنل نشون بده

ممنونم از تلاش های شما

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و پیشنهادتون
دو مورد اول با مدل کار این پنل و پراکسی ها سازگار نیست.
مورد سوم اضافه شده. منتظر نسخه جدید باشید.

**Comment by arsoltani72** [comment]
متشکرم
