### ISSUE TITLE
Clone feature has bug on reality

### ISSUE THREAD

**Issue by amirhakimnejad** [alireza0/x-ui#305]
When you clone a config with a reality setting, both configs stop working. Until you generate another private, public keys for the new one.
So I assume cloning a config with reality should regenerate the certificate for the new one.

**Comment by alireza0** [comment]
Thank you for this report.
It is only about cloning VLESS inbounds and not about certificate. Could be fixed by editing and saving again.

I am going to fix this issue soon.

**Comment by alireza0** [comment]
It is fixed now.
You can compile it manually or wait for new release.

Thanks again.
