### ISSUE TITLE
ارتقا سابستکریپشن 

### ISSUE THREAD

**Issue by Ariagsm** [alireza0/x-ui#306]
سلام آقا علیرضا 
آیا امکانش هست در پروتکل tcp قسمت آدرس رو خودمون دستی وارد کنیم نه اینکه خودکار با ادرس پنل ساخته بشه؟
چون موقعی که لینک سابستکریپشن به مشتری داده میشه بشه تمام تغییرات رو داخل سرور انجام داد

**Comment by linehman** [comment]
سلام ، به نظر من هم این ویژگی می تونه به خیلیا کمک کنه که باکس نام domain رو وقتی تیک tls فعال نیست هم داشته باشیم. تا بشه چند کانفیگ با دامنه های مختلف بدون tls هم ایجاد کرد که از طریق subscription در دسترس باشند.

**Comment by alireza0** [comment]
درود بر شما
اضافه کردن این تنظیمات بدون tls هم خیلی اذیت کننده است و هم اینکه راه حل زیاد داره.
برای TLS روی نسخه جدید ارائه میشه

**Comment by Ariagsm** [comment]
اگر میشد اضافه بشه خیلی عالی می بود
