### ISSUE TITLE
اضافه کردن حجم و زمان به صورت سراسری

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/x-ui#307]
سلام وقتت بخیر عزیز

به نظرم اگر این امکان رو داشته باشیم که بتونیم بصورت سراسری حجم و یا زمان خاص اضافه بکنیم (به کسانی که حجم و یا زمان نامحدود ندارن) خیلی خوب میشه.

چون بعضی مواقع قطعی هایی برامون پیش میاد و برای جبرانی میخوایم چند روز زمان اضافه بدیم به همه.

ممنون از شما ❤️

**Comment by alireza0** [comment]
درود بر شما.
سپاسگزارم از همراهی و پیشنهادتون.
اصولا این مدل دستکاری ها توی سیستم های بزرگ یا به شکل دستی و یا پکیجی انجام میشه.
این سیستم خیلی کوچکتر از اونیه که بخوایم پیچیدگی هایی شبیه به این رو پیاده سازی کنیم.
