### ISSUE TITLE
Merge multiple x-ui.db into one database

### ISSUE THREAD

**Issue by arsoltani72** [alireza0/x-ui#309]
hi there hope you doing well 
and thank for all of your efforts and enhancments 
is it possible to merge two or more x-ui.db data base into one ?

**Comment by alireza0** [comment]
Hello @arsoltani72,
Thank you for your suggestion.
This needs a lot of consideration in tables and is not easy to manage.
Complexity is not my choice

**Comment by arsoltani72** [comment]
I will try to figure it out
