### ISSUE TITLE
Similar to spyware !!!

### ISSUE THREAD

**Issue by ikooshk** [alireza0/x-ui#31]
سلام
عزیز دل، شما همکار هستید توی بخش سایبری؟
اینی که زحمت کشید و درستش کردید توی 2 سوت ردشو میزنن!! من یه اسکریپ دیگه غیر ایرانی گذاشتم واسه همکارام الان 6 ماهه داریم استفاده میکنیم.. مال شمارو ریختم واسه سرور فامیلی هر بار که ریختم با همون کانفیگ سرورای قبلیم ردش زده شد..
عزیز دل واقعا تو این شرایط بجای اینکه کمک هم باشیم جاسوس افزار درست میکنیم تا پدر همو دربیاریم؟
بیشتر اسکریپتای ایرانی همکاری صمیمانه ای با گریت فایروال دارن... دم شما گرم
در انتها امیدوارم من اشتباه کرده باشم.. موفق باشید

**Comment by alireza0** [comment]
درود بر شما
دوست عزیز، این بخشی که شما پیامتون رو ارسال کردین مخصوص حل مشکلات هست.
لطفا اگر اشکالی میبینید با ذکر دلیل و سند اعلام بفرمایید تا حل کنیم.

جهت اطلاع شما، این قبیل ایرادات مربوط به نرم افزارهای کمپایل شده است ( مثل اپ های اندروید و نرم افزار های پک شده ) و در مورد کد های متن باز مطرح نمیشه.

لطفا از یک متخصص و یا برنامه نویس مورد اعتمادتوت راهنمایی بگیرید. امیدوارم مشکلتون رو پیدا کنید و بتونید از اینترنت آزاد استفاده کنید.
ارادتمند
