### ISSUE TITLE
یک پیشنهاد کارامد جهت بهبود ربات تلگرامی

### ISSUE THREAD

**Issue by Morghak963** [alireza0/x-ui#312]
سلام مهندس
وقت بخیر
همینطور که مستحضرید داخل پنل میشه برای هر اکانت یک یوزرنیم تلگرام مشخص کرد که از طریق اون بتونند به راحتی از ربات استفاده کنند برای مشاهده حجم و تاریخ انقضا
اگر بشه هشدار تموم شدن حجم یا زمان هم به ربات اضاف بشه عالیه
به این صورت که مثلا یکروز قبل از اتمام تاریخ یا یک گیگ مونده به پایان حجم یک نوتیفکیشن از طریق ربات به آیدی تلگرامی مذکور ارسال بشه و کلاینت اطلاع پیدا کنه از این مسئله
بعضا دیده شده بعضی از کاربرها تاریخ انقضای اکانت یا حجمش رو یادشون میره و با قطعی سریع به پشتیبان پنل پیام میدن و فکر میکنن مشکل از سمت پنل هست
اینجوری آمادگی قطع شدن لینک رو پیدا میکنن
متشکرم

**Comment by alireza0** [comment]
درود بر شما
متاسفانه برنامه ریزی سیستم جوری نیست که وضعیت کاربر رو ذخیره کنیم. اگر بخوایم پیام بفرستیم هر ۱۰ ثانیه یکبار فرستاده میشه و جایی ذخیره نمیشه که این مشتری یکبار مطلع شده. پیامهای سیستم هم در صورت عدم ارسال پیگیری نمیشن. همه اینها بار روی سیستم رو زیاد میکنه و برای این مدل ساده، این پیچیدگی ها مناسب نیست.

سپاس از همراهی و پیشنهادتون
