### ISSUE TITLE
مسدود نکردن سایت های ایرانی

### ISSUE THREAD

**Issue by amirhellboy** [alireza0/x-ui#313]
سلام خسته نباشید
با اینکه من تیک مسدودسازی دامنه های ایرانی رو زدم و تیک مستقیم رو هم نزدم ولی همچنان سایت www.alibaba.ir داره برام بالا میاد ممنون میشم بررسی بکنید

**Comment by alireza0** [comment]
درود بر شما
همین سایت رو مجددا تست کردم و با مسدود سازی دامنه های ایرانی کاملا بلاک شد.
آیا شما بخش sniffing رو توی سرویس فعال کردین ؟

**Comment by amirhellboy** [comment]
سلام بله فعال هست
من قبلا طبق این لینک جلو میفرتم و خیلی عالی بود ولی از وقتی اخرین ورژن رو نصب کردم دیگه این متد کار نمیکنه ممنون میشم با این سیستم اینو مچ کنید:
https://github.com/iranxray/hope/blob/main/routing.md#%D9%85%D8%B3%D8%AF%D9%88%D8%AF%D8%B3%D8%A7%D8%B2%DB%8C-%D8%A7%D8%B2-%D8%B3%D9%85%D8%AA-%D8%B3%D8%B1%D9%88%D8%B1

**Comment by alireza0** [comment]
توی نسخه جدید براش دکمه گذاشتیم. فقط کافیه فعالش کنید.

**Comment by amirhellboy** [comment]
دقیقا مشکل منم همینه که وقتی سیستم رو اپدیت کردم به کل کدها گیر داد که مجبور شدم ریست پیشفرض رو بزنم بعدش اومدم تیک مسدودسازی دامنه های ایران و ایپی های ایران رو زدم دیدم داره درست کار میکنه ولی روی بعضی سایت ها کار نمیکنه که گفتم alibaba یکی از اونا بود

**Comment by alireza0** [comment]
لطفا الگوی کانفیگ outbound و routing rules رو بفرستید

**Comment by amirhellboy** [comment]
مشکل با اپدیت به 1.3.1 الان برطرف شد 
ممنون از شما

**Comment by alireza0** [comment]
بسیار عالی
موفق باشید
