### ISSUE TITLE
 اضافه کردن بستن سایت های بزرگسال  و اسپید تست

### ISSUE THREAD

**Issue by Bullshark21** [alireza0/x-ui#315]
سلام

لطفا بستن سایت های بزرگسال و اسپید تست رو هم به پنل اضافه کنید

**Comment by alireza0** [comment]
درود بر شما
سایتهای بزرگسال با فعال کردن حالت خانواده قابل انجامه.
بستن تست سرعت حیلی منتطقی نیست. هدف ما وصل کردنه و نه قطع کردن. اگر میخواید بهتره دستی اضافه کنید
