### ISSUE TITLE
هسته های قدیمی تر

### ISSUE THREAD

**Issue by aliwishstar** [alireza0/x-ui#316]
آیا راهی داره بخواهیم از هسته های قدیمی تر مثلا از ورژن ۱.۷.۵ استفاده کنیم یا راهی که بتونیم خودمون کاستومایز کنیم ؟

**Comment by alireza0** [comment]
بهترین روش اینه که نسخه قدیمی این پنل رو نصب کنید
‍‍```
bash <(curl -Ls https://raw.githubusercontent.com/alireza0/x-ui/master/install.sh) 0.5.2
```

**Comment by aliwishstar** [comment]
ممنون ولی منظورم با امکانات جدید پنل با هسته قدیمی هست

**Comment by aliwishstar** [comment]
علیرضا داداش سورس xray core  شما repository که داره پابلیک نیست ؟
