### ISSUE TITLE
Xray Status: error

### ISSUE THREAD

**Issue by AliHasannejad** [alireza0/x-ui#326]
من با نصب پنل دچار این مشکل شدم Xray Status: error
به اخرین نسخه که ارتقا دادم فقط به ورژن 1.80 و 1.81 فقط دسترسی میده
که کلا این دوتا ورژن از کار افتاده ست...
ورژنای قبلی باز کار میکرد ولی این ورژن کلا کار نمیکنه
نمیدونم مشکل از کجاست!

**Comment by alireza0** [comment]
خطای xray رو همیشه میتونید با بردن نشانگر روی علامت سوال کنار Xray Status ببینید.

روی این پنل از نسخه ۱.۰.۰ به بعد، نسخه های قدیمی xray-core و همچنین پروتکل xtls دیگه ساپورت نمیشه.
برای تصحیح، این تنظیمات قدیمی رو تغییر بدید

**Comment by amir-gharajedaghi** [comment]
طبق تجربه ای ک داشتم این مشکل هنگام تعریف کلاینت در قسمت نام ایمیل هنگام rename کردن و تکراری بودن نام ایمیل در بعضی مواقع ک تو پنل جدید اجازه نام ابمیل تکراری داده نمیشه  به وجود میاد ک با پاک کردن کلاینت مشکل در اکثر موارد حل میشه. و در پنل های ورژن قدیمی خطا کنار Xray Status با جزییات کامل و مربوط به کدام کاربر هست نمایش داده میشده ولی در پنل جدید با جزییات کامل خطا رو نمایش نمیده. (خیلی مختصر نمایش میده)
