### ISSUE TITLE
subscription

### ISSUE THREAD

**Issue by justinzoo** [alireza0/x-ui#327]
سلام خسته نباشی
اگه یه توضیحی درمورد سابسکریبشن قسمت جدیدی ک اضافه شده بدید ممنون میشم
مثلا چطور یه دامنه ی جدا واسه ساب ها بزاریم

**Comment by alireza0** [comment]
درود بر شما
شاید متوجه سوالتون نشدم، به هر حال تنظیمات خیلی ساده است.
اسم دامنه سابسکریپشن رو میتونید توی بخش دامنه بگذارید و اگر IP جداگانه ای روی سرور دارید که میخواید فقط روی اون گوش داده بشه، اون رو هم توی بخش ListenIP مشخص کنید. پورت هم که باید روی اون IP مخشص شده تکراری نباشه.
تنظیمات دامنه خودتون رو هم باید قبلا انجام داده باشید.
