### ISSUE TITLE
clone & single port feature

### ISSUE THREAD

**Issue by AmoAlireza** [alireza0/x-ui#328]
سلام
امکانش هست قابلیت clone کردن کاربران موقع clone یک inbound بزارید با این تفاوت که uuid همشون بصورت رندوم generate بشه ولی همه اطلاعاتش مثل email و... مثل قبلی باقی بمونه؟
تنها مشکل اینجاس که اسم email ها نمیشه یکی باشه که من با یه ترفند تونستم اینو دور بزنم که به اسم [ZERO WIDTH SPACE](https://unicode-explorer.com/c/200B) شناخته میشه که آخر هر email میزارم و اگر خواستید به جای تغیرات زیاد توی کد میتونید فقط یه قابلیت بزارید که اگر email وجود داشت بیاد یدونه از ZERO WIDTH SPACE بزاره آخر email جدید.
و قابلیت بعدی که بیشتر افراد درخواست میکنن داشتن یک port برای چنتا inbound که من در مورد fallback یه سری مطالب دیدم ولی اون نیازی که داشتم fallback فراهم نمیکرد اگر امکانش هست این قابلیت هم اضافه کنید.

**Comment by alireza0** [comment]
درود بر شما
امکان تکراری بودن فیلد ایمیل توی این مدل دیتابیس وجود نداره و تغییرش هزینه خیلی زیادی داره.
کپی کردن کاربرها با اطلاعات غیر تکراری هم که میتونه با Bulk درست بشه.

درمورد فالبک من یک سری تغییرات دادم که کار نهایی رو برای شما ساده میکنه.
روش اجراش رو هم امیدوارم دوستان سریع تر به شکل تصویری و ویدیویی درست کنند که راحت بتونید با قدرت بیشتری میتونید انجام بدید.

در حال حاضر پنل های دیگه از طریق همین فالبک روی یک پورت، چند سروریس ارايه میکنند.

**Comment by AmoAlireza** [comment]
علیرضا جان فکر کنم منظورمو متوجه نشدین, درواقع منظورم اینه که اطلاعات کاربر مثل email و لینک ساب هم clone بشه.
در مورد fallback دوستان اگر تجربه استفاده دارن یا خودتون منبعی که آموزش بده دارید حالا با هر زبان بزارید ممنون میشم.
