### ISSUE TITLE
issue with users data usage

### ISSUE THREAD

**Issue by mamdali96** [alireza0/x-ui#33]
I have your x-ui v 2.04 (latest)
And I used with clean install with moving all the clients from old panel to yours
The issues that I'm seeing and facing

The usage counter doesn't work on most of the accounts
And some of them are overused

**Comment by alireza0** [comment]
Dear @mamdali96

Thank you for your kindly report.
In this version ( and lots of other multi-user panels ) you should use complex and unique email to avoid problem of finding email in traffics.
I have found this problem and fixed it recently.
Please change your client's email or wait for my new release.

Thank you so much.

**Comment by alireza0** [comment]
Unfortunately old codes will count the traffic for other users ( first match ) and it is a bad problem.
Sometimes it will delete the trafic row in client_traffic table in database.
Please be aware and fix it by editing inbound and save it again.

**Comment by mamdali96** [comment]
Could you do me solid and explain to me how to fix it In farsi ?

**Comment by mamdali96** [comment]
And I use a specific username/email for each user

**Comment by mamdali96** [comment]
این کار رو انجام دادم ، طبق پیام قبلیت و چند کاربر رو تغییر نام دادم ، ولی فایده نداشت ، آیا لازمه دوباره اکانت هارو از اول بسازم یا انتقال بدم ؟ 

توی پنل 
NidukaAkalanka
این مشکل رو تجربه نکردم (اگه کمکی می‌کنه)

**Comment by alireza0** [comment]
اگر میتونید تنظیمات یک کاربر نمونه رو از دیتابیس برای من بفرستید میتونم بهتر چک کنم
جدول ها:
select * from client_traffics where email='ایمیل کاربر';
select settings from inbounds where id = (select inbound_id from client_traffics where email="ایمیل کاربر");

**Comment by mamdali96** [comment]
سلام ، x-ui.db رو باز کردم با نانو و حتی دانلود کردم توی تکست دیدم ، خیلی از داده ها بهم ریخته و به نوعی
Corrupt 
شده ؟ بخوای میتونم ارسال کنیم

ولی اگه دو خط سالم باشه حدودا ۳۰ خط داره که توش ناسالم هستش و غیر قابل خواندن بود

**Comment by mamdali96** [comment]
تو نسخه اخیر هم که پابلیک کردی امروز ، مشکل هنوز پابرجاست
یک سوال ، روی سرور تازه و خالی از اکانت هم این مشکل ممکنه به وجود بیاد ؟

**Comment by alireza0** [comment]
ممکنه مشکل قبلا به دلیل باگ ها و یا عدم تطابق با پنل های دیگه بوجود اومده باشه.
نمیتونم با اطمینان بگم، ولی میتونم بررسی کنم. تا الان گزارشی در این مورد نگرفتم و بررسی کدهای این بخش به من مشکلی رو نشون نداده.
اگر باگ باشه باید درست بشه و اگر مشکل دیتابیس باشه میتونم راهنمایی کنم که چطور رفع کنید.
