### ISSUE TITLE
Multi domain

### ISSUE THREAD

**Issue by Ptechgithub** [alireza0/x-ui#330]
سلام عزیز برای قسمت مولتی بهتره که  قسمتRequest header اصلاح بشه و بتونه چند تا دامین رو ثبت کنه چون الان اگه مثلا دوتا دامین ثبت کنی و سیو بشه دومی میمونه و اولی پاک میشه. و اگر sni  هم بشه چند تا ثبت کرد که دیگه اوکی هست چون باید به صورت دستی تغییر داده بشه .

**Comment by alireza0** [comment]
درود بر شما
به ازای هر سرویس نمیشه دوتا SNI داشت. اگر میخواید ارتباط مستقیم داشته باشید با چند تا دامنه، میتونید SNI رو خالی بگذارید و مولتی دامین رو با دامین های واقعی پر کنید.
بخش Header رو خودتون بر اساس مدل ارتباطتون تنظیم میکنید.
