### ISSUE TITLE
کانفیگ

### ISSUE THREAD

**Issue by Saeedmhm** [alireza0/x-ui#338]
ممنون از زحماتت، پنل خیلی بهتر شده ولی مشکلی که هست پیچیدگی پنله، که فعلا یکم مبهمه خیلی جاهاش، مخصوصا که مولتی دامین درست کار نمیکنه، و کانفیگها پینگ ندارن

**Comment by alireza0** [comment]
تلاش ما راحت کردن استفاده از xray-core بوده به طوری که نیاز های اتصال رو برای سرور شخصی تامین کنه.
پیشنهاد من اینه که اگر در مورد پروتکل و یا تنظیمات خاصی مشکل دارید با تحقیق و دیدن آموزش های آنلاین میتونید بهترین روش رو پیدا و تست کنید
