### ISSUE TITLE
Telegram new features

### ISSUE THREAD

**Issue by alireza0** [alireza0/x-ui#34]
I am going to add new features in telegram bot usage:
- [x] Fix message length problem
- [x] Find by Email instead of UUID
- [x] Report based on Volume and Date threshold
- [x] Add backup schedule
- [x] Add menu

**Comment by ariandcir** [comment]
Thanks mate, really good stuff.

I think practicality should also be considered. Could there be some sort of tracking mechanism built so a client usage details would only be shown to the respective whitelisted users on telegram for example a reseller and its customer or just the customer? Ultimately the admin of course.

also a feature that would let people to create clients on telegram through the bot would be interesting though I guess to make it practical, there should be some other tracking mechanism like allocating certain amount of money to certain account ids on telegram and then create predefined packages like 30gig 60gig of a particular inbound, if the price for the package is less than or equal to the money allocated to the person, let them create a new config and receive the qr codes and link on the fly.

**Comment by alireza0** [comment]
I am trying to make it powerful but as simple as possible. It supports `api` calls for any change in database. So, this part should only be used for reporting.

Based on your idea, I will try to add:
- [ ] Multi admin `tg_id`
- [ ] Support client reports
- [ ] Use `tg_id` in `email` for clients like `jugTv57@telegramID`
