### ISSUE TITLE
New future for unknown SNI block when tls or xtls or reality enabled

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#340]
this future if enabled blocks unknows sni which are not included in cert files attached to inbound.

the Xray-Core already has this future under the name of "rejectUnknownSni":

Config EX:
```json
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "certificates": [
          ],
          "rejectUnknownSni": false,

          "alpn": [
            "h2",
            "http/1.1"
          ]
        }
```

as I'm not a front-end programmer I cant contribute so I would like you guys add following :

1. a switch under condition of tls , xtls or reality enabled. which makes the "rejectUnknownSni" true or false.

- the default would be false of course.

regards,

**Comment by sudospaes** [comment]
Hi Do you sure reality support rejectUnknownSni ?
I did read Project X Configuration guide but I didn't about rejectUnknownSni in reality object

you can see rejectUnknownSni in TLS Object : https://xtls.github.io/config/transport.html#tlsobject
but it is not found for Reality Object : https://xtls.github.io/config/transport.html#realityobject

**Comment by sudospaes** [comment]
I did add it to panel but its just for TLS, not Reality

**Comment by X-Oracle** [comment]
oh really ?
I didn't try in reality but in theory it should be there since it's functionality can be used in reality too.
Maybe RPRX forgot to add it .
I will open an issue and him about it .

**Comment by sudospaes** [comment]
> oh really ? I didn't try in reality but in theory it should be there since it's functionality can be used in reality too. Maybe RPRX forgot to add it . I will open an issue and ask him about it .

i did add it to this [project](https://github.com/sudospaes/x-ui). you can test that. if that is correct, I will send it to here with request pull

**Comment by X-Oracle** [comment]
Thanks .
I'll try it and let you know how it goes.

**Comment by X-Oracle** [comment]
hi i testedi it 

> > oh really ? I didn't try in reality but in theory it should be there since it's functionality can be used in reality too. Maybe RPRX forgot to add it . I will open an issue and ask him about it .
> 
> I did add it to this [project](https://github.com/sudospaes/x-ui). you can test that. if that is correct, I will send it to here with pull request

nice work but according to [TLS Object](https://xtls.github.io/config/transport.html#tlsobject) it should be inside "tlsSettings" not in "tlsSettings" > "settings"i think moving it there would be better.

and I asked about reality and he said it will not handled by xray anymore the destination site decides to reject or accept it so the option removed for reality.

**Comment by X-Oracle** [comment]
> > hi i testedi it
> > > > oh really ? I didn't try in reality but in theory it should be there since it's functionality can be used in reality too. Maybe RPRX forgot to add it . I will open an issue and ask him about it .
> > > 
> > > 
> > > I did add it to this [project](https://github.com/sudospaes/x-ui). you can test that. if that is correct, I will send it to here with pull request
> > 
> > 
> > nice work but according to [TLS Object](https://xtls.github.io/config/transport.html#tlsobject) it should be inside "tlsSettings" not in "tlsSettings" > "settings". I think moving it there would be better.
> > and I asked about reality and he said it will not handled by xray anymore the destination site decides to reject or accept it so the option removed for reality.
> 
> That's right, I have the same opinion. But it seems to be more standard because it is next to allowInsecure. Because its code is placed in the tlsStreamSettings class. What matters is its performance. Did you get what you need to get?
> 
> If you want, I can rewrite it off as you said.

I checked and I couldn't find anything called settings object under tls object in xray config.

in python we cant call "rejectUnknownSni" in "tlsSettings" > "settings" if we expect it to be in "tlsSettings".
I don't know go but i think its should be the same.

regarding settings object , I think it contains the client configs which is not used in xray server and x-ui only use it to create config links . if that is the case "rejectUnknownSni" defiantly shouldn't be in "settings" object.


i also tried the panel .it seemed xray version 1.8.0 and 1.8.1 is by default rejects unknown sni . it is a bug it is in beta phase anyway and i will report it shortly after this. but I am sure it will work if you do what as I said .

best of luck.

**Comment by alireza0** [comment]
Thanks to @sudospaes 
It is now merged to the main codes
