### ISSUE TITLE
عدم مسدود سازی سایت های ایرانی

### ISSUE THREAD

**Issue by barsamsabbagh** [alireza0/x-ui#344]
با سلام با اینکه کلید بلاک سایت ها و آی پی های ایران رو انتخاب می کنیم اما متاسفانه بلاک نمیشه !؟

**Comment by alireza0** [comment]
مشکل از تنظیمات شما میتونه باشه

**Comment by barsamsabbagh** [comment]
میشه لطفا راهنمایی برای این مورد کنید؟

  تنظیم دیگری باید انجام شود یا پکیج دیگری نصب شود در سرور؟

**Comment by alireza0** [comment]
تنظیمات xray رو ریست کنید و مسدود سازی رو از اول تنظیم کنید. مطمئن باشید بخش sniffing در سرویسها فعال هستند
