### ISSUE TITLE
client_traffics

### ISSUE THREAD

**Issue by straymail** [alireza0/x-ui#345]
سلام

وقت شما بخیر

یک مشکلی که وجود داره اینه که ربات های مدیریت کانفیگ و پنل x-ui برای پاک کردن کانفیگ های منقضی شده نیاز به دسترسی api به جدول client_traffics دارند.
آیا شدنیه؟
پیشنهاد شما چیه؟

تشکر

**Comment by alireza0** [comment]
درود بر شما
از متد getInbounds استفاده کنید که همه اطلاعات رو به شما میده
