### ISSUE TITLE
درخواست داکر پنل نسخه x86-64 

### ISSUE THREAD

**Issue by Aboozarr** [alireza0/x-ui#346]
سلام 
بابت بروزرسانی پنل تشکر میکنم. 
امکانش هست نسخه X86-64 داکر هم ارایه کنید؟

ممنون

**Comment by alireza0** [comment]
درود بر شما
نسخه amd64 ارايه شده. از اون استفاده کنید

**Comment by Aboozarr** [comment]
سلام 
متاسفانه در زمان نصب ارور میده. (روی میکروتیک CHR نصب میکنم).
پنل x-ui دیگه ای بدون ارور نصب میشه اما بدلیل اینکه بروز نیستن قصد نصبشون رو ندارم.

**Comment by alireza0** [comment]
فایل داکر توی پروژه هست. میتونید دستی image خودتون رو بسازید

**Comment by Aboozarr** [comment]
نحوه ساخت image رو خوندم اما متاسفانه تسلط کافی به لینوکس ندارم.
