### ISSUE TITLE
خطا api  برای دستورات add

### ISSUE THREAD

**Issue by spyaea2** [alireza0/x-ui#347]
با پایتون و php  و چندین سرور تست شد
حتی از  [Postman Collection](https://gist.github.com/mehdikhody/9a862801a2e41f6b5fb6bbc7e1326044) هم استفاده کردیم.
لاگین موفق انجام می شود با  api

- **اما دستورات add کار نمی کنه**

- فقط دستور list کار می کنه و خروجی می دهد
-

لطفا بررسی نمایید

**Comment by alireza0** [comment]
لطفا بفرمایید چی رو بررسی کنم؟

**Comment by alireza0** [comment]
منظور من اینه که وقتی مستنداتون کامل نباشه نمیشه بررسی کرد.
بخش سوالاتی که برای هر issue گذاشتم برای پاک کردن نیست و باید بهش جواب داده بشه.
چه نسخه ای دارید ؟ چه پارامترهایی ارسال کردین ؟ چه جوابی گرفتین؟

اصولا مشکل اساسی دوستان با متدهایی شبیه add اینه که به نوع دیتای ارسالی دقت نمیکنن و شماتیک رو رعایت نمیکنن.

بهترین راه یادگیری اینه که همون مدل کار رو با خود پنل انجام بدید و دیتای ارسالی رو چک کنید و دقیقا شبیه همون انجام بدید

**Comment by spyaea2** [comment]
[v1.6.1](https://github.com/MHSanaei/3x-ui/releases/tag/v1.6.1)
این نسخه استفاده میشه
https://gist.github.com/mehdikhody/9a862801a2e41f6b5fb6bbc7e1326044
با این مستندات درخواست ارسال میشه
اما تابع add خطا 404 بر می گرداند فقط دستور list خطا نمی دهد

**Comment by alireza0** [comment]
نسخه ای که استفاده میکنید مربوط به این پنل نیست.
مجموعه کدهایی که استفاده میکنید هم جای دیگری تعریف شده.
لطفا سوالات و گزارش خودتون رو در ریپوزیتوری مربوط به خودش ارائه بدین.
