### ISSUE TITLE
مدیریت پروتکل docodemo با تلگرام

### ISSUE THREAD

**Issue by thisis-sadra** [alireza0/x-ui#348]
سلام وقت بخیر
لطفا فیلد آی دی تلگرام رو به پروتکل docodemo door اضافه کنید
خیلی اپشن کاربردی هست

**Comment by alireza0** [comment]
درود بر شما
چه کاربردی میتونه داشته باشه ؟

**Comment by alireza0** [comment]
این گزینه فقط برای پروتکل های مولتی یوزر کاربرد داره و برای سرویس انجام نمیشه
