### ISSUE TITLE
مشکل قطع اتصال کاربر هنگام افزودن یوزر جدید

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#351]
سلام
وقتی یوزر جدید اضافه میشه کانکشن کاربرها برای یک لحظه قطع میشن که اونم به دلیل ری استارت شدن xray-core برای لود کردن کانفیگ جدید هست
این مشکل با استفاده از xray api قابل حل است و پروژه هایی مثل هیدیفای و مرزبان این مشکل رو از همین طریق حل کردن
با توجه به اینکه x-ui سبک ترین پنل موجود هست حیف هست این باگش حل نشه
قبلا گفته بودید رو یه پروژه ی جدید و مشترک با MHSanaei هستید، نمیدونم اون در چه حال هست اما همین پروژه x-ui هم خیلی خوبه و اگر مشکلات اینچنینی حل بشن
تشکر

**Comment by alireza0** [comment]
درود بر شما
متاسفانه باید کد ها رو کامل ببینید تا متوجه راحت بودن و یا نبودنش بشید.
پنل x-ui کاملا بر اساس تحلیل دیتای JSON پایه گذاری شده. چیزی که golang به شدت توش ضعف داره.
به همین دلیل اکثر کدها در بخش frontend نوشته شده.

برای اینکه بتونیم از API برای ارتباط با x-ui استفاده کنیم یا باید کل پایه کد ها رو تغییر بدیم و یا یه سری کد تبدیل بنویسیم. در هر دو حالت هم زمان زیادی میبره و هم مشکلات زیادش باعث کم شدن پایداری پروژه موجود میشه.
ترجیح خود من اینه که به جای اینکه همه چیز رو شخم بزنم و از اول بنویسم، وقتم رو برای نوشتن پروژه دیگه ای بذارم که بتونه از پایه همه چیز رو متناسب با نیازهای استفاده کننده ها در بیارم و هرچی کمبود بوده رو با پایه مناسب جبران کنم.

استفاده کردن از api خیلی وقته توی ذهن من بوده، ولی حجم زیاد تغییرات مانع شده. با این پیشنهاد شما به این فکر افتادم که حذف/اضافه کردن کاربر ها ( که خیلی بیشتر اتفاق میافته ) رو به صورت ارتباط api تبدیل کنم و بقیه موارد رو به شکل قبلی باقی بذارم.

**Comment by alireza0** [comment]
سپاس از پیشنهادتون
در نسخه جدید اضافه شد

**Comment by arash88** [comment]
این [XrayAPI](https://github.com/crossfw/Air-Universe/tree/master/pkg/XrayAPI) ظاهرا برای اضافه و حذف inbound ها هم کارایی داره.
پیشنهاد میکنم این کلاس inbound.go هم اضافه بشه!

**Comment by alireza0** [comment]
بله. خیلی سخته و باگی میشه با این مدل طراحی دیتابیس.
به همین دلیل تا الان نزدم. اگر بدون باگ درآوردم، حتما اضافه میکنم
