### ISSUE TITLE
استفاده از آیپی نسخه ۶ کنار نسخه ۴

### ISSUE THREAD

**Issue by shahryarjb** [alireza0/x-ui#354]
با درود خدمت شما.
می خواستم سوال کنم آیا امکان این وجود داره که بتونیم هم کانفیگ برای IPV4 و هم برای IPV6 بسازیم؟
روی سرور آیپی وی ۶ هم هست از اونجایی که ایرانسل هم ساپورت می کنه خواستم ازشون استفاده کنم. در  Listening IP  اومدم یکی از سابسنت های IPV6 شو قرار دادم ولی کانفیگی که می سازم مثلا در نرم افزار هایی مثل nekoray و ... ایمپورت نمی شه
تشکر از شما

**Comment by alireza0** [comment]
درود بر شما
بله ساپورت میشه.
فقط همونطوری که در مورد IPv6 میدونید، تعریفش باید به شکل صحیح اعمال بشه ( بین [] باید باشه)
پیشنهاد من اینه که روی دامنه تون رکورد AAAA اضافه کنید.

**Comment by shahryarjb** [comment]
درود مجدد @alireza0 ممنون حتما AAAA می زنم رکوردشو روی دامنه فقط جسارتا امکانش هست یک مثال از موردی که فرمودید یعنی [] بزنید من فکر کنم دارم اشتباه می نویسمش
ببخشید بازم
ممنون

**Comment by alireza0** [comment]
هر جوری که آدرس IPv6 رو بذارید توی بخش Listenning IP ، قبول میکنه، ولی برای درست کردن لینک شما نیاز دارین که اون آدرس کنار بقیه پارامتر ها مثل پورت باشه. پورت با علامت ":" جدا میشه که خب نشونه گزاری IPv6 هم هست.
برای مثلا اگر آدرس سایت شما "2001:4998:24:120d::1:0" باشه و پورت 8080 ،‌باید آدرس رو اینجوری بذارین:
‍```
http://[2001:4998:24:120d::1:0]:8080
```
پس بهتره توی بخش Listening IP حتما از [] استفاده کنید.
لطفا به لینک نهایی دقت کنید.

**Comment by shahryarjb** [comment]
با تشکر از شما جناب @alireza0  اوکی شد هم با AAAA. 
یک مشکلی که دارم اینکه وصل می شم ولی وقتی روی اینترنت می یام آیپیمو چک می کنم هم ipv4 و هم ipv6 رو می یاره. در صورتی که دامنه این روش شما فرمودید ست شده روی ipv6 سرور!!
چطور می شه یک کلاینت فقط روی نسخه ۶ باشه و با اون شناخته بشه!
این پکیج ۶۰ تایی IPv6 رنجشو گرفتم که از نسخه IPv4 محافظت بشه و مسدود نشه
با تشکر

**Comment by alireza0** [comment]
وقتی بعد از اتصال به سرور، IP رو چک میکنید در واقع IP سرور که با استفاده از اون به اینترنت دسترسی دارید رو مشاهده میکنید.
سرور هم از هردو IP خودش استفاده میکنه. 
البته این ربطی به دیده شدن نداره، چون ارتباط شما از ایران به سرور از طریق IPv6 هست ولی ارتباط شما از سرور به اینترنت آزاد از طریق هر دو پروتکل.
اگر میخواید از یکی از اینها استفاده کنید ( توصیه نمیشه) میتونید توی بخش تنظیمات Xray ، استراتژی کلی استفاده از شبکه خروجی مستقیم ( freedom strategy ) رو تغییر بدید.
