### ISSUE TITLE
Not displaying user traffic

### ISSUE THREAD

**Issue by mrjavadseydi** [alireza0/x-ui#355]
after adding few user (30-40) in a single inbound , users traffic is disappeared.

in the console i'm getting this errors :
```
[Error] TypeError: undefined is not an object (evaluating 'clientStats.down')

[Error] TypeError: undefined is not an object (evaluating 'stats.up')
```
 i check the `clientStats`  and there is no record for many users  on that inbound.

<img width="1184" alt="Screenshot" src="https://github.com/alireza0/x-ui/assets/59200320/875c2236-5eb4-4460-9a62-d1231bf17d15">

in the x-ui logs i have this warning : 
``` WARNING - AddClientTraffic update data  empty slice found```

**Comment by alireza0** [comment]
It seems these users configured with abnormal way.
I don't understand:
1. Why you wipe all needed data out! What should we understand from wiped picture ?
2. The word -few- between 30 and 40 means that you expect this system to work at least 1k per inbound!

If clientTraffic table hasn't some data, this means there are some errors in `email` definition (which is wiped in your picture).
This warning message in logs sounds same problem.

**Comment by mrjavadseydi** [comment]
sorry for that , i didn't know you need that 

<img width="1205" alt="Screenshot 2023-06-01 at 11 40 47 PM" src="https://github.com/alireza0/x-ui/assets/59200320/6d0c30d0-9a9e-481a-bfb1-fddba0e33e37">


2-3 inbound for company employees  with cloudflare open ports

in total 40 active users

**Comment by alireza0** [comment]
Did you add the clients with an API call ?
Look like another tool added these data!

BTW: You can fix it by running migration process:

```
/use/local/x-ui/x-ui mirgate
```

**Comment by mrjavadseydi** [comment]
yes i add clients  with api 

thanks it's work !
