### ISSUE TITLE
امکان محدود کردن یوزر

### ISSUE THREAD

**Issue by Benserver24** [alireza0/x-ui#358]
سلام

امکان محدود کردن تعداد یوزر برای هر کانفیگ وجود نداره توی آخرین ورژن؟

**Comment by misagh72** [comment]
از اول وجود نداشته و اضافه هم نخواهد شد این  پنل برای مصرف شخصی هست 
میتونید برای این محدودیت پنل سنایی رو استفاده کنید

**Comment by Benserver24** [comment]
عالی ممنونم

**Comment by mshaterzadeh** [comment]
البته پنل سنایی هم قسمت کنترل تعداد یوزهاش عملا کار نمیکنه
