### ISSUE TITLE
letting only few domains use proxy

### ISSUE THREAD

**Issue by The13east** [alireza0/x-ui#360]
Hi , I want to create a service using your panel so it can direct all the traffic from the normal internet and direct only 1 website through the proxy . I tried reading the documentation in xtls git but I'm too much of a noob ! 

Slm bache ha ! man ghasd daram ye service free run konam ke baraye marhale aval faghat twitch.tv ro ba proxy baz kone vali baghie site haro be soorat direct baz kone ya hata block kone vali gashtam o khoondam natoonestam befahmam ke chejoori kar mikonan chon be code ke mirese yekam noobam ! age kasi mitoone komak kone mamnoon misham 
[Template.txt](https://github.com/alireza0/x-ui/files/11645598/Template.txt)

**Comment by alireza0** [comment]
Hello.
It is only possible in client application.
Alternatively, you can use direct connections in 1st server when you use two servers connecting with tunels.
