### ISSUE TITLE
Add reality short id auto generation

### ISSUE THREAD

**Issue by p19lord** [alireza0/x-ui#361]
**Is your feature request related to a problem? Please describe.**
زمان ایجاد کانفیگ reality داخل تنظیمات short id به صورت اتوماتیک نیست و باید به صورت دستی ایجاد بشه.

**Describe the solution you'd like**
لطفا برای تنظیمات reality تدبیری انجام بشه که shortid به صورت اتوماتیک جاگذاری بشه

**Comment by alireza0** [comment]
انجام شد
لطفا برای اعمال تغییرات منتظر نسخه بعدی باشید و یا به صورت دستی کمپایل کنید.

**Comment by p19lord** [comment]
خیلی ممنون
پنل بسیار خوبی هستش
یه موضوع هم که به نظرم اضافه شدنش بد نباشه WARP هستش توی ChatGPT و Netflix بسیار بسیار کارایی داره. اون رو هم داخل اسکریپت و پنل جای بدید بسیار بسیار عالی میشه.

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و محبتتون

این پروتکل ها رو دستی میتونید اضافه کنید. اینجوری هرکسی که اطلاعات کافی
داره با قبول دردسرهاش میتونه استفاده کنه.
من ترجیح میدم این مدل تنظیمات پیشرفته توی پنل نباشه، چون ناخواسته کاربر رو
درگیر تنظیمات سنگین میکنه.
به جای اون میتونید از IPv4 strategy استفاده کنید و معمولا همه این مشکلات حل
میشه
Yours Cordially
Alireza Ahmadi
