### ISSUE TITLE
"/addClient/"

### ISSUE THREAD

**Issue by mohamadfarahani** [alireza0/x-ui#362]
minor problem.
there is nothing in the API documentation table as to specifying where the request should add the client it just says "/addClient/"
to what inbound and how to specify that are not clear
 
btw: honestly love and appreciate your work you're doing such a great service

**Comment by alireza0** [comment]
You are right! The documentation is not enough.
It is about a small project and everyone tried to find their solutions by try-failure :/ .
For API usage, I will try to describe it more simple as soon as possible.

**Comment by AmoAlireza** [comment]
![add](https://github.com/alireza0/x-ui/assets/79990596/e2551968-39a0-49e9-930f-0704317bea5a)
