### ISSUE TITLE
راهکار برای مسدود سازی سایت ها و آی پی های ایرانی

### ISSUE THREAD

**Issue by barsamsabbagh** [alireza0/x-ui#363]
با سلام 
لطفا یکبار درمورد بند کردن آی پی ها و سایت های ایرانی راهنمایی کنید ؟

**Comment by p19lord** [comment]
`nano /etc/hosts`
بعد خط زیر رو اضافه کنید
`127.0.0.1 speedtest.net`

**Comment by p19lord** [comment]
#344

**Comment by arshambh** [comment]
سلام 
این قسمت دایرکت کردن آی پی یا سایت های ایرانی میشه بگید کدوم بخش از پنل باید تنظیم شود؟
بخشی که این قابلیت باید فعال کنم پیدا نکردم
تشکر

**Comment by alireza0** [comment]
دایرکت کردن برای سرورهای ایران هست که تانل شده.
اینجوری همه ترافیک کاربرها به تانل ارسال میشه به جز ترافیک دایرکت شده مثلا برای ایران
