### ISSUE TITLE
مشکل ساخت یوزر reality 

### ISSUE THREAD

**Issue by AmirPY82** [alireza0/x-ui#364]
سلام و عرض خسته نباشید
من زمانی که میخوام با استفاده از api، یوزر جدید reality اضافه کنم، وقتی با random string فیلد های privatekey و publickey رو به api میدم، یوزر ایجاد میشه و مشکلی نداره ولی آپلود و دانلود نمیده و کار نمیده زمانی که داخل پنل ادیتش میزنم و generate new key میزنم اوکی میشه مشکلش
این باید چه فرمت خاصی داشته باشه تا مشکلی نباشه و وصل بشه؟

**Comment by alireza0** [comment]
درود بر شما
بله. این دو فیلد باید حتما گواهی دیجیتال از نوع X25519 باشند.
برای دریافت این مقادیراز خود xray-core استفاده کنید. برای مثال در نسخه لینوکس:
```bash
/usr/local/x-ui/bin/xray-linux-amd64 x25519
```

**Comment by AmirPY82** [comment]
ممنونم بابت پاسخ و پروژه خوبتون، لطف کردید.
