### ISSUE TITLE
Adding a feature for opening and closing ports in UFW while creating or deleting an inbound

### ISSUE THREAD

**Issue by GoldExynos** [alireza0/x-ui#365]
It would be great if we could have this feature on the panel. So, when we create and delete an inbound, the process will check if UFW is enabled and if it is, it automatically edits the UFW rules for opening and closing ports.

**Comment by alireza0** [comment]
UFW is not a common firewall app in all supported operation systems.
Generaly it is on the shoulder of infrastructure manager.

It is strongly recommended to install x-ui in minimize OS to use the maximum performance.
But if you need to enable firewall, it is better to open a range of ports and pre-define it in firewall.
