### ISSUE TITLE
کسی متوجه این کانفیگ میشه؟

### ISSUE THREAD

**Issue by jamiekarvans** [alireza0/x-ui#366]
سلام بنده یه کانفیگ خریدم که هرچی فکر میکنم نفهمیدم این دوستمون چیکار کرده میشه لطفا یک نگاه کنید و بگید چه اتفاقی افتاده و چطور میشه همچین کانفیگی ساخت؟

> vless://8c8ec53b-e054-45bf-d290-2f8b42c3c3ee@snapp.market:8080?encryption=none&security=none&type=ws&host=hakimkhan.top&path=%2F#User2-5594

مشکل من اینجاس که نمیفهمم چرا اطلاعات به snapp.market ارسال میشه؟ و چطور امکان داره؟ اینم بگم پینگی که سرور میده خیلی پایین تر سروری هست که خودم میسازم با این حال که دامین هم سرورم داره
و اینکه کلا برای کاهش پینگ سرور چه کاری پیشنهاد میکنید

**Comment by dreamboxone** [comment]
این کانفیگ CDN‌اروان هست. شما وقتی از CDN‌اروان به صورت WS  استفاده میکنی میتونی در قسمت ادرس یک سایت که اون هم از اروان استفاده میکنه بزاری مثل snapp.market یا حتی Arvancloud.ir و غیره

**Comment by jamiekarvans** [comment]
> این کانفیگ CDN‌اروان هست. شما وقتی از CDN‌اروان به صورت WS استفاده میکنی میتونی در قسمت ادرس یک سایت که اون هم از اروان استفاده میکنه بزاری مثل snapp.market یا حتی Arvancloud.ir و غیره

سلام آره منم حدس زدم اینطور باشه واسه همین رو سرور خودم همین کارو کردم ولی جواب نمیده، از cdn آروان استفاده میکنم و توی کانفیگ هم قسمت ws تامین خودمو می‌زارم و تو قسمت سرور اصلی snapp.market  می‌زارم ولی جواب نمیده
تنظیمات خاصی باید توی پنل انجام بدم یا کانفیگ و طوری دیگه باید تنظیم کنم تو سرور؟

**Comment by rahman8521** [comment]
تو cdn اروان چون همگاری داره با اوپراتورها
