### ISSUE TITLE
چطور میشه ادرسی رو در برای سایتهای ایرانی اضافه کرد؟

### ISSUE THREAD

**Issue by dreamboxone** [alireza0/x-ui#369]
سلام
فایل iran.dat به اندازه کافی کامل نیست و برخی سایتها باید بهش اضافه بشه تا بشه از قابلیت اتصال مستقیم کشور ایران واقعا استفاده کرد. چطور میشه برخی سایتها رو بهش اضافه کرد؟
چه تو پنل چه تو فایل؟
ممنون

**Comment by sudospaes** [comment]
You can use manual list to block some ips and domains

**Comment by dreamboxone** [comment]
> You can use manual list to block some ips and domains

Thanks but what is the entry format. please kindly elaborate more

**Comment by sudospaes** [comment]
> > You can use manual list to block some ips and domains
> 
> Thanks but what is the entry format. please kindly elaborate more

JSON Array

```
[
   "your domian or ip"
]
```
for example : 
```
[
  "google.com",
  "youtube.com"
]
```
