### ISSUE TITLE
مشکل در لینک subscriptions

### ISSUE THREAD

**Issue by LiamAghamohammadi** [alireza0/x-ui#371]
سلام وقت بخیر، خسته نباشید
یک باگی در لینک های subscriptions وجود داره:
زمانی که ما allow insecure رو داخل پنل روشن میکنیم و لینک از subscriptions میگیریم داخل ایفون و برنامه شدوراکت بدون هیچ مشکلی سرور اضافه میشه و اوکیه، روی ویندوز و نکوری هم همینطور ولی روی اندروید و برنامه v2rayng وقتی سرور اضافه میشه allow insecure خاموش هست پیش فرض و وقتی کاربر دستی اون رو روشن میکنه بعد یه مدت که اتومات اپدیت میشه دوباره خاموش میشه. انگار برنامه v2rayng از لینک subscriptions نمیتونه متوجه بشه باید allow insecure روشن باشه.

**Comment by sudospaes** [comment]
This is probably a v2rayNG bug. I tested subscriptions link generator again. its ok.

**Comment by X-Oracle** [comment]
v2rans 1.7.5+ can read '''allow insecure''' in config links otherwise it ignores that section.
