### ISSUE TITLE
امکان اضافه کردن پخشی به نام دامنه 

### ISSUE THREAD

**Issue by r-sbr90** [alireza0/x-ui#374]
سلام 
میخواستم درخواست کنم یک بخش به نام دامنه (مثل پنل هدیفای) اضافه کنید که بتوان برای روشی مثل reality  چند تا sni مختلف تعریف کنیم 
آخه بعضی از sni ها برای یک نت جواب میدهد و برای نت دیگر نه 
ولی اگر چند تا بتوان داشت کاربر تست میکند و اون که بهتر هست را انتخاب میکند 
امیدوارم منظورم را درست بیان کرده باشم

**Comment by misagh72** [comment]
الان هم میشه شما توی قسمت servername با استفاده از , کاما می تونید چندتا Sni مختلف اضاقه کنی

**Comment by r-sbr90** [comment]
چه جور میتوانید برایم اسکرین بگیرید 
بعد از ذخیره برای هر sni یک کانفیگ جدا می‌سازد یا رندم به یکی از آنها وصل میشود

**Comment by misagh72** [comment]
هیچ کدوم خودتون باید توی کانفیگ تغییر بدین به sni مورد نظر

**Comment by r-sbr90** [comment]
منظورتون تو بخش اول هست که دامنه را با 443 میزنیم یا بخش دوم

**Comment by misagh72** [comment]
بخش دوم دوست عزیز

**Comment by r-sbr90** [comment]
ممنون بابت راهنمایی 🙏
