### ISSUE TITLE
 روی یک سری کانفیگ ها تا نریم تو اپلیکیشن واتساپ پیام ها نمیاد 

### ISSUE THREAD

**Issue by mehradraissi** [alireza0/x-ui#379]
سلام روی یک سری کانفیگ ها بعضی وقتها هم روی همه PUSH NOTIFICATION  ها انگار کار نمیکنه و این مشکل فقط روی این پنل هست. من از تروجان پنل هم استفاده میکنم اون مشکلی نداره. ممنونم

**Comment by alireza0** [comment]
درود بر شما
تروجان پنل هسته و تنظیمات متفاوتی داره.
این مشکلات بیشتر مربوط به تنظیمات و نحوه استفاده است.

**Comment by mehradraissi** [comment]
ممنونم از پاسختون. کانفیگ خواصی رو پیشنهاد میدید که اون رو ستاپ کنم که  این مشکل حل بشه ؟
