### ISSUE TITLE
[Feature]: Fallback support

### ISSUE THREAD

**Issue by nimagp** [alireza0/x-ui#382]
**Is your feature request related to a problem? Please describe.**
It is very time consuming to define an inbound along the users and fallback settings by hand and debug the load-balancer as well
**Describe the solution you'd like**
Another field in inbound settings to allow adding fallbacks for vless/trojan on tcp.
**Describe alternatives you've considered**
Editing configuration by hand
**Additional context**

**Comment by X-Oracle** [comment]
you can do fallback on vless/trojan tcp . what is the problem ?

**Comment by sudospaes** [comment]
> امیدوارم رو نسخه بعدی بشه بدون TLS از Fallback استفاده کرد

it is easy. Just remove inbound.tls from v-if and use return again without tls.

<img width="394" alt="Screenshot 2023-06-11 165934" src="https://github.com/alireza0/x-ui/assets/79229394/de2948dd-23a6-4139-a1cb-5f91d0b9ce2e">

**Comment by alireza0** [comment]
fallbacksItem is optional and can only be used for TCP+TLS transport combination

[Reference](https://xtls.github.io/config/features/fallback.html#fallbackobject)
