### ISSUE TITLE
shadow socks ورژن قدیم

### ISSUE THREAD

**Issue by mohamadn69** [alireza0/x-ui#383]
سلام.

داخل نسخه جدید چرا شدو ساکس نسخه قدیمی حذف شده . نیازش دارم توی نسخه سنایی و نسخه شما حذف شده اگه میشه اضافش کنید
تعدادی از کاربرهام روی شدو کار میکنن به خاطر همین نمیتونم بیام روی پنل شما دیتابیس  نسخع های قدیم را نمیخونه

**Comment by misagh72** [comment]
به دلیل اینکه بدرد نمیخوره حذف شده شما چرا اصرار دارین استفاده کنید

**Comment by mohamadn69** [comment]
من بصورت ریورس پروکسی کار میکنم و سرور اصلی که کاربرهام روشه ایرانه به خیلی ها مخصوصا گوشی آیفون قدیمی که نمیتونن napsernet و ...  نصب کنن شادوساکس فروختم و بدون مشکل کار میکنه. نیازش دارم

**Comment by misagh72** [comment]
ورژن های قدیمی رو فقط منیتونید نصب کنید

**Comment by alireza0** [comment]
@mohamadn69 

در نسخه جدید اضافه خواهد شد
