### ISSUE TITLE
speed limit

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/x-ui#387]
سلام عزیز
با توجه به اینکه سرور های ایران خیلی محدود هستند و سرعت پایینی دارند (برای تونل کردن) به نظرم اگر محدودیت سرعت دانلود و آپلود بشه اضافه کردن برای تمام کاربران و اشتراک ها خیلی از مشکلات سرعت پایین رو میشه حل کرد

با تشکر

**Comment by alireza0** [comment]
درود بر شما

این پنل تنظیمات مربوط به xray رو تا حدودی برای کاربر نهایی ساده میکنه. امکاناتی که خود هسته پشتیبانی نمیکنه از عهده پنل خارجه.
لطفا از طریق نرم افزار های دیگه در سطح سیستم عامل اقدام کنید.

**Comment by emadtoranji** [comment]
یعنی هیچ راهی نیست که بشه سرعت کاربر رو از خود پنل x-ui محدود کرد؟!

**Comment by alireza0** [comment]
راه زیاده! عرض کردم بهتره از نرم افزار های جانبی استفاده کنید.
تا الان، xray-core راهی برای محدود کردن کاربر ارائه نداده و به نظر نمیاد بخواد ارائه بده.
