### ISSUE TITLE
چند سوال برای استفاده از x-ui

### ISSUE THREAD

**Issue by ehsanfotoo** [alireza0/x-ui#388]
سلام وقت بخیر. چند سوال دارم:
**1-** برای نصب SSL چهار عدد کامند نوشتید. آیا SSL به صورت اتوماتیک تمدید میشود؟
**2-** آیا استفاده از دامین مسدود نشدن ip سرور را کاهش میدهد؟ اگر دامین ir استفاده کنم مشکلی پیش میاد؟ یا بهتره پسوند دیگه ای باشه؟
**3-** اگر SSL نصب نکنم ، باعث میشود ip سرور سریعتر شناسایی و مسدود شود؟ یا فقط در امنیت تبادل اطلاعات اثر میگذارد؟
**4-** برای استفاده 3 تا 5 نفر آیا استفاده از یک سرور خارج مثل آلمان کافیه؟ یا حتماً باید سرور ایران تهیه کنم و تانل بزنم؟
**5-** راهی وجود دارد که برخی از ip ها یا URL ها را تعریف کنم که بدون استفاده از x-ui به آن وصل شوم؟ مثلاً همه ip های ایران را allow کنم که به صورت اتوماتیک تشخیص دهد که اگر سایتی مثل سایت بانکها که ip ایران دارند را باز کردم ، با ip واقعی خودم متصل شوم نه ip که در x-ui تعریف کردم.
**6-** آیا نیاز به نصب وب سروری مانند nginx است؟ تاثیری در سرعت دارد؟
**7-** آیا راهکاری سراغ دارید که مسدود شدن ip سرور را بسیار کاهش دهد؟

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و توجهتون.
هدف از فعال کردن بخش issue ، مباحث مربوط به کد پنل بوده. سوالاتتون در مورد پنل نیست و خیلی عمومیه. بهتره جواب سوالات رو از فوروم ها و مطالب منتشر شده توسط دوستان با تجربه پیگیری کنید.
