### ISSUE TITLE
نمایش حجم و انقضا در Subscription 

### ISSUE THREAD

**Issue by usamirali** [alireza0/x-ui#389]
سلام و خسته نباشید لطفا راه کاری برای نمایش حجم و تاریخ قرار بدید بجز تلگرام
مثلا داخل ساب یا چیز دیگه ای و اگه راه کاری هست ممنون میشم بگید که انجام بدم

**Comment by alireza0** [comment]
درود بر شما
حجم و تاریخ توسط هدر ها به صورت استاندارد روی ساب ارائه شده.
لطفا از نرم افزاری که هدرها رو ساپورت میکنه استفاده کنید.

**Comment by usamirali** [comment]
میشه برنامه که ساپورت میکنه برای اندروید و ایفون معرفی کنید 
من یه چیزی تو مایه های پنل مرزبان منظورم هست

**Comment by alireza0** [comment]
HiddifyNG
Shadowrocket
clash

**Comment by usamirali** [comment]
دستت درد نکنه و اینکه واقعا ازت ممنونم که داری این پنل رو توسعه میدی برای ما
امیدوارم ایرانی ازاد داشته باشیم

**Comment by X-Oracle** [comment]
Oh I see it is in header.

But the applications supporting it is fewer than the ones not supporting it and users prefer to use v2rayng and napsternetV rather than those apps.

Having a fake config which has these info in its name is better for majority of xray clients.

Anyway thanks for the info .

**Comment by alireza0** [comment]
@X-Oracle

You are right! I am thinking a better way to add this feature as an option :D
Your nice idea in #376 is good enough to work on it. Thanks!
