### ISSUE TITLE
Bot cpu warning enhancement 

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#392]
It is a great feture.

If we can have the 3 most cpu intensive services sent to us when the percentage reaches the limit we set in settings will be much more usefull.

I can already do it with ```top``` command . But some times it's too late to check .

**Comment by alireza0** [comment]
I am not agree with this option. It is related to the OS instead of panel and xray.

**Comment by X-Oracle** [comment]
@alireza0 
> It is related to the OS instead of panel and xray.

I don't agree with not having this future because of it is a OS related .
I mean it will make the ```CPU warning``` future more helpful. (it is not always xray or x-ui that uses the cpu anyway)

but if you are not willing to then I'm ok .

anyway I'm glad I can share my opinion with you.
thanks for your attention.
