### ISSUE TITLE
مشکل نشان عدم محاسبه ترافیک کاربران shadowSocks

### ISSUE THREAD

**Issue by MD-97** [alireza0/x-ui#394]
حجم مصرفی اعمال نمیشه برای کاربرا

**Comment by alireza0** [comment]
سپاسگزارم از همراهی و ثیت مشکل
اطلاعات ارسالی کامل نیست.
لطقا قبل از باز کردن باگ جدید از وجود باگ مطمئن بشید. لاگ ها و همه اطلاعات لازم رو آماده کنید و بعدش ارسال کنید.
