### ISSUE TITLE
Conditions for <<depleting soon>> flag

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#396]
It is not clear when does a config will be flagged as ```depleting soon```.
can you explain about it ?

also is there a way for us to make custom condition for it ?

**Comment by alireza0** [comment]
You can set traffic/expiration threshold in main page of panel configuration.
When these threasholds are reached, `depleeting soon` will be on.

**Comment by X-Oracle** [comment]
SO those two entries related to ```depleting soon``` !!
I didn't know . 

thanks for your attention .
