### ISSUE TITLE
Flow Usage Enhancements

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#397]
I think we can have more detailed in the following sections . or something like that .

![image](https://github.com/alireza0/x-ui/assets/129892464/fd7b9459-67ca-4b52-957f-e22c74c0f337)

Reason : I have to do math to tell others how much of their flow is remaining.
like : Total - ( upload + download )
and it sometime gets harder to do. ( I'm slow at math 😅)

if you value this. Consider this in your free time sir . 

Thanks.

**Comment by alireza0** [comment]
This option is now added beside small simplification of showing traffic in table.
In table you can see only `used` and `total` traffic and additional traffic data (up/down/remaining) in `popover` object.
![image](https://github.com/alireza0/x-ui/assets/12573084/5bf8c3cb-bf9e-40f0-b96c-c3c44d11b161)

In addition, you can find it better in client information modal page.
![image](https://github.com/alireza0/x-ui/assets/12573084/b65bec7a-56dd-4b84-a892-80ee28b7a83d)

These changes will be available in next release.

**Comment by X-Oracle** [comment]
Nice .

It seems it will trigger when hover mouse pointer on it.
Is it going to work on a phone which we can't hover?

Thanks for your attention.

**Comment by alireza0** [comment]
Yes. Despite you can see it in info modal, it is also possible to tap on this tag in mobile browser.

**Comment by X-Oracle** [comment]
> Yes. Despite you can see it in info modal, it is also possible to tap on this tag in mobile browser.

good to hear . it will be a great help .
