### ISSUE TITLE
کار نکردن Direct Domains

### ISSUE THREAD

**Issue by ehsanfotoo** [alireza0/x-ui#402]
سلام
وقتی از طریق پنل x-ui در قسمت Xray Configurations از تبهای Manual Lists یا Complete Template دامینهایی را به Direct Domains اضاف میکنم ،  دایرکت نمیشوند و همچنان در حالت پروکسی قرار دارند. اما وقتی از طریق نرم افزار v2rayN برای ویندوز ، این دامینها را در whitelist قرار میدهم ، دایرکت میشوند.
آیا برای اینکه دامینهایی را در سرور دایرکت کنم ، باید از همین قسمت Direct Domains اقدام کنم؟
هدف اینه که برای همه کاربرهایی که وصل میشوند ، این دامینها دایرکت شوند که نیاز نباشد کاربر کانفیگی انجام دهد.

**Comment by nimagp** [comment]
همچین قابلیتی نداره xray-core
باید سمت کلاینت انجام بشه

**Comment by alireza0** [comment]
درود بر شما
دایرکت کردن دامنه و IP سمت سرور انجام میشه و برای انجام دادن سمت کاربر باید خود کاربر این کار رو انجام بده.
وقتی کاربر شما به سرور خارج متصل میشه همه ترافیکش دایرکت از سرور خارج میشه.
این تنظیمات برای کسانی قابل استقاده است که مثلا سرور ایران و خارج دارند و ترافیک کاربران سرور ایران رو از طریق تانل v2ray به سرور خارج میفرستن.
اینجوری میتونید این ترافیک ها رو به جای فرستادن به تانل، از خود سرور به صورت دایرکت خارج کنید.

**Comment by ehsanfotoo** [comment]
> درود بر شما دایرکت کردن دامنه و IP سمت سرور انجام میشه و برای انجام دادن سمت کاربر باید خود کاربر این کار رو انجام بده. وقتی کاربر شما به سرور خارج متصل میشه همه ترافیکش دایرکت از سرور خارج میشه. این تنظیمات برای کسانی قابل استقاده است که مثلا سرور ایران و خارج دارند و ترافیک کاربران سرور ایران رو از طریق تانل v2ray به سرور خارج میفرستن. اینجوری میتونید این ترافیک ها رو به جای فرستادن به تانل، از خود سرور به صورت دایرکت خارج کنید.

با سرور ایران تانل زدم به سرور خارج.
دایرکت دامین را از طریق نرم افزار انجام دادم اما میخواهم روی سرور ست کنم که نیاز نباشه هر کاربر دایرکت دامین انجام بده.
از کدام قسمت از پنل x-ui یا از کدام فایل در سرور میتوانم آدرس وبسایتها را قرار دهم که دایرکت شوند؟
---------------------
سوال دوم اینه که از سرور ایران فقط برای تانل استفاده میکنم. آیا نیازی است روی این سرور SSL نصب کنم؟
آیا SSL های رایگان تفاوتی با SSL های پولی دارند؟

**Comment by alireza0** [comment]
1. روی سرور ایران
2. بستگی به خودتون داره، ولی سرورهای ایران در حال حاضر بررسی و فیلتر نمیشن که نیاز به TLS داشته باشه
3. از نظر کارایی تفاوتی ندارند ولی معمولا از نظر زمانی متفاوت هستند. مثلا letsencrypt به شما ۹۰ روزه میده

**Comment by ehsanfotoo** [comment]
> 1. روی سرور ایران
> 2. بستگی به خودتون داره، ولی سرورهای ایران در حال حاضر بررسی و فیلتر نمیشن که نیاز به TLS داشته باشه
> 3. از نظر کارایی تفاوتی ندارند ولی معمولا از نظر زمانی متفاوت هستند. مثلا letsencrypt به شما ۹۰ روزه میده

روی سرور ایران به جز کامندهای زیر چیزی اجرا نیست یا چزی نصب نیست که بخواهم دامین تعریف کنم. آیا لینکی دارید که توضیح بده چطور در سرور ایران دامین برای دایرکت کردن قرار دهم؟
sysctl net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -p tcp --dport 22 -j DNAT --to-destination IRAN-IP
iptables -t nat -A PREROUTING -j DNAT --to-destination Kharej_ip
iptables -t nat -A POSTROUTING -j MASQUERADE

**Comment by alireza0** [comment]
دوست عزیز، این مدل port forward اصلا تانل نیست! به کاربردن این اصطلاح برای این مدل اشتباهه.
توی این روش هیچ کاری نمیتونید بکنید. عملا یه سرور واسط گذاشتین برای ارسال ترافیک به سرور خارج.
روی سرور ایران باید پنل نصب کنید و کاربراتون رو اونجا تعریف کنید.
برای اتصال به سرور خارج، اگر سرورتون فیلتر نیست پیشنهاد میکنم از [ریلیتی](https://github.com/XTLS/REALITY) استفاده کنید.

آموزشش رو ثنایی عزیز [اینجا](https://t.me/panel3xui/65) گذاشتن.

**Comment by ehsanfotoo** [comment]
طبق ویدیوهای youtube این مورد را انجام دادم. پس اشتباه آموزش دادند.
سوالات آخرم اینه:
1- باید پنل شما را هم روی سرور ایران و هم روی سرور خارج نصب کنم. درسته؟
2- سپس طبق آموزش آقای ثنایی کار را انجام دهم. درسته؟
3- برای دایرکت کردن دامینها باید از طریق پنل شما که بر روی سرور ایران است ، دامینها را قرار دهم تا دیگر نیاز نباشد کاربرها به صورت دستی دامینها را روی v2rayng ست کنند. درسته؟

**Comment by ehsanfotoo** [comment]
> دوست عزیز، این مدل port forward اصلا تانل نیست! به کاربردن این اصطلاح برای این مدل اشتباهه. توی این روش هیچ کاری نمیتونید بکنید. عملا یه سرور واسط گذاشتین برای ارسال ترافیک به سرور خارج. روی سرور ایران باید پنل نصب کنید و کاربراتون رو اونجا تعریف کنید. برای اتصال به سرور خارج، اگر سرورتون فیلتر نیست پیشنهاد میکنم از [ریلیتی](https://github.com/XTLS/REALITY) استفاده کنید.
> 
> آموزشش رو ثنایی عزیز [اینجا](https://t.me/panel3xui/65) گذاشتن.

طبق ویدیوهای youtube این مورد را انجام دادم. پس اشتباه آموزش دادند.
سوالات آخرم اینه:
1- باید پنل شما را هم روی سرور ایران و هم روی سرور خارج نصب کنم. درسته؟
2- سپس طبق آموزش آقای ثنایی کار را انجام دهم. درسته؟
3- برای دایرکت کردن دامینها باید از طریق پنل شما که بر روی سرور ایران است ، دامینها را قرار دهم تا دیگر نیاز نباشد کاربرها به صورت دستی دامینها را روی v2rayng ست کنند. درسته؟

**Comment by alireza0** [comment]
1. بله
2. بله
3. بله. درسته. اینجوری ترافیک کاربرها از سرور ایران به مقصد میره. جزو ترافیک اونها و سرور ایران محصوب میشه
