### ISSUE TITLE
[Feature]: Multiple TLS certificates support

### ISSUE THREAD

**Issue by nimagp** [alireza0/x-ui#403]
**Is your feature request related to a problem? Please describe.**
In some cases you can't have xray-core operate on multiple domains with the current certificate input
 (While xray-core supports multiple certificates)
**Describe the solution you'd like**
Turning the certificate input to a list. 
**Describe alternatives you've considered**
Get a multi-domain certificate.
**Additional context**

**Comment by alireza0** [comment]
Hello @nimagp 
Multi TLS is already supported.
