### ISSUE TITLE
multi domain + multi sni

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/x-ui#405]
سلام وقتت بخیر عزیز

از اونجایی که معمولا هر دامنه (آیپی) با sni های جداگانه کار میکنه به نظرم اضافه کردن مورد زیر خیلی میتونه کاربردی باشه:

برای هر دامنه ای که در پنل اضافه میکنیم بتونیم یک sni جداگانه هم تعریف بکنیم؛ که هم لینک هامون اختصاصی تر بشه و هم بخش subscription کامل تر بشه.

با تشکر از شما

**Comment by mohamad6996** [comment]
سلام برای ثبت دامنه و sni میشه کمکم کنید و توضیحاتی بمن بدید

**Comment by alireza0** [comment]
درود بر شما
بخش مولتی دامین برای اتصال از چندین سرور به سرور اصلی استفاده میشه.
برای هر SNI باید سرویس مجزایی ایجاد کنید و یا خالی بگذارید.

**Comment by emadtoranji** [comment]
درواقع میخوام چندین لینک در یک اشتراک وجود داشته باشه با sni های مختلف.
اکثر پنل ها این آپشن رو دارن. چون هر اپراتوری با یک sni خاص اتصال بهتری داره

**Comment by alireza0** [comment]
این موردی که میفرمایید با مولتی دامین قابل انجامه.
مولتی SNI برای زمانیه که شما میخواید پشت پراکسی ( مثلا کلادفلر ) به چند تا دامنه ( سرور مجزا ) برسید.
جهت اطلاع: در نسخه TLS1.3 پارامتر SSNI داریم که انکریپت شده و قابل دیدن توسط اپراتور نیست.
