### ISSUE TITLE
Add fallback option is hidden for vless and only shown for TLS

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [alireza0/x-ui#408]
Many thanks for your efforts. 

**Describe the bug**
(Unlike some other x-ui derived panels) The "add fallback" option (button) in `add inbound` window, is initially hidden for `vless `protocol, unless security is set to `TLS`.  This is in spite of `vless` supporting fallbacks either with no encryption set or with `reality `(as well as TLS).

**Expected behavior**
IMHO, add fallback should (almost) always be visible for vless-type inbounds. It should be possible to define fallbacks on a vless inbound which uses reality security, TLS security or no encryption at all.

Thank you.

**Comment by alireza0** [comment]
Thank you for your comment. But it is not a BUG!

Please read [fallbackObject](https://xtls.github.io/en/config/features/fallback.html#fallbackobject) documentation carefully.
It is obviously mentioned:

> The fallbacks object is optional and can only be used for the TCP+TLS transport combination.
