### ISSUE TITLE
Copy the code by clicking on QR

### ISSUE THREAD

**Issue by Nipoto** [alireza0/x-ui#41]
[web.zip](https://github.com/alireza0/x-ui/files/10880925/web.zip)

**Comment by alireza0** [comment]
It was removed due to duplicate clipboard button. `Copy` botton and `Click on image`.
I thought it was enough to have `Copy` button.
Isn't it ?
If not, it is better to just bind them to the same function.

**Comment by Nipoto** [comment]
Copying address by clicking on the image is easier ...

**Comment by alireza0** [comment]
Done. Please check manually or wait for next release
