### ISSUE TITLE
مشکل در دایرکت دامین

### ISSUE THREAD

**Issue by ehsanfotoo** [alireza0/x-ui#410]
سلام
یک سرور خارج و یک سرور ایران دارم. بر روی هر دو سرور ، پنل شما را نصب کردم. بر روی هر دو سرور reality ساختم.
طبق آموزش آقای ثنایی ، با استفاده از reality از سرور ایران به خارج تانل زدم.
هم در سرور ایران و هم در سرور خارج ، دامینهایی را در قسمت direct domain قرار دادم که مستقیم باز شوند و ترافیکشان از پروکسی عبور کند اما همه این سایتها از پروکسی عبور میکنند و دایرکت نمیشوند.
احتمال زیاد باگ وجود دارد. لطفاً بررسی کنید.

**Comment by AmoAlireza** [comment]
سلام
روی هر دو تا پنل باید دایرکت کنی.

**Comment by ehsanfotoo** [comment]
> سلام روی هر دو تا پنل باید دایرکت کنی.

سلام. روی هر دو پنل دایرکت کردم اما کار نمیکنه.
دایرکت دامین فقط وقتی کار میکنه که روی V2rayn ست کرده باشم.

**Comment by alireza0** [comment]
درود بر شما
این مشکل به عدم وجود اطلاعات کافی برای اینکار مربوط میشه و نه باگ پنل.
