### ISSUE TITLE
run source

### ISSUE THREAD

**Issue by r0zbeh** [alireza0/x-ui#413]
i clone repository and install go on (ubuntu 20.04), when try run source with go run main.go it was not work fine !! how its possible run source code ? i am just bigginer :)

error is 👍 

`start xray failed: Write the configuration file failed: open bin/config.json: no such file or directory`

**Comment by MHSanaei** [comment]
you need a bin folder

**Comment by r0zbeh** [comment]
:))) it solve !! tnx !
