### ISSUE TITLE
Generate addresses with domains instead of ips for non tls

### ISSUE THREAD

**Issue by ariandcir** [alireza0/x-ui#42]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hey mate, on the inbound ui, maybe a field that could be used to input a domain name for non tls configurations so that it could be used by the backend when generating links instead of adding the ip address to the configuration variables that are sent to the clients would be great.

**Comment by alireza0** [comment]
Hello @ariandcir ,
Backend does not aware of links and qrCode. All will be done in FrontEnd.
In x-ui, it is planned to use hotname that you used for openning the panel.
If you want to change it, it is better to open the panel by desired domain name.

**Comment by ariandcir** [comment]
All sorted
