### ISSUE TITLE
In-game voice chats are not working

### ISSUE THREAD

**Issue by Eidreven** [alireza0/x-ui#421]
In this X-ray Ingame voice not working ( valorant, overwatch etc ) it seems not connecting to voice channel, I tested whatsapp and discord are working well,

Config : vless ws tls

Any fix?

**Comment by alireza0** [comment]
I have no idea about this problem!
You have a special problem which is related to your configuration and xray-core. It is not related to x-ui.

Please ask it in xray-core channels.
