### ISSUE TITLE
راهنمای در مورد کامپایل سورس

### ISSUE THREAD

**Issue by alirezazarghi** [alireza0/x-ui#422]
ا سلام و حسته نباشید خدمت شما
آیا امکان دارد در مورد کامپایل کردن سورس من را راهنمایی کنید؟
من چند api اضافه کردم به سورس ولی از آنجا که با GO آشنایی زیادی ندارم
لطفا من را راهنمایی کنید تا سورس را کامپایل نماییم
با تشکر از شما

**Comment by alireza0** [comment]
درود بر شما
امیدوارم این درخواستتون تست هوش نباشه!
چون api های این پروژه به زبان golang نوشته شده و اگر اضافه کردید حتما میتونید کمپایل هم کنید.
به هرحال شما میتونید با یه جستجوی ساده هم پیدا کنید:

```bash
go build main.go
```
