### ISSUE TITLE
تانل کردن

### ISSUE THREAD

**Issue by jamiekarvans** [alireza0/x-ui#424]
سلام خسته نباشید  ممنون بابت تلاشاتون و وقتی که میزارید
من اومدم دوکدمودور زدم از سرور ایران به خارج و روی سرور ایران از پنل تیک که دامین ایران رو مستقیم وصل کنه و به سرور خارج نفرسته اما کار نکرد اینطور
حالا اومدم طبق اموزش اقای ثنایی توی کانال گزاشته بود برای ریلیتی رفتم و همه چی اوکی بود و دامین ایران رو با سرور ایران میرفت اما 
 1. مشکل اول اینکه با این کار فقط یک اینباند میشه زد درسته؟ اگر بخوام من چندتا اینباند بزنم توی قسمت اوتباند سرور ایران چطور باید واردشون کنم؟ و چرا دایرکت ایپی با همون دوکدمودور جواب نمیده؟
2. و یک موضوع دیگه الان بهترین روش برای سرعت خوب و دیر فیلتر شدن کدومه هنوز همون ریلیتیو ویژن هست؟
ممنون بابت کمک هاتون

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی تون

۱. تعداد تانل ها از سرور داخل به خارج محدود نیست. برای هر تانل تگ جدا بذارید. اینجوری میتونید هر تانل رو برای مسیردهی یک یا چند اینباند استفاده کنید.
دوکودمودور فقط برای رد کردن ترافیک از داخل xray استفاده میشه. در واقع با اون روش شما از نرم افزار کاربر به سرور خارج تانل میزنید و سرور داخلی شما اطلاعی از داخل این تانل نداره و فقط ترافیک رو به سرور خارج میفرسته. به همین دلیل محتوای تانل دوکودمودور قابل روت کردن نیست.

۲. بهترین روش رو برای هر منطقه باید تست کنید. نمیشه به قطعیت گفت.

موفق باشید

**Comment by jamiekarvans** [comment]
با تشکر فراوان بابت توضیحات دقیق و مرتب
