### ISSUE TITLE
Warp Iran's ip range

### ISSUE THREAD

**Issue by linehman** [alireza0/x-ui#425]
سلام وقت بخیر ، در حال حاضر پنل امکان بن کردن اتصال به سایت های ایران رو داره. اگر امکانی برای route کردن این ترافیک به warp اضافه بشه ، امکان ارتباط با این سایت ها برقرار می شه و هم آی پی سرور پنهان میمونه.

**Comment by alireza0** [comment]
درود بر شما

برای اتصالات اینچنینی که کاربر خاص لازم داره، همیشه راه وجود داره.
دلیلی نداره که پیچیدگی اضافه بشه که همه طیف کاربرها لازم ندارن، ولی راه اضافه کردنش برای کاربر پیشرفته وجود داره.

برنامه ای برای اضافه کردن WARP فعلا ندارم
