### ISSUE TITLE
TLS HADSHAKE ERROR 

### ISSUE THREAD

**Issue by mehradraissi** [alireza0/x-ui#426]
سلام روز بخیر من پنل بسیار خوب شما رو روی ۲ تا سرورم نصب کرده بودم و به خوبی کا میکرد الان چند روزه جفتشون اشکال داره و لاگ که میگیرم خطای TLS HANDSHAKE ERROR  میده 
ممنون میشم راهنمایی کنید

**Comment by alireza0** [comment]
درود بر شما
این لاگ ها برای سرور شما مشکلی ایجاد نمیکنه.
این خطاها به دلایل زیادی به وجود میان. مثلا اگر از کلادفلر و یا پراکسی های مشابد استفاده میکنید،‌ ممکنه تعداد این خطاها بیشتر بشه.

**Comment by alireza0** [comment]
به اون مشکل ربطی نداره.
اگر فیلتر شده باشه، هندشیک درست انجام نمیشه و این خطا هم ممکنه به دلیل اون باشه
