### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by aliwishstar** [alireza0/x-ui#427]
سلام ممنون از پنل خوبتون.
من پنل رو به صورت داکر نصب کردم و وقتی روی دکمه logs توی صفحه اصلی میزنم
به من این خطا رو میده .
getLogs Fail: exec: "journalctl": executable file not found in $PATH

مسیر برای لاگ ها رو توی کانفیگ تعریف کردم ولی مشکل همچنان وجود دارد.

  "log": {
    "loglevel": "Debug",
    "access": "/usr/local/bin/access.log"
  }
  
  چجوری میش این مشکل رو برطرف کرد؟

**Comment by alireza0** [comment]
درود بر شما
لاگها رو باید از خود داکر بگیرید.
```bash
docker logs x-ui
```

**Comment by aliwishstar** [comment]
ممنون من اگر بخواهم  خود لاگ های xray  رو بگیرم  که اینجا تعریف کردم .

"log": {
"loglevel": "Debug",
"access": "/usr/local/bin/access.log"
}

با api میتونیم ؟ اگر بخواهم خودم با زبان go اضافه کنم فایل خاصی رو راهنمایی میکنید که edit کنم و بتونم این کار رو بکنم  و همینطور بتونم با api توی کانفیگ تغییر ایجاد کنم.

**Comment by alireza0** [comment]
میتونید محل فایل لاگ رو توی داکر mount کنید که از خود سرور ببینید و هرکاری خواستید میتونید روش انجام بدید.
اگر میخواید خطاها رو ببینید:
```json
{
  "log": {
    "access": "file_path",
    "error": "file_path",
    "loglevel": "debug",
    "dnsLog": false
  }
}
```

ولی اگر debug ها رو میخواید ببینید کار سختیه.

**Comment by alireza0** [comment]
این مشکل با ارائه متد جدید لاگ ([in mem logs & syslog](https://github.com/alireza0/x-ui/commit/59204cdb0c7c287c347cfc951fffa37184840272)) حل میشه.
