### ISSUE TITLE
base.go: I18nWeb function bug.

### ISSUE THREAD

**Issue by MK0ltra** [alireza0/x-ui#429]
Somethings might be wrong with this function:

https://github.com/alireza0/x-ui/blob/main/web/controller/base.go#L28, related to 43dc1e5522d2ce139f9042a99d85d9fb102a308d

I see this message in x-ui logs when i try to login to panel:
 `ERROR - Failed to localize message: message "pages.login.toasts.successLogin" not found in language "en"`

Also when i try to add Client to inbound:
 `ERROR - Failed to localize message: message "success" not found in language "en"`

Everything was ok in 1.4.0. It started when i updated to 1.5.0.

**Comment by alireza0** [comment]
It is already fixed [here](https://github.com/alireza0/x-ui/commit/86508876f95af9055163fcea9eca65c85c4be901).
Please wait for next version or build it manually.
