### ISSUE TITLE
change pannel

### ISSUE THREAD

**Issue by Cjxer** [alireza0/x-ui#43]
سلام من میخوام از پنل https://github.com/mhsanaei/3x-ui/ مهاجرت کنم به پنل شما
اما دیتابیس رو که آپلود میکنم و x-ui رو ریستارت میکنم ، پنل بالا نمیاد

ممکنه راهنمایی بفرمائید چیکار باید بکنم؟
ممنون

**Comment by alireza0** [comment]
درود بر شما
لطفا سرویس رو بررسی کنید:
x-ui status

**Comment by rezagolden2018** [comment]
سلام من چجوری نسحه جدید رو دانگرید کنم به نسخه قبلی؟

**Comment by alireza0** [comment]
@rezagolden2018 
تمامی نسخه های این پنل رو میتونید [اینجا](https://github.com/alireza0/x-ui/releases) ببینید.
از نسخه دلخواهتون، فایل مربوط به نوع سیستم عامل خودتون رو انتخاب و دانلود کنید.
سپس از حالت فشرده خارج کنید و فایل x-ui رو به آدرس `/usr/local/x-ui/` کپی و جایگزین کنید. در نهایت سرویس رو ریستارت کنید.
