### ISSUE TITLE
سرور مناسب

### ISSUE THREAD

**Issue by alirezazarghi** [alireza0/x-ui#431]
با سلام
من چندین هاست تهیه کردم و روی اقدام به نصب کردم
مشکل اینجاست که بسیار کند هستند
مشخصات آخرین هاست :
Cpu : 2
Ram: 4
Os:ubuntu 20.04 lts
لطفاً من را راهنمایی کنید

**Comment by alireza0** [comment]
درود بر شما
سوال شما در رابطه با این محصول نیست. لطفا در فوروم ها و گروه ها در این مورد سوال بفرمایید
