### ISSUE TITLE
جدا کردن remark از email

### ISSUE THREAD

**Issue by ZakariaRasoli** [alireza0/x-ui#436]
لطفا برای هر کلایت یک remark جدا در نظر بگیرین 

و اینکه بتونیم وقتی یه کلاینتی اضافه میکنیم توی چندتا اینباند بتونیم اضافه کنیم که با یدونه ساب بشه چندین اینباند اضافه بشه

**Comment by ZakariaRasoli** [comment]
قسمت url هم بشه اون xui رو حذف کرد یا جایگزین یچیز دیگه کرد خیلی خوب میشه تست کردم یدونه سرور ایپی سالم بدون هیچ کانفیگی فقط پنلشو بدون وی پی ان باز کردم یساعت طول نکشید ایپیش محدود شد

**Comment by alireza0** [comment]
@ZakariaRasoli 
شما میتونین با استفاده از تنظیم گواهی های SSL پنل این درخواست ها رو مخفی نگهدارید.
جدا از اینکه میتونید از پروکسی های مشهور برای تبدیلش به هرچیزی که میخواید استفاده کنید.

**Comment by ZakariaRasoli** [comment]
خیلی ممنون 

یه پیشنهاد دیگه هم که دارم اینکه بشه تو صفحه مثلا ۵۰ تای اولو نشون بده یا همرو این خیلی کمک میکنه به لود سریع صفحه 
 و اسم اخرین کانفیگ اضافه شده هم نشون بده خیلی خوب میشه

**Comment by alireza0** [comment]
@ZakariaRasoli 

مدل چند صفحه ای در نسخه جدید اضافه خواهد شد.
