### ISSUE TITLE
Import/Export Database as a .json

### ISSUE THREAD

**Issue by Enkidu-6** [alireza0/x-ui#440]
Hi, I see an option for exporting links which basically gives you all the config links of your user accounts. Is there a way to export an account as a .json file or perhaps import a .json file for an account instead of creating it using the GUI?

As for the same subject, I have an old vaxilu x-ui which is quite outdated and another one from [NidukaAkalanka](https://github.com/NidukaAkalanka/NidukaAkalanka) which is the English version. I'm hoping to migrate them both to your version without losing the current user configs. What's the best way to go about that?

Thanks

**Comment by Enkidu-6** [comment]
P.S.
I see that the user configs are in the config.json file so I guess it wouldn't be hard to copy them to your config.json. The confusing part is /etc/x-ui/x-ui.db. Will I have to modify the database too or is it auto generated based on the info in the config.json?

Thanks.

**Comment by alireza0** [comment]
Hi,

Regarding json config, it is possible to have server configuration. But it seems you need client configuration which is not easy here.

Converting all other `x-ui` projects are possible. Just don't forget to have backup.

Regarding your confusion: Your guess is not true. Everything will be prepared from database. Ex. config.json
You need to move the database only.

FYI: You can also import the database via web panel.

**Comment by Enkidu-6** [comment]
##
Regarding your confusion: Your guess is not true. Everything will be prepared from database. Ex. config.json
You need to move the database only.
##

Cool. Thanks

##
FYI: You can also import the database via web panel.
##

That's what I was originally looking for but I'm still looking for it to no avail. In the inbound section I see the option "Export Links" but I have looked in all sections of the panel and can't see an option for "import Database" or "Export Database".

Nevertheless, I whipped up a VPS on my system, installed a fresh Ubuntu server and then your panel. I set it up the way I liked it and then replaced your x-ui.db in /etc/x-ui with my old one and the panel didn't load at all and had to reboot the VPS. 

Could be because I didn't stop XRay before replacing the file or it could be because my database is ancient and belongs to Vaxiliu X-UI. It even has a couple of XTLS configs which are not supported anymore. Not to mention that it doesn't even support subscriptions.

The good news is that I only have 6 or 7 users on that panel and I can simply recreate them after installing your panel. So it's all good.

By the way, now that I have your ears, do you have any plans to add support for the H2 protocol in your panel?

Thank you.

**Comment by alireza0** [comment]
_ In main page ( system status ) you can find `Backaup & Restore` blue button.
_ Yes, you are right. New Xtay is not supporting XTLS encryption anymore. You should change the inbound in advance.
_ http1.1/H2 have same configuration in transmission and the `HTTP` option should be selected. In #314 we discussed it more. It seems Xray treat HTTP + TLS as H2 ([here](https://xtls.github.io/config/transport.html#streamsettingsobject)). But in clients side only, we saw different H2 and HTTP options.

**Comment by Enkidu-6** [comment]
> In main page ( system status ) you can find `Backaup & Restore` blue button.

Boy I must have been blind.


> _ In main page ( system status ) you can find `Backaup & Restore` blue button. _ Yes, you are right. New Xtay is not supporting XTLS encryption anymore. You should change the inbound in advance. _ http1.1/H2 have same configuration in transmission and the `HTTP` option should be selected. In #314 we discussed it more. It seems Xray treat HTTP + TLS as H2 ([here](https://xtls.github.io/config/transport.html#streamsettingsobject)). But in clients side only, we saw different H2 and HTTP options.

Yes you're absolutely correct and thank you for the link to the discussion. Since we know what it is, you can make a button for it and let people generate a pre configured inbound.  Although it's not a big deal.

I've seen it done in another panel, Sanaei I believe if I'm spelling it correctly. Although the end result config doesn't seem to be correct. In fact you can create a simple html config with no security thinking you've made an H2. But that's a subject for another discussion.

Thank you for your time. I've tried a few XRay panels and yours is the panel of choice for me. Feel free to close this issue as done. I'll be opening another issue regarding Shadowsocks soon. :)
