### ISSUE TITLE
Problem with adding certificates

### ISSUE THREAD

**Issue by userbody** [alireza0/x-ui#441]
Ubuntu 20.04
[v1.5.1]

![1](https://github.com/alireza0/x-ui/assets/59291386/7e98643a-faaf-4e77-9a00-946a1d393197)
![1323131](https://github.com/alireza0/x-ui/assets/59291386/3924cd25-b4b0-46ac-b13b-11fbd5bb5f5d)

**Comment by alireza0** [comment]
Could you please describe me which kind of bug do you see here ?
You should fix access to the cert file. It is not related to `x-ui`.

**Comment by finstape** [comment]
> Could you please describe me which kind of bug do you see here ? You should fix access to the cert file. It is not related to `x-ui`.

Which access should be to the cert files? I tried root, my user, nobody:nogroup bit it still not working
