### ISSUE TITLE
مشکل کار با api

### ISSUE THREAD

**Issue by m1faridi** [alireza0/x-ui#442]
سلام خسته نباشید
من از api میخواستم استفاده کنم ابتدا 
http://****:54321/login
پارامتر ها رو هم فرستادم و خرجی 
{
    "success": true,
    "msg": "Login Success",
    "obj": null
}
دریافت کریدم اما هرکاری میکنم این کار نمینه

http://****:54321/xui/API/inbounds/
و خروجی برابر هست با 
404 page not found

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم

شما باید پارامتر گرفته شده بعد از لاگین رو در درخواست بعدیتون بفرستید و هربار چک کنید که اگر لاگین نیستید، لاگین انجام بشه
