### ISSUE TITLE
فعال بودن کانفیگ با پایان حجم

### ISSUE THREAD

**Issue by straymail** [alireza0/x-ui#443]
سلام قربان
بنده دیتابیس 1.5.0 رو به سرور دیگه با پنل 1.5.1 انتقال دادم
الان کانفیگ های منقضی هم کار میکنن و حجم منفی میزنه

**Comment by alireza0** [comment]
درود بر شما
لطفا لاگ های آخر رو بفرستید و اینکه بفرمایید محدودیت شما روی کلاینت بوده و یا سرویس ؟

**Comment by r0zbeh** [comment]
same !!
![image](https://github.com/alireza0/x-ui/assets/25858679/451cdd0a-7497-4b3c-b41b-5df39eb0cf0b)

**Comment by alireza0** [comment]
این مقدار نرماله، مخصوصا در محدودیت حجم کم.
@r0zbeh 
مصرف کاربر هر ده ثانیه چک میشه و توی این مدت، بیشتر شدن مصرف طبیعیه.
یک سری مشکلات توی shadowsocks توی این زمینه هست که دارم برطرف میکنم.

**Comment by r0zbeh** [comment]
بیشتر از 10 بار تست کردم کردم ترافیک به صورت کامل قطع نمیشه الان 20 دقیقه هم هست همچنان مصرف ترافیک ادامه داره فقط با سرعت کم ! vless/ws/tls

**Comment by alireza0** [comment]
این مورد رو با تمام لاگ ها چک کردم. ظاهرا بعد از حذف کاربر، بدون ریستارت xray کاربر تلاشش رو ادامه میده برای اتصال ولی اینترنتی دریافت نمیکنه. این تلاش همه در بخش آپلود اضافه میشه.
بخش گزارش مصرف xray ترافیک یک کاربر رو تا مدتی توی گزارش ها نگه میداره. به همین دلیل، حتی بعد از حذف کاربر باعث چند خطای دیگه هم میشه. این خطاها مشخص و حذف شد.
ولی در مورد قطع نشدن توی این نسخه، فقط در مورد shadowsocks مشکل داریم که اون رو هم حل کردم.
در نسخه بعد shadowsocks کاملتری خواهیم داشت.

**Comment by r0zbeh** [comment]
ممنون بله درسته چون بعد از حذف کاربرو Depleted شدن ،ترافیک به شدت کاهش پیدا میکنه و فقط درخواست ها ی کاربر باعث بالارفتن ترافیک میشه البته بعضی از درخواست ها هم پاسخ داده میشه چون برای مثال در اینستاگرام بخش explore بعد از حذف کاربر هنوز لودینگ پست ها جدید انجام میشه ولی کامل نیست و  از هر 40 تا پست 3 یا 4 تای اون فقط لود صفحه اولش انجام  میشه - البته همون طور که گفتن یا یه مدت محدود مثلا 10 دقیقه این روند ادامه داره بعد کامل قطع میشه ممنون بابت پیگیری
