### ISSUE TITLE
Failed add vmess config to the Fair - Alterid not found

### ISSUE THREAD

**Issue by r0zbeh** [alireza0/x-ui#444]
**Describe the bug**
when try add vmess config to Fair(ios) v2ray Clinet application its faild .

Error : Alterid Not Found

**Screenshots**
![fairerror](https://github.com/alireza0/x-ui/assets/25858679/86c70068-dd31-4ebb-b5e7-2d7bb99279a0)

**Comment by sudospaes** [comment]
This is not a bug. The problem is with your client. Fair is now obsolete. Use other clients.
vmess has been deprecated for some time. And alterid is also removed from xray core.

**Comment by r0zbeh** [comment]
what is your suggestion for ios client app?

**Comment by sudospaes** [comment]
> what is your suggestion for ios client app?

You can [Foxray](https://apps.apple.com/us/app/foxray/id6448898396) or [Streisand](https://apps.apple.com/us/app/streisand/id6450534064). and use vless instead vmess
