### ISSUE TITLE
کد رستارت  کردن سرور بدون قطع شدن کاربران

### ISSUE THREAD

**Issue by r0zbeh** [alireza0/x-ui#445]
با سلام ، بنده اطلاعات درون دیتابیس رو تغییر میدم اما تا Xray رستارت نشه تغییرات اعمال نمیشه و کار نمیکنه ، تا اینکه از کد `a.xrayService.RestartXray(true)` استفاده کردم الان تنظیمات اوکی میشه فقط میخوام بدونم این کد روش درستی هست برای آپدیت کردن سرور که از اطلاعات جدید دیتابیس استفاده کنه و آیا هنگام رستارت شدن به این روش کاربران برای چند لحظه ای از سرور قطع نمی شن؟

**Comment by alireza0** [comment]
درود بر شما
سرور xray از دیتابیس استفاده نمیکنه. در نتیجه تغییرات مستقیم نمیتونه بدون ریستارت شدن اعمال بشه.
رستارت شدن xray-core در هر صورت باعت قطع شدن همه کاربرها میشه.
نسخه جدید ارائه شده میتونه برای درخواست های inbound و client ها، بدون ریستارت شدن تغییرات رو اعمال کنه. نیازی به دستکاری دیتابیس ندارید.
