### ISSUE TITLE
چند تا پیشنهاد جهت بهبود کارایی پنل

### ISSUE THREAD

**Issue by UltimateABC** [alireza0/x-ui#447]
## قسمت سابسکریپشن که تعریف شده ، بنظرم کارایی زیادی نداره.
ببینید بنظر من سابسکریپشن برا اینه که شما برای یک کلاینت، بتونید چند تا کانفیگ بفرستید.

این مدل سابسکریپشن که توی پنل ارایه شده، بنظر میاد برای ساخت کاربرها بصورت تصادفی باشه، مثلا یه نفری بخواد روی یک کانفیگ 10 تا کاربر داشته باشه  که همه رو یه جا بفرستی براش و اونم بین کاربرای خودش تقسیم کنه.

برای بهبود سابسکریپشن بنظرم باید این شکلی ساخته بشه

```
**Subscription Clinet 1**
                                     -------- VLESS.TCP.TLS
                                     -------- . . . . . . . . . . . . .
                                     -------- VLESS.gRPC.TLS

```
 یعنی با ارسال لینک سابسکریپشن ، برای هر کاربر بتونیم چند تا کانفیگ که توی سابسکریپشن تعریف کردیم رو بفرستیم، و با هر کدوم تونست وصل بشه، مثلا ایرانسل با gRPC وصل بشه و همراه اول با TCP، محدودیت های آی پی و ترافیک هم روی همون سابسکریپشن اعمال میشه

با این روش ادمین کار خیلی راحت تری داره، تمامی کانفیگ های مورد نظرش رو روی یک سابسکریپشن میسازه، برای اضافه کردن کاربر فقط یه clone subscription میزنه و تمام.

 
 یه چیز دیگه هم که میشه به سابسکریپشن اضافه کرد، اینه که یه کانفیگ fake ساخته بشه، با اسم subscription و تاریخ و حجم مصرف شده کاربرا
 
 برا مثال
 
![image](https://github.com/alireza0/x-ui/assets/3676067/986688f6-91ab-46e6-abeb-5342cbecdadc)

![image](https://github.com/alireza0/x-ui/assets/3676067/063374f7-4d8f-41d1-915a-79e6d61e8cb6)

```
vless://1@25.days:11#8.167%2F30B

```
 
## گزینه family option توی تعاریف inbounds اضافه بشه.
با این وضعیت اینترنت مجبوریم که برای کودکان و نوجوانان دور و برمون vpn تهیه کنیم. باید محتوای پورنو و تبلبغات +18 رو براشون محدود کنیم.
توی کانفیگ های json  قبلا تنظیمات dns رو دیده بودم، حالا اینو نمیدونم که آیا امکان این هست که بشه روی کلاینت ها ست کرد یا نه، بنظرم باید از طرف سرور ست بشه که کاربر نتونه تغییرش بده.
 
 ## کامل نبودن کانفیگ webSocket
 توی کانفیگ های web socket وقتی برای کلاینت فرستاده میشه، قسمت camouflage type و camouflage domain (host) خالی هست، اینو باید بصورت دستی بعد از انتقال به کلاینت اضافه کرد. اینو اگه امگانش هست اوکی کنید.
 
 ## اضافه کردن تظنیمات حرفه ای برای ویرایش پایه کانفیگ ها
 برای مثال بتونیم ساختار base پیشفرض هر کانفیگ رو ویرایش کنیم.

**Comment by alireza0** [comment]
درود بر شما

سپاس از همراهی و ارائه نظراتتون.
۱. قابلیت subscription به صورت محدود ارائه شده و فقط در جهت تامین نیاز کاربران بودده
۲. ارائه یک ساب شامل چند کلاینت از ابتدای اضافه شدن این قابلیت، قابل انجام بود. ( به هر تعداد کاربری که میخواید مقدار ثابتی از subid رو بدید )
۳. کانفیگ فیک فقط کاربرد نمایشی داره. اطلاعات اکانت توی هدرهای ساب ارسال میشه. بهتره از نرم افزارهای کلاینت مناسب استفاده کنید.
۴. گزینه Family-friendly خیلی وقته اضافه شده. این امکان برای همه کاربر ها اعمال میشه. اگر میخواید روی یک سرویس ارائه بدید، در حال حاضر بهتره که به صورت دستی توی تنظیمات پیشرفته این کار رو انجام بدید.
۵. کانفیگ Web Socket چنین مقادیری نداره. این مقادیر فقط برای tcp استفاده میشه.
۶. تنظیمات حرفه ای مد نظر شما در قالب پنل قابل ارائه نیست. هر تغییری در ساختار تنظیمات نیازمند نحوه ذخیره شدن مجزاست. و این به معنی عوض کردن کل ساختار دیتابیسی پنله

با اجازتون درخواست رو میبندم و اگر درخواست ویژگی مفید و جامعی داشتین که میتونه مزایای زیادی برای اکثر کاربرها ایجاد کنه، لطفا توی درخواست مجزایی ارسال کنید.
ارادتمند

**Comment by UltimateABC** [comment]
مرسی بابت پاسخ ها، در مورد گزینه دوم میتونم توضیح بیشتری داشته باشم ازتون؟

سابسکرایب چگونه کار میکنه؟
میاد تمامی کانفیگ هایی که ساب آیدی  مشترک داره رو برمیگردونه؟

ساب آی دی رفرنس کدوم میشه؟
برا کنترل ترافیک و آی پی لیمیت چجوری تنظیم کنیم که روی همه کانفیگ های مشترک با اون سابسکرایب اعمال بشه، برا مثال اگه از کانفیگ vmessاستفاده کنه، از کانفیگ vless هم کم بشه.

نرم افزار v2rayng آخرین نسخه هست، ندیدم جایی اطلاعات ترافیک باقیمانده ارسال بشه.

گزینه ۴ رو چجوری باید انجام بدم، باید تگ خاصی تعریف بشه؟ مثلا برای همه کانفیگ های vmess یا اینکه برا مثال میشه روی پروتوکل هم اعمال کرد؟


در انتها میشه بپرسم امکان ارایه چندین سابسکرایب روی یک پورت هست یا نه؟

**Comment by alireza0** [comment]
> سابسکرایب چگونه کار میکنه؟
میاد تمامی کانفیگ هایی که ساب آیدی مشترک داره رو برمیگردونه؟

بله

> ساب آی دی رفرنس کدوم میشه؟

مقدار subid برای همه کانفیگ ها یکی میشه

> برا کنترل ترافیک و آی پی لیمیت چجوری تنظیم کنیم که روی همه کانفیگ های مشترک با اون سابسکرایب اعمال بشه، برا مثال اگه از کانفیگ vmessاستفاده کنه، از کانفیگ vless هم کم بشه.

چنین امکانی در حال حاضر توی این پنل نداریم

> نرم افزار v2rayng آخرین نسخه هست، ندیدم جایی اطلاعات ترافیک باقیمانده ارسال بشه.

این نرم افزار قابلیت نمایش این دیتا رو نداره. به جاش از hiddifyNG و یا clash استفاده کنید

> گزینه ۴ رو چجوری باید انجام بدم، باید تگ خاصی تعریف بشه؟ مثلا برای همه کانفیگ های vmess یا اینکه برا مثال میشه روی پروتوکل هم اعمال کرد؟

![image](https://github.com/alireza0/x-ui/assets/12573084/eac6ef09-d1da-4ad7-b58a-d864f5f174df)
این تنظیم برای کل سیستمه.
یکی از راه های ساده جداسازی اینه که با تنظیم route rule خروجی اینباندهای هدف رو برای پورت 53 به سمت سرور خاص هدایت کنید.

> در انتها میشه بپرسم امکان ارایه چندین سابسکرایب روی یک پورت هست یا نه؟

اگر منظورتون چند اینباند روی یک پورت باشه، بله. با ترکیب های reverse proxy میتونید این تنظیمات رو انجام بدید.
خود xray امکان fallback رو داره. اگر مسلط تر هستید میتونید از نرم افزار های دیگه مثل nginx و  haproxy هم استفاده کنید

**Comment by selfishtom** [comment]
سلام و عرض خسته نباشید.

لطفا آموزش تصویری 

> ۲. ارائه یک ساب شامل چند کلاینت از ابتدای اضافه شدن این قابلیت، قابل انجام بود. ( به هر تعداد کانفیگی که میخواید مقدار ثابتی از subid رو بدید )

برای این مورد بزارید چون من نتونستم این کارو انجام بدم
