### ISSUE TITLE
اعمال تغییرات در ساعت خاص

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/x-ui#448]
سلام وقتتون بخیر
دوست عزیز اگر امکان این باشه که تغییرات در هسته v2ray مانند ساخت کلاینت جدید هر یک ساعت یکبار انجام بشه خیلی میتونه به کمتر شدن قطعی ها کمک بکنه. این مورد در مواردی مثل گیم و ترید خیلی کاربر داره که نباید قطعی لحظه ای داشته باشیم.
همچنین اگر بشه ساعت خاص انتخاب کرد خیلی میتونه مفید باشه.

با تشکر از شما بابت توسعه این پنل جذاب

**Comment by alireza0** [comment]
درود بر شما
لطفا بروزرسانی کنید. در نسخه جدید، عملیات های مختلف روی inbound و client بدون قطع شدن کاربران پنل انجام میشود.
