### ISSUE TITLE
Shadowsocks entry on the subscription page.

### ISSUE THREAD

**Issue by Enkidu-6** [alireza0/x-ui#449]
Hello again. 

Background:
--------------

I use a Php script on another domain that acts as a crude reverse proxy to fetch the subscription from the site that's running your panel and display it on the site people are visiting. The idea is to separate the site that runs the proxy from the site users fetch the subscription list. The advantage of this is that if the proxy's IP address is blocked, I can simply switch the domain name or IP Address , and the users won't be the wiser and they'll continue like nothing happened and I won't have to send them a new subscription link.

The problem:
---------------

This works for practically all configurations except for Shadowsocks. The domain name of the server seems to be hard coded for all configurations but Shadowsocks seems to be picking it up from the current domain where the subscription page is viewed.

Example:
----------

If he client checks the subscription from the main domain example.com the subscription appears as

ss://MjAyMi1ib........=@example.com and it works and they can connect

If the client checks the subscription from foo.com. The subscription appears as:

ss://MjAyMi1ib........=@foo.com and it won't work for them because there's nothing on foo.com to reply.

Now my question is, how is the domain name picked up for the subscription link? I might be able to fool the browser in the script
OR Is it possible to hard code the domain name just like the rest of them in future versions?

Thank you.

**Comment by alireza0** [comment]
Hello @Enkidu-6 ,

You can use http headers to pass `host` to the subscription service. Then your config will be changes to your desired domain. Here is an example of the `nginx` config:

```nginx
        server_name foo.com;

        location ~ ^/(.+)$ {
                proxy_pass http://example.com:2096/$1;
                proxy_set_header Host "example.com";
        }
```

**Comment by Enkidu-6** [comment]
> Hello @Enkidu-6 ,
> 
> You can use http headers to pass `host` to the subscription service. Then your config will change to your desired domain. Here is an example of the `nginx` config:
> 
> ```nginx
>         server_name foo.com;
> 
>         location ~ ^/(.+)$ {
>                 proxy_pass http://example.com:2096/$1;
>                 proxy_set_header Host "example.com";
>         }
> ```

Sorry, I didn't get that part. Do you mean the nginx on the reverse proxy at foo,com? In that case the problem is not everyone has access to nginx config files. Most people use some kind of a shared hosing plan with no access to what's going on under the hood. Which is why I suggested a simple .php file to do the job using a simple:
```
$response = str_replace($domain, "example.com", $response);
```
This is what I'm currently using to do it:
```
<?php

$server_domain="https://example.com:2096";


$domain = $_SERVER['HTTP_HOST'];
$ip = $_SERVER['HTTP_CF_CONNECTING_IP'] ?? $_SERVER['HTTP_X_FORWARDED_FOR'] ?? $_SERVER['REMOTE_ADDR'];
$url = $server_domain . $_SERVER['REQUEST_URI'];

$context = stream_context_create([
    "ssl" => [
        "verify_peer" => true,          // Enable SSL certificate verification.
        "verify_peer_name" => true,     // Enable SSL certificate verification.
        "allow_self_signed" => false,   // Do not allow self-signed certificates.
    ],
    'http' => [
        'method' => 'GET',
        'header'=>"CF-Connecting-IP: $ip\r\nHost: $domain\r\n"
    ],
]);

$response = file_get_contents($url, false, $context);

$response = str_replace($domain, "example.com", $response);

foreach ($http_response_header as $header) {
    header($header);
}
echo $response;
```
This file is served on foo.com/index.php

And it does work with no problem. The problem starts when the subscription config is encrypted. In that case there's nothing to filter except a bunch of gibberish. Not sure if the nginx method works either because I'm assuming the encryption is done before the page is served?? So changing the host won't have any effect on the already encrypted content?

**Comment by alireza0** [comment]
Changing the host will completely change the encrypted content. You can use this code, and then you dont need to replace any content.
If you need to change the content, just dencrypt it with BASE64 and change the content, then encrypt it again for output:

```php
<?php

$server_domain="https://example.com:2096";


$domain = $_SERVER['HTTP_HOST'];
$ip = $_SERVER['HTTP_CF_CONNECTING_IP'] ?? $_SERVER['HTTP_X_FORWARDED_FOR'] ?? $_SERVER['REMOTE_ADDR'];
$url = $server_domain . $_SERVER['REQUEST_URI'];

$context = stream_context_create([
    "ssl" => [
        "verify_peer" => true,          // Enable SSL certificate verification.
        "verify_peer_name" => true,     // Enable SSL certificate verification.
        "allow_self_signed" => false,   // Do not allow self-signed certificates.
    ],
    'http' => [
        'method' => 'GET',
        'header'=>"CF-Connecting-IP: $ip\r\nHost: example.com\r\n"
    ],
]);

$response = file_get_contents($url, false, $context);

foreach ($http_response_header as $header) {
    header($header);
}
echo $response;
```

**Comment by Enkidu-6** [comment]
Ah... Now I get it. Beautiful. You learn something new each day. Thank you again for the time you've taken. Much appreciated. Feel free to close this issue.
