### ISSUE TITLE
امکان ساخت چند کانفیگ برای یک یوزر

### ISSUE THREAD

**Issue by taregh-n** [alireza0/x-ui#450]
گاهی برای یک کاربر لازم است چند کانفیگ بسازیم اما پنل اجازه نمیدهد و با خطای زیر مواجه میشویم:

`Something went wrong! Fail: Duplicate email: xxx`

که ذر اینجا xxx نام کاربری کاربر (email) است

**Comment by alireza0** [comment]
این درخواست تکراری است.
این قابلیت با طراحی پایه ای این پنل تداخل دارد.
