### ISSUE TITLE
نمایش حجم و زمان اکانت 

### ISSUE THREAD

**Issue by abedin70** [alireza0/x-ui#451]
لطفاً این قابلیت رو اضافه کنید
ممنون از زحمات شما

**Comment by alireza0** [comment]
این مورد مشکلات زیادی داره.
یکی از دوستان زحمت کد رو کشیدن. جواب و مشکلات رو میتونید [اینجا](https://github.com/alireza0/x-ui/pull/453#issuecomment-1651858376) ببینید.
لطفا قبل از باز کردن درخواست چک بفرمایید
