### ISSUE TITLE
نصب دو پنل همزمان بدون داکر

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#455]
سلام آیا امکان داره که روی یه سرور دو تا x-ui بالا بیارم بدون استفاده از داکر ؟

**Comment by alireza0** [comment]
درود بر شما
لطفا برای پرسش ها، گزینه مناسب رو انتخاب کنید.

بله، باید نصب به صورت دستی انجام بشه و از XUI_DB_FOLDER برای تغییر مسیر فایل دیتابیس استفاده کنید

**Comment by wulfric93** [comment]
ممنون میشم بیشتر راهنمایی کنید

**Comment by wulfric93** [comment]
> میتونید به صورت دستی سرویس دیگه ای اجرا کنید. برای این کار فایل سرویس اصلی رو میتونید کپی کنید:
> 
> ```shell
> cp /etc/systemd/system/x-ui.service /etc/systemd/system/x-ui2.service 
> ```
> 
> بعد محتواش رو به شکل زیر تغییر بدید:
> 
> ```shell
> [Unit]
> Description=x-ui2 Service
> After=network.target
> Wants=network.target
> 
> [Service]
> Environment="XRAY_VMESS_AEAD_FORCED=false"
> Environment="XUI_BIN_FOLDER=bin2"
> Environment="XUI_DB_FOLDER=db2"
> Type=simple
> WorkingDirectory=/usr/local/x-ui/
> ExecStart=/usr/local/x-ui/x-ui
> Restart=on-failure
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> بعد از اون باید systemd رو بروزرسانی کنید و سرویس رو اجرا کنید. لطفا مطمئن باشید که پنل قبلی روی پورت ۵۴۳۲۱ نباشه و پورت های تکراری باعث خطا در xray-core میشه.
> 
> ```shell
> systemctl daemon-reload
> systemctl restart x-ui2.service
> ```
> 
> در نظر داشته باشید این سرویس نمیتونه با دستور x-ui کنترل بشه.

 چطور میتونم x-ui رو هم داشته باشم ؟ مثلا با دستور x-ui-2
