### ISSUE TITLE
تماس صوتی و تصویری

### ISSUE THREAD

**Issue by r0zbeh** [alireza0/x-ui#456]
با سلام ، با تشکر از علیرضای عزیز و دیگر دوستان
میشه بفرمایید تماس صوتی و تصویری چرا روی کلاینت های Ios  مشکل داره ؟ برای اندروید به اندروید اوکیه !! ولی در گوشی های آیفون مشکل وجود داره !!

پروتکل های تست شده : vless, vmess,shadowsocks,reality

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم

این مشکل مربوط به پنل نیست و باید از طریق کانال ها و گروه های مربوط به پراکسی ها پیگیری بشه.
