### ISSUE TITLE
مشکل ورود و ساخت اکانت اینستاگرام

### ISSUE THREAD

**Issue by r0zbeh** [alireza0/x-ui#457]
هنگام ورود و یا ساخت اکانت با روشن بودن گانفیگ ها صفحه سفید و بدون لود نمایش داده میشه !!

مشکل از کجا میتونه باشه ! با کانفیگ های مختلف تست شد بعضی از کانفیگ ها صفحه رو لود میکنن `https://www.instagram.com/accounts/emailsignup/` ولی بعد از وارد کردن اطلاعات اررور میدن ، بیشتر کانفیگ ها هم اصلا صفحه سفید هست و لود نمیشه !

**Comment by arsoltani72** [comment]
این مشکل رو داشتم
