### ISSUE TITLE
افزودن shadowsock نسخه قدیم

### ISSUE THREAD

**Issue by mohamadn69** [alireza0/x-ui#459]
سلام لطفا این موضوع توی نسخه جدید  فراموش نشه. ممنون
https://github.com/alireza0/x-ui/issues/383#issuecomment-1634722635

**Comment by alireza0** [comment]
درود بر شما
کامیت شده و مراحل تستش هم تمام شده.
متدهای قدیمی هم به شکل مولتی یوزر ارائه شده.
منتظر نسخه جدید باشید
