### ISSUE TITLE
Add Packet segmentation to outbounds

### ISSUE THREAD

**Issue by arash88** [alireza0/x-ui#461]
Hi @alireza0 joon,
The last Xray-core build contains a quite important feature, Packet segmentation.
Please read [this PR](https://github.com/XTLS/Xray-core/pull/2021).
It's fairly easy to add this feature to your config. It applies to outbounds in a few lines:

```
{
    "protocol": "freedom",
    "settings": {
        "fragment": {
           "length": "10-20", // length of each fragment to send in bytes. It can be single value or range it has to be a string. If it is a range the values are randomly chosen.
            "interval": "100-500", // the time to wait for each packet in milliseconds. Can be single value or range but it has to be a string. If it is a range the values are randomly chosen.
            "packets": "1-3" // nth packet(s) to fragment, if empty all outbound packets will be fragmented, can be a single number or a range. The start packet cannot be 0 so 0-3 is not acceptable. The range numbers are inclusive.
        }
    },
    "streamSettings": {
        "sockopt": {
            "tcpNoDelay": true // This needs to be enabled so the kernel doesn't cache the fragments
        }
    }
}
```

**Comment by alireza0** [comment]
Hi @arash88 jan,

Actually it does not help as we expect.
Beside this fact that only experts can understand this feature, it is generaly designed for client side usages which will use `freedom` object.
That means it is not enjoyable solution for servers ( even in chain of proxies ).
Additionally, experts can do it simply by changing in json file :)
