### ISSUE TITLE
DNS leak

### ISSUE THREAD

**Issue by AmoAlireza** [alireza0/x-ui#462]
سلام
راهی روشی چیزی سراغ ندارین که بشه از سمت خود سرور و کانفیگ پنل این مشکل dns leak حل کرد؟
مثلا عکس زیر ببینید dns leak test وبسایت browserleaks هستش که با ای پی اصلی خودم هستم و فقط 42 تا سرور و 3 تا لوکیشن پیدا کرد:

![1](https://github.com/alireza0/x-ui/assets/79990596/14df7bfd-ce21-4128-9750-235db9e9adc6)

و اینم عکس یه نمونه دیگست که اصلا dns leak نداره و میخام بدونم میشه همچین چیزی پیدا کرد روی کانفیگ پنل که بدون dns leak باشه؟

![2](https://github.com/alireza0/x-ui/assets/79990596/824672de-9d04-435f-8ba4-a28663b89ca7)

**Comment by alireza0** [comment]
درود بر شما
اگر تنظیمات DNS رو روی xray انجام ندادین. توی تنظیمات سرور باید انجام بدین و باید مشکل حل بشه.

پی نوشت ۱: DNS leak یکی از مزخرف ترین چیزهاییه که بعضی سایت ها گیر میدن بهش.
پی نوشت ۲: البته دوست ندارن از سرویس هاشون پشت پراکسی استفاده بشه و جزو قوانینشونه. پس بهتره به قوانینشون احترام بذارید.

**Comment by AmoAlireza** [comment]
علیرضا جان تنظیمات dns داخل پنل انجام میدم و داخل قسمت Xray Configuration Template میزارم به اینصورت:

![Capture](https://github.com/alireza0/x-ui/assets/79990596/54e030bf-1986-4c73-bdd6-a0888d798bc1)

ولی هیچ تغیری ایجاد نمیشه.

**Comment by alireza0** [comment]
این dns های کلادفلره و خب یکی از عوامل dns leak. شما باید از دامنه هایی که سرویس دهنده سرورتون ارائه کرده استفاده کنید.

**Comment by AmoAlireza** [comment]
روشی که گفتین تست کردم ولی کلا نمیدونم چرا کانفیگ ها پینگ نمیدن ولی پنل running هستش.

**Comment by alireza0** [comment]
توی یوتیوب مطلب در موردش زیاده. تنظیمات dns توی xray رو حذف کنید و توی سیستم درست کنید
