### ISSUE TITLE
x-ui.sh enhancement.

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#464]
Hi. 

I was updating x-ui when suddenly I lost the connection and x-ui sloped in middle of update . then I  couldn't run x-ui again cause  I figured out I couldn't connect to GitHub . it was horrible day for me.

could you please download dependencies first then fry current files instead of frying all of them first then download.
in that case if connection list or such then at least current x-ui exist until connection problem solved.

**Comment by alireza0** [comment]
Hello @X-Oracle ,

Thank you for your hint.
You are right. In the starting process of running install script, it stops x-ui service unconditionally.
It is fixed now and will run service stop after download and if x-ui exists.
