### ISSUE TITLE
sni

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/x-ui#466]
سلام وقت شما بخیر
میخواستم اگر امکانش باشه توضیح مختصری در مورد اینکه کاربرد sni چی هست بدید.

و اینکه اگر sni رو دامنه سرور ایران بدیم و address رو دامنه سرور خارج چه تاثیری خواهد داشت.

باتشکر از شما

**Comment by emadtoranji** [comment]
یه چیزایی میدونم که برای proxy cloudflair استفاده میشه، ssl wildcard هم گرفتم برای دامنه؛ اما هرکاری کردم متصل نشد، ممنون میشم اموزش استفاده و جاگذاری در پنل رو بزارید برامون. باتشکر

**Comment by alireza0** [comment]
درود بر شما
این سوالات در مورد پنل نیست و بهتره توی گروه ها و صفحات مربوط به خودش دنبال بشه.
مستندات زیادی توی اینترنت وجود داره. مثل [ویکی‌پدیا فارسی](https://fa.wikipedia.org/wiki/%D9%86%D8%B4%D8%A7%D9%86_%D9%86%D8%A7%D9%85_%D8%B3%D8%B1%D9%88%D8%B1) و [کلادفلر](https://www.cloudflare.com/learning/ssl/what-is-sni/)

در مورد آموزش هم میتونید به ویدیوها و یا صفحات آموزشی مراجعه کنید.
