### ISSUE TITLE
غیرفعال کردن کلاینت

### ISSUE THREAD

**Issue by asadace1** [alireza0/x-ui#468]
سلام وقت بخیر
یه باگی که هست اینه که وقتی که ما یه کلاینت رو غیرفعال میکنیم کلاینت وصل نمیشه اما در clientStats مقدار enable تغییر نمیکنه و true هست ولی در settings['clients'] مقدار تغییر میکنه به false
من با استفاده از api کلاینت استات رو میارم و true  و بعد کلاینت رو غیرفعال میکنم و دوباره استات میگیرم بازم true هست در حالی که باید false بشه

**Comment by asadace1** [comment]
البته زیاد مهم نیست در هر صورت بعد از غیرفعال کردن وصل نمیشه منتها برای ما گرفتن وضعیت کلاینت دوتا کار میشه 
چون میخام ترافیک مصرفی رو بگیرم باید از clientStats  بگیرم و وضعیت فعال بودن یا نبودن رو بخام بگیرم از settings['clients'] باید بگیرم
اگر وضعیت enable اکانت در clientStats  هم تغییر میکرد بهتر بود با تشکر

**Comment by alireza0** [comment]
https://github.com/alireza0/x-ui/issues/452#issuecomment-1651832422
