### ISSUE TITLE
Traffic calculation

### ISSUE THREAD

**Issue by AmoAlireza** [alireza0/x-ui#469]
سلام @alireza0 جان
امکانش هست این قابلیت اجرا کنید که نحوه محاسبه ترافیک و زمان بر اساس لینک سابسکرایب باشه؟ مثلا چند مدل مختلف پروتکل و inbound داخل پنل هست که نیازه کاربر بتونه به همشون وصل بشه ولی مشکل اینجاس که ترافیک و زمان جداگونه محاسبه میشه و نمیشه گفت به طور کلی محاسبه کنه.
اگر بشه یه چیزی شبیه fallback که فیلد listen مخصوص میزاری اینم یه قسمت مخصوص بشه ست کرد عالی میشه.
دم شما گرم ❤

**Comment by alireza0** [comment]
درود بر شما
من معمولا به همه گیر بودن سرویس درخواستی دقت میکنم. خود سرویس ساب خیلی مورد نیاز همه نیست و به همین دلیل براش تنظیمات جدایی گذاشتیم.
برای این درخواست شما، باید ساختار جدیدی درست کنیم و نمیشه توی همون ساختار این مدل رو اجرا کنیم.
ساختار جدید هم باعث مشکلات دیگه میشه که ترجیح میدم خیلی درگیرش نشم.
این کار رو یه برنامه نویس میتونه با api به راحتی انجام بده و هر چند ثانیه اطلاعات یک ساب رو راحت بگیره. هروقت به عدد مورد نظر رسید، دستور غیر فعال کردن همه اکانتها رو بده.

به جای تغییر ساختار ترجیح میدم یه نرم افزار دیگه با ساختار مناسب برای همه درخواست ها رو از اول بنویسم.

**Comment by AmoAlireza** [comment]
تشکر علیرضا جان, بله در جریان اجرای این با api هستم منتهی گفتم اگر بشه به کد اصلی پنل اضافه کرد بهتر میشه.
و یک نکته دیگه ای شما فکر کنم که دارین روی یک مدل پنل دیگه کار میکنید جسارتاً در چه مرحله ای هستش اگر فضولی نباشه 😅

**Comment by alireza0** [comment]
در مرحله طراحی دیتابیس سه چهارماهه مونده 🤦🏻‍♂️

**Comment by AmoAlireza** [comment]
بابت زحمت هایی که میکشین ممنون ❤
بیزحمت روی پنل جدید محدودیت کاربر هم بزارید لطفا چون من از پنل شما بصورت شخصی استفاده میکنم و به خاطر محدودیت کاربر برای فروش از پنل جناب ثنایی عزیز هم استفاده کنم.
دمتون گرم 🤍
