### ISSUE TITLE
can't install using docker

### ISSUE THREAD

**Issue by kingofcs20** [alireza0/x-ui#47]
**Describe the bug**
[A clear and concise description of what the bug is.
](docker: Error response from daemon: pull access denied for alireza0/x-ui, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.)

**Comment by kingofcs20** [comment]
the problem is your docker hub user is alireza7

but the code u said to install docker is  `alireza0/x-ui:latest` :)
fix it mate

**Comment by alireza0** [comment]
Thank you for your hint. It is fixed now.
FYI:
- It is also available via github package as well: `ghcr.io/alireza0/x-ui:latest`
- You can use `docker-compose.yml` file for `docker-compose` easy run
