### ISSUE TITLE
Is HTTP + TLS possilbe ?

### ISSUE THREAD

**Issue by theahz** [alireza0/x-ui#471]
Hi hope you are having a nice day , i have a request for the panel and that is adding tls support for HTTP as an application protocol . Right now we do have the option to use tls with http while using vless or vmess as the application layer protocol , but there is no option to use tls with http when it is being used as an application layer protocol . Is there a reason for this ? because not only plain http is not safe for daily usage but it is also pretty straight forward for advanced firewalls. A layer of protection would be nice since we are already using tls with other protocols and it is only missing for this protocol . I brought this up since you just updated your panel to support multi user for http protocol and i was curious about this.

**Comment by alireza0** [comment]
Hi,
Actually, x-ui is a web-UI for better using of this xray-core.

There are two facts here:
1. HTTP protocol is for http proxy that you can use simply in your system/browser and the protocol has no TLS.
2. X-ui is providing the configuration for feeding xray and we are following xray configuration.

P.S. HTTP proxy with TLS is not innovated yet.

**Comment by theahz** [comment]
I see, so basically it must be added to xray core first and then to x-ui if i got it right , anyhow thank you for clarifying .

**Comment by alireza0** [comment]
This protocol should be first innovated and documented.
