### ISSUE TITLE
امکان ایجاد کلاینت با up و down سفارشی(برای مواردی از قبیل تغییر لوکیشن و تغییر پروتکل)

### ISSUE THREAD

**Issue by LordDeveloper** [alireza0/x-ui#472]
سلام وقتتون بخیر، امیدوارم حالتون خوب باشه. قبل از همه چیز عذر می‌خوام که issue با زبان فارسی باز کردم، از اونجایی که زبانم زیاد خوب نیست، شاید نتونم منظورم رو به خوبی منتقل کنم.

برحسب موضوع، درخواستم و همچنین پیشنهادم برای وجود قابلیتی هست که بتونیم موقع ایجاد کلاینت توسط API رسمی توسط مسیر /addClient بتونیم مقدار up و down رو هم ارسال کنیم؛ اگر هم این موارد خالی باشه، به صورت پیشفرض برروی 0 تنظیم بشه.

برای این که بهتر متوجه منظورم بشید لطفاً این دوتا خط کد رو نگاه کنید:
https://github.com/alireza0/x-ui/blob/9e3c7b1db6e49af182f708f21beacef383767ea2/web/service/inbound.go#L444
https://github.com/alireza0/x-ui/blob/9e3c7b1db6e49af182f708f21beacef383767ea2/web/service/inbound.go#L885

سپاس از شما.

**Comment by alireza0** [comment]
درود بر شما
شما میتونید مقدار باقی مانده ترافیک کاربر رو به عنوان ترافیک مجاز وارد کنید و یا با تغییر داخل دیتابیس به چیزی که میخواهید تبدیل کنید.

**Comment by LordDeveloper** [comment]
> درود بر شما شما میتونید مقدار باقی مانده ترافیک کاربر رو به عنوان ترافیک مجاز وارد کنید و یا با تغییر داخل دیتابیس به چیزی که میخواهید تبدیل کنید.

ممنون از پاسخ‌گویی، در مورد دیتابیس که best practice محسوب نمی‌شه، چون تعداد سرورهام بالاست و من بخوام با ssh لاگین بشم و دیتابیس رو تغییر بدم زیاد جالب نمی‌شه نتیجه کار.

و این که من مصرف آپلود و دانلود و همچنین مصرف کلی رو به کاربران در قالب ربات تلگرام نشون می‌دم و محاسبه مقدار باقی مانده کمک کننده نیست.
این پیامم تو گروه هست اگه می‌شه لطف کنید ببینید.
https://t.me/c/1939905425/225036/650753

طبق فرمایش شما درسته می‌شه این کار رو انجام داد ولی این up و down هم اوکی بشه عالی می‌شه.

**Comment by LordDeveloper** [comment]
یا حداقل این بخش مربوط به resetClientStat هم کاش می‌شد یه جوری باشه که بتونیم به مقدار دلخواه این عمل reset رو انجام بدیم. :(

**Comment by LordDeveloper** [comment]
امکانش نیست درسته؟

**Comment by alireza0** [comment]
مزایای این درخواست از معایبش خیلی کمتره.
پنل به اندازه کافی شلوغ هست و ترجیح من اینه که توی پنل گذاشته نشه.
