### ISSUE TITLE
Subscription update intervals

### ISSUE THREAD

**Issue by Enkidu-6** [alireza0/x-ui#474]
Hello again.

I was wondering what exactly is the function of Subscription update intervals? The explanation suggests that it should be forcing clients to update their subscription at a certain interval but it doesn't seem to have any effects on my client applications.

I've even set it to one hour to test the function but on both V2rayNG and NekoRay, it has no effect. Is my understanding of the feature wrong?

Thank you.

**Comment by alireza0** [comment]
Hello,

Your client should support this function. Both v2rayNG and [Nekoray](https://github.com/MatsuriDayo/nekoray/issues/321) didn't accept to deploy this function.
You can use other client applications like clash.
In MacOs/iphone, you can use Shadowrocket.

**Comment by Enkidu-6** [comment]
Got it. Thank you.
