### ISSUE TITLE
ocspStapling

### ISSUE THREAD

**Issue by shahin-io** [alireza0/x-ui#475]
hi, alireza jan.

Please consider adding "TLS(OCSP)Stapling" feature to the panel. i’m already using this feature combined with TLS1.3 via kafka panel and seems actually it works great.

kheyli thanks.

**Comment by alireza0** [comment]
Hello @shahin-io ,

Thank you for supporting me with new applicable feature.
It is ready now and you can build the panel yourself or wait for the next version.
