### ISSUE TITLE
cannot change password. new does not apply

### ISSUE THREAD

**Issue by SaviorVirus** [alireza0/x-ui#479]
Hello. After fresh docker version install you have defaults logpass. But when you change it and panel restarts. every try return only **Invalid username or password.**

**To Reproduce**
1. fresh docker installation
2. login with defaults
3. change password
4. panel restart
5. try to login with new one or old
6. Invalid username or password.

**Desktop (please complete the following information):**
 - OS: Windows 11 build 22621.2134
 - Browser: chrome
 - Version 115.0.5790.171

**Comment by alireza0** [comment]
Hello.
Based on docker function, everytime you reset the docker, everything will be reseted to the first state.
You should use pesistent storage to have persistent database in host.

**Comment by SaviorVirus** [comment]
but password should stores into db. am I right?
volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/

**Comment by alireza0** [comment]
If you set these volumes, it should store the password.
Please check if it is mounted correctly and each time provide last logs as well.

**Comment by SaviorVirus** [comment]
![image](https://github.com/alireza0/x-ui/assets/105457383/2d844fea-5a4e-48c4-a702-03d665d1a7b7)
Sorry mate. Look like I cant read well) I read "New password" where red arrow, and "Confirm new password" where yellow arrow.
