### ISSUE TITLE
Traffic not counting

### ISSUE THREAD

**Issue by theahz** [alireza0/x-ui#480]
Hello! hope you are having a nice day. recently I've noticed a bug in the latest version of panel and that is if a client doesn't have any email, or better to say, the email value of a client is empty the traffic counter bugs out and doesn't count any traffic regardless of how much proxy is being used . you can see an example of this in the picture I'm attaching here .
![photo_2023-08-11_16-43-17](https://github.com/alireza0/x-ui/assets/68293923/8bfd2abe-fde8-48eb-aeee-14a699e012c7)
i tested this multiple times and it seems like it is consistent and happens every time .

**Comment by alireza0** [comment]
Hello,
It is not a bug!
In xray-core, client's traffic reports by email filed. When you don't define email, then there will be no report.
Some other functions will unusable when you define empty email field.
