### ISSUE TITLE
اضافه کردن حجم/تاریخ به کل یوزرا

### ISSUE THREAD

**Issue by MrMehdiAfshar** [alireza0/x-ui#481]
با توجه به شرایط و قطعی های پیاپی سرور های ایران از جمله ابراروان و اسیاتک که همگی میدونیم خیلیا ازین دو دیتاسنتر استفاده میکنن و به علت مجازی بودن سرورا قطعی زیادی رخ میده. یه ایده به ذهنم رسید و دیدم مشکل یه عده فروشنده هم هست که گفتم مطرح کنم. معمولا بخاطر قطعی سعی میکنن یا چند روز تاریخ سرور رو بیشتر کنن یا حجم اضافی برای کاربر بزنن که جبران بشه ولی این مورد توی کاربرای زیاد خیلی زمان بره. یه feature بزنید بشه برای کل کاربرا مثلا به مقدار زمان/حجم اضافه کرد کار خیلی ها حل میشه

**Comment by alireza0** [comment]
ابن درخواست برای همه کاربران استفاده ای ندارد.
دستکاری های اینچنینی بهتره با API و یا دستی در دیتابیس انجام بشه.
