### ISSUE TITLE
Fail2ban

### ISSUE THREAD

**Issue by MrMehdiAfshar** [alireza0/x-ui#482]
بیشتر کسایی که از پنل استفاده میکنن حداقل یه بار fail2ban رو تست کردن که در بیشتر مواقع ارور cannot import name 'mutablemapping' رو میگیرن. من چندان دانش فنی پایتون ندارم ولی با کمک یکی از دوستان فهمیدیم که موقع نصب fail2ban معمولا python3.8 هم نصب میشه که با حذف کردن پایتون fail2ban هم پاک میشه. همچنین با نصب python3.12 پنل به درستی کار میکنه و میشه ایپی لیمیت رو کار انداخت. اگه این مسئله مربوط به پنل هست خیلی خوب میشه حل بشه
![IMG_20230811_231849_426](https://github.com/alireza0/x-ui/assets/140209118/2c541f75-2ba0-4353-89e7-4a4af47eb1ad)

**Comment by alireza0** [comment]
در مورد این رپوزیتوری نیست
