### ISSUE TITLE
change alpn priority order

### ISSUE THREAD

**Issue by shahin-io** [alireza0/x-ui#483]
hello, alireza jan.

can u please change "alpn" selection order in panel? when i select "HTTP1" and then "h2" in the panel, alpn section in generated config link and also file on the server will be saved in the order that I had chosen in row [http/1.1,h2]. since the newer version must be first and not everyone knows how to select in the right order. it’s better to change orders to "H3, H2, HTTP1" in the panel and prevents potentially risk of associated with it. 
thanks for your time and work.

**Comment by alireza0** [comment]
Hello @shahin-io ,

I can't find any document related to this order which you consern about. If you know sth, please share it here.
Please be informed that alpn in TLS object is different.
You can find some hints about Fallback's ALPN in [XTLS documentation](https://xtls.github.io/config/features/fallback.html#fallbackobject):

![image](https://github.com/alireza0/x-ui/assets/12573084/3fe10bcb-425a-45a4-bf42-f5f85cc1afcf)

**Comment by alireza0** [comment]
The reason I did it as checkbox was that the priority is not important in xray and it is only for checking if tls should support these methods.

In cloudflare it is important to use max/min version and it starts from max.

If priority is important, then I should think about another way of form's input!

BTW, in this way you can disable the http1 which you can not do it in cloudflare.

**Comment by alireza0** [comment]
I have to find a better way in frontend for sorting this value of ALPN automatically.

**Comment by alireza0** [comment]
After trying lots of possible solutions and checks, the best way is to showing the periority.
It is added now. Please wait for the next version or compile it manually.
