### ISSUE TITLE
Generate self-signed certificate for TLS

### ISSUE THREAD

**Issue by mozilla-firefox** [alireza0/x-ui#489]
سلام
لطفا یه دکمه اینجا قرار بدید تا خودکار یه سرتیفیکیت ایجاد کنه
هنگام تست پروتکل ها و سناریو های مختلف به کار میاد این
![image](https://github.com/alireza0/x-ui/assets/41063376/3c5b20b7-c7a3-457c-bbed-b27430cb7d80)
با تشکر

**Comment by alireza0** [comment]
درود بر شما.
ایجاد کردن سرتیفیکیت کلی پارامتر داره و فقط کافیه یکبار ایجاد بشه.
از نظر من، مواردی که استفاده خیلی کمی دارند بهتره پنل رو شلوغ نکنن
