### ISSUE TITLE
SSL file does not exist

### ISSUE THREAD

**Issue by Trenobol** [alireza0/x-ui#490]
Tell me where to insert SSL certificates ?

I created them via certbot and got the path
/etc/letsencrypt/live/MYDOMAIN/fullchain.pem
/etc/letsencrypt/live/MYDOMAIN/privkey.pem

But when inserting I get an error
Modify Settings Fail: cert file <> or key file </etc/letsencrypt/live/here my domain> invalid: open : no such file or directory

**Comment by vildyaev** [comment]
на 3X-UI также... на хабре есть обсуждение, но ничего не понял в итоге

**Comment by Trenobol** [comment]
> on 3X-UI too ... I join the question of how to show the path correctly
I installed 3X-UI and it worked
At 3X-UI, the SSL key files were immediately installed in root/cert

And in GUI:
Panel Certificate Public Key File Path: /root/cert/MYDOMAIN/fullchain.pem
Panel Certificate Private Key File Path: /root/cert/MYDOMAIN/privkey.pem
Panel URL Root Path: /root/

But in X-UI it doesn't work...

**Comment by alireza0** [comment]
Are you using Docker ?

**Comment by Trenobol** [comment]
> Are you using Docker ?

Yes

**Comment by alireza0** [comment]
> > Are you using Docker ?
> 
> 
> 
> Yes

Predictable!

Please search and learn how to mount a path into docker.
