### ISSUE TITLE
Always first client is edited while Edit button is pushed

### ISSUE THREAD

**Issue by gleruzh** [alireza0/x-ui#491]
**Describe the bug**
While push inbounds-> ANY client Edit button always got to first client edit form

**To Reproduce**
1. Go to '<your link to panel>/xui/inbounds'
2. Click on 'edit button' of any NOT first client 
3. See it's first one.

**Expected behavior**
Edit the client which edit button is pushed

**Desktop (please complete the following information):**
 - Mozilla Firefox, Google Chrome
 - Latest stable

**Additional context**
I've found in `web\html\xui\inbounds.html` and changed
```
 firstKey = Object.keys(client)[0];
 ```
 to
 ```
 firstKey = Object.keys(client)[2];
```
After rebuild app, it shows propper client on edit button and seems working as expected

**Comment by alireza0** [comment]
It is about a bug reported before related to ShadowSocks inbounds only and fixed in this commit:
[fix finding client issue](https://github.com/alireza0/x-ui/commit/c6816d253120462f38f144899a3c6be4fc87074f)
Please wait for new release or compile it manually.
