### ISSUE TITLE
enable and disable problem

### ISSUE THREAD

**Issue by aliwishstar** [alireza0/x-ui#494]
علیرضا جان سلام ممنون از زحمات.
من وقتی یک کلاینک روی غیرفعال می کنم یا فعال میکنم ، اعمال نمیشه و سرویس حتما باید ریستارت بشه . میخواستم ببینم مشکل از کجاست. چون یادمه گفته بودی دیگه به ریستارت سرویس نیازی نیست یعنی نه اتوماتیک ریستارت میشه و نه نیاز هست دستی سرویس رو رستارت کنیم .
ممنون میشم راهنمایی کنی.

و اینکه اگر به صورت دستی توی فایل config.json تغییر اعمال کنیم راهی هست که بدون ریستارت سرویس تنظیمات اعمال بشه ؟

**Comment by alireza0** [comment]
درود بر شما
ممنون میشم اگر گزارشی دارید دقیقا نوع گزارش (خطا، پیشنهاد، سوال) رو درست انتخاب کنید.
برای گزارش خطا حتما سوالات مربوطه رو جواب بدین و حتما لاگ مربوط به مشکل رو ارسال کنید.
توی تست های ما این ویژگی به درستی کار میکنه و خطای شما ممکنه به دلیل تنظیمات اشتباه باشه.

> و اینکه اگر به صورت دستی توی فایل config.json تغییر اعمال کنیم راهی هست که بدون ریستارت سرویس تنظیمات اعمال بشه ؟

این فایل به صورت اتوماتیک در هربار ریستارت ایجاد میشه. تغییرات دستی کاملا نادیده گرفته میشه.
