### ISSUE TITLE
ارور 403 گوگل

### ISSUE THREAD

**Issue by mmd1401** [alireza0/x-ui#495]
سلام
در پنل شما، سرویس های گوگل و اصلا خود گوگل باز نمیشه و ارور 403 ظاهر میشه
میشه یک روش معرفی کنید برای حل این مشکل

**Comment by alireza0** [comment]
درود بر شما
این پنل با گوگل کاری نداره و فقط جهت درست کردن تنظیمات برای xray-core ساخته شده.
اگر توی تنظمیاتتون، تنظیمات مسدود سازی برای کشور چین رو فعال کردید باید غیر فعال کنید.
