### ISSUE TITLE
Expected BEGIN_OBJECT but was string

### ISSUE THREAD

**Issue by artheadsgames** [alireza0/x-ui#498]
Hello, when importing config file downloaded from X-UI, the client V2rayNG returns error: `Expected BEGIN_OBJECT but was string`. However, if I open the config file and just copy its content to import it from clipboard - it works.
At the same time the same file imported and works just fine in another client Nekobox.

**Comment by alireza0** [comment]
Hello.
Config file is not applicatble for clients like V2rayNG.

**Comment by artheadsgames** [comment]
Hi, but which client I can use on iPhone to use Config file?

**Comment by alireza0** [comment]
No client application could use this. It is only for setting up another `xray-core` for advanced users or just for your knowledge if the configuration is correct :)

**Comment by artheadsgames** [comment]
However, I have X-UI installed on my server and using it successfully with [Nekobox](https://github.com/MatsuriDayo/nekoray) client on both Android and Windows... I think we are talking about different things, isn't it? :)

**Comment by alireza0** [comment]
If you are talking about `config.json` file which you can download it from main page, it is not useful in clients.

If you mean a copy function in inbounds page from a client row, you should use `link` which is a url for client's applications.

In some client applications you can also import a `json` configuration which x-ui could not generate it yet.

**Comment by artheadsgames** [comment]
I'm talking about info for clients on inbounds page, yes ) 
Do you mean a Subscription link?

**Comment by alireza0** [comment]
Nop! Subscription link is a http(s) url. But I mean vmess:// or vless:// links

**Comment by artheadsgames** [comment]
Ok, got it! Thanks for everything!

**Comment by alireza0** [comment]
No problem :)
