### ISSUE TITLE
درخواست امکان اضافه کردن دو اکانت با ایمیل و آیدی یکسان

### ISSUE THREAD

**Issue by asadace1** [alireza0/x-ui#499]
برای ما نیاز هست که یک کاربر بتونه از دو پروتکل متفاوت استفاده کنه
مثلا ما یه ایمیل تو یه اینباند درست کنیم و همون ایمیل رو تو یه اینباند دیگه درست کنیم و ترافیک براساس همون ایمیل باشه، یعنی کاربر از هر پروتکل استفاده کنه ترافیک رو ایمیل بندازه
مثلا با همراه اول vless بهتره و با ايرانسل vmess و ما دو تا لینک داشته باشیم از یه ایمیل، که بتونیم از هرکدوم استفاده کنیم
یه جاهای دیگه هم به درد میخوره مثلا ما میدونیم tcp رو که الان باز کردن قراره دوباره بسته باشه و قبل از بسته شدن کپی اینباند بزنیم و تمامی یوزرها رو به اینباند جدید مثلا ws کپی کنیم
و بعد لینک جدید بهشون بدیم داشته باشن و هر موقع استفاده کنن از لینک جدید ادامه ترافیک یا زمان اون قبلی رو بندازه
آیا امکانش هست این کارو بکنید؟

**Comment by X-Oracle** [comment]
you cant do that . unless 2 account are in deferent port .
its not x-ui limitation, its xray's.

**Comment by alireza0** [comment]
لطفا قبل از درخواست، درخواست های قبلی رو چک کنید. این سوال چندین بار جواب داده شده.
