### ISSUE TITLE
device alert + dark theme

### ISSUE THREAD

**Issue by AmoAlireza** [alireza0/x-ui#50]
Hi
thx for best x-ui panel ♥.
can you add device alert(will notify in telegram bot when connected ip changes) like [FranzKafkaYu](https://github.com/FranzKafkaYu/x-ui) and dark theme in next update.

**Comment by alireza0** [comment]
Hello @alireza0,
Thank you for your kind message.
Login alert is already exists. Could you please explain more about `connected IP change` ? I cant find it in [FranzKafkaYu](https://github.com/FranzKafkaYu/x-ui)

Regarding dark-theme, it is a good idea. I will try to add it

**Comment by alireza0** [comment]
Thank you for this explanation.
I have removed the IP limit and other auxiliary codes to have it as simple as possible.
This change needs checking access log and create new database for client logs.
I will let it be open to check if it is possible to have it in the future.

P.S. [FranzKafkaYu](https://github.com/FranzKafkaYu/x-ui) is not a fully open-source project and they didn't update their code in their public repo.

**Comment by AmoAlireza** [comment]
thx mr @alireza0 ♥.

**Comment by MG-Token** [comment]
hi 
we need ip limit to control people who share link's to channel and uhhh...
in  MHSanaei page its released ip limit
https://github.com/MHSanaei/3x-ui/releases
if you can add ip limit + device alert + dark theme this panel will go to very beautiful and complete...

**Comment by alireza0** [comment]
Hello @MG-Token 
Thank you for using and help us to improve the codes.
MHSanaei and me were decided to keep this x-ui panel as simple as possible.
Instead we will work together in 3x-ui or other projects to have more complex and and advanced solutions.

- For sure device alert could be enabled in 3x-ui but not this x-ui.
- Dark theme is not supported by this old front-end framework, but I will try to add it soon manually.
- Please be patient to use xra-core 1.8.0 which is not mature yet

**Comment by MG-Token** [comment]
hi you can use 
https://github.com/NidukaAkalanka/Xray-core
this xray core code is have ip-limit...
this panel is best work on ip limit with access log and use blockedips file to block ip then this will use more cpu and more io req but still we need him

**Comment by AmoAlireza** [comment]
hi @alireza0 
actually i have idea, bring back ip limit but with an interesting trick, the trick is when user connect more than device in same time we define in panel the link will disabled for a special time(i accept maybe it will hard to do it with for each client in one inbound) and we can set this special time in panel setting like in ***other setting*** like you set user if connected more than 2 device the link will disable for 10 min or "INPUT TIME" hour & day & week and etc... like crontab time.

and can you add disable and enable option for clients like for inbounds.
like picture below:
![Capture](https://user-images.githubusercontent.com/79990596/225252132-b00046b9-2be3-4173-97a7-12f30a0cc78b.JPG)

**Comment by alireza0** [comment]
@AmoAlireza @MG-Token 
Device detection is not possible and IP Limit is not supported by official xray-core.
For this purpose we should use another fork of xray-core instead, and taking care of it.
In another hand, this solution is not working properly and may cause several problems as I described before. Additionally it interprets the `access.log` and will affect I/O and cpu.

In this panel, simplicity is one of the most important basics. It might be added to [3x-ui](https://github.com/MHSanaei/3x-ui).

BTW: Your suggestion to have dark-theme is in progress! Thank you for providing this nice idea.

**Comment by AmoAlireza** [comment]
@alireza0 thx ♥
and how about enable/disable button for each client? possible?

**Comment by MG-Token** [comment]
hi again and tnx to added dark mode
its have 2 or maybe 3 problem in 3x-ui
First:
https://mega.nz/file/uSRAWYTC#sw0NcCqCAETphoee8KraUG8YzaVAxa7HqTQbWlZOtPE
when we try to select time for clients its will be show a white screen... (but can select manual at top screen)
2:
i think the MH panel ip limit is not work when we try to download with 2 ip its continue and once ip is not blocked...
3:
add a clear log on log report...
maybe add save log can be help to handle.... (cant select all log to clipboard (ctrl +a) :) )

at the last its very good panel 
if you can use async or multi thread its will be go good enough...
Thanks

**Comment by alireza0** [comment]
Dear @MG-Token 
Thank you for this bug report.
Next time, if you want to report new bug, please open new issue. It is not easy to find the problems by this way.
1st: It will be fixed in new release
2: As I mentioned before, these panels are not designed to support this. It works fine as much as it is injected to xray-core.
3: It will be added soon in a better way.
