### ISSUE TITLE
خطای نمایش تاریخ در پنل 

### ISSUE THREAD

**Issue by mehranmts** [alireza0/x-ui#500]
سلام وقت بخیر
بابت پروژه ای که بصورت اوپن سورس در اختیار عموم قرار دادین ممنونم.
مشکلی در نمایش تاریخ در پنل وجود داره.
بنده با کد php  زیر برای ساخت کاربر جدید، مقدار  expireTime  رو بصورت timestamp ارسال میکنم

$today = new DateTime();
$today->add(new DateInterval('P1M'));
$expire_date = $today->getTimestamp();

ولی تاریخی که برای این فیلد در پنل تنظیم میشه مقدار زیر هست
1970-1-20 18:24:8
لطفا در این مورد راهنمایی بفرمایید و یا اگه ایرادی هست برطرف کنید.
 باتشکر

**Comment by alireza0** [comment]
درود بر شما
لطفا در انتخاب نوع گزارش دقت کنید.
این مشکل مربوط به نرم افزار شما میشه. عددی که شما ارسال میکنید، بر اساس ثانیه است و پنل به عددی میلی ثانیه نیاز داره.
میتونید با ضرب عددتون در عدد هزار این مشکل رو حل کنید.
