### ISSUE TITLE
ارور ساب لینک بعد از اضافه کردن و ریستارت کردن 

### ISSUE THREAD

**Issue by SatanicDeveloper** [alireza0/x-ui#503]
سلام من یک وب سرویس روی دیتابیس x-ui شما پیاده کردم بعد اضافه کردن هر کانفیگ هم x-ui ریستارت میکنم با این کامند systemctl restart x-ui. همچیز درست کار میکنه و میتونم کانفیگ اضافه کنم از طریق همین وب سرویس ولی یک مشکل اساسی دارم اونم اینه که وقتی کانفیگ اضافه میکنم ساب لینک اون کانفیگ کار نمیکنه . جالب اینجاست که حتی من پنل و خود x-ui هم ریستارت میکنم بازم کار نمیکنه . ولی فقط توی یک حالت کار میکنه اونم اینکه یک بار همین کلاینت رو فعال و غیر فعال میکنم همچیز برمیگرده حالت عادی و درست کار میکنه.لطفا راهنمایی کنید که چه کاری باید انجام بدم .

**Comment by alireza0** [comment]
درود بر شما
دلیل این مورد اینه که اطلاعاتی که توی دیتابیس وارد میکنید به صورت درستی وارد نشده.
لطفا مشابهش رو با خود پنل درست کنید و بررسی کنید که مشکل شما دقیقا کجاست.

**Comment by SatanicDeveloper** [comment]
ممنون ازتون چک میکنم مجدد.
