### ISSUE TITLE
Expire Date Enhancemet

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#504]
@alireza0 

Right now it is shown like date but it is not possible for admin to tell how much date is remaining unless it is calculated by admin and it is not efficient to do for every user .

Can you change it so it is shown remaining days and when hovered shows exact date in lunisolar and solar calendar .

thanks for your attention.

**Comment by alireza0** [comment]
Remain days is reserved for delay-start expiration date!
It makes conflict.
Some users need date and some others want to have remainig days.
As far as there is no value to change the working method, I prefer to keep it as is.
