### ISSUE TITLE
مشکل به هم ریختن تاریخ واتس اپ در گوشی های با سیستم عامل اندرویید

### ISSUE THREAD

**Issue by rezaj1394** [alireza0/x-ui#506]
سلام
من از دو سرور، یکی ایران و دیگری آلمان استفاده کردم و هر دو سرور پنل شما رو نصب کردم و پروتکل هم vless استفاده میکنم. سرعتش هم عالیه و تنها مشکل اینه که تاریخ واتس اپ به هم میریزه و خیلی وقتا اصلا نمیشه وارد واتس اپ شد.
تایم هر دو سرور هم روی تهران تنظیم کردم ولی مشکل همچنان پا برجا هست

**Comment by alireza0** [comment]
درود بر شما

این موضوع به پنل ربطی نداره. لطفا از گروه های مرتبط سوال بفرمایید
