### ISSUE TITLE
Shadowsocks chacha20-ietf-poly1305 name of encryption

### ISSUE THREAD

**Issue by chernyshaw** [alireza0/x-ui#507]
When using `shadowsocks` protocol X-UI have `chacha20-poly1305` encryption.
Most clients (for example NekoRay, Outline VPN client) expect `chacha20-ietf-poly1305` name of encryption. Encryption method is right but name is wrong. Clients aren't working until change name to `chacha20-ietf-poly1305`.

**Comment by alireza0** [comment]
Simply you can change it manually, due to as per documention, both are OKay.
BTW I have added it to the front. Check it in next version.

**Comment by chernyshaw** [comment]
Thank you, Alireza, for fast response and add this to new release.

I tested chacha20-ietf-poly1305 at X-UI 1.5.4 and now Xray 1.8.3 not started with error:

```
Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: unsupported cipher method:
```

Config that was generated:

```json
{
      "listen": null,
      "port": 51185,
      "protocol": "shadowsocks",
      "settings": {
        "clients": [
          {
            "email": "user1",
            "method": "",
            "password": "t5B5Zz7DvOBv+MzzaRz9bAbVZ9CUa/Hg7p6dZCMuKtA="
          }
        ],
        "method": "chacha20-ietf-poly1305",
        "network": "tcp,udp",
        "password": "vFD9tR+6MZYfMMQUzmksoc5jIpOeH54kauv3LTR47+E="
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls",
          "quic",
          "fakedns"
        ],
        "enabled": true
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tcpSettings": {
          "acceptProxyProtocol": false,
          "header": {
            "type": "none"
          }
        }
      },
      "tag": "inbound-51185"
    }
```

**Comment by alireza0** [comment]
@chernyshaw You are right. I have found some visual and non-updated problems from the last night.
But don't rush.
1.5.4 is still `pre-release` and I will publish it after all these fixes and tests.

Thank you for testing soon and founding this bug :)

**Comment by alireza0** [comment]
@chernyshaw It is updated now. Please test it again. I am waiting for your acceptance to publish the new version.

**Comment by chernyshaw** [comment]
Works perfect now! Thank you, @alireza0. Now I can migrate my users from Outline VPN server to X-UI seamless.

**Comment by alireza0** [comment]
Done!
