### ISSUE TITLE
ipv4 configs ineffective

### ISSUE THREAD

**Issue by Enkidu-6** [alireza0/x-ui#508]
**Describe the bug**
IPv4 routing for google is chosen in the panel, yet the traffic is tunneled through IPv6.

![20230826_002252](https://github.com/alireza0/x-ui/assets/101878139/5b6323ff-635a-4006-8aff-a47670389568)

![20230826_001921](https://github.com/alireza0/x-ui/assets/101878139/9e9842e3-58af-41b8-9545-c590e1657a4c)

Panel version 1.5.3,  Xray version 1.8.3,  Config Reality.

Frankly, I don't think any of the IPv4 routing options work as they should at least not with my panels.  

Thank you for your time.

**Comment by alireza0** [comment]
It almost related to the final config.
Please sene the rules and outbound configurations.

**Comment by Enkidu-6** [comment]
Hi, thanks for the response. The config was the standard config out of the box plus two modifications. I reset to default and manually added my adjustments again and all is working now. 

The only manual adjustment that I had made were one to logs: 
```
  "log": {
    "loglevel": "warning",
    "access": "./access.log",
    "error": "./error.log"
  },
```
and of course another one to the IPv4 config:

```
[
  "geosite:netflix",
  "geosite:google",
  "geosite:openai",
  "geosite:spotify",
  "geosite:instagram",
  "geosite:facebook",
  "geosite:binance"
]
```
After the reset I added both modifications again, and it's working as it should. So I'm not sure what the problem was. The rules don't seem to be the cause as they're working now. Perhaps how they were saved?

I seemed to have a problem when it came to saving things. Normally the moment you modify something, the save button turns blue and let's you save them and restart, but lately when I modify things, the save button stays greyed out. I have to refresh the page and modify again, sometimes several times, before the save button turns blue.

So I'm not sure what had happened.  For now, things work and the save button turns blue too.

By the way, is X-ui using  [v2fly Domain List](https://github.com/v2fly/domain-list-community) or is it some other file? I'd like to make sure the category actually exists when I add a geosite .

Thank you for your time. Next time I'll try to file the issue as a question instead of a bug.  :)

**Comment by alireza0** [comment]
When you put a wrong JSON code, browser's code may crash and you need to reload the page.
It is better to write your configurations in a text editor first and then copy-paste it in panel.

As you can see [here](https://github.com/alireza0/x-ui/blob/main/.github/workflows/release.yml#L32-L33) we are using same geofiles:
https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

**Comment by Enkidu-6** [comment]
Yes, thank you. After I asked the question, I went looking through the codes and found the links. I appreciate your time. 

I do think however that something in the last update or two somehow corrupted the database or the config because the same settings were working and somehow stopped working without me making any modifications. I say this because I also have a Sanaei panel on another server and after this incident, I checked that panel too and low and behold, the same problem happened with WARP routing. In that case, IPv4 routing worked but warp routing was ineffective.  I've since filed a ticket for that panel too.

Since both of your panels are similar and you both collaborate extensively, I'm assuming it's caused by something you both use.

Regardless, resetting the config to default settings and putting everything back one by one seems to have solved the problem. I'm just hoping I won't have to do this after each update.

Feel free to close this issue please and again I appreciate the time you spend entertaining my annoying questions.

Cheers.

**Comment by alireza0** [comment]
Please be aware of Warp problems and don't use it for big usages.
It could only handle few connections and may cause crash on xray-core.
