### ISSUE TITLE
Total traffic 

### ISSUE THREAD

**Issue by ErfanTech** [alireza0/x-ui#509]
من به یه یوزر از دوتا اینباند جدا کلاینت میدم 
میخوام مثلا کل ترافیک ۱۰۰گیگ باشه 
چه راهی هست که بشه هردو کلاینت به یه یوزرنیم ترافیک بندازن؟

**Comment by alireza0** [comment]
کل ترافیک رو توی مدلی که الان x-ui داره نمیشه محدود کرد.
تنها راهتون استفاده از API و کنترلش با یه نرم افزار دیگه میتونه باشه.
