### ISSUE TITLE
اضافه کردن قابلیت

### ISSUE THREAD

**Issue by s43id** [alireza0/x-ui#51]
سلام وقتی کانفیگ جدیدی مثلا با VMESS ساخته میشه دیگه نمیشه ادیتش کرد و تغییرش داد به VLess یا...
در صورت لزوم عالی میشه اگه این قابلیت رو اضافه کنید که بتونیم بین پروتکل های مختلف بدون ساخت کانفیگ جدید سوییچ بشیم

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی و ارسال نظرتون
به دلیل اینکه این پروتکل ها تنظیمات جدایی دارند، پنل های مشابه در صورت تغییر پروتکل، کل کاربرها  رو پاک میکنند.
این پنل بیشتر به هدف تعریف چند کاربر روی یک پورت توسعه داده شده.
در صورت نیاز به تغییر پروتکل، راه درست اینه که سرویس جدید تعریف بشه و کاربران جدید با تنظیمات جدید اضافه بشه.
