### ISSUE TITLE
Assistance Request - Connection Limitation in config.json File

### ISSUE THREAD

**Issue by xkjdox** [alireza0/x-ui#510]
Hello X-U Support Team,

I'm reaching out hoping you could assist me with a question regarding connection limitation in the config.json file. Currently, I'm looking to understand the proper way to implement a connection limitation within the configuration file.

Could you provide an example of how I can set connection limitations within the config.json file? not from panel

thanks

**Comment by alireza0** [comment]
The `xray-core` does not implement any connection limit yet.
The file `config.json` is directly related to that project.
