### ISSUE TITLE
Connection getting refused  by xray 

### ISSUE THREAD

**Issue by theahz** [alireza0/x-ui#511]
My Xray fails randomly through out the day with error of "inbound-port number-blocked", this error happens pretty consistently and i don't exactly know how to reproduce it as it happens completely random but I captured part of error log

![photo_2023-08-26_21-35-33](https://github.com/alireza0/x-ui/assets/68293923/0fa9a791-ba98-41c9-8c99-7f006ff515d3)

as it shows in the screenshot , it seems like my requests to Xray is getting blocked for some reason , this only happens for Xray service meaning all open ports and services of the server including ssh can be accessed during this event . there is no expire time or usage size set and both of these values or set to unlimited. the error client receives is "Connection refused" even tho my target port is clearly open . this issue only lasts for 30-40 seconds for all protocols with or without tls and after this time passing issue will be resolved by itself without any action or xray reboot . if this is not a bug , i would be happy to know how can i solve this since it happens every day and makes my connection to the server unstable . I'm using the latest version of the panel.

**Comment by alireza0** [comment]
The `combination of Amazon/Google IPs receiving packets from cloudflare` sounds like a complex solution.
I don't know about this error and your configuration. It is not a normal behaviour!
It seems you configured a fallback with some special configuration.

**Comment by theahz** [comment]
So the reason the IP in the screenshot is coming from Cloudflare is the fact that I'm using Cloudflares cdn with one of my configurations in the panel , the reason the port number is not one of the supported Cloudflare's https port numbers is the fact that i've modified cloudflare's setup in a way that it would change the DP from 443 to my customized port number. this way client will establish a connection to port 443 of cloudflare's edge server while cloudflare will send those requests to my desired port number . Despite the setup the error I'm getting is not related to this setup considering during this event all other configurations also goes down and give Connection refused regardless of Protocol , limitations and configurations . For now I've completely removed all profiles and remade them from scratch and haven't faced this particular error , if this persist I have an idea what might have caused this, so when I created this configurations I removed all Email values as every configuration already had a Label when making them and i was unaware of potential issues i'll face in the future . After  a while i started to notice my connections go down randomly through out the day with connection refused error which was strange to me so i looked into the logs and i realized i was getting this error , " Warning AddClientTraffic update data  empty slice found ", i thought the issue would be solved if i gave a value to Email option in client section and when i did it , the error was in fact solved but i still had connection issues to the server because of this Connection refused error . This time i completely made new profiles without removing email value at the setup and for now it is has been working without problem , but if this is was why this was happening i think it is better to force users to choose a email value and make them unable to leave the email value empty as it causes this issues I've already talked about .

**Comment by alireza0** [comment]
Without email field your statistics won't be calculated and some services could not be delivered.
The error you've mentioned is related to the statistics problems may happen when you remove the email of online client.

**Comment by theahz** [comment]
The thing is the problem insisted even after i fixed the configuration and set an email for the client. It is also worth mentioning even tho i only left one configuration without any email value, during this error all the configurations were affected by it which was strange to me . But after a few days i can confirm the way you can reproduce this error is by making a configuration and a client without any email value and after a while xray goes down with the errors that I've already mentioned. The only thing I did find to fix this issue was by removing the whole configuration and remaking it. I do think it should be mandatory to not leave the email value empty since it causes corruption of xray .

**Comment by alireza0** [comment]
It is not possible to understand the problem without having the complete solution.
But I think it is related to your route configuration. Specially if you are using `Warp`

**Comment by theahz** [comment]
I do use routing but not for warp specially, I've only blocked few ad services and domains and bit torrent. I couldn't gather any log from this error as i checked x-ui logs , x-ui statues and even i looked through journalctl -u x-ui to see if I can gather more info but there was no trace of it . I also did looked through more general logs like syslog or kern.log but still no luck. The only way i was able to see what was wrong with it was by going into the panel and wait for it to fail and then hover over the xray failed icon to see more info about it . If there is a specific path for this that i could check let me know so i could provide more info about this error.

**Comment by alireza0** [comment]
These errors are related to xray-core crashes and it is normal in some situations.
Actually, x-ui is only a controller over the xray-core to make the configurations easier. X-ui is running xray-core as a command in a special golang thread. There is no log capturing implemented to observe the xray's inside activities and crashes reasons.
Therefore it is better to discuss it in xray's forums and groups with proper evidences.

**Comment by theahz** [comment]
In that case it would be difficult to determine what could be the reason of this since xray doesn't have any logger implemented , anyways this issue was solved by removing the profile completely and remaking it , the reason of this happening was the fact the when i created this configuration I left the Email option empty which not only caused incoming traffics not counting but it literally caused network and xray core failure.
