### ISSUE TITLE
BUG Settings not saved in config.json without reloading x-ui

### ISSUE THREAD

**Issue by Pro100x3mal** [alireza0/x-ui#512]
The data in the config.json file is not saved when a backup is created. If you make changes to the connection settings (for example, enable acceptProxyProtocol) and then create a backup copy or view it in the web panel, these settings will not be saved. To do this, you must first restart x-ui and only then the information in config.json will be up to date. Tested in the web panel and when viewing the backup in the Telegram bot

**Comment by alireza0** [comment]
This `config.json` file will be generated automatically based on `x-ui` database.
If you can download/observe it, it means that you can only view it for debug porposes.
All kind of changes in this file will be ignored.
