### ISSUE TITLE
ناپدید شدن اینباند ها

### ISSUE THREAD

**Issue by karimiorg** [alireza0/x-ui#514]
سلام از نسخه آخر پنل سنایی استفاده میکنم، اینباند هام پنهان شدند ولی کانفیگ ها متصل هستن و کار میکنند.

زمانی که این اتفاق افتاد X-ray متوقف شد و من پنل رو آپدیت کردم ، اتصال برقرار شده ولی همچنان اینباند ها نیستند

**Comment by alireza0** [comment]
درود بر شما
پنل ثنایی رپوزیتوری خودش رو داره.
لطفا گزارشتون رو همونجا ارسال کنید
