### ISSUE TITLE
سلام،وقتی روی دکمه Edit Client میزنم صفحه سفید میاد و نمیشه ادیت بزنم    از هر ده تا یوزر سه تاش اینجوری شده و نمیشه ادیت زد

### ISSUE THREAD

**Issue by ErfanAhmadi1378** [alireza0/x-ui#516]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alireza0** [comment]
اگر از پنل دیگه ای مهاجرت کردین توی این نسخه مشکل داره و برای نسخه بعد حل شده.
برای تصحیح توی همین نسخه، کافیه یکبار inbound مربوطه رو ویرایش و ذخیره کنید.

**Comment by alireza0** [comment]
این موضوع در نسخه جدید حل شده. لطفا بروزرسانی کنید
