### ISSUE TITLE
شخصی سازی ترجمه

### ISSUE THREAD

**Issue by mhdkhani** [alireza0/x-ui#517]
سلام ممنون از زحماتتون
من نیاز یکسری ترجمه های ربات تلگرام رو تغییر بدم.مسیر فایل translate.fa_IR.toml که ترجمه های زبان فارسی هست رو توی سرور پیدا نمیکنم.
میشه path پروژه رو بگین یا path این فایل رو.
ممنونم

**Comment by alireza0** [comment]
درود بر شما
مسیر رو اینجا میفرستم:
```
/web/translation
```

**Comment by mhdkhani** [comment]
تشکر
این مسیر رو توی روت اصلی سرور پیدا نمیکنم. اگه امکان داره مسیر اصلی پروژه رو بفرمایید

**Comment by alireza0** [comment]
اگر پیدا نمیکنید احتمالا جای اشتباهی دنبالش میگردین. مسیر پوشه مربوطه از ریشه رپوزیتوری ارسال شده.
