### ISSUE TITLE
traffic usage of clients  show only zero

### ISSUE THREAD

**Issue by shahinfard93** [alireza0/x-ui#52]
The traffic usage of the clients is not increasing with usage. There is a picture that shows the problem. Is there a way to fix this in the settings???
![Untitled](https://user-images.githubusercontent.com/41050901/224116057-5f637aa2-6bca-41c7-bd3a-ad9f7b51db42.png)

**Comment by alireza0** [comment]
Hello @shahinfard93 ,
Did you define the email ?
FYI: Traffic will be calculated only when you define unique email for each user.
