### ISSUE TITLE
باگ در قسمت  تنظیمات 

### ISSUE THREAD

**Issue by mehradraissi** [alireza0/x-ui#522]
سلام 
در قسمت تنظیمات 
Advanced Template 
نمیذاره دکمه save رو بعد از تفییراتی که در outbound میدم بزنم 
دکه توسی هست و دکمه Restart Panel یکسره قرمز و رشون هست. 

هرچی تایپ میکنم دکمه سیو آبی نمیشه که بتونم ذخیره کنم تغییرات رو.

**Comment by alireza0** [comment]
درود بر شما
دکمه ذخیره فقط در صورتی فعال میشه که تنظیماتی که ارائه کردین به فرمت درست json باشه.
