### ISSUE TITLE
Telegram Bot Proxy Settings

### ISSUE THREAD

**Issue by Bullshark21** [alireza0/x-ui#523]
دروود و خسته نباشید من این روش در پنل سنایی https://github.com/alireza0/x-ui/issues/252 تونستم ربات رو راه بندازم ولی وقتی انتقال میدم به پنل شما ربات کار نمیکنه دیگه

**Comment by alireza0** [comment]
درود بر شما
این کد به پنل ربطی نداره. هرجا راه اندازی بشه باید کار کنه.
باید خودتون عیب یابی کنید.
