### ISSUE TITLE
فوروارد

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#526]
سلام ممنون 
امیدوارم یه قسمت بزارید که بتونیم v2ray Client  اجرا کنیم روی سرور یعنی یه کانفیگ بزاریم داخل سرور و پنل ایران که که پنل از این کانفیگ استفاده کنه که ریلتی برای اینکار خوب جواب گو هست

**Comment by alireza0** [comment]
درود بر شما
این قسمت از اول وجود داشته.
میتونید آموزشش رو [اینجا](https://t.me/panel3xui/65) ببینید
