### ISSUE TITLE
exppiry dates of client

### ISSUE THREAD

**Issue by Kup1ng** [alireza0/x-ui#530]
سلام علیرضا

من دارم یک ربات میسازم برای استعلام کانفیگ ها و نیاز دارم که تعداد کل روز هایی که برای هر کلاینت تنظیم شده را داشته باشم
اما داخل پنل نتونستم همچین اپشنی پیدا کنم و وقتی یوزر به کانفیگ وصل میشه عملا دیگه هیچ ردی از تعداد روز های تنظیم شده به جا نمیمونه

راهی داری که بتونه کمکمون کنه؟
یا اگر در نسخه الان راهی نیست لطفا لطفا تو نسخه های بعدی این قابلیت را اضافه کن که در هر وضعیتی که کلایننت قرار داشت ( استفاده شده - استفاده نشده - غیرفعال ) تعداد روز های تنظیم شده برای اون کلاینت را نشون بده

**Comment by alireza0** [comment]
درود بر شما
این قابلیت وجود داره و میتونید ExpiryTime رو با متد های مختلفی ببینید.
Method | Path | Action
-- | -- | --
GET | "/" | Get all inbounds
GET | "/get/:id" | Get inbound with inbound.id
POST | "/getClientTraffics/:email" | Get Client's Traffic

https://github.com/alireza0/x-ui#api-routes
