### ISSUE TITLE
overall issues

### ISSUE THREAD

**Issue by StayAway32** [alireza0/x-ui#532]
سلام و عرض ادب
معذرت میخوام اینجا مزاحمتون شدم بنده از اون یکی پروژتون استفاده میکنم که ورژن 1.7.8 هست

2 تا موضوع تقریبا مهم هست که گفتم اینجا بگم شاید جواب دادید

1 : اینک راهی هست بتونیم پنل رو از h1.1 به h2 ارتقا بدیم ؟ منظورم پنل مدیریت هست

2 : اینک Fail2Ban با Ipv4 به خوبی کار میکنه ولی متاسفانه Ipv6 رو نه به درستی توی IP Log نشون میده و نه بن میکنه در صورتی که مثلا رو اکانت تک کاربر 4 کاربر با Ipv6 وصل باشن

آیا این موارد قابل رفع هستن ؟ اگر وقت گیر هست براتون و یا مقدور نیست ممکنه سرنخی به بنده بدین تا تلاشی برای حل این موضوع بکنم چون الان ایرانسل - رایتل و آسیاتک Ipv6 میدن برای استفاده و واقعیت خیلی هم وضعیت قیمت و تعدادش بهتره هم به نوعی استفاده از هر 2 تا ورژن آی پی یه نوع Load Balance هست
تنها موردی که نمیزاره از Ipv6 استفاده کنیم همینه که Fail2Ban به درستی کار نمیکنه در صورتی که سازنده هاش میگن ما Ipv4 و Ipv6 رو همزمان با هم کاملا ساپورت میکنیم بدون مشکل

ببخشید سرتون رو درد آوردم روز خوبی داشته باشید

**Comment by alireza0** [comment]
درود بر شما
لطفا فقط ایشو های مربوط به این پنل رو اینجا اعلام کنید.
در مورد استفاده از h2 هم راه وجود داره ولی به دلیل اینکه سودی به پنل اضافه نمیکنه و پنل فقط مخصوص مدیرش هست، بهتره به ساده ترین شکل ممکن باشه.

در مورد Fail2ban هم در جریان تنظیمات و تغییرات نیستم

**Comment by StayAway32** [comment]
حق با شماست
ممنون بابت توضیحاتتون و عذرخواهم بابت ایجاد تاپیک اینجا
روز خوبی داشته باشید
