### ISSUE TITLE
Json Converter

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#534]
سلام خسته نباشید چطور میتوانم با پایتون لینک vless یا vmess را به فایل json تبدیل کنم و بلعکس ؟ خیلی گشتم دنبالش اگر api هم باشه مشکلی نیست

**Comment by alireza0** [comment]
درود بر شما
کد ها موجوده میتونید استفاده کنید و یا تبدیل کنید

**Comment by Ghasem1243** [comment]
کجا موجوده اسمت رو علی رضا گذاشتی که چی

**Comment by alireza0** [comment]
دوست عزیز
این پروژه متن بازه و همه کدها کاملا توی رپوزیتوری وجود داره.
با کمی جستجو و داشتن کمی اطلاعات درباره javascript میتونید کدهای مرتبط با ایجاد لینک رو پیدا کنید.
لطفا [این کد](https://github.com/alireza0/x-ui/blob/16113ce7aafbe4f7c8781d876814be3c167f469d/web/assets/js/model/xray.js#L1438-L1450) رو ببینید.

پی نوشت۱:اگر اطلاعاتی وجود نداشت ما هم نمیتونستیم کدها رو بنویسیم و یا ویرایش کنیم.

پی نوشت۲: لطفا قبل از جستجو و اطمینان کامل، مطلب ناصحیح رو انتشار ندید.
