### ISSUE TITLE
تماس تصویری صوتی واتساپ

### ISSUE THREAD

**Issue by ErfanAhmadi1378** [alireza0/x-ui#536]
سلام،تماس صوتی و تصویری برای کاربران ایفون غیر ممکنه 
هم سی دی ان زدم هم ریلتی یکی گفت ی اسکریپت وجود داره برای رفع این مشکل 
آیا این مشکل به پنل برمیگرده؟ و اینکه اطلاعی در مورد این اسکریپت دارید؟
خسته نباشید

**Comment by alireza0** [comment]
درود بر شما
پنل فقط تنظیمات مربوط به xray رو انجام میده و غیر از اون به پنل ربطی نداره
