### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by hosseinbaghi** [alireza0/x-ui#538]
سلام
از پنل ثنایی به پنل شما اپگرید کردم ولی به وب پنل دسترسی ندارم و ارور ۴۰۴ میده
با دامین و ssl وارد پنل میشدم
وب سروری هم ندارم
دوباره اگ به پنل ثنایی اپگرید کنم این مشکل بر طرف میشه
دلیلش چی میتونه باشه؟
ممنونم

**Comment by alireza0** [comment]
درود بر شما
بدون داشتن اطلاعات کافی نمیشه مشکلتون رو تشخیص داد.
لطفا لاگ ها رو هم چک کنید و بفرستید. همچنین نسخه استفاده شده رو اعلام کنید.

**Comment by Valresian** [comment]
Hi!
Problem the same.
Fresh install
~/x-ui# x-ui log
The OS release is: ubuntu
-- Logs begin at Sun 2023-05-14 21:49:45 CEST. --
Sep 09 17:20:27   systemd[1]: Started x-ui Service.
Sep 09 17:20:27   x-ui[4121]: 2023/09/09 17:20:27 x-ui 1.5.5
Sep 09 17:20:27   /usr/local/x-ui/x-ui[4121]: INFO - web server run http on [::] :777
Sep 09 17:21:20   systemd[1]: Stopping x-ui Service...
Sep 09 17:21:20   systemd[1]: x-ui.service: Succeeded.
Sep 09 17:21:20   systemd[1]: Stopped x-ui Service.
Sep 09 17:21:20   systemd[1]: Started x-ui Service.
Sep 09 17:21:20   x-ui[4215]: 2023/09/09 17:21:20 x-ui 1.5.5
Sep 09 17:21:20   /usr/local/x-ui/x-ui[4215]: INFO - web server run http on [::] :777

**Comment by alireza0** [comment]
@fars0ng Hi
Did you configure the panel settings again ?

**Comment by fars0ng** [comment]
@alireza0 
First time i used custom ports and creds.
Next i tried without modification.
Just tried docker
Unfortunately "404 page not found"

**Comment by alireza0** [comment]
There is a diference between `3x-ui` and `x-ui` in url:
3x-ui root : /panel/
x-ui root: /x-ui/

**Comment by fars0ng** [comment]
> @fars0ng Hi
> Did you configure the panel settings again ?

Yep, clean reinstall with default config was successful.
Thanks a lot for support!

**Comment by hmd20s** [comment]
سلام
قبل هر چیزی بابت پنل دمت گرم

بی زحمت کد Certificate رو برام میفرستی ممنون میشم تشکر

**Comment by alireza0** [comment]
@hmd20s 
دوست عزیز
لطفا برای سوالاتتون از ایجاد سوال جدید استفاده کنید.
در ضمن سوال شما واضح نیست. کد certificate معنی نمیده.
لطفا در یک ایشو جدید سوالتون رو واضح مطرح کنید.
