### ISSUE TITLE
تانل کردن

### ISSUE THREAD

**Issue by mehradraissi** [alireza0/x-ui#539]
علیرضا جان سلام و ممنون از پنل عالیت. 
یه سوال داشتم من با doko-demo door تانل کردم بین سایت ایران و خارجم، الان با توجه به اینکه داریم نزدیک میشیم به لحظات ملکوتی میخواستم بدونم روش من در زمان اختلالات کار میکنه ؟ یه دوستی گذاشته بود برای وقتی که اینترانت میشه بهتره از iptables استفاده کنید و یه روشی هم برای outbound ها خود شما یاد داده بودید میخواستم ببینم تو بدترین شرایط کدوم روش بهتر کار می کنه برای ما ایرانی های بیچاره با محدودیت های فراوان 
ممنونم

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم
اختلالات روش خاصی نداره و در صورت قطعی باید بدونید چه روزنه هایی وجود داره.
روش dokodemo-door با iptables از نگاه کلی شبیه به هم هستند.
ولی تانل outbound و مخصوصا روش reverse-proxy بیشتر توصیه میشه.
اگر ارتباط سرور ها با خارج قطع نشه، همه روش ها جوابگو هستند. اگر یکطفه قطع بشه فقط reverse جوابگو هست.
اگر کلا قطع بشه هیچکدام جوابگو نیستند!

**Comment by alireza0** [comment]
اینترانت به خارج راهی نداره!
قطع یکطرفه یعنی از ایران به خارج نشه وصل شد ولی از خارج بشه به سایتها و دیتاسنترهای ایرانی وصل شد

**Comment by mehradraissi** [comment]
> 

 اینجوری یعنی dokodemo کار نمیکنه ؟ فقط reverse ?  من چون deko demo کردم میخوام ببینم اگه اینجوری برم زودتر reverse کنم . ممنونم

**Comment by alireza0** [comment]
تنظیم تانل reverse برای مدلهای بیشتری جواب میده و معمولا سرعت خوبی هم داره.

**Comment by kalilovers** [comment]
> درود بر شما سپاسگزارم اختلالات روش خاصی نداره و در صورت قطعی باید بدونید چه روزنه هایی وجود داره. روش dokodemo-door با iptables از نگاه کلی شبیه به هم هستند. ولی تانل outbound و مخصوصا روش reverse-proxy بیشتر توصیه میشه. اگر ارتباط سرور ها با خارج قطع نشه، همه روش ها جوابگو هستند. اگر یکطفه قطع بشه فقط reverse جوابگو هست. اگر کلا قطع بشه هیچکدام جوابگو نیستند!

تو ریورس میتونیم پروتکل اتصال اوتباند رو تایین کنیم مثلا ریلیتی باشه با ایپی 6 ؟ چون این پروتکل برا اوتباند خیلی خوب جواب داده سادش . ریورسش رو کار نکردم تازه اومده
