### ISSUE TITLE
Add a handy copy function for socks5 format

### ISSUE THREAD

**Issue by o02** [alireza0/x-ui#54]
Hope a handy copy function can be added for socks5 format, thanks. like this
![11](https://user-images.githubusercontent.com/38731893/224194741-e88f69b3-7fc6-4a88-83c7-112049ae9ade.png)

**Comment by alireza0** [comment]
Hello @o02 ,
Good point!
I have removed it for all protocols. It should be added for single-user inbounds. In the next version you can find it in `operate` menu.

**Comment by alireza0** [comment]
But copy function is only supported for protocols that has `link` capability.

**Comment by o02** [comment]
You can add a "view" function, and a window will pop up to display the contents of IP/port/account/password.

**Comment by alireza0** [comment]
I will do so
