### ISSUE TITLE
The login time limit has expired, please log in again

### ISSUE THREAD

**Issue by voiprostov** [alireza0/x-ui#546]
After logging into the control panel, the message appears after a few minutes:
_The login time limit has expired, please log in again_

![image](https://github.com/alireza0/x-ui/assets/12111118/37b8acb6-8695-43af-989c-818260ab9e7d)

Session maximum age set 1000

**Comment by alireza0** [comment]
You can check your cookies in the browser's developer mode if the expiration time is set correctly.

**Comment by voiprostov** [comment]
![image](https://github.com/alireza0/x-ui/assets/12111118/00330301-7904-4844-96c5-d29a3af39465)
If you leave a tab in the background with auto-refresh enabled, the session ends after a while.
