### ISSUE TITLE
UDP problem in iran server

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#547]
hi there hope you doing well 
I use SSH reversed tunnel port forwarding method by using this command :
ssh -N -R 0.0.0.0:65535:localhost:65535 root@IR Server
*65535 is Warp Local port on Germany server 

and i use this section as outbound on my server in Iran and need to mention that users get mananged by iran server

[
  {
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "127.0.0.1",
          "port": 65535
        }
      ]
    }
  },
  {
    "protocol": "freedom",
    "settings": {}
  },
  {
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }
]

Evrything is ok but i cant make a call using whatsapp etc. 

can you help me here ?

**Comment by alireza0** [comment]
Hi.
This configuration is not stable.
First note: Don't use WARP for all the traffics. It could not do that!
Your problem: Warp configuration should be configured to accept UDP as well.

**Comment by wulfric93** [comment]
how can i cofigure it to do so ?

**Comment by wulfric93** [comment]
بذارید فارسی بگم 
من با روش تونل معکوس پورت وارپ روی سرور خارج رو وصل کردم به همون پورت روی سرور ایران 
همه چیز اوکی هست ولی تماس ها که باید بر بستر UDP  باشن امکان اتصال ندارن 
آیا راهی هست که ترافیک UDP از داخل همون تونل معکوس بر بستر TCP  منتقل بشه ؟

**Comment by alireza0** [comment]
پروتکل وارپ چه در سرور داخل و چه در خارج، تحمل ترافیک کامل کاربر رو نداره. بهتره فقط برای دیدن وب سایت هایی خاص که با IP دستاسنتر شما مشکل دارند استفاده بشه.
من با وارپ زیاد کار نکردم ولی ظاهرا نسخه های جدید، با udp و درخواست های tcp به سایتهای ایرانی مشکل داره و باعث از کار افتادن xray هم میشه.

**Comment by wulfric93** [comment]
خب من الان میخوام که یوزر هام روی سرور ایران باشن و با یه outbound  بتونم که سیستم درست کار بکنه من جمله تماس صوتی که بر بستر udp انجام میشه 
شما روشی رو بلد هستید ؟

**Comment by alireza0** [comment]
1. [xray chain](https://alireza0.github.io/fa/docs/security/chains/#%DB%B5-%D8%B2%D9%86%D8%AC%DB%8C%D8%B1%D9%87-xray)
2. [reverse](https://alireza0.github.io/fa/docs/security/reverse/)
