### ISSUE TITLE
Duplicate email

### ISSUE THREAD

**Issue by ErfanSahabShabani** [alireza0/x-ui#548]
**Is your feature request related to a problem? Please describe.**
Make it possible to add duplicate email for the same uuid in more than one inbounds

**Describe the solution you'd like**
A way to bypass the limitation when using REST Api

**Describe alternatives you've considered**
I have been adding different emails so I sum it up each time getting clients.

**Comment by alireza0** [comment]
It is about a duplicate issue and answered before.
By original structure of database and x-ui, we cannot use duplicate email.
It is better to do it by API as well as you are doing it
