### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by mnhgsd** [alireza0/x-ui#552]
**warp could not be installed**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alireza0** [comment]
Warp is not provided on this panel. If you need to install it, do it by your own risk.

**Comment by wulfric93** [comment]
> Warp is not provided on this panel. If you need to install it, do it by your own risk.

can i ask why ?

**Comment by alireza0** [comment]
Personal decision!
Using a bunch of other tunnels makes the pannel unstable.

**Comment by wulfric93** [comment]
it is stable with warp
Here is my config.json file 
take a look 
so far i've encounter no problem with this
[config.json](https://github.com/alireza0/x-ui/files/13363300/config.json)
