### ISSUE TITLE
واضح نبودن نحوه استفاده از برخی آرگومان ها در api

### ISSUE THREAD

**Issue by moradpoor** [alireza0/x-ui#557]
سلام و عرض ادب
جسارتا بنده نتونستم توضيح درستی براي api پیدا کنم 
مثلا برا آپدیت کلاینت چه چیز هایی باید به روت "/updateClient/:clientId" پاس بشه , چی رو اپدیت میکنه ؟ تاریخ رو ? حجم رو ؟ ...

با تشکر از زحمات شما

**Comment by alireza0** [comment]
درود بر شما

زیر جدول API توضیح دادم:

*- The field clientId should be filled by:

client.id for VMESS and VLESS
client.password for TROJAN
client.email for Shadowsocks

**Comment by moradpoor** [comment]
سلام بله اون مورد که کاملا واضح بود منظور بنده اینه که چه دیتایی از کاربر رو باید براش ارسال کنیم که اپدیت کنه ؟

**Comment by alireza0** [comment]
هر جایی که مشکل دارید، میتونید از دیتایی که مرورگر شما زمان کار با پنل ارسال میکنه الگو بگیرید:

یک inbound باید بفرستید که فقط ویژگی های های id و settings رو داره.
توی settings هم فقط ویژگی clients با تمام اطلاعات همون کاربر ارسال میشه. برای مثال:
```json
{
  "id": 18,
  "settings": "{\"clients\": [{ \"id\": \"19de609e-2d3c-4365-bca0-5b2d83b86d75\",\"flow\": \"\", \"email\": \"email1\",\"totalGB\": 0,\"expiryTime\": 0, \"enable\": true,\"tgId\": \"\",\"subId\": \"\"}]}"
}
```

اطلاعات داخل settings باید یک JSON تبدیل شده به STRING باشه. نمونه JSON در مثال بالا:

```json
{
  "clients": [
    {
      "id": "19de609e-2d3c-4365-bca0-5b2d83b86d75",
      "flow": "",
      "email": "email1",
      "totalGB": 0,
      "expiryTime": 0,
      "enable": true,
      "tgId": "",
      "subId": ""
    }
  ]
}
```

**Comment by moradpoor** [comment]
سلام مهندس ممنون از توجهتون , بله به روشی که فرمودید انجام دادم منتها با وجود پاسخ

**Comment by alireza0** [comment]
چه چیزی رو تغییر دادین و چه تغییری رو انتظار دارین ؟
آیا هیچ تغییری توی دیتابیس انجام نشده ؟
آیا فیلد کلیدی مثل apssword تکراری ندارین ؟
آیا خطایی در لاگ داشتید ؟

**Comment by moradpoor** [comment]
اکانت از قبل در پنل وجود داشته و الان میخواستم حجم کلی و تاریخ انقضا رو تغییر بدم
قبل از اینکه کد رو اجرا کنم یکبار از طریق پنل وضعیت رو چک کردم و اکانت مشکلی نداشت 
خیر تکراری وجود نداره (به فرض تکراری بودن آیا نباید روی هر دو اعمال کنه ؟ ) 
خیر خطایی ندارم و پروسه کامل پیش میره و پاسخ ریکوئست به سرور با نتیجه موفق برمیگرده

**Comment by alireza0** [comment]
در صورت تکراری بودن باید باا خطا مواجه بشه. از طرف دیگه روی هردو اعمال شدن منطقی نیست.
لطفا دیتابیس رو بررسی کنید.
متدی که استفاده میکنید با متدی که در پنل استفاده میشه فرقی نداره. پس اگر پنل درست انجام میده، یه جای کار شما مشکل داره.

**Comment by moradpoor** [comment]
بنده دقیقا دیتایی که توی مرورگر میگیرم (سافاری) رو کپی میکنم تو کد 
از اونجایی که موفق برمیگرده و هیچ خطایی نمیده بنده تصور کردم شاید این مشکل توی api باشه

**Comment by moradpoor** [comment]
مهندس سلام مجدد و  تشکر میکنم که صبورانه پاسخگو هستید 
بنده گاهی مستقیم در پنل هم ارور ۵۰۰ میگیرم برای حذف 
Error: Request failed with status code 500

**Comment by alireza0** [comment]
درود بر شما
لطفا هرباری که خطا میگیرید با اطلاعات کافی و اسکرینشات یک ایشو جدید باز کنید.
سپاسگزارم
