### ISSUE TITLE
دسترسی فقط به یک سایت

### ISSUE THREAD

**Issue by shyton** [alireza0/x-ui#558]
سلام وقت بخیر

کانفیگ پنل به چه صورت می تونم تنظیم کنم که مثلا فقط سایت youtube.com از طریق اتصال کاربر به سرویس باز بشه و هر سایت دیگه ای مسدود شود؟

**Comment by alireza0** [comment]
درود بر شما
میتونید با قوانین روتینگ، این سایت رو به خروجی بفرستید و بقیه درسترسی ها رو به سیاهچاله (blackhole).
برای اینکه DNS کار کنه باید DNS رو تعریف کنید و یا مجاز به استفاده بکنید. ( قانون دوم در مثال )
```json
{
  "type": "field",
  "domain": ["full:youtube.com"],
  "outboundTag": "direct"
},
{
  "type": "field",
  "port": "53",
  "network": "udp",
  "outboundTag": "direct"
},
{
  "type": "field",
  "ip": ["0.0.0.0/0"],
  "outboundTag": "blocked"
}
```

بخش outbound هم باید این دوتا رو داشته باشه
```json
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ]
```
