### ISSUE TITLE
Remove flow

### ISSUE THREAD

**Issue by yasin6723** [alireza0/x-ui#56]
سلام
میخواهم فیلد flow با مقدار xtls-rprx-direct را از کلاینت های قبلی پاک کنم، اما در گزینه های ویرایش نیست
(برای اپگرید به ورژن 1.8.0)

در تنظیمات کلاینت ها از هیچ tls استفاده نشده است، اما ورژن های قدیمی فیلد flow را خودشان پر کرده اند.

لطفا راهنمایی نمایید
تشکر
![Screenshot 2023-03-11 031230](https://user-images.githubusercontent.com/49768974/224445161-fb09aa58-3643-416c-b034-4ee4e099a49f.jpg)

**Comment by alireza0** [comment]
درود بر شما
متاسفانه این مشکل توی ورژن های قدیمی بود و hard-code شده بود.
تنها راه تصحیح این هست که به صورت موقت برای این سرویس ( inbound ) گزینه tls رو فعال کنید تا آپشن flow توی کاربرها ( clients ) به شما نمایش داده بشه.
بعد برای تک تک کاربر ها باید این گزینه رو به none ( هیچ ) تغییر بدید.
راه سریعتر ولی حرفه ای تر دستکاری دیتابیس هست.
