### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by kilyabin** [alireza0/x-ui#560]
I got an error ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
![image](https://github.com/alireza0/x-ui/assets/65072190/d53e83b3-3699-4532-ac27-c00b782f57c8)

**Comment by alireza0** [comment]
Thank you for your report.

Docker compse file is only a sample file. You have to chage it manually.
The reason it has error in you side is about your installed version of docker (v1) which is deprecated. The newer updates of docker may never complain about version as error!

BTW: You are right, v3.9 does not exist yet. At the moment 3.8 is the last one. Please use version "3" instead. I will change it as well.

To have more information about versions, check it [here](https://docs.docker.com/compose/compose-file/compose-versioning/#versioning).

**Comment by kilyabin** [comment]
my docker version is 20.10.5
i edited docker-compose.yml file from version 3.9 to 3 and it solved my problem!
Thank you
