### ISSUE TITLE
دسترسی به منوی ایکس یو آی در داکر

### ISSUE THREAD

**Issue by Wolf6470** [alireza0/x-ui#561]
درود مهندس عزیز و ممنون از تمامی زحماتی که میکشید. وقتی که پنل رو روی داکر نصب می کنیم چگونه در سرور می‌توانیم به منوی x-ui دسترسی پیدا کنیم که  bbr و بقیه کارا را انجام بدهیم؟ با چه دستوری؟

**Comment by alireza0** [comment]
درود بر شما
با اجرای داکر شما نیازی به این فایل ندارید و این منو وجود نداره.
دلیلی برای اجرای BBR توی داکر نیست. اگر بخواهید، میتونید توی هاستش اجرا کنید.
اگر واقعا کار با پنل برای شما سخت تر از وارد شدن به داکر باشه و یا بخواید دستورات متنی خود نرم افزار رو انجام بدید، به داکر متصل بشید و فایل اجرایی رو میتونید توی این آدرس پیدا کنید:
```bash
/app/x-ui
```

پی نوشت: استفاده از داکر مفاهیم خودش رو داره. اگر دسترسی به سرور دارید، اجرای پنل با داکر برای پروداکشن کار درستی نیست.

**Comment by Wolf6470** [comment]
ممنون از پاسخگوییتون.پنل که صد در صد راحت‌تر هستش ولی خوب با داکر میتونم سرویس هایی مثل کزم رو میتونید ران کنم.

**Comment by alireza0** [comment]
بهتره روی سرور مینیمال هیچ چیزی به جز x-ui نداشته باشید. سرویس های دیگه توی سرویس پراکسی اختلال ایجاد میکنند.
میتونید سرویس های دیگه رو با داکر بیارید بالا و x-ui رو نرمال نصب کنید.

برای بروزرسانی باید container رو بروز کنید: [اینجا را ببینید](https://docs.docker.com/engine/reference/commandline/container_update/)

**Comment by Wolf6470** [comment]
ممنون از تمامی زحماتی که میکشید.و راهنمایی های خوبتون.
