### ISSUE TITLE
قطع شدن یوزر های قدیمی 

### ISSUE THREAD

**Issue by mobingasemi** [alireza0/x-ui#566]
با سلام و درود
یوزر های قدیمی پنلم در روز های مختلف از ۱۰ تا مثلا ۶ تاشون خود به خود قطع میشن و متصل نمیشن در صورتی که در داخل پنل هم حجم و تایم مصرفشون هنوز اتمام نشده مشکل از چی میتونه باشه و چجوری رفع کنم ؟

**Comment by alireza0** [comment]
درود بر شما
فرآیندی برای قطع شدن خودبخود توی پنل وجود نداره.
لطفا اول مطمئن بشید که ارتباط کاربر با پنل به دلیل فیلترینگ یا مشکلات هاستینگ قطع نشده.
برای حل مشکل به اطلاعات بیشتری نیاز دارم
