### ISSUE TITLE
Problem after update xray

### ISSUE THREAD

**Issue by Nipoto** [alireza0/x-ui#57]
hi Alireza,
Thank you for releasing the new version
Unfortunately, it is not possible to update to the new X-ray version

![Untitled](https://user-images.githubusercontent.com/3000646/224467376-082568d9-b5ac-488e-953a-952cb1c3bc96.png)

**Comment by misagh72** [comment]
back to 1.7.5 
in 1.8.0, xtls change to Reality so u can make vless xtls

**Comment by Nipoto** [comment]
> back to 1.7.5 in 1.8.0, xtls change to Reality so u can make vless xtls

I edited the database manually and the problem was solved 😕

**Comment by Nipoto** [comment]
after successful update, now I have problem to create VLESS/XTLS account

![image](https://user-images.githubusercontent.com/3000646/224491437-fe269bc9-7044-4e42-abbf-dc598a2ee280.png)

**Comment by alireza0** [comment]
@Nipoto On this time, we have no idea about implementing Reality. It is still in `Prerelease` mode and no complete documentation provided.
If you are using XTLS, don't upgrade it to 1.8.0 which dosn't support XTLS anymore.
Please be patient till we have everything mature and well documented.

**Comment by alireza0** [comment]
@Nipoto 
I have no plan to expand this old panel. Instead, might be a new panel with new features could be such a better solution

**Comment by xxSaeidxx** [comment]
> @Nipoto I have no plan to expand this old panel. Instead, might be a new panel with new features could be such a better solution

سلام @alireza0  

آیا برای Reality دارید یک پنل جداگانه طراحی می کنید؟ و اینکه کی آماده میشه؟ آیا امکان نصب دو تا x-ui در کنار هم وجود داره؟
ممنون میشم پاسخ بدید.

**Comment by alireza0** [comment]
@xxSaeidxx 
درود بر شما
لطفا برای سوالاتتون یک issue مخصوص جدید ایجاد کنید. امکان دیده شدن این سوالات خیلی کمه.

۱. ایده برای طراحی پنل وجود داره ولی وقت زیادی میگیره. ممکنه به همین پنل هم اضافه بشه
۲. دلیلی برای نصب دوپنل همزمان نیست، شما میتونید با تنظیمات xray مدل های مختلف کاربردی درست کنید.
اگر حتما میخواید کاملا جدا باشن، میتونید از پیاده سازی با داکر استفاده کنید. ( قبلش حتما اطلاعات کافی در مورد داکر و شبکه داخلی اش داشته باشید )

**Comment by xxSaeidxx** [comment]
> @xxSaeidxx درود بر شما لطفا برای سوالاتتون یک issue مخصوص جدید ایجاد کنید. امکان دیده شدن این سوالات خیلی کمه.
> 
> ۱. ایده برای طراحی پنل وجود داره ولی وقت زیادی میگیره. ممکنه به همین پنل هم اضافه بشه ۲. دلیلی برای نصب دوپنل همزمان نیست، شما میتونید با تنظیمات xray مدل های مختلف کاربردی درست کنید. اگر حتما میخواید کاملا جدا باشن، میتونید از پیاده سازی با داکر استفاده کنید. ( قبلش حتما اطلاعات کافی در مورد داکر و شبکه داخلی اش داشته باشید )

طبق اطلاعاتی که گفتن با بعضی از قابلیت های قبلی پنل باید خداحافظی کرد وقتی که Reality اضافه بشه. گفتم شاید شما برای Reality پروژه ایجاد پنل جدید در نظر گرفتید. نمی تونید بگید چی زمانی اضافه میشه به پنل تون ؟
تشکر از زحماتتون.

**Comment by alireza0** [comment]
بله درسته، این یکی از مهمترین دلایل عدم آپدیت پنل های مشابه میتونه باشه.
زمان مشخصی نداره متاسفانه.
