### ISSUE TITLE
اتصال سرور ایران به تلگرام

### ISSUE THREAD

**Issue by gechindir** [alireza0/x-ui#571]
سلام و خسته نباشید

بنده تنظیمات مربوط دکومودور رو طبق گفته شما انجام دادم 
کار نمیکنه اتصال ب تلگرام
داخل سرور ایران انجام شده
[طبق اینجا](https://github.com/alireza0/x-ui/issues/252#issuecomment-1533339290)

میشه راهنمایی بفرمایید
![IMG_20230930_015846_388](https://github.com/alireza0/x-ui/assets/146492191/a29dfb87-0121-4695-a543-e6540311d3de)
![IMG_20230930_015728_793](https://github.com/alireza0/x-ui/assets/146492191/1a175911-7d44-4e23-81aa-0e47ea1649f7)
![IMG_20230930_015722_588](https://github.com/alireza0/x-ui/assets/146492191/419686e7-64e9-405b-b2dc-e004dd360249)

@alireza0 استاد ممنون میشم یه پاسخی بدین

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم
پورت رو توی این مدل حتما باید ۴۴۳ بذارید
