### ISSUE TITLE
مشکل تو قالب بندی

### ISSUE THREAD

**Issue by SahandSOne** [alireza0/x-ui#574]
با سلام و خسته نباشید
این مشکل تو قالب xui برام پیش اومده, حجم و more information برام قابل نمایش نیست. چطور میتونم فیکی کنم ؟

البته فکر کنم از ربات هم میتونه باشه که ساب اسکریپشن رو تغییر میده

![sss](https://github.com/alireza0/x-ui/assets/134105392/617abbdc-3b0e-4c53-afdc-21d8f3951614)

**Comment by alireza0** [comment]
درود بر شما
این مشکل به طور قطع به دلیل عدم ارائه دیتا به شکل صحیح بوجود اومده.
لطفا ربات رو تصحیح کنید.
برای اینکه بدونین چه مشکلی بوجود اومده، کنسول مرورگر رو چک کنید
