### ISSUE TITLE
Repo deployment on Gitlab

### ISSUE THREAD

**Issue by armin567ip** [alireza0/x-ui#575]
Dear Mr. Alireza, Your project is truly impressive, and I have a suggestion that could make it even more accessible.

This expansion would be particularly beneficial for individuals looking to utilize cost-effective IPv6-Only servers for deploying the VPN.

The reason behind this request is that IPv6-Only servers face restrictions when trying to access resources hosted on GitHub due to its IPv4-only nature.

By offering the repository on GitLab as well, you would make it more accessible and user-friendly for a broader audience.

Thank you for considering this proposal, I look forward to your response.

**Comment by alireza0** [comment]
Dear @armin567ip 
Thank you for your kind consideration.
I will keep it and think about it to find the best solution.

**Comment by EarlVadim** [comment]
@armin567ip 
add to    /etc/hosts

2a01:4f8:c010:d56::2 github.com
2a01:4f8:c010:d56::3 api.github.com
2a01:4f8:c010:d56::4 codeload.github.com
2a01:4f8:c010:d56::5 objects.githubusercontent.com
2a01:4f8:c010:d56::6 ghcr.io
2a01:4f8:c010:d56::7 pkg.github.com npm.pkg.github.com maven.pkg.github.com nuget.pkg.github.com rubygems.pkg.github.com

**Comment by EarlVadim** [comment]
@armin567ip 
it means you did something wrong. because this is exactly what I use successfully for this project.

**Comment by EarlVadim** [comment]
@armin567ip 
just add strings to file and save
