### ISSUE TITLE
ریست ترافیک

### ISSUE THREAD

**Issue by 33mamad** [alireza0/x-ui#577]
سلام مهندس
وقتی میخوام کلاینت هارو ریست ترافیک کنم ارور 404 میده راه حل چیست؟

**Comment by alireza0** [comment]
درود بر شما
لطفا اطلاعات رو کامل ارائه بدین.
نسخه، خطای مرورگر، خطاهای لاگ ( در صورت وجود ) و نوع تنظیمی که استفاده میکنین.

**Comment by 33mamad** [comment]
نسخه 1.8.4
Error: Request failed with status code 500

**Comment by 33mamad** [comment]
نوع vmess+ws+tls

**Comment by alireza0** [comment]
خطای ۵۰۰ باید حتما لاگ داشته باشه.
خطای مرورگر هم توی کنسول مرورگر باید دیده بشه
