### ISSUE TITLE
message size

### ISSUE THREAD

**Issue by davover** [alireza0/x-ui#578]
سلام در تنظیمات کانفیگ و یا هسته xray مقداری برای WebSocket message size تعیین شده ایا؟

در کد های xray یه مقدار اشاده با عنوان buffer size که روی  1024 تنظیم شده این همون مقداره؟ ایا امکان تغییر این مقدار مستقیما از سورس پنل قبل نصب روی سرور هست یا خیر

سپاس

**Comment by alireza0** [comment]
درود بر شما
پنل فقط تنظیمات رو برای xray تامین میکنه و در تنظیمات xray تا امروز هیچ تنظیمی برای مورد مد نظر شما وجود نداشته.
برای این کار باید کد های xray-core رو تغییر بدید
