### ISSUE TITLE
Using `install.sh` script gives `bash: /dev/fd/63: No such file or directory` error

### ISSUE THREAD

**Issue by Kenya-West** [alireza0/x-ui#584]
**Describe the bug**
When I run `bash <(curl -Ls https://raw.githubusercontent.com/alireza0/x-ui/master/install.sh)` with `sudo` permissions, it gives me `bash: /dev/fd/63: No such file or directory` error. I use Ubuntu on VPS:

```log
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

with 2 GB free space, according to info provided by `duf`.

**To Reproduce**
1. `bash <(curl -Ls https://raw.githubusercontent.com/alireza0/x-ui/master/install.sh)`

**Expected behavior**
It should be installed successfully

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by alireza0** [comment]
Please use fresh miniamal OS to avoid conflicts.
It is also recommended to login by `root` user instead of using `sudo` command.
If you are not sure what is the root-cause of the error, please contanct a system admin.

**Comment by kirillclone** [comment]
How to remove x-ui?
