### ISSUE TITLE
No Telegram field when adding user to inbound

### ISSUE THREAD

**Issue by Kenya-West** [alireza0/x-ui#585]
**Describe the bug**
In `1.5.4`, there is Telegram field when I add user. In `1.5.5`, there is no. Why?

**To Reproduce**
1. Go to "Add Inbound" button, click
2. Try to add user

**Expected behavior**
There should be `Telegram` string field to add TG username.

**Comment by alireza0** [comment]
If you disabled the telegram bot configuration in Settings, then there should be no tg_id input in user modal.

**Comment by Kenya-West** [comment]
You are right. I thought I enabled the bot (added bot token and other configuration parameters) but I have forgotten to toggle "Enable Telegram bot" switch. The issue is now solved and should be closed. Thanks fpr help!
