### ISSUE TITLE
چگونه میتوانم کانفیگ های محدود به یک کاربر یا دو کاربر را بسازم؟

### ISSUE THREAD

**Issue by Corium0** [alireza0/x-ui#588]
سلام خسته نباشید وقتتون بخیر و نیکی،قبلش یه تشکر و قدر دانی بکنم بابت این سرویسی که بطور رایگان خدمتمون ارائه دادین
و بعد یه سوال داشتم
چطوری میتونم کانفیگ هامو یک کاربره کنم؟ یا دو کاربره؟ مثلا بیشتر از یه دستگاه روش نتونه وصل بشه رو دستگاه دومی کار نکنه
یا مثلا فقط رو دوتا دستگاه کار کنه یا فقط  رو سه تا دستگاه کار کنه خلاصه اینکه منظورم اینه دو کاربره سه کاربره یا تک کاربره شو چطوری باید انجام بدم؟

**Comment by wulfric93** [comment]
تانلی ؟
نحوه تانلت چیه ؟

**Comment by Corium0** [comment]
نه کلا از هیچ تانلی استفاده نمیکنم،رو یه سرور آلمان یه پنل ساختم و تموم

**Comment by wulfric93** [comment]
ببینید بحث آیپی هست اینجا 
یعنی اگر کسی از شما اکانت بگیره و مثلا با یک وای فای چند دستگاه وصل بشن به سرویس شما همه خواهند تونست که وصل بشن چون عملا یک آی پی هست 
شما توی ترمینال باید فعال کنید محدودیت آی پی رو 
توی پنل علیرضا رو نمیدونم ولی توی پنل ثنایی باید از ترمینال فعال بشه 
<img width="192" alt="image" src="https://github.com/alireza0/x-ui/assets/117269334/68e02276-18eb-4baf-b228-a640610b5b88">
توی گزینه 17 هست

**Comment by alireza0** [comment]
درود بر شما
در این پنل امکان محدود کردن کاربر ها در حال حاضر وجود نداره.
میتونید از پنل ثنایی استفاده کنید که یک مدل شبیه سازی با نرم افزار های جانبی انجام میده.
