### ISSUE TITLE
نصب وارپ

### ISSUE THREAD

**Issue by xlirezx** [alireza0/x-ui#592]
درود
روی پنل سنایی، امکان مصب وارپ هست. روی این پنل چطوری باید وارپ کلادفلر رو نصب کنم؟

**Comment by alireza0** [comment]
درود بر شما
کلا نصب و اجرای وارپ خارج از حوصله این پنل هست.
اگر میخواهید انجام بدید در موردش تحقیق کنید تا به مشکل نخورید.
