### ISSUE TITLE
ارور هنگام بیلد در داکر

### ISSUE THREAD

**Issue by babakazizigithub** [alireza0/x-ui#594]
جناب علیرضا عزیز
این ارور موقع بیلد روی داکر پیش میاد 
چه جوری میشه رفعش کرد؟ 

docker build -t x-ui .
[+] Building 1.6s (2/2) FINISHED                                                                                             docker:default
 => [internal] load build definition from Dockerfile                                                                                   0.3s
 => => transferring dockerfile: 2B                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                      0.5s
 => => transferring context: 2B                                                                                                        0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount771317329/Dockerfile: no such file or directory

ممنونم

**Comment by alireza0** [comment]
درود بر شما
این خطا مربوط به سیستم شماست.
برای آشنایی بیشتر با دستورات ساخت داکر [اینجا](https://docs.docker.com/engine/reference/commandline/build/) رو ببینید
