### ISSUE TITLE
ادرس فایلی که ای پی ای ایکس ری دسترسی داره و همگام سازی

### ISSUE THREAD

**Issue by jamiekarvans** [alireza0/x-ui#597]
با سلام
با توجه که دستورات ساخت کاربر و مصرف از طریق api xray وارد میشه فایلی که بهش دسترسی داره کجاست و چرا برای همگام سازی چند سرور قابلیت 

بر این فرض که اگر فایلی بهش دسترسی داره current state باشه یا همون فایل توی /etc/x-ui در نظر بگیریم:
از شروع استارت xray یا پنل یک کپی از فایل current state گرفته بشه و در تمام سرور ها این فایل در مکان مشخص برای مثال در /etc/x-ui/state با نام last state ذخیره بشه در این صورت فایل این فایل در تمام سرور ها یکی هست و ثابت  و هر 5 دقیقه یا حالا هر مدتی یکبار تغییرات فایل current state با last state برای هر سرور مقایسه بشه و تغییرات با هم جمع بشن حالا اگه حجمی کم شده یا... و بر روی فایل last state اعمال شن( کل این کار که بشه تغییرات رو به صورت درست حساب کرد) و فایل last state جدید در تمام سرور ها برای last state و current state اپلود شه

حالا با توجه که دستورات رو با api xray وارد میکنید که نیاز به ری استارت نباشه سوال بنده اینجاست چرا این تغییرات رو به همین صورت وارد نمیکنید؟ و در صورت اپدیت کردن مستقیم فایلی که api دسترسی داره پنل ری استارت میشه؟

**Comment by alireza0** [comment]
درود بر شما
من چند بار متن رو خوندم و متوجه منظورتون نشدم.
در کل، xray api به فایلی ارتباط نداره.
