### ISSUE TITLE
تغییر در نمایش مشخصات یوزر در سابسکریپشن

### ISSUE THREAD

**Issue by Morghak963** [alireza0/x-ui#598]
سلام 
مهندس یک پیشنهاد
بجای اینکه داخل سابسکریپشن حجم مصرفی و تایم رو داخل اسم کانفیگ بیارید
عین مرزبان یک کانفیگ جدا (که وصل نمیشه) نمایش داده بشه که توی اسمش فقط روزهای باقی مونده و حجم نشون بده

چون وقتی این پارامترها درکنار اسم خود کانفیگ میاد ،اسم کانفیگ طولاني میشه و داخل بعضی از آپ ها دیگه نشون نمیده درست مشخصات رو

ممنون میشم🌹

**Comment by alireza0** [comment]
درود بر شما
این مدل برای نرم افزار مرزبان قابل استفاده است.
در مدل اجرا شده در این پنل، هر کاربر مشخصات خودش رو داره و میشه چند کاربر رو توی یک سابسکرپیشن آورد.
به همین دلیل وقتی مشخصات مصرف رو به صورت کلی در یک تنظیم فیک بیاریم، قابلیت جداسازی مشخصات مصرف هر کاربر از پنل گرفته میشه.

**Comment by Morghak963** [comment]
ممنون بابت توضیحاتتون مهندس🌹

**Comment by ashkantoorani** [comment]
بی ک مشکلی که ساب شما داره ، اینه که در بخش name پایان لینک ساب ، میاد uuid رو میگذاری ، من خودم uuid رو به عنوان ساب میزارم می‌خوام ، نام کانفیگ بیاد انتها مثل پنل ثنایی ، ولی اینطور نیست
http://xxx.com:2096/subscribe/58hh0e9d-961d-43d3-b716-7691214ea3c3?name=vbcqsigxbvvu4xa9
باید اینطور باشه
http://xxx.com:2096/subscribe/58hh0e9d-961d-43d3-b716-7691214ea3c3?name=vpn

**Comment by alireza0** [comment]
اون انتها نام ساب میاد. اینجوری توی بعضی نرم افزار ها اسم گروه رو درست میکنه.
این روشی که شما میخواید باز هم با این حالت که چند تا کلاینت توی یک ساب باشند مشکل داره. اسم کدومشون را باید بذاریم ؟

**Comment by ashkantoorani** [comment]
قرار نیست چند تا کلاینت توی یک ساب باشه برای یونیک بودن ، برای هر کاربر ، به جای جنریت رندوم ساب، میام uuid کاربر رو تو فیلد ساب کپی میکنم. اینجا اتفاقی که میفته ، هر کاربر یدونه شناسه یونیک داره، حالا اگر من بخوام کانفیگ های مختلف تو سرورم به یک کاربر بدم، فقط لینک ساب رو یکی میزارم ( uuid ) کاربر رو میزارم ، حالا اینجا چرا مثل ثنایی عمل نکردی!؟ ثنایی email یا نام کاربر رو میزارم انتهای لینک ساب، من بر اساس ثنایی ، یک صفحه ساب اختصاصی ایجاد کردم ، از موقعی که اومدم رو پنل شما یعنی علیرضا ، چون ، مثل ثنایی نیست ، لینک های اسکریپت ساب من فیل میشه، ولی شما میای رندوم جنریت ساب رو به جای نام کاربر میزاری، خواستی میتونم اسکریپت رو براتون بفرستم، مشاهده کنید

**Comment by alireza0** [comment]
اینکه شما چطور میخواهید استفاده کنید با اینکه چطوری ساخته شده کمی متفاوته.
این ویژگی پنل از اول به شکلی که عرض کردم ساخته شده و قرار بوده چند تا کانفیگ ( با ایمیل های متفاوت ) بتونند در یک سابسکریپشن استفاده بشن.
جناب ثنایی اگر عوضش کردن احتمالا به دلایل خودشون بوده.
تغییر به سبکی که شما میخواید برای بقیه کاربر ها دردسر ایجاد میکنه.

به هر حال، لینک ایجاد شده در بخش اطلاعات کاربرها، کاملا به صورت مثاله و شما میتونید اون بخش انتهایی رو خودتون عوض کنید.
اگر از اسکرپیت استفاده میکنید که کار خیلی راحتی دارید.
