### ISSUE TITLE
مرتبط کردن سرور ایران با چند سرور

### ISSUE THREAD

**Issue by Mrlehmet** [alireza0/x-ui#599]
سلام ، میخاستم ببینم امکانش هست که بشه تعیین کرد که مثلا یک اینباند خاص به یک اینباند خاص سرور  خارج متصل بشه؟

و همینجوری اینباند بعدی به یک اینباند از  سرور دیگه

در روش تونل به شکل پنل به پنل

**Comment by alireza0** [comment]
درود بر شما
بله. با استفاده از قوانین مسیریابی (routing rules) این کار قابل انجامه

**Comment by Mrlehmet** [comment]
سلام و عرض ادب متشکرم از لطفتون بزرگوار، آیا مثال یا آموزشی دارید که طبق اون پیش برم؟

و یک سوال دیگر از لحاظ امنیت و کیفیت ،اگر شما باشید اینکه من تک پورت ریورس یا فیک تونل بزنید به چند سرور خارج ، یا اینکه اینباند بسازید و هرکدومو به یک سرور اختصاص بدهید 

کدوم رو انتخاب میکنید؟

**Comment by Mrlehmet** [comment]
> درود بر شما بله. با استفاده از قوانین مسیریابی (routing rules) این کار قابل انجامه

سلام و عرض ادب متشکرم از لطفتون بزرگوار، آیا مثال یا آموزشی دارید که طبق اون پیش برم؟

و یک سوال دیگر از لحاظ امنیت و کیفیت ،اگر شما باشید اینکه من تک پورت ریورس یا فیک تونل بزنید به چند سرور خارج ، یا اینکه اینباند بسازید و هرکدومو به یک سرور اختصاص بدهید

کدوم رو انتخاب میکنید؟

**Comment by Mrlehmet** [comment]
> درود بر شما بله. با استفاده از قوانین مسیریابی (routing rules) این کار قابل انجامه

سلام جنای مهندس ، دیشب بررسی کردم منوال رو به این نتیجه رسیدم ، در ادامه کدو میزارم لطفا یه نگاه بندازید ببینید درست انجام دادم یا خیر

------------------------------------------------ configuration  outbounds 

//Server1
{
  "outbounds": [
    {
      "sendThrough": "0.0.0.0", اگر چندتا آیپی آیپی که میخام خارج شه//    
      "protocol": "vless",
      "settings": {          "address": "سرور خارج",
            "port": 2087,
            "users": [
              {
                "id": "14eb1479-0ef9-4db5-970d-c6a708148605",
                "alterId": 0,
                "email": "[t@t.tt](mailto:t@t.tt)",
                "security": "auto",
                "encryption": "none",
                "flow": ""
              }
            ]
          }
        ]
},

      "tag": "Server_1",    //نام اوتباند سرور ایران 

      "streamSettings": {  اطلاعات دیگه اینباند سرور خارج // 
  "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": " سرور خارج ", 
          "alpn": [
            "h2",
            "http/1.1",
            "h3"
          ],
          "fingerprint": "firefox",
          "show": false
},

"tcpSettings": {
         "tag": " Server_1tag" تگ شناسایی اوتباند سرور ایران //
           "header": {
            "type": "http",
            "request": {
              "version": "1.1",
              "method": "GET",
              "path": [
                "/"
              ],
              "headers": {
                "Host": [
                  "telewebion.com"
                ],
                "User-Agent": [
                  ""
                ],
                "Accept-Encoding": [
                  "gzip, deflate"
                ],
                "Connection": [
                  "keep-alive"
                ],
                "Pragma": "no-cache"
              }
            }
          }
        }
  },

      "mux": {   ترکیب کانکشن به تعداد 1/8، قبل از خروجی زد از سرور ایران // 

  "enabled": false,
  "concurrency": 8
}
    }
  ]
}



//Server2
همون مشخصات قبلی رو تکرار میکنم با اطلاعات اینباند سرور دوم خارج



------------------------------------------------ configuration  routing rules
//inbound X – to Server 1

{
  "routing": {
    "domainStrategy": "AsIs",
    "domainMatcher": "hybrid",
    "rules": [
        {
  "domainMatcher": "hybrid", 
  "type": "field",
  "port": "2053", //پورت اینباند داخل سرور ایران
  "sourcePort": "2053",
  "network": "tcp",
  "inboundTag": ["tag-vmess"], // اسم اینباند داخل سرور ایرانم  (نمیدونم اسم یا آیدیه این)
"outboundTag": " Server_1tag", تگی که بالا در بخش اوتباند زده بودم //  
  "balancerTag": "balancer"
}
        ],
 اگرم چند تا آیپی دارم از لیستن تو داخل اینباند ستش میکنم که فقط از اون آیپی به یک سرور خاص متصل بشه

{
  "tag": "balancer",
  "selector": []
}


//inbound  y – to Server 2
همینارو براش تکرار میکنم فقط اطلاعات اینباند و تگ اوتیاند تغییر میکنه

**Comment by alireza0** [comment]
خیلی پیچیش دادین!
نیازی به تعریف اینباند در تنظیمات نیست. اینباند های تعریف شده در صفحه ورودی ها (inbounds) با تگ مشخصی تنظیم میشن که ترکیب "inbounds-" و پورت همون اینباند هست. شما میتونید تنظیم اعمال شده توسط پنل رو توی صفحه اصلی و با چک کردن config.json ببینید.

برای تعریف قانون مسیر یابی کافیه به این شکل اضافه کنید:
فرض کنید یک اینباند با پورت ۵۱۵۱۵ داریم و میخوایم به یه خروجی با تگ "out" متصل بشه:

```json
      {
        "inboundTag": [
          "inbound-51515"
        ],
        "outboundTag": "out",
        "type": "field"
      },
```

در ضمن به اولویت قوانین از بالا به پایین دقت کنید

**Comment by Mrlehmet** [comment]
سلام ، متشکرم بله فردای اونروز به اقن نتیجه رسیدم ک تمام شرایط لازم نیست صدف کند ، یه شرط اصلی ک نام اینباند هست کافی هست

۲ تا سوال داشتم
اول این mux رو اگر فعال کنم احتمال پیدا کردن سرور ایران کمتر میشه؟؟ 
تو مانیتورینگ تاثیری داره؟ و اینکه باعث کاهش سرعت میشه ؟


سوال دوم این هست که برای send through  اگر ایپی listen یچیز باشه و در اوتباند send through رو بزارم رو یه ایپی دیگر سرورم تاثیری روی پیدا کردن سرور ایران و همچنین پیدا کردن ایپی داره؟

**Comment by alireza0** [comment]
پرسش های شما در شرایط مختلف جواب های متفاوتی دارن.
گزینه mux برای تانل بین سرورها، کاربرد زیادی نداره.
به کاربردن آدرس دوم برای خروجی هم زیاد ربطی به فیلتر شدن و یا نشدن نداره.

بهتره شرایطتون رو دقیق تر بررسی کنید.
