### ISSUE TITLE
قابلیت های ورژن جدیدچیه

### ISSUE THREAD

**Issue by ramtiny** [alireza0/x-ui#602]
سلام‌وقت بخیر
میشه ورژن جدید قابلیت هاشو به فارسی هم بنویسید؟
تشکر
فقط اینکه شابسکرایب حجم تلفیقی هم برنامه نویسا نمیتونن رو پنل تون انجام بدن ؟

**Comment by Morghak963** [comment]
داداش نوشته دیگه توقع داری چی بنویسه

**Comment by alireza0** [comment]
درود بر شما
وقت شما هم به شادی

- طراحی صفحه ها از پایه بهینه سازی و ریفکتور شده. رسپونزیو اضافه شده که میتونین روی گوشی هم بهتر پنل رو باز کنید.
- نمایش کاربران آنلاین ( کاربرانی که ترافیک دارند )
- ویژگی ریست خودکار ترافیک در مدت زمان مشخص (Auto renew)
- ویژگی صفحه بندی جدول ورودی ها و کاربران

**Comment by alireza0** [comment]
@ghojaei1995 

مشکلی نداره. لطفا بررسی کنید کجا رو درست تنظیم نکردین

**Comment by alireza0** [comment]
@ghojaei1995 

در نسخه جدید قابلیت استفاده از chatid اضافه شده.
لطفا منتظر بمانید
