### ISSUE TITLE
محدود کردن دستگاه های قابل اتصال

### ISSUE THREAD

**Issue by thejianyu** [alireza0/x-ui#603]
درود و خسته نباشید خدمت دولوپر عزیز این پنل
لطفا یه قابلیت به پنل اضافه کنید که برای هر کاربر، حداکثر تعداد دستگاه های متصل همزمان رو بشه محدود کنیم

**Comment by misagh72** [comment]
پنل سنایی رو استفاده کنید

**Comment by thejianyu** [comment]
پنل سنایی آیپی لیمیت داره، من درخواستم لیمیت دیوایس هاست، مثلا ممکنه کانکشن از طریق یک اینترنت و یک آیپی انجام بشه اما تعداد دیوایس ها محدود بشه

**Comment by misagh72** [comment]
امکانش نیست لیمیت دیوایس

**Comment by thejianyu** [comment]
فکر کنم بشه تعداد کانکشن های فعال برای هر کلاینت رو محدود کرد

**Comment by X-Oracle** [comment]
> فکر کنم بشه تعداد کانکشن های فعال برای هر کلاینت رو محدود کرد

نمیتوانید . زیرا هسته Xray استاندارد توانایی استفاده از این قابلیت را ندارد.

**Comment by thejianyu** [comment]
پنل زیر که داره توی چین فعالیت میکنه (از کلش استفاده میکنن) چنین قابلیتی داره:
https://bit.ly/3QW2gcc

**Comment by AliBelali** [comment]
همونطور که @X-Oracle فرمودند متاسفانه هسته استاندارد x-ray این قابلیت رو نداره و فک کنم تنها راه جایگزین، کاستومایز کردن هسته xray هست که از device ID به جای آی پی استفاده بشه که نه تنها توسعه ی پنل رو سخت میکنه نیاز داره نرم افزار کلاینت هم از device id پشتیبانی کنه که در نتیجه برای اینکه قابل دورزدن نباشه باید کاربر رو محدود کرد که نتونه با هر نرم افزاری کانکت بشه و فقط با نرم افزارهایی که از device id پشتیبانی میکنن بتونن متصل بشن که این خودش خیلی سخت میشه شاید نیاز بشه یه نسخه کلاینت جدید برای پنل جدید فورک بشه از طرف دیگه اشتراک گذاری device id یه مقدار باعث نگرانی حریم خصوصی کاربرا میشه
خلاصش اینکه زحمت زیادی داره
نمیگم محاله اما اگه فعلا انجام نشد بدونید که این قابلیت زحمت زیادی برای توسعه دهنده داره
