### ISSUE TITLE
Panel Style Confusion

### ISSUE THREAD

**Issue by bingdong700** [alireza0/x-ui#604]
![QQ截图20231110220350](https://github.com/alireza0/x-ui/assets/231647/03e86e7a-0500-4d98-91d4-8ce23ce6af7d)

**Comment by alireza0** [comment]
Thank you for this report. I will fix it soon

**Comment by bingdong700** [comment]
Login page drop-down box cannot select Chinese

**Comment by alireza0** [comment]
It is fixed now.
Login page is also fixed in [another commit ](https://github.com/alireza0/x-ui/commit/2ca3a05cca1a397aa8a11415631c3a6e7400b594)
