### ISSUE TITLE
Xray Settings/ InboundsPage Improvments

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#605]
Hi.
First of all, A big thanks for recent update. (specially the new look)

## Xray Settings:
most of my time is spent on Xray config page and the config page is long. 

- can you make 2 button in the bottom-right corner of the page to perform `restart panel` and `save` as it makes it a lot easier to make changes on the go. (to make it fancy you can make it paper when the page is not at the top)
- the config page is a pure Textaria which is not suited for Json indentation and highlighting. is there something to use which could provide these in it? (right now, I'm using VScode to change configs then copy/paste into settings page)

## Inbounds:
- a button which scrolls the top of the page. (this can be implanted in Inbounds page where there are too many clients)

if you had spare time, consider these. Thanks.

**Comment by alireza0** [comment]
Hi @X-Oracle 
Frontend framework supports`back to top` as well. I have to find a place to add it.

I have been thinking to JSON editor for monthes! There is no colclution yet :(
The first step was to have separate xray config page. It is just a start ;)

**Comment by alireza0** [comment]
Done.
Will be available in next version
