### ISSUE TITLE
اضافه کردن زمان آخرین زمان اتصال 

### ISSUE THREAD

**Issue by BehnamAB** [alireza0/x-ui#606]
سلام خسته نباشید ممنونم از زخمات شما 
میخواستم اگه میشه الان که گزینه انلاین . افلاین اضافه شده اگه میشه زمان خرین زمان اتصال هم اضافه بشه مثلا یوزر 10 دقیقه پیش وصل بوده 

ممنونم

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم

کانکشن های پراکسی، به صورت ذاتی این ویژگی رو نداره و در این پنل با چک کردن ترافیک ها تشخیص داده میشه.
در پنل x-ui به صورت کلی این ویژگی در نظر گرفته نشده و دیتابیس هم ظرفیت این کار رو نداره.
در مجموعه رها، این موضوع به صورت پیش فرض در نظر گرفته شده.
