### ISSUE TITLE
زمان شمسی در بات بجای میلادی

### ISSUE THREAD

**Issue by mehdi7arfand10** [alireza0/x-ui#608]
سلام
واقعا توی آپدیت جدید عالی شده همه چیز..
چند ماهه که از پنل شما استفاده میکنم و واقعا هیچ ایرادی ندیدم توش..
مرسی از آپدیت های خوبتون..
اگه میشه تاریخ میلادی که توی بات تلگرام نشون میده رو به شمسی تبدیل کنین،خیلی عالی میشه.. ۹۰ درصد کاربرایی که به بات مراجعه میکنن برای استعلام از تاریخ میلادی سر در نمیارن..

**Comment by m38d1** [comment]
با سلام لطفاْ یکی این رو پیگیری کنه

**Comment by ramtiny** [comment]
شمسی یشه که عالیه
