### ISSUE TITLE
name problem in bulk account creation 

### ISSUE THREAD

**Issue by arsoltani72** [alireza0/x-ui#61]
hi here , hope you doing well 

is there any way to remove ramdom name given in bulk creastion section ? 
![Uploading Screenshot 2023-03-13 134446.png…]()

**Comment by arsoltani72** [comment]
i mean nonsence prefix before user no.

**Comment by arsoltani72** [comment]
به فارسی : 
زمانی که به صورت انبوه درخواست ساخت اکانت داده میشود، یک سری حروف رندوم در نام کانفیگ استفاده میشود 
آیا امکان دارد که این حروف ساخته نشود ؟

**Comment by alireza0** [comment]
درود بر شما
سپاس از حمایتتون
در این مورد در [اینجا](https://github.com/alireza0/x-ui/issues/40) صحبت شد و برای اینکه از تکراری بودن ایمیل ها در هر صورت جلوگیری بشه این تصمیم گرفته شد.

**Comment by arsoltani72** [comment]
نحوه فعال سازی بات تلگرام برای صاحب اکانت و بررسی مشتری چطور هست ؟

**Comment by alireza0** [comment]
> ممنون میشم راهنمایی کنید به صورت دستی غیرفالش کنم ؟ آیا اصلا امکان پذیره ؟
متاسفانه انبوه سازی مشکلات زیادی داره که از هدف اصلی این پنل ( ساده سازی ) دور میشه. برای ساخت حرفه ای بهترین کار استفاده از API میتونه باشه.


> نحوه فعال سازی بات تلگرام برای صاحب اکانت و بررسی مشتری چطور هست ؟
نحوه ساخت در README.md در [اینجا](https://github.com/alireza0/x-ui#tg-robot-use) اشاره شده. شما میتوید کلیات ساخت ربات رو از[ این بلاگ](https://coderfan.net/how-to-use-telegram-bot-to-alarm-you-when-someone-login-into-your-vps.html) ببینید.
برای اینکه هر کاربر بتونه آمار مربوط به خودش رو از طریق این بات ببینه، باید در انتهای email نام کاربری تلگرام شخص رو بعد از @ وارد کنید.[ اینجا اعلام شده](https://github.com/alireza0/x-ui#telegram-bot-features)

لطفا توجه داشته باشید که telegramID و telegram username متفاوت هستند. اولی رو برای ادمین باید بگذارید و از طریق ربات @getidsbot قابل دریافته، ولی برای راحتی کاربرها، telegram username که خودشون تعریف کردند رو باید استفاده کنید

**Comment by arsoltani72** [comment]
> > ممنون میشم راهنمایی کنید به صورت دستی غیرفالش کنم ؟ آیا اصلا امکان پذیره ؟
> 
> متاسفانه انبوه سازی مشکلات زیادی داره که از هدف اصلی این پنل ( ساده سازی ) دور میشه. برای ساخت حرفه ای بهترین کار استفاده از API میتونه باشه.
> 
> > نحوه فعال سازی بات تلگرام برای صاحب اکانت و بررسی مشتری چطور هست ؟
> 
> نحوه ساخت در README.md در [اینجا](https://github.com/alireza0/x-ui#tg-robot-use) اشاره شده. شما میتوید کلیات ساخت ربات رو از[ این بلاگ](https://coderfan.net/how-to-use-telegram-bot-to-alarm-you-when-someone-login-into-your-vps.html) ببینید. برای اینکه هر کاربر بتونه آمار مربوط به خودش رو از طریق این بات ببینه، باید در انتهای email نام کاربری تلگرام شخص رو بعد از @ وارد کنید.[ اینجا اعلام شده](https://github.com/alireza0/x-ui#telegram-bot-features)
> 
> لطفا توجه داشته باشید که telegramID و telegram username متفاوت هستند. اولی رو برای ادمین باید بگذارید و از طریق ربات @getidsbot قابل دریافته، ولی برای راحتی کاربرها، telegram username که خودشون تعریف کردند رو باید استفاده کنید

متوجه شدم 
آیا امکانش هست کمک کنید تا قسمت رندوم رو حذف کنم که اون حروف رندوم رو نسازه ؟
و
راهی نیست که مشتری با دادن نام اکانت خودش مقدار مصرف و باقی مانده رو بتونه ببینه توی یک ربات تلگرامی ؟

**Comment by alireza0** [comment]
برای جلوگیری از مشکلات احتمالی، تنها راه، ویرایش تک تک کاربر ها میتونه باشه که اصلا پیشنهاد نمیکنم. راستش دلیل این تغییر رو متوجه نمیشم!
شکل remark در لینک نهایی میتونه با تغییر دادن دستی حل بشه. گزینه remark فقط نمایشی است و این پنل از ایمیل داره برای remark استفاده اضافه میکنه.
در صورتی که فیلد ایمیل حتما باید یکتا باشه، وگرنه ترافیک ها قابل تفکیک و محاسبه برای هر کاربر نیست.

مشتری با دادن نام اکانت دیگران نباید بتونه مقدار مصرف رو بدست بیاره. این مورد کمی امنیتی محسوب میشه. در حال حاضر فقط ادمین این اجازه رو داره.

**Comment by alireza0** [comment]
@arsoltani72 
با اضافه شدن دستور /usage در نسخه جدید، کاربرها میتونن استعلام بگیرند.

**Comment by arsoltani72** [comment]
سلام 
من برای ساخت اکانت در تعداد بالا از کار شما استفاده کردم 
و برای مرتب کردن اکانت ها و حذف قسمت رندوم از فورک هگزا استفاده کردم 
در حال حاظر وقتی بین فورک شما و فورک هگزا جا به جا می شوم  چند ثانیه بعد از اجرای اسکریپت هگزا  هسته کرش میکند و  در قسمت استتوس پیام : 
x-ui.service: Failed with result 'signal'. 
![Uploading image.png…]()
![Uploading image.png…]()
نشان داده میشود راه درست کردنش چی هست

**Comment by arsoltani72** [comment]
![image](https://user-images.githubusercontent.com/117269334/226765467-dd59755d-8ec3-43ee-8619-6b4c3ed26d48.png)
![image](https://user-images.githubusercontent.com/117269334/226765462-f413105f-3432-4be2-b028-ef049febc092.png)

**Comment by alireza0** [comment]
@arsoltani72 
درود بر شما
بعضی فورک ها تغییراتی رو توی دیتابیس دارند که سویچ کردن باعث مشکلات خاص میشه.
توی نسخه جدید، امکان ایجاد کاربر بدون بخش تصادفی اضافه شده! لطفا چک کنید.

خطایی که دیده میشه مربوط به منقضی شدن certificate شماست.

**Comment by arsoltani72** [comment]
> 
راهکاری هست که این خطا رو برطرف کرد ؟
