### ISSUE TITLE
Compatibility for nginx fronting

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#610]
I also have the same problem for inbounds when I want nginx front.
Example :
Nginx set to get requests from 443 but when I set nginx to 443 I can't set configs to 443 so instead I need to set inbounds to for example 5443 and set nginx to forward 4r3 to 5443. 

The problem is X-UI script gives configs for 5443 and I need to manually set it to 443.

In this case I can't give subs to users, cause I can't make changes to inbound uris inside sub.

My solution for this:
is a toggle inside each inbound settings (not users) if the toggle enabled a new filed apper and we can set custom ports to be place in Xray uris which was generated from that inbound.
If the toggle not appear then do as before.

I would like to know what your thoughts about this issue. 

Thank You

**Comment by alireza0** [comment]
This one is not so easy!
The `Port` field is a kind of `primary-key` and playing with filed could be dangerous.
But I will keep it in my mind to find a general solution

**Comment by X-Oracle** [comment]
Hello @alireza0 

I understand the port section is used for many parts of X-ui's server.

what I'm suggesting is we have 2 sections for ports:
1) Primary port: which is used by server xray-core (this is the section we have right now and we don't want to mess with this as you said)
2) URI Port: which X-ui should use to generate Config URIs.

in order to have the second section, the URI generation function needs to be separated from Primary port.
this is easier and doesn't theoretically make problems if it is in `web js` section and not in `go`.

I would like to have your thoughts about it.
is it still problematic?
where is URIs Generation function? server-side or client-side (browser)?

**Comment by alireza0** [comment]
Everything is in client side!
But it should be stored somewhere in database. The we need to load it each time from backend.

I thought about adding possibility to add complete url in `path` input.
Then we can detect full url based on the information provided in this section.

But it adds complexities which is not my favour.
I am thinking about adding new section for other configurations or adding `proxy url` on each `panel` and `sub`

**Comment by X-Oracle** [comment]
Thanks for your response @alireza0.

> But it should be stored somewhere in database. The we need to load it each time from backend.

We can put `URI port` in related xray outbound config in `settings` key which is made by X-UI for additional data to be included in URI like `rprx-vision-udp443` for clients .

We can set a new key value like this ..
```json
"outbound":[
{
    "tag": "PORT-5566",
    "port": 5566,
    ...
    "settings" : {
        "reversePort": 443,
        ...
    }
}
]

```
I named it `reversePort` since it will be reversed in server .(you can name it anything you want)

This way has many benefits: 
1. Migration compatibility
2. Database structure won't change
3. Compatible with older version of X-UI if for some reason the admin tries to migrate to older versions or some version which doesn't have the new feature.
4. As X-UI already reads settings value for config URI generation it won't be hard to make this feature.

What's your opinion about this ?

**Comment by X-Oracle** [comment]
As for subscription, I don't know what it's mechanism is. I will look the related code and try to come up with something simple for it.

**Comment by alireza0** [comment]
@X-Oracle I don't get the point of using `outbound` for `inbound` configurations.
My idea was adding a parameter in `inbound.settings` and name it as `reverseURI` which has complete reverse's domain+port as a string.
I am thinking about its consequenses!

**Comment by X-Oracle** [comment]
@alireza0 
User's outbound is our server's inbound .
And URI is for user's outbound. So I called it outbound. Sorry for misunderstanding.

**Comment by EarlVadim** [comment]
@alireza0 

I'm trying to figure out how to use your improvements yesterday, but I couldn't. It's all too confusing. need a manual for testing..

**Comment by alireza0** [comment]
Done!
Available in next version...
