### ISSUE TITLE
Traffic Cap

### ISSUE THREAD

**Issue by nazari-dev** [alireza0/x-ui#613]
Feature: *Traffic Cap*

With this feature, you can define a traffic cap for each client limited to a period. Eg: 30G per month
This way the traffic automatically will be reset and at the end of the period (eg 30 days) 
Finally, this feature can have an expiration date. In this case, for example client will have 30G per month for a year.

**Comment by X-Oracle** [comment]
Good suggestion.

My solution for that:

3 check box under traffic limit:
1. Reset traffic on traffic end.
2. Reset traffic on expiration date.
3. Add traffic on expiration date.(in case you don't want the client to lose their remaining traffic.)

**Comment by alireza0** [comment]
@nazari-dev Except final expiration date, this feature is added by `Auto renew` feature in this release.
@X-Oracle  Adding some features need a complex solution which is not compatible with this weak implementation.

> Reset traffic on traffic end

Is already means infinite expiration date.

> Reset traffic on expiration date

Is about auto renew

> Add traffic on expiration date.

For this one we need to add another date for absolute expiration!
I am always thinking about negetive impacts on changing database structure :(

**Comment by nazari-dev** [comment]
@alireza0 Cool. Will this `Auto renew` have an ending/expiration date?

**Comment by alireza0** [comment]
@nazari-dev No!
Actually it is not a full accounting system.
Just about some features that makes the life easier ;)
