### ISSUE TITLE
سوال 

### ISSUE THREAD

**Issue by Gggbbhhhhhhhhh** [alireza0/x-ui#614]
سلام آقا علی رضا من از یکی چند وقته پنل می‌خرم مثل اینکه از شما میخریده 
ایدی تلگرام شما داخل پنل هست خداستم بپرسم چجوری باید درست کنم یا از خود شما خرید کنم ؟ 
چون گرون هست

**Comment by PesareIran250** [comment]
پنل علی رضا فروشی نیست 
مجانیه

**Comment by Gggbbhhhhhhhhh** [comment]
خب چجوری میتونم در ارتباط باشم باهاش چون از من ۳۳۰۰ هرماه میگیره

**Comment by Gggbbhhhhhhhhh** [comment]
> پنل علی رضا فروشی نیست
> مجانیه

کمکی میشه بکنید که چیکار یکنم ؟

**Comment by Gggbbhhhhhhhhh** [comment]
> پنل علی رضا فروشی نیست
> مجانیه

داخل وضعیت سیستم که میرم [panel3xui](https://t.me/panel3xui) این کانال تلگرامی یادداشت شده من هرماه دارم ۳۳۰۰ میدم تازه میگه کمم هست 
ای پی و اینا رو همه شو یعنی از اینجا مجانی میکیره ؟ 
لطفا ی کمکی بکنید

**Comment by PesareIran250** [comment]
پنل مجانیه اما سرور نه 
شما هزینه سرور رو به ایشون پرداخت میکنین که با هزینه کمتر و سرور ارزونتر هم میتونین

**Comment by Gggbbhhhhhhhhh** [comment]
> پنل مجانیه اما سرور نه
> شما هزینه سرور رو به ایشون پرداخت میکنین که با هزینه کمتر و سرور ارزونتر هم میتونین

خب هرچی باشه از ۳۳۰۰ بهتره هرماه پرداخت میکنم

**Comment by Gggbbhhhhhhhhh** [comment]
> پنل مجانیه اما سرور نه
> شما هزینه سرور رو به ایشون پرداخت میکنین که با هزینه کمتر و سرور ارزونتر هم میتونین

میشه کمکم کنید چجوری باهاش در ارتباط باشم 
چجوری خریداری کنم 
چون همین امروز اومدم گیت هاب اصلا سر در نمیارم 💔😅

**Comment by PesareIran250** [comment]
داداش علی رضا که سرور فروش نیستن
باید خودتون برین از سایتهایی که سرور میفروشن سرور بگیرین و نصب کنین که باید علمش و داشته باشین

**Comment by Gggbbhhhhhhhhh** [comment]
اخه اون بالا گفتید که پنل مجانیه برا سرور باید هزینه پرداخت کنم
اگر میشه سایت هم معرفی کنید
پس ققط پنل میتونم بگیرم ازشون ؟

**Comment by Gggbbhhhhhhhhh** [comment]
من واقعا پولام صفر شده انقد قیمت بالا میگیره واقعا هم پول نیاز دارم برا
همین پیام میدم شرمنده واقعا کمک میخوام

**Comment by PesareIran250** [comment]
6850930@gmail.com   میتونید ایمیل بدین راهنمایی کنم

**Comment by Gggbbhhhhhhhhh** [comment]
ایمیل دادم

**Comment by Gggbbhhhhhhhhh** [comment]
> [6850930@gmail.com](mailto:6850930@gmail.com) میتونید ایمیل بدین راهنمایی کنم

اومد ایمیلم ؟

**Comment by misagh72** [comment]
> > [6850930@gmail.com](mailto:6850930@gmail.com) میتونید ایمیل بدین راهنمایی کنم
> 
> اومد ایمیلم ؟

vpn میفروشی شما؟

**Comment by X-Oracle** [comment]
The Panel is free and open source.

The price you pay is for VPS and server configuration in order to make server ready for panel installation.

You yourself buy server and config server or pay somebody to do that for you. Simple
