### ISSUE TITLE
غیر فعال کردن speedtest

### ISSUE THREAD

**Issue by PesareIran250** [alireza0/x-ui#615]
سلام
چطور میتونم speedtest رو مسدود کنم چون گزینش تو پنل نیست
قبلا پنل سنایی بودم داشت
اگه نداره لطفا بگین به صورت دستی چه طور انجام بدم

**Comment by alireza0** [comment]
درود بر شما
توی بخش لیست دامنه های مسدود شده، این مورد رو اضافه کنید:
```json
[
  "geosite:speedtest"
]
```
