### ISSUE TITLE
دسترسی به منوی x-ui نصب شده در داکر

### ISSUE THREAD

**Issue by PesareIran250** [alireza0/x-ui#616]
آیا میشه وارد منو x-ui نصب شده بر روی داکر شد؟
چون x-ui مینویسم وارد قسمت مدیریت پنلی که بدون داکر و به صورت مستقیم نصب شده میشه و نمیتونم به محیط پنلی که با داکر نصب شده بشم

**Comment by alireza0** [comment]
لطفا از یک system admin کمک بگیرید.
