### ISSUE TITLE
Mtproto proxy

### ISSUE THREAD

**Issue by Morghak963** [alireza0/x-ui#617]
سلام مهندس جان وقت بخیر 

نمیدونم این پیشنهادم عملی باشه یا خیر ولی اگر بشه امکان ساخت پروکسی. Mtprotoبرای تلگرام هم به پنل اضافه بشه عالی میشه

با تشکر

**Comment by X-Oracle** [comment]
Mt-Proto is not included in Xray Core.
If Alireza wants to, then he needs to add a MT-Proto module and it's related backend and front code and checks if it crashes X-UI or not. which is a lot of work and I don't think he will do that.

**Comment by alireza0** [comment]
@X-Oracle @Morghak963  MT-Proto is easily recognizable for GFW. Due to this, it was not usable and `xray-core` has deleted this feature.
We strongly recommand to not to use it. It is better to use internal proxy server in your home/company and use socks5 for telegram conectivity in local network.
