### ISSUE TITLE
دسترسی به access logs

### ISSUE THREAD

**Issue by rasa68** [alireza0/x-ui#618]
سلام و وقت بخیر.
ممنون از آپدیت جدیدتون، خیلی کار با موبایل راحت شد.
یه پیشنهاد داشتم، امکانش هست در صفحه  System Status و بخش logs امکان دسترسی به access logs هم فراهم بشه؟

**Comment by X-Oracle** [comment]
It is possible but for what reason ?
Access log is for tracking people for what they visit.

**Comment by alireza0** [comment]
درود بر شما
همینطور که دوستمون اشاره کردن،‌ این لاگ برای استفاده های دیگه است که برای این پنل زیاد کاربردی نیست.
پیشنهاد من به دوستانی که از سرور اشتراکی استفاده میکنند هم اینه که این بخش رو در تنظیمات حذف کنند.

**Comment by yasinabbasiiii** [comment]
چطوری لاگ ها را غیرفعال کنیم در سرور، اصلا نمیخواهم لاگی ثبت بشود

> درود بر شما همینطور که دوستمون اشاره کردن،‌ این لاگ برای استفاده های دیگه است که برای این پنل زیاد کاربردی نیست. پیشنهاد من به دوستانی که از سرور اشتراکی استفاده میکنند هم اینه که این بخش رو در تنظیمات حذف کنند.

**Comment by alireza0** [comment]
@yasinabbasiiii https://github.com/alireza0/x-ui/issues/636#issuecomment-1826369022
