### ISSUE TITLE
Token api

### ISSUE THREAD

**Issue by mtashani** [alireza0/x-ui#620]
سلام علیرضا جان برای استفاده از api یبار لاگ این کنم و کوکی ذخیره کنم کافیه؟ یا باید دوره ای اینکارو بکنم؟

**Comment by ErfanTech** [comment]
بعد 1ماه منقضی میشه.

**Comment by alireza0** [comment]
درود بر شما
همونطور که دوستمون فرمودن، زمان انقضا داره که پیش فرضش یکماه تنظیم شده.
میتونید از تنظیمات پنل برای تغییرش استفاده کنید.
بهتره هربار قبل از اجرای دستوراتتون اعتبار کوکی رو چک کنید.
