### ISSUE TITLE
[BUG] Remaining 0 B

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#622]
Hello There Hope you doing well , thank you for this amazing update 1.6.0
i've encounter the BUG : 
when i move my mouse over traffic section this popup message comes up :
<img width="277" alt="image" src="https://github.com/alireza0/x-ui/assets/117269334/9f4e52d6-75ff-443a-88eb-59c6d6d1085d">
this is not a traffic calculation problem its just a preview problem i think

**Comment by alireza0** [comment]
Hello @wulfric93
Thank you for this report.
It is fixed now! You can compile it or wait for new version.

**Comment by wulfric93** [comment]
how can i compile it ?
