### ISSUE TITLE
Is it Possible to add Password/UDID Column 

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#623]
hi there hope you doing well is it possible to add Password/UDID Column to main x-ui page as Sanaei Panel

because i use them to find sold accounts in telegram to notify customers account expiration 

Thank you

**Comment by alireza0** [comment]
Hi @wulfric93 

It is not a good idea to find customers by UUID.
You should use email instead. You can search email as well as UUID in telegram bot.

I removed it because there was no logic to keep the page chaotic.

**Comment by wulfric93** [comment]
no no , i dont want to find user in panel 
i use trojan password to clients chat in telegram in order to tell them about their account expiration

**Comment by alireza0** [comment]
In admin access, you can search clients by `email`!
If it is your panel, use your admin access.
