### ISSUE TITLE
Telegram Bot Issue

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#624]
Hello there 
i've encounter problem with new 1.6.0 update :
i've used my client numerical Telegram ID instead of their Telegram ID and now users unable to ckeck their account usage 
is it a bug ?

**Comment by wulfric93** [comment]
i migrate from sanaei panel

**Comment by alireza0** [comment]
I didn't check if there is telegram ID there.
But it is not simple to change the way that lots of people are using right now.

**Comment by wulfric93** [comment]
in sanaei panel you can enter either telegam numerical id or telegram id and its worked with both

**Comment by alireza0** [comment]
I didn't track that change.
It will be added if I found a stable solution for it.

**Comment by wulfric93** [comment]
ill be appreciated 😊
