### ISSUE TITLE
Fallback missing

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#626]
Hi @alireza0 .
I was configuring ports without tls and I found that fallback is hidden when there is no tls.

as fallback works for non-tls and tls configs (except for reality). please make it unhidden again.

thanks

**Comment by alireza0** [comment]
Hi @X-Oracle,

Do you have any evidence or document for this claim?
It is clearly mentioned [here](https://xtls.github.io/en/config/features/fallback.html#fallbackobject) that:

> The `fallbacks` object is optional and can only be used for the `TCP+TLS` transport combination.

It was never worked for me to use fallback without tls.

**Comment by X-Oracle** [comment]
thanks for your reply @alireza0 

I wouldn't report it if it didn't work for me. I am already using it for port 80 (although its settings are not in `web panel` but the config is there in `config.json` since I migrated from sanai panel.)

> It is clearly mentioned [here](https://xtls.github.io/en/config/features/fallback.html#fallbackobject) that:
> 
> > The `fallbacks` object is optional and can only be used for the `TCP+TLS` transport combination.
> 
> It was never worked for me to use fallback without tls.

about this. it is said because it is insecure to use vless without tls so no one should use vless without tls.
but I'm using it as a reverse proxy rather than using it for user's config.

**Comment by alireza0** [comment]
I will add it after double check.
Thank you for this report by the way :)

**Comment by X-Oracle** [comment]
Thanks for you attention. 

I read the guide; Fallback originally made for preventing vless tls detection by active probing. vless without tls can be easily detected by gfw even without active probing so the author didn't mention anything.

but fallback code works for no-tls too but not for its original purpose but as a reverse proxy.

**Comment by alireza0** [comment]
It supports for `TLS` and `None` security types now.

**Comment by X-Oracle** [comment]
That's much better.
Thanks for your attention.
