### ISSUE TITLE
API Routes

### ISSUE THREAD

**Issue by rzadrzi** [alireza0/x-ui#627]
با سلام
چطور میتونم از API Routes استفاده کنم؟؟
/login with PUSH user data: {username: '', password: ''} for login
دقیقا منظور از عبارت بالا چیه؟؟؟

**Comment by alireza0** [comment]
درود بر شما
باید مثل فرم وب این دو پارمتر رو POST کنید به آدرس نوشته شده و بعد کوکی ها رو ذخیره کنید.
هر بار اعتبار کوکی رو چک کنید و اگر اعتبار داشت میتونید دستورات رو با api ارسال کنید.
