### ISSUE TITLE
سلام چرا قسمت request header  قسمت name رو خودتون Host وارد نکردید باید هربار یوزم میسازیم اون قسمت رو خودمون تایپ کنیم اینجوری اذیت میشیم و اینکه چرا trojan میسازیم گذینه tls رو خاموش میکنم ولی داخل برنامه که وارد میکنم گذینه tls فعال هستش این مشکل رو هم حل کنید ممنون

### ISSUE THREAD

**Issue by vahid68-vpn** [alireza0/x-ui#628]

**Comment by alireza0** [comment]
درود بر شما
هدر ها میتونن اسم های متفاوتی داشته باشن و همینطور مقادیر منتاظر اونها.
هاست یکی از هدرهایپر کاربرد محسوب میشه.

پروتکل تروجان به صورت پیشفرض با tls باید تنظیم بشه. خیلی از نرم افزارهای سمت کاربر هم این مورد رو به صورت پیش فرض دارند

**Comment by PesareIran250** [comment]
سلام

کلا همیشه فقط value وارد میکردیم کافی بود .اما الان باید name  و value رو تایپ کنیم تا سربرگ اضافه بشه

**Comment by alireza0** [comment]
اگر جایی این کار رو میکردین به این دلیل بود که مقدار name رو به صورت پیشفرض با host پر کردن. این مدل کار درستی نیست و هر هدر اسم و مقدار خاص خودش رو باید داشته باشه

**Comment by PesareIran250** [comment]
> اگر جایی این کار رو میکردین به این دلیل بود که مقدار name رو به صورت پیشفرض با host پر کردن. این مدل کار درستی نیست و هر هدر اسم و مقدار خاص خودش رو باید داشته باشه

مهندس الان یه مشکل دیگه که دارم host و name رو پر میکنم و به inbount اضافه میشه اما وقتی با گوشی اسکن میکنم تو تنظیمات کانفیگ هاستی که وارد کردم نیست و باید همونجا تو گوشی باز دستی برای کانفیگ تایپ کنم
