### ISSUE TITLE
Request header

### ISSUE THREAD

**Issue by Saeedroshan1906** [alireza0/x-ui#629]
سلام در قسمت request header مشکل هست و در سر برگ وقتی یه سایت وارد میشه موقع سیو کردن در اینباند وارد نمیشه

**Comment by alireza0** [comment]
درود بر شما
منظورتون رو درست متوجه نشدم. لطفا با مستنداتی مثل عکس بیشتر توضیح بدید.
تست هم گرفتم مشکلی نداره. احتمالا تنظیماتتون رو درست انجام ندادید

**Comment by Saeedroshan1906** [comment]
سلام مشکل حل شد باید در قسمت استتار  http گزینه local به صورت دستی تایپ کرد
که در پنل جناب ثنایی تایپ شده هست سپاس از لطفتون

**Comment by Saeedroshan1906** [comment]
و اینکه چرا توی پنل منوی وارپ وجود نداره ؟

**Comment by alireza0** [comment]
برای نصب وارپ گزینه ها و آموزش های زیادی موجوده.
برای هر کاربردی باید به شکل خاصی استفاده بشه.
هر کدوم رو که فکر کردید بهتره، با مسئولیت خودتون میتونید اضافه کنید.
