### ISSUE TITLE
Subscription based bandwidth report

### ISSUE THREAD

**Issue by Enkidu-6** [alireza0/x-ui#630]
Hello again and thank you for your hard work. I have to say I really like the addition of displaying the bandwidth and the online or offline status.

Now it seems to me that the panel is already making those calculations and keeps track of them and the database is able to handle the pressure. My question is how hard or easy for that matter, would it be to add up those already calculated numbers based on the subscription ID?

The reason I'm asking this is - to me - , the main purpose of a subscription link is to be able to provide one user with several configs. In other words, let's say I have 5 Inbounds and each inbound has Jack as a user. Since the email address can't be the same, his account is  Jack1 under inbound1, Jack2 under inbound2, Jack3 under inbound3, etc... But Jack has the same subscription ID under all inbounds, let's say Jack-xyz. So Jack gets 5 different configs. Reality-TCP, TCP-TLS, Reality-GRPC, etc...

The problem is that I can limit the bandwidth individually for each account but not the combined bandwidth as a whole based on the subscription ID.

So again, I was wondering. Would this be a major undertaking to combine those numbers and set the limit on the combined usage for the subscription ID?

Thanks again for your time.

Cheers.

**Comment by alireza0** [comment]
Hello @Enkidu-6 ,

XTLS project as well as X-UI project are trying to provide free and easy solutions for accessing people to free internet.
These kind of solutions will only use in commercial porpose whic is not our target.

Some features has both commercial and personal benefits. When we understand that people could get the most of this features, then we will provide/accept the solutions.

Thank you for your understanding

**Comment by Enkidu-6** [comment]
Thank you for the reply. I completely agree. Circumventing censorship should not be a for profit endeavor. I'm not in it for the money either. 

To give you a better picture, I'm a Tor relay operator currently running 6 Guard relays which are generally used as the first point of entry to the Tor Network. I also run about 30 snowflakes proxies which for some reason - compared to other countries - is favoured among Iranians by an order of magnitude. This is a momentary snapshot of how many people are connected to only one of my snowflake machines:
```
      1 Belarus
      1 Canada
     29 China
      1 Colombia
      2 Czechia
      1 Denmark
      2 Finland
      2 France
      4 Germany
      1 Hong Kong
      1 India
    884 Iran
      1 Italy
      1 Lithuania
      2 Netherlands
      2 Poland
      2 Romania
     20 Russia
      1 Singapore
      2 Spain
      1 Switzerland
      1 Turkey
      1 Uganda
      1 Ukraine
      1 United Kingdom
     10 United States
```
Together my servers contribute 190 TB upload (380 TB combined) each month and all for free.

The popularity of snowflake with Iranians was a reason for me to look for other ways to help, which eventually brought me to Xray and X-UI. I now also have a few of your panels running and the configurations are provided to people from several countries on various groups and forums and to individuals for personal use, all for free.

Unfortunately, Iran seems to be one of a few countries where donated configurations are harvested by a group of people who apply for personal use and then sell them for profit which brought me to the conclusion that there needs to be a method to prevent abuse to preserve the overall health of the network.

There are several ways to combat that, one of which would be bandwidth limitation. Other methods are IP limits or time limits. For now, I'm using configurations that are valid for 3 days and then they need to be replaced. This won't stop the abuse immediately but it will tarnish the reputation of those selling a 3 day config as a monthly subscription.  

Again thank you for reading my long and in parts, off topic response. Just venting. :) Feel free to close this thread.

Cheers.

**Comment by X-Oracle** [comment]
> Together my servers contribute 190 TB upload (380 TB combined) each month and all for free.

Wow that a lot.

> Unfortunately, Iran seems to be one of a few countries where donated configurations are harvested by a group of people who apply for personal use and then sell them for profit which brought me to the conclusion that there needs to be a method to prevent abuse to preserve the overall health of the network.

It comes from people not knowing the donation source. unfortunately, not many people are interested in making these source public so this will be the obvious result. although config source can be figured out when shared by links but most of them are given to people with encrypted files made by application like NapsternetV.

speed limit for each IP ( NOT UUID ) is obvious choice, but Xray refuses to add the feature as @alireza0 mentioned, this can make more ways to make profit out of it. 
So, if you want to make speed limit you don't need Xray for that. IP based speed limit is used in every download-datacenter if you search you will find something.

Good Luck.

**Comment by Enkidu-6** [comment]
@X-Oracle 
Thanks for the comment. Yes I'm aware of those, but speed or bandwidth use is not really a concern to me. Speeds are not limited and I can easily handle twice the current bandwidth usage. It's just that it pisses me off when I see a bunch of schmucks try to make easy money off the backs of the very people I'm trying to help . 

The most obvious sign of abuse is when you see a config given to one person, relays far too much data than a single person can use or would need. That's when you know you're not dealing with one person and it's been sold. The solution for that is to either limit the data usage per config or limit the config by IP address.

But I fully agree with @alireza0 and the X-Ray developers. Allowing bandwidth limitation will simply put more money in the pockets of those who are in this for profit and that goes against the spirit of X-Ray and this panel.

Cheers.
