### ISSUE TITLE
Adult content block not working

### ISSUE THREAD

**Issue by Amirali-Rezaei** [alireza0/x-ui#631]
I set the adult content blocking to true, and in my xray settings it's blocked, but I can still access adult websites, like pornhub.![Screenshot_20231118_180532_Vivaldi Browser.jpg](https://github.com/alireza0/x-ui/assets/80537157/deb8f910-fd9a-494a-b324-af735f56466c)

**Comment by X-Oracle** [comment]
Hi @Amirali-Rezaei 
it's not a bug.
The document for XRAY DNS server is not clear.
by default, Xray sends DNS requests to your vps's DNS server.
I suggest you configure your vps's DNS in order to apply DNS based adult content blocking.
