### ISSUE TITLE
یه برنامه نویسی هست که با هسته xray کار کرده باشه؟

### ISSUE THREAD

**Issue by m0x61h0x64i** [alireza0/x-ui#635]
سلام مهندس، الان اگر منِ کاربر 100 کیلو مصرف میکنم اینو xray میفهمه اما اون کدی که نوشته میشه که بره اینو توی دیتابیس اعمال کنه رو خود xray کنترل میکنه یا باید خودمون بنویسیمش؟

**Comment by alireza0** [comment]
درود بر شما
باید از xray بخونید و خودتون اضافه کنید
