### ISSUE TITLE
غیرفعال کردن لاگ و محاسبه میزان مصرف

### ISSUE THREAD

**Issue by yasinabbasiiii** [alireza0/x-ui#636]
سلام
چطوری میتوانم لاگ و محاسبه میزان مصرف را غیرفعال کنم؟
سرور ضعیفی دارم و استفاده شخصی، میخواهم بار سرور به حداقل برسد. چون از سرور برای کار دیگری هم استفاده میکنم
تشکر

**Comment by alireza0** [comment]
درود بر شما
توی بخش تنظیمات xray باید لاگ رو به شکل زیر تنظیبم کنید:

```json
  "log": {
    "loglevel": "info",
    "access": "/dev/null"
  }
```

**Comment by X-Oracle** [comment]
for logs:

```json 
 "log": {
    "loglevel": "none"
  }
```

and delete `policy.system`.

it won't log nor count user traffics.
