### ISSUE TITLE
Add the ability to specify a separate port when adding clients (xtls-reality)

### ISSUE THREAD

**Issue by Pro100x3mal** [alireza0/x-ui#637]
Hello. I have configured xtls-reality (manually) such that the server itself listens on 127.0.0.1:8443. On vps, using the nginx module ssl_preread_server_name, I configured it so that nginx listens on port 443 and then proxies to the services I need - xray on port 8443, other sites - on 4430, 4431, etc. In this case, port 8443 is closed using ufw. All of this can be customized using your excellent x-ui panel. But there is a need to manually adjust the URL links for clients, namely:

1) With this configuration, clients must connect to the xray server not at 127.0.0.1 (localhost), but at the vps IP address. You can solve the problem either by specifying a domain in the x-ui configuration that refers to the vps IP address or manually specifying the vps server IP in the client application instead of the automatically transmitted value 127.0.0.1.

2) With this configuration, x-ui creates a link for the client indicating port 8443 (for the reality protocol), but you need to manually set the client application to port 443. Hence the question: is it possible to add to the x-ui configuration the ability to specify the port separately in the settings client? To simplify this, is it possible to add the default value from the port server to this field, but give the opportunity to change it to another?

My use case is also relevant for setting up a very useful configuration with your dest like here: https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY/steal_oneself

**Comment by X-Oracle** [comment]
> 1. With this configuration, clients must connect to the xray server not at 127.0.0.1 (localhost), but at the vps IP address. You can solve the problem either by specifying a domain in the x-ui configuration that refers to the vps IP address or manually specifying the vps server IP in the client application instead of the automatically transmitted value 127.0.0.1.


you want a new field to set custom port for user's client port rather than xray-server listen port? (like https://github.com/alireza0/x-ui/issues/610)


> 2\. With this configuration, x-ui creates a link for the client indicating port 8443 (for the reality protocol), but you need to manually set the client application to port 443. Hence the question: is it possible to add to the x-ui configuration the ability to specify the port separately in the settings client? To simplify this, is it possible to add the default value from the port server to this field, but give the opportunity to change it to another?

this already exists with the name `multi-domain` but it only enables when tls toggle is enabled.
it could be useful for non tls configs ( Vmess CDN, multi-domain configs ) too, so I suggest moving `multi-domain` right bellow `listen field` and make it available for all domains.

what do you think about this @alireza0 ?

**Comment by X-Oracle** [comment]
@Pro100x3mal 

for port, it is not possible to make deffrent ports for each inbound-user simce x-ray doesn't allow us to configure individual port for each use.



As for domain, it can be configured to be user based since it is not related to xray, but it makes the panel.

I personally think it can be implanted like this:

1- Have multi-domain available for all kind of  configs in inbound section. ( this can easily implanted as it needs some adjustment to existing code.)

2- Have a new field in user section, if field the inbound section ignored and make config based on the user field. (this can make panel heavier as it needs to check for each user and makes panel slower like a turtle if the users are a lot.)

**Comment by AliBelali** [comment]
recently I saw in a response alireza was considering add this option
option that just change client's config link and qr code but config actually work in port that configed in inbound, this option is usefull for who is using reverse proxy like nginx

alternatively you can run nginx on custom port (let's asuume port 8443) and config x-ui inbound port that you want client's to connect (let's assume 443)
after that add a firewall dst-nat rule to redirect all requests from network interface of server (for example eth0) on port 443 to port 8443
this rule in iptables is something like:

```iptables -t nat -A PREROUTING -m addrtype --dst-type LOCAL -i eth0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 8443```

in this situation client send requests to port 443
firewall of the server redirects requests to port 8443 that is the port nginx is listening , nginx checks the request if request have format of v2ray connection it sends requests to port 443 (port that xray is listening)

for better security you can drop direct requests to nginx by adding another firewall rule:

```iptables -A INPUT -m addrtype --dst-type LOCAL -i eth0 -p tcp -m tcp --dport 8443 -m state --state NEW -j DROP```

**Comment by AliBelali** [comment]
> @AliBelali Yes, we'll be waiting for the author to implement this great feature! Your use case does not suit me, since I also have a variety of services on different ports, including through nginx

in this scenario since all requests on port 443 will be redirected to nginx(with firewall) , it's as same as running nginx on port 443 and for example if you have a website that handled by nginx it will be accessable on port 443

**Comment by alireza0** [comment]
Dear @Pro100x3mal @AliBelali @X-Oracle 

As I mentioned in #607 and #610 , it is not sane to add a feature (for some group of users) which may cause problem or difficulty for normal users.

Adding this feature for subscription is somehow a logical idea. But for individual inbounds or the panel, I did not find a conclusion or a general way.

@X-Oracle Multidomain is designed for TLS based configurations which people can use SNI.
This feature could be combined with sub+Fallback and avoid a lot of repeated work on links.
BTW, It is already added to tls configuration in database. Therefore, moving it to a place in inbound table will cause problem for old configurations.

**Comment by X-Oracle** [comment]
@alireza0 could we at least make vmess to have a domain other than x-ui panel domain.
from what i see, it can only be changed if listen Ip changes but if I for example put Cloudflare Ip in it, then xray won't listen to 0.0.0.0 and make the config unusable.

> Multidomain is designed for TLS based configurations which people can use SNI.
> This feature could be combined with sub+Fallback and avoid a lot of repeated work on links.

I understand this. this is one of the benefits of Multidomain, but other non-tls could have benefits other than this.
like:
- providing multiple domains in case one of them goes down.

BTW it is only a suggestion. Multidomain is a good feature for non-tls domains too.

**Comment by alireza0** [comment]
I have finished implementing my general idea on my new codes and tests.
It would be appreciated if you can also test it in order to preparing for new release.

This implementation's benefits:
- Non-tls inbounds is now could have one or more domains!
- Support forcedTLS/none/same security for using on behind of proxy
- Change port is possible for each one
- Move it to standard streamSettings instead of only tlsStream object
- Use a migration for old MultiDomain users and optimizing database

**Comment by X-Oracle** [comment]
@alireza0 
Awesome. I will test it once I learn how to build it 😅(I'm a python guy, I don't know how to build another language right now)

**Comment by alireza0** [comment]
Done!
Under the test for new version...

**Comment by MK0ltra** [comment]
Completely unnecessary feature. Such complicity is against the general use of xui panels specially for normal users. There should be a limitation on requesting features in production purpose.

**Comment by alireza0** [comment]
@MK0ltra 
I am completely disagree!
Limitation is useful for business. While multi domain and multi port is necessary for bypassing GFW and limitation.

**Comment by Enkidu-6** [comment]
I agree. The best way to blend in is to make our connections as similar as possible to normal web browsing, which means coming in through port 443 or 80 for everything. The current modifications by @alireza0  is a leap forward toward that direction.

Unfortunately I don't see a good A to Z instruction for implementing this method in x-ui with Haproxy or nginx, at least not in English. There may be something in Farsi somewhere which I'm not aware of. But as I said, this is a leap forward in that direction and hopefully soon we'll see a good instruction so everyone - novice or expert - can easily implement this.

This will also opens the door to perhaps bundling x-ui with a preconfigured Haproxy or Nginx docker image to make it possible for everyone to use this method without having to modify the core X-ui panel with all the complexities that it entails.

Kudos to @alireza0  and Cheers.
