### ISSUE TITLE
باگ قطع نشدن یوزرها حتی در صورت غیرفعال کردن

### ISSUE THREAD

**Issue by PesareIran250** [alireza0/x-ui#638]
متاسفانه در پنل ثنایی و علیرضا اگه دستی یوزرها را غیرفعال کنید همچنان متصل باقی میمونن.میبینید که دکمه های کشویی یوزر خاموش هست
حتی تو اخرین ورژن هر دو پنل این مشکل وجود داره
عکس پیوست  رو ببینین
 البته کاربر کنار دست خودم بود و دستی چند بار  خاموش کردم اما باز کانکت بود .
![unnamed (1)](https://github.com/alireza0/x-ui/assets/114500209/d5785e28-28a5-4b71-a8be-d27d6121e1b3)

**Comment by alireza0** [comment]
آنلاین بودن کاربر معمولا بستگی به ترافیک داره و تا مدتی بعد از قطع شدن احتمال آنلاین دیده شدن وجود داره. ولی این دلیلی برای اینکه کاربر قطع نشده نیست.

لطفا اطلاعات کاملتری ارائه بدید.
تنظیمتون چی بوده؟ آیا لاگی داشتید و یا خیر ؟!
آیا ترافیک محاسبه میشه ؟
