### ISSUE TITLE
How to Access the number of online clients API?

### ISSUE THREAD

**Issue by behnamsadeghi22** [alireza0/x-ui#639]
سلام
چطوری میتونم به API تعداد کلاینت‌های آنلاین دسترسی داشته باشم؟

**Comment by alireza0** [comment]
درود بر شما
توی نسخه آخر اضافه نشده.
نسخه بعدی اضافه می کنم.

**Comment by alireza0** [comment]
https://github.com/alireza0/x-ui#api-routes
