### ISSUE TITLE
بالا نیومدن وبسایت مدریت کاربران

### ISSUE THREAD

**Issue by shayanadad** [alireza0/x-ui#640]
درود
سرور من هر چند وقتی یک بار دگه وارد وبسایت مدیریت نمی شود و کانفیگ های که از قبل بودن هم کار نمیکردن 
ای پی و دامنه هم پینگ میدن 
با این حال من یک بار کامل x-ui پاک کردم و دوباره نصب کردم و با این حال بازم وبسایت بالا نمیاد 
با ایپی بغییر  ایران میره

**Comment by alireza0** [comment]
درود بر شما
وقتی از جاهای دیگه میتونید باز کنید مشکل از پنل نمیتونه باشه.
