### ISSUE TITLE
تاریخ انقاضا

### ISSUE THREAD

**Issue by alka30r** [alireza0/x-ui#641]
سلام 
میخوام مثل قدیم تاریخ انقضا نشون بده 
الان مینویسه چند روز مانده و  برای تک تک یوزرا باید موس نگه دارم تا تاریخ ببینم 

(من چون برای پیدا کردن تاریخ کاربرای هر روز مجبور به سرچ هستم اینو میخوام   و خود پنل قسمتی نداره سرچ کنه بر اساس تاریخ

**Comment by alireza0** [comment]
درود بر شما
لطفا نسخه قدیمی که با روش کار شما مناسب هست رو نصب بفرمایید.

برای جستجو بر اساس تاریخ فیچری نداریم در حال حاضر

**Comment by ramtiny** [comment]
کاش بدون دانگرید کردن بشه اون قابلیت رو مثل قبل تو تاریخ انقضا ها آورد
