### ISSUE TITLE
مشکل اضافه نشدن host به کانفیگ بعد اسکن در گوشی

### ISSUE THREAD

**Issue by PesareIran250** [alireza0/x-ui#642]
سلام
هاست و والیو رو پر میکنم به Inbound  اضافه میشه اما تو گوشی که کانفیگ به برنامه ایمپورت میکنم host اضافه نشده و باید دستی وارد 
کنم  
چه با لینک چه با کیو آر کد 
.نمونه لینک
vless://b85515f0-d417-462d-dq9a-5376bef5df70@serials.cimop.ir:456339?type=tcp&path=%2F&host:www.telewebion.com&headerType=http#vless-user4-mk
و این مشکل تازه به وجود اومده چون پنل شما رو 2 هفته  قبل اخرین ورژن رو یک سرور دیگه نصب کردم مشکل نداره اما 2 روز پیش رو یه سرور دیگه نصب کردم این مشکل وجود داره

**Comment by alireza0** [comment]
درود بر شما

این مشکل از جایی دیگه بوجود اومده.
لطفا تنظیمات رو از طریق پنل چک کنید. در بخش Request Header ، در ورودی نام دقیقا Host رو وارد کنید و در بخش مقدار www.telewibion.com .
اسکریپت ایجاد لینک vless چنین نتیجه ای نمیتونه ایجاد کنه : 

path=%2F&**_host:www.telewebion.com_**&headerType=http

درستش اینه:

path=%2F&host=www.telewebion.com&headerType=http

**Comment by PesareIran250** [comment]
راستش با qr code اسکن میکنم بازم همینه و هاست به گوشی ایمپورت نمیشه حتی با برنامه های ویندوزی مثل v2rayng , nekoray همین مشکل وجود داره.
یه سرور خام از هتزنر گرفتم و تست کردم بازم همین مشکل وجود داشت و مجبور شدم سرور اصلی رو ببرم رو پنل دوستتون
میتونم qr code که پنل میده رو براتون بفرستم خودتون  تست کنید

**Comment by PesareIran250** [comment]
> درود بر شما
> 
> این مشکل از جایی دیگه بوجود اومده. لطفا تنظیمات رو از طریق پنل چک کنید. در بخش Request Header ، در ورودی نام دقیقا Host رو وارد کنید و در بخش مقدار [www.telewibion.com](http://www.telewibion.com) . اسکریپت ایجاد لینک vless چنین نتیجه ای نمیتونه ایجاد کنه :
> 
> path=%2F&**_host:www.telewebion.com_**&headerType=http
> 
> درستش اینه:
> 
> path=%2F&host=www.telewebion.com&headerType=http

اینو من دستی تایپ کردم برای اینکه متوجه بشین و اشتباه تایپی داشتم بین = و :
خود پنل لینکی که میده داخلش هاست نیم وجود نداره در صورتی که تو قسمت مشخصات inbound فیلد مربوطه هاست و نام وجود داره

**Comment by alireza0** [comment]
نام Host رو با حرف اول بزرگ باید استفاده کنید
