### ISSUE TITLE
اضافه یا ادغام با هسته سینک باکس

### ISSUE THREAD

**Issue by uzer98** [alireza0/x-ui#644]
یکسری پروتکل های جدید مثل هیستریا۲ و توییک روی هسته سینک باکس هست که پنل مدیریتی برای کنترل حجم و زمان نداره
اگه هسته سینک باکس با پروتکل های هیستریا۲ و توییک تو هسته x-ray ادغام بشه که بشه مدیریت کرد یوزرها رو 
عالی میشه

البته این دو هسته در کنار هم نصب و بدون مشکل کار میکنن و مشکلی برای ادغام و کنار هم بودنش نیست

**Comment by alireza0** [comment]
این پنل برای استفاده راحت از xray طراحی شده و امکان اضافه کردن هسته دیگه به راحتی نیست.
