### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by l3lack-eyes** [alireza0/x-ui#647]
سلام . چطور وارپ بزنم؟روش و کد تمپلیت از پنل سنایی میشه برداشت؟

**Comment by Shellgate** [comment]
چندین روش برای این کار هست ولی پیشنهاد نمیشود
همچنین از Tor هم میتوانید به جای وارپ استفاده کنید

**Comment by Shellgate** [comment]
[[
  {
    "protocol": "freedom",
    "settings": {
      "domainStrategy": "UseIP"
    }
  },
  {
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  },
  {
    "tag": "WARP",
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "127.0.0.1",
          "port": 40000
        }
      ]
    }
  }
]](url)

**Comment by Shellgate** [comment]
> [
  {
    "protocol": "freedom",
    "settings": {
      "domainStrategy": "UseIP"
    }
  },
  {
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  },
  {
    "tag": "WARP",
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "127.0.0.1",
          "port": 40000
        }
      ]
    }
  }
]

**Comment by Shellgate** [comment]
```go
[
  {
    "protocol": "freedom",
    "settings": {
      "domainStrategy": "UseIP"
    }
  },
  {
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  },
  {
    "tag": "WARP",
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "127.0.0.1",
          "port": 40000
        }
      ]
    }
  }
]
```

**Comment by Shellgate** [comment]
```go

[
    {
      "mux": {
        "concurrency": -1,
        "enabled": false,
      },
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "level": 8,
            "method": "chacha20-poly1305",
            "ota": false,
            "password": "",
            "port": 40000
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": ""
      },
      "tag": "proxy"
    },

``` 

رد کردن کل ترافیک سیستم از وارپ
