### ISSUE TITLE
Best resources for V2ray

### ISSUE THREAD

**Issue by armin567ip** [alireza0/x-ui#648]
Hi sir, I hope you're doing great.

Which type of server resources is more important in V2Ray and X-UI to handle users smoothly, Is it Ram, CPU, SSD?
Which one you think is more recommended.

And what type of CPU is better with V2ray Ampere or Intel/AMD?

And what Linux distro do you personally recommend?

**Comment by alireza0** [comment]
Hi @armin567ip,

Everything is related to your type of usage. For v2ray/xray, CPU and the speed of RAM are most important.

My personal recommendation is:
1. 2x core CPU (Inter/AMD/ARM)
2. 1G of RAM >= DDR4
3. Ubuntu > 20.04 LTS minimal

If you need logs, it is better to have SSD or NVME high speed disks.
If you are using VPS or cloud systems, please be aware of shared HDD speed which may cause database errors. At least remove the unnecessary logs.

**Comment by alireza0** [comment]
Check this: #636

**Comment by alireza0** [comment]
For traffic limit, you need traffic reports and don't need logs.
For other types of limitations by 3rd party apps, you may need to using logs.
