### ISSUE TITLE
Need Vless Proxy Example 

### ISSUE THREAD

**Issue by MrMarvel** [alireza0/x-ui#649]
Can you write output config to forward to proxy for me.
oubound for now:
```json
[
  {
    "protocol": "freedom",
    "settings": {}
  },
  {
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  },
  {
    "tag": "blackhole",
    "protocol": "freedom"
  }
]
```

Simple xray server(2nd server) has config:
```json
{
  "log": {
    "loglevel": "info"
  },
  "routing": {
    "rules": [],
    "domainStrategy": "AsIs"
  },
  "inbounds": [
    {
      "port": 490,
      "protocol": "vless",
      "tag": "vless_tls",
      "settings": {
        "clients": [
          {
			"comment": "MrMarvel (Owner)",
            "id": "SECRETe51-ad3e-4121-9c4b-27087935a4e2",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "dl.google.com:443",
          "xver": 0,
          "serverNames": [
            "dl.google.com"
          ],
          "privateKey": "MEFRmIBSECRET7EWatavoak9_77Q0jlsUhv3YvpLR20",
          "minClientVer": "",
          "maxClientVer": "",
          "maxTimeDiff": 0,
          "shortIds": [
            "857ae98e6f267cb4"
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ]
}

```

**Comment by wulfric93** [comment]
Hi there 
use this : https://github.com/XTLS/Xray-examples

**Comment by Shellgate** [comment]
[
  {
    "mux": {
      "concurrency": 0,
      "enabled": true
    },
    "protocol": "vless",
    "settings": {
      "vnext": [
        {
          "address": "Example.com",
          "port": 443,
          "users": [
            {
              "encryption": "none",
              "flow": "",
              "id": "74649d8d-ddb8-4baa-b66d-d07dfc832608",
              "level": 8,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "allowInsecure": false,
        "fingerprint": "firefox",
        "publicKey": "",
        "serverName": "Example.com",
        "shortId": "",
        "show": false,
        "spiderX": ""
      },
      "wsSettings": {
        "headers": {
          "Host": "Example.com"
        },
        "path": "/4726/???/"
      }
    },
    "tag": "proxy"
  },
  {
    "protocol": "freedom",
    "settings": {
      "domainStrategy": "UseIP"
    }
  },
  {
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  },
  {
    "tag": "direct",
    "protocol": "freedom"
  }
]
