### ISSUE TITLE
Display the number of active and connected IPs and display the number of active user IPs in a separate box

### ISSUE THREAD

**Issue by Shellgate** [alireza0/x-ui#650]
گزینه ای به صفحه اول پنل اضافه شده و تعداد کاربران متصل با تعداد ای پی های متصل را نمایش دهد

 
ایجاد باکس کوچک که تعداد نفرات متصل یا ای پی های متصل از یک یو ای دی را نمایش دهد

**Comment by X-Oracle** [comment]
number of active users: already exists.
connected IPs: not possible with xray-core Api.

**Comment by alireza0** [comment]
امکان انجام این درخواست برای پروتکل های پراکسی وجود ندارد.
