### ISSUE TITLE
Reverse Guide 

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#651]
درود و عرض ادب 
آیا امکانش هست که یک راهنمایی برای ریورس پروکسی کنید ؟
من یک سرور در آلمان دارم 
یک سرور در ایران 
چطور میتونم این کار رو بکنم ؟

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم

https://alireza0.github.io/fa/docs/security/reverse/

برای نسخه بعد شما میتونید بدون دستکاری و یا دانش تنظیمات xray، این تنظیمات رو انجام بدید.
عکسش ظاهریش رو توی صفحه اول این ریپوزیتوری گیتهاب گذاشتتم
فقط مفاهیم رو از لینک بالا و مراجعش بخونید.

**Comment by wulfric93** [comment]
نسخه جدید کی منتشر میشه ؟

**Comment by alireza0** [comment]
معمولا وقتی مجموع کارهایی که میخوایم انجام بشه و تمامی تست ها رو انجام دادیم، منتشر میشه.
