### ISSUE TITLE
عدم نمایش صحیح حجم باقی مانده در inbounds

### ISSUE THREAD

**Issue by m38d1** [alireza0/x-ui#653]
با سلام
در قسمت inbounds در کنار نوار وضعیت حجم مصرفی کاربر در صورت tool tip نگه داشتن روی حجم اون رو بصورت 0B در نظر گرفته
میشه یه بررسی کنید لطفا
X-UI: 1.6.0
Xray: 1.8.4
![image](https://github.com/alireza0/x-ui/assets/5637159/eff4d94a-0601-4862-94b3-1c0f9fc23197)

**Comment by wulfric93** [comment]
در آپدیت بعدی مشکل حل خواهد شد

**Comment by alireza0** [comment]
Duplicate issue. It is already fixed

[[bug] fix remained traffic display](https://github.com/alireza0/x-ui/commit/1735faa1930f5a27390cd14c6fbbf88c6ba12ee0) https://github.com/alireza0/x-ui/issues/622
