### ISSUE TITLE
TLS for Shadowsocks

### ISSUE THREAD

**Issue by shahin-io** [alireza0/x-ui#654]
hello @alireza0 jan

can u please consider adding TLS layer to Shadowsocks!? this layer help to obfuscation traffic of shadowsocks and at same time has more benefits than VMESS for example “supporting UDP network”. kaka panel support this method and u can using it for implementation into ur panel. thanks for ur work and time.

**Comment by alireza0** [comment]
Hello @shahin-io ,

Thank you for this suggestion. You are right. I will add it soon.

**Comment by alireza0** [comment]
Done!
It will be available in next version.
