### ISSUE TITLE
Bugs I encountered so far.

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#656]
@alireza0 
os : ubuntu 22
x-ui version: self-built till [e372575](https://github.com/alireza0/x-ui/commit/e372575f58482244076d41e4d665eb55244d8fa8)
database: a copy of my main server.

here are my test results so far:

1- external proxy: it won't migrate old `multi-domains` to `external proxy`
2- external proxy: external proxy problem with ipv6 (`***:****:****:****:443`) [it should only split the last `:`]
2- external proxy: checking the port part to be integer and be in range of `[0:65536]`. since clients will probably crash if they saw a letter or out of range number in port section.
3- external proxy: when external proxy enables, we should hide `Domain name` when `tls` or `reality` enabled.
4- sub: needs an example under `Reverse Proxy URI` for a hint
5- Xray settings.Outbounds : make the table width match the outer frame like `routing rules` table
6- Xray settings.Outbounds : add outbound.json.link : it does not work (I think its purpose is v2ray-link->json )
7- Xray settings.Outbounds : add outbound.json.link : when button clicked ,`close` or (X) button won't work and needs to reload the page.
8- x-ui system status.logs: logs font color is unreadable in light theme.

**Comment by alireza0** [comment]
Thank you for the test and report.
some answers are listed below:
1. Migration could be run in install script. For manual running you should use `x-ui migrate` on manual build.
2. & 2. Actually it is only for `domain:port` and IPv6 support is somehow complext. Any mistake in port and IP will cause only problem in link generator and not crash.
3.  Yes! I have finished removing serverName for tls and it is under the test.
4. Good point! I have to add a paramether for all settings to have a placeholder.
5. It contains two table with less data : Outbounds and Reverse. Designing will be checked for next version.
6. I will check it. Thanks
7. It is because error handeling which should be implemented in JS. I will check it.
8. It is about designing problem which I should find a solution soon.

Overall thank you for all.
I will change the codes and announce them here.

**Comment by X-Oracle** [comment]
Thanks for reading my report.

> 2\. & 2. Actually, it is only for `domain:port` and IPv6 support is somehow complex


The behavior of external proxy for ipv6 is like this ...

for example, we have:
- 111.111.111.111:443
- 2606:4700::6810:84e5:8443

For first one the link will be normal but for ipv6 it will be like this:
domain = 2606 (the first part of ipv6 ) port = 443 (port of the previous domain)

also, it will result in `http:500` for all users in inbound containing ipv6 in `external proxy`.

> Yes! I have finished removing serverName for tls and it is under the test.


For `Reverse Proxy URI` it worked like this:  `http | https://domain:port/path/`


Thanks for the huge improvements in `xray settings` section. specially replacing Json text view.

Good Luck.

**Comment by alireza0** [comment]
Altought there is not enough space in this form, but I am going to separate host and port...

**Comment by X-Oracle** [comment]
> Altought there is not enough space in this form, but I am going to separate host and port...

In python I usually get `domain:port` as a string and split them using `:`, pick last part as port, join the rest of them using `:` and put it as domain.

Can't we achieve something like that in js?

**Comment by alireza0** [comment]
In fact we had nothing for validating all the values!
I know that it is not a clean code, but starting a new project is much easier than refactoring with validation :(

For IPv6, we should use brackets like `[a:b::c:d]:433` and in x-ui, validatings are on the shoulder of the admin.
Unfortunately it is not efordable to have everithing perfect.

BTW, please check migration process and all the fixes.
Thank you in advance

**Comment by X-Oracle** [comment]
> In fact we had nothing for validating all the values!
> I know that it is not a clean code, but starting a new project is much easier than refactoring with validation :(

Oh, what a safe code 😅.
That fine.

> For IPv6, we should use brackets like [a:b::c:d]:433 and in x-ui, validatings are on the shoulder of the admin.
> Unfortunately it is not efordable to have everithing perfect.

I will test that.

> BTW, please check migration process and all the fixes.

I will.

**Comment by X-Oracle** [comment]
@alireza0 
config generation won't put ports in the configs.
the port problem is not related to ipv6.

> For IPv6, we should use brackets like [a:b::c:d]:433 and in x-ui, validatings are on the shoulder of the admin.
Unfortunately it is not efordable to have everithing perfect.

I did [2606:4700::6810:84e5] for domain section and 8443 for port section.
it did put [2606:4700::6810:84e5] for domain but port did not.

> BTW, please check migration process and all the fixes.

it migrated perfectly.

**Comment by X-Oracle** [comment]
the placeholder for sub needs to be like `(http|https)://domain[:port]/path/` instead of `(http|https)://domain[:port]/path`

**Comment by X-Oracle** [comment]
xraySettings.Outbounds.reverse : delete button doesn't work but if we hit delete button and delete an outbound, we will see that it deleted.

**Comment by X-Oracle** [comment]
in `xraySettings.Outbounds.reverse`:
if we add reverse functionality manually in `advanced template`, will it recognize them and add them to reverse table?

I know it will recognize the "reverse" key in template, I'm talking about reverse outbound and inbound.

**Comment by X-Oracle** [comment]
> I did the test for vmess, vless, trojan and SS again, but it works fine for me!

I'm sure it didn't put any port in generated links.

**Comment by alireza0** [comment]
> As links generated using sub are also broken, I doubt about problem being web client side.

Super! It was type mistmatch and it is fixed now.

But I did a test in remote windows OS/Edge browser vless/tcp/reality and it works fine!
Could you pelase pull the latest head and hard refresh the page ?

**Comment by X-Oracle** [comment]
I will it may take time.

**Comment by X-Oracle** [comment]
but it needed hard refresh in order to fix the web panel port.

**Comment by X-Oracle** [comment]
> the placeholder for sub needs to be like `(http|https)://domain[:port]/path/` instead of `(http|https)://domain[:port]/path`

this needs to fix too or we can set it to add `/` if there is no `/` at the end of base sub link/

**Comment by X-Oracle** [comment]
@alireza0 is there anything else for me to test?

**Comment by alireza0** [comment]
> but it needed hard refresh in order to fix the web panel port.

Yes. Changing in codes and testin local needs always a good consideration on browser cache.

> this needs to fix too or we can set it to add `/` if there is no `/` at the end of base sub link/

Done!

> @alireza0 is there anything else for me to test?

Thanks a lot for your accurate tests.
I will wait till tomorrow for further tests and reports and then release the new version.

Supporting external proxy for panel itself was tested before and I think it is almost okay withouth need to add configuration as same as subscription. Isn't it ?

**Comment by X-Oracle** [comment]
> Supporting external proxy for panel itself was tested before and I think it is almost okay withouth need to add configuration as same as subscription. Isn't it ?

Yeah, it works.
When I used sanai panel before migrating to yours, There was a situation when I restarted the panel, it would redirect to configured panel port (54321) instead of the revered port I used before restarting panel (443). I think it was set to redirect to panel port instead of just refreshing the page. But it seems fixed but it would be better to check if you see it critical.

Good luck.

**Comment by X-Oracle** [comment]
Inbound configuration: It seems that after migration . Panels will forget all sni fields.

Not a problem for reality users. Only for tls users.

**Comment by X-Oracle** [comment]
X-ray core 1.8.6 seems unstable

**Comment by X-Oracle** [comment]
@alireza0 

vless tcp without external proxy .
Qr code configs are ok but subs config address are 127.0.0.1.

It is ok for reality tho.

**Comment by alireza0** [comment]
> Inbound configuration: It seems that after migration . Panels will forget all sni fields.
> 
> Not a problem for reality users. Only for tls users.

`sni` and `server name` was not in correct place. It does not work properly before.
sni was in inbound.streamSettings.tlsSettings.settings.serverName
server name was in inbound.streamSettings.tlsSettings.serverName ( which is exactly the sni place )

> vless tcp without external proxy .
> Qr code configs are ok but subs config address are 127.0.0.1.

Weird! It is OKay here and in a production server!
