### ISSUE TITLE
How to change host

### ISSUE THREAD

**Issue by KvizadSaderah** [alireza0/x-ui#657]
Hi. 
Could you please help me find a solution. 
Parnell was setup for custom domain, got clients. 
But now I found out that for better security it's better to use localhost as a host. 
Changed it docker-compose.yml. 
But nothing helps console still available under custom domain, not on localhost. 

Where should I make changes?

upd:
1. Install with custom domain as host
2. Run
3. Connect clients
4. Try to change host

**Comment by alireza0** [comment]
Hello @KvizadSaderah ,

If you mean domain name for the panel itself, it is possible to set localhost in panel settings.
The you should run a third party app like nginx or using ssh tunnel to access the panel.

if you want to change urls' domain name, you should wait for next version to use `externalProxy` and set configuration's domains there.

**Comment by alireza0** [comment]
> where is that record, settings that tells console to work on specific hostname?

It is in the first page of panel seetings called `Panel Listening Domain`.

> p.s. so on 1 server, i was able to change hostname from `localhost` to `custom domain`, but was not able to turn it back.
> Maybe because of added peers. But i'm not sure.

Configs are served by xray-core. When you define a hostname in the configuration of inbound, xray-core will limit the connection for this hostname.



> p.p.s. all i want is to change panel hostname from `https://custom-domain.com` to `localhost`, that it would only be accessable from local

When you chnage it in panel settings, it is only affected access to the pannel.
