### ISSUE TITLE
Telegram username

### ISSUE THREAD

**Issue by Navid-9696** [alireza0/x-ui#659]
سلام 
توی قسمت ربات تلگرام به غیر یوزرنیم لطفا آیدی هم اضافه شود و وقتی کاربر دریافت آمار رو میزنه هم آیدی نشونش بده هم یوزرنیم (در ثنایی این کار انجام شده)
همچنین متن پیکربندی یافت نشد ادامش خیلی عجیب نوشته شده و میتونست قشنگ تر باشه
و نکته آخر اینکه اگه میشد به جای حجم کل میزان باقی مانده دوره ای که شارژ شده رو نشون میداد بهتر بود
مثلا یک کلاینت 300 گیگ مصرف کرده و من براش دوباره 50 گیگ شارژ میکنم
در قسمت کل بجای مثلا 300 / 350 بزنه 0 / 50 چون ریست ترافیک نمیخوام بزنم و میخوام مشخص باشه مصرف ها

**Comment by alireza0** [comment]
درود بر شما
استفاده از chatId در نسخه جدید اضافه میشه. قبلا این درخواست اعلام شده بود.

> در قسمت کل بجای مثلا 300 / 350 بزنه 0 / 50 چون ریست ترافیک نمیخوام بزنم و میخوام مشخص باشه مصرف ها

این حالت امکان پذیر نیست. چون این نرم افزار برای حسابداری پیچیده ساخته نشده و باید یک سری کار های ساده رو انجام بده.
چون اطلاعات داخل دیتابیس رو نشون میده، بهتره خودتون به جای ۳۵۰ بهش ۵۰ بدید.

سپاسگزارم
