### ISSUE TITLE
پنهان کردن Webrtc

### ISSUE THREAD

**Issue by Shellgate** [alireza0/x-ui#661]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

سلام و عرض ادب 
مشکل ssl و repata گوگل و شناسایی شدن ای پی ایران توسط سایت های تحریم شده مانند Vulter
از تایم زون مروگر 
در ویندوز برنامه هایی برای پنهان کردن Webrtc وجود دارد ایا امکان اضافه کردن قابلیتی برای رفع این مشکل وجود دارد 

با شناسایی ای تایم ایران مسدود میشود نمونه های مسدود شده و نمونه شناسایی توسط سایت ها

![Screenshot_۲۰۲۳-۱۱-۳۰-۱۹-۳۷-۰۹-۶۵۵_com android chrome](https://github.com/alireza0/x-ui/assets/128194280/119610b6-755d-4033-bc82-aaab6c9a6542)

![Screenshot_۲۰۲۳-۱۱-۳۰-۱۹-۴۸-۴۲-۸۹۵_cn wps xiaomi abroad lite](https://github.com/alireza0/x-ui/assets/128194280/873fa373-8189-47b2-bb3e-2babc978d51d)

**Comment by Shellgate** [comment]
قابل توجه اون دوستی که میگفت تایم زون هیچی نیست

**Comment by Shellgate** [comment]
کاش راهی بود که این مشکل رو خل میکردیم چندین بار توسط سایت های تحریمی شناسیی شدم و اکانت والترم رو هم بستن بستن این دوستان با ردگیری تایم زون مروگر ها اقدام به شناسایی میکنند
فقط دو روش رو برای این مشکل پیدا کردم

تغییر تایم زون سرور و منطقه و تایم گوشی ها
استفاده از افزونه Webrtc control در مرورگر های chrome و Firefox
بازم چیزی یافتم اطلاع میدم ولی کاش راه حلی برای این موارد پیدا میکردید که سرور های مقصد توانایی خواندن اطلاعات ما رو نداشته باشن و عوض مود ما فقط تایم زون سرور و لوکیشن سرور براشون به نمایش در بیاد

مرسی و تشکر بایت توسعه این برنامه ها

**Comment by X-Oracle** [comment]
Webrtc is a problem if you are using a proxy, since it bypass it. 
You don't need to worry about it if you are using VPN mode, since all traffic include webrtc is tunneled through vpn.

Android users are using VPN mode by default.

**Comment by Shellgate** [comment]
You are right, just like the image, websites are able to identify the time system, and my vulter is for the same purpose. closed
