### ISSUE TITLE
path های مختلف در یک inbound ?

### ISSUE THREAD

**Issue by yasinabbasiiii** [alireza0/x-ui#662]
سلام
آیا امکان دارد path های مختلف در یک inbound داشته باشیم؟
![image](https://github.com/alireza0/x-ui/assets/49768974/d50bd280-a753-44e1-baff-eab299429cbd)

**Comment by alireza0** [comment]
درود بر شما
خیر. در پرتکل انتقال [WebSocket](https://xtls.github.io/en/config/transports/websocket.html#websocketobject) فقط یک مسیر میشه معرفی کرد.
ولی در هدر http در مدل tcp میشه چند تا path معرفی کرد.

**Comment by yasinabbasiiii** [comment]
آیا با تغییر در سورس پروژه میشه این امکان را اضافه کرد یا کلا ب خاطر ساختار وب سوکت نمیشه؟

**Comment by alireza0** [comment]
این پنل تنظیمات رو برای xray-core آماده میکنه و اونجا اجرا میشه.
لینک ارائه شده نشون میده که xray-core ساپورت نمیکنه و برنامه نویسی باید اونور انجام بشه.
شما میتونید با استفاده از پراکسی های دیگه مثل nginx استفاده کنید و path ها رو به این سرویس متصل کنید.
