### ISSUE TITLE
Testing the new version, External proxy

### ISSUE THREAD

**Issue by Enkidu-6** [alireza0/x-ui#663]
I am testing the new panel features after your modifications and when I go to any inbound --> External Proxy --> same , regardless of the port used, the port number is blank in the subscription link. So let's say I choose port 443, It comes out as ***@domain.ltd:?*** instead of ***@domain.ltd:443?***

And in the v2rayNG app the port shows as ***-1***

Not sure if this is a bug or I'm doing something wrong.

Thanks.

**Comment by alireza0** [comment]
Thank you for reporiting. It was reported in #656 as well.
It is now fixed by
[[sub] fix port in externalProxy](https://github.com/alireza0/x-ui/commit/d2f693817707d9240ddc01b264c864608efba262)

It was about my fault on casting integer (port number) into string.

**Comment by Enkidu-6** [comment]
Thank you. It's fixed.
