### ISSUE TITLE
آموزش استفاده از قابلیت های جدید تونل معکوس

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#665]
سلام
ممنون میشم راهنمایی بفرمایید چطور هست

**Comment by alireza0** [comment]
درود بر شما
یه راهنمای قدیمی قبلا نوشتم میتونید مفاهیم رو ساده تر [اونجا](https://alireza0.github.io/fa/docs/security/reverse/) ببینید.
توی مدل جدید، تنظیم به جای کد، گرافیکی شده.

**Comment by wulfric93** [comment]
به صورت واضح تر اگر توضیح بدید ممنون میشم

**Comment by alireza0** [comment]
@aliamg1356 

اگر به تصویر ها دقت کنید میتونید متوجه بشید که چطور کار میکنه.

تنظیم سرور خارجی:
در پل (Bridge) دو outbound با هم پل میشوند اولی دریافت کننده ترافیک از سرور داخلی (interconnection) و دومی ارسال کننده به اینترنت آزاد ( یا سرور بعدی)

تنظیم سرور داخلی
در پرتال (Portal) چندین inbound با یک inbound interconnection  به هم متصل میشوند که اولی شامل همه کاربران و دومی ارسال کننده به سرور خارج است.


@wulfric93 

> به صورت واضح تر اگر توضیح بدید ممنون میشم

منطقش خیلی ساده و کوتاهه. لطفا بفرمایید کدوم بخشش سخته یا اگر سوالی دارید بفرمایید تا بیشتر توضیح بدم.

**Comment by aliamg1356** [comment]
> @aliamg1356
> 
> اگر به تصویر ها دقت کنید میتونید متوجه بشید که چطور کار میکنه.
> 
> تنظیم سرور خارجی: در پل (Bridge) دو outbound با هم پل میشوند اولی دریافت کننده ترافیک از سرور داخلی (interconnection) و دومی ارسال کننده به اینترنت آزاد ( یا سرور بعدی)
> 
> تنظیم سرور داخلی در پرتال (Portal) چندین inbound با یک inbound interconnection به هم متصل میشوند که اولی شامل همه کاربران و دومی ارسال کننده به سرور خارج است.
> 
> دامین فیلد اجباریه و فقط برای تشخیص و تفکیک ترافیک ریورس ها از هم (بین تانل های مختلف) استفاده میشه
> 
> @wulfric93
> 
> > به صورت واضح تر اگر توضیح بدید ممنون میشم
> 
> منطقش خیلی ساده و کوتاهه. لطفا بفرمایید کدوم بخشش سخته یا اگر سوالی دارید بفرمایید تا بیشتر توضیح بدم.

دو تا اینباند در سرور ایران ساختم و یکی رو در اوتباند سرور خارج وارد کردم در سرور خارج رو حالت بریج دو اوتباند دایرکت و ایران رو گذاشتم  در سرور ایران هم رو حالت پرتال اینتر کانکشن رو گذاشتم اینباند تانل و اوتباند رو گذاشتم اینباند یوزر  اما هیچ تبادلی انجام نشد  و کار نکرد
