### ISSUE TITLE
مشکل در لینک سابسکریپشن

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#667]
با سلام و عرض ادب 
مشکلی که پیش اومده این هست که من توی هر پورت یک یوزر رو ایدی سابسکریپشن با ساب دامین های متفاوت دادم و وقتی که آپدیت کردم پنل رو و از لینک آپدیت کردم اکانت ها رو ، همه اون یوزر ها با دامنه ای که برای سابسکریپشن  ست کرده بودم ریلود شدن و دامنه های متفاوت لود نشدن 
مشکل چی هست ؟
با ورژن 1.6.0 این مشکل نبود

**Comment by wulfric93** [comment]
ببینید مشکل به این صورت هست 
من 8 تا اینباند دارم با پورت های متفاوت و توی هر اینباند یک یوزر رو برای خودم با یک نام سابسکریپشن مثلا Test  ست کردم که از همه پورت ها یک کلاینت باشه و همه این اینباند ها هم با ساب دامنه های متفاوتی از یک دامنه مثلا : 
a.test.com
b.test.com
.
.
.
z.test.com
هستن 
و آدرس پنل با a.test.comهست و آدرس لینک سابسکریپشن هم همینطور 
با ورژن قبلی 1.6.0 وقتی آپدیت میکردم کلاینت ها هر کدوم با آدرس سابدامین خودشون میومدن ولی با ورژن جدید همه با  آدرس لینک سابسکریپشن آپدیت میشن

**Comment by wulfric93** [comment]
> @wulfric93
> 
> لطفا هربار از لینک نصب استفاده کنید. فرآیند نصب شامل یک مرحله مهاجرت میشه که دیتابیس شما رو برای نسخه جدید آماده میکنه. اگر فقط فایل x-ui رو بروزرسانی کردین میتونین دوباره نصب کنید ویا فرآیند مهاجرت رو دستی انجام بدید:
> 
> ```shell
> x-ui migrate
> ```

این قسمت رو من متوجه نشدم

**Comment by alireza0** [comment]
> این قسمت رو من متوجه نشدم

وقتی از یک نسخه به نسخه دیگه میرید، توی اسکریپت نصب یه متد داریم که کار تغییرات دیتابیس رو انجام میده. شما اگر از منو x-ui برای بروزرسانی استفاده کرده باشید این کار اتوماتیک انجام میشده.

مشکل شما حذف شدن servername بوده و برای حل مشکلتون برای هر اینباند باید دستی توی external proxy اون دامنه ها رو اضافه کنید.

**Comment by wulfric93** [comment]
سپاس مشکل حل شد

> > این قسمت رو من متوجه نشدم
> 
> وقتی از یک نسخه به نسخه دیگه میرید، توی اسکریپت نصب یه متد داریم که کار تغییرات دیتابیس رو انجام میده. شما اگر از منو x-ui برای بروزرسانی استفاده کرده باشید این کار اتوماتیک انجام میشده.
> 
> مشکل شما حذف شدن servername بوده و برای حل مشکلتون برای هر اینباند باید دستی توی external proxy اون دامنه ها رو اضافه کنید.
