### ISSUE TITLE
مشکل در انتخاب Configure Strategy for Freedom Protocol

### ISSUE THREAD

**Issue by Shellgate** [alireza0/x-ui#668]
سلام و عرض ادب
این مورد بعد از اپدیت دیگر کار نمیکند البته میتوان در منوی دیگر تغیر داد ولی این گزینه کلا کار نمیکند و امکان تغییر رو نمیدهد

![IMG_۲۰۲۳۱۲۰۲_۲۲۰۷۴۶](https://github.com/alireza0/x-ui/assets/128194280/8e4ba5aa-b993-48ed-8f92-382602498a74)
![IMG_۲۰۲۳۱۲۰۲_۲۲۰۷۱۷](https://github.com/alireza0/x-ui/assets/128194280/dcf02386-2e83-42ef-8753-5eb441f2d5b1)

**Comment by Shellgate** [comment]
افزودن این گزینه fragment برای افرادی که از cdn استفاده میکنن اون هم به صورت  گرافیکی واقعا عالی بود البته سرعت اتصال رو کاهش میده چون یه وقفه ایجاد میکنه تا بسته ها رد بشن

**Comment by Shellgate** [comment]
![IMG_۲۰۲۳۱۲۰۳_۰۱۱۳۱۵](https://github.com/alireza0/x-ui/assets/128194280/52a25f1f-0117-4c17-84b3-cfc9a80397c6)

چه مقادیر رو بیشتر پیشنهاد میکنید 
این گزینه cpu بیشتر درگیر میکنه ولی در عوض بسته ها رد میشن

**Comment by alireza0** [comment]
درود بر شما
بله، متاسفانه بخش اول به دلیلی اینکه برای تنظیمات قدیمی درست شده بود این مشکل رو داره که به دنبال یک freedom بدون tag میگرده و اگر نباشه درست کار نمیکنه.
باید ببینم چطور میتونم یک حالت کلی براش در بیارم. و یا اگر این مورد وجود نداشت این گزینه غیر فعال باشه.

بله دقیقا بخش دوم قابلیت این رو داره که از سرور داخل محدوده فیلتر شده، یک سری سایتها مثل یوتیوب رو به راحتی با Fragmentation بدون سرور خارجی مستقیم متصل نگه دارید.

**Comment by Shellgate** [comment]
یک باگ دیگه هم در بخش outbound هست اونم اینه که نمیسه برای هر inbound تعویض کرد و روی کل شبکه اعما میشه

همچنین گزینه mux رو هم اضافه بشه خوبه

**Comment by Shellgate** [comment]
واقعا کارتون درسته مرسی و تشکر 
با اینکه ایده های زیادی دارم ولی فکر میکنم خودتون بهتر بتونید پروژه رو ادامه بدین

**Comment by alireza0** [comment]
> یک باگ دیگه هم در بخش outbound هست اونم اینه که نمیشه برای هر inbound تعویض کرد و روی کل شبکه اعمال میشه

این کار شدنیه، ولی نه توی بخش outbound. باید توی بخش قوانین مسیریابی این کار رو انجام بدید. لطفا در نظر داشته باشید که ترتیب قوانین خیلی مهم هستند. یعنی بالاترین قانون اگر match بشه دیگه قوانین بعدی نمیتونن اعمال بشن.
نکته مهم اینه که اگر برای یک ارتباط، هیچ قانونی به outboumd نرسید، اولین outbound به عنوان خروجی برگزیده میشه. پس outbound اول هم خیلی مهمه.


> همچنین گزینه mux رو هم اضافه بشه خوبه

به این دلیل اضافه نشده که برای کاربرد شخصی خیلی مناسبه و برای سرور پیشنهاد نمیشه و کاربرد درستی نمیتونه داشته باشه.

به هر حال سپاسگزارم از لطف و همراهیتون
همه این ایده ها گاهی قبلا گفته شده و در اون زمان تایید و یا انجام نشده.
خوبه و سپاسگزارم که ایده ها رو مطرح میکنید. این خاصیت دنیای متن بازه. این ایده ها در یک زمان بهتر به هم میرسن و عملیاتی میشن.

**Comment by alireza0** [comment]
https://alireza0.github.io/fa/docs/security/reverse/

**Comment by Shellgate** [comment]
عالی مفید و کاربردی

**Comment by Shellgate** [comment]
جدیدا پیگیر Hysteria2 بودم و به نتایج خوبی رسیدم هیتریا واقا عالی عمل میکند و همچنین پروکسی داخل دارد که تمکان استفاده و تانل کردن ان را فراهم می‌کند پنل های را یافتم که تقریبا توانستن هیستریا را با xray ترکیب کنند حتی برنامه هایی همچون v2raya  tuic رو هم در خود دارند حال اگر ما بتوانیم این ها را به هسته xray پیوند دهیم یا حداقل با پراکسی داخلی پیش برسم میتونسم جزو اولین پنل های باشیم که این این قالبیت ها را اضافه کرده اند

**Comment by Shellgate** [comment]
> https://alireza0.github.io/fa/docs/security/reverse/

در سرور ایران پورتال ایجاد می‌کنیم ایا نام دامنه را تغیر میدیهم یا نام دامنه دامنه سرور ایرانی هست یا خارجی

**Comment by Shellgate** [comment]
> https://alireza0.github.io/fa/docs/security/reverse/

 
برای این مورد خواهشمندم دو کانفیگ کامل ارایه هم برای ایران و هم خارجی

نتونستم این مورد رو کامل کنم

**Comment by alireza0** [comment]
Fixed. Please update
