### ISSUE TITLE
ربات تلگرام سمت کلاینت

### ISSUE THREAD

**Issue by smblue07** [alireza0/x-ui#67]
سلام وقت بخیر
ربات تلگرام سمت کلاینت درست کار نمیکنه، اگه امکانش هست بررسی کنید و اینکه قبلا با عبارت
/usage uuid
کلاینت میزان مصرفشو میتونست چک کنه ولی الان با این کد بهش خطا نمایش میده
اگر امکان داره هم با id هم با ایمیل میزان مصرف کلاینت نمایش داده بشه توی ربات خیلی عالی میشه
یعنی کلایت عبارت 
/usage uuid
/usage Email 
رو فرستاد بتونه مصرفشو مشاهده کنه
سمت ادمین همه چی عالیه . تشکر از شما

**Comment by razikazeminezad** [comment]
تایید میکنم این مشکل هست و نظر دوستمون خیلی بهتره .

**Comment by alireza0** [comment]
درود بر شما
ممنونم از مشارکت و ریپورت خطا

در مورد اینکه درست کار نمیکنه لطفا توضیح بیشتر بدید، من مشکل رو نمیتونم اینجوری متوجه بشم.
لطفا توجه داشته باشید که برای اینکه کاربر بتونه مصرف کانفیگ هاش رو ببینه، باید telegram username اون کاربر رو به انتهای email های مربوط به خودش و بعد از @ اضافه کنید. تنها در این صورت میتونه ترافیکش رو ببینه.
لطفا نمایش خطا و همچنین از نتیجه دستور `/start` و نتیجه زدن دکمه `get status` رو برای من ارسال بفرمایید.

اینکه کاربر هم بتونه همه ایمیل ها رو جستجو کنه، امنیت رو پایین میاره. این مورد مخالفان زیادی داره.

**Comment by smblue07** [comment]
سلام وقتتون بخیر
مشکل دقبقا همینجاس که من به تمامی یوزرهام گفتم برای مشاهده مصرفتون میتونید عبارت /usage uuid (که uuid هر اکانت رو به کاربر ارسال کردم)رو توی ربات بزنید و مصرفتون رو ببینید. الان علاوه بر اینکه سیستم رو تغییر دادید و دیگه با اون دستور قبلی نمیتونه یوزر مصرفشو ببینه و باید حتما ایمیل رو بفرسته تا ببینه، ادمین هم بابد بره ایمیل تمام کلاینتهاشو تغییر بده و آیدی تلگرام بهشون اضافه کنه (شاید یوزر تلگرام ما واسه خودش آیدی ست نکرده باشه!؟!) 

واسه همین درخواست کردم که اگرقراره شیوه جدیدی واسه استعلام گیری اضافه بشه به پنل، شیوه قبلی هم برقرار بمونه. ممنون
اسکرینشاتی ندارم از دیروز کوچ کردم به اسکریپت اقای ثنایی و فعلا دارم بخاطر ربات کلاینت قبلی از پنل اقای ثنایی استفاده میکنم

**Comment by alireza0** [comment]
منطقیه!
متاسفانه این روش چک کردن با uuid  از زمانی که فقط vmess و vless  قابلیت مولتی کلاینت داشتند مونده و برای trojan کاربردی نداره.
برای کاربر میتونم جستجو با uuid و password برای trojan رو به شکل قبلی اضاقه کنم.

@razikazeminezad 
هر پنل و نرم افزاری، امکانات و کاربرد خودش رو داره.
این پنل کلی ضعف داره که با این تغییرات ساده قابل تصحیح نیست و در صورت اضافه کردن، دیگه نمیتونه با پنل های مشابه دیگه کار کنه.
ولی نقاط قوت زیادی داره و در همون حد بمونه، میتونه نیاز خیلی ها رو برطرف کنه

**Comment by smblue07** [comment]
خسته نباشید
چون واقعا بخش ادمین این پنل فعلی رو خوشم اومد و تنهامشکلم با بخش کلاینتش بود که نیازمند این بود تمام کلاینتهارو مجدد توی پنل تغییر بدم و بهشون اطلاع بدم که روش استعلام گیری تغییر کرده (البته این موضوع واسه سرورهایی که روش یوزر تعداد بالا دارن مشکل سازه و واسه پنلهای تازه تاسیس خیلی هم مناسبه)
بهرحال ممنون میشم اگه همون مدل قبلی استعلام با uuid رو برای vmess  و vless اضافه کنید توی اپدیت جدیدتون
با تشکر

**Comment by razikazeminezad** [comment]
> منطقیه! متاسفانه این روش چک کردن با uuid از زمانی که فقط vmess و vless قابلیت مولتی کلاینت داشتند مونده و برای trojan کاربردی نداره. برای کاربر میتونم جستجو با uuid و password برای trojan رو به شکل قبلی اضاقه کنم.
> 
> @razikazeminezad هر پنل و نرم افزاری، امکانات و کاربرد خودش رو داره. این پنل کلی ضعف داره که با این تغییرات ساده قابل تصحیح نیست و در صورت اضافه کردن، دیگه نمیتونه با پنل های مشابه دیگه کار کنه. ولی نقاط قوت زیادی داره و در همون حد بمونه، میتونه نیاز خیلی ها رو برطرف کنه

درسته اما چه دلیل داره ما از تغییر دادن پنل بترسیم؟
کسی نخواد اپدیت نمیکنه.
من 1800 تا یوزر دارم یک روز متوجه شدم تانلی که از ایران به سرور زدم مشکل داره همون روز کل 1800 نفر رو قطع کردم و مشکل رو رفع کردم کامل و از اول به همه اکانت ساختم و دادم دلیل این کار اینه که من باید امنیت کاربرم اولویتم باشه نه رضایتش چون هیچ اطلاعاتی ندارن اونا.
اولویت با صحیح بودن سیستم هست نه با نظر دیگران حتی من.
ذاتا ربات تلگرام یه اپشن هست برای پنل بهتر روش های جدید اتصال  که الان داره فعال میشه رو V2ray دنبال شه.
مثل Xvision.
این REALITY رو هم تست زدم نشد چطوریه این؟

**Comment by alireza0** [comment]
@smblue07 
به نسخه جدید اضافه شد

@razikazeminezad 
تغییرات پیشنهادی اگر مشکلی برای دیگران ایجاد نکنه و امکانات زیادی اضافه کنه، استقبال میکنم.
برای ربات تلگرام من از بکاپ شروع کردم و موارد دیگه اضافه شد.

در مورد Reality تا اینجای کار نمیشه به راحتی توی این پنل گنجونده بشه. علاوه بر اینکه هنوز همه کلاینت ها ساپورت نمیکنن و پارامترهای لینکش دقیق مشخص نیست.
فعلا برنامه ای براش ندارم

**Comment by alireza0** [comment]
@smblue07 
تا چند دقیقه پیش این تغییرات به صورت prerelease  بود. برای تست در این حالت باید دستی فایل رو جایگزین کنید.
در حال حاضر نسخه جدید ریلیز شده و میتونید با دستورات اتوماتیک، بروزرسانی کنید.

خواهشمندم از نو بروزرسانی و آزمایش کنید

**Comment by smblue07** [comment]
بله خیلی ممنون الان چک کردم اوکی شده بود
بسیار متشکرم مهندس عزیز
یه مورد جزئی دیگه هم که هست اینه که هر بار کلاینت به ربات هر پیامی میده ارور ❗ Unknown message دریافت میکنه (من با کلاینت ها روی ربات در ارتباطم و قبلتر این پیغام فقط در هنگام استارت کردن ربات نمایش داده میشه و بعد از پیامهای دیگه پیغام ❗ Unknown message واسش ارسال نمیشد)
اینم میشه برطرف کرد که هر بار بعد هر پیام کلاینت نمایش نده؟
تصویر رو به پیوست میفرستم 
![Screenshot_2023-03-17-18-12-44-305_ir ilmili telegraph](https://user-images.githubusercontent.com/118044213/225938090-053690ef-d410-4512-985f-40eb6f929fa8.jpg)

**Comment by aliafshany** [comment]
@alireza0 

سلام آقا علیرضا.

میبخشید من پنلم رو به آخرین نسخه آپدیت کردم ولی همچنان ربات تلگرام من سرچ با uuid رو پشتیبانی نمیکنه.
در صورتی که با email id اوکی هست و مشکلی ندارم.
ممکنه این رو چک کنید؟ ریستارت پنل هم زده شده.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/40741745/228026102-b531905b-dd98-4bcd-9921-58e13da943e9.png">
