### ISSUE TITLE
Remove domainName in tls and reality #656 IMPORTANT

### ISSUE THREAD

**Issue by l3lack-eyes** [alireza0/x-ui#672]
خسته نباشید . دلیل این امر چیه ؟
کسی که هم ریلتی داره هم cdn باید چیکار کنه؟

**Comment by r0zbeh** [comment]
سلام پاک نشده به محلش تغییر کرده میتونید از این به بعد برای تمام پروتکل های این رو استفاده کنید ، تیک External Proxy رو روشن کنید میتونید اونجا اضاف کنید / فکر کنم باید قسمت اولش رو same بزارید!

**Comment by l3lack-eyes** [comment]
بله الان چک کردم روی همون پورت دامین جدید رو ست کردم و اوکی شد . ممنونم ازتون فقط اینکه کارایی ش چی هست مخصوصا گزینه های غیر ''same''

**Comment by r0zbeh** [comment]
خودمم درگیرش هستم ولی طبق چیزایی که علیرضا جان گفتن :
برای ترکیب با نرم افزار خارجی مثل nginx و دامین های مختلفه

Same: امنیت مشابه inbound
None: وقتی ورودی nginx بدون tls باشه، توی لینک، tls حذف میشه.
TLS:  وقتی nginx با tls خودش تنظیم شده، tls به لینک اضافه میشه

**Comment by r0zbeh** [comment]
![image](https://github.com/alireza0/x-ui/assets/25858679/3e1b0f71-7f74-40b9-8dc8-c7d4d95867ff)
چون فارسی انگلیسی بود بهم ریخته بود این بهتر مشخصه
