### ISSUE TITLE
1 لینک ساب برای چند اینباند و

### ISSUE THREAD

**Issue by BehnamAB** [alireza0/x-ui#676]
سلام خسته نباشید میخواتم بدونم تو پنل جدید میشه کاری کرد که 1 لینک ساب به یوزر بدیم که شمامل چند اینباند با کانفیگهای مختلف باشه ولی مصرف حجم و زمان رو  روی همه کانفیگ ها محاسبه کنه ؟

**Comment by mortezaafshar92** [comment]
> این قالبیت وجود دارد ولی تعریف این مورد نیاز به دانش فنی دارد میتونید برای هر inbound رو به یک outbound در قسمت route تنظیم کنید و کانفیگ های مختلف رو متصل کنید

برای افراد مبتدی سخته دیگه اینی که شما میگی

**Comment by alireza0** [comment]
درود بر شما
ویژگی های بات تلگرام و سابسکریپشن در این پنل به صورت خیلی ساده تعریف شده.
اگر شما از تنظیمات externalProxy استفاده کنید، همه اینک ها به یک کاربر برمیگرده و همه یکجا محاسبه میشه.
در غیر اینصورت ساختار این پنل اجازه این کار رو به ما نمیده.

**Comment by BehnamAB** [comment]
ممنونم ولی در externalProxy فقط یه مدل کانفیگ میشه تعریف کرد تا حایی که من تست کردم ؟ اگه بیشتر راهنمایی بفرمایید ممنئن میشم

**Comment by alireza0** [comment]
بله.
همونظور که گفتم توی پنل x-ui نمیشه چند مدل مختلف برای یک کاربر ساخت.
ولی چند کاربر رو میشه توی یک ساب با هم آورد. کافیه اسم سابشون یکی باشه.
ولی احتمالا شما محاسبه ترافیک مجموع رو میخواید که این پنل نمیتونه ساپورت کنه

**Comment by BehnamAB** [comment]
خیلی ممنونم از راهنماییتون
