### ISSUE TITLE
جلوگیری از فیلتر شدن سرور

### ISSUE THREAD

**Issue by sadegh1210** [alireza0/x-ui#677]
سا سلام
وقت بخیر
با توجه به اپدیت جدید ، اگر بخواهیم کانفیگ مستقیم بزنیم ، کدوم بخش میتواند بیشترین کمک رو در جلوگیری از فیلتر شدن ایپی سرور به ما بکند؟

**Comment by alireza0** [comment]
درود بر شما
همینطور که دوستمون گفتن هیچ تضمینی نیست که سرور شما فیلتر نشه.
ولی میتونید احتمالش رو با پراکسی معکوس کمتر کنید.

**Comment by sadegh1210** [comment]
امکانش هست در مورد موضوعی که مطرح کردید ، بیشتر توضیح بدهید ؟

**Comment by alireza0** [comment]
لطفا [این راهنما](https://alireza0.github.io/fa/docs/security/) رو مطالعه کنید
