### ISSUE TITLE
اضافه شدن  IP Limit

### ISSUE THREAD

**Issue by leokeuo** [alireza0/x-ui#68]
سلام ممنون از پنل عالیتون
اگر Ip Limit هم اضافه کنید عالی میشه.
کامل ترین پنل x-ui هست ممنون از کاستومایز عالیتون.

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از استفاده و نظراتتون

محدودیت تعداد client بر اساس ip ، توسط خود XTLS/xray نوشته نشده و نیازمند دستکاری و نگهداری اون پکیج هست.
علاوه بر این، راهکار های توسعه داده شده موجود، علاوه بر مشکلات، کارایی سیستم رو متاثر میکنه.

هدف از ارایه این پنل ساده سازی تنظیمات xray-core بوده و اضافه کردن این پیچیدگی ها بیشتر در اصل ماجرا مشکل ایجاد میکنه.

**Comment by alireza0** [comment]
For this porpose, it is better to use [3x-ui](https://github.com/MHSanaei/3x-ui) pannel.
