### ISSUE TITLE
Add graphics option to menu for load balancing 

### ISSUE THREAD

**Issue by Shellgate** [alireza0/x-ui#682]
Hello and courtesy Due to the presence of load balancing in V2ray The possibility of adding this item as a practical item can be effective 

![Screenshot_۲۰۲۳-۱۲-۰۳-۲۳-۱۶-۲۶-۵۷۲_com android chrome](https://github.com/alireza0/x-ui/assets/128194280/cb3c5c9b-2a52-4c79-bf43-bd87c1a94c48)
![Screenshot_۲۰۲۳-۱۲-۰۳-۲۳-۱۶-۴۳-۸۳۰_com android chrome](https://github.com/alireza0/x-ui/assets/128194280/4a33ddd0-0399-48b3-bf6f-ccfb95eb3bdf)

**Comment by alireza0** [comment]
It is already added. Closing the issue...
