### ISSUE TITLE
Panel Error

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#683]
<img width="399" alt="image" src="https://github.com/alireza0/x-ui/assets/117269334/707ea69b-2f81-4af0-860b-368aa6a21669">

با سلام این مشکل چی هست ؟

**Comment by Shellgate** [comment]
کانفیگ تانلتون درست نیست ویرایش کنید یا به صورت دستی از برنامه v2rayng خروجی بگیرید
پیام داخل تصویر هست کانفیگ رو ویرایش و encryption  رو روی none بگزارید و ذخیره و پنل رو ریستارت کنید

**Comment by wulfric93** [comment]
اصن این گزینه encryption رو نداره !
<img width="466" alt="image" src="https://github.com/alireza0/x-ui/assets/117269334/4d902815-20b5-4695-91a0-c9f33a29c983">

**Comment by Shellgate** [comment]
یه نمونه براتون میگزارم ویرایش کنید و در قسمت outbound
کلش رو پاک و جایگزین کنید پیشنهاد میکنم قبل از جایگزاری داخل گوشی یا کامپیوترتان اول ویرایش کنید بعد جایگزین کنید


```go

[
  {
    "mux": {
      "concurrency": 1,
      "enabled": false,
      "xudpConcurrency": 1,
      "xudpProxyUDP443": "skip"
    },
    "protocol": "vless",
    "settings": {
      "vnext": [
        {
          "address": "????????",
          "port": 443,
          "users": [
            {
              "encryption": "none",
              "flow": "",
              "id": "92ca388b-e29a-429f-e288-6e402cfce447",
              "level": 8,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "allowInsecure": false,
        "fingerprint": "firefox",
        "publicKey": "",
        "serverName": "",
        "shortId": "",
        "show": false,
        "spiderX": ""
      },
      "wsSettings": {
        "headers": {
          "Host": ""
        },
        "path": "/??????/"
      }
    },
    "tag": "proxy"
  },
  {
    "tag": "direct",
    "protocol": "freedom",
    "settings": {
      "domainStrategy": "UseIP"
    }
  },
  {
    "tag": "blocked",
    "protocol": "blackhole",
    "settings": {
      "response": {
        "type": "none"
      }
    }
  }
]

```

**Comment by wulfric93** [comment]
> یه نمونه براتون میگزارم ویرایش کنید و در قسمت outbound کلش رو پاک و جایگزین کنید پیشنهاد میکنم قبل از جایگزاری داخل گوشی یا کامپیوترتان اول ویرایش کنید بعد جایگزین کنید
> 
> ```go
> [
>   {
>     "mux": {
>       "concurrency": 1,
>       "enabled": false,
>       "xudpConcurrency": 1,
>       "xudpProxyUDP443": "skip"
>     },
>     "protocol": "vless",
>     "settings": {
>       "vnext": [
>         {
>           "address": "????????",
>           "port": 443,
>           "users": [
>             {
>               "encryption": "none",
>               "flow": "",
>               "id": "??????????",
>               "level": 8,
>               "security": "auto"
>             }
>           ]
>         }
>       ]
>     },
>     "streamSettings": {
>       "network": "ws",
>       "security": "tls",
>       "tlsSettings": {
>         "allowInsecure": false,
>         "fingerprint": "firefox",
>         "publicKey": "",
>         "serverName": "",
>         "shortId": "",
>         "show": false,
>         "spiderX": ""
>       },
>       "wsSettings": {
>         "headers": {
>           "Host": ""
>         },
>         "path": "/??????/"
>       }
>     },
>     "tag": "proxy"
>   },
>   {
>     "tag": "direct",
>     "protocol": "freedom",
>     "settings": {
>       "domainStrategy": "UseIP"
>     }
>   },
>   {
>     "tag": "blocked",
>     "protocol": "blackhole",
>     "settings": {
>       "response": {
>         "type": "none"
>       }
>     }
>   }
> ]
> ```

["{
  "protocol": "vless",
  "settings": {
    "vnext": [
      {
        "address": "bridge.cpndomain.tk",
        "port": 443,
        "users": [
          {
            "id": "a1b5ca40-7c31-40d1-86f4-7c78eba5855d"
          }
        ]
      }
    ]
  },
  "streamSettings": {
    "network": "ws",
    "security": "tls",
    "tlsSettings": {
      "serverName": "bridge.cpndomain.tk",
      "alpn": [],
      "fingerprint": "",
      "allowInsecure": false
    },
    "wsSettings": {
      "path": "/Cyberhunters"
    }
  }
}"
](url)

**Comment by wulfric93** [comment]
> یه نمونه براتون میگزارم ویرایش کنید و در قسمت outbound کلش رو پاک و جایگزین کنید پیشنهاد میکنم قبل از جایگزاری داخل گوشی یا کامپیوترتان اول ویرایش کنید بعد جایگزین کنید
> 
> ```go
> [
>   {
>     "mux": {
>       "concurrency": 1,
>       "enabled": false,
>       "xudpConcurrency": 1,
>       "xudpProxyUDP443": "skip"
>     },
>     "protocol": "vless",
>     "settings": {
>       "vnext": [
>         {
>           "address": "????????",
>           "port": 443,
>           "users": [
>             {
>               "encryption": "none",
>               "flow": "",
>               "id": "??????????",
>               "level": 8,
>               "security": "auto"
>             }
>           ]
>         }
>       ]
>     },
>     "streamSettings": {
>       "network": "ws",
>       "security": "tls",
>       "tlsSettings": {
>         "allowInsecure": false,
>         "fingerprint": "firefox",
>         "publicKey": "",
>         "serverName": "",
>         "shortId": "",
>         "show": false,
>         "spiderX": ""
>       },
>       "wsSettings": {
>         "headers": {
>           "Host": ""
>         },
>         "path": "/??????/"
>       }
>     },
>     "tag": "proxy"
>   },
>   {
>     "tag": "direct",
>     "protocol": "freedom",
>     "settings": {
>       "domainStrategy": "UseIP"
>     }
>   },
>   {
>     "tag": "blocked",
>     "protocol": "blackhole",
>     "settings": {
>       "response": {
>         "type": "none"
>       }
>     }
>   }
> ]
> ```

`"{
  "protocol": "vless",
  "settings": {
    "vnext": [
      {
        "address": "",
        "port": 443,
        "users": [
          {
            "id": ""
          }
        ]
      }
    ]
  },
  "streamSettings": {
    "network": "ws",
    "security": "tls",
    "tlsSettings": {
      "serverName": "",
      "alpn": [],
      "fingerprint": "",
      "allowInsecure": false
    },
    "wsSettings": {
      "path": ""
    }
  }
}"
`
کانفیگ من به این صورت بوده

**Comment by alireza0** [comment]
سپاسگزارم از گزارشتون
لینک ها چند تا مشکل دارند در این نسخه. بهتره بعد از تبدیل لینک حتما از بخش تنظیمات پیشرفته درستش کنید.
برای نسخه بعد درستش میکنم

**Comment by wulfric93** [comment]
سپاس از پیگیری شما

**Comment by wulfric93** [comment]
سلام و عرض ادب 
این مشکل کماکان برقرار هست 
![image](https://github.com/alireza0/x-ui/assets/117269334/6e386ef6-d376-4acc-a996-b7963b1bdc35)

**Comment by alireza0** [comment]
تنظیم قدیمی بوده؟
اوتباند جدید رو یکبار ویرایش و بدون تغییر ذخیره کنید درست میشه

**Comment by wulfric93** [comment]
تلگرام دارید ؟

**Comment by wulfric93** [comment]
این تنظیماتی بوده که قبل از آپدیت پنل داشتم

**Comment by wulfric93** [comment]
لازم به ذکر هست که ربات تلگرام رو طبق آموزش خودتون اوکی کردم

**Comment by wulfric93** [comment]
> تنظیم قدیمی بوده؟ اوتباند جدید رو یکبار ویرایش و بدون تغییر ذخیره کنید درست میشه
وقتی که میخوام ادیت و سیو کنم هم  میگه که تگ بده و وقتی که میدم همون ارور میاد 
![image](https://github.com/alireza0/x-ui/assets/117269334/02b5598c-bab7-44d4-98a0-ebf82f16c49f)

**Comment by alireza0** [comment]
این اوتباند رو پاک کنید و یکبار دیگه انجام بدید.
فیلد های لازم هنوز پر نشدن!

**Comment by wulfric93** [comment]
> این اوتباند رو پاک کنید و یکبار دیگه انجام بدید. فیلد های لازم هنوز پر نشدن!

کدوم فیلد پر نشده ؟

**Comment by alireza0** [comment]
فیلدهایی که اتوماتیک توسط کد میاد.
این خطایی که بعد از آپدیت ارسال کردید مربوط به نسخه قبل بود که روی پورت بعد از تبدیل لینک مشکل داشت.

در هر صورت هر مشکلی که داشته باشه باید بعد از ویرایش و ذخیره حل بشه.
در ضمن فیلد tag الزامیه

**Comment by wulfric93** [comment]
> فیلدهایی که اتوماتیک توسط کد میاد. این خطایی که بعد از آپدیت ارسال کردید مربوط به نسخه قبل بود که روی پورت بعد از تبدیل لینک مشکل داشت.
> 
> در هر صورت هر مشکلی که داشته باشه باید بعد از ویرایش و ذخیره حل بشه. در ضمن فیلد tag الزامیه

اگر تلگرام داشته باشید میتونم باهاتون در ارتباط باشم ؟
ایمیل من این هست 
پنل رو بدم خودتون چک کنید

**Comment by alireza0** [comment]
ایمیل من رو میتونید توی پروفایل گیتهاب ببینید.

**Comment by wulfric93** [comment]
> ایمیل من رو میتونید توی پروفایل گیتهاب ببینید.

میل زدم بهتون
