### ISSUE TITLE
مسدود نشدن سایتهای ایرانی

### ISSUE THREAD

**Issue by mokhtarabdi** [alireza0/x-ui#684]
سلام . من دیشب پنلم رو از سنایی به علیرضا انتقال دادم الان سایتهای ایرانی رو بلاک نمیکنه
تو سنایی بلاک میکرد اما علیرضا بلاک نمیکنه میشه لطف کنید برطرف کنید؟

**Comment by Shellgate** [comment]
![IMG_۲۰۲۳۱۲۰۴_۰۰۳۹۰۵](https://github.com/alireza0/x-ui/assets/128194280/00afbe39-6126-41d4-ad92-0a8f65ac9416)
![IMG_۲۰۲۳۱۲۰۴_۰۰۳۹۴۱](https://github.com/alireza0/x-ui/assets/128194280/9db861bb-71fc-4b34-a3c0-d772f62fa45d)
![IMG_۲۰۲۳۱۲۰۴_۰۰۴۱۰۰](https://github.com/alireza0/x-ui/assets/128194280/eaa63bc4-14e1-40e1-a937-04de5b9074f5)

این موارد رو چک کنید و استراژدی دامنه رو به useip تغیر بدین

**Comment by mokhtarabdi** [comment]
همه اینها رو چک کردم کار نکرد . ربطی به وارپ نداره؟؟

**Comment by alireza0** [comment]
درود بر شما.
اولویت قوانین مهمه. احتمالا مشکلتون اینجا باشه.
وارپ اگر اولویتش پایین تر باشه، بعد از اون چک میشه.

در ضمن یادتون باشه که sniffing رو فعال کنید.

**Comment by mokhtarabdi** [comment]
ممنون حل شد

**Comment by mokhtarabdi** [comment]
ایراد از من بود این صفحه رو کلا پاک کنید . ببخشید اگه اذیتتون کردم و ممنون بابت پاسخگوییتون
