### ISSUE TITLE
accept proxy protocol واسه چیه؟

### ISSUE THREAD

**Issue by r0zbeh** [alireza0/x-ui#685]
accept proxy protocol واسه چیه؟

البته 2 جا هست هم 1-تو صفحه اصلی ساخت اینباند هم 2-در قسمت transparent proxy

**Comment by r0zbeh** [comment]
برای کسایی که مثل من کنجکاو هستن ! تا اون جایی که سرچ کردن این گزینه برای وقتیه که بین پنل و کاربر یک پروکسی مثل انجین کس قرار میگیره . در اون صورت با فعال کردن این گزینه هم در ویورس پروکسی (انجنکیس ) و هم در پنل باعث میشید که پنل بتونه ای پی اصلی و پورت اصلی کسی که درخواست کرده (کلاینت ) رو ببنه ، نه اینکه اطلاعات پروکسی سرور رو دریافت کنه تقریبا شبیه زیر:
کلاینت -----------------> پروکسی ----------------> پنل ایکس ری
البته هنوزم متوجه نشدم چه نیازی به این کار هست و اگر ایکس رو این اطلاعات رو دریافت نکنه چه مشکلی هست!

**Comment by r0zbeh** [comment]
ممنون ، فقط اینکه این اطلاعات فقط شامل پورت و ای پی میشه یا اطلاعات دیگه هم هست ؟ و اگر xray این دوتاروندونه که مشکلی در روند کاریش ایجاد نمیشه ؟!

**Comment by alireza0** [comment]
نه. هدرها اطلاعات بیشتری دارند.
اگر ندونه و محدودش نکرده باشید، در واقع به nginx سرویس میده و کاربر مشکلی حس نمیکنه.
