### ISSUE TITLE
Transparet proxy توضیح

### ISSUE THREAD

**Issue by r0zbeh** [alireza0/x-ui#686]
میشه در مورد این بیشتر توضیح بدین من داکیومنت رو هم خوندم ولی متوجه نشدم !
یعنی کاری میکنه که کانکشن فقط به عنوان gateway هم قابل استفاده بشه؟ بدون اینکه کلاینت ها بخوان چیزی نصب کنن!! 
چطوری میشه از این قابلیت استفاده کرد؟

**Comment by alireza0** [comment]
این ویژگی داخلی xray-core برای ترکیب با پراکسی های دیگه و گرفتن اطلاعات صحیح پکت ها از خارج از xray استفاده میشه.
خود xray گزینه های زیادی داره که من چند تا از به درد بخورترین هاش رو آوردم. ولی خب برای همه کاربرد ها استفاده نمیشه.
حتما باید اطلاعات زیادی در مورد مدیریت شبکه و سیستم لینوکس داشته باشید تا بتونید این بخش ها رو ترکیب کنید.

**Comment by ramtiny** [comment]
منظور از پروکسی اکسترنال چیه
