### ISSUE TITLE
مشکل در ویرایش Advanced Template ها

### ISSUE THREAD

**Issue by Shellgate** [alireza0/x-ui#688]
سلام و عرض ادب و احترام
 

در پنل جدیدتون در بخش Advanced Template 
و به صورت کلی کانفیگ سرور حساسیت رفع اشکال بالا رفته
به گونه ای که در مواردی اجازه ویرایش کانفیگ و outbound
رو نمی‌ده و سریع پاک می‌کنه و این مورد واقعا رو اعصاب هست
در مواردی اصلا نمیشه بهش کد اضافه یا حذف کرد و کلش رو پاک میکنه
در نسخه قبلی این مشکل وجود نداشت

البته با پاک کردن ] رفع اشکال از کا می‌افته و اجازه ویرایش رو میده 
نیازمند برسی هست این مورد
![IMG_۲۰۲۳۱۲۰۴_۰۲۵۰۳۵](https://github.com/alireza0/x-ui/assets/128194280/8344ce9b-fd4b-4168-a975-8d386ae5330a)

**Comment by alireza0** [comment]
درود بر شما

سپاسگزارم از گزارشتون

برای ویرایش این بخش درستش اینه که از قبل کدهاتون آماده باشه و فقط کپی کنید.
تغییراتی که توی این بخش دادم برعکس اون چیزی که میفرمایید رو ازش انتظار دارم.
قبلا این خطاهایی که میفرمایید وجود داشت و الان فقط در صورتی اعمال میشه که کد json درستی باشه.

من مجددا چک میکنم و اگر مشکلی بود تصحیح میکنم

**Comment by Shellgate** [comment]
مرسی و تشکر

**Comment by Shellgate** [comment]
اصلا اجازه هیچ کاری رو بهم نمیده قبلا خیلی بهتر بود

**Comment by Shellgate** [comment]
البته این مشکل بیشتر رو گوشی دیده میشه با کامپیوتر مشکلی مدارم

**Comment by alireza0** [comment]
به نظر میرسه که مشکل بیشتر سنگین بودن اسکریپت نمایش codemirror باشه.
بهتره این مدل دستکاری ها رو با دستگاهی که مشکل نداره انجام بدین.
البته من سبکترین پکیج رو انتخاب کردم و نباید مشکلی باشه. با گوشی هم تست کردم مشکلی نداشت.

**Comment by Shellgate** [comment]
همون طور که گفتین با کامپیوتر ادیت ها رو انجام میدم ولی جاهای هست که نیازه با گوشی انجام یشه مثلا بیرون از خانه من از مرورگر chrome استفاده میکنم گوشی هم پرچم دار هست ولی با این وجود اصلأ اجازه ویرایش یا اضافه کردن کدی رو بهم نمیده

**Comment by alireza0** [comment]
کدهایی که codemirror نشون میدن، توی خودش خطاگیری انجام میشه و این مزیت استفاده از اون بوده.
اگر خطا رو میتونین ببینین برای من بفرستید.
