### ISSUE TITLE
📍 Ip Limit Count 

### ISSUE THREAD

**Issue by iRepix** [alireza0/x-ui#69]
Hey, Can you add ```Ip count limit``` ?
your panel is really good and have nice feature but **"ip count limit"** can make it really better, **thanks**
![IMG_20230315_211327](https://user-images.githubusercontent.com/122776741/225397029-8ef9875c-6da7-4056-bd2e-c727feb6ec2d.jpg)

**Comment by alireza0** [comment]
Hello @iRepix ,
For this porpose, it is better to use [3x-ui](https://github.com/MHSanaei/3x-ui) pannel.

Regards

**Comment by iRepix** [comment]
> Hello @iRepix , For this porpose, it is better to use [3x-ui](https://github.com/MHSanaei/3x-ui) pannel.
> 
> Regards

Ok Thanks.
