### ISSUE TITLE
The API routes differ from the documentation.

### ISSUE THREAD

**Issue by 4erdenko** [alireza0/x-ui#691]
I've noticed that the paths have changed, and in some places, there's something strange being returned. For example, you can get client statistics at the address xui/API/inbounds/.
Also, many other actions like resetClientTraffic, updateClient, addClient are called at the address xui/inbound/, not xui/API/inbounds/.

**Comment by 4erdenko** [comment]
> It is not as same as what you think.
> `/API/inbounds` is an API route only for external usages using api. But in the panel itself, backend is available in another path.
> It is not possible to use `/xui/inbounds` for external calls.

Oh. Okay, so how can i use addClient or something else from external ? When im try xui/API/inbounds it doesn't work.

**Comment by alireza0** [comment]
It is a normal API usage. Here is an example from another developer:
https://github.com/alireza0/x-ui/issues/266
