### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by ghojaei1995** [alireza0/x-ui#692]
سلام در اپدیت جدید وقتی مولتی دامین میزنیم و با سابسکراپیشن رو به یوزر میدیم چیکار باید کنیم تا اون اسم اینباند اصلی رو برای یوزر نشون نده( فقط اسم خود یوزر و اسم هر دامین براش نشون بده)
چون اسم اون اینباند اصلی هم نشون میده خیلی شلوغ میشه

**Comment by alireza0** [comment]
دقیقا به همین روشی که روزبه عزیز گفتن طراحی شده.
ریمارک های اینباند-کاربر-پراکسی با هم جمع میشن و هرکدوم خالی باشه حذف میشه

**Comment by alireza0** [comment]
اون اسمی که میفرمایید در واقع remark بوده و نه اسم. توی این پنل اسم برای اینباند نداریم.
نمیشه پنل رو به سلیقه یه عده تنظیم کرد. این راه حلی که ارائه شده همه مدل ها رو ساپورت میکنه. 

> یک مورد باگ هم در اپدیت جدید امروز متوجه شدم قسمت سرچ یوزرها در پنل بعد اپدیت کار نمیکنه

اگر مثل #698 شما هم از پنل ثنایی منتقل شدید، راه کاری که اونجا نوشتم رو امتحان کنید.

**Comment by alireza0** [comment]
اینباند رو ویرایش و ذخیره کنید. اصولا حل میشه.
در ضمن در حال کار روی پنل ثنایی به همراه خود ایشون هستیم. احتمالا طی همین چند روز بروزرسانی انجام میشه.
ولی لطفا تا قبل از بروزرسانی ایشون، پنلتون رو منتقل نکنید.
معمولا بعد از انتقال بین پنل ها ممکنه به این مشکل بخورید که در هر صورت با راه حلی که گفتم حل میشه
