### ISSUE TITLE
اپدیت اخر

### ISSUE THREAD

**Issue by Saeedroshan1906** [alireza0/x-ui#693]
سلام به علیرضای عزیز واقعا اپدیت اخر خیلی حرفه ای شده و اینکه رول ها و خروجی ها رو میشه تنظیم کرد فوق‌العاده شده به جرات میشه گفت قویترین پنل x-ui هست .

**Comment by Saeedroshan1906** [comment]
فقط یک موردی علیرضا جان گزینه domain name توی تنظیمات نیست دیگه مثلا میخوایم از یک دامنه دیگه استفاده بشه برای روش دکودومودور باید به چه صورت انجام بدیم ؟

**Comment by alireza0** [comment]
مولتی دامین و نام سرور حذف شده و به جاش externalProxy رو گذاشتیم.
خوبیش اینه که روی همه اینباندها قابل استفاده است و محدود به tls نیست

**Comment by Saeedroshan1906** [comment]
بسیار عالی فقط من الان روی نوع همسان گذاشتم و جواب گرفتم سپاس از جوابگوییت
