### ISSUE TITLE
تغییر پورت ربات

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#694]
وقتی بخواییم از ربات در سرور ایران از ربات استفاده کنیم باید در اینباند تغییراتی بدیم 
اگر پورت443 در سرور مشغول باشه و توسط سرویس استفاده بشه چون برنامه های تانل و یا چیزهای دیگه ربات کار نمیکنه و پنل ارور میخوره  امکان تغییر پورت مورد استفاده tgbot به پورتی غیر 443 هست؟
امکانش هست در آپدیتهای بعدی امکان تغییر این پورت در پنل گنجانده بشه؟
پورت خروجی 443 باشه حتی در صورت استفاده یک سرویس دیگر مشکلی نیست اما پورت ورودی حتما باید غیر این پورت باشه.
ممنون

**Comment by alireza0** [comment]
پورت توی پنل x-ui استفاده پایه ای داره و نمیشه به راحتی عوضش رد.
بهتره برای ربات تلگرام از یک اینباند توی تنظیمات ایکس‌ری استفاده کنید.

**Comment by alireza0** [comment]
اگر تنظیم دیگری روی این پورت دارید اون رو به آدرس IP سرور محدود کنید.
اگر بخش آدرس در اینباند خالی باشه، همه آدرس ها از جمله loopback ها رو اشغال میکنه و نمیتونید دیگه روی اون پورت سرویس دیگه ای داشته باشید.

**Comment by aliamg1356** [comment]
قضیه از این قرار رو سرور خارج پنل x-ui و سافت اتر وصله و پورت 443 برای سافت اتر استفاده میشه با این وجود ربات در پنل کار میکنه
در سرور ایران هم  پنل xui و سافت اتر نصبه و پورت 443 برای سافت اتر استفاده میشه.وقتی اینابند میسازم و پورت 443 رو به سمت آی پی 127.0.0.43 فوروارد میکنم پنل به ارور میخوره

**Comment by alireza0** [comment]
اگر نمیتونید نرم افزار دیگه رو روی یک آدرس محدود کنید، بهتره شما از راه حل دیگه ای برای حل مشکل تلگرام استفاده کنید.
