### ISSUE TITLE
How to config?

### ISSUE THREAD

**Issue by mesmaili151** [alireza0/x-ui#696]
Hi guys,
I wanted to ask if anyone knows the best settings for this panel?
I want to run the script, but i've seen there are lots of topics in general and settings on the internet about this panel that confuse me.

I appreciate any help.

**Comment by r0zbeh** [comment]
Where does he live ? For what purpose do you want to use it?

**Comment by r0zbeh** [comment]
> They are in Iran. And i want to set it up for my friends and family

its depend to which internet provider they use :
Irancel :vless+websocket+tls
Hamrah Aval : You should use two server and use Tunneling(iran vps+outside vps)/or you can use vless+tcp+Reality but you need un filtered SNI 
ADSL & Rightel: you can use Irancell method for other provides

**Comment by mesmaili151** [comment]
Thanks, i was wondering if there is any good video to how to tunnel actually and set it with the panel

**Comment by r0zbeh** [comment]
[for tunneling iran -> out of Iran ](https://www.youtube.com/watch?v=Vxrxkc5KnDc)
