### ISSUE TITLE
مشکل سرچ

### ISSUE THREAD

**Issue by sadeghbb** [alireza0/x-ui#698]
سلام
تو اپدیت اخر مشکل سرچ دارم
هر یوزری رو سرچ میکنم پیدا نمیکنه
مگه اینباندهای قدیمی
ممنون میشم چک کنید

**Comment by sadeghbb** [comment]
> درود بر شما اگر از گزینه جستجو توی بخش اینباند ها این کار رو انجام میدین، هیچ تغییری نکرده و همه کاربرها رو جستجو میکنه.

تشکر
ولی برا من روی یه اینباند به مشکل خورده
بقیه اینباندهارو سرچ میزنه ولی رو این هیچ یوزری رو پیدا نمیکنه
بتازگی هم از پنل ثنایی به پنل شما اومدم
دو سه روز اوکی بود
بکباره سرچ اون اینباند به مشکل خورد !
فقط یوزر های اون اینباند رو الان پیدا نمیکنه چک کردم
امکانش هست راهنمایی کنید

**Comment by alireza0** [comment]
میتونید یکبار اینباند رو ویرایش و ذخیره کنید. احتمالا درست میشه.
در حال کار روی پنل ثنایی هستیم. همه آپدیت ها رو اونطرف بزودی دارین. ولی لطفا منتظر نسخه جدید اون پنل باشید و قبل از اون انتقال ندید.

**Comment by alireza0** [comment]
پنل هایی که تست کردم هیچکدوم مشکلی نداشتن. مولتی دامین هم داشتن.
راه حلی که دادم رو تست کنید و نتیجه رو به من اعلام کنید

**Comment by sadeghbb** [comment]
> میتونید یکبار اینباند رو ویرایش و ذخیره کنید. احتمالا درست میشه. در حال کار روی پنل ثنایی هستیم. همه آپدیت ها رو اونطرف بزودی دارین. ولی لطفا منتظر نسخه جدید اون پنل باشید و قبل از اون انتقال ندید.

انجام دادم قبلا وای اوکی نشد
نمیدونم مشکل از چیه
اینباندهای جدید یسری اوکیه یسری نه
قدیمیا اوکیه کامل
حتی به اسپیس و فاصله اینام دقت کردم ولی نتیجه ای نداشت

**Comment by BehnamAB** [comment]
سلام منم دقیقا هم روی سنایی هم علیرضا این مشکل و دارم

**Comment by alireza0** [comment]
وقتی جستجو میکنید خطایی توی بخش کنسول مرورگر نیست؟

**Comment by alireza0** [comment]
توی گوشی نمیشه خطای کنسول رو دید.
باید با کامپیوتر کنسول بخش developer mode رو چک کنید.
من چون خطایی تا الان ندیدم نمیتونم چک کنم که خطا از کجاست!

**Comment by Shellgate** [comment]
دوست عزیز هنگام جستجو یا وارد کردن نام طرف مممنه جاهای خالی اضافه اضافه بشن که دیده نمیشه بعد از نوشتن اسم فرد یک بار گزینه برگشت یا پاک کردن رو بزنید درست میشه

**Comment by sadeghbb** [comment]
> توی گوشی نمیشه خطای کنسول رو دید. باید با کامپیوتر کنسول بخش developer mode رو چک کنید. من چون خطایی تا الان ندیدم نمیتونم چک کنم که خطا از کجاست!

Failed to load resource: the server responded with a status of 404 ()
utils.js?1.6.1:180 

Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at ObjectUtil.deepSearch (utils.js?1.6.1:180:24)
    at ObjectUtil.deepSearch (utils.js?1.6.1:175:26)
    at inbounds:1098:52
    at Array.forEach (<anonymous>)
    at inbounds:1097:57
    at Array.forEach (<anonymous>)
    at wn.searchInbounds (inbounds:1091:37)
    at wn.<anonymous> (inbounds:1657:22)
    at common.js?1.6.1:68:16
5utils.js?1.6.1:180 

Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at ObjectUtil.deepSearch (utils.js?1.6.1:180:24)
    at ObjectUtil.deepSearch (utils.js?1.6.1:175:26)
    at inbounds:1098:52
    at Array.forEach (<anonymous>)
    at inbounds:1097:57
    at Array.forEach (<anonymous>)
    at wn.searchInbounds (inbounds:1091:37)
    at wn.<anonymous> (inbounds:1657:22)
    at common.js?1.6.1:68:16



تایپ دستی و کپی پیس بدون فاصله ولی موردی یافت نمیشه از یوزرها !

**Comment by alireza0** [comment]
آیا شما از نرم افزارهای دیگه که با api پنل کار میکنند استفاده میکنید؟
این خطاها مربوط به پارامترهایی میشه که به درستی در دیتابیس ذخیره نشدن.
خیلی از این نرم افزارها با نسخه های جدید پنل سازگار نیستند!

به هر حال مشکل رو تقریبا متوجه شدم و سعی میکنم توی نسخه بعد درستش کنم.

**Comment by alireza0** [comment]
بر اساس گزارش شما، خطا زمانی بوجود میاد که یک شیئ با مقدار null در تنظیمات وجود داشته باشه.
این مورد در پنل هایی که از جای دیگه دستکاری نمیشن نباید وجود داشته باشه.
ولی به هرحال تغییرات لازم برای هندلینگ این خطا انجام شده.

**Comment by wulfric93** [comment]
سلام 
من هم همین مشکل رو دارم

**Comment by alireza0** [comment]
> گفتین در اپدیت جدید ربات با چت ایدی هم یوزر تشخیص میده و کار میکنه ولی متاسفانه کار نمیکنه

شما باید chatID رو به درستی توی بخش telegram id اون کاربر بذارید. مشکلی نداره.

> این سری نمیدوم چرا باگ ها اینقدر زیادن😐

کدوم باگ ها رو منظورتونه ؟

> تنظیمات xray من الان اینطوریه ایراد داره که همه مشکل بوجود میاد؟

این بخش مربوط به تنظیمات الگوی xray میشه و منظور من از تنظیمات اینباند ها، دقیقا اطلاعات پشت صحنه در صفحه inbounds بود.
به هرحال مشکل گزینه جستحو در نسخه بعد حل میشه.

**Comment by sadeghbb** [comment]
> بر اساس گزارش شما، خطا زمانی بوجود میاد که یک شیئ با مقدار null در تنظیمات وجود داشته باشه. این مورد در پنل هایی که از جای دیگه دستکاری نمیشن نباید وجود داشته باشه. ولی به هرحال تغییرات لازم برای هندلینگ این خطا انجام شده.
درود
امکان داشته باشه باگ سرچ رو براش یه اپدیت فوریتی بدین ممنون میشیم
چون خیلی اذیت کنندست سرچ دستی 
تشکر

**Comment by wulfric93** [comment]
مشکل حل شد 
سپاس بیکران
