### ISSUE TITLE
قوانین مسیریابی

### ISSUE THREAD

**Issue by hasan4643** [alireza0/x-ui#702]
سلام خسته نباشین قسمت قوانین مسیریابی چه کاری انجام میده و اموزشی براش وجود داره؟

**Comment by alireza0** [comment]
درود بر شما
این بخش از اول ایجاد v2ray وجود داشته و الان توی این پنل براش بخش گرافیکی اضاقه در نظر گرفته شده.
آموزش هاش به صورت سنتی (json) و توی اسناد خود xtls و v2fly وجود داره
