### ISSUE TITLE
محدودیت کاربر

### ISSUE THREAD

**Issue by AminMXs** [alireza0/x-ui#704]
سلام اگر امکانش هست قابلیت تک کاربره کردن یا همون محدودیت کاربر هم به پنل اضافه کنید مثل سنایی همون fail2ban چیزی مشابه اون یا بهتر از اون خیلی خوب میشه خیلی نیازه اگر میشه هرچی سریع تر یه اپدیت بدید و این اضافه بشه خیلی ممنون

**Comment by alireza0** [comment]
درود بر شما
لطفا قبل از ایجاد ایشو، ایشو های قبل رو جستجو کنید تا از ایجاد پیشنهاد تکراری جلوگیری بشه.
این قابلیت به این پنل اضافه نخواهد شد. لطفا برای استفاده از این قابلیت ها از پنل ثنایی استفاده کنید.

سپاسگزارم

**Comment by AminMXs** [comment]
میتونم بدونم به چه علت اضافه نمیشه>؟
