### ISSUE TITLE
Questions about routing rules

### ISSUE THREAD

**Issue by MiniKoro** [alireza0/x-ui#717]
Add routing rules in the routing rules interface and restart xray will fail. The generated routing rules seem to have no type attribute. I don't know if this is the problem?

**Comment by MiniKoro** [comment]
Sorry, I don't understand the language in the issue. I don't know if anyone has the same problem as me, so I can only add a new issue.

**Comment by MiniKoro** [comment]
..... Well, you can add attributes manually

**Comment by Enkidu-6** [comment]
The error seem to be localization related. Change the language to English and see if those errors still appear.

It looks like you're running a socks VPN on Docker? If that's the case, are you sure you're pointing your routing rules to the correct IP address? 

To see which address port 1080 is listening on type:
```
netstat -tunlp
```

**Comment by i-Eureka** [comment]
> The error seem to be localization related. Change the language to English and see if those errors still appear.
> 
> It looks like you're running a socks VPN on Docker? If that's the case, are you sure you're pointing your routing rules to the correct IP address?
> 
> To see which address port 1080 is listening on type:
> 
> ```
> netstat -tunlp
> ```

I tested socks5 in the x-ui container, and it seems to be able to communicate normally. But when accessing icanhazip.com in the routing rules generated by x-ui, the socks5 proxy is still not used.
`root@ip-172-26-2-164:~# docker exec -it x-ui sh
/app # curl -x 'socks5://172.18.0.2:1080' -k -v --resolve icanhazip.com:443:104.18.114.97 https://icanhazip.com
* Added icanhazip.com:443:104.18.114.97 to DNS cache
*   Trying 172.18.0.2:1080...
* Connected to 172.18.0.2 (172.18.0.2) port 1080
* Hostname icanhazip.com was found in DNS cache
* SOCKS5 connect to 104.18.114.97:443 (locally resolved)
* SOCKS5 request granted.
* Connected to 172.18.0.2 (172.18.0.2) port 1080
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Apr  7 00:00:00 2023 GMT
*  expire date: Apr  6 23:59:59 2024 GMT
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://icanhazip.com/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: icanhazip.com]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: icanhazip.com
> User-Agent: curl/8.5.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200 
< date: Sat, 09 Dec 2023 05:07:45 GMT
< content-type: text/plain
< content-length: 15
< access-control-allow-origin: *
< access-control-allow-methods: GET
< set-cookie: __cf_bm=ZArSS44lXIW7GJjHms85XRSnRLRCwBxyaJgzKv_UPNY-1702098465-0-AXepuUw59OIgcXkowM+bT0dcazKm1U0DEtDOcvwFGfsju90ymUpZR28F8QYdrH6wkmMtzSirU04dg62Y2f5bXmw=; path=/; expires=Sat, 09-Dec-23 05:37:45 GMT; domain=.icanhazip.com; HttpOnly; Secure; SameSite=None
< server: cloudflare
< cf-ray: 832ab9f44c7bdee7-NRT
< alt-svc: h3=":443"; ma=86400
< 
149.50.210.208
* Connection #0 to host 172.18.0.2 left intact
`

**Comment by i-Eureka** [comment]
This is the routing configuration for 3x-ui, but it's not in a docker `container.
```
{
  "log": {
    "loglevel": "warning",
    "access": "./access.log",
    "error": "./error.log"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "inbounds": [
    {
      "tag": "api",
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv6"
      },
      "tag": "IPv6-out"
    },
    {
      "tag": "ToVPN",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    },
    {
      "tag": "IPv4",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "domain": [
          "geosite:twitter",
          "geosite:openai",
          "geosite:spotify",
          "geosite:yandex"
        ],
        "outboundTag": "IPv6-out"
      },
      {
        "type": "field",
        "outboundTag": "ToVPN",
        "domain": [
          "geosite:cn",
          "regexp:.*\\.cn$",
          "geosite:netflix",
          "icanhazip.com"
        ]
      },
      {
        "type": "field",
        "outboundTag": "ToVPN",
        "ip": [
          "geoip:cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ]
      },
      {
        "type": "field",
        "outboundTag": "IPv4",
        "domain": [
          "geosite:google"
        ]
      }
    ]
  },
  "stats": {}
}
```

**Comment by i-Eureka** [comment]
This is the routing configuration of 3x-ui. Its configuration can be distributed normally, but it is not in the docker container. The socks5 proxy server is still in the docker container, and the port mapping is 40000
```
{
  "log": {
    "loglevel": "warning",
    "access": "./access.log",
    "error": "./error.log"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "inbounds": [
    {
      "tag": "api",
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv6"
      },
      "tag": "IPv6-out"
    },
    {
      "tag": "ToVPN",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    },
    {
      "tag": "IPv4",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "domain": [
          "geosite:twitter",
          "geosite:openai",
          "geosite:spotify",
          "geosite:yandex"
        ],
        "outboundTag": "IPv6-out"
      },
      {
        "type": "field",
        "outboundTag": "ToVPN",
        "domain": [
          "geosite:cn",
          "regexp:.*\\.cn$",
          "geosite:netflix",
          "icanhazip.com"
        ]
      },
      {
        "type": "field",
        "outboundTag": "ToVPN",
        "ip": [
          "geoip:cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ]
      },
      {
        "type": "field",
        "outboundTag": "IPv4",
        "domain": [
          "geosite:google"
        ]
      }
    ]
  },
  "stats": {}
}
```
