### ISSUE TITLE
ارور پنل در هنگام استفاده از اوتباند با vless

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#718]
در هنگام استفاده از اوتباند با پروتکل vless پنل به خطا میخوره  
Xray 1.8.6 (Xray, Penetrates Everything.) Custom (go1.21.4 linux/amd64)

A unified platform for anti-censorship.

2023/12/07 22:29:21 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: failed to parse to outbound detour config. > json: cannot unmarshal string into Go struct field VLessOutboundVnext.vnext.port of type uint16

**Comment by alireza0** [comment]
درود بر شما
بله این باگ شناخته شده است و به همراه https://github.com/alireza0/x-ui/issues/683 تصحیح شد.
این مشکل در زمان تبدیل لینک بوجود میاد. میتونید یکبار به تب فرم مراجعه کنید و پورت رو تغییر بدید تا درست بشه.
منتظر نسخه بعد باشید.
