### ISSUE TITLE
UDID/Password Column 

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#719]
با سلام و عرض ادب 
ممنون میشم اگر که مثل پنل 
https://github.com/sudospaes/x-ui
ستونی برای UDID/Password  توی آپدیت بعدی لحاظ کنید 
<img width="956" alt="image" src="https://github.com/alireza0/x-ui/assets/117269334/f0f90427-d33e-4f11-83e4-30bf1e212ec9">

**Comment by alireza0** [comment]
درود بر شما
این مدل در واقع نسخه قدیمی x-ui محسوب میشه. نسخه های پایین تر از 1.6.0 همین شکل بودن.
دلیلی به اشغال صفحه با این پارامتر نداریم.
این پنل جزو اولین پنل هایی بود که کاربر ها رو به این شکل نشون داد واین اطلاعات رو از سر کمبود اطلاعات قابل نمایش گذاشتم.

برای نمایش در گوشی همراه و همچنین ارائه صفحه سبکتر حذف شد.
شما میتونید همچنان این اطلاعات رو با کلید روی تگ `اطلاعات بیشتر` مشاهده کنید.

سپاسگزارم
