### ISSUE TITLE
درخواست چند ویژگی جدید

### ISSUE THREAD

**Issue by straymail** [alireza0/x-ui#72]
سلام

بنده بتازگی پنل جناب سنایی را نصب کردم و از کانال تلگرام ایشان صفحه شما را دیدم.

احتراما چند پیشنهاد خدمت شما گرامی دارم که لطفا در 3x-ui هم منتشر شود.

1- لطفا کلاینت هایی که در حال اتمام حجم یا زمان هستند به شکلی مثلا با رنگ زرد نمایش داده شوند. (مثلا کلاینت های کمتر از 2 گیگ حجم یا 5 روز مانده به پایان اعتبار)

2- حجم مصرفی هر کلاینت پس از یک ماه از زمان شروع مصرف حجم آن بصورت خودکار ریسیت شود.
( ریسیت یک ماه پس از شروع مصرف حجم از این جهت اهمیت دارد که همه کلاینت ها با هم ریسیت نشوند )
( یا بعضی تعدادی کلاینت از قبل ساخته و آماده می کنند ولی هنوز تحویل کاربر داده نشده پس ملاک ریسیت شدن، زمان ساخته شدن کلاینت نباشد)

3- دو دکمه کنار کیوآرکدها قرار داده شود که با هربار زدن آن یک ماه به اعتبار کلاینت اضافه یا کم شود.

4- دکمه غیر فعال کردن هر کلاینت کنار کیوآرکد وجود داشته باشد.

با سپاس

**Comment by shahrooz1349** [comment]
@alireza0 
درود و عرض خسته نباشید بابت توسعه عالی از این پنل
علیرضای عزیز اگر امکان دارد و مشکلی در دیتابیس ایجاد نمیشود امکان ایجاد یوزر گروهی فقط با اعداد پشت سرهم بدون ایمیل رندم را نیز فراهم بفرمایید
با احترام 🙏🌹

**Comment by alireza0** [comment]
درود بر شما
@straymail 
۱. با استفاده از بات تلگرام میتونید این گزارش رو به صورت دوره ای بگیرید
۲. پیچیدگی این کار خارج از هدف این پنل بوده و وظیقه نرم افزار های اکانتینگ محسوب میشه.
۳. اضافه کردن یکماه رو به راحتی در قسمت ویرایش میتونید انجام بدید. 
۴. غیرفعال کردن کلاینت در این سیستم اتوماتیک انجام میشه. پیشنهاد من تغییر زمان اعتبار کاربر به زمان گذشته است.

@shahrooz1349 
چشم، ولی اصلا توصیه نمیکنم!
