### ISSUE TITLE
چندین هدر

### ISSUE THREAD

**Issue by ghojaei1995** [alireza0/x-ui#720]
سلام وقت بخیر اگه بخواهیم چند هدر بزنیم طبق کدوم تصویر بزنیم درست عمل میکنه
![Screenshot_۲۰۲۳۱۲۰۸_۰۲۲۱۲۵_Chrome](https://github.com/alireza0/x-ui/assets/97450649/1d0ea98a-5a3e-4239-a3f8-0105c08a5f49)
![Screenshot_۲۰۲۳۱۲۰۸_۰۲۲۰۴۱_Chrome](https://github.com/alireza0/x-ui/assets/97450649/a13061d7-6f24-475e-b097-897709b70d1f)

**Comment by alireza0** [comment]
درود بر شما
دومی درسته. هر خط یک مقدار.
ولی این کارکمکی به شما نمیکنه. چون درخواست نرمال وب یک هاست بیشتر نداره.
هدر هاست فقط یکی از هدرهاییه که میتونید بذارید. متاسفانه نرم افزار های سمت کاربر فقط همین هدر رو ساپورت میکنن.
