### ISSUE TITLE
auto restart the xray core

### ISSUE THREAD

**Issue by adamgonglj** [alireza0/x-ui#721]
I am using x-ui as a transparent proxy managing panel.

I just found that the xray core will restart every 11-13 seconds. 

could you remove this kind of logic? set it as an optional function, auto restart xray core or not.

**Comment by alireza0** [comment]
There is no such a function.
Please check your configuration which causes crash on xray.

**Comment by adamgonglj** [comment]
Dec 08 18:36:49 router x-ui[1445]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:36:49 router x-ui[1445]:         panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:36:49 router x-ui[1445]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab66d7]
Dec 08 18:36:49 router x-ui[1445]: goroutine 151 [running]:
Dec 08 18:36:49 router x-ui[1445]: google.golang.org/grpc.(*ClientConn).Close.func1()
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1252 +0x17
Dec 08 18:36:49 router x-ui[1445]: panic({0x1518d20?, 0x2f6d750?})
Dec 08 18:36:49 router x-ui[1445]:         /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
Dec 08 18:36:49 router x-ui[1445]: google.golang.org/grpc.(*ClientConn).Close(0x0)
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1256 +0x6c
Dec 08 18:36:49 router x-ui[1445]: x-ui/xray.(*XrayAPI).Close(...)
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/work/x-ui/x-ui/xray/api.go:52
Dec 08 18:36:49 router x-ui[1445]: x-ui/web/service.(*InboundService).disableInvalidClients(0xc0000de158, 0x0?)
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/work/x-ui/x-ui/web/service/inbound.go:962 +0x3a7
Dec 08 18:36:49 router x-ui[1445]: x-ui/web/service.(*InboundService).AddTraffic(0xc000bfec00?, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/work/x-ui/x-ui/web/service/inbound.go:657 +0x24d
Dec 08 18:36:49 router x-ui[1445]: x-ui/web/service.(*XrayService).GetXrayConfig(0xc0000de158)
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/work/x-ui/x-ui/web/service/xray.go:72 +0xba
Dec 08 18:36:49 router x-ui[1445]: x-ui/web/service.(*XrayService).RestartXray(0xc00084ff80?, 0x0)
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/work/x-ui/x-ui/web/service/xray.go:181 +0xda
Dec 08 18:36:49 router x-ui[1445]: x-ui/web.(*Server).startTask.func1()
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/work/x-ui/x-ui/web/web.go:246 +0x45
Dec 08 18:36:49 router x-ui[1445]: github.com/robfig/cron/v3.FuncJob.Run(0x305a680?)
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x12
Dec 08 18:36:49 router x-ui[1445]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x5b
Dec 08 18:36:49 router x-ui[1445]: created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 10
Dec 08 18:36:49 router x-ui[1445]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xa5
Dec 08 18:36:49 router systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 08 18:36:49 router systemd[1]: x-ui.service: Failed with result 'exit-code'.
Dec 08 18:36:49 router systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 6.
Dec 08 18:36:49 router systemd[1]: Stopped x-ui Service.
Dec 08 18:36:49 router systemd[1]: Started x-ui Service.
Dec 08 18:36:49 router x-ui[1633]: 2023/12/08 18:36:49 x-ui 1.6.1
Dec 08 18:36:49 router /usr/local/x-ui/x-ui[1633]: INFO - web server run http on [::]:9923
Dec 08 18:37:04 router x-ui[1633]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:37:04 router x-ui[1633]:         panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:37:04 router x-ui[1633]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab66d7]
Dec 08 18:37:04 router x-ui[1633]: goroutine 16 [running]:
Dec 08 18:37:04 router x-ui[1633]: google.golang.org/grpc.(*ClientConn).Close.func1()
Dec 08 18:37:04 router x-ui[1633]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1252 +0x17
Dec 08 18:37:04 router x-ui[1633]: panic({0x1518d20?, 0x2f6d750?})
Dec 08 18:37:04 router x-ui[1633]:         /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
Dec 08 18:37:04 router x-ui[1633]: google.golang.org/grpc.(*ClientConn).Close(0x0)
Dec 08 18:37:04 router x-ui[1633]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1256 +0x6c
Dec 08 18:37:04 router x-ui[1633]: x-ui/xray.(*XrayAPI).Close(0xc000794380)
Dec 08 18:37:04 router x-ui[1633]:         /home/runner/work/x-ui/x-ui/xray/api.go:52 +0x1f
Dec 08 18:37:04 router x-ui[1633]: x-ui/web/service.(*XrayService).GetXrayTraffic(0xc000062fb8?)
Dec 08 18:37:04 router x-ui[1633]:         /home/runner/work/x-ui/x-ui/web/service/xray.go:173 +0x106
Dec 08 18:37:04 router x-ui[1633]: x-ui/web/job.(*XrayTrafficJob).Run(0xc000794360)
Dec 08 18:37:04 router x-ui[1633]:         /home/runner/work/x-ui/x-ui/web/job/xray_traffic_job.go:22 +0x5e
Dec 08 18:37:04 router x-ui[1633]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Dec 08 18:37:04 router x-ui[1633]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x5b
Dec 08 18:37:04 router x-ui[1633]: created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 34
Dec 08 18:37:04 router x-ui[1633]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xa5
Dec 08 18:37:04 router systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 08 18:37:04 router systemd[1]: x-ui.service: Failed with result 'exit-code'.
Dec 08 18:37:04 router systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 7.
Dec 08 18:37:04 router systemd[1]: Stopped x-ui Service.
Dec 08 18:37:04 router systemd[1]: Started x-ui Service.
Dec 08 18:37:04 router x-ui[1780]: 2023/12/08 18:37:04 x-ui 1.6.1
Dec 08 18:37:04 router /usr/local/x-ui/x-ui[1780]: INFO - web server run http on [::]:9923
Dec 08 18:37:19 router x-ui[1780]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:37:19 router x-ui[1780]:         panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:37:19 router x-ui[1780]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab66d7]
Dec 08 18:37:19 router x-ui[1780]: goroutine 51 [running]:
Dec 08 18:37:19 router x-ui[1780]: google.golang.org/grpc.(*ClientConn).Close.func1()
Dec 08 18:37:19 router x-ui[1780]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1252 +0x17
Dec 08 18:37:19 router x-ui[1780]: panic({0x1518d20?, 0x2f6d750?})
Dec 08 18:37:19 router x-ui[1780]:         /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
Dec 08 18:37:19 router x-ui[1780]: google.golang.org/grpc.(*ClientConn).Close(0x0)
Dec 08 18:37:19 router x-ui[1780]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1256 +0x6c
Dec 08 18:37:19 router x-ui[1780]: x-ui/xray.(*XrayAPI).Close(0xc000a82020)
Dec 08 18:37:19 router x-ui[1780]:         /home/runner/work/x-ui/x-ui/xray/api.go:52 +0x1f
Dec 08 18:37:19 router x-ui[1780]: x-ui/web/service.(*XrayService).GetXrayTraffic(0x12d9179?)
Dec 08 18:37:19 router x-ui[1780]:         /home/runner/work/x-ui/x-ui/web/service/xray.go:173 +0x106
Dec 08 18:37:19 router x-ui[1780]: x-ui/web/job.(*XrayTrafficJob).Run(0xc000a82000)
Dec 08 18:37:19 router x-ui[1780]:         /home/runner/work/x-ui/x-ui/web/job/xray_traffic_job.go:22 +0x5e
Dec 08 18:37:19 router x-ui[1780]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Dec 08 18:37:19 router x-ui[1780]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x5b
Dec 08 18:37:19 router x-ui[1780]: created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 9
Dec 08 18:37:19 router x-ui[1780]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xa5
Dec 08 18:37:19 router systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 08 18:37:19 router systemd[1]: x-ui.service: Failed with result 'exit-code'.
Dec 08 18:37:19 router systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 8.
Dec 08 18:37:19 router systemd[1]: Stopped x-ui Service.
Dec 08 18:37:19 router systemd[1]: Started x-ui Service.
Dec 08 18:37:19 router x-ui[1806]: 2023/12/08 18:37:19 x-ui 1.6.1
Dec 08 18:37:19 router /usr/local/x-ui/x-ui[1806]: INFO - web server run http on [::]:9923
Dec 08 18:37:34 router x-ui[1806]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:37:34 router x-ui[1806]:         panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:37:34 router x-ui[1806]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab66d7]
Dec 08 18:37:34 router x-ui[1806]: goroutine 44 [running]:
Dec 08 18:37:34 router x-ui[1806]: google.golang.org/grpc.(*ClientConn).Close.func1()
Dec 08 18:37:34 router x-ui[1806]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1252 +0x17
Dec 08 18:37:34 router x-ui[1806]: panic({0x1518d20?, 0x2f6d750?})
Dec 08 18:37:34 router x-ui[1806]:         /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
Dec 08 18:37:34 router x-ui[1806]: google.golang.org/grpc.(*ClientConn).Close(0x0)
Dec 08 18:37:34 router x-ui[1806]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1256 +0x6c
Dec 08 18:37:34 router x-ui[1806]: x-ui/xray.(*XrayAPI).Close(0xc00089d7c0)
Dec 08 18:37:34 router x-ui[1806]:         /home/runner/work/x-ui/x-ui/xray/api.go:52 +0x1f
Dec 08 18:37:34 router x-ui[1806]: x-ui/web/service.(*XrayService).GetXrayTraffic(0x493493?)
Dec 08 18:37:34 router x-ui[1806]:         /home/runner/work/x-ui/x-ui/web/service/xray.go:173 +0x106
Dec 08 18:37:34 router x-ui[1806]: x-ui/web/job.(*XrayTrafficJob).Run(0xc00089d7a0)
Dec 08 18:37:34 router x-ui[1806]:         /home/runner/work/x-ui/x-ui/web/job/xray_traffic_job.go:22 +0x5e
Dec 08 18:37:34 router x-ui[1806]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Dec 08 18:37:34 router x-ui[1806]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x5b
Dec 08 18:37:34 router x-ui[1806]: created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 22
Dec 08 18:37:34 router x-ui[1806]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xa5
Dec 08 18:37:34 router systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 08 18:37:34 router systemd[1]: x-ui.service: Failed with result 'exit-code'.
Dec 08 18:37:34 router systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 9.
Dec 08 18:37:34 router systemd[1]: Stopped x-ui Service.
Dec 08 18:37:34 router systemd[1]: Started x-ui Service.
Dec 08 18:37:34 router x-ui[1831]: 2023/12/08 18:37:34 x-ui 1.6.1
Dec 08 18:37:34 router /usr/local/x-ui/x-ui[1831]: INFO - web server run http on [::]:9923
Dec 08 18:37:49 router x-ui[1831]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:37:49 router x-ui[1831]:         panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:37:49 router x-ui[1831]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab66d7]
Dec 08 18:37:49 router x-ui[1831]: goroutine 56 [running]:
Dec 08 18:37:49 router x-ui[1831]: google.golang.org/grpc.(*ClientConn).Close.func1()
Dec 08 18:37:49 router x-ui[1831]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1252 +0x17
Dec 08 18:37:49 router x-ui[1831]: panic({0x1518d20?, 0x2f6d750?})
Dec 08 18:37:49 router x-ui[1831]:         /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
Dec 08 18:37:49 router x-ui[1831]: google.golang.org/grpc.(*ClientConn).Close(0x0)
Dec 08 18:37:49 router x-ui[1831]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1256 +0x6c
Dec 08 18:37:49 router x-ui[1831]: x-ui/xray.(*XrayAPI).Close(0xc00080e200)
Dec 08 18:37:49 router x-ui[1831]:         /home/runner/work/x-ui/x-ui/xray/api.go:52 +0x1f
Dec 08 18:37:49 router x-ui[1831]: x-ui/web/service.(*XrayService).GetXrayTraffic(0x0?)
Dec 08 18:37:49 router x-ui[1831]:         /home/runner/work/x-ui/x-ui/web/service/xray.go:173 +0x106
Dec 08 18:37:49 router x-ui[1831]: x-ui/web/job.(*XrayTrafficJob).Run(0xc00080e1e0)
Dec 08 18:37:49 router x-ui[1831]:         /home/runner/work/x-ui/x-ui/web/job/xray_traffic_job.go:22 +0x5e
Dec 08 18:37:49 router x-ui[1831]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Dec 08 18:37:49 router x-ui[1831]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x5b
Dec 08 18:37:49 router x-ui[1831]: created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 7
Dec 08 18:37:49 router x-ui[1831]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xa5
Dec 08 18:37:49 router systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 08 18:37:49 router systemd[1]: x-ui.service: Failed with result 'exit-code'.
Dec 08 18:37:49 router systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 10.
Dec 08 18:37:49 router systemd[1]: Stopped x-ui Service.
Dec 08 18:37:49 router systemd[1]: Started x-ui Service.
Dec 08 18:37:49 router x-ui[1873]: 2023/12/08 18:37:49 x-ui 1.6.1
Dec 08 18:37:49 router /usr/local/x-ui/x-ui[1873]: INFO - web server run http on [::]:9923
Dec 08 18:38:04 router x-ui[1873]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:38:04 router x-ui[1873]:         panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:38:04 router x-ui[1873]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab66d7]
Dec 08 18:38:04 router x-ui[1873]: goroutine 67 [running]:
Dec 08 18:38:04 router x-ui[1873]: google.golang.org/grpc.(*ClientConn).Close.func1()
Dec 08 18:38:04 router x-ui[1873]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1252 +0x17
Dec 08 18:38:04 router x-ui[1873]: panic({0x1518d20?, 0x2f6d750?})
Dec 08 18:38:04 router x-ui[1873]:         /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
Dec 08 18:38:04 router x-ui[1873]: google.golang.org/grpc.(*ClientConn).Close(0x0)
Dec 08 18:38:04 router x-ui[1873]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1256 +0x6c
Dec 08 18:38:04 router x-ui[1873]: x-ui/xray.(*XrayAPI).Close(0xc000a92980)
Dec 08 18:38:04 router x-ui[1873]:         /home/runner/work/x-ui/x-ui/xray/api.go:52 +0x1f
Dec 08 18:38:04 router x-ui[1873]: x-ui/web/service.(*XrayService).GetXrayTraffic(0x12d9179?)
Dec 08 18:38:04 router x-ui[1873]:         /home/runner/work/x-ui/x-ui/web/service/xray.go:173 +0x106
Dec 08 18:38:04 router x-ui[1873]: x-ui/web/job.(*XrayTrafficJob).Run(0xc000a92960)
Dec 08 18:38:04 router x-ui[1873]:         /home/runner/work/x-ui/x-ui/web/job/xray_traffic_job.go:22 +0x5e
Dec 08 18:38:04 router x-ui[1873]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Dec 08 18:38:04 router x-ui[1873]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x5b
Dec 08 18:38:04 router x-ui[1873]: created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 22
Dec 08 18:38:04 router x-ui[1873]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xa5
Dec 08 18:38:04 router systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 08 18:38:04 router systemd[1]: x-ui.service: Failed with result 'exit-code'.
Dec 08 18:38:04 router systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 11.
Dec 08 18:38:04 router systemd[1]: Stopped x-ui Service.
Dec 08 18:38:04 router systemd[1]: Started x-ui Service.
Dec 08 18:38:04 router x-ui[1904]: 2023/12/08 18:38:04 x-ui 1.6.1
Dec 08 18:38:04 router /usr/local/x-ui/x-ui[1904]: INFO - web server run http on [::]:9923
Dec 08 18:38:19 router x-ui[1904]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:38:19 router x-ui[1904]:         panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:38:19 router x-ui[1904]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab66d7]
Dec 08 18:38:19 router x-ui[1904]: goroutine 73 [running]:
Dec 08 18:38:19 router x-ui[1904]: google.golang.org/grpc.(*ClientConn).Close.func1()
Dec 08 18:38:19 router x-ui[1904]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1252 +0x17
Dec 08 18:38:19 router x-ui[1904]: panic({0x1518d20?, 0x2f6d750?})
Dec 08 18:38:19 router x-ui[1904]:         /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
Dec 08 18:38:19 router x-ui[1904]: google.golang.org/grpc.(*ClientConn).Close(0x0)
Dec 08 18:38:19 router x-ui[1904]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1256 +0x6c
Dec 08 18:38:19 router x-ui[1904]: x-ui/xray.(*XrayAPI).Close(0xc000526c20)
Dec 08 18:38:19 router x-ui[1904]:         /home/runner/work/x-ui/x-ui/xray/api.go:52 +0x1f
Dec 08 18:38:19 router x-ui[1904]: x-ui/web/service.(*XrayService).GetXrayTraffic(0x493493?)
Dec 08 18:38:19 router x-ui[1904]:         /home/runner/work/x-ui/x-ui/web/service/xray.go:173 +0x106
Dec 08 18:38:19 router x-ui[1904]: x-ui/web/job.(*XrayTrafficJob).Run(0xc000526c00)
Dec 08 18:38:19 router x-ui[1904]:         /home/runner/work/x-ui/x-ui/web/job/xray_traffic_job.go:22 +0x5e
Dec 08 18:38:19 router x-ui[1904]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Dec 08 18:38:19 router x-ui[1904]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x5b
Dec 08 18:38:19 router x-ui[1904]: created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 23
Dec 08 18:38:19 router x-ui[1904]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xa5
Dec 08 18:38:19 router systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 08 18:38:19 router systemd[1]: x-ui.service: Failed with result 'exit-code'.
Dec 08 18:38:19 router systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 12.
Dec 08 18:38:19 router systemd[1]: Stopped x-ui Service.
Dec 08 18:38:19 router systemd[1]: Started x-ui Service.
Dec 08 18:38:19 router x-ui[1928]: 2023/12/08 18:38:19 x-ui 1.6.1
Dec 08 18:38:19 router /usr/local/x-ui/x-ui[1928]: INFO - web server run http on [::]:9923
Dec 08 18:38:34 router x-ui[1928]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:38:34 router x-ui[1928]:         panic: runtime error: invalid memory address or nil pointer dereference
Dec 08 18:38:34 router x-ui[1928]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab66d7]
Dec 08 18:38:34 router x-ui[1928]: goroutine 67 [running]:
Dec 08 18:38:34 router x-ui[1928]: google.golang.org/grpc.(*ClientConn).Close.func1()
Dec 08 18:38:34 router x-ui[1928]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1252 +0x17
Dec 08 18:38:34 router x-ui[1928]: panic({0x1518d20?, 0x2f6d750?})
Dec 08 18:38:34 router x-ui[1928]:         /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
Dec 08 18:38:34 router x-ui[1928]: google.golang.org/grpc.(*ClientConn).Close(0x0)
Dec 08 18:38:34 router x-ui[1928]:         /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/clientconn.go:1256 +0x6c
Dec 08 18:38:34 router x-ui[1928]: x-ui/xray.(*XrayAPI).Close(0xc0001b0140)
Dec 08 18:38:34 router x-ui[1928]:         /home/runner/work/x-ui/x-ui/xray/api.go:52 +0x1f
Dec 08 18:38:34 router x-ui[1928]: x-ui/web/service.(*XrayService).GetXrayTraffic(0x12d9179?)
Dec 08 18:38:34 router x-ui[1928]:         /home/runner/work/x-ui/x-ui/web/service/xray.go:173 +0x106
Dec 08 18:38:34 router x-ui[1928]: x-ui/web/job.(*XrayTrafficJob).Run(0xc0001b0120)
Dec 08 18:38:34 router x-ui[1928]:         /home/runner/work/x-ui/x-ui/web/job/xray_traffic_job.go:22 +0x5e
Dec 08 18:38:34 router x-ui[1928]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Dec 08 18:38:34 router x-ui[1928]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x5b
Dec 08 18:38:34 router x-ui[1928]: created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 37
Dec 08 18:38:34 router x-ui[1928]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xa5
Dec 08 18:38:34 router systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 08 18:38:34 router systemd[1]: x-ui.service: Failed with result 'exit-code'.
Dec 08 18:38:34 router systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 13.
Dec 08 18:38:34 router systemd[1]: Stopped x-ui Service.
Dec 08 18:38:34 router systemd[1]: Started x-ui Service.
Dec 08 18:38:34 router x-ui[1954]: 2023/12/08 18:38:34 x-ui 1.6.1
Dec 08 18:38:34 router /usr/local/x-ui/x-ui[1954]: INFO - web server run http on [::]:9923

**Comment by adamgonglj** [comment]
here is the log.

**Comment by alireza0** [comment]
You have a null pointer in routing rule and it cause a crash in xray.
There is a cron task inside x-ui which will check xray existence. it is not a auto restart, but a auto recovery.

**Comment by adamgonglj** [comment]
I have routing rules.

`  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "balancers": [
      {
        "tag": "hk",
        "selector": [
          "realdvhk",
          "dvhk",
          "dvhk_1"
        ]
      }
    ],
    "rules": [
      {
        "type": "field",
        "ip": [
          "1.1.1.1",
          "1.0.0.1",
          "8.8.8.8",
          "8.8.4.4"
        ],
        "balancerTag": "hk"
      },
      {
        "type": "field",
        "ip": [
          "103.226.125.97",
          "223.5.5.5",
          "223.6.6.6",
          "119.29.29.29",
          "1.12.12.12",
          "120.53.53.53",
          "114.114.114.114",
          "114.114.115.115"
        ],
        "outboundTag": "direct"
      }
    ]
  },`

**Comment by adamgonglj** [comment]
"routing": {
    "domainStrategy": "IPIfNonMatch",
    "balancers": [
      {
        "tag": "hk",
        "selector": [
          "realdvhk",
          "dvhk",
          "dvhk_1"
        ]
      }
    ],
    "rules": [
      {
        "type": "field",
        "ip": [
          "1.1.1.1",
          "1.0.0.1",
          "8.8.8.8",
          "8.8.4.4"
        ],
        "balancerTag": "hk"
      },
      {
        "type": "field",
        "ip": [
          "103.226.125.97",
          "223.5.5.5",
          "223.6.6.6",
          "119.29.29.29",
          "1.12.12.12",
          "120.53.53.53",
          "114.114.114.114",
          "114.114.115.115"
        ],
        "outboundTag": "direct"
      }
    ]
  },

**Comment by adamgonglj** [comment]
I will check again.

**Comment by alireza0** [comment]
I cant see any error here. Please check the whole xray config to fine a bug in this configuration.
Also please pay attention to the xray status in main page to find the error.
