### ISSUE TITLE
مدیریت پهنای باند

### ISSUE THREAD

**Issue by sadegh1210** [alireza0/x-ui#723]
سلام مهندس
وقت بخیر
ایا امکان این هست پهنای باند پورت هارو به یک مقدار مشخص لیمیت کرد؟
یا ایپی هایی ک متصل میشوند ؟

**Comment by alireza0** [comment]
درود بر شما
خیر قربان. چنین امکانی در xray وجود ندارد.

**Comment by sadegh1210** [comment]
کامندی نیست ک داخل لینوکس زد و پورت هارو لیمیت کرد ؟

**Comment by alireza0** [comment]
نرم افزار های زیادی هست.
بهتره جستجو کنید
