### ISSUE TITLE
Please run SSE for get status requests

### ISSUE THREAD

**Issue by selfishtom** [alireza0/x-ui#724]
سلام و خسته نباشید.
طی بررسی هایی که انجام شده برای نمایش Status در پنل شما از متد Post برای دریافت اطلاعات به صورت Timer استفاده شده و این در سرور های پر کاربر موجب کندی میشود.
توصیه من استفاده از متد Get به حالت Stream توسط Server Sent Event هست تا بار متد Post از روی سرور برداشته شود.
شاد و پیروز باشید.

**Comment by alireza0** [comment]
درود بر شما
متد GET و POST برای ارسال درخواست استفاده میشه و ربطی به دریافت اطلاعات نداره.
سرورهای پر کاربرد رو متوجه نمیشم. این پنل، فقط مخصوص مدیر سیستمه و پرکاربرد بودن بر میگرده به سرویس های xray و نه پنل مدیریتی.
خود این پنل اونقدر بزرگ نیست که کاربر زیادی داشته باشه.

در واقع برای سرویس مبتنی بر gin web service ، برای درخواست های خالی از پارامتر ( مثل این مثال ) بار اضافه زیادی بین این دو روش نیست.
برای پردازش درخواست به خصوص درخواست های بدون body اطلاعات، این اختلاف قابل اغماض هست.

ولی نکته مهمتر اینه که درخواست های GET کاملا قابل دیدن هستن و برای امنیت بیشتر اطلاعات مهم رو از طریق POST باید درخواست بدیم.
یه موضوع امنیتی دیگه هم هست که شما به راحتی با یه مرورگر میتونید متد GET رو درخواست بدین، ولی برای POST امکانپذیر نیست.

**Comment by selfishtom** [comment]
صرفا پیشنهاد بود.

**Comment by alireza0** [comment]
سپاسگزارم
امیدوارم ایده ها و بررسی های دیگه هم در آینده داشته باشیم از شما.
کدهای متن باز تمام قدرتشون به همین ایده هاست.
