### ISSUE TITLE
tweak inbound UI

### ISSUE THREAD

**Issue by shahin-io** [alireza0/x-ui#725]
hello @alireza0 jan.

can u please consider swapping position of "Host" with "Remark" in "External Proxy" section. given that on the section above request header host is on right side of UI, this change will unify "name/remark" to left side and "value/host" to the right. results in fewer user error. 

thanks.

_
![94BD990E-FDDC-4E2D-BBF0-0BC7367228E2](https://github.com/alireza0/x-ui/assets/115543613/d270eb25-da99-4ca0-aef3-1ca956eb09b4)
_

**Comment by alireza0** [comment]
Dear @shahin-io ,
These two parts are not same.

Host is not mentioned in request headers!
It is not only for put the host:address. Headers has `key`=`value`. It is logical to position the key at first.

In External proxy we have these schema: `[http/https]` :// `HOST` : `PORT` # `Remark`
And remark is optional.
Is it sane to have another order ?
