### ISSUE TITLE
روش اتصال به چند outbound و سرور وامکان لود بالانسینگ load_balance

### ISSUE THREAD

**Issue by Shellgate** [alireza0/x-ui#728]
یکی از موردی که دوستان و شخص خود من دنبالش بودم این بود که چند سرور مختلف رو بشه همزمان متصل شد
و یک قالبیت هم باشه که بشه بین سرور ها سویچ خودکار انجام بشه

روش‌کار به این صورته که میشه به یک سرور چند ای پی تعریف کرد و حتی از چند cdn استفاده کرد
حال این ای پی های و ادرس ها رو در در outbound خودمون تعریف میکنیم و به صورت همزمان در خواست ها ارسال میشن برای بهبود عملکرد و درست کار کردن این مورد هم بهتره از mux استفاده کنید 

در اخر میشه از لود بالانسینگ هم استفاده کرد که به جای اتصال همزمان بین سرور ها سویچ انجام بشه
از دوست عزیز علیرضا جان میخوام که این قالبیت رو هم به پنل اضافه کنه که بتونیم به صورت گرافیکی کار رو پیش ببریم

نحوه کار و تانل چند سرور یا یک سرور با ایپی های مختلف

در کانفیگ زیر روش Reverse nginx  هست که به  چند سرور یا یک‌ سرور با چند ایپی میتوان اتصال داد

```go
[
  {
    "mux": {
      "concurrency": 0,
      "enabled": true,
      "xudpConcurrency": 0,
      "xudpProxyUDP443": "skip"
    },
    "protocol": "vless",
    "settings": {
      "vnext": [
        {
          "address": "First IP of the server",
          "port": 443,
          "users": [
            {
              "encryption": "none",
              "flow": "",
              "id": "92ca388b-e29a-429f-e288-6e402cfce447",
              "level": 8,
              "security": "auto"
            }
          ]
        },
        {
          "address": "The second IP of the server",
          "port": 443,
          "users": [
            {
              "encryption": "none",
              "flow": "",
              "id": "92ca388b-e29a-429f-e288-6e402cfce447",
              "level": 8,
              "security": "auto"
            }
          ]
        },
        {
          "address": "CDN IP or domain",
          "port": 443,
          "users": [
            {
              "encryption": "none",
              "flow": "",
              "id": "92ca388b-e29a-429f-e288-6e402cfce447",
              "level": 8,
              "security": "auto"
            }
          ]
        },
        {
          "address": "CDN IP or domain",
          "port": 443,
          "users": [
            {
              "encryption": "none",
              "flow": "",
              "id": "92ca388b-e29a-429f-e288-6e402cfce447",
              "level": 8,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "allowInsecure": false,
        "fingerprint": "firefox",
        "publicKey": "",
        "serverName": "",
        "shortId": "",
        "show": false,
        "spiderX": ""
      },
      "wsSettings": {
        "headers": {
          "Host": "The main server IP "
        },
        "path": "/empty or path/"
      }
    },
    "tag": "proxy"
  },
  {
    "tag": "direct",
    "protocol": "freedom",
    "settings": {
      "domainStrategy": "UseIP"
    }
  },
  {
    "tag": "blocked",
    "protocol": "blackhole",
    "settings": {
      "response": {
        "type": "none"
      }
    }
  },
  {
    "tag": "dns",
    "protocol": "dns",
    "settings": {
      "network": "tcp",
      "address": "8.8.8.8",
      "port": 53
    }
  }
]

``` 

این بخش رو هم در قسمت کلی کد به زیر routing اضافه میکنم

```go

  "outboundBalancers": [
    {
      "tag": "balancer",
      "selector": [
        "tag:proxy"
      ],
       "strategy": "round-robin"
    }
  ],

``` 

در قسمت بالا هم میتونید الگوریتم لود بالانسینگ رو انتخاب کنید و این گزینه مهم هست. 

در ضمن لود بالانسینگ رو اگه استفاده نکنید کل کانفیگ ها به صورت همزمان استفاده میشن

**Comment by Shellgate** [comment]
درسته من هم از لود بالانسینگ استفاده نمیکنم 
ودقیق این مشکل وجود دارد که سرور خراب رو تشخیص نمیده و الان هم دمشون گرم کل ایپی ها رو شناسایی و مسدود کردن اوضاع جالبی نیست 
روش ریورس رو نتونستم پیاده کنم چون در مورادی به مشکل بر خوردم
اگر امکان دارد روش رو برام ایمیل بفرستید
shellgate76@gmail.com

**Comment by ehsaninuc** [comment]
> درسته من هم از لود بالانسینگ استفاده نمیکنم ودقیق این مشکل وجود دارد که سرور خراب رو تشخیص نمیده و الان هم دمشون گرم کل ایپی ها رو شناسایی و مسدود کردن اوضاع جالبی نیست روش ریورس رو نتونستم پیاده کنم چون در مورادی به مشکل بر خوردم اگر امکان دارد روش رو برام ایمیل بفرستید [shellgate76@gmail.com](mailto:shellgate76@gmail.com)

https://alireza0.github.io/fa/docs/security/reverse/
