### ISSUE TITLE
مشکل اضافه نشدن نام سرشاخه Inbound داخل کلاینت 

### ISSUE THREAD

**Issue by mahdi449** [alireza0/x-ui#73]
![chf](https://user-images.githubusercontent.com/57775071/226022188-476dfe8c-08ee-4c90-98ef-09a5b0b9a77c.PNG)
به طور مثال اسم اکانت ساخته شده **test** هست و زیر مجموعه آن **vreh55o** هست 
وقتی روی کپی پانفیگ میزنیم دکمه کپی کانفیگ کارنمیکنه داخل آپدیت جدید و باید روی qr code زد تا کپی شود 
وقتی داخل clipboard کپی میشه و داخل برنامه کلاینت مثل v2rayn اضافش میکنم فقط اسم زیرمجموعه رو مینویسیه یعنی فقط میزنه **vreh55o** 
![ashashsah](https://user-images.githubusercontent.com/57775071/226024720-0252e783-3d6d-4046-9f3d-90e917cd8992.PNG)

امید وارم سریعتر رفع بشه چون برای من اضافه کاری میاره و باید اسم ها رو شروع کنم از اول نوشتن

**Comment by mahdi449** [comment]
قبلا کامل میزد مینوشت  test vreh55o 
اسم کانفیگ رو 

الان فقط اسم زیرشاخه یعنی vreh55o رو میزنه داخل کلاینت

**Comment by alireza0** [comment]
درود بر شما
این مورد باگ نیست و جزو امکانات اضافه شده از نسخه 0.4.0‌ بوده.
مراجعه کنید به [این تغییر](https://github.com/alireza0/x-ui/commit/8efa776cd71c97523b8dd8ed853eb5d671e62996).
به صورت کلی، remark یک متن اضافه شده به لینک بوده که میتونید بدون هیچ مشکلی تغییرش بدین و به کلاینت ارسال کنید.
تغییرش برای کاربر به جز اسم قابل مشاهده در نرم افزار سمت کاربر، هیچ مشکلی رو ایجاد نمیکنه. نیازی به تغییر در همه کاربرها نیست. فقط برای ایجاد کلاینت های جدید، تنها email رو‌در نظر بگیرید.
از زمانی که جستجو اضافه شده، کاربر رو میتونید با همون email جستجو کنید و به راحتی پیداش کنید.
اگر حتما میخواهید remark شامل هر دو اسم باشه، میتونید فیلد email رو تغییر بدید.
اگر email خالی باشه، remark به عنوان اسم نهایی توی لینک و qrCodeاعلام میشه. ولی بدون email نمیتونید مصرف ترافیک کاربر رو داشته باشید.

**Comment by mahdi449** [comment]
متوجه شدم سپاس
