### ISSUE TITLE
باگ قطع نشدن یوزرها هنگام اتمام حجم 

### ISSUE THREAD

**Issue by ghojaei1995** [alireza0/x-ui#734]
سلام امروز یک باگ وحشتناک در پنل مشاهده کردم یوزری که حجم ۱۰۰ گیگ براش زده بودم حجم تموم شده بود که متوجه شدم یوزر آنلاین زده و حجم مصرف شده را ۱۰۳ گیگ نوشته کانفیگش را تست کردم که متاسفانه دیدم کانفیک کار میکنه و غیر فعال نشده نمیدونم این  این اپدیت جدید چرا اینهمه باگ های عجیب غریب داره

**Comment by alireza0** [comment]
درود بر شما
این خطا رو جستجو کنید و متوجه میشید که خیلی ها این اشتباه رو داشتن. مربوط به این نسخه نیست.
لطفا از اینهمه باگی که مشاهده کردین، یه چند تاییش رو گزارش کنید تا با حلش به همه کمک بشه.

حقیقت اینه که همه سیستم هایی که اکانتینگ دارن، از کوچیک تا حرفه ای ترین ها، کاربر رو سر میلی ثانیه قطع نمیکنن.
توی این پنل هر ۱۰ ثانیه ترافیک ها چک میشه و اگر کاربری تمام شده بود به xray دستور میده که اون رو بیرون بندازه.

نشون دادن آنلاین اولین اشتباه همه است که فکر میکنن چون هنوز آنلاین نشون میده یعنی وصله!
چندین جا هم اعلام کردم، اگر ترافیک کاربر بیاد، توی اون ۱۰ ثانیه کاربر توی لیست آنلاین ها هست.

حالا اگر شما مشکل هارد توی سرورتون داشته باشید، طبیعیه که این تغییرات ذخیره نمیشه.

نکته مهمتر اینه که اگر xray اون کاربر رو بیرون نندازه ( که بعید هم نیست)، این باگ x-ui نیست.

لطفا در گزارشاتتون لاگ حالت DEBUG رو بذارید و هر وقت مطمئن شدید این خطا رو درست متوجه شدید با اسناد درست ایشو بزنید.
این همه متنی که نوشته شده به دلیل همین عدم ارائه اسناد و لاگهاست که مجیوریم با اما و اگر به شما جواب بدیم.

منتظر اطلاعات تکمیلی شما هستم
سپاسگزارم
