### ISSUE TITLE
تغییر نکردن configure strategy

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#735]
در آپدیت جدید این قسمتی رو که علامت زدم رو نمیشه تغییر داد
![Untitled](https://github.com/alireza0/x-ui/assets/124570423/afbd30a0-777b-409a-8f64-172fc2fea11a)

**Comment by alireza0** [comment]
Already fixed
[[bug] fix routing dns strategy](https://github.com/alireza0/x-ui/commit/9cc893a39611a9458af68692fb82f49bd374f1a2) https://github.com/alireza0/x-ui/issues/668
