### ISSUE TITLE
ساخت پروتکل دوکو به صورت دستی

### ISSUE THREAD

**Issue by MaMMaD1999** [alireza0/x-ui#736]
درود، من از آخرین نسخه پنل سنایی استفاده میکنم، نمیدونم مشکل از سرور مبدا هست یا پنل باگ خورده اما بصورت گرافیکی که توی پنل یه پروتکل دوکو میسازم کار نمیکنه

طبق [این آموزش خودتون](https://github.com/alireza0/x-ui/issues/252) وقتی بصورت دستی کنار پورت 443 بصورت دستی دوکو رو توی تنظیمات xray اضافه میکنم این پروتکل کار میکنه!
میخوام بدونم اگه بخوام یه پروتکل دیگه بصورت دوکو کنار همیهنا ( حالا با یه پورت دیگه مثلا) بخوام بسازم بصورت دستی به چه شکل باید انجام بدم؟
(هدفم از این کار تانل کردن پروکسی MTProto تلگرامی هست که روی سرور خارجم زدم، قبل تر که این پروتکل کار میکرد تو پنل آیپی سرور خارج رو توی مقصد میزدم و پورت پروکسی رو هم تنظیم میکردم و کار میکرد)

**Comment by alireza0** [comment]
درود بر شما
در پنل شما امکان تغییر tag رو ندارید و به صورت اتوماتیک inbound-[port] در نظر گرفته میشه.
اگر شما روی پورت ۴۴۳ تنظیم کردین، تگ این اینباند میشه: inbound-443

اگر خروجی سرور داخلی شما freedom باشه، نتیجه استفاده از دوکودمودور فیلتر شدن ارتباط و حتی سرور شما میشه.
خاصیت دکودمودور اینه که ترافیک رو میگیره و از طریق مسیریابی و خروجی xray اون به هدف میرسونه

**Comment by MaMMaD1999** [comment]
> درود بر شما در پنل شما امکان تغییر tag رو ندارید و به صورت اتوماتیک inbound-[port] در نظر گرفته میشه. اگر شما روی پورت ۴۴۳ تنظیم کردین، تگ این اینباند میشه: inbound-443
> 
> اگر خروجی سرور داخلی شما freedom باشه، نتیجه استفاده از دوکودمودور فیلتر شدن ارتباط و حتی سرور شما میشه. خاصیت دکودمودور اینه که ترافیک رو میگیره و از طریق مسیریابی و خروجی xray اون به هدف میرسونه


درود، ممنون از توضیحات تون، اما خروجی پنل بصورت پروکسی هست نه freedom و بین دو پنل تانل زده شده، توی قسمت خروجی موردی نیست، سوالم اینه که توی قسمت inbound چطوری یک دوکو جدید مثل این قسمت دوم 
![Screenshot 2023-12-11 191500](https://github.com/alireza0/x-ui/assets/134168076/3fe44e52-ff94-4808-9fd1-10cfb658584c)
 که توی عکس گزاشتم تعریف کنم

**Comment by alireza0** [comment]
شما هرجوری بسازید پنل به خطا نمیخوره. روشش توی همون داکیومنت اعلام شده
https://github.com/alireza0/x-ui/issues/252
