### ISSUE TITLE
WireGuard Protocol

### ISSUE THREAD

**Issue by shahin-io** [alireza0/x-ui#738]
hello @alireza0 Jaan.

Do u have any plan for adding `Wireguard` protocol into `X-UI` in the near future? given that `Xray 1.8.6` recently add support for it.

thanks.

**Comment by alireza0** [comment]
Hello @shahin-io Jan,

There is no documentation yet, but:
https://xtls.github.io/config/outbounds/wireguard.html#outboundconfigurationobject

Pay attention to the banner!

**Comment by alireza0** [comment]
Dear @shahin-io ,

The wireguard protocol is going to be better by some other PRs like [this](https://github.com/XTLS/Xray-core/pull/2794) and [this](https://github.com/XTLS/Xray-core/pull/2717).

I am waiting for the new version of xray-core.
