### ISSUE TITLE
مشکل در کپی ادرس VMESS

### ISSUE THREAD

**Issue by razikazeminezad** [alireza0/x-ui#74]
با سلام،
یه چند روز هست بنده زمانی که چند یوزر پشت سر هم ساخته و بعد روی دکمه qr-code کلیک و کپی رو میزنم و بعد میرم سراغ یوز بعدی متسفانه دومین یوز دکمه کپی در کادر qr-code کار نمیکنه.
روی سرور جدید و با مرور گر های مختلف تست کردم مشکل پا بر جاست.
در ضمن در گوشی هم به همین شکل بود

**Comment by mahdi449** [comment]
دقیقا این مشکل رو منم دارم و براش ریپورت باگ ساختم

**Comment by aliafshany** [comment]
@razikazeminezad 
باید روی خود تصویر qr code کلیک کرد تا کپی شه.
اینطوری میشه دورش زد

**Comment by alireza0** [comment]
این مشکل حل شده، لطفا دوباره بروزرسانی کنید.
