### ISSUE TITLE
Some Ideas 

### ISSUE THREAD

**Issue by wulfric93** [alireza0/x-ui#741]
hi There hope you doing well 
and thank you for all of your efforts 

i have an ideas 
is it possible to add account managements feature for Panel to add reseller to sell accounts? 
i mean a limited one which the owner of server choose each reseller can only create certain number  of account on the inbounts that owner allowed them to create account and sell but dosent have a access to remove or other administrator privileges

**Comment by alireza0** [comment]
Hello @wulfric93 ,

This project is not developed free to make a business. I am not agree to put a feature to help sellers.
