### ISSUE TITLE
عدم درج نام یوزر در ریمارک بعد از تغییرات در چینش ریمارک در تنظیمات پنل

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#743]
در نسخه جدید وقتی تغییراتی رو در ریمارک بوجود میاری دیگه بعد اون در آپدیت لینک ساب نام یوزر یا همون ایمیل از کانفیگ حذف میشه و نمیاد هر چقدر هم تغییرات میدیم
البته ذکر کنم که الان چمد تا پنل که آپدیت ضدن و این قسمت تغییر نداده شده اوکی هستند ولی یکی از پنلها رو که تغییر دادم دیگه در کانفیگها نام کاربری یا ایکیل نمیاد پ حذف شده

**Comment by aliamg1356** [comment]
توضیحات تکمیلی اینکه در پنل آقای سنایی هم همین مشکل بوجود اومده .فکر کنم کدهای هر دو پنل در این مورد یکی هستند

**Comment by alireza0** [comment]
لطفا اون پنل رو مجدد بروزرسانی کنید. مشکل قبلا حل شده
