### ISSUE TITLE
مشکل نمایش کاربران با تعداد زیاد

### ISSUE THREAD

**Issue by eventhorizon1dora** [alireza0/x-ui#744]
با سلام و تشکر بابت زحماتی که میکشید
هنگامی که یوزر های یک اینباند تعداد زیادی ( ۲۰۰۰ تا به بالا)‌هستش زمانی که اینباند رو expand میکنید به دلیل تعداد زیاد یوزر های مقدار5 گیگ رم کروم مصرف میکنه و یوزر ها رو نمیتونه نمایش بده
پیشنهاد میکنم اگه بتونید صفحه بندی کنید که هر صفحه مثلا ۱۰ تا کاربر رو نشون بده به جای اینکه یکجا همه رو باهم نشون بده مشکل حل بشه
سپاس

**Comment by ramtiny** [comment]
کلا با مرورگر های‌گوشی متاسفانه وقتی میخواییم یه یوزر ادیت کنیم خیلی کند هست
چیکار باید کرد؟

**Comment by eventhorizon1dora** [comment]
> این قابلیت در حال حاضر اضافه شده. وارد panel settings بشید و گزینه Pagination size رو از عدد صفر به عدد دلخواهتون تغییر بدید. هر عددی تنظیم کنید، همونقدر رو تو یک صفحه به نمایش میزاره و تقسیم بندی میکنه.

دم شما و علیرضا گرم که فکر همه جا رو کرده
