### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by ArfatRahman** [alireza0/x-ui#745]
how to migrate the database from one old xui server to new one,

**Comment by wulfric93** [comment]
> how to migrate the database from one old xui server to new one,

from what panel do you want to migrate?

**Comment by ArfatRahman** [comment]
V2ray x-ui panel,

I want to transfer the database and ssl certificate to another server

**Comment by alireza0** [comment]
1. Remove your certificate file paths in panel/subscription settings.
2. Install same version of x-ui in new server.
3. Copy your database.
4. Change DNS to new server's IP.
5. Use certificates:
  a. Free certificate: Issue new certificate in new server.
  b. Paid certificates: Copy files into new server.
6. (re-)Start x-ui.
7. Configure your certificate file paths in panel/subscription settings.
8. Make sure that everything is working properly.
9. Upgrade x-ui to desired versoin if you want.
