### ISSUE TITLE
درخواست اپلیکشن اندروید برای پنل

### ISSUE THREAD

**Issue by ramtiny** [alireza0/x-ui#747]
آیا امکانش هست برای پنل یه اپلیکیشن اندروید بیرون بدید
که مثلا برای ساخت و ادیت یوزر بتونیم ازش استفاده کنیم؟
چون الان با مرورگر گوشی یخورده کنده

**Comment by wulfric93** [comment]
دوست عزیز کسی رایگان این کار رو انجام نمیده

**Comment by ramtiny** [comment]
خب پنل رو بصورت پولی کنن
