### ISSUE TITLE
قسمت مولتی ادمین

### ISSUE THREAD

**Issue by smblue07** [alireza0/x-ui#75]
سلام خسته نباشید
1.قسمت مولتی ادمین کاراکتر "," رو قبول نمیکنه و روی عدد قفل شده
اگه امکان داره این مورد رو بررسی کنید
2.در ربات تلگرام وقتی یوزر پیامی مینویسه بهش عبارت ❗️ Unknown message نمایش داده میشه (قبلا روی ربات فقط با تایپ کاراکتر "/" این پیام دریافت میشد.) در واقع قبلا فقط به عبارتهایی که با / شروع میشد و کامند ربات بود واکنش نشون میداد ولی الان به تمامی عباراتی که واسش ارسال میشه واکنش نشون میده
اینم بررسی کنید به حالت قبل دربیاد بهتره
![225938090-053690ef-d410-4512-985f-40eb6f929fa8](https://user-images.githubusercontent.com/118044213/226094641-ed1dbde8-e8e9-43b0-8482-68cae280fe13.jpg)
3. در هنگام بکاپ گیری روی ربات تلگرام علاوه بر فایل x-ui.db فایل config.json هم بکاپ گرفته بشه.
4. در ربات تلگرام ادمین با زدن دکمه Get Inbounds کلاینتهای هر inbound هم با دیتای مصرفشون ارسال بشه.
با تشکر

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و گزارش اشکال
ظاهرا شما از نسخه قدیمی تر استفاده میکنید. لطفا بروزرسانی کنید
۱. این مشکل حل شده
۲. در نسخه جدید به همه پیام های ناصحیح این پیغام ارسال میشه و نشونه سلامت بات میتونه باشه
۳. پیشنهاد خوبیه، در نسخه های بعدی بررسی میکنم
۴. متاسفانه به دلیل محدودیت تعداد پیام ها این مورد ممکنه که باعث بلاک شدن بشه. (هرچند تاخیر ۵۰۰ میلی ثانیه اضافه شده)

**Comment by smblue07** [comment]
مورد ۲ رو بی زحمت حساس به کامند های ربات کنید بهتره
چون خیلیا مثل من از طریق ربات با یوزرها ارتباط هم دارند و همین باعث میشه هر پیامی میدن ارور بگیرن

**Comment by smblue07** [comment]
مورد ۴ هم اگه امکانش هست لیست اینباندهارو نمایش بده تا ادمین بعد از انتخاب اینباند لیست کلاینتهای هر اینباند رو بتونه روی ربات دریافت کنه به نظرم خیلی عالی میشه

**Comment by alireza0** [comment]
> مورد ۲ رو بی زحمت حساس به کامند های ربات کنید بهتره چون خیلیا مثل من از طریق ربات با یوزرها ارتباط هم دارند و همین باعث میشه هر پیامی میدن ارور بگیرن

استفاده همزمان از بات باعث ایجاد مشکل توی سرور میشه. بهتره برای ارتباط با پنل از بات دیگه ی استفاده کنید.
در ضمن با استفاده از api شما میتونید بات مناسب خودتون با امکانات بیشتر رو بنویسید



> مورد ۴ هم اگه امکانش هست لیست اینباندهارو نمایش بده تا ادمین بعد از انتخاب اینباند لیست کلاینتهای هر اینباند رو بتونه روی ربات دریافت کنه به نظرم خیلی عالی میشه

مشکلی نیست میتونم اضافه کنم،‌ ولی برای کسانی که تعداد زیادی inbound دارند پیغام های زیادی میره و قابل کنترل نیست

**Comment by smblue07** [comment]
راجب مورد 2 به نظرتون اینکه با هر پیغامی ارور نمایش داده بشه اصولی هستش؟!
من قبلتر هم داشتم از این ربات برای ارتباط استفاده میکردم مشکلی نداشتم. شما هم به نظرم این مورد رو به حالت قبلی برگردون که بسترش فراهم باشه. حالا هرکسی خواست از ربات مجزا واسه ارتباط استفاده کنه!

ممنون

**Comment by alireza0** [comment]
بله دوست عزیز، نمایش خطا در صورت وجود، یک کار اصولی است. ( رجوع شود به Exception Handling )
ولی از اونجایی که قرار نیست روی پیام ها کار کنیم و سرور فقط command و callback رو باید جواب بده، جواب پیام ها رو حذف کردم.
فایل config.json مربوط به xray  هم ارسال میشه.
دستور `/inbound ` اضافه شد که میتونید inbound رو با اسمش جستجو کنید و کارکرد کلاینت هاش رو هم بتونید بگیرید. اینجوری هم شما میتونید کلاینت ها رو ببینید و هم دوستان دیگه اذیت نمیشن. برای دیدین کل inbound ها میتونید اسمش رو خالی بذارید:

All inbounds + clients' stats:
```
/inbound
```
Search for inbound by remark + its clients' stats
```
/inbound [remark]
```

**Comment by smblue07** [comment]
بسیار ممنونم از شما دوست عزیز
