### ISSUE TITLE
Can you provide a tutorial on how to set up a subscription link? I'm really confused and have no idea how to do it.

### ISSUE THREAD

**Issue by li-wendian** [alireza0/x-ui#752]
![image](https://github.com/alireza0/x-ui/assets/87528847/a9dfa4f9-c102-4018-a905-6737d3e570a8)
![image](https://github.com/alireza0/x-ui/assets/87528847/98392b18-f6c0-40d9-a422-8feda2a5b9f3)

**Comment by alireza0** [comment]
You can find user's subscription link in information link for each user.

**Comment by wulfric93** [comment]
Just Enable Subscription at Panel Support and assign your desired letters (panel itself assign one randomly, but you can change it) at each client section
