### ISSUE TITLE
Telegram API URL

### ISSUE THREAD

**Issue by badmast** [alireza0/x-ui#754]
اگر بخشی اضافه بشه که بتونیم آدرس ورکری که با این  ([soheylfarzane/TelegramByapss](https://github.com/soheylfarzane/TelegramByapss)) روش ساختیم رو جایگزین آدرس API تلگرام کنیم، مشکل تلگرام در سرور‌های ایران حل میشه.

در این فایل ([web/service/tgbot.go](https://github.com/alireza0/x-ui/blob/main/web/service/tgbot.go)) از این کد ([mymmrac/telego](https://github.com/mymmrac/telego)) استفاده شده که در خط ۱۷ فایل [mymmrac/telego/bot.go](https://github.com/mymmrac/telego/blob/main/bot.go) آدرس APIای که برای تلگرام ازش استفاده می‌کنه رو میشه تغییر داد.

**Comment by wulfric93** [comment]
درود مشکل تلگرام قبلا حل شده 
https://github.com/alireza0/x-ui/issues/252

**Comment by alireza0** [comment]
- در این پنل ما از telego استفاده نمیکنیم.
- تعویض آدرس یک راه حل موقته و امن نیست.
- مشکل تلگرام با راه های ارائه شده به صورت امنی قابل حله.

**Comment by babakazizigithub** [comment]
> * در این پنل ما از telego استفاده نمیکنیم.
> * تعویض آدرس یک راه حل موقته و امن نیست.
> * مشکل تلگرام با راه های ارائه شده به صورت امنی قابل حله.

 درود جناب علیرضا 
این راه حل ها رو لطف میکنید بفرمایید .. اون روش دوکو روی سرور های ایران ما کار نمیکنه 
ممنون میشم

**Comment by alireza0** [comment]
درود بر شما @babakazizigithub 
کد های اجرای تلگرام توی نسخه های جدید تغییراتی داشته که با همون راه حل دوکودمودور بهتر کار میکنه.
