### ISSUE TITLE
چطوری میشه حجم مصرفی کاربر هر ماه اتوماتیک ریست بشه؟

### ISSUE THREAD

**Issue by EmperorofWeb** [alireza0/x-ui#756]
چطوری میشه حجم مصرفی کاربر هر ماه به صورت اتوماتیک ریست بشه؟ در واقع همون کاری که فعال کردن گزینه auto reset تو پنل کافکا انجام میداد

**Comment by alireza0** [comment]
وقتی تاریخ انقضای کاربر رو تغیین میکنید، زیرش گزینه ریست اتوماتیک فعال میشه که میتونید تعداد روز های هر دوره رو توش مشخص کنید

**Comment by EmperorofWeb** [comment]
درسته، خیلی ممنون

**Comment by EmperorofWeb** [comment]
درسته، خیلی ممنونم
