### ISSUE TITLE
معرفی داکیومنت

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#757]
با سلام و خسته نباشید
در اینباند قسمتی هست به اسم پراکسی شفاف یاTransparent Proxy که گزینه های متعددی داره.میشه داکیومنتی معرفی کنید در این مورد اطلاعات بهتری کسب کنیم؟

**Comment by wulfric93** [comment]
https://guide.v2fly.org/en_US/app/transparent_proxy.html
