### ISSUE TITLE
چرا زمانی که تانل میکنم ip limit کار نمیکنه

### ISSUE THREAD

**Issue by Namkarbari** [alireza0/x-ui#758]
؟؟؟

**Comment by wulfric93** [comment]
با تانل آی پی لیمیت کار نمیکنه 
و فکر میکنم که این پنل (علیرضا) کلا قابلیت آی پی لیمیت رو نداره

**Comment by alireza0** [comment]
این پنل قابلیت محدودیت IP نداره
