### ISSUE TITLE
1 bot for all panels

### ISSUE THREAD

**Issue by aliafshany** [alireza0/x-ui#76]
Thank you for the excellent work you have done.
 I would like to make a request to see if it is possible. Could you create a Telegram bot that operates across multiple Panels with just one bot? It would be greatly appreciated if you could consider this. 

Best regards.

**Comment by alireza0** [comment]
Hello Ali jan,
Telegram bot feature is bi-directional. Each message from telegram should be sent to one server.
Telegram doesn't support multi server answering.

If you need to have backup and report, you can use it. But user/admin commands' treatment won't be predictable
