### ISSUE TITLE
Appreciation and Minor Issues in x-ui Docker Migration

### ISSUE THREAD

**Issue by sgrtye** [alireza0/x-ui#760]
I want to express my sincere gratitude for your hard work and valuable contribution to the community. I recently migrated from the [FranzKafkaYu](https://github.com/FranzKafkaYu/x-ui?tab=readme-ov-file) version of x-ui, as the repository has been archived. Your version has proven to be a reliable open-source alternative.

The migration process has been smooth, and most features are working correctly. However, I've encountered a few minor details that I would like to bring to your attention and seek clarification. I am using x-ui on Ubuntu 22.04 with Docker.

Resource Loading Issues:

On page load, two resources, namely favicon.ico and Vazirmatn-UI-NL-Regular.woff2, fail to load correctly. Both return a status code of 500 with the response 'seeker can't seek'. The missing favicon.ico affects the web icon display, and the absent font does not seem to impact functionality. I assume there might be a fallback default for missing font files.
![image](https://github.com/alireza0/x-ui/assets/55668018/42903328-f8a9-422f-bc79-e217ebca2a39)

Home Page Host Field:

On the home page, the 'host' field displays a code instead of the host website. In my previous x-ui version, this field was not present, and I'm uncertain about its purpose. Additionally, when hovering over the IPv4, it shows the IP address and subnet for my Docker container rather than the private IP of the hosting server or the public IP in use. I noticed a different implementation by [MHSanaei](https://github.com/MHSanaei/3x-ui) where there is no 'host' field, and the IPv4 is the public IP. Could you provide insights into the purpose of these two fields?
![image](https://github.com/alireza0/x-ui/assets/55668018/682b0ab2-fcf0-481b-8ae2-e7786bb5e002)

Client Traffic Calculation:

Inbound traffic is calculated correctly, but not for client traffic. I came across an issue mentioning that each client must have a unique email for correct functioning. Is this still the case, and is it possible to link multiple identifiers (inbound remark, inbound id, client id) to identify the client, removing the requirement for a unique email for each client?
![image](https://github.com/alireza0/x-ui/assets/55668018/62eebfbc-dfdc-487c-9577-7f88387dc545)

Once again, thank you for your excellent work, and I appreciate any guidance or assistance you can provide regarding these queries.

**Comment by alireza0** [comment]
Hello @sgrtye,
Thank you for your kind consideration.

Regarding the resources whic are not loaded, you should track what is the problem in geting files from this path:
```
/x-ui/assets/
```
It might be a kind of docker configuration which routes only subdirectories of this folder.

Regarding `Hostname` and `IP`, it was what exactly we need for determining the host.
If it was checking the IP from an external resource, it should be checked each 2s. It may case problems due to delays.
Also, imagine a host with several IPs and when you use external checking, it shows only one.
But when you have real hostname and real IP of hosts, it will help you to determine the host/docker container without any dependency on external resources.
Finding external IP is not so hard while you opened the page with that address ;)

Regarding client traffics: in this panel, it is checking the traffics from xray-core's api and xray-core identifies users by email. When you have no email, there should be no result from xray-core.

**Comment by sgrtye** [comment]
Hi @alireza0,

Thanks for your prompt response. I've investigated further into the issues and have a few follow-up questions.

### Resources Loading Issue:
I couldn't find the path '/x-ui/assets/' in the file system. As shown below, there is no assets folder, and two x-ui occurrences one contains x-ui.db and the other one is not a directory. While other resources from 'assets' load correctly, I wonder if you can give more details on how resources are stored in the file system. Could you provide additional information or clarification?

![Resource Loading Issue](https://github.com/alireza0/x-ui/assets/55668018/907330cc-1e59-4219-b16a-82e447654f74)

### Hostname and IP Issue:
I understand your implementation logic, but my hostname doesn't align with the stack name, container name, ID, or hash. Can you give me some insight into how the hostname is determined, what factors are taken into account, and whether it's possible to make it more user-friendly (human-readable)?

### Client Email and Traffic Issue:
I changed the client email to the ID of inbound (I only have 1 client per inbound, thus, each client has one unique email, I also tried the random generation by the panel), but after rebooting Xray core, the container, and the host system, the client traffic still doesn't work. Additionally, I assume the online/offline indicator is also based on the client's email. Can you provide more details on resolving the client conflict issue to address both problems?

![Client Traffic Issue](https://github.com/alireza0/x-ui/assets/55668018/083ee4bb-8019-4dc3-9f3c-7752ef3e06a9)

Any help or guidance you can provide would be greatly appreciated. Thank you!

**Comment by alireza0** [comment]
> Resources Loading Issue:

This resources has no physical place, but only in-app scripts. I wrote a worng path! Sorry, it is `http(s)://<domain>:<port>/xui/assets/`.
You should check outside of the app (specially in your docker network/loadbalancer) if there is any kind of path limitation.

> Hostname and IP Issue:

I don't know what do you mean by human readable? If you want so, you need to run x-ui outside of docker ;)
If you type the command `hostname` inside your docker, you can see the exact text as the app showing.

> ### Client Email and Traffic Issue:

If you set uinque email for each client, there should be no problem. If it shows no traffic in clients, then it should be the problem related to your xray configuration.
Simple solution is to reset your xray-configuration in xray page.
Advanced solution is to check if these parts are correctly configured in your xray configuration:

1. policy:
```json
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
```

2. stats:
```json
  "stats": {}
```

**Comment by Enkidu-6** [comment]
Just a few things to help you troubleshoot

> On page load, two resources, namely favicon.ico and Vazirmatn-UI-NL-Regular.woff2, fail to load correctly

On a fresh docker install I have the same issue, so I don't think that has anything to do with your setup.

> On the home page, the 'host' field displays a code instead of the host website.

That's not the case for me. The host name appears correctly.

> when hovering over the IPv4, it shows the IP address and subnet for my Docker container rather than the private IP of the hosting server or the public IP in use.

Not sure what you mean by the private IP of your hosting server but in my case, it shows what it's supposed to show which is ***both*** my server's /32 Public IP address ***and*** right next to it, my /16 private IP address of the docker container.

And for IPV6, it shows my correct public IPV6 address of the server and of course no local IPV6 address because, well,  docker doesn't support IPV6 out of the box anyway.

Happy hunting!

**Comment by Enkidu-6** [comment]
P.S.

Forgot to mention that my installation has no problem calculating or displaying the client traffic either.

**Comment by sgrtye** [comment]
Hi @alireza0 and @Enkidu-6,

>On a fresh docker install I have the same issue, so I don't think that has anything to do with your setup.

Thanks for your information, I also tried the image on another machine (different OS + different architecture), and it seems like the loading issue is indeed not caused by my setup.

Since I am using Nginx as a reverse proxy, I just hijacked all requests of favicon.ico to another icon. And the missing font does not seem to affect functionality anyway.

I was unaware of the hostname that docker can set. After adding it to the docker-compose file, it works great.

>Not sure what you mean by the private IP of your hosting server but in my case, it shows what it's supposed to show which is both my server's /32 Public IP address and right next to it, my /16 private IP address of the docker container.

But on both of my machines, the IPv4 field only displays the container IP in the docker network. However, showing my public IP is not part of my priorities.

As for the client traffic, it turns out to be a migration issue. I had to first reset the Xray config, then it worked for only one inbound. This confused me for hours until I remembered that I changed the UUID of that inbound, thus, deleting and adding a new client to each inbound solves the problem. If you(@alireza0) find this information important, you can add this to the README file so that people migrating from other branches of x-ui can know about this in advance.

Thank you both for your time and effort dedicated to this issue. I am now closing this issue as complete. It has truly been a pleasure engaging in conversation with both of you.
