### ISSUE TITLE
حذف ادرس دامنه از ریلتی 

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#764]
چرا آدرس دامنه را از ریلتی پاک کردید ؟؟؟
![IMG_20231214_164954](https://github.com/alireza0/x-ui/assets/94555298/7aca7df3-3aa4-46a1-91c8-356ea11ad52d)
![Screenshot_2023-12-14-16-49-16-460_com android chrome](https://github.com/alireza0/x-ui/assets/94555298/5d1adedf-89e5-497e-b6c0-a878e9314df8)

**Comment by alireza0** [comment]
به دلیل اینکه یه گزینه بهتر اضافه کردیم: external Proxy

لطفا هربار که بروزرسانی میکنید، متن تغییرات هر نسخه رو بخونید.
