### ISSUE TITLE
یاگ عجیب در تنظیمات اوتباند و روتینگ پنل

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#766]
با سلام
از ورژن 1.6.3 استفاده میکنم
متوجه باگ عجیب و شکل داری شدم در پنل 
یک سرور خارج به دو سرور ایران به صورت ریورس تانل شدن پنل به پن
روتها و رولها رو نوشته بودم  ولی صبح دیدم رولها پاک شدم فکر کردم خودم اشتباهب پاک کردم  حتب رولهای مربوط به بلاک کردن بیت تورنت و  ipv4 و موارد دیگه هم پاک شده بود.به جز رولهای اوت باند و ریورس
رولها رو دوباره نوشتم ولی هنگام ریستارت پنل یا ریفرش مرورگر باز پاک میشند  دستی خواستم رولها رو با کد اضافه کنم باز همون مشکل بود .از قسمت روتینگ رول خواستم اضافه کنم اضافه میکردم ولی وقتی سیو میزدم اضافه نمیشد.خطایی هم نمیداد.
در ورژن 1.6.2 مشکلی نبود ولی در ورژن 1.6.3 این مشکل هست  خیلی سعی کردم ولی رولها ذخیره نمیشد.سرور رو ریستارت کردم باز مشکل پا برجا بود
نه پنل خطایی میده و نه خطایی در لاگ xray ثبت میشه

**Comment by aliamg1356** [comment]
یه مشکل دیگه در این ورژن رو متوجه شدم  سرویس بعد مدتی کار دیگه آپلود و دانلود نداره و باید سرویس xray ریستارت بشه تا حل بشه

**Comment by alireza0** [comment]
درود بر شما
مشکل اول،‌ مورد تاییده و مشکل در پروسه حذف یا ویرایش reverse بود.
در نظر داشته باشید تغییرات تا ذخیره نشده باشند، قابل بازیابی نیستند و با هر بار رفرش دیتای موجود در دیتابیس لود میشه.
تا نسخه بعدی که مشکل رو حل میکنم، لطفا ویرایش و حذف ریورس رو توی حالت پیشرفته انجام بدین.

در مورد مشکل دومی که اعلام کردین، باید لاگ ها رو چک کنید.
البته منظور شما رو از آپلود و دانلود نداشتن متوجه نشدم!
- کل سرویس از کار می افته ؟ ( ممکنه فیلترینگ و یا تنظیمات دیگه باشه)
- ترافیک ثبت نمیشه ؟ ( ممکنه خطای دیتابیس داشته باشید و یا سرور شما درست تنظیم نشده باشه )
- تانل کار نمیکنه ؟ ( ممکنه از فیلترینگ و یا خارج از سرویس xray باشه )

**Comment by aliamg1356** [comment]
> درود بر شما مشکل اول،‌ مورد تاییده و مشکل در پروسه حذف یا ویرایش reverse بود. در نظر داشته باشید تغییرات تا ذخیره نشده باشند، قابل بازیابی نیستند و با هر بار رفرش دیتای موجود در دیتابیس لود میشه. تا نسخه بعدی که مشکل رو حل میکنم، لطفا ویرایش و حذف ریورس رو توی حالت پیشرفته انجام بدین.
> 
> در مورد مشکل دومی که اعلام کردین، باید لاگ ها رو چک کنید. البته منظور شما رو از آپلود و دانلود نداشتن متوجه نشدم!
> 
> * کل سرویس از کار می افته ؟ ( ممکنه فیلترینگ و یا تنظیمات دیگه باشه)
> * ترافیک ثبت نمیشه ؟ ( ممکنه خطای دیتابیس داشته باشید و یا سرور شما درست تنظیم نشده باشه )
> * تانل کار نمیکنه ؟ ( ممکنه از فیلترینگ و یا خارج از سرویس xray باشه )

منون بابت پاسخگویی
در مورد اول تنظیمات ذخیره میشد و بعد از ریفرش پاک میشد انگار تنظیمات پنل ریست شده باشه.
در مورد مشکل دوم پنل هیچ خطایی نمیداد.در ظاهر هیچ اختلالی نداره.ولی کانفیگها با وجود اینکه پینگ میدن ولی هیچ چیزی باز نمیشه  مگر اینکه از داخل پنا xrayریستارت بشه تا درست بشه

**Comment by alireza0** [comment]
تا زمانی که دکمه ذخیره و نزنید ذخیره نمیشه. ولی توی همه جای بخش تنظیمات xray دیده میشه.
اگر این کار رو انجام میدید و باز هم مشکل داره، حتما بعد از ذخیره کردن به تنظیمات پیشرفته سر بزنید.
ممکنه تنظیمات شما از نظر json درست نباشه. در اینصورت ذخیره هم نخواهد شد.

در مورد اینکه چیزی باز بشه و یا نشه، مشکل از تنظیماتیه که شما انجام میدید و یا فرآیند فیلترینگ.
این مورد ربطی به پنل نداره.
