### ISSUE TITLE
Base64 is not encryption.

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#767]
As you know `base64` is an encoding type. it should not be misunderstood as an `encryption` method.

So, I think it should be renamed as `Encode configs` instead of `Encrypt configs`.

Good Luck!

**Comment by alireza0** [comment]
You are right. But it is not a bug. It is a kind of typo ;)

**Comment by alireza0** [comment]
It is fixed in #765 by @shahin-io

**Comment by X-Oracle** [comment]
Thank.
