### ISSUE TITLE
EOF after updateClient route

### ISSUE THREAD

**Issue by EryX0** [alireza0/x-ui#768]
when I use updateClient to change traffic/time of the client, the changes get saved and i get success response from the api, but the client gets EOF when trying to connect, then after manually disabling and enabling the client, it works again.

here's the code block for updating the client: (python)

```python
    client= {"id": id,
        "alterId": 0,
        "email": email,
        "limitIp": iplimit,
        "totalGB": int(volume) * 1073741824,
        "expiryTime":  -1 *int(days) * 24 * 60 * 60 * 1000,
        "enable": 'true',
        "tgId": "",
        "subId": ""}
    client = json.dumps(client)
    data = {
        "id": inbound_id,
        "settings": '{"clients": [' + client + ']}',
    }
    updateClient_post = session.post('ip:port/path/xui/API/inbounds/updateClient/' + str(id), data = data)
```

anyway to fix this? am i missing something ?

**Comment by alireza0** [comment]
When you disable and enable it in the panel, the problems in your config will be corrected.
Please note that:
1. we have no `limitIP`.
2. `alterId` is depricated and we dont suport it anymore.
3. `reset` is now added to the client's parameters. But when you don't have it, there should be no problem.

To fix your problem, check database ( or get inbound ) and track the diference between your configuration and corrected configuration after disable/enable

**Comment by EryX0** [comment]
> When you disable and enable it in the panel, the problems in your config will be corrected. Please note that:
> 
> 1. we have no `limitIP`.
> 2. `alterId` is depricated and we dont suport it anymore.
> 3. `reset` is now added to the client's parameters. But when you don't have it, there should be no problem.
> 
> To fix your problem, check database ( or get inbound ) and track the diference between your configuration and corrected configuration after disable/enable

hey, thanks for the response and heads up about depricated options, figured out the actual problem was that I was sending the "enabled": "true" key value to the client settings options which was wrong, i should have sent "enabled": True (no double quotation around True value) and that fixed it, i'm closing the issue.
