### ISSUE TITLE
انتقال کلاینت

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#769]
سلام امیدوارم انتقال کلاینت رو هم اضافه کنید هم گروهی هم تکی 
و دوتا پورتوکول روی یک کلاینت رو هم اضافه کنید

**Comment by wulfric93** [comment]
> سلام امیدوارم انتقال کلاینت رو هم اضافه کنید هم گروهی هم تکی و دوتا پورتوکول روی یک کلاینت رو هم اضافه کنید

سلام 
مورد اول که اضافه شده 
مورد دوم رو باید ببینیم امکان داره یا نه که کار آقای علیرضا هست

**Comment by Ghasem1243** [comment]
کجا اضافه شدن لطفا راهنمایی کنید

**Comment by alireza0** [comment]
درود بر شما
میتونید از منو اینباند در سرور نخست، گزینه کپی به حافظه رو انتخاب کنید و در سرور دوم از منوی عملیات کلی، گزینه وارد کردن سرویس، جایگزاری کنید

**Comment by Ghasem1243** [comment]
یک کلاینت از اینباند به اینباند دیگه  منظورم هست نه سرور دیگه

**Comment by alireza0** [comment]
چه سودی داره ؟
اگر با ترافیک مصرف شده اش مشکل دارید، میتونید کلاینت جدید درست کنید و مقدار باقیمانده رو برای حجمش بذارید.
خیلی کار سختی نیست. شما در نهایت باید لینک جدید به کاربر بدید
