### ISSUE TITLE
غیر فعال نشدن بعد از اتمام حجم مجاز

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/x-ui#771]
سلام وقت شما بخیر
یک باگ در قسمت غیر فعال سازی خودکار کانفیگ ها وجود داره، وقتی کاربر بیشتر از حجم مجاز مصرف میکنه کانفیگش غیرفعال نمیشه.
از ورژن ۱.۶.۲ دارم استفاده میکنم.
![Screenshot 2023-12-17 182940](https://github.com/alireza0/x-ui/assets/44028596/e03bbc4e-6867-47f4-9510-6b17b4a67de5)

**Comment by alireza0** [comment]
درود بر شما
این مورد چند بار گزارش شده. لطفا قبل از باز کردن ایشو جستجو کنید.
چندین نکته هست که باید در نظر بگیرید:
۱. این کاربری که نشون دادین غیر فعال شده! منظورتون اصولا دیر غیر فعال شدنه
۲. این پنل هر ۱۰ ثانیه چک میکنه و اگر مصرفش بیشتر از ترافیک بود دستور قطع کردن رو میفرسته. پس این مشکل پنل نیست!
۳. طبق ارزیابی های ما، وقتی کاربر در حال دانلود با پهنای باند بالا باشه، نزدیک به دو دقیقه طول میکشه که همه session های کاربر در xray به اتمام برسه. این زمان قطعی نیست. توی این مدت، مصرف کاربر گزارش میشه و توی پنل هم ثبت میشه.
۴. هدف از کنترل ترافیک، جلوگیری از لو رفتن کانفیگ بوده و اینکه کاربر قطع بشه در نهایت انجام میشه.
۵. در نسخه های گذشته ( قبل از ۱.۵.۰) که در هر تغییری، xray ریستارت میشد، همه کاربرها قطع میشدن و امکان ادامه session برای همه از بین میرفت. از زمانی که ویرایش ها با API انجام میشه، این مورد خیلی دور از انتظار نیست.

**Comment by hasan4643** [comment]
سلام من این مشکلو رو سنایی دارم حتی با حذفشون هم باز کاربر متصله و قطع نمیشه حتلا باید پنلو ریستارت کنم یوزامو انتقال دادم به علی رضا به امید اینکه حل شه مشکل ولی مثل اینکه اینم همونه😂
تانل ایپی تیبل  هستم کانفیگ vless tcp http  البه رو vmess این مشکل کمتره
