### ISSUE TITLE
تیک پروکسی cloudflare

### ISSUE THREAD

**Issue by amirmbi** [alireza0/x-ui#772]
سرور ها کار می کنند ولی تیک پروکسی cloudflare رو که میزنم از کار می افتند ... 

ssl سرتيفيكت به درستي نصب شده و سرور بروي پروتكل https بالا مي آيد....

فايروال سرور هم خاموش مي باشد و بر روي پورت هاي cloudflare نيز تست شده است ...

**Comment by asadace1** [comment]
سلام تو قسمت SSL در کلودفلار باید بزاری رو Full و از پورتهای https استفاده کنی

**Comment by amirmbi** [comment]
> سلام تو قسمت SSL در کلودفلار باید بزاری رو Full و از پورتهای https استفاده کنی

سلام ممنون از پاسخگوييتون .... بله دوست عزيز روي FULL ميذارم ولي متاسفانه به محض اينكه تغيررات اعمال مي كنم حتي با پورت هاي https هم كار نمي كند.

**Comment by alireza0** [comment]
invalid topic
