### ISSUE TITLE
Email in routing

### ISSUE THREAD

**Issue by AliMajidi1** [alireza0/x-ui#773]
![image](https://github.com/alireza0/x-ui/assets/118878444/c33fa8bd-a7e7-4357-855f-ed0bd6529a24)
سلام در قسنت روتینگ، قسمت یوزر ایمیل وجود دارد ولی قابل پر کردن نیست. (به طور مثال میخواهیم برای هر یوزر یک روتینگ ایجاد کنیم ولی در حال حاظر فقط بخش اینباند تگ کار می کند و فقط میشود روتینگ را برای کل کانفیگ اعمال کرد)
در اسکرین شات readme شما هم روتینگ شماره ۴ دارای بخش ایمیل است ولی در ادیت هیچ گزینه ای برای آن نیست.
![image](https://github.com/alireza0/x-ui/assets/118878444/45002f5f-8dad-4b31-81fd-4d41e2c30cd0)

**Comment by alireza0** [comment]
درود بر شما
بله، از قلم افتاده بود که دیروز دیدم و درستش کردم: https://github.com/alireza0/x-ui/commit/7dd5449cf41a6ebbfe3dfc68c863ee40deb05953
