### ISSUE TITLE
مشکل قطعی چند ثانیه ای کانفیگ تانل

### ISSUE THREAD

**Issue by JackyJack212** [alireza0/x-ui#774]
من سرور ایران ای دارم که با کانفیگ vmess + tcp + http به سرور خارج به صورت پنل به پنل تانل شده و کانفیگ نهایی استفاده از تانل هم به صورت vmess + tcp + http هستش ،
اما یک هفته ای میشه که در حین استفاده از کانفیگ 10 تا 20 ثانیه اتصال قطع میشه و دوباره برقرار میشه و داخل لاگ هم اصلا مشکلی نیست و حتی پنل هم ری استارت نشده.

اقدامات متفاوتی هم روی این سرور برای بهبودش تست کردم مثل عوض کردن سرور خارج، تغییر header http و... اما مشکل برطرف نشد.
سرور ایران هم از سلامت کامل برخورداره و همچنین سرعت مناسبی ارائه میده.

لطفا راهنمایی کنید...

**Comment by alireza0** [comment]
دوست گرامی، این بخش برای پرسشهای خارج از پنل ساخته نشده.
خواهشمندم از گروه های کاربران پرسشتون رو دنبال کنید.
