### ISSUE TITLE
New Filter

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/x-ui#775]
سلام عزیز
به نظرم اگر یک گزینه به عنوان (Enable) در بخش فیلتر ها اضافه بشه خیلی میتونه مفید باشه، اینجوری میتونیم کاربر هایی اشتراکشون فعال هست رو یکجا ببینیم و مدیریتشون بکنیم (چه آنلاین باشن چه نباشن)

**Comment by alireza0** [comment]
درود بر شما
نکته خوبیه. هرچند برای نمایش در گوشی دیگه جایی برای افزودن این بخش نداریم، ولی حتما بهش فکر میکنم.
