### ISSUE TITLE
سوال در مورد AllowInsecure

### ISSUE THREAD

**Issue by asadace1** [alireza0/x-ui#776]
سلام راهی نداره تو پنل وقتی لینک ساب میدیم کانفیگ با AllowInsecure ture تو گوشی ثبت بشه؟؟
برنامه های آیفون تو ستینگش AllowInsecure ندارن ک برا همیشه فعال کنیم و وقتی دستی کانفیگ رو ادیت میکنیم و AllowInsecure  رومیزاریم رو true بعدش اگه آپدیت سابسکربشن رو بزنیم دوباره برمیگرده رو false 
با اینکه AllowInsecure تو پنل true هستش ولی با Update Subscription برمیگرده false میشه
تو اندروید تو ستینگ برنامه ها AllowInsecure  تیک داره میزنی برا همیشه true هستش ولی تو ios این گزینه رو ندارن برنامه ها و مشکل ایجاد میشه
با تشکر

**Comment by alireza0** [comment]
درود بر شما
این اشتباه نرم افزار های سمت مشتری میتونه باشه. همه لینک های این پنل استاندارد هستند.

**Comment by asadace1** [comment]
> درود بر شما این اشتباه نرم افزار های سمت مشتری میتونه باشه. همه لینک های این پنل استاندارد هستند.

بعله متوجه هستم ممنون
