### ISSUE TITLE
google developer

### ISSUE THREAD

**Issue by yaramahmadi** [alireza0/x-ui#778]
سلام و احترام

برخی سرویسهای گوگل مانند:

https://developers.google.com

https://analytics.google.com

بعد از اتصال به کانفیگ با ارور403 (مثل اینکه کانفیگ متصل نباشد) از طرف خود گوگل مواجه میشوند در صورتی که باقی سایتهای فیلتر شده به راحتی کار میکنند، خواهشمند است راهنمایی فرمایید که به چه شکل این مشکل را برطرف کنیم

![image](https://github.com/alireza0/x-ui/assets/103871792/8a4574f7-722c-48d9-90eb-6b909e11f1f1)

**Comment by alireza0** [comment]
درود بر شما
این پرسش در مورد پنل نیست. خواهشندم از گروه های کاربران پیگیری کنید
