### ISSUE TITLE
DNS Setup

### ISSUE THREAD

**Issue by BorhanPourshafiee** [alireza0/x-ui#780]
![Clipboarder 2023 12 18-002](https://github.com/alireza0/x-ui/assets/95101840/254f0001-3c74-43e6-bf13-85e175cdfa7d)
امکانش هست توضیحات مختصری درباره این بخش بدید؟خیلی تلاش کردم که ازش استفاده کنم اما موفق نبودم،نکته خاصی در استفاده از DNS به عنوان Outbound هستش؟

**Comment by alireza0** [comment]
تلاش ما آسان کردن ویژگی های پشتیبانی شده در xray بوده و پرسش شما خارج از این چهارچوب است.
خواهشمندم از گروه های کاربران بپرسید.

**Comment by alireza0** [comment]
بله، این ویژگی در نرم افزار xray-core به درستی کار میکنه.
