### ISSUE TITLE
small bugs

### ISSUE THREAD

**Issue by MiniKoro** [alireza0/x-ui#783]
When the xray configuration adds "http" or "socks" outbound, if you set a password, the attribute name supported by xray is "pass", and now the generated configuration is "password" and cannot be outbound normally.

**Comment by alireza0** [comment]
Thank you for this report. I will fix it soon.
Meanwhile you can fix it in JSON mode

**Comment by alireza0** [comment]
Done!
It will be fixed in next version.

**Comment by MiniKoro** [comment]
Thank you
