### ISSUE TITLE
افزودن امکان مسدود کردن سایت های تست سرعت

### ISSUE THREAD

**Issue by aref199** [alireza0/x-ui#784]
سلام خیته نباشید
درصورت امکان قابلیت مسدود کردن سایت های تست سرعت را به پنل اضافه کنید.

**Comment by wulfric93** [comment]
<img width="425" alt="image" src="https://github.com/alireza0/x-ui/assets/117269334/78a31b3b-c151-4182-8577-b6a67a534108">

**Comment by alireza0** [comment]
درود بر شما
ساده تر اینه که همینجا وارد بشه.
