### ISSUE TITLE
1.6.4

### ISSUE THREAD

**Issue by f6rhad** [alireza0/x-ui#786]
سلام. بعد از آپدیت ورژن جدید xray از کار افتاده. قبل این آپدیت مشکلی نداشتم. چندین بار سرور و xui رو ریست کردم. مشکل حل نشد.

![image](https://github.com/alireza0/x-ui/assets/154353484/0c53d6d5-06a0-4eb6-9277-8d36b88600c2)

![image](https://github.com/alireza0/x-ui/assets/154353484/1ac9c3aa-6a61-4943-aa54-aa9f9efd2732)

![image](https://github.com/alireza0/x-ui/assets/154353484/83522e14-6a65-4ee6-a20b-adfb6e8e60f9)

**Comment by f6rhad** [comment]
> سلام، از توی پنل وقتی روی Xray Status: error میزنید، روی یه ابرک توضیحات ارور رو مینویسه، ببینید ارور مربوط به چه قسمتی از کانفیگتون هست، اگر نتونستید اسکرین شات ارور رو قرار بدید.

ممنون از کمکتون. متن پیام خطا به این صورت هست:
![image](https://github.com/alireza0/x-ui/assets/154353484/8af53f5a-7894-4635-a1a6-1ebf21e03dbb)

**Comment by f6rhad** [comment]
بعد اینکه کدهای جدید رو وارد میکنم نمیتونم ذخیره کنم . روش دوم رو امتحان میکنم الان

**Comment by f6rhad** [comment]
> از قسمت xray setting در سربرگ basic template گزینه reset to default config رو بزنید. در بعد در قسمت block میتونید سوییچ Iran IPs و همینطور Iran Domains و block ads رو روشن کنید، تا بلاک بشن.

ممنون از راهنمایی کاملتون. مشکل حل شد.

**Comment by alireza0** [comment]
@f6rhad گرامی

خواهشمندم:
۱. پیش از بروز رسانی ، نوشته های نگارش ها را درست بخوانید.
۲. از اینکه نگارش هدف با روش ساماندهی پنل شما سازگاری دارد، آگاه شوید.
۳. اگر درگیر چالشی شدید، ابتدا درستی کار خود را بیازمایید.
۴. ساختن یک پرسمان bug بدون آگاهی از درستی این کار، نادرست است.
۵. هنگامی که چالش شما به پایان رسید، پرسمان را ببندید.

با سپاس
