### ISSUE TITLE
نحوه شناسایی و فیلترینگ 

### ISSUE THREAD

**Issue by Shellgate** [alireza0/x-ui#788]
خوب دوستان مدتی بود میخواستم این مطلب رو براتون بزارم
مخصوصا این روز ها که فیلتریگ شدیدتر شده و سرور های ایرانی و خارجی شناسایی و فیلتر میشن

خوب اصل ماجرا اینه که اطلاعات ما برای اینکه مسیر یابی بشن باید از dns استفاده کنند
و وقتی ما تانل میزنیم یا مستقیم وصل میشم کلیه در خواست های ما از فیلتریگ دولت رد میشه و عملا به همه اطلاعات ما دسترسی دارن و میدونن به عنوان مثال شما به کدام سایت یا درگاه متصل هستین و چه چیزی رو درخواست کردین

وقتی ما از سرور خارجی درخواست میکنیم که مثلا Instagram رو بیاره این درخواست اول توسط کلاینت یک باز از دی ان اس های شرکت های مخابراتی عبور میکنه و کلیه در خواست ها به صورت واضح مشخص هستن
دوم وقتی این درخواست ها از سرور ایرانی به خارجی ارسال میشن و این مورد هی تکرار میشه

برای این مورد استفاده از Dnsoverhttps وDns over tls و غیره پیشنهاد میشد که درخواست ها به صورت رمز گزارس شده ارسال و در یافت میشدند حال برنامه اینه که کلیه dns سرور ها بسته و به روتر های خود کشور متصل هستن و روی سرور های ایرانی امکان استفاده از این مورد وجود نداره حتی اگه با روش هایی این مورد رو هم دور بزنید
مثلا من از ایپی استفاده کردم و دی ان اس های سرور ایرانی رو کاملا بستم
در hosts ایپی و دامنه سرورم رو تعریف کردم و نتیجه این شد که درخواست ها از سرور خارجی فقط  انجام میشد که بعد از 5 دقیقه فیلتر شدیم
یعنی سیستم اجازه عبور نمی‌ده 

با برسی چندین مرد دیگه دریافتم که کلا همه اطلاعات ما شنود میشن و تا به الان هم دولت عملا همه چی رو خونده

حال گزینه دیگری  هم استفاده از fakedns و تغییر درخواست هاست یعنی مثلا شما میخواهید از گوگل استفاده کنید این درخواست از سیستم فیلترینگ هم ثبت و رد میشه ولی در خواست به صورت یک نام دیگه مثلا 
درخواست google.com هست ولی به این صورت به سیستم خرونده میشه xurh-suf.com مثال

ولی با این وجود باز از سمت کلاینت امکان خواندن در خواست ها وجود داره واینجوری میشه که ایپی شما در جا شناسای و فیلتر میشه

باید فیلتر شکنی یا روشی باشه که درخواست ها فقط از سرور خارجی خواسته بشن یا به صورت انحرافی تا بشه سیستم رو دور زد

امنیت v2ray اصلا تضمینی نیست

این لینک هم برای دوستان علاقه مند

```
https://wikicensorship.github.io/fa/docs/measure-internet-censorship/DNS/
```

**Comment by Shellgate** [comment]
خوب دوست عزیز انگار کامل نخودین بله اگر متوجه نشه فیلتر میشه امتحان کن
Doh و dot رو نمیتونید ست کنید مگر ایرانی باشه مثل شکن

باگ نیست خود فیلتریگ و شنوده برا اطلاعات گزاشتم

**Comment by alireza0** [comment]
خواهشمندم توجه داشته باشید:
۱. جای این بحث ها در گروه های کاربری است و نه یک تاپیک در گیتهاب
۲. برچسب باگ رو باید زمانی انتخاب کنید که از خطای موجود در نرم افزار اطلاع دارید و مستند خطا دارید.
۳. لینک ارائه شده به هیج وجه مطلبی برای استفاده کنندگان از پراکسی نداره و فقط برای کاربر معمولی استفاده کننده از فیلترنت ایرانه
۴. ترافیک dns بعد از برقراری ارتباط v2ray با سرور به صورت پیشفرض از تانل پراکسی رد میشه و اصلا قابل مشاهده نیست! مگر اینکه خودتون تنظیم کنید از اینترنت معمولی رد بشه.
۵. سرویس های DoH کاملا برای ایرانی ها فیلتره!
۶. سرویس های DoH باعث کندی شدید اینترنت میشن و اصلا توصیه نمیشه.
۷. استفاده از chain of fakeDNS  ها باید با دانش کامل باشه
۸. روش کار fakeDns دادن fake IP هست و نه دامنه مجهول!
۹. امنیت یک موضوع نسبیه. تنها دستگاه امن در شبکه، دستگاه خاموشه! ولی در مورد مطلبی که گفتید، به نسبت استفاده بدون فیلترشکن، امنیت بالاتری داره.

درسته که نوشتن تجربیات میتونه به افراد کمک کنه، ولی حتما باید با یک متخصص بررسی کنید و مطمئن بشید که مطلب درسته.
در ضمن باز هم تکرار میکنم، این مطلب نه جاش اینجاست و نه مخاطبی اینجا داره.

موفق باشید

**Comment by Shellgate** [comment]
👌
بله فیلتره چون درخواست ها رو رمزگذاری میشدند و از دید فیلتر چی پنهان
در ضمن  خود باگ است چون کافیه با یک مانیتورینگ ساده منظور من رو به عمل شاهد خواهید بود تمامی درخواست ها بعد از اتصال از دی ان اس ها رد میشن 
مخاطب داره یا نداره این موضوع مهمه و کسی که هزینه می‌کنه زحمت میکشه برنامه رو ارتقا میده کاربری که مصرف کننده این این پلتفرمه فکر نمیکنم امنیت و چیز به این مهمی رو بشه نادیده گرفت

این و گزاشتم تا چاره کنید نه اینکه آموزشگاه را بندازیم

**Comment by alireza0** [comment]
> در ضمن خود باگ است

تعریف باگ یا مشکل رو میتونید جستجو کنید یا از [ویکی پدیا](https://fa.wikipedia.org/wiki/%D8%A7%D8%B4%DA%A9%D8%A7%D9%84_%D9%86%D8%B1%D9%85%E2%80%8C%D8%A7%D9%81%D8%B2%D8%A7%D8%B1%DB%8C) بخونید.

> چون کافیه با یک مانیتورینگ ساده منظور من رو به عمل شاهد خواهید بود تمامی درخواست ها بعد از اتصال از دی ان اس ها رد میشن

من نمیدونم از چه مانیتورینگی استفاده میکنید! ولی برای اثبات اشتباه بودنش نیازی به اون ندارید. کافیه بدونید سایتهای زیادی فقط از طریق dns فیلتر میشن و وقتی شما میتونید اونها رو با استفاده از v2ray client app باز کنید، یعنی درخواست dns شما از مسیر outbound منتقل شده.
در ضمن این موارد رو متونید با tcpdump و یا wireshark روی کامپیوترو یا سرورتون به وضوح ببینید.

اگر در اون مستندی که ارائه کردید این موضوع رو دیدید و منظور شما اینه که یک درخواست dns همیشه وجود داره، درسته! ولی الزاما نباید توسط فیلترچی دیده بشه! وقتی بسته dns هم از تانل v2ray رد میشه، دیگه فیلترچی نمیتونه اون رو مثل یک پکت عادی dns ببینه.

> مخاطب داره یا نداره این موضوع مهمه و کسی که هزینه می‌کنه زحمت میکشه برنامه رو ارتقا میده کاربری که مصرف کننده این این پلتفرمه فکر نمیکنم امنیت و چیز به این مهمی رو بشه نادیده گرفت

در نظر داشته باشید اگر قرار باشه هرکسی هر مطلبی در مورد شبکه و اینترنت و امنیت اینجا بذاره، از نظر شما مرتبط میشه، ولی [قوانین جامعه متن باز](https://opensource.guide/) این رو نمیگه. اینجا فقط باید در مورد کد های نوشته شده در این رپوزیتوری صحبت بشه.

> این و گزاشتم تا چاره کنید نه اینکه آموزشگاه را بندازیم

اگر منظور شما مشکل در نرم افزار سمت کلاینته ( که باتوجه به صحبت های پیشین این مورد هم صحیح نیست ) ، ما چه کمکی میتونیم بکنیم؟
نرم افزار های دیگه ریپوزیتوری خودشون رو دارن. بهتره این بحث ها با سند و مدارک درست اونجا مطرح بشه.

پیشنهاد میکنم اگر میخواهید یک باگ رو گزارش کنید، ابتدا بررسی کنید آیا این باگ هست یا نه ( رجوع کنید به تعریف ). بعد از اون مطمئن بشید که همه مدارک لازم رو دارید و میدونید از کدوم ماژول یا خط کد این مشکل وجود داره و بارها برای شما در شرایط خاصی تکرار شده. بعد با ارائه مستندات فنی کافی گزارشتون رو ارسال کنید.
اگر بتونید پیشنهادی برای رفع اون بدید هم مزید امتنان خواهد بود :)
