### ISSUE TITLE
Could you add "sockopt" in "streamSettings" settings in the GUI

### ISSUE THREAD

**Issue by adamgonglj** [alireza0/x-ui#791]
I use the x-ui as the transparent proxy server, I will use "sockopt" option in "streamSettings", could you add "sockopt" in "streamSettings" settings in the GUI.

**Comment by alireza0** [comment]
It is already implemented in inbound settings called Transparent proxy

**Comment by adamgonglj** [comment]
No, I need it in outbound settings.

**Comment by alireza0** [comment]
You can set all your needed configuration in JSON mode.
GUI is useful for amateur users and not for advanced users.

**Comment by adamgonglj** [comment]
okok
