### ISSUE TITLE
Subscription adds a proxy with domain for address, instead of listen IP

### ISSUE THREAD

**Issue by Steve-Brule** [alireza0/x-ui#794]
Hi. I am trying to set up subscriptions and it all seems to work well, except that my inbound is xray vless reality, which must listen on my VPS' IP address. However, when I add the proxy to my client using the subscription link, it always puts my domain name in the address field, which means that I can not connect to the proxy.

Is there a way to specify a listen address for the proxy so that it is respected by the subscription link? If not, this should be an option.

**Comment by Steve-Brule** [comment]
To clarify, I am running the latest stable X-Ui via docker on a debian 12 VPS.

When I substitute the domain for the VPS IP in the proxy cofig the subscription adds, everything works well.

**Comment by alireza0** [comment]
Hello @Steve-Brule ,
You can use External proxy configuration and set your IP address in domain name field.
