### ISSUE TITLE
ایمپورت لینک ساب توی نرم افزار singbox

### ISSUE THREAD

**Issue by meysamrn** [alireza0/x-ui#795]
من لینک ساب رو توی کلاینتهای nekobox , nekoray , hiddify next ایمپورت کردم و به درستی کانفیگهامو می خونه و کار می کنه ولی هر کاری می کنم نمی تونم توی کلاینت singbox لینک ساب رو ایمپورت کنم و ارور می ده
![Screenshot_20231222_014254.jpg](https://github.com/alireza0/x-ui/assets/71894773/05647403-3bd7-4ec4-8d7a-318e4de6e112)

**Comment by alireza0** [comment]
چطور میتونیم به شما کمک کنیم ؟
این مورد مربوط به نرم افزار دیگه است و توی همون ریپوزیتوری باید بررسی بشه.
