### ISSUE TITLE
Support subdirectories when UI worked through reverse proxy (via nginx for example)

### ISSUE THREAD

**Issue by iamlexs** [alireza0/x-ui#796]
I hide X-UI admin behind nginx proxy.
Access X-UI via subdirectory, for example /xuiadmin/

I configured the interface to load by adding a location for /assets/ and /xui/. It's loading.

But now an error appears on the main page: "Error: Request failed with status code 404". And Dashboard not working.

I suggest making an environment variable for such a case. If it is installed, then the root directory is changed in all necessary places

**Comment by MiniKoro** [comment]
It seems that I do the same as you, but there is no mistake. Did you fill in the wrong UI panel?

**Comment by iamlexs** [comment]
Sorry. All settings are available in the web interface. I should have gone there for the first time at the direct address
