### ISSUE TITLE
Enable / Disable in Edit client section

### ISSUE THREAD

**Issue by forkeer** [alireza0/x-ui#80]
Hi
Can developed  add Feature enable/disable in edit client for enable or disable any of client manually ?

Thanks

**Comment by alireza0** [comment]
Hello @forkeer 
There is an automatic Endable/Disable field which is controlled by backend to disable exhausted users.
This field will be `true` if the user has time/traffic and reverse if traffic/time is finished.

It is always possible to do everything.
Isn't it better to simply simulate this need by changing the expiration time to a time in the past?

**Comment by forkeer** [comment]
Hi @alireza0 
Respectfully, by changing the date for this matter, we have removed the problem statement
Suspension and unsuspension of each account is one of the requirements of an accounting system

Thanks

**Comment by alireza0** [comment]
Hi @forkeer 
I don't want to have any change in database which this feature needs.
BTW: It is not an accounting application.
