### ISSUE TITLE
محدودیت روی ساباسکرایب 

### ISSUE THREAD

**Issue by Parsam1989** [alireza0/x-ui#801]
**سلام و خسته نباشید
ممنون از زحمات شما در ارتقا پنل x ui
میخواستم ی پیشنهاد بدم
در واقع توی اختلات مجبور شدم از ای پی تمیز همراه اول استفاده کنم
و به مشتری ها بدم
مشکل اینجا بود بعضی مشتری ها میخوان هم از وای فای استفاده کنن و هم همراه اول
و اینحا مجبور به دادن دوتا کانفیگ هستیم
یک ریالیتی و یک آی پی تمیز
و اگر بخوایم محدودیت حجم بذاریم امکانش نیست
تقسیم هم کنیم ممکنه یکی کمتر مصرف داشته باشه
میخواستم بگم آیا امکانش هست واسه یک سابسکرایب بشه حجم تعیین کرد
مثلا ساب تعیین میکنم Reza 
برای رضا محدودیت حجم بذارم و تاریخ یا حتی محدودیت آی پی
مثلا حجم ۳۰ گیگ
بعد هر تعداد کانکشن با ساب Reza  باشه مجموع استفاده بشه ۳۰ قطع بشن همه کانفیگ ها
آیا امکانش هست ؟**

**Comment by aliamg1356** [comment]
شما راه حل راحتتری دارین
اینباند رو که ساختین در قسمت اکسترنال پروکسی میتونین آی پی های تمیز برای هر اپراتور رو جداگانه بدین و پورت رو هم حتما درست تنظیم کنین چون پیش فرض روی 443 میمونه و برای هر کدوم هم یک ریمارک مشخص بذارین
وقتی در این صورت لینک ساب رو میدین برای یوزر به تعداد اکسترنال پروکسی هایی که ساختین کانفیگ اد میشه و مصرف یوزر با هر کدوم از اون کانفیگها از حجم کلی یوزر کم میشه

**Comment by Parsam1989** [comment]
این رو میدونم
ای پی تمیز دردسرهای خاص خودش رو داره
ولی برای وای فای آیپی تمیز خاصی نیست و اسکن چون شاید دسترسی به اون نت نباشه سخته
و اینکه ای پی‌تمیز فقط برای همراه استفاده می‌کنیم 
برای سایر اینترنت ها از ریالیتی استفاده می‌کنیم
بحث اینه که حالا برای یه کانفیگ ریالیتی و یک آیپی تمیز 
چطور یک محدودیت حجم بذاریم که مجموع که به تون حد رسید قطع بشه

**Comment by ramtiny** [comment]
این مورد اگه اضافه بشه عالی میشه

**Comment by alireza0** [comment]
درود بر شما
در این پنل پیش فرض محدودیت حجم برای کار تجاری نیست و فقط برای پیشگیری از سوء استفاده است.
به همین دلیل سادگی پنل رو با این کار نمیتونیم به دردسر بندازیم
