### ISSUE TITLE
باگ در کلون کردن اینباند

### ISSUE THREAD

**Issue by aliamg1356** [alireza0/x-ui#805]
با سلام و خسته نباشید
امروز سه تا اینباند رو کلون کردم در پنل و ظاهرا موفقیت آمیز بود
ولی در دوتا از این اینباند های کلون شده در کانفییک استخراجی یوزر به جای پورت اینباند کلون شده ،پورت اینباند مادر قرار داده میشد
یعنی اگه پورت اینباند مادر 1254 بود و پورت اینباند کلون شده 25412،در کانفیگ یوزر پورت 1254 قرار داده میشد  
بالاجبار اینباندهای کلون شده رو پاک کرد و دستی ایجاد کردم

**Comment by alireza0** [comment]
درود بر شما
اگر شما از external-proxy استفاده میکنید، باید به صورت دستی اون رو هم بروز رسانی کنید.
در غیر این صورت مشکلی وجود نداره
