### ISSUE TITLE
باگ قطع نشدن یوزر ها بعد اتمام حجم

### ISSUE THREAD

**Issue by hasan4643** [alireza0/x-ui#806]
سلام خسته نباشین لطفا یه فکری به حال این مشکل قطع نشدن یوزر ها بکنید حتی خاموشش هم که میکنم باز طرف استفاده میکنه خودم الان تستش کردم حجم تموم شه باز وصل میشه ولی قطع و وصلی داره و کلاینتو خاموش کردم بازم وصل بود و حجم مینداخت عکساشم پیوست میکنم ببینین

<img width="770" alt="image_2023-12-24_17-48-36" src="https://github.com/alireza0/x-ui/assets/152972276/65e283b6-2250-440a-b801-19565350ea8c">
![photo_2023-12-24_18-04-14](https://github.com/alireza0/x-ui/assets/152972276/180fa1e3-0071-4a55-bcd2-20d37b2e30ca)

**Comment by alireza0** [comment]
درود بر شما
لطفا قبل از ایجاد یک ایشو، چک کنید!
https://github.com/alireza0/x-ui/issues/771#issuecomment-1861822323
