### ISSUE TITLE
حذف دست جمعی

### ISSUE THREAD

**Issue by mohammad1937** [alireza0/x-ui#807]
سلام لطفا فابلیت حذف دست جمعی اضافه کنین
مثلا 20 تا رو انتخاب کنیم یهو همشون باهم حذف بشن
خیلی لازمه
ممنون بابت همه زحماتتون

**Comment by alireza0** [comment]
درود بر شما
توی برنامه هامون بود، ولی ضررش بیشتر از سودش بود و انجام نشد.
در حال حاضر امکان حذف همه کاربران منقضی شده همزمان وجود داره.

**Comment by mohammad1937** [comment]
واقعیتش خیلی وقته منتظر این فابلیتم
اگه میشه یه بار دیگه بزارین توی برنامتون
نمیشه همه کاربران منقضی رو باهم حذف کرد. چون ممکنه یه نفر یک روز از تاریخش گذشته باشه و بخواد تمدید کنه.
ما فقط میتونیم اونایی که چند ماه از تاریخشون گذشته رو حذف کنیم.
واقعا لازمه اگه ممکنه یه بار دیگه روش فکر کنین. ممنون

**Comment by alireza0** [comment]
متاسفانه برای قابلیت هایی که فقط کار کوچکی رو ساده تر میکنن و بار زیادی رو برای کاربران معمولی ایجاد میکنه نمیتونم برنامه ای بذارم.
