### ISSUE TITLE
اضافه کردن دسترسی همکار

### ISSUE THREAD

**Issue by hasan4643** [alireza0/x-ui#808]
سلام خسته نباشین لطفا اگر امکانش هست لاگین به پنل بجز با یوزر پس ادمین برای مشتری های همکار هم اضافه کنید که فقط دسترسی به قسمت های تایین شده داشته باشن مثلا یک کانکشن

**Comment by alireza0** [comment]
درود بر شما
این پنل برای مصرف تجاری توصیه نمیشه
