### ISSUE TITLE
عدم نمایش remark  در خروجی کانفیگ

### ISSUE THREAD

**Issue by darklies** [alireza0/x-ui#81]
مشکلی که هست اینه وقتی خروجی میگیری نام client یا همون ایمیله میاد 
و این دردسره 
بخوایم بفهمیم یوزرش چیه و تمدید کنیم سخت میشه
بهتر اینه مثل 3xui   خود remark اول بیاد بعد حالا client ID

**Comment by alireza0** [comment]
درود بر شما
سپاس از همراهی و گزارشتون
بله این مورد بعد از اضافه شدن جستجو، عمدا در [Remark only email when exist](https://github.com/alireza0/x-ui/commit/8efa776cd71c97523b8dd8ed853eb5d671e62996) اضافه شده.
برای پیدا کردن کاربر میتونید از جستجو استفاده کنید.
در ضمن اگر کاربر ها ایمیل نداشته باشند از remark استفاده میشه. دلیلش هم طولانی نشدن طول remark بوده.
اگر به اون حالت قبلی عادت دارید میتونید برای کاربران جدیدتون به صورت دستی قبل از ایمیل اضافه کنید.
