### ISSUE TITLE
اضافه کردن امار دوره ای مصرف ترافیک

### ISSUE THREAD

**Issue by hasan4643** [alireza0/x-ui#811]
سلام خسته نباشی لطفا اگر امکانش هست قسمتی به پنل اضافه کنید که امار دقیق مصرفت دوره ای ترافیک سرور و کانکشن هارو نشون بده (مصرف یک روز و یک هفته و یک ماه و...)

**Comment by alireza0** [comment]
درود بر شما
این امکان برای پنل پر امکانات x-ui فشار زیادی رو روی دیتابیس و هارد دیسک میاره که با این مدل دیتابیس به صرفه نیست.

**Comment by wulfric93** [comment]
شما میتونید به منظور داشتن آمار از vnstat استفاده کنید 
نصب هم : 
snap install vnstat
