### ISSUE TITLE
مولتی پروتکل کردن پنل با یک اسکریپت ساده

### ISSUE THREAD

**Issue by Lordrichard23** [alireza0/x-ui#812]
سلام مهندس جان
وقت بخیر
https://github.com/M4mmad/3xui-multi-protocol
آیا امکان ادغام این اسکریپت یا اسکریپت مشابه با اون که حتی تاریخ انقضای اینباندهارو هم یکی کنه در پنل وجود داره؟ عملا به سادگی میشه پنل رو مولتی پروتکل کرد بدون تغییرات خاصی در پنل 
با تشکر

**Comment by alireza0** [comment]
درود بر شما
این پروسس میشه به کد های پنل اضافه بشه. ولی فشار زیادی رو روی دیتابیس میاره که ترجیح اینه که استفاده نکنیم

**Comment by Lordrichard23** [comment]
ممنون از شما،اگر بشه به عنوان یک آپشن باشه که فرد برای استفاده و روشن کردنش با توجه به اینکه پنل رو درگیر میکنه تصمیم بگیره، میتونه آپشن خوبی باشه
