### ISSUE TITLE
مشکل در اکسترنل پروکسی

### ISSUE THREAD

**Issue by mojmoj20** [alireza0/x-ui#813]
سلام و وقت بخیر 
هنگام ایجاد اینباندهای  vless websoucket tls  وقتی که اکسترنال پروکسی رو تعریف میکنیم با پورت مشخص و کاربر آپدیت سابسکریپشن میزنه  گزینه ی    request host در نسخه ی اندرئید و comuflage domain host  در نسخه ی ویندوزی خالی میمونه ( برای کانفیگ هایی که از دامینی به غیر از دامین اصلی تعریف میشن) و برای دستررسی باید کاربر اون قسمت رو بصورت دستی با دامین اصلی که به پنل وصل شده پر کنه تا بتونه از طریق اکسترنال لینک هم اتصال داشته باشه ...

یا اینکه من استفاده از این گزینه رو به درستی انجام نمیدم 

خیلی زحمت میکشید بسیار ممنونم

**Comment by alireza0** [comment]
درود بر شما
اگر شما هاست رو توی هدر ها درست تنظیم کرده باشید باید درست کار کنه.
![image](https://github.com/alireza0/x-ui/assets/12573084/cb4360e9-d3a0-4c9d-ad2a-ea4a7da0b1da)

به مقدار نام هدر توجه کنید

**Comment by mojmoj20** [comment]
درود فراوان / دقیقا مشکلم با مقدار نام هدر بود / حل شد / مرسی بزرگوار
