### ISSUE TITLE
اتصال به چند سرور به عنوان اوتباند در پنل ایران و تانل اوتباند 

### ISSUE THREAD

**Issue by kalilovers** [alireza0/x-ui#814]
سلام خسته نباشید روشی میشناسید که بشه وقتی پنل اصلی رو ایران هست و با تانل اوتباند ریلیتی متصل هستیم مثلا دوتا سرور یا دو آیپی از همون سرور به اوتباند ایران بدیم که ترافیک پخش شه و تاخیر و ریسک فیلتری کمتر شه ؟ تیکه کدش رو دارید اضافه کنیم

**Comment by PatrickstarWritesCode** [comment]
https://xtls.github.io/en/config/routing.html#balancerobject

**Comment by kalilovers** [comment]
> https://xtls.github.io/en/config/routing.html#balancerobject

یه نمونه کدشو میتونی مثال بزنی مثلا برای اوتباند با کانفیگ ریلیتی . برای دوتا سرور خارج

**Comment by PatrickstarWritesCode** [comment]
باید بالانسر ایجاد کنی و توی روتینگ رول‌ها outbound رو این بالانسر بگذاری. اون قسمت selector هم tag اوتباندهایی هستند که قراره بینشون بالانس شه.

`  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "balancers": [
      {
        "tag": "balancer_DR",
        "selector": [
          "dr-1",
          "dr-3",
          "dr-4"
        ],
        "strategy": {
          "type": "Random",
          "settings": {
            "weights": [
              1,
              2,
              4
            ]
          }
        }
      }
    ],`

**Comment by kalilovers** [comment]
> باید بالانسر ایجاد کنی و توی روتینگ رول‌ها outbound رو این بالانسر بگذاری. اون قسمت selector هم tag اوتباندهایی هستند که قراره بینشون بالانس شه.
> 
> ```
> {
>     "routing": {
>         "balancers": [
>             {
>                 "tag": "balancer_DR",
>                 "selector": [
>                     "dr-1",
>                     "dr-3",
>                     "dr-4"
>                 ],
>                 "strategy": {
>                     "type": "Random",
>                     "settings": {
>                         "weights": [
>                             1,
>                             2,
>                             4
>                         ]
>                     }
>                 }
>             }
>         ]
>     }
> }
> ```

ممنونم تشکر ببین درست میگم / دوتا اوتباند ایجاد میکنم تو قسمت اوتباند با تانل ریلیتی مثلا . pr1 & pr2   بعدش

**Comment by PatrickstarWritesCode** [comment]
شما کلا weight رو حذف کن به نظرم

**Comment by PatrickstarWritesCode** [comment]
```
{
   "routing":{
      "balancers":[
         {
            "tag":"har_esmi_doost_dari",
            "selector":[
               "outbound-1",
               "outbound-2",
               "outbound-3"
            ]
         }
      ]
   }
}
```

**Comment by kalilovers** [comment]
> ```
> {
>    "routing":{
>       "balancers":[
>          {
>             "tag":"har_esmi_doost_dari",
>             "selector":[
>                "outbound-1",
>                "outbound-2",
>                "outbound-3"
>             ]
>          }
>       ]
>    }
> }
> ```

پس تنها کاری که باید بکنم دوتا یا هرچنتا که میخوام اوتباند بدم به ایرانم و فقط این رول رو ادیت کنم و اضافه کنم به قسمت روتینگ رول ؟ بعدش تموم دیگه ؟

**Comment by PatrickstarWritesCode** [comment]
بله. البته باید ترافیک رو هم توی routing rules از بالانسر بدید بیرون

**Comment by kalilovers** [comment]
> بله. البته باید ترافیک رو هم توی routing rules از بالانسر بدید بیرون

خیلی ممنون تستش میکنم حتما لطف کردید

**Comment by nimaafallah** [comment]
> > بله. البته باید ترافیک رو هم توی routing rules از بالانسر بدید بیرون
> 
> خیلی ممنون تستش میکنم حتما لطف کردید


سلام 
شما موفق شدین ؟

**Comment by kalilovers** [comment]
> > > بله. البته باید ترافیک رو هم توی routing rules از بالانسر بدید بیرون
> > 
> > 
> > خیلی ممنون تستش میکنم حتما لطف کردید
> 
> سلام شما موفق شدین ؟

سلام نه هنوز انجام ندادم ولی تو پنلای جدید راحت تر شده فکر کنم دوتا کانفیگ مجزا به ایران بدیم اوکیه فقط باید رول لودبالانس رو هم اضافه کنیم
