### ISSUE TITLE
اضافه کردن محدودیت مصرف روزانه 5 گیگ و 10 گیگ در سرویس نامحدود برای هر کانفیگ

### ISSUE THREAD

**Issue by iamfarhad** [alireza0/x-ui#818]
اگر این فیچر اضافه بشه خیلی خوب میشه

**Comment by wulfric93** [comment]
این دیگه چه نوع نامحدودی هست ؟ خب بگو ماهی 150 گیگ یا 300 گیگ دیگه 
من که بعید میدونم توسعه دهنده پنل انجام بده

**Comment by alireza0** [comment]
بعد از تنظیم تاریخ اتمام، وقتی شما تنظیم ریست رو روی ۱ روز بگذارید و محدودیت حجم رو روی مقدار مورد نظر خودتون بذارین، پنل این کار رو اتوماتیک انجام میده

**Comment by wulfric93** [comment]
یعنی مثلا اینطوری ؟
<img width="626" alt="image" src="https://github.com/alireza0/x-ui/assets/117269334/7c02d3c6-38ca-4532-a36c-bd1ff0133f34">

**Comment by alireza0** [comment]
بله.
توی این تنظیم شما، پس از اتمام تاریخ انقضا، یکروز به تاریخ انقضای کاربر اضافه میشه و ترافیکش صفر میشه.

**Comment by wulfric93** [comment]
> بله. توی این تنظیم شما، پس از اتمام تاریخ انقضا، یکروز به تاریخ انقضای کاربر اضافه میشه و ترافیکش صفر میشه.

یعنی هر روز میتونه مثلا یک گیگ استفاده کنه تا همیشه ؟

**Comment by uzer98** [comment]
با روش بالا زمان نامحدود میشه و مصرف روزانه میتونی تعیین کنی که چیزی که شما میخوای نیست
چون شما میخوای مثلا در محدوده زمانی یکماهه روزی ۵-۱۰ گیگ حجم تعیین کنی

**Comment by iamfarhad** [comment]
> با روش بالا زمان نامحدود میشه و مصرف روزانه میتونی تعیین کنی که چیزی که شما میخوای نیست چون شما میخوای مثلا در محدوده زمانی یکماهه روزی ۵-۱۰ گیگ حجم تعیین کنی

دقیقا منظور من همین هست

@alireza0
