### ISSUE TITLE
خود پنل revese در حالت تانل rules مشکل کار نکردن 

### ISSUE THREAD

**Issue by kalilovers** [alireza0/x-ui#819]
سلام وقت بخیر من تانل رو انجام دادم و متصل شدم کیفیت خیلی خوبی هم داره تشکر از زحماتتون اما یه مشکلی هست :
طبق تصاویر من یه سری رول ها تو سرور پل یا خارج انجام دادم مثلا یه سری چیزا از وارپ رد شه و یه سری چیزا مسدود و... و کلشون هم ایپی 4 خارج شه .
 اما چون فقط یه اوتباند میشه تعریف کرد تو تنظیمات پل خارج نمیشه که همه این رول هارو باهم استفاده کرد بنابراین یا باید دایرکت باشه اتصال پل به هدف یا وارپ یا ... .
 روشی هست که بتونه همه رول هارو موقع اتصال به شبکه خارج اجرا کنه ؟ چندتا ریورس پل باهم ساختم به هرکدوم یه رول دادم ولی کار نکرد اینطوری

![photo_2023-12-30_17-00-30](https://github.com/alireza0/x-ui/assets/30160766/d7d925ff-69e7-4fb1-854b-e37225a7f7d9)
![photo_2023-12-30_17-00-25](https://github.com/alireza0/x-ui/assets/30160766/c62f672b-7973-4406-b165-f6dcd21cf4eb)

تو تصویر که میبینید اوتباند پل رو فقط میشه یه رول داد بهش . منتهی من رول های متفاوتی دارم و اغلب پنل دارا هم از وارپ استفاده میکنن و رول های دیگه

**Comment by alireza0** [comment]
درود بر شما
شما به اخطار بالای صفحه دقت نکردید
اولویت قوانین مهم هستند!
قوانین وارپ و بلاک سایتهای ایرانی باید بالاتر از قوانین تانل معکوس باشند.
از منو کناری استفاده کنید تا اولویت ها رو درست کنید

**Comment by kalilovers** [comment]
> درود بر شما شما به اخطار بالای صفحه دقت نکردید اولویت قوانین مهم هستند! قوانین وارپ و بلاک سایتهای ایرانی باید بالاتر از قوانین تانل معکوس باشند. از منو کناری استفاده کنید تا اولویت ها رو درست کنید
سلامت باشید . عالیه ! یعنی رول ریورس رو اخرش بزارم و دایرکت رو هم یکی قبل ریورس (مابقی بالای اینا) و اوتباند رو بندازم رو دایرکت اوکی میشه ؟

**Comment by kalilovers** [comment]
> درود بر شما شما به اخطار بالای صفحه دقت نکردید اولویت قوانین مهم هستند! قوانین وارپ و بلاک سایتهای ایرانی باید بالاتر از قوانین تانل معکوس باشند. از منو کناری استفاده کنید تا اولویت ها رو درست کنید

سلامت باشید . عالیه ! یعنی رول ریورس رو اخرش بزارم و دایرکت رو هم یکی قبل ریورس (مابقی بالای اینا) و اوتباند رو بندازم رو دایرکت اوکی میشه ؟

**Comment by kalilovers** [comment]
> سلامت باشید . عالیه ! یعنی رول ریورس رو اخرش بزارم و دایرکت رو هم یکی قبل ریورس (مابقی بالای اینا) و اوتباند رو بندازم رو دایرکت اوکی میشه ؟

سلامت باشید . عالیه ! یعنی رول ریورس رو اخرش بزارم و دایرکت رو هم یکی قبل ریورس (مابقی بالای اینا) و اوتباند رو بندازم رو دایرکت اوکی میشه ؟
![photo_2023-12-31_17-19-44](https://github.com/alireza0/x-ui/assets/30160766/59110b91-ec0e-434e-8f0e-97f2198bb4d2)
یعنی به اینصورت

**Comment by kalilovers** [comment]
من به هرنحوی تنظیم کردم این اولیت هارو وارپ کار نکرد . به نظرتون چطور تنظیم کنم رول ipv4-blocked-warp-api

**Comment by alireza0** [comment]
قانون وارپ احتمالا با دوتا بالترش مشکل داره.
بهتره بذاریدش قانون چهارم

**Comment by kalilovers** [comment]
> قانون وارپ احتمالا با دوتا بالترش مشکل داره. بهتره بذاریدش قانون پنجم

هرچقد بالاپایین کردم درست نشد چندتا مورد پیش اومد . اینارو هرکدوم رو تک رول هم انجام دادم ینی فقط وارپ باشه تو رول جز تانل یا فقط ایپی 4 و..

یکی اینکه حتی بعد از کار کردن وارپ , فقط تو pc کار میکرد و تو گوشی همون ایپی اصلی هارو میداد(درحالی که به محض  تغییر نوع تانل اوکی میشد) قبلا این مشکل رو داشتم که با تغییر نوع تانل به پنل به پنل اوتباند حل شده بود . 
دوم اینکه وقتی رول برای ipv4 میزاشتم کار نمیکرد تانل . نباید رول برای ipv4 بزارم 

نمیدونم چیکار کنم اینا کنار هم کار کنن خیلی تانل خوبیه ولی این رول ها خیلی باهم تداخل دارن و کانفیگ این قسمت ها خیلی مشکله

**Comment by alireza0** [comment]
اگر وارپ رو با آدرس لوپ بک ۱۲۷.۰.۰.۱ دادین، با قانون دوم هم به مشکل میخوره.
بذاریدش دومین قانون.
در ضمن چون دامنه رو معرفی کردین، حتما باید sniffing برای سرویس ها فعال باشه

**Comment by kalilovers** [comment]
> اگر وارپ رو با آدرس لوپ بک ۱۲۷.۰.۰.۱ دادین، با قانون دوم هم به مشکل میخوره. بذاریدش دومین قانون. در ضمن چون دامنه رو معرفی کردین، حتما باید sniffing برای سرویس ها فعال باشه

ترتیب قرار گیری باید چطور باشه ؟
هرکدوم اوله اول اجرا میشه ؟
 اگر با 127.0.0.1 مشکل داشته باشه چطور اونو از ایپی 4 جدا کنم که بتونم هر دورو اعمال کنم ؟
فقط یه اینباند تو ایران درست کردم که sniffing هم پیشفرض روشنه . تو خارج و جای دیگه نیازه در این باره کار خاصی بکنم ؟ چون خارج کانفیگ اینباند که نیاز نداره . کاربرا تو ایران هستن

**Comment by alireza0** [comment]
geoip:private
این آدرس شامل ۱۲۷.۰.۰.۱ هم میشه. مطمئن نیستم ولی میتونید تست کنید.
اگر توی سرور خارج هیچ اینباندی ندارید، بهتره قوانین bittorrent و privateIP ها رو فقط توی سرور ایران داشته باشید.

- بسته کاربر با اولین قانونی که مطابق بشه، از اون خروجی خارج میشه و بقیه قوانین پایینتر چک نمیشه!
- اگر توی اینباند ایران sniffing دارین دیگه مهم نیست. توی خارج هم اعمال میشه.

**Comment by kalilovers** [comment]
> geoip:private این آدرس شامل ۱۲۷.۰.۰.۱ هم میشه. مطمئن نیستم ولی میتونید تست کنید. اگر توی سرور خارج هیچ اینباندی ندارید، بهتره قوانین bittorrent و privateIP ها رو فقط توی سرور ایران داشته باشید.
> 
> * بسته کاربر با اولین قانونی که مطابق بشه، از اون خروجی خارج میشه و بقیه قوانین پایینتر چک نمیشه!
> * اگر توی اینباند ایران sniffing دارین دیگه مهم نیست. توی خارج هم اعمال میشه.

وارپ رو که نمیتونم تو ایران بزنم . نظرتون چیه بلاک هارو تو ایران انجام بدم و فقط وارپ رو تو خارج اعمال کنم ؟ اینطور که شما میگید باید تو خروجی خارج هم بلاک بشه 
منتهی میمونه دوتا چیز . یه سری رول ها لازمه فقط تو خارج باشه مثل اونکه ipv6 رو مسدود میکنه ( 0::/) و همچنین اعمال ipv4 رو کل خروجی با رول (regexp:.*)

**Comment by kalilovers** [comment]
> geoip:private این آدرس شامل ۱۲۷.۰.۰.۱ هم میشه. مطمئن نیستم ولی میتونید تست کنید. اگر توی سرور خارج هیچ اینباندی ندارید، بهتره قوانین bittorrent و privateIP ها رو فقط توی سرور ایران داشته باشید.
> 
> * بسته کاربر با اولین قانونی که مطابق بشه، از اون خروجی خارج میشه و بقیه قوانین پایینتر چک نمیشه!
> * اگر توی اینباند ایران sniffing دارین دیگه مهم نیست. توی خارج هم اعمال میشه.

وارپ رو که نمیتونم تو ایران بزنم . نظرتون چیه بلاک هارو تو ایران انجام بدم و فقط وارپ رو تو خارج اعمال کنم ؟ اینطور که شما میگید باید تو خروجی خارج هم بلاک بشه 
منتهی میمونه دوتا چیز . یه سری رول ها لازمه فقط تو خارج باشه مثل اونکه ipv6 رو مسدود میکنه ( 0::/) و همچنین اعمال ipv4 رو کل خروجی با رول (regexp:.*)

**Comment by alireza0** [comment]
منظور من دقیقا همون بلاک ها بود.
وارپ باید خارج باشه.
برای اعمال ipv4 روی خروجی باید توی همین اینباند خروجی اعمال کنید.
- نیازی نیست IPv4 for goole رو تنظبم کنید.
- خروجی تانل معکوس رو بذارید direct باشه. توی تنظیمات کلی، تنظیم خروجی مستقیم رو use IPv4 بذارید. البته میتونید این کار رو توی تنظیمات خرجی هم انجام بدید

**Comment by kalilovers** [comment]
> منظور من دقیقا همون بلاک ها بود. وارپ باید خارج باشه. برای اعمال ipv4 روی خروجی باید توی همین اینباند خروجی اعمال کنید.
> 
> * نیازی نیست IPv4 for goole رو تنظبم کنید.
> * خروجی تانل معکوس رو بذارید direct باشه. توی تنظیمات کلی، تنظیم خروجی مستقیم رو use IPv4 بذارید. البته میتونید این کار رو توی تنظیمات خرجی هم انجام بدید

اینباند خروجی ؟این قسمت رو متوجه نشد لطف میکنید دقیق تر بفرمایید 

من ipv4 رو بخاطر این تنظیم میکنم که کل ترافیک رو در این حالت رد کنه که وقتی تو خود پنل فعالش میکنم درست کار نمیکنه و اینستا و... به مشکل میخورن حتی اون بلاک هاهم بخاطر همونه . ولی وقتی از طریق رول اعمال میکنم اوکی میشه . منتهی تو این نوتع تانل اینکارو کنم از کار میوفته تانل . اوتباند معکوس رو گزاشتم رو حالت دایرکت . اون یوس ایپی 4 رو هم که همیشه تنظیم میکنم و پایینش هم میزارم رو asis

**Comment by kalilovers** [comment]
![photo_2023-12-31_19-28-27](https://github.com/alireza0/x-ui/assets/30160766/e202cc71-6d7d-4c89-960d-bfc223a476e8)
![photo_2023-12-31_19-28-26](https://github.com/alireza0/x-ui/assets/30160766/6e254543-543d-4d81-b0a0-288802daeca6)
![photo_2023-12-31_19-28-25](https://github.com/alireza0/x-ui/assets/30160766/984b99a8-433c-4605-b926-2df2d0db1004)
بلاک هارو برداشتم و طبق فرمایش شماعمل کردم فقط وارپ فعال کردم و ایپی 4 از تو پنل بدون رول .
میبینید درست کار نمیکنه ipv4 از اون قسمت . دوباره داره ایپی 6 رو هم میده بیرون وقتی رول نباشه . و اینکه باز هم وارپ فقط تو pc کار میکنه تو کلاینت های گوشی کار نمیکنه (تو تانل عادی اوتباند اوکیه)

**Comment by alireza0** [comment]
تصویر اول مشکلش تنظیم وارپه و نه پنل.
با تنظم پنل هم استفاده ازipv6 بعد از وارپ حل نمیشه.
احتمالا تست درستی توی دستگاه هاتون هم نمیگیرید. نباید تفاوتی باشه مگر اینکه تنظیمات کلاینت رو تغییر داده باشید

**Comment by kalilovers** [comment]
> تصویر اول مشکلش تنظیم وارپه و نه پنل. با تنظیم پنل هم استفاده ازipv6 بعد از وارپ حل نمیشه. احتمالا تست درستی توی دستگاه هاتون هم نمیگیرید. نباید تفاوتی باشه مگر اینکه تنظیمات کلاینت رو تغییر داده باشید

از وارپ نیستش از همون رول ایپی6 هستش که مال خود پنل درست کار نمیکنه بدون وارپ هم تستش کردم . درمورد دستگاه ها هم اوکیه(درخصوص نوع کانفیگ هستش تو ترنسمیشن tcp توی vless هدر وارپ درست کار نمیکنه بخاطر نوع تانل هم الان درست کار نمیکنه تو کانفیگ های دیگه اوکی میشه. عکسشو میفرستم 
![photo_2023-12-31_20-16-35](https://github.com/alireza0/x-ui/assets/30160766/7ff180d7-e3f8-4558-b68b-58e081dc0da8)
![photo_2023-12-31_20-16-34](https://github.com/alireza0/x-ui/assets/30160766/fc4dd25a-3e8b-4cf1-b1b2-b02d0c738986)
بخاطر مشکل ریسلاو تو تانلی که با ریورس زدم سایتای واتس مای ایپی اینا درست کار نمیکرد با گوگل تست کردم وگرنه تو اونا هم تست کردم همین مورد هستش و حتی ایپی 6 رو تانل ریورس میده ولی تو تانل اوتباند که رول برا ایپی 4 گذاشتم نمیده

**Comment by kalilovers** [comment]
اقا درست شد همش ممنون مهندس
![photo_2023-12-31_20-33-12](https://github.com/alireza0/x-ui/assets/30160766/5a35592a-1fec-4b0b-8dad-dafbeab1b18a)
این رول ایران هستش که بلاک هارو توش انجام دادم و به قول شما کامل اوکی شد فقط بیت تورنت حتما تو خارج هم بسته میشه ؟ چون هتزنر ابیوز میفرسته میبنده 
![photo_2023-12-31_20-33-13](https://github.com/alireza0/x-ui/assets/30160766/c3107317-9883-4a9f-9d31-079a957aaa81)
اینم خارج هستش که وارپو دادم بهش

اون مشکل وارپ سمت کلاینت گوشی هم درمورد اون ترنسمیشن tcp تو vless وهدر هستش که درسته . تو وارپ سمت کلاینت گوشی ها مشکل ساز هستش بعضی از پنل دارا هم این موردو داشتن  منتهی تو تانل اوتباند اینطوری نیست اوکی میشه . تو ریورس دوباره پیش اومد که الان رفع شد شاید بخاطر وارپ پلاس بوده . ایپی 6 اش هم بخاطر وارپ پنل هست که 6 هم میندازه تو چینی اوکیه . من بقیه چیزارو کامل چک میکنم میبندم ایشو رو اوکی بود

**Comment by kalilovers** [comment]
> اقا درست شد همش ممنون مهندس ![photo_2023-12-31_20-33-12](https://private-user-images.githubusercontent.com/30160766/293516280-5a35592a-1fec-4b0b-8dad-dafbeab1b18a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNDYyNTQsIm5iZiI6MTcwNDA0NTk1NCwicGF0aCI6Ii8zMDE2MDc2Ni8yOTM1MTYyODAtNWEzNTU5MmEtMWZlYy00YjBiLThkYWQtZGFmYmVhYjFiMThhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE4MDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYmNhYTViNDIyYmQ4M2M4YjNlMDc0NmNmOGRjZDI3Y2Q0MmQ3OTJlYjZiMWU4ZjljNTRmMzIzZjU1ZTU3YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lys2d7QRAutsOQkV9j5EVUAb_AswWWWL3-0WzzgDjGk) این رول ایران هستش که بلاک هارو توش انجام دادم و به قول شما کامل اوکی شد فقط بیت تورنت حتما تو خارج هم بسته میشه ؟ چون هتزنر ابیوز میفرسته میبنده ![photo_2023-12-31_20-33-13](https://private-user-images.githubusercontent.com/30160766/293516316-c3107317-9883-4a9f-9d31-079a957aaa81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNDYyNTQsIm5iZiI6MTcwNDA0NTk1NCwicGF0aCI6Ii8zMDE2MDc2Ni8yOTM1MTYzMTYtYzMxMDczMTctOTg4My00YTlmLTlkMzEtMDc5YTk1N2FhYTgxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE4MDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYjQ2OWVjNmQyOTA2ZDU0NjQ1OTA0MTAxZmJlZDFkZjA0YThkNGIwNGUzZWQ5ZGU1YWVlMjU5NWRmNDY5ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYJQlVOFLZqgyOZdSOO3QS5TsiPjgCBt79JhfP8ZLfQ) اینم خارج هستش که وارپو دادم بهش
> 
> ایپی 6 اش هم بخاطر وارپ پنل هست که 6 هم میندازه تو چینی اوکیه
> 
> فقط به نظرت چرا وقتی بعضی چیزارو از وارپ رد میکنم پینگ میره بالا ؟ بدون اینکه ترافیکی رو سایت باشه فقط خودم روشم . درحالی که باید فقط رو چیزایی که برا وارپ تایین کردم تاثیر بزاره نوسان و پینگ و... ولی رو موارد دیگه از وارپ رد نمیشن هم تاثیر میزاره

و یک سوال دیگه مهم : من الان اینباندی که تو ایران برای اوتباند سرور خارج ساختم پورتش 8443 گذاشتم چون یکی 443 برای کاربر ها هستش ولی تو خارج دیدم که 8443 اشغال نیست ! ینی میتونم همین اینباند 8443 رو به اینباند کاربر ها که 443 هست فالبک بزنم و با پورت 443 بدمش به خارج ؟

**Comment by kalilovers** [comment]
یه سوال اینکه اکر دوتا سرور پل (خارج) رو با ریورس به اوتباند یه پورتا وصل کنیم چی میشه ؟ من انجام دادم دومی کار نکرد . تانل از کار نیوفتاد ولی دومی استفاده نشد

**Comment by alireza0** [comment]
> فقط به نظرت چرا وقتی بعضی چیزارو از وارپ رد میکنم پینگ میره بالا ؟ بدون اینکه ترافیکی رو سایت باشه فقط خودم روشم در حالی که فقط برای روی چیزایی کع ازش رد میشه تاثیر بزاری ولی رو مابقی هم تاثیر گذاشته رو پینگ و نوسان و...

من اطلاعی در مورد نحوه تنظیم شما و کدی که استفاده میکنید ندارم. احتمالا مشکل از سمت نرم افزار استفاده شده است.

> و یک سوال دیگه مهم : من الان اینباندی که تو ایران برای اوتباند سرور خارج ساختم پورتش 8443 گذاشتم چون یکی 443 برای کاربر ها هستش ولی تو خارج دیدم که 8443 اشغال نیست ! ینی میتونم همین اینباند 8443 رو به اینباند کاربر ها که 443 هست فالبک بزنم و با پورت 443 بدمش به خارج ؟

بله با اینباند های پشت فالبک هم خوب کار میکنه. ولی استفاده از tls/fallback میتونه برای انتقال همه اطلاعات خروجی میتونه پردازشگر شما رو متاثر کنه. در جریان باشید! فعلا میتونید از یک پورت ساده و بدون انکریپشن هم استفاده کنید

> یه سوال اینکه اکر دوتا سرور پل (خارج) رو با ریورس به اوتباند یه پورتا وصل کنیم چی میشه ؟ من انجام دادم دومی کار نکرد . تانل از کار نیوفتاد ولی دومی استفاده نشد

به صورت پیشفرض لودبالانس میشه. البته برای کیفیت بهتر، بهتره که دوتا کاربر درست کنید توی همون اینباند و هر سرور خارج به یکی از اون کاربرها وصل بشه.

**Comment by kalilovers** [comment]
> > فقط به نظرت چرا وقتی بعضی چیزارو از وارپ رد میکنم پینگ میره بالا ؟ بدون اینکه ترافیکی رو سایت باشه فقط خودم روشم در حالی که فقط برای روی چیزایی کع ازش رد میشه تاثیر بزاری ولی رو مابقی هم تاثیر گذاشته رو پینگ و نوسان و...
> 
> من اطلاعی در مورد نحوه تنظیم شما و کدی که استفاده میکنید ندارم. احتمالا مشکل از سمت نرم افزار استفاده شده است.
> 
> > و یک سوال دیگه مهم : من الان اینباندی که تو ایران برای اوتباند سرور خارج ساختم پورتش 8443 گذاشتم چون یکی 443 برای کاربر ها هستش ولی تو خارج دیدم که 8443 اشغال نیست ! ینی میتونم همین اینباند 8443 رو به اینباند کاربر ها که 443 هست فالبک بزنم و با پورت 443 بدمش به خارج ؟
> 
> بله با اینباند های پشت فالبک هم خوب کار میکنه. ولی استفاده از tls/fallback میتونه برای انتقال همه اطلاعات خروجی میتونه پردازشگر شما رو متاثر کنه. در جریان باشید! فعلا میتونید از یک پورت ساده و بدون انکریپشن هم استفاده کنید
> 
> > یه سوال اینکه اکر دوتا سرور پل (خارج) رو با ریورس به اوتباند یه پورتا وصل کنیم چی میشه ؟ من انجام دادم دومی کار نکرد . تانل از کار نیوفتاد ولی دومی استفاده نشد
> 
> به صورت پیشفرض لودبالانس میشه. البته برای کیفیت بهتر، بهتره که دوتا کاربر درست کنید توی همون اینباند و هر سرور خارج به یکی از اون کاربرها وصل بشه.

ممنون مهندس خسته نباشی . من بعد از اینکه تانل رو برقرار کردم حدود 3 بعد از کار افتاد تا 2 ساعت مختل شد . قبلا هم تانل های ریورس تو هر دیتاسنتری انجام میدادم همینطوری میشد کاربران به این مشکل میخوردن :
![photo_2024-01-02_02-05-39](https://github.com/alireza0/x-ui/assets/30160766/1343cb53-0b36-4600-88d9-20428d35aba1)
این مال یکیشون هست البته همه به این مشکل خوردن . دقیقا این مشکل eof رو ریورس های دیگه مقل rtt با sni مشابه speedtest که هم تو اون بود هم تو این مال خود پنل استفاده شد پیش میومد . 
ولی تو تانل عادی اوتباند این مورد پیش نمیاد و اتصال پایدار تره هرچند کیفیتش در حد ریورس نیست ولی کیفیت خوب و پایداری داره با همین sni . به نظرتون مشکل چی میتونه باشه ؟

همزمان با اون اختلال و قطعی 2 ساعته پشت سر هم این ارور تو لاگ پنل بود : 
an 02 02:04:57 alireza x-ui[77416]: [Tue Jan 2 02:04:57 +0330 2024] ERROR Execution error getUpdates: request call: fasthttp do request: tls: first record does not look like a TLS handshake
Jan 02 02:04:57 alireza x-ui[77416]: [Tue Jan 2 02:04:57 +0330 2024] ERROR Getting updates: telego: getUpdates(): internal execution: request call: fasthttp do request: tls: first record does not look like a TLS handshake
Jan 02 02:04:57 alireza x-ui[77416]: [Tue Jan 2 02:04:57 +0330 2024] ERROR Retrying to get updates in 8s


این ارور تو اغلب تانل ها و حتی اوتباند اگر ارتباط تانل برقرار نشه میاد
