### ISSUE TITLE
چند سوال

### ISSUE THREAD

**Issue by smblue07** [alireza0/x-ui#82]
سلام خسته نباشید. اول از همه بابت بخش کلاینت تلگرام بسیار بسیار از شما ممنونم. فوق العاده عالی شد
مواردی که توی تست مشاهده کردم رو خدمتتون عرض میکنم
1.من با گزینه ی /inbound نتونستم کار کنم (یکی از اینباندهام اسمش PM Users 1 هستش) ولی نتونستم این مورد رو توی ربات ادمین مصرف کلاینتهاشو ببینم شاید کد رو اشتباه میزنم!
ممنون میشم راجب این بخش یکم بهتر توضیح بدید که چجوری میتونم کلاینتهای این اینباند رو ببینم

2.مورد بعدی که باهاش مواجه شدم  این بود که خود /inbound رو که خالی تایپ میکنم تمامی اینباند های داخل پنلم رو شروع میکنه دونه دونه ارسال کردن که این خب مورد بدی نیست ، موردی که واسم سواله اینه که من توی اینباندی که اعلام کردم توی مورد اول 10 تا یوزر دارم که توی پنلم نمایش داده میشه، ولی توی پیام ارسالی ربات که خدمتتون عکسشو ارسال میکنم 18 مورد رو ارسال کرده ( 10 مورد  true دارم، 8 تاش false هستش که توی پنل ریموو شده ولی همچنان توی ربات اطلاعاتشمون میاد که این عجیبه)

3.چجوری میتونم یه کلاینت رو از بیخ و بُن ریموو کنم که از دیتابیس هم حذف بشه؟!

**Comment by smblue07** [comment]
اره دیتابیسم قدیمیه
اگه کلاینت جدید ایجاد کنم با نام قبلی و حذفش کنم،  از دیتابیس حذف میشه؟؟

یه سوال دیگه ام دارم اینکه توی پنل که تایم و ترافیک تعیین میکنیم که نوتیفیمیشن ارسال کنه، واسه یوزر ریمایندرش ارسال میشه یا ادمین؟

**Comment by alireza0** [comment]
بله، به صورت نرمال باید پاک بیشه.

پیام مدیریتی و پشتیبان گیری فقط برای ادمین(ها) ارسال میشه.

**Comment by smblue07** [comment]
مچکرم🙏🙏🙏
