### ISSUE TITLE
اوتباند برای بخش بات تلگرام

### ISSUE THREAD

**Issue by babakazizigithub** [alireza0/x-ui#820]
درود جناب علیرضا
لطف کنید به سوال من جواب بدید ممنون میشم

امکانش هست که یه اوتباند بنویسیم ( مثل تانل اوتباند که کل ترافیک سرور ایران رو منتقل میکنه روی یه اینباند روی سرور خارج)  که فقط ترافیک بخش بات تلگرام رو بفرسته روی خارج و بتونیم با این حالت ربات رو روی سرور ایران فعال کنیم؟  همچین امکانی هست؟

سپاس

**Comment by wulfric93** [comment]
به این بخش توجه بفرمایید : 
https://github.com/alireza0/x-ui/issues/252

**Comment by babakazizigithub** [comment]
> به این بخش توجه بفرمایید : #252

این روش رو هم تست کردم ولی بازم کار نمیکنه - اگر شما ران کردید امکانش هست آی دی تلگرامتون رو بدید من چند دقیقه ای مزاحمتون بشم؟ شدیدا گیرم رو اون این موضوع

اگر هم نمیخوایید آی دی تون اینجا باشه من آی دیم رو میزارم زحمت بکشید یه پیام بدید        @babakazizii

**Comment by kalilovers** [comment]
> > به این بخش توجه بفرمایید : #252
> 
> این روش رو هم تست کردم ولی بازم کار نمیکنه - اگر شما ران کردید امکانش هست آی دی تلگرامتون رو بدید من چند دقیقه ای مزاحمتون بشم؟ شدیدا گیرم رو اون این موضوع
> 
> اگر هم نمیخوایید آی دی تون اینجا باشه من آی دیم رو میزارم زحمت بکشید یه پیام بدید @babakazizii
> 
> ممنونم

اینو بندازید تو قسمت اینباند تنظیمات ایکسری ایران :

[
  {
    "listen": "127.0.0.1",
    "port": 62789,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
  },
  {
    "listen": "127.0.0.43",
    "port": 443,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "149.154.167.220",
      "port": 443,
      "network": "tcp"
    },
    "tag": "telegram"
  }
]

و این دستورو هم بزنید فقط تو سرور ایران :
echo "127.0.0.43 api.telegram.org" >> /etc/hosts
و اینو هم تو سرور ایران و هم خارجتون بزنید :
ufw allow 443/tcp
ufw allow 62789/tcp
