### ISSUE TITLE
Rootless container

### ISSUE THREAD

**Issue by andrico21** [alireza0/x-ui#821]
Hi, been just curious and now have a question - is there any specific reasoning to force running x-ui with root privileges (even inside container, yes - it's still risky)?
Additionally, what about 'network_mode: **host**'?
```yaml
services:
  xui:
    network_mode: host
```
I assume one requirement might be privileged port usage or some another specific privilege/capability required (but it still can be granularly added to container). It's possible to bind 443 to some container port without any root permissions.

**Comment by alireza0** [comment]
Hello @andrico21 ,
It is just a suggestion.
Some problems may heppen due to insufficient privilages for some amateure users.
