### ISSUE TITLE
Ip limited 

### ISSUE THREAD

**Issue by Amir200h** [alireza0/x-ui#824]
با سلام خدمت جناب علیرضا،
خواستم بپرسم آیا تو برنامه تون هست که محدود کردن تعداد کاربران روی کانفیگو اضافه کنید ب برنامه یا خیر؟

**Comment by TheHolyLoli** [comment]
> درود بر شما خیر. اضافه کردن نرم افزار های جانبی و یا دستکاری پکیج xray-core رو توی برنامه هام ندارم.

آیا حداقل امکان اضافه کردن یک API برای گرفتن آیپی های کاربر از فایل access.log وجود دارد؟
