### ISSUE TITLE
enable an inboud in filter mode, doesn't work 

### ISSUE THREAD

**Issue by shiraziamir** [alireza0/x-ui#827]
**Describe the bug**
When filtering inbounds, and try to enable/disable it, it wont work. if you clear the filter, it works!

**To Reproduce**
define a filter and try to disable or enable aninboud, it just bounce back to previous state.

**Expected behavior**
We shoud be able to enable or disable an inbound when there is a filter

**Comment by alireza0** [comment]
Thank you for your report. It is confirmed and I will fix it soon.

**Comment by alireza0** [comment]
New version released. Please upgrade
