### ISSUE TITLE
How to reset a console user-password

### ISSUE THREAD

**Issue by Geil** [alireza0/x-ui#829]
Hello!
Please how to reset the forgotten user-password of the panel?
Using docker container.
Thanks!

**Comment by Enkidu-6** [comment]
To get inside the container type:
```
docker exec -it container-name sh
```
Once inside, type:
```
 ./x-ui setting -username whatever -password whatever
```
Replace the container-name with yours and of course "whatever" with whatever you want your user name and password to be.

**Comment by Geil** [comment]
Thanks a lot, man
