### ISSUE TITLE
وصل نشدن با tls فعال

### ISSUE THREAD

**Issue by lalash** [alireza0/x-ui#83]
سلام مهندس من از ورژن قبلی پنل شما استفاده میکنم و راضی هستم الان یه سرور جدید زدم و پنل آپدیت جدید را نصب کردم ولی با tls روشن در هیچ یک از کانفیگ های vmess vless trojan وصل نمیشه اصلا 
ولی در حال tls خاموش وصل میشن

**Comment by lalash** [comment]
بر گردوندم به نسخه 0.4.0 کار کرد روی همون سرور و همون سرتیفیکیت ها

**Comment by alireza0** [comment]
درود بر شما @lalash 
تست های من نشون میده که تنظیمات کاملا درست کار میکنن.
یه باگ توی تعریف alpn پیدا کردم. لطفا تایید بفرمایید که در صورت حذف alpn مشکلتون حل میشه.
در غیر اینصورت ممنون میشم اگر اطلاعات بیشتری از تنظیماتتون در اختیار من بگذارید تا بهتر بتونم مشکل رو شبیه سازی و حل کنم

**Comment by wilbernight** [comment]
![screenshot](https://user-images.githubusercontent.com/82760221/226878577-006eface-087e-4cc0-8115-1fa4d125da5d.png)
مهندس من اینجوری کانفیگ میکنم ولی کار نمیکنه کانفیگ جدید ها

این هم کد xray config
`
{
  "log": {
    "loglevel": "warning", 
    "access": "./access.log"
  },
 
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

`

**Comment by alireza0** [comment]
برای استفاده از xtls بهتره flow رو توی تنظیمات کاربر روی none بگذارید.
