### ISSUE TITLE
SSL Installation in Docker Container

### ISSUE THREAD

**Issue by Geil** [alireza0/x-ui#830]
Hello!
As I see, an SSL Certificate automatic installation process instructions are posted at the main page.
But I can't reproduce it under the Docker container, when I'm trying to type `./x-ui`, it just says some info about the app and don't show any numeric options to choose, like `17`, as it should be.
How to do it correctly?
Thanks.

**Comment by ehsaninuc** [comment]
To set up SSL certificates for your X-UI panel:

1. Use Certbot to generate SSL certificates and mount them in the container.
2. Modify your `docker-compose.yml` file to include new volume mappings:

```yml
volumes:
  - $PWD/db/:/etc/x-ui/
  - /etc/letsencrypt/archive/YOURDOMAIN/fullchain1.pem:/etc/x-ui/letsencrypt/fullchain1.pem
  - /etc/letsencrypt/archive/YOURDOMAIN/privkey1.pem:/etc/x-ui/letsencrypt/privkey1.pem
```

3. Update the X-UI panel settings to reference the actual certificate key paths as follows:

- For the Certificate Public Key Path, enter: `/etc/x-ui/letsencrypt/fullchain1.pem`
- For the Certificate Private Key Path, enter: `/etc/x-ui/letsencrypt/privkey1.pem`

Ensure you replace `YOURDOMAIN` with the actual domain name associated with the certificates and use the absolute paths, not symbolic links.

**Comment by Enkidu-6** [comment]
> 2\. Modify your `docker-compose.yml` file to include new volume mappings:

@ehsaninuc 
Linking to fullchain1.pem in archive will cause problems when the certificate is renewed. The renewed certificate will be called fullchain2.pem and then you still have a link to the expired certificate.

Also when mapping the volume, you don't need to map each file separately. You can just map the directory. Here's the more efficient way:
```
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/certs/:/etc/certs/
 ```
Then all you have to do is copy fullchain.pem and privkey.pem to $PWD/certs/ and point your panel to that directory.

To avoid having to copy the certificates every time they're renewed, create a file in **/etc/letsencrypt/renewal-hooks/deploy** and name it **001-copy.sh** and place the following code in the file:

```
#!/usr/bin/env bash

/bin/cp -Lrf /etc/letsencrypt/live/yourdomain/fullchain.pem path-to-your-$PWD-certs-directory/fullchain.pem
/bin/cp -Lrf /etc/letsencrypt/live/yourdomain/privkey.pem path-to-your-$PWD-certs-directory/privkey.pem

```
Then make sure the file is executable. Just chmod the file to 0700 . Each time a new certificate is deployed, that script will run and will copy the new certificate for you automatically.

**Comment by Geil** [comment]
Thank you very much @ehsaninuc @Enkidu-6, I'll try and revert.
