### ISSUE TITLE
x-ui.service: Failed with result 'exit-code

### ISSUE THREAD

**Issue by Bullshark21** [alireza0/x-ui#833]
سلام وقت بخیر من جدیدا یه مشکل دارم که هسته xray ام خودکار ریستارت میشه با این اررور

-- Logs begin at Sat 2024-01-06 12:31:58 CET, end at Sat 2024-01-06 18:37:01 CET. --
Jan 06 15:34:41 ubuntu systemd[1]: x-ui.service: Failed with result 'exit-code'.

چه دلیلی میتونه داشته باشه این خطا و اینکه تانل اوتباند روی سرور هست

[
  {
    "inboundTag": [
      "api"
    ],
    "outboundTag": "api",
    "type": "field"
  },
  {
    "ip": [
      "geoip:private"
    ],
    "outboundTag": "blocked",
    "type": "field"
  },
  {
    "outboundTag": "blocked",
    "protocol": [
      "bittorrent"
    ],
    "type": "field"
  }
]

اینم Routing Rules

**Comment by alireza0** [comment]
درود بر شما
توی این لاگ نشون میده که x-ui رستارت شده. این عمل معمولا دستی انجام میشه.
باید کل سرور رو چک کنید و مشکل رو پیدا کنید. اگر نتونستید با یک متخصص system admin مشورت کنید

**Comment by Bullshark30** [comment]
بخاطر مشکل رم بود فک کنم که کرش میشد 

به نظر شما ام از همین رم میتونه باشه که xui رو متوقف کنه ؟

**Comment by alireza0** [comment]
بله. میتونه باشه. سیستم عامل برای کنترل حافظه نرم افزار ها رو میتونه ببنده

**Comment by Bullshark21** [comment]
Jan 09 22:16:46 ubuntu /usr/local/x-ui/x-ui[4459]: INFO - web server run http                                                                                                                                                              on [::]:8081
Jan 09 22:16:46 ubuntu /usr/local/x-ui/x-ui[4459]: INFO - XRAY: infra/conf/se                                                                                                                                                             rial: Reading config: bin/config.json
Jan 09 22:16:46 ubuntu x-ui[4459]: panic: runtime error: slice bounds out of                                                                                                                                                              range [195:180]
Jan 09 22:16:46 ubuntu x-ui[4459]: goroutine 24 [running]:
Jan 09 22:16:46 ubuntu x-ui[4459]: x-ui/xray.(*LogWriter).Write(0xc000795340,                                                                                                                                                              {0xc000ab8000?, 0x2c8, 0xc00061f6f8?})
Jan 09 22:16:46 ubuntu x-ui[4459]:         /home/runner/work/x-ui/x-ui/xray/l                                                                                                                                                             og_writer.go:30 +0x5a6
Jan 09 22:16:46 ubuntu x-ui[4459]: io.copyBuffer({0x24da0e0, 0xc000795340}, {                                                                                                                                                             0x24d9b00, 0xc000064038}, {0x0, 0x0, 0x0})
Jan 09 22:16:46 ubuntu x-ui[4459]:         /opt/hostedtoolcache/go/1.21.5/x64                                                                                                                                                             /src/io/io.go:432 +0x1f4
Jan 09 22:16:46 ubuntu x-ui[4459]: io.Copy(...)
Jan 09 22:16:46 ubuntu x-ui[4459]:         /opt/hostedtoolcache/go/1.21.5/x64                                                                                                                                                             /src/io/io.go:389
Jan 09 22:16:46 ubuntu x-ui[4459]: os/exec.(*Cmd).writerDescriptor.func1()
Jan 09 22:16:46 ubuntu x-ui[4459]:         /opt/hostedtoolcache/go/1.21.5/x64                                                                                                                                                             /src/os/exec/exec.go:560 +0x34
Jan 09 22:16:46 ubuntu x-ui[4459]: os/exec.(*Cmd).Start.func2(0xc0000d3280?)
Jan 09 22:16:46 ubuntu x-ui[4459]:         /opt/hostedtoolcache/go/1.21.5/x64                                                                                                                                                             /src/os/exec/exec.go:717 +0x2c
Jan 09 22:16:46 ubuntu x-ui[4459]: created by os/exec.(*Cmd).Start in gorouti                                                                                                                                                             ne 9
Jan 09 22:16:46 ubuntu x-ui[4459]:         /opt/hostedtoolcache/go/1.21.5/x64                                                                                                                                                             /src/os/exec/exec.go:716 +0xa0a
Jan 09 22:16:46 ubuntu systemd[1]: x-ui.service: Main process exited, code=ex                                                                                                                                                             ited, status=2/INVALIDARGUMENT
Jan 09 22:16:46 ubuntu systemd[1]: x-ui.service: Failed with result 'exit-cod                                                                                                                                                             e'.
Jan 09 22:16:46 ubuntu systemd[1]: x-ui.service: Scheduled restart job, resta   

این لاگ دقیق تر هست اگه میتونید بررسی کنید

**Comment by alireza0** [comment]
به باگ شناخته شده توی این لاگها میبینم که توی نسخه بعدی درست میشه.
در هر صورت این حل باگ فقط کرش x-ui رو درست میکنه و xray همچنان مشکل تنظیم داره.
بیشتر مراقب تنظیمات باشید و چک کنین چه چیزی باعثش شده.

**Comment by Bullshark30** [comment]
من تو xray به صورت دستی تنظیم کرده بودم که لاگ رو error.log بنویسه در صورتی که توی دیفالت نسخه جدید این بخش حذف شده بود

**Comment by Bullshark21** [comment]
تا قبل از اینکه آپدیت رو بدید راه حلی است که از کرش x-ui جلوگیری کنیم ؟

**Comment by alireza0** [comment]
مدل خطای جدید xray باعث خطا میشه. با تعریف error.log احتمالا دیگه به x-ui نمیفرسته

**Comment by Bullshark21** [comment]
این قسمت رو حذف کردم پیشنهاد دیگه ای دارید تا قبل از آپدیت انجام بدم ؟

**Comment by alireza0** [comment]
فعلا اگر مشکلی ندارید روی نسخه قدیمی تر xray-core هم میتونید بمونید.

**Comment by alireza0** [comment]
نسخه جدید ریلیز شده. لطفا بروزرسانی کنید.
در صورت وجود مشکل، ایشو جدید باز کنید.
سپاسگزارم
