### ISSUE TITLE
cannot delete a user

### ISSUE THREAD

**Issue by rezamh79** [alireza0/x-ui#834]
Dear Alireza
there is a user without uuid , I cannot assign a UUID as well and cannot delete that user , which causes x-ui to fail 
could you please help to resolve the issue
![1](https://github.com/alireza0/x-ui/assets/52989144/c413a5b1-12a5-4078-a9ea-4db905cf9515)
![2](https://github.com/alireza0/x-ui/assets/52989144/e2e97754-4af8-44af-89f0-6d1fb49b946d)

**Comment by alireza0** [comment]
Dear @rezamh79 ,

You should not delete the UUID, due to it is a key to find the client.
To fix it, you can:
1. fix it in database directly.
2. Use copy inbound to clipboard and fix it by text editor. Then delete the inbound and import fixed JSON.
