### ISSUE TITLE
عدم نمایش آنلاین و حجم

### ISSUE THREAD

**Issue by Amir200h** [alireza0/x-ui#839]
سلام جناب علیرضا
تو پنل ، مشتری وصل شده و داره استفاده میکنه، ولی نه آنلاینشو میزنه نه حجمشو، حجمش صفر مونده

**Comment by alireza0** [comment]
درود بر شما
این مورد باگ نیست. تنظمات xray رو به پیش فرض برگردونید.
لطفا قبل از اینکه ایشو باز کنید از صحت مشکل مطمئن بشید و با مدارک کافی ارسال کنید.
