### ISSUE TITLE
Show the first client's info to everyone by using /usage command in Tg bot

### ISSUE THREAD

**Issue by OhSorrow** [alireza0/x-ui#84]
**تعریف باگ**
با درود. در صورت اتصال ربات تلگرام به پنل و ارسال دستور /usage بدون پارامتر توسط هر کاربر غیر ادمین، اطلاعات client اول موجود در پنل برای کاربر ارسال میشود.

**مراحل**

1. اتصال ربات تلگرام به پنل
2. تعریف Client در پنل (برای مثال از نوع vmess)
3. ارسال دستور /usage بدون پارامتر به ربات تلگرام (توسط هر کاربر تلگرام غیر ادمین)
4. مشاهده اطلاعات Client اول تعریف شده در پنل

**رفتار مورد انتظار**
عدم نمایش اطلاعات Client ها و نمایش ارور به علت عدم ارسال پارامتر (id)

**Comment by alireza0** [comment]
درود بر شما
ممنونم از گزارشتون
حتما تصحیح میکنم.
سپاسگزارم

**Comment by OhSorrow** [comment]
سپاس از زحمات شما
