### ISSUE TITLE
نحوه استفاده از وایرگارد 

### ISSUE THREAD

**Issue by kalilovers** [alireza0/x-ui#848]
سلام وقت بخیر خسته نباشید
 چطور میتونم از حالت وایرگارد پنل استفاده کنیم ؟ 
به فرض من یک سرور داخل دارم دوتا خارج . تانل به صورت اوتباند هستش از ایران به خارج . حالا توی خارج میخوام غیر از وارپ از وایرگارد هم استفاده کنم به این صورت که رو خارج دومم وایرگارد بیارم بالا و بدمش به خارجی که روش تانل شده و یه لیستی بهش بدم تا اون رو از خارج دومم رد کنه (مثلا خارج دومم امریکا هستش . خارج اولم المان که گوگل و.. رو از وارپش رد کنه و موارد دیگه رو که من تعیین میکنم از وایرگارد و درواقع سرور امریکام رد کنه) 

من هرچقد سعی کردم نتونستم رو پنل امریکام وایرگارد بالا بیارم به صورت اینباند همچین قابلیتی رو نیاورد . مقاله اموزشی دارید براش چطور وایرگارد رو ران کنم تو هر دو سرور ورودی و خروجی

**Comment by kalilovers** [comment]
من سعی کردم از socks استفاده کنم یه ساکس تو المان ساختم اینباند دادمش به به اوتباند ساکس امریکا . تو رول امریکا یه سایت اضافه کردم ولی کار نکرد میرفتم تو اون سایت ارور quic پروتکل میداد بعدش udp رو هم تو اینباند ساکس المان تیک زدم باز حل نشد هیچ حتی رم و پردازنده المان هم به شدت افزایش پیدا کرد تا حدود 100 درصد بعد اینکه از فایروال بستمش به حالت قبل برگشت

**Comment by alireza0** [comment]
درود بر شما
چند دقیقه پیش نسخه جدید ریلیز شده که این کار رو برای شما ساده میکنه

**Comment by vpnagency** [comment]
لطفادر مورد نحوه استفاده از وایرگارد توضیح دهید
با سپاس

**Comment by kalilovers** [comment]
> درود بر شما
> چند دقیقه پیش نسخه جدید ریلیز شده که این کار رو برای شما ساده میکنه

اره خیلی ممنون چند دقیقه بعد از ایشو باز کردنم منتشر کردید 😅
