### ISSUE TITLE
ساخت کانفیگی که خروجیش دو یا چند کانکشن داشته باشه

### ISSUE THREAD

**Issue by alihosseinii67** [alireza0/x-ui#849]
سلام وقت بخیر میشه کانفیگی ساخت که خروجی لینک سابسکرایبشنش دوتا کانفیگ داشته باشه که دوتا سابدامین متفاوت بده به کاربر تو هر کدوم هدر جدا ست کنیم چون رو بعضی اینترنتا هدر speedtest جوابه بعضی دیگه جواب نمیده

**Comment by alireza0** [comment]
درود بر شما
از ExternalProxy برای ارائه چند لینک در سابسکرپیشن میشه استفاده کرد.
اگر میخواید چند کلاینت ساخته شده با یک لینک سابسکریپشن ارائه بشه، باید Subscription ID رو توی همه اون کاربر ها یکسان تنظیم کنید. در اینصورت لینک برای همه اون تنظیمات یکی میشه.
