### ISSUE TITLE
   دستور usage ربات تلگرام

### ISSUE THREAD

**Issue by mostafa5804** [alireza0/x-ui#85]
سلام و عرض خسته نباشید
در قسمت ربات؛ اگه یک کاربر  دستور /usage رو خالی بزنه مشخصات کانفینگ یکی از کاربرا رو میاره
برای همه کاربرا هم فقط یک کاربر خاص رو میاره
نتونستم بفهمم چرا
![Screenshot_20230320_220929](https://user-images.githubusercontent.com/122720103/226436107-5a4f9c86-851a-4259-ab76-729cc22c6a43.jpg)

**Comment by mahdi449** [comment]
دقیقا من چند تا سرورم روی یک بات ست شده منم همین مشکل رو دارم 
/usage خالی میزنه مشخصات یک یوزر رو برمیگردونه هربار عوض میشه

**Comment by mahdi449** [comment]
@mostafa5804 اون یوزر که اول استفاده کرده پاک بشه دوباره ساخته بشه یعنی درست میشه ؟
