### ISSUE TITLE
گزارش باگ بخش محاسبه ترافیک و لود سنگین و ایجاد ترافیک فیک روی سرور

### ISSUE THREAD

**Issue by hamid8080** [alireza0/x-ui#850]
درود وقت بخیر
چند روزی هست یه لود فیک اومده روی پنلم مثلا کاربر آنلاین نیست اما براش ترافیک می اندازه و همین طور در میزان ورودی و خروجی سرور به شدت افزایش پیدا کرده به طوری که cpu صد میشه
به طوری که در چند روز گذشته چند میلیون الکی پول ترافیک تانل دادم زود به زود حجم یوزر ها تمام میشه در حالی که استفاده نمی کنن

از نسخه ها ی مختلف پنل استفاده کردم اما مشکل رفع نشد
لیمت هم کلا صفر کردم و.... بازم درست نشد
از دوستام پرسیدم اونا هم مشکل منو داشتند

مثلا الان ترافیک یکی از یوزر ها رو ریست کردم اما با وجود آفلاین بودن ترافیک براش ثبت میشه معلوم نیست ترافیک واسه چیه
لطفا یه فکری برای این باگ کنید در جند روز گذشته کلی هزینه الکی تانل دادم به خاطر این باگ
![1](https://github.com/alireza0/x-ui/assets/90449878/89975305-b642-4072-825a-cd428619305e)
![2](https://github.com/alireza0/x-ui/assets/90449878/e5e66c3e-df62-4004-bbd4-e0be6972bc14)

**Comment by alireza0** [comment]
درود بر شما
اینکه هزینه کردید مشکلی رو اعلام نمیکنه.
اگر این مشکل رو چند روزه دارین و قبلا نداشتین، ربطی به پنل نداره.
اطلاعات مصرف کاربر ها به شکل کاملا امنی در خود سرور از xray-core گرفته میشه و پنل توش دخالتی نداره.
در واقع امکان ثبت ترافیک بدون مصرف کاربر وجود نداره!
ولی اگر ترافیک زیادی روی سرورتون هست مربوط به امنیت سرور شما میشه و نه پنل.

همینطوری که بارها اعلام کردم، لطفا اول درک درستی از مفهوم باگ داشته باشید و پس از اون با مدارک کافی محل باگ رو پیدا کنید و اگر مربوط به کد های پنل هست میتونید اینجا اعلام کنید.
در رپوزیتوری های متن باز، چون همه کدها باز هستند، همه میتونن این کد ها رو چک کنند و مشکل رو پیدا کنند.
این بخش گزارش برای بهبود کارایی کدها و کمک به بهینه کردن کار همه کاربران نرم افزار هست و نه برای کمک رایگان برای حل مشکلات شخصی

از درک شما سپاسگزارم

**Comment by hamid8080** [comment]
ممنون که پاسخ دادید 
حرف شما کاملا درسته وقتی جسارت نشه من مظور بدی نداشتم شما کارتون خیلی درسته قدر دان شما هستیم
ولی مشکلی که الان باهاش بر خوردم  طوری هست یوزر اصلا به کانفیگش متصل نیست اما ترافیک براش محاسبه میشه یا مثلا برای یوزر های آنلاین هم ترافیک اضافه بر مصرف محاسبه میشه 
این مشکل دقیقا بعد از آپدیت پنل برام به وجود اومده 
سرور های مختلف هم تست کردم اما مشکل رفع نشد 
من اصلا با هزینه اش مشکلی ندارم اگر می تونید مشکلم رو حل کنید هزینه اش هم هر چقدر که باشه  تقدیم می کنم 
تمامی مواردی که گفتید چک کردم اما مشکلم حل نشد

**Comment by alireza0** [comment]
همونطوری که عرض کردم ترافیک رو xray محاسبه میکنه و این پنل فقط ذخیره میکنه.
باید مشکل رو جایی دیگه دنبالش باشید.
مشکل شما میتونه مربوط به نوع تنظیمات شما باشه.

نکته ای که مهمه اینه که تشخیص آنلاین بودن کاربر فقط با چک کردن ترافیک انجام میشه.
یعنی کاربری که ترافیک داره آنلاین نشون داده میشه. اگر برای کاربری ترافیک ثبت شده!
پس حتما کاربر زمانی آنلاین بوده و توی اون لحظه ای که شما چک میکنید غیر فعال شده

**Comment by mokhtarabdi** [comment]
نوع تانل بی نهایت تاثیر داره . من یه نوع ریورز زدم همین مشکلو داشتم به نظر من نوع تانلتو عوض کن
