### ISSUE TITLE
اضافه کردن Fragment به پنل

### ISSUE THREAD

**Issue by alipour66m** [alireza0/x-ui#852]
با سلام خدمت علی رضای عزیز

قطعا بیشتر از هر کسی میدونی که در این شرایط سخت چقدر نیاز به تنظیمی برای فرگمنت ClientHello و آی پی سگمنت داریم.
فکر میکنم تنها فردی که کل ایران بهش بتونن تکیه کنن خودت باشی.

یه حرکت بزرگی بزن مرد

**Comment by alireza0** [comment]
درود بر شما
این امکان وجود داره و توی Outbound میتونید پروتکل freedom رو با این مدل تنظیم کنید.
اگر منظورتون سمت کلاینته که متاسفانه اینک ها ساپورت نمیکنن و شما باید به صورت دستی اونها رو تنظیم کنید.

**Comment by alipour66m** [comment]
منظورم داخل پنله که بشه تنظیم کرد و دستی نباشه
________________________________

**Comment by alireza0** [comment]
داخل پنله و دستی نیست.
اگر منظورتون سمت کاربره، امکانش ربطی به پنل نداره و نرم افزارها ندارند.

**Comment by hrgh1985** [comment]
درود بی کران
وقتت بخیر
لطفا در صورت امکان در خروجی نمایش کیو آر فرگمنت یک کلید اضافه شود برای خروجی گرفتن فایل json که در سیستم یا گوشی ذخیره شود. مانند ircfspace.github.io که کانفیگ بهش میدیم - خروجی فایل json میدهد.
با سپاس

**Comment by alireza0** [comment]
@alipour66m 
درود بر شما
نیازی به دکمه زدن نیست. وقتی شما برای ساب json فرگمنت رو فعال کنید، به صورت اتوماتیک در کانفیگ نهایی اعمال میشه. کافیه qrcode مخصوص json رو اسکن کنید و یا لینکش رو از اطلاعات بیشتر کپی کنید.

**Comment by alireza0** [comment]
@hrgh1985 

خواهشمندم اگر نیاز شما با ویژگی جدید sub json حل شده، این ایشو رو ببندید.
سپاسگزارم

**Comment by hrgh1985** [comment]
بله دیدم - بسیار عالی و ممنونم - فقط اگر مقدوره مانند ircfspace.github.io
یک روتینگ رول بهش اضافه بشه - که برای استفاده از برنامه های ایرانی نیاز به قطع کردن فیلتر شکن نباشد.

**Comment by alireza0** [comment]
استفاده از روتینگ منوط به وجود فایل geosite توی نرم افزار کاربره. در غیر اینصورت اتصال با خطا مواجه میشه.

**Comment by hrgh1985** [comment]
سلام و احترام
چن وقت پیش یک پنل توسط ایمان آقاپور معرفی شد [Libertea ](https://github.com/VZiChoushaDui/Libertea/blob/master/README-fa.md)
https://www.youtube.com/watch?v=InEpCcFnwvI

اینطوری که توضیح میدن توی این پنل دایرکت شدن سایت های ایرانی کار میکنه و نیازی به فایل نداره.
امکان پیاده سازی در x-ui نداره؟

**Comment by alireza0** [comment]
درود بر شما
هر مدل پیاده سازی بدون فایل، کامل نمیتونه باشه.
این فایل ها باید توسط کلاینت همیشه بروزرسانی بشن. خوشبختانه خیلی از کلاینت ها ساپورت میکنن و میشه اضافه کرد.
پنل معرفی شده ساب کانفیگ رو ارائه میده و این مدل ساب امکان اضافه کردن روتینگ رو نداره.
این کار توسط ساب json قابل انجامه و سعی من اینه که برای نسخه بعد آماده‌اش کنم
