### ISSUE TITLE
wireguard 入站功能缺失

### ISSUE THREAD

**Issue by Songxwn** [alireza0/x-ui#853]
![image](https://github.com/alireza0/x-ui/assets/21145071/7c1507bf-ce23-41a8-84b2-a90eabf52887)

1. Unable to configure Peer IP
2. Unable to generate QR code or export configuration file
3. Peer public key shared key cannot be automatically generated.

**Comment by wulfric93** [comment]
it seems that wireguard is only applicable to outbound

**Comment by MiniKoro** [comment]
In fact, I don't quite understand why it is necessary to wireguard inbound, usually not for outbound?

**Comment by Songxwn** [comment]
Thanks to the developer for the answer, you can refer to this project for client access generation.

https://github.com/ngoduykhanh/wireguard-ui

**Comment by alireza0** [comment]
The concept behinh the Wireguard protocol in xray-core is for tunneling known servers.
Most Wireguard client apps are able to prepare their own key-pair. Therefore client's public key should be stored in wireguard inbound. That means we should prepare client and server together and exchange the public keys.

We cannot expect that peers could play a rule as well as clients in other potocols like VLESS.
By this concept, in my opinion it is not necessary to prepare client's configs in advance.

Wireguard links have two two models: `wireguard:// `and `wg://`

I will take a look at other applications if I can convert it to sth like multi-client interface.
Then it is also possible to convert the link in outbound modal.

**Comment by Songxwn** [comment]
xray wireguard inbound is a site-client function, not a site-to-site function. I feel it is better to automatically generate Peer configuration to facilitate client access.

**Comment by alireza0** [comment]
@Songxwn Actually it is not true!
Wireguard protocol is a peer-to-peer protocol and not site-client.
But hopefully we can convert it to multi peer configuration with providing link+qrcode.
I should find a standard way for it.

**Comment by alireza0** [comment]
@OnceUponATimeInAmerica
Sorry! I didn't answer in this issue.
Yes, based on this thread and #896 , it was tested and deployed.
I hope it could help.
Don't hesitate to inform me if there is any problem or ambiguity.

**Comment by Songxwn** [comment]
Thank you very much for the support. I feel that after testing, it can be closed.
