### ISSUE TITLE
How can I reset all parameters to their default settings using a Docker container? Thank you!

### ISSUE THREAD

**Issue by taotao1058** [alireza0/x-ui#855]
Hello! First, I would like to thank the developers for their dedication. I have forgotten the login parameters for the panel, including the port, path, and password. How can I reset all parameters to their default settings using a Docker container? Thank you!

**Comment by Enkidu-6** [comment]
https://github.com/alireza0/x-ui/issues/829#issuecomment-1874688495

**Comment by Enkidu-6** [comment]
And
```
./x-ui setting -h
```
for everything else

**Comment by taotao1058** [comment]
> And
> 
> ```
> ./x-ui setting -h
> ```
> 
> for everything else

Thank you!
