### ISSUE TITLE
خطای : cp.cloudflare.com not resolve 

### ISSUE THREAD

**Issue by lucaswhob** [alireza0/x-ui#859]
با سلام
متاسفانه بروی گوشی های شیائومی با اندروید 7 و 10 و 11 من تست می کنم 
شدوساکس این پیام رو برگشت می دهد متاسفانه : cp.cloudflare.com not resolve 
کارهای انجام شده جهت حل مشکل که بی فایده بوده است 
1-ست کردن کاستون دی انس بروی گوشی مستقیما
2-تغییر دادن encryption و تست کردن encyption های مختلف هنگام ساخت اینباند شدوساکس
3-غیرفعال کردن ای پی 6 بروی سرور
4-تست نسخه های مختلف شدوساکس از اخرین نسخه و تست کردن قدیمیترین نسخه ها دانلود شده از این لینک : 
https://apkpure.net/shadowsocks/com.github.shadowsocks
متاسفانه بروی گوشی های شیائومی این مشکل دیده می شود بروی سایر برندها اوکی هست و مشکلی نداریم
ضمنا اتصال با سرور برقرار می شود اما هیچ ارسال دریافتی نداریم
همین انفیگ بروی سایر برندها کار می کند دقیقا
ممنون میشم کمک کنید

**Comment by alireza0** [comment]
درود بر شما
من متوجه نشدم باگ پنل اینجا چیه!؟
