### ISSUE TITLE
Filter out anything after last @ from email inclusive of the sign itself to generate links

### ISSUE THREAD

**Issue by ariandcir** [alireza0/x-ui#86]
Hey mate,

since now the telegram bot supports users checking their own details, if we add the telegram id at the end of their connection name, in case of copying the connection link after the addition of telegram id to the name, the telegram id would be included in for example the vless address or the name key used when constructing the vmess json.

I reckon because of this on the frontend, there should be a filtering done to Filter out anything after last @ from email inclusive of the sign itself to generate links

Cheers

**Comment by alireza0** [comment]
Hello @ariandcir 
Thank you for this report.
Actually, `Remark` is a tag just for describing the configuration name in client application. ( and nothing more! )
It is designed to be like this. Your request might affect requrements of all others.

You can simply remove or change the Remark manually. It doesn't affect the configuration.

**Comment by ariandcir** [comment]
Sorry I was referring to the connection remarks/emails not the inbound remarks

**Comment by alireza0** [comment]
The term `Remark` which I mentioned, is a term which we use for naming the link in clinet applicaiton.
```
vless://${uuid}@${address}:${port}#${remark}
```
You can manually change the `remark` value in the link. It is just a simple text which will be usefull only in client application for naming the config!
