### ISSUE TITLE
Please add "First" to right-click menu of Xray configs->Outbounds for setting the "main outbound" from UI

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [alireza0/x-ui#861]
سلام.

میخواستم امکان اضافه کردن "First" یعنی "برو به بالاترین مکان" رو به منوی هر سطر برای صفحه اوتباند ها در قسمت کانفیگ xray جویا بشم (علاوه بر گزینه های فعلی که delete , edit  هستن).

چون اگرچه ترتیب بقیه اوتباندها زیاد مهم نیست و استفاده ازشون طبق قوانین روتینگ تعیین میشه اما اوتباند اول اهمیت داره و طبق [داکومنت های ایسکری](https://xtls.github.io/en/config/outbound.html#outboundobject) وقتی رولی match نشه از اون اوتباند استفاده میشه و یه نوع default/main outbound محسوب میشه و خوبه که این موضوع در x-ui  هم مورد تاکید قرار بگیره تا کاربرها آگاه باشن.

البته بر خلاف صفحه روتینگ لازم نیست "up"  , "down"  اضافه بشن و فقط "first" مهمه.

با تشکر

**Comment by alireza0** [comment]
درود بر شما
بله، در جریان هستم و براش برنامه دارم.
ممنون از یادآوری. این ایشو رو باز میذارم تا انجام بشه و بهتون اطلاع میدم.

**Comment by alireza0** [comment]
این ویژگی افزوده شد. در نسخه آینده میتونید ازش بهره برداری کنید.
با سپاس
