### ISSUE TITLE
دیسبل نشدن اینباند ها

### ISSUE THREAD

**Issue by babakazizigithub** [alireza0/x-ui#862]
درود مهندس علیرضا
آقا در ورژن جدید 1.7 نمیشه اینباند ها رو disable کرد

**Comment by alireza0** [comment]
درود بر شما
بله این باگ شناخته شده بود در روز اول ریلیز و با https://github.com/alireza0/x-ui/commit/30d73764632607727e0657eba5d78f889edb12ac حل شد. در نسخه بعد این مورد برطرف میشه.
برای راه حل موقت از ویرایش استفاده کنید.

**Comment by wulfric93** [comment]
> درود بر شما بله این باگ شناخته شده بود در روز اول ریلیز و با [30d7376](https://github.com/alireza0/x-ui/commit/30d73764632607727e0657eba5d78f889edb12ac) حل شد. در نسخه بعد این مورد برطرف میشه. برای راه حل موقت از ویرایش استفاده کنید.
ممنون میشم زودتر ریلیز کنید واقعا نیازه 
سپاس از شما
