### ISSUE TITLE
A small suggestion: Please make the SSL prompt in the red box on the home page smaller. Don't use red, otherwise it will greatly affect the appearance.

### ISSUE THREAD

**Issue by taotao1058** [alireza0/x-ui#865]
**A small suggestion: Please make the SSL prompt in the red box on the home page smaller. Don't use red, otherwise it will greatly affect the appearance. It would be better if it could be removed. Because anyone who knows how to set up a custom proxy knows that without SSL, it's not secure. People who don't understand SSL will definitely not know how to set it up.**
 
 
 
![web111](https://github.com/alireza0/x-ui/assets/115192496/5475d39c-7d7d-4b18-b170-ade19eadfe61)

**Comment by Enkidu-6** [comment]
There's a reason it has an x on the top right.

**Comment by taotao1058** [comment]
> There's a reason it has an x on the top right.

**It still appears after switching pages or re-entering the panel. Cannot be closed permanently**

**Comment by alireza0** [comment]
@taotao1058
If you know about consequences of using insecure HTTP, please pay attention to the alarm.
Security is more important than design.

As our friend @Enkidu-6 mentioned, X is there. IMHO it should not be closable till you follow the security principles
