### ISSUE TITLE
نحوه کانفیگ وایرگارد در اینباند سرور دوم و افزودن به اوتباند سرور اول

### ISSUE THREAD

**Issue by kalilovers** [alireza0/x-ui#866]
سلام وقت بخیر خسته نباشید 
من یه سری رولم میخوام از وارپ رد شه یه سری هم از وایرگارد خارجم
پنل بروزه وارپ وایرگارد اوکیه 
ولی یه اینباند تو امریکام ساختم دادم اوتباند المانم و تو رول یه سری سایت دادم که از اون رد شه ولی کار نکرد . البته اشناییت کاملی ندارم باهاش چون همین این قسمت خالیه تو اینباند امریکا :
![Screenshot 2024-01-16 161935](https://github.com/alireza0/x-ui/assets/30160766/6ca6dc12-7119-4ac2-bdd2-04a1d66b7887)

هم این قسمت تو اوتباند المان ::

![Screenshot 2024-01-16 1622113](https://github.com/alireza0/x-ui/assets/30160766/0c0c9e57-28c0-4c37-8f7a-7f833eea2c39)

ممنون میشم نحوه کانفیگ این دو قسمت رو بهم بگید
ایپی و پورت کجا ادد میشه 
چطور میتونم محدود کنم ورود به اینباندم رو مثلا به ایپی خاص

**Comment by alireza0** [comment]
درود بر شما
سوال شما در مورد نحوه کارکرد پروتکل هست ولی در این بخش سوالات مربوط به پنل رو بررسی میکنیم.
خواهشمندم برای پیدا کردن جواب، گوگل کنید و موارد رو تست کنید.
