### ISSUE TITLE
 اتصال یک سرور ایران به چندتا سرور خارج 

### ISSUE THREAD

**Issue by ghost** [alireza0/x-ui#867]
درود وقت بخیر
من یک سرور ایران دارم با چندتا خارج 
آیا ممکنه هر اینباد ایران به صورت جدا گونه متصل کرد به یک سرور خارج ؟
به طوری که یوزر ها در سرور ایران ساخته شوند تا بتونم از طریق Subscription لینک تمامی سرور ها بدم به کاربر 
آیا راهکاری وجود دارد ؟

**Comment by alireza0** [comment]
درود بر شما
این مورد ربطی به پنل نداره و در مورد امکانات xray-core میتونه باشه.
بله این امکان در xray-core وجود داره.
با نمایش گرافیکی که به تازگی در پنل ارائه شده میتونید این تنظیمات رو بصورت راحت تری انجام بدید.
برای آموزش بهتره در گروه های کاربری و یا یوتیوب در مورد خروجی ها و قوانین مسیریابی جستجو کنید
