### ISSUE TITLE
Auto restart

### ISSUE THREAD

**Issue by ArfatRahman** [alireza0/x-ui#868]
It will be best if there is an auto restart the x-ui panel, using timer. 

Like, auto restart on Which time. And add multiple times in a day to restart.

The main reason for this is that sometimes the server goes down and not working...

**Comment by alireza0** [comment]
Auto restart is exist in services in case of any crashes.
If you need to add manual restart without any reason ( or due to outbound problems ) you can add it yourself in crontab

**Comment by alireza0** [comment]
It is related to system admin's duties. If you don't know how to set it, my suggestion is not to touch it!
One of the simple solution for this action is:
(do it only once)
```bash
echo "0 0 * * * root systemctl restart x-ui" | sudo tee -a /etc/crontab
```

Please be informed that every unknown changes in your server may cause problem.
