### ISSUE TITLE
regex in routing panel

### ISSUE THREAD

**Issue by mmrabbani** [alireza0/x-ui#87]
**Describe the bug**
regex cannot e used in routing panel.

**To Reproduce**
1. Go to panel setting - xray configuration - configuration of routing rules
2. add text below
  {
    "domain": [
      "regexp:.+\.ir$"
    ],
    "outboundTag": "blocked",
    "type": "field"
  },
4. save and restart panel
5. regex routing is not saved

**Expected behavior**
It is expected that routing configuration is saved in config file.

**Comment by alireza0** [comment]
Hello @mmrabbani 
It is about safety process which avoid configuration with json's syntax error to be saved.
Please check your syntax.

**Comment by mmrabbani** [comment]
I have checked this. I', using syntax "regexp:.+.ir$" in client side already and it works (It refers to all .ir top level domains). I cannot check it in server side because of this safety process.
It seems that the safety process is very strict and needs to be looser. I don't know if the process is developed in this project or the safety process is an independent project that is used in this project.

**Comment by alireza0** [comment]
It is in frontend! It will convert the text to JSON. And if it isnot a valid syntax, you can see the console error.
Please check if you write it in a coorect place with correct syntax like this:
```
[
  {
    "inboundTag": [
      "api"
    ],
    "outboundTag": "api",
    "type": "field"
  },
  {
    "ip": [
      "geoip:private"
    ],
    "outboundTag": "blocked",
    "type": "field"
  },
  {
    "domain": [
      "regexp:.+.ir$"
    ],
    "outboundTag": "blocked",
    "type": "field"
  },
  {
    "outboundTag": "blocked",
    "protocol": [
      "bittorrent"
    ],
    "type": "field"
  }
]
```
**Please be informed that this config will deny access to domains ended by `.ir`**
if you want to allow them to use `.ir` domains with normal internet, it is not a correct solution!

**Comment by mmrabbani** [comment]
This is accepted and worked. Thank you.
