### ISSUE TITLE
enable warp

### ISSUE THREAD

**Issue by er212121** [alireza0/x-ui#870]
**Describe the bug**
i want to enable Warp in latest version 
but i faced this issue
 Fail: invalid character 'e' looking for beginning of value
**To Reproduce**
1. Go to 'xray configs ..'
2. Click on 'basic '
3. Scroll down to 'warp configs'
4. generate
5. face the issue

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alireza0** [comment]
Every error you reciving is not a BUG !
Please carefully use labels and provide always full information about possible problem and solution.
