### ISSUE TITLE
subscription Bug

### ISSUE THREAD

**Issue by Johnwick-68** [alireza0/x-ui#871]
سلام و خسته نباشید جانانه خدمت شما بابت زحماتی که برای پنل می کشید

یه مشکلی در قسمت سابسکریپشن هست این هست که با اینکه دامنه جدا در اون قسمت ست میکنیم باز ادرس در قسمت سرور ها همین 
,دامنه میاره و دامنه اصلی که سرور روش هست رو نمیاره در تنظیمات پیکربندی هم دامنه دیگری وارد میشه تفاوتی ایجاد نمیشه.

در صورتی که دامنه فیلتر بشه عملا این قسمت هم از کار میوفته و چون اطلاعات لینک اشتراکی رو از همین میخونه.این شرایط مشکل ساز هست

میشه کلا این قسمت سابسکریپشن رو دامنش رو جوری تنظیم کنید که اگر دامنه جدا قرار گرفت کلا فقط مختص این بخش باشه؟پنل با یه دامنه مخصوص سابسکریپشن و یک دامنه برای خود سرور راه اندازی بشه
یعنی عملا دامنه ای که این بخش قرار میگیره مخصوص همین لینک اشتراکی باشه 
در صورتی که دامنه سرور رو زدن و از این بخش به راحتی بروز کنیم و مشکلی ایجاد نشه

خیلی تنظیمات پنل رو تغییرات دادم تست کردم تفاوتی ایجاد نشه.این مورد به خصوص برای استفاده از کلود فلر که سریعا دامنه فیلتر میشه شدیدا کاربردی هست.

با تشکر منتظر پاسخ شما هستم

**Comment by alireza0** [comment]
درود بر شما
در صورتی که شما دامنه ای در بخش External Proxy نگذارید، فرض پنل به اینه که از همون دامنه ای میخواید استفاده کنید که لینک رو ارائه میدین.
این باگ نیست! لطفا در انتخاب برچسب دقت کنید.

**Comment by Johnwick-68** [comment]
سلام علیرضا جان وقتت بخیر.ممنون برای پاسخ.

اما اون قسمت هم دامنه قرار دادم

لینک سابسکریپشن هم از همون دامنه میاره.مشکل اینجاست که داخل خود کانفیگ ها مثلا کانفیک reality یا هر vless دیگه ای که بزنیم از همین دامنه ای که External Proxy قرار گرفته استفاده می کنه.

منظور بنده این هست که کلا یه دامنه برای سابسکریپشن قرار بگیره و ادرس سرور در کانفیگ ها رو از دامنه اصلی که ست میشه بخونه.
به این شکل دامنه سابسکریپشن هیچ زمانی فیلتر نمیشه
متوجه منظور بنده شدید؟

**Comment by alireza0** [comment]
شما میتونید برای پنل و ساب دو دامنه مجزا استفاده کنید و حتی برای هر کانفیگ چند دامنه مجزا هم تعریف کنید.
حتی اگر غیر از این باشه هم مشکل نیست و نمیشه به عنوان باگ معرفی کرد.
مگر اینکه یکی از اینها درست کار نکنه. که باید دقیق بگید کدوم و لاگ و مستندات لازم رو بذارید

**Comment by Johnwick-68** [comment]
مورد باگ تگ اشتباه خورد عذر خواهی میکنم
اما لاگ کدوم قسمت رو ارسال کنم؟


 چند دامنه هم ست بشه روی پنل تفاوتی ایجاد نمیکنه

به محضی که در تب Subscription چه در قسمت Listen Domain و چه Reverse Proxy URI هر دامنه ای وارد بشه در این قسمت
در فایل کانفیگ های سرور هم زمانی که از لینک Subscription استفاده بکنیم در قسمت Address هم همین دامنه Subscription رو میزنه.

 در کلاینت مثلا V2rayng در قسمت Address باز همین همین دامنه Subscription که ست شده رو میاره که این مورد در صورت فیلتر شدن دامنه مشکل ساز میشه.تنها نکته ای که میخوام طی چند باری که پیام دادم بگم همین هست.این مورد رو
یه لطف کنید خودتون هم تست کنید متوجه عرایض بنده میشید.

**Comment by alireza0** [comment]
> درود بر شما
> 
> در صورتی که شما دامنه ای در بخش External Proxy نگذارید، فرض پنل به اینه که از همون دامنه ای میخواید استفاده کنید که لینک رو ارائه میدین.
> 
> این باگ نیست! لطفا در انتخاب برچسب دقت کنید.

من اینجا جواب رو مشخصا اعلام کردم.
در صورتی که شما به کانفیگ اعلام نکنید که از دامنه دیگه ای استفاده کنه (تنظیم external proxy) پنل از کجا باید بدونه که چه آدرسی باید توی کانفیگ بذاره؟
پیش فرض پنل همون دامنه ای هست که از طریقش کاربر ساب رو میبینه.
اگر میخواید دامنه دیگه ای داشته باشه، کافیه external proxy رو فعال کنید و دامنه ای که میخواید لینک با اون دامنه ساخته بشه بهش بدید.

**Comment by Johnwick-68** [comment]
عذر خواهی میکنم مشکل از بنده بود که منظور شمارو بد متوجه شدم
من قسمت Reverse Proxy URI رو تست می کردم فکر می کردم منظور شما این هست!
الان باز دقت کردم که external proxy داخل تنظیمات متفاوت از این تنظیم هست و تست کردم بدرستی کار کرد

خیلی ممنون از وقتی که میزاری و نشانه شخصیت بالات هست
خیلی ممنون که پنل به خوبی و رایگان برای همه فعال کردی تو این شرایط کشور

دمت گرم همه جوره 
خدا برات بسازه علیرضای عزیز

**Comment by alireza0** [comment]
خواهش میکنم
موفق باشید 🙏🏻
