### ISSUE TITLE
Log Writer Bug Report

### ISSUE THREAD

**Issue by Bullshark21** [alireza0/x-ui#872]
با عرض سلام و خسته نباشید 

طبق تست های که این هفته انجام دادم به این نتیجه رسیدم که log wirter با تانل های اوتباند مشکل داره و باعث کرش شدن میشه

من خودم فعلا از نسخه 1.6.1 پنل استفاده میکنم و به مشکل کرش شدن نخوردم چون تا اون نسخه combine log و log wirter اضافه نشدن

حالا نمیدونم به چه دلیدلی باعث میشه که در تانل اوتباند xui رو کرش کنه ولی اگه بتونیم این قسمت رو به همون حالت 1.6.1 برگردونیم خیلی عالی میشه

**Comment by Bullshark21** [comment]
x-ui[80209]: Tgbot connected!
 /usr/local/x-ui/x-ui[80209]: INFO - Starting Telegram receiver ...
 /usr/local/x-ui/x-ui[80209]: WARNING - XRAY: core: Xray 1.8.7 started
 x-ui[80209]: panic: runtime error: slice bounds out of range [358:154]Jan 23 12:38:02 Amali-1 x-ui[80209]: goroutine 16 [running]:
 x-ui[80209]: x-ui/xray.(*LogWriter).Write(0xc000c74b60, {0xc000c9e000?, 0x204, 0x0?})
 x-ui[80209]:         /home/runner/work/x-ui/x-ui/xray/log_writer.go:35 +0x5e6
 x-ui[80209]: io.copyBuffer({0x2520fa0, 0xc000c74b60}, {0x25209a0, 0xc000b408d8}, {0x0, 0x0, 0x0})
 x-ui[80209]:         /opt/hostedtoolcache/go/1.21.5/x64/src/io/io.go:432 +0x1f4
 x-ui[80209]: io.Copy(...)
 x-ui[80209]:         /opt/hostedtoolcache/go/1.21.5/x64/src/io/io.go:389
 x-ui[80209]: os/exec.(*Cmd).writerDescriptor.func1()
 x-ui[80209]:         /opt/hostedtoolcache/go/1.21.5/x64/src/os/exec/exec.go:560 +0x34
 x-ui[80209]: os/exec.(*Cmd).Start.func2(0xc0003c0bd0?)
 x-ui[80209]:         /opt/hostedtoolcache/go/1.21.5/x64/src/os/exec/exec.go:717 +0x2c
 x-ui[80209]: created by os/exec.(*Cmd).Start in goroutine 13
 x-ui[80209]:         /opt/hostedtoolcache/go/1.21.5/x64/src/os/exec/exec.go:716 +0xa0a
 systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
 systemd[1]: x-ui.service: Failed with result 'exit-code'.
 systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 291.
 systemd[1]: Stopped x-ui Service.
 systemd[1]: x-ui.service: Start request repeated too quickly.
 systemd[1]: x-ui.service: Failed with result 'exit-code'.
 systemd[1]: Failed to start x-ui Service.

**Comment by alireza0** [comment]
این مشکل قبلا شناسایی و در این [کامیت](https://github.com/alireza0/x-ui/commit/b63f30573766db1e192820bee87d41d4c5beac18) و در نسخه ۱.۷.۰ رفع شده بود.
یک گزارش مشابه هم داشتیم : #833

**Comment by Bullshark21** [comment]
متاسفانه انگار در نسخه 1.7.0 هم رفع نشده عکس رو میفرستم همینجا میبینید که نسخه xui هم 1.7.0 هست
![xuierror](https://github.com/alireza0/x-ui/assets/133830928/a2e0d916-4226-4ee2-9c4f-d6a17b0905d2)

**Comment by alireza0** [comment]
خط کدی که داره ایراد میگیره با یک شرط کامل محدود شده:
```go
		startIndex := strings.Index(messageBody, "[")
		endIndex := strings.Index(messageBody, "]")
>		if startIndex != -1 && endIndex != -1 {
>			level := strings.TrimSpace(messageBody[startIndex+1 : endIndex])
```
از نظر منطقی هیچ دلیلی برای این خطا وجود نداره. تا الان هم گزارش دیگه ای نگرفتم.
تنها حالتی که میتونه به ذهنم برسه اینه که «[» بعد از «]» بیاد این خطا میتونه بوجود بیاد. این حالت در لاگ استاندارد هیچوقت بوجود نمیاد.
من این شرط رو اضافه میکنم و امیدوارم مشکل شما حل بشه

**Comment by Bullshark21** [comment]
ممنون از زحمات شما انشاالله در اپدیت بعدی که اومد تست میکنم
