### ISSUE TITLE
socks برای ربات

### ISSUE THREAD

**Issue by Shm9220** [alireza0/x-ui#873]
socks برای ربات توی اپدیت بعدیتون میاد ؟

**Comment by alireza0** [comment]
برنامه ای براش ندارم.
راه حل استفاده از تلگرام در منطقه فیلتر شده در ایشو ها پین شده.

**Comment by Shm9220** [comment]
ثنایی زده اخه

**Comment by alireza0** [comment]
دلیل خوبی نیست!
در ضمن، ماژول تلگرام اون پنل کاملا متفاوته.
