### ISSUE TITLE
Support for Shadowsocksrr in X-UI

### ISSUE THREAD

**Issue by MrSaeid007** [alireza0/x-ui#874]
Hi @alireza0 

Is that possible to add support for Shadowsocksrr to the X-UI panel?
https://github.com/shadowsocksrr/shadowsocksr/

Thank you.

**Comment by alireza0** [comment]
Hi @MrSaeid007 ,

X-UI is not supposed to provide a protocol itself.
But only providing a setup for xray-core app.

If it is provided by xray-core, then we can provide the new configuration.

**Comment by MrSaeid007** [comment]
> Hi @MrSaeid007 ,
> 
> X-UI is not supposed to provide a protocol itself. But only providing a setup for xray-core app.
> 
> If it is provided by xray-core, then we can provide the new configuration.

Thanks for information
