### ISSUE TITLE
باگ اسکریپ مولتی پروتکل

### ISSUE THREAD

**Issue by PouryaDe** [alireza0/x-ui#875]
سلام وقت بخیر
این اسکریپ مولتی پروتکل یه باگی داره

مثلا وقتی یه کلانت در دو تا اینباند میسازیم و زمانش رو Start on Initial Use میذاریم وقتی کاربر به اینباند دوم وصل میشه، محاسبه زمان استارت میخوره ولی در اینباند اول هنوز محاسبه تاریخ اتفاق نمیوفته

بعضا هم وقتی تاریخ همون کلاینت در اینباند عوض میشه روی بقیه اینباند ها اعمال نمیشه و فقط حجم رو یکسان سازی میکنه

کلا چک کردم ظاهرا فقط حجم ها رو یکسان سازی میکنه و تاریخ انقضا رو یکسان سازی نمیکنه لطفا بررسی کنید

**Comment by PouryaDe** [comment]
کاش تو api یه متدی اضافه کنید که با SubID بشه ResetTraffic و EditClient و AddClient انجام داد

**Comment by alireza0** [comment]
درود بر شما
در این پنل چنین چیزی وجود نداره. اگر نرم افزار جانبی باگ داره با خود طراحش صحبت کنید.
برای تغییرات در کاربران، میتونید از ترکیب متد ها استفاده کنید. اطلاعات کلی رو بگیرید، تحلیل کنید و تغییرات دلخواه رو اعمال کنید.

**Comment by PouryaDe** [comment]
این اسکریپ مولتی پروتکل رو کی نوشته لطفا گیت هابش رو بفرستید براش بگم باگ رو

**Comment by alireza0** [comment]
دوست عزیز، در این پنل چیزی به نام مولتی پروتکل ارائه نشده.
شما استفاده کردین و باگ پیدا کردین، چرا من باید بدونم از کجا گرفتین؟

**Comment by MHSanaei** [comment]
این اسکریپتمولتی پروتکل روی پنل مهندس علیرضا نیست و ایشون هم اصلا در جریان نیستن انقد بنده خدارو اذیت نکنید

باگ های اون اسکریپت رو باید به این شخص گزارش کنید که برطرف کنند
@M4mmad
