### ISSUE TITLE
error after update to 1.7

### ISSUE THREAD

**Issue by elect0nik** [alireza0/x-ui#876]
Hi my xray stopped working after update. any idea how to fix?

2024/01/19 18:32:08 ERROR - XRAY: IPC error -22: invalid UAPI device key: allowed_ip
2024/01/19 18:32:08 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/01/19 18:31:38 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/01/19 18:31:08 ERROR - XRAY: IPC error -22: invalid UAPI device key: allowed_ip
2024/01/19 18:31:08 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/01/19 18:30:38 ERROR - XRAY: IPC error -22: invalid UAPI device key: allowed_ip
2024/01/19 18:30:38 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/01/19 18:30:08 ERROR - XRAY: IPC error -22: invalid UAPI device key: allowed_ip
2024/01/19 18:29:44 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/01/19 18:29:41 ERROR - XRAY: IPC error -22: invalid UAPI device key: allowed_ip
2024/01/19 18:29:41 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/01/19 18:29:38 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/01/19 18:29:08 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/01/19 18:28:23 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/01/19 18:28:19 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/01/19 18:28:09 INFO - X-UI: Starting Telegram receiver ...
2024/01/19 18:28:09 ERROR - XRAY: IPC error -22: invalid UAPI device key: allowed_ip
![image](https://github.com/alireza0/x-ui/assets/25589574/95ce1570-c454-4fbd-ba3e-e6cd973b0f63)

**Comment by alireza0** [comment]
You should remove invalid json keys. It is clear that you have allowed_ip from another X-UI panel.
Another option is to edit and save Inbounds one by one.
