### ISSUE TITLE
Custom outbounds 

### ISSUE THREAD

**Issue by sharif221** [alireza0/x-ui#877]
**Is your feature request related to a problem? Please describe.**
the problem is that in outbound tab the UI dont cover all combination of json configs and if you copy custom json to (json tab) in [add outbound] it sometimes dont save correct json.
For example you cant save outbound contain [sockopt]. For this you need to create it in advance tab AND remember not to open outbound in outbounds tab because it force rewrite json and mess it up.

**Describe the solution you'd like**
The solution can be 2 things:
1. Adding support for all json combinations in UI. (Its hard and confusing for majority of users)
2. Adding custom outbound option in [add outbound] UI, its just text editor that you put yor json in it and it makes sure that json is correct and saves it. There is no UI page in this mode. Its just json text editor.

**Additional context**
Or it might have UI but UI is just for basics for example tag and address.

**Comment by sharif221** [comment]
i know its totally fine.
But its much cleaner if the option for raw json be available in outbound tab. And also raw json in routing and reverse tab.

Because when you make change its come in these places anyways, and the bug that is currently here is that you have to make sure not to touch these configs in outbound tab and other tabs.


But it's totally respectable if you think these is unnecessary : )

**Comment by alireza0** [comment]
@sharif221 
Please mind that you are not the only one using this panel and other users has their own opinion and way of configuration.
I am trying to make every simple ways simple for users with basic knowledges.
For advanced users like you, I stringly recommend to use xray-core itself.

**Comment by sharif221** [comment]
@alireza0 

Please don't get mad, I'm just trying to suggest.
Thanks for response.

I appreciate that you spend your time on this project without getting anything in return.

**Comment by Malcolmxx3** [comment]
How can my inbound setting listen to my custom IP

**Comment by sharif221** [comment]
> How can my inbound setting listen to my custom IP

That's easy, in inbound setting look for listening ip that is empty means it listen to 0.0.0.0 or everything. You can change that to the fixed ip.
