### ISSUE TITLE
SNI not set

### ISSUE THREAD

**Issue by Cjxer** [alireza0/x-ui#88]
سلام وقتتون بخیر 🌹

![IMG_20230322_203347_893](https://user-images.githubusercontent.com/26128739/226982303-64b38314-6b44-45ef-8e57-d74cc2f98770.jpg)

من به این صورت قسمت domain رو دامنه ایرانم که تانل کردم میذارم
و قسمت SNI هم دامنه سرور خارجم رو میذارم
اما وقتی کلاینت رو میسازم قسمت SNI خالی می مونه
و باید حتما توی Request header هم دامنه ای که توی SNI میذارم رو بذارم تا SNI هم پر بشه

مشکل رو میشه بررسی کنید؟
ممنون 🙏

**Comment by alireza0** [comment]
درود بر شما
این گزینه به لینک اضافه میشه. ممکنه نرم افزار سمت کاربر این گزینه رو توی لینک ساپورت نکنه.
لطفا لینک رو چک کنید
