### ISSUE TITLE
اکسپورت لینک های ساب اینباند

### ISSUE THREAD

**Issue by hamed0mh** [alireza0/x-ui#880]
لطفا توی بخش export links اینباند
اکسپورت لینک های ساب داخل اینباند رو اضافه کنین

الان مثلا برای یک اینباند ده تا یوزر تعریف کردی برای هر کدوم باید تک به تک لینک ساب رو کپی بزنی
.
هم زمان بر هست و هم توی تعداد بالا اشتباه پیش میاد

**Comment by alireza0** [comment]
این ویژگی افزوده شده و در نسخه آینده در دسترس خواهد بود
