### ISSUE TITLE
اضافه کردن تمدید خودکار بعد از اتمام حجم

### ISSUE THREAD

**Issue by liamnees** [alireza0/x-ui#881]
اگر امکان دارد امکان تمدید خودکار علاوه بر پایان زمان بعد از پایان حجم هم فعال بشه و همینطور جابجا کردن کلاینت ها در اینباند هم اگر بشه خیلی خوبه

**Comment by alireza0** [comment]
فایده اش چیه؟
الان حجم مصرف شده بعد از دوره ریست میشه و دوره هم به زمان اضافه میشه.
اگر بعد از پایان حجم ریست بشه رسما هیچوقت قطع نمیشه!
خب نامحدودش کنید هم همون میشه.

جابجا کردن یعنی چی ؟

**Comment by liamnees** [comment]
فکر کنم خوب منظورمو نگفتم، اگر برای یکی بزنیم 30 روز و مثلا 20 گیگ و قسمت Auto Renew 30 بزنیم. زمان تمام بشه 30 روز و 20 گیگ مجدد تمدید میشه ولی اگر ظرف 10 روز 20 گیگ مصرف کنه تمام بشه تمدید نمیشه منظورم این بود. و اگر این قسمت Auto Renew پر نکنی که خودکار تمدید نمیشه پس قطع میشه اگر خودکار اتوماتیک پر نشه. جابجا کردن هم یعنی کلاینت هایی که ساختی داخل اینباند بشه توی لیست جابجا کرد. اکانت هایی که 1 نفر گرفته همه کنار هم باشه. به نظر من مفید حالا ممکنه کسی اصلا استفاده هم نکنه ولی اگر امکانش باشه اضافه بشه خوبه.

**Comment by alireza0** [comment]
همون شد! اگر قرار نیست کاربر قطع بشه و همه جوره تمدید میشه، خب نامحدود بذارین!
حس میکنم دارین خودتون رو گول میزنین!

در مورد ترتیب کاربرها، میشه انجام داد. ولی خیلی درخواست لاکچری میشه .
اولویت وقتی مهم نیست، هزینه زیباسازی میشه شلوغ شدن منو.
با این کار برای هر بار تغییر، باید کل صفحه دوباره لود بشه و توی این حالت طراحی پنل، خیلی ضرر داره.

**Comment by liamnees** [comment]
ببین یکی ماهانه مثلا ۲۰ گیگ می خواد ولی ۲۵ روزه تمامش می کنه ولی نمی خوای قطع بشه ۲۰ گیگ و ۲۵ روزه تمام کرد دوباره صفر بشه با ۲۰ گیگ و ۳۰ روز، با نامحدود فرق داره، و اینکه اگر قسمت auto renew پر نکنی که خودبه خود تمدید نمیشه پس نگرانی بابت قطع نشدن وجود نداره.

**Comment by alireza0** [comment]
دوست عزیز، شما دارین خودتون رو گول میزنید. وقتی کاربر قطع نمیشه، با نامحدود فرقی نداره.
سیستم مالی بهش وصل نیست که اتوماتیک کم کنه از حسابش و یا گزارش بده که چند دوره ریست شده!
توی سیستم های پیچیده مفاهیمی مثل AutoCharge و AutoRenew داریم که بستگی به نوع Deposite داره.
اینجا ما هیچکدوم رو نداریم و هدف تجاری سازی هم نداریم.
