### ISSUE TITLE
Multi Protocol 

### ISSUE THREAD

**Issue by Mehdioop** [alireza0/x-ui#882]
با سلام و احترام، 
لطفا در صورت امکان قابلیت Multi Protocol که در پنل سنایی هم اضافه شده، اضافه کنید.

**Comment by alireza0** [comment]
درود بر شما
لطفا قبل از ایجاد ایشو از تکراری نبودن اون مطمئن بشید.
استفاده از نرم افزار های خارجی، اصلا توی برنامه این پنل نیست.
جدا از اینکه امکانات تجاری سازی در این پنل تا حد امکان اضافه نمیشه.
