### ISSUE TITLE
reverse

### ISSUE THREAD

**Issue by nimaafallah** [alireza0/x-ui#883]
سلام و عرض ادب

من ریورس رو انجام دادم و به خوبی کار میکنه، اما یه مشکلی دارم اینه که تو سرور ایران هر یورزی که تعریف میکنم باید توی تب ریورس هم پورت اون یوزر جدید رو تیک بزنم(یوزر هام رو روی یک پورت نمیخوام بدم)، میخواستم بدونم راهی هست که وقتی یوزری میسازم دیگه لازم نباشه این کارو انجام بدم؟

**Comment by GoldenVDS** [comment]
من از شما سوال دارم چ.ن ریورز و مثل من مشغول استفاده هستید:: آیا یوتیوب به درستی کار میکنه؟

**Comment by nimaafallah** [comment]
سلام بله، یک سری از دوستان دیدم گفته بودن ای پی خارج فیلتر باشه هم کار میکنه، مندتست کردم، راست میگن کار میکنه ولی یه سری ای پی ها دانلود ضعیف هست یه سری آپلود.

**Comment by alireza0** [comment]
@nimaafallah 
درود بر شما
بستگی به تعاریف قوانین شما داره.
میتونید قانون  کلی ارسال به تانل رو دستکاری کنید و به جای لیست اینباند ها ، همه آی‌پی ها رو معرفی کنید.
مثلا فقط فیلد پورت رو 0-65532 بگذارید.
یا اگر از sniffing استفاده نمیکنید، میتونید فیلد IP رو روی 0.0.0.0/0 تنظیم کنید.
