### ISSUE TITLE
حذف آخرین کلاینت یک اینباند از طریق API

### ISSUE THREAD

**Issue by AliM1988** [alireza0/x-ui#884]
سلام
از طریق API این امکان هست اخرین کلاینت یک اینباند هم حذف بشه. با این کار نمایش کل اینباندها در پنل محفی میشه و فقط با حذف اینباند خالی و ریستارت کردن پنل مشکل حل میشه. شاید بهتر باشه API اجازه حذف اخرین کلاینت رو نده.

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از گزارشتون
مشکل رفع شد و در نسخه بعدی اضافه میشه
