### ISSUE TITLE
Reverse --- youtube  not working

### ISSUE THREAD

**Issue by GoldenVDS** [alireza0/x-ui#885]
درود و عرض ادب
ممنون بابت زحمات بی چشم داشت شما.

من دو پنل نصب کردم در دو سرور ایران و آلمان و بصورت Reverse اونم با IPV6 دو پنل متصل و با سرعت خوبی سرور ایران سرویس دهی میکند.
اما....
اما من در تنظیمات سرور ایران گفتم ادرس ها و ای پی های ایرانی دایرکت باشد که منطقی هم هست ترافیک داخل ایران بیخود چرا منتقل کنیم به سرور خارج ولی گویا درست عمل نمیکنه من مثلا اپلیکیشن بانک باز کردم اخطار ای پی خارجی داد.
و یک نکته دیگه اینکه سرور خارج و مستقیم به خودش وصل میشم هیچ موردی نداره ولی از طریق ایران که متصل میشم یوتیوب باز نمیکنه!!!! این مورد آزار دهنده است
حالا راهنمایی میخواهم بدونم مشکل دارم در تنظیمات و عملکرد و یا باگ هست و راه حل این مشکل چیست.

سپاس

**Comment by alireza0** [comment]
درود بر شما
این موارد به تنظیم قوانین مسیریابی برمیگرده.
کسی چشم بسته نمیتونه راهنماییتون کنه. لطفا تنطیمات و شواهد کافی ارسال کنید.

**Comment by GoldenVDS** [comment]
> درود بر شما این موارد به تنظیم قوانین مسیریابی برمیگرده. کسی چشم بسته نمیتونه راهنماییتون کنه. لطفا تنطیمات و شواهد کافی ارسال کنید.

درود به روی ماهت و ممنون از پاسخگویی
حقیقت اره روت ها رو مرتب کردم این مشکل بر طرف شد. اما یک مشکل بزرگتر دارم علیرضا جان ببخشید اگر الکن توضیح میدهم.

یک سرور ایران با یک سرور هتزر آلمان الان ریورز شده اما یک اتفاقی میفته من از چرایی ان و درک و حل مشکل عاجزم.

استاد یکم بیشتر توضیح بدهم 
سرور ایران بدون ریورز: یوزر روش میسازم متصل میشم با همه اپراتورها بدون ارور هندشیک و خب طبیعی که از فیلترینگ عبور نکرده اما به محض ریورز کردن یکسری اپراتور ها دیگه قابلیت اتصال و ندارند و اصلا سرور ایران انگار خصوصیت واسط بودن و از دست میدهد.

اگر لازمه بفرمایید چطوری دسترسی بفرستم تا خودتان بررسی و من را راهنمایی کنید.

حقیقتا سه تا از دوستان دیگه هم که مطابق توضیحات آقای ایمان آقاپور مثل من ریورز را انجام دادند همین مشکل و پیدا کردند و بر گشتند سمت تانل پورت فوروارد.


میشه این مورد و بهم یاد بدید که مشکل چیه و چطوری حل میشه.

ممنون

**Comment by alireza0** [comment]
ببینید این بخش برای مشکلات کانفیگ و تنظیم برای اپراتورها و مشکلاتشون ساخته نشده.
من در این موارد تخصص و تجربه ای ندارم.
بهتره سوالاتتون رو در گروه های تلگرامی و یا فوروم ها جستجو کنید.
در کل تنها کمکی که میتونم بکنم اینه که بگم مقایسه نوع معکوس با IPTables کار درستی نیست. بهتره اون رو با روش تانل مستقیم مقایسه کنید.
شرایط سرور و ترافیک ایران با سرورهای خارج متفاوته.

موفق باشید
