### ISSUE TITLE
باگ اسکرول لیست پاپ آپ کاربرها

### ISSUE THREAD

**Issue by mrcodebaz** [alireza0/x-ui#887]
سلام ، نسخه پنل الانم 1.7.0

توی قسمت اینباندها وقتی روی اعداد میزنی و لیست پاپ‌اپ باز میشه ، مثلا افراد آنلاین
وقتی لیست طولانیه اسمهاشون اسکرول نمیشه
کش هم خالی کردم از اون نیست
توی پنل ثنایی درسته و سازنده ui هردوتون فکر کنم یه خانمی بود!!! اما این مورد ظاهراً جا افتاده

لطفاً رفع این مورد رو برای نسخه بعدی مد نظر داشته باشید

**Comment by alireza0** [comment]
تغییرات اعمال شد
در نسخه بعد اعمال میشه
