### ISSUE TITLE
تغییر کلی اینباند یا انتقال کاربران به اینباند متفاوت

### ISSUE THREAD

**Issue by selfishtom** [alireza0/x-ui#888]
سلام من دیروز دامنه ام فیلتر شد و خواستم اینباند رو تغییر بدم ساختارش رو نتونستم یک سری گزینه رو عوض کنم

بخاطر همین به این فکر کردم که کاربرانم رو چطور میتونم به اینباند جدید انتقال بدم ؟
که ساختارش کاملا متفاوت هستش
برای مثال :
inbound 1 : vless + ws + tls + cdn with proxy
inbound 2 : vless + gRpc + Reality
ممنون میشم اینو بگید میتونم این کارو بکنم که بلد نیستم ؟
یا ممکنه به پنل این قابلیت رو اضافه کنید که فقط کاربر هایی که میخوایم رو به یک اینباند دیگه انتقال بدیم ؟

یک سوال دیگه هم که داشتم اینه
توی حالت اینباند 1 من از warp+ داخل پنل برای تغییر IP خروجی توی یک سری سایت ها استفاده میکردم ولی برای اینباند 2 این حالت اصلا کار نمیکنه ، باگ هست یا کلا کار نباید بکنه ؟

**Comment by alireza0** [comment]
درود بر شما
در مورد اولین مسئله: این مورد خیلی عمومی نیست که بشه براش یه تغییر بزرگی داد.
بهتره دستی انجام بدید. میتونید مشخصات اینباند رو به مدل دیگه ای تغییر بدید و همه کاربرها اتوماتیک بروز رسانی میشن.

در مورد سوال: مشکل از تنظیمات بخش قوانین مسیریابی شما باید باشه.
ورودی و خروجی ها متفاوت هستند و با قوانین مسیریابی متصل میشن.

**Comment by hrgh1985** [comment]
سلام و احترام
فکر میکنم منظور ایشون انتقال کاربران از یک اینباند به اینباند دیگر است. یعنی نام - حجم - تاریخ و آی دی کاربر منتقل شود به اینباند دیگر.
چند وقت پیش من هم به این مشکل خوردم که میخواستم اینباند ها را ادغام کنم و نمیشد.
دلیلش هم این بود که میخواستم لودبالانس ایجاد کنم از ایران و تعداد پورتی که اون دیتاسنتر برای لود بالانسر به من میداد محدود بود و مجبور بودم یجوری اینا را ادغام کنم که دستی انجام دادم و خیلی زمان بر شد.
اگر ممکنه Move کردن کاربران از یک اینباند به اینباند دیگر را اضافه کنید.
سپاس
