### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by Amirbutik** [alireza0/x-ui#891]
سلام من از طریق تانل معکوس خواستم استفاده کنم ولی وقتی لینک یک اینباند رو میخوام توی اوتباند اون یکی سرورم وارد کنم وقتی لینک رو در قسمت json پیست میکنم خطای wrong link میده
راهنمایی کنید ممنون

**Comment by alireza0** [comment]
درود بر شما
برای لینک اشتباه و یا لینکی که ساپورت نمیشه این خطا رو برمیگیردونه

**Comment by Amirbutik** [comment]
من هر لینکی که ساختم و حتی لینک های درست از بقیه دوستان و تو قسمت اوت باند وارد میکنم این ارور و بازم میگیرم

**Comment by alireza0** [comment]
پس احتمالا لینک رو درست کپی و جایگذاری نمیکنید.
اگر نمونه لینک رو دارید با حفظ امنیتش اینجا بفرستید.

**Comment by Amirbutik** [comment]
vless://e2ff3e1d-efea-4a1d-8588-8a44d4e2751f@iranserver.com:2083/?type=grpc&serviceName=&security=tls&fp=&alpn=h2%2Chttp%2F1.1&sni=pol.amirtrojan.tk#9orbvkzri

**Comment by alireza0** [comment]
لینکتون اشتباه درست شده! به علامت «/» بعد از پورت دقت کنید. ساختار درست لینک vless این شکلی باید باشه:
```html
vless://<UUID>@<host>:<port>?<key1>=<value1>&...&<keyN>=<valueN>#<remark>
```

**Comment by Amirbutik** [comment]
من با خود پنل ساختم
ممکنه همین لینکو اصلاحش کنید ببینم مشکلم از کجاست؟

**Comment by Amirbutik** [comment]
اینم همون خطارو میده و تمام لینکها خطا میده موقع خروجی اینباند
مرورگر safari
ios 17

**Comment by alireza0** [comment]
گوشی آی‌فون، لینک ها رو زمان کپی کردن تغییر میده.
بعد از اینکه لینک رو جایگذاری کردید، باید حرف «/» رو بعد از پورت به صورت دستی حذف کنید.
مشکل از جای دیگه ای نیست
