### ISSUE TITLE
ویژگی نود مرزبان و سابلینک مرزبان

### ISSUE THREAD

**Issue by danielrad2006legend** [alireza0/x-ui#893]
امکان استفاده از لینک ساب دو پنل که از هم جدا هستن و از دو کشور متفاوت هست و یهنی یک ساب لینک بشه ساخت از دو پنل  و به هم وصل کرد تا در اون ساب لینک دوتا کشور جدا برای اتصال کاربر وجود داشته باشه یعنی یه امکانی مثل نود مرزبان که میشه ازش چند تا پروتکل ساخت با چند تا ریجن کشور دیگه که به اون لینک ساب وصله 
 با تشکر اگر بتونید این اموان رو اضافه کنید عالی میشه ❤️

**Comment by alireza0** [comment]
مدل کار x-ui با مرزبان متفاوته و نمیشه به راحتی این ویژگی ها رو اضافه کرد.
