### ISSUE TITLE
فعال کردن رباط تلگرام در سرور ایران

### ISSUE THREAD

**Issue by porozhe50** [alireza0/x-ui#895]
سلام و خسته نباشی برادر گلم خاستم بدونم وقتی ریورس تانل رو انجام دادم آیا راهی هست که سرور ایرانم بتونه به تلگرام وصل بشه ک بتونیم از سرور ایران با اسکریپت حجم باقی مانده کانفیگ هارو ببینیم و اینکه مثلا من سرور قدیمی دارم تعداد اینباند های زیادی داره زمانی ک میخام‌ریورس رو ب عنوان پورتابل انجام بدم برای انتخاب پورت ها چون زیاد هستن یکم وقت میبرن خاستم بدونم امکانش هست گزینه اضافه بشه داخل اون قسمت ک انتخاب همه باشه ولی مهم تر از همه همین وصل شدن ب تلگرام روی سرور ایران هستش برای استعلام حجم تست گرفتم جواب نداد بکنم با قوانین مسیر یابی ور رفتم ولی متاسفانه ربات کار نمیکرد

**Comment by alireza0** [comment]
درود بر شما
راه حل های تلگرام زیاده، و من دو مدلش رو توی یه ایشو گفتم و پین کردم.
شما میتونید بالای ایشو ها ببینید.
در مورد ریورس، باید اینباندی که برای تلگرام درست کردین رو جزو اینباند های ورودی به پورتال بذارید و یا آدرس api.telegram.org رو به پورتال بفرستید.

اضافه کردم دکمه برای انتخاب همه راحته، ولی چون باعث مشکلات میشه نذاشتم.
اگر راه حل مناسبی دیدم، اضافه میکنم.
