### ISSUE TITLE
Wireguard

### ISSUE THREAD

**Issue by elect0nik** [alireza0/x-ui#896]
There is no keys auto generation for WG peers and no qr codes for peers now, or am I missing something?

**Comment by alireza0** [comment]
Yes. It is now design is for peer-to-peer networks.
There are lots of documentation for other applications which could help you to set it up , but there is no multi client support yet. Maybe next versions.

**Comment by mahdiazizi1365** [comment]
علیرضا جان . خسته نباشی و یک دنیا ممنون بابت همه زحماتت . 
شاید سوالم تکراری باشه  . پس پیشاپیش عذر میخوام . 

سناریویی که ما با vless مثلا یک کانفیگ درست میکنیم و بعد میزنیم توی v2ray . امکانش الان با وایگارد پنل شما نیست  ؟

**Comment by alireza0** [comment]
@mahdiazizi1365 
فعلا وجود نداره
به موفع اش روش کار میکنم
شاید در نسخه بعد ارائه بدم

**Comment by alireza0** [comment]
@elect0nik ,
It is now added and will be available in next release.
You can use Qr-Code in all the standard client applications.
