### ISSUE TITLE
وصل شدن ربات تلگرام به کانفیگ انتخابی برای دور زدن فیلترینگ سرور ایران

### ISSUE THREAD

**Issue by rween** [alireza0/x-ui#897]
لطفا قابلیتی اصافه کنید که با کپی پیست کردن کانفیگ بشه کاری کرد ربات سرور ایران به تلگرام که فیلتر هست از طریق کانفیگ متصل بشه

**Comment by alireza0** [comment]
راه حل برای ارتباط تلگرام زیاده.
فعلا برنامه ای برای افزایش قابلیت های بات ندارم.
