### ISSUE TITLE
HTTP to HTTPS migration: do existing clients preserve using HTTP and not HTTPS, or will be rejected, or will be migrated to HTTPS? 

### ISSUE THREAD

**Issue by Kenya-West** [alireza0/x-ui#898]
I will try to upgrade HTTP to HTTPS using cert bot in docker container (since my setup is made by docker-compose), what are exact behaviour of the question in the subject?

Clients are connected by Subscription links (by HTTP).

**Comment by alireza0** [comment]
A shared mount-point `cert` is reserved by default. You can copy ( or link ) your certificates there ( in host ) and use /root/cert/ ( by default or change it in `docker-compose.yml`) in your panel.

**Comment by Kenya-West** [comment]
> A shared mount-point `cert` is reserved by default. You can copy ( or link ) your certificates there ( in host ) and use /root/cert/ ( by default or change it in `docker-compose.yml`) in your panel.

Thanks for help. I tried this. And then X-UI becomes inaccessible by HTTP. It has access only through HTTPS and domain name.

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/alireza0/x-ui/assets/12271104/9d327cbc-cbd6-431d-a565-27a1b1c416f7)


</p>
</details> 

It becomes inaccessible by following ways:
- `0.0.0.0` (both http and https)
- `127.0.0.1` (both http and https)
- external IP (both http and https)
- domain name (http)

It has only access by domain name and https, sadly.

I want X-UI to be accessible both by HTTP and HTTPS from IP address and domain name for backward compatibility reasons (many clients are impossible to reach, they only connect by IP address and HTTP).

**Comment by alireza0** [comment]
These configurations are only for limiting access to the panel for security reasons.
In one port it is not possible to listen to http and https in same time.
You should devide it by externall proxies like nginx.
BTW, it is recommended to update the clients as well.
