### ISSUE TITLE
محدود کردن پهنای باند کاربران

### ISSUE THREAD

**Issue by sadegh1210** [alireza0/x-ui#899]
با سلام و خسته نباشید.
کاش میشد که مثلا inbound یا client ها رو یجوری سرعتشون رو به مقدار دلخواه تنظیم کرد .

**Comment by alireza0** [comment]
درود بر شما
بهتره از نرم افزار های جانبی استفاده کنید.
نرم افزار xray این قابلیت رو ساپورت نمیکنه.

**Comment by sadegh1210** [comment]
برنامه های جانبی ؟!
میشه لطفا نام ببرید ؟

**Comment by alireza0** [comment]
لطفا جستجو کنید. من از شرایط شما اطلاعی ندارم

**Comment by sadegh1210** [comment]
سرور ubuntu دارم ، روش v2ray دارم .
حالا هرچی شما بگید من میرم در موردش تحقیق میکنم

**Comment by alireza0** [comment]
trickle

**Comment by sadegh1210** [comment]
ممنون
