### ISSUE TITLE
Bug fixes and feature additions

### ISSUE THREAD

**Issue by mhosseint** [alireza0/x-ui#90]
سلام وقت بخیر
یه مورد باگ هست که خواستم اطلاع بدم خدمتتون تا این مشکل را برطرف کنید و یه تعدادی هم درخواست اضافه کردن ویژگی و قابلیت هستند.

باگ:
۱- گزینه Reset traffic که برای کل Inbound هست را وقتی میزنیم فقط لاگ ترافیک خود Inbound حذف میشود. در صورتی که اصولا باید اینگونه باشد که وقتی این گزینه را بزنیم علاوه بر ترافیک خود Inbound ترافیک کل کاربرای اون Inbound هم ریست بشن و اگر هم کسی خواست که فقط کاربر خاصی ترافیکش ریست بشه خوب برای هر کاربر دکمه ریست اختصاصی وجود دارد.
۲- و اینکه وقتی مثلا برای کاربر خاصی ترافیک را ریست میکنیم مقدار حذف شده آن ترافیک از Inbound کم نمیشود. در صورتی که میبایست اصولا این دو با یکدیگر متصل باشند و با حذف ترافیک یک کاربر ترافیک Inbound هم آپدیت شود. چون ترافیک Inbound درواقع حجم کل ترافیک اون دسته را نمایش میدهد.

درخواست های اضافه کردن ویژگی:
۱- یک قابلیت بسیار مهم که شما همکنون از پنل حذف کردید قابلیت محدودیت آی پی هست. لطفا این قابلیت را اضافه بفرمایید که برای هر کاربر بتوانیم تعداد مجاز آی پی را مشخص کنیم و اگر محدودیت آی پی برای کاربر را یک عدد گذاشتیم یعنی فقط یک آی پی مجاز به استفاده باشد و آی پی دوم بلاک شود. همچنین لطفا گزینه لاگ آی پی برای هر کاربر را هم قرار دهید که بسیار مهم و ضروری هستند.
نمونه پنل که IP Restriction دارد: https://github.com/HexaSoftwareTech/x-ui
۲- گزینه email که در هنگام افزودن کاربر وجود دارد دارای ضرورت مهم حتما جهت نوشتن ایمیل نیست و هیچ عملکرد خاصی هم ندارد. لطفا این گزینه و تمام جاهایی که email وجود دارد را به گزینه name تغییر بدید که هرکس هرچی تمایل داشت بنویسد.
۳- اگر امکان داشته باشد که یک قابلیت Auto Reset traffic به صورت اختصاصی برای کاربر وجود داشته باشد خیلی عالی میشود. به صورتی که مثلا یک کاربر فقط ماهانه حجم مشخصی میتواند استفاده کند و دارای تاریخ اتمام هم نیست. و ما برای اون یک تاریخ مشخص کنیم که صورت خودکار و دوره ای در آن تاریخ ترافیکش ریست شود. و اگر قبل از ترافیکش را مصرف کرده بود و غیرفعال شده بود به صورت خودکار مجدد فعال شود.
۴- اینکه عملکرد ربات تلگرام برای کاربر ها اضافه شده خیلی خوبه ولی بجای اینکه آی دی تلگرام هر کاربر را با اضافه کردن @ جلوی نام او بنویسیم، ای کاش یک فیلد جدا قرار میدادید که اگر میخواستیم برای اون کاربر آی دی تلگرام هم بنویسیم. و آی دی تلگرام دیگه در کنار نام او نمایش داده نشود. و این تمامی در قسمت Add bulk هم تصحیح و یکپارچه شوند.
۵- و اگر هم امکان داشت یک قابلیتی را داشته باشیم که برای مثال اطلاعیه های اتمام ترافیک و تاریخ را برای هر کاربر تنظیم بکنیم که اصلا ارسال بشود یا نه و اینکه برای خود کاربر و ادمین هم استفاده بشود یا فقط برای ادمین ارسال شود یا فقط برای خود کاربر ارسال شود. این جوری خیلی عالی تر میشود.

و بنده چندتا هم سوال داشتم:
۱- دو گزینه Ban bittorrent usage و Ban private ip range to connect که داخل تنظیمات هستند دقیقتا کارشون چی هست؟
۲- گزینه Alter ID که در هنگام اضافه کردن کاربر هست چه عملکردی دارد؟ و چرا عدد صفر هست؟

نهایتا اگر امکان داشت يک آی دی تلگرام خودتون رو هم بتونید برام بفرستید که بیشتر با شما در ارتباط باشیم که بسیار ممنون میشم.
باتشکر فراوان

**Comment by alireza0** [comment]
درود بر شما
## در مورد باگ ها:
این مدل طراحی xray-core  و گزارشش هست و ما قرار نیست تغییری توش بدیم.
برای م‍ثال ترافیک fallback جزو ترافیک خود inbound حساب میشه، ولی عملا هیچکدوم از کاربرهای زیرمجموعه هیچ استفاده ای نکرده اند.

## ویژگی های درخواستی
۱. ابن پنل از همین رپوزیتوری که شما اعلام کردین فورک شده. محدودیت IP رو عمدا توی این پنل حذف کردم، اگر لازم دارید میتونید از پنل [3x-ui](https://github.com/MHSanaei/3x-ui) استفاده کنید.
۲. گزینه ایمیل طبق تعریف xray-core مشخص شده، تغییر اسم کاری انجام نمیده. عملا همه هرمدلی دلشون بخواد تنظیم میکنن
۳. قابلیت های نرم افزار های AAA از طاقت این نرم افزار کوچک خارجه. نه اینکه نشه. بلکه همه گیر نیست و باعث کلی بار اضافه و سوتفاهم برای کاربران میشه.
۴. این مدل از استفاده بات تلگرام و اضافه نکردن بغضی امکانات به دلیل اینه که تا الان نمیخواستیم دیتابیس رو تغییر بدیم. اگر در آینده تصمیم گرفتیم این کار رو انجام بدیم حتما جداسازی خواهیم کرد
۵. میتونم روی این گزینه کار کنم. ممنونم از پیشنهادتون

## سوالات
۱. بخش تنظیمات پیشرفته x-ray برای کسانی که به صورت حرفه ای از الگو های تنظیمات استفاده میکنند مناسبه.
این دو گزینه برای بستن دسترسی کاربران به پروتکل bittorrent و دیگری برای حذف دسترسی برای IP های غیرمعتبر استفاده میشه.
۲. این گزینه عددی رو فقط برای vmess داریم و جزو تنظیمات اون محسوب میشه. اینکه چیکار میکنه رو بهتره از [اینجا](https://www.v2ray.com/en/configuration/protocols/vmess.html#userobject) ببینید

میتویند برای من مستقیم ایمیل بفرستید
