### ISSUE TITLE
اینباند

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#900]
فعال و غیر اینباند کار نمیکنه اگر غیر فعال بشه دیگه فعال نمشه دیتا بیس رو ویرایش کردم دو باره فعال کردم

**Comment by alireza0** [comment]
لطفا قبل از باز کردن ایشو جدید، جستجو کنید. #862 :

> بله این باگ شناخته شده بود در روز اول ریلیز و با https://github.com/alireza0/x-ui/commit/30d73764632607727e0657eba5d78f889edb12ac حل شد. در نسخه بعد این مورد برطرف میشه.
> برای راه حل موقت از ویرایش استفاده کنید.
