### ISSUE TITLE
غیرفعال شدن پنل بعد از آپدیت به نسخه جدید

### ISSUE THREAD

**Issue by HO3EINNNK** [alireza0/x-ui#901]
سلام و خسته نباشید
من نسخه 1.7.5 رو استفاده میکردم که بعد از ارتقا به نسخه آخر پنل error میخوره و با تغییر ورژن های x-ui از داخل خود پنل هم running نمیشه؛ چیکار باید بکنم؟ از طریق سرور دوباره برمیگردونم به نسخه 1.7.5 کار میکنه ولی وقتی میخوام ارتقا بدم میوفته رو error و قرمز میشه!! راه حلی دارن از دوستان که من رو کمک بکنه؟ ممنون از شما

**Comment by alireza0** [comment]
درود بر شما
آخرین نسخه این پنل 1.7.0 هست. آیا شما از آینده میاید ؟

**Comment by HO3EINNNK** [comment]
> درود بر شما آخرین نسخه این پنل 1.7.0 هست. آیا شما از آینده میاید ؟

من والا سنایی رو نصب کرده بودم نمیدونم چرا از طریق پنل به صفحه شما منتقل شدم😅 در هر صورت ممنونم مشکلم اوکی شد
ینی اینجوری حل شد که ورژن ارتقا یافته روی تروجان و XTLS کار نمیکنه و باید تغییر بدی به پروتکول دیگه
گفتم اینم بگم که بقیه هم در جریان باشن
