### ISSUE TITLE
مشکل با تمدید سرتیفیکت

### ISSUE THREAD

**Issue by alirezani** [alireza0/x-ui#903]
سلام من می خواهم سرتیفیکت پنل را تمدید کنم پورت 80 توسط apache اشغال است.لطفا راهنمایی کنید

[Mon 29 Jan 2024 05:45:55 AM CET] The domain '*******.top' seems to have a ECC cert already, lets use ecc cert.
[Mon 29 Jan 2024 05:45:55 AM CET] Renew: '*********.top'
[Mon 29 Jan 2024 05:45:55 AM CET] Renew to Le_API=https://acme-v02.api.letsencrypt.org/directory
[Mon 29 Jan 2024 05:45:57 AM CET] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon 29 Jan 2024 05:45:57 AM CET] Standalone mode.
[Mon 29 Jan 2024 05:45:58 AM CET] LISTEN    0         511                      *:80                     *:*        users:(("apache2",pid=45821,fd=4),("apache2",pid=36563,fd=4),("apache2",pid=36562,fd=4),("apache2",pid=36561,fd=4),("apache2",pid=36560,fd=4),("apache2",pid=36559,fd=4),("apache2",pid=36534,fd=4))
[Mon 29 Jan 2024 05:45:58 AM CET] tcp port 80 is already used by (("apache2",pid=45821,fd=4),("apache2",pid=36563,fd=4),("apache2",pid=36562,fd=4),("apache2",pid=36561,fd=4),("apache2",pid=36560,fd=4),("apache2",pid=36559,fd=4),("apache2",pid=36534,fd=4))
[Mon 29 Jan 2024 05:45:58 AM CET] Please stop it first
[Mon 29 Jan 2024 05:45:58 AM CET] _on_before_issue.

**Comment by alireza0** [comment]
درود بر شما
این مشکل ربطی به پنل نداره
لطفا از ایراد سوالات خارج از این پنل خودداری کنید
