### ISSUE TITLE
قوانین مسیریابی و خروجی

### ISSUE THREAD

**Issue by Avampiire** [alireza0/x-ui#906]
سلام و درود به علیرضا عزیز
آقا آیا امکان این وجود داره برای تانل از طریق خروجی و قوانین مسیریابی یک دامنه خاص رو به این تانل اختصاص بدیم چون من از اکسترنال پروکسی استفاده می کنم و 4 دامنه فعال دارم میخوام یکی از دامنه هام فقط رو یک اینباند دایرکت بشه برای تانل؟؟!!

**Comment by alireza0** [comment]
درود بر شما
بله
کافیه قانون استثنا رو بالاتر از قوانین ریورس بذارید

**Comment by Avampiire** [comment]
علیرضا عزیز سلام مجدد
ممنون از پاسخ اما کامل متوجه نشدم و اینکه باید توضیحات بیشتری خدمتت ارائه می دادم .
چیدمان پنل من به اینصورته 4 دامنه دارم که همگی به cdn کلودفلر وصل هستن و از روش vless/ws/tls هم استفاده می کنم و 4 ورودی با پورت های https ساخته ام و هر ورودی یوزرهای خودش را دارد و هر ورودی را external proxy را روشن کردم و 4 دامنه نه با تگ همسان بلکه تگ tls و در آخر ssl هر دامنه را اضافه کردم
حالا من از قسمت قوانین اومدم بخش خروجی و یک کانفیگ از پنل دیگرم یک لوکیشن دیگر اضافه کردم و در قوانین مسیریابی تنظیم کردم که یک ورودی با پورت مثلا 443 به صورت کامل متصل به لوکیشن مورد نظر شود در صورتی که میخواهم اگر بشود فقط یکی از دامنه هایی که در هر ورودی در قسمت اکسترنال پروکسی قراردادم به لوکیشن دیگر وصل شود و بقیه دامنه ها به لوکیشن پیش فرض خودشون متصل بشن در ضمن سابسکریپشن هم با یک دامنه جداگانه فعال است 
راهی برای این موضوع هست علیرضا جان؟؟

**Comment by alireza0** [comment]
تنظیمات بخش external proxy مربوط به اتصال کاربر به خارج از پنل هستند و از مسیر های خارجی به xray متصل میشوند.
این تنظیمات در روتینگ ها قابل دیدن نیستند. بهتره ازنرم افزار هایی شبیه nginx و یا haproxy برای جداکردن ترافیک این دامنه ها استفاده کنید

**Comment by Avampiire** [comment]
متوجه شدم
درود بر تو مرد بزرگ
