### ISSUE TITLE
How new WARP works?

### ISSUE THREAD

**Issue by sohate** [alireza0/x-ui#907]
Can you please explain how new WARP works? Should I install additional warp (https://github.com/hamid-gh98/x-ui-scripts) or it works without it? Thanks!

**Comment by alireza0** [comment]
As far as xray-core supports `wireguard` protocol, there is no need to install an external `wireguard` app.
In this panel, it will generate automatically and fully works without any external app.

**Comment by sohate** [comment]
@alireza0 Sorry, but it's just not working. I've tried everything, but WARP+ doesn't work. I added a key (the key is fine), added in "Inbound tag" my inbouds (vless, reality), added warp in "outbound tag". And no internet at all.

**Comment by alireza0** [comment]
You should define a Routing rule to use your warp outbound interface.
Or simply move your warp outbound to the first outbound ( default outbound )

**Comment by sohate** [comment]
@alireza0 Tested. Yes, if I move warp outbound to the first outbound everything works fine. It's very not intuitive, but at least it works. 3X-Panel's WARP doesn't work at all, tested every scenario.

Thank you very much for clarifying.
