### ISSUE TITLE
درخواست بروزرسانی ضروری و مهم برای پنل

### ISSUE THREAD

**Issue by javadmahmoodi670** [alireza0/x-ui#908]
سلام
من از پنل سنایی به پنل شما اومدم و خواهش میکنم لطفا مثل پنل سنایی گذینه انتخاب تعداد کاربر برای متصل شدن به اکانت را اضافه کنید.
درضمن ربات تلگرام هم اگه میتونید دکمه های واکنشی برای تمدید تاریخ یا حجم دقیقا مانند پنل سنایی رو اضافه کنید.
باتشکر

**Comment by alireza0** [comment]
درود بر شما
نه متاسسفانه. باید یه تفاوتی بین دوپنل باشه

**Comment by javadmahmoodi670** [comment]
خب تفاوت به مزایا و داشته هاست و برتری داشتن نه نداشتن امکانات.
بنظرم مثلا شما متفاوت تر ربات رو انجام بدید.
الان تو صنعت گوشی های موبایل و حتی رابط کاربری ها میبینید چجوری نزدیک به هم و حتی با خلاقیت از هم پیشی میگیرن.
البته که شما خلاق هستید منظورم این هست که شما هم پنلتون را با امکانات و حتی بهتر و با رابط کاربری حرفه ای تر رو در اختیار کاربراتون قرار بدید بهتره.
تفاوت اینجوریش خوبه برای توسعه دهنده و کاربرانش.
ممنون

**Comment by alireza0** [comment]
من دنبال رقابت و برتری نیستم
اگر ویژگی بتونه به صورت موثر به هدف نرم افزار کمک کنه، استقبال میکنم.
ولی به صورت کلی با اهداف تجاری سازی مخالفم. البته دلایل زیادی هست که قبلا گفتم.
