### ISSUE TITLE
gRPC MultiMode

### ISSUE THREAD

**Issue by The-1818** [alireza0/x-ui#909]
Hello community, if you choose gRPC transmission method there's a setting "MultiMode", does anybody know what it does? Is it better to have it enabled or disabled? Couldn't find any information on the internet about it.

**Comment by MHSanaei** [comment]
https://xtls.github.io/en/config/transports/grpc.html

**Comment by The-1818** [comment]
> https://xtls.github.io/en/config/transports/grpc.html

Interesting, thank you. Have you tried using it maybe?

**Comment by MHSanaei** [comment]
Yes but i didn't saw any difference
