### ISSUE TITLE
قابلیت کپی کردن کانفیگ

### ISSUE THREAD

**Issue by hashemim66110** [alireza0/x-ui#91]
سلام جناب
توی سرور ها یکی از چیزایی که خیلی لازمه اینه که بتونیم از روی یه کانفیگ، داپلیکیت بگیریم
اینطوری که مثلا میخوایم اکانت 30 گیگ درست کنیم،  هی میایم برای هر اکانت یه کانفیگ تعریف میکنیم و همه اون کارا رو دوباره انجام میدیم
در حالی که خیلی راحت میشه دکمه داپلیکیت گذاشت و از روی اکانت کپی کرد
اینطوری دیگه لازم نیست همه مراحلو دوباره و دوباره تکرار کنیم، فقط یه بار انجام میدیم و بعدیا رو کپی میکنیم

به نظرم خیلی جالب میشه اگه ادش کنی، و خیلی کاری نداره
فقط باید به /xui/add یا یه چنین چیزی، یه ریکوئست بفرستی با اطلاعات همون کانفیگی که انتخاب شده.

**Comment by alireza0** [comment]
درود بر شما
امکان ایجاد کاربر دسته ای به همین دلیل درست شده. میتونین ازش استفاده کنید
