### ISSUE TITLE
مشکل عدم نمایش کاربران انلاین و حجم مصرف شده

### ISSUE THREAD

**Issue by alihosseinii67** [alireza0/x-ui#911]
سلام من پنل رو نصب کردم الان بعد چند روز نه تعداد یوزر انلاین رو نشون میده نه حجم مصرف شده از کانفیگهارو پنل رو روی چندتا سرور نصب کردم رو بقیه اوکیه تعداد رو با رنگ سبز نشون میده ولی یه سرورم بعد چند روز ثابت شد هیچی نشون نمیده چقدر مصرف شده مشکل از چیه راه حلی داره که یوزرام نپره؟

**Comment by alireza0** [comment]
درود بر شما
مشکل از ترتیب قوانین مسیریابیه
باید قانونی که برای api هست همیشه اول باشه تا این خاصیت فعال بشه

**Comment by liamnees** [comment]
راهی هست لینک سابسکرایبی که خارج ار پنل درست می کنی اونم مثل لینک ساب پنل حجم و تاریخ اکانت کنار لینک نشان بده؟

**Comment by alireza0** [comment]
@liamnees 
خیر
