### ISSUE TITLE
در تانل پنل به پنل ، دسترسی به سایت های ایرانی مسدود نمیشه

### ISSUE THREAD

**Issue by GithubUN89** [alireza0/x-ui#912]
سلام 
دو سرور ایران و خارج رو بصورت معکوس ، پنل به پنل کردم ، اما بعد از فعال کردن مسدود کردن سایت های ایرانی ، دسترسی به سایت های ایرانی مسدود نمیشه 

لطفاً رفعش کنید 
ممنون

**Comment by alireza0** [comment]
درود بر شما
این مشکل مربوط به پنل نیست. تنظیمات شما برای xray این نحوه بازخورد رو داره.

**Comment by mohamadn69** [comment]
استراتژی روتینگ داخل تنظیمات باید حتما ipifnonematch  باشه تا ip block یا ip direct کار کنه.  طبق تجربه این کار باعث کند شدن سرور  و سرعت میشه . من از Asis استفاده میکنم و در عوض دامین ها را دایرکت یا بلاک میکنم.

**Comment by mohamadn69** [comment]
routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "regexp:.*\\.ir$",
          "regexp:.*\\.xn--mgba3a4f16a$",
          "ext:geosite_IR.dat:ir"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "ext:geoip_IR.dat:ir"
        ]
      }
    ]
  },

**Comment by alireza0** [comment]
وقتی شما sniffing رو برای ورودی ها فعال میکنید، مقصد پکت ها در ابتدای ورود به دامنه تبدیل میشن.
به همین دلیل با استراتژی AsIs نمیتونید همه ip ها رو بلاک یا دایرکت کنید.
استراتژی ipIfNonMatch هم اول مثل AsIs چک میکنه و اگر match نشد میاد دامنه رو ترجمه میکنه و یکبار دیگه تمام قوانین رو بررسی میکنه.
به همین دلیل هم منابع بیشتری میگیره و هم کندتره.

اگر فقط قوانین ip دارید، sniffing معنی نداره. اگر فقط قوانین domain دارید، حتما از AsIs استفاده کنید. و اگر شرایط ترکیبی دارید و منابعتون خوبه، ipIfNonMatch بذارید

**Comment by mohamadn69** [comment]
دقیقا . کسایی که سرور ایران را پنل به پنل میزنن بهتره که سایت های ایران را دایرکت کنن که از اوتباند سرور خارج رد نشن .با توجه به اینکه سرعت اینترنت خارج کشور را محدود کردن  هم توی سرعت و مصرف ترافیک خارجی تاثیر میزاره هم سایت های بانک و ... به راحتی باز میشن و توی دام فیلترینگ نمی افتید. من یکساله از این روش استفاده کردم و خوشبختانه فیلتر نشدم.  تنها بدیش اینه که اگه تخلفی صورت بگیره با ip سرور شما انجام میشه و شما گیر هستید. ولی خب احتمالش کمه
