### ISSUE TITLE
Some bugs in v1.7.0

### ISSUE THREAD

**Issue by MK0ltra** [alireza0/x-ui#913]
1.
XRAY CONFIGS >> Advanced:
in this section, inbounds not showing and just api inbound shows up.

2.
When turning off an inbound with switch button, it says success but switch button is still on. even after reloading page it's still on.

**Comment by alireza0** [comment]
1. It is not a bug! In xray config you could only change the templates. In final conguration file, all inbounds will be copied from database to the template.
2. It is a known bug and fixed already. Please wait for next release and just use edit inbound to disable it meanwhile.

**Comment by MK0ltra** [comment]
Oh ok. I got it now but i think it's necessary to let user's edit inbounds with json like older versions, because all parts of configuration can be edited with json except inbounds, but It's your decision. Thanks.

**Comment by alireza0** [comment]
In latest versions we never provided json edit for inbounds.
It was only for Inbound template which is still exists in `Advanced` tab
