### ISSUE TITLE
سابسکریشن داخلش ارور هستش

### ISSUE THREAD

**Issue by tarighi82** [alireza0/x-ui#914]
اونی که با api از طریق ربات میسازه رو سابش رو نمیاره و Error! مینویسه وگرنه همون رو که ربات ساخته رو از تو پنل کلون میکنم سابش کار میکنه. انگار مشکل پنله

**Comment by alireza0** [comment]
این باگ بات شماست که کانفیگ رو به صورت استاندارد ارائه نمیده.
اول مطمئن بشید نسخه پنل شما با نرم افزار جانبی سازگاره و در صورت وجود مشکل از سازنده اش پیگیر بشید
