### ISSUE TITLE
پاک کردن یک جا این باندها

### ISSUE THREAD

**Issue by vahid68-vpn** [alireza0/x-ui#917]
سلام علیرضا جان لطفا گذینه ای اضافه کن که بشه تمام این باندهارو پاک کرد
و مسعله دوم اینکه مثلا الان یک کانفیگ برای مشتری میزنم و حجم 30 گیگ براش تعریف میکنم و
 مشتری حجم رو زودتر از 30 روز تموم میکنه میخوام گذینه ای اضافه کنید که بشه دید چه مدت زمانی این حجم رو تموم کرده

**Comment by vahid68-vpn** [comment]
جواب مارو ندادین علیرضا جان

**Comment by wulfric93** [comment]
خب زمان بدید که متوجه بشید توی چه مدتی مصرف کردن  دیگه

**Comment by alireza0** [comment]
درود بر شما
ببخشید که این ایشو رو ندیدم و دیر جواب میدم.
توی این پنل امکان ذخیره کردن زمان مصرف کاربر وجود نداره و برای اضافه کردنش باید ساختار کلی عوض بشه.
اگر هم اضافه نشده بیشتر به دلیل اینه که ذخیره دیتای خیلی زیادی داره که مصرف خیلی کمی داره واین خودش مشکلات خیلی زیادی ایجاد میکنه.
