### ISSUE TITLE
مشکل تگ direct در قوانین مسیریابی

### ISSUE THREAD

**Issue by siamakmu** [alireza0/x-ui#919]
پیش از هر چیز خیلی تشکر میکنم از جناب علیرضای عزیز بابت این پنل حرفه ای.

در بخش Routing نرم افزار های v2Ray چه کامپیوتر و چه موبایل وقتی Rule جدید میسازیم در قسمت outboundTag معمولاً سه گزینه ی proxy ، direct و block وجود داره.
الآن داخل پنل علیرضا و سنایی پیش فرض دو تگ direct و blocked وجود داره که با فعال کردن warp هم سه تا حساب میشه. من خیلی زیاد تست کردم. تگ blocked که کارشو به خوبی انجام میده و تمام دامین ها یا سایر موارد رو طبق خواسته و تنظیمات ادمین برای کاربران غیر قابل میکنه. تگ warp هم به همین ترتیب بی نظیر عمل میکنه و از کلادفلر عبور میکنه ولی تگ direct داره کارشو اشتباه انجام میده و به جای اینکه مثل نرم افزار های کلاینت کامپیوتری و موبایلی تگ direct کارش این باشه که برای اتصال به سایت های مورد نظر از IP عادی کاربر (آی پی ایران) استفاده بشه و دیگه از IP سرور متصل استفاده نکنه داره مشابه تگ proxy استفاده میکنه و در واقع هر قانونی که با direct تعریف میکنیم همون کار عادی Inbound ها رو پیش میگیره. حتی "اتصال مستقیم دامنه‌های ایران" و "اتصال مستقیم دامنه‌های ایران" که فعال میکنیم و قوانین مسیریابی اضافه میشه به همین ترتیب عمل میکنه

### بدون پروکسی:
<img width="1230" alt="image" src="https://github.com/alireza0/x-ui/assets/51283486/466cf053-dfb4-4836-afb3-3be44e615552">

______________________________________________________________________

### blocked که به درستی کار میکنه:
<img width="1460" alt="image" src="https://github.com/alireza0/x-ui/assets/51283486/c668397f-8344-4db8-a724-71c7b6455d24">

______________________________________________________________________

### direct که هنوز داره از پروکسی رد میکنه:
<img width="1273" alt="image" src="https://github.com/alireza0/x-ui/assets/51283486/7fc7da42-60db-42fa-957d-cbe767f74aa5">

______________________________________________________________________

### warp که به درستی کار میکنه:
<img width="1314" alt="image" src="https://github.com/alireza0/x-ui/assets/51283486/a5b2a8aa-4779-45f8-8758-4a38227b2a3a">

اگر منظور شما از direct همین رد شدن از پروکسی بوده پس باگ حساب نمیشه و فقط بهتره به جای تگ دایرکت نوشته بشه proxy و ازتون راهنمایی میخوام برای ساخت یک outbound که مقصود مورد نظر منو انجام بده.

بازم خیلی متشکرم از شما.

**Comment by ErfanTech** [comment]
> پیش از هر چیز خیلی تشکر میکنم از جناب علیرضای عزیز بابت این پنل حرفه ای.
> 
> در بخش Routing نرم افزار های v2Ray چه کامپیوتر و چه موبایل وقتی Rule جدید میسازیم در قسمت outboundTag معمولاً سه گزینه ی proxy ، direct و block وجود داره. الآن داخل پنل علیرضا و سنایی پیش فرض دو تگ direct و blocked وجود داره که با فعال کردن warp هم سه تا حساب میشه. من خیلی زیاد تست کردم. تگ blocked که کارشو به خوبی انجام میده و تمام دامین ها یا سایر موارد رو طبق خواسته و تنظیمات ادمین برای کاربران غیر قابل میکنه. تگ warp هم به همین ترتیب بی نظیر عمل میکنه و از کلادفلر عبور میکنه ولی تگ direct داره کارشو اشتباه انجام میده و به جای اینکه مثل نرم افزار های کلاینت کامپیوتری و موبایلی تگ direct کارش این باشه که برای اتصال به سایت های مورد نظر از IP عادی کاربر (آی پی ایران) استفاده بشه و دیگه از IP سرور متصل استفاده نکنه داره مشابه تگ proxy استفاده میکنه و در واقع هر قانونی که با direct تعریف میکنیم همون کار عادی Inbound ها رو پیش میگیره. حتی "اتصال مستقیم دامنه‌های ایران" و "اتصال مستقیم دامنه‌های ایران" که فعال میکنیم و قوانین مسیریابی اضافه میشه به همین ترتیب عمل میکنه
> 
> ### بدون پروکسی:
> <img alt="image" width="1230" src="https://private-user-images.githubusercontent.com/51283486/302032346-466cf053-dfb4-4836-afb3-3be44e615552.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDk3MzMsIm5iZiI6MTcwODAwOTQzMywicGF0aCI6Ii81MTI4MzQ4Ni8zMDIwMzIzNDYtNDY2Y2YwNTMtZGZiNC00ODM2LWFmYjMtM2JlNDRlNjE1NTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE1MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NzQ2MTY0M2ZjNmUzMWViNWEwMDI0Y2Y3YjU1ZDYzNTAxY2ZjZDUxMTlmZDhiN2IwZTZiZWFhOTk4MTY3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7EdyaRU4o6yj_b0p9yswGGtQni53bFfu8XSGFHnarhQ">
> ### blocked که به درستی کار میکنه:
> <img alt="image" width="1460" src="https://private-user-images.githubusercontent.com/51283486/302032484-c668397f-8344-4db8-a724-71c7b6455d24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDk3MzMsIm5iZiI6MTcwODAwOTQzMywicGF0aCI6Ii81MTI4MzQ4Ni8zMDIwMzI0ODQtYzY2ODM5N2YtODM0NC00ZGI4LWE3MjQtNzFjN2I2NDU1ZDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE1MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZDg0NDE5ZGU0YWFhZDY2ZDdkNmI2ZjNhMDI4ZDk0M2U3NTQ1OTQ3YWE0NmM5YzgyY2Y3NjdjYTA4YTYzM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7Rn97lA8H4wQuPryskVWLskGtp7vZnyHOYj7Tegb_WM">
> ### direct که هنوز داره از پروکسی رد میکنه:
> <img alt="image" width="1273" src="https://private-user-images.githubusercontent.com/51283486/302032669-7fc7da42-60db-42fa-957d-cbe767f74aa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDk3MzMsIm5iZiI6MTcwODAwOTQzMywicGF0aCI6Ii81MTI4MzQ4Ni8zMDIwMzI2NjktN2ZjN2RhNDItNjBkYi00MmZhLTk1N2QtY2JlNzY3Zjc0YWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE1MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzM2ZkYjJiOThkNzE5MTI0MzZkOTVlMWFkNTk4YzlmMzY5NmI0M2NhMGI0MDUzMTQzOThlZTM4MDU4N2ExMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uiEtjpQj7w4HW_tjMUlbp4LXnkOviTvOK8zyJruUn0c">
> ### warp که به درستی کار میکنه:
> <img alt="image" width="1314" src="https://private-user-images.githubusercontent.com/51283486/302032780-a5b2a8aa-4779-45f8-8758-4a38227b2a3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDk3MzMsIm5iZiI6MTcwODAwOTQzMywicGF0aCI6Ii81MTI4MzQ4Ni8zMDIwMzI3ODAtYTViMmE4YWEtNDc3OS00NWY4LTg3NTgtNGEzODIyN2IyYTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE1MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YTM0YWUxMzJlZjA2M2Y4MDlhMzI2ODE4ZTU1ZTMyMmZhZmIzYzBmN2EzOGVhYjk0ZmEwNjM4OTMxNGY4N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pZ4xleWx-o_sKsTPRWeFUyjcpF3XNLUCdW7_uTWB788">
> اگر منظور شما از direct همین رد شدن از پروکسی بوده پس باگ حساب نمیشه و فقط بهتره به جای تگ دایرکت نوشته بشه proxy و ازتون راهنمایی میخوام برای ساخت یک outbound که مقصود مورد نظر منو انجام بده.
> 
> بازم خیلی متشکرم از شما.

@alireza0

**Comment by ErfanTech** [comment]
@alireza0

**Comment by alireza0** [comment]
تگ direct برای اینه که از خروجی سرور شما استفاده بشه.
سرور شما خارج از ایرانه و ترافیک شما بدون اعمال قانون آخر هم به direct میره.

چیزی که شما لازم دارید دایرکت کردن از کلاینت خودتونه که باید توی همون نرم افزار تنظیم بشه و نه از سرور.

**Comment by siamakmu** [comment]
سلام و عرض ادب،
خیلی ممنون از شما.
من برای استفاده ی خانوادگی و دوستان سرور راه اندازی کردم ولی خب کاربرها رعایت نمیکنن و هر ترافیک ایران هم که واقعاً نیازی نیست وقتی از سرور رد میشه باعث زود فیلتر شدن دامین میشه. راهی نیست این دایرکت کردن رو بشه از سمت سرور تنظیم کرد تا بدون نیاز به تنظیم بر روی تک تک دیوایس ها خودکار انجام بشه؟

**Comment by alireza0** [comment]
اگر سرور خانوادگیه برای همه زمان نصب کردن روی گوشی اونها تنظیم کنید که ترافیک ایران از این تنظیم رد نشه.
بهتره دسترسی ایران رو برای این مشکل بلاک کنید و یا از وارپ رد کنید.

**Comment by ErfanTech** [comment]
> سلام و عرض ادب،
> خیلی ممنون از شما.
> من برای استفاده ی خانوادگی و دوستان سرور راه اندازی کردم ولی خب کاربرها رعایت نمیکنن و هر ترافیک ایران هم که واقعاً نیازی نیست وقتی از سرور رد میشه باعث زود فیلتر شدن دامین میشه. راهی نیست این دایرکت کردن رو بشه از سمت سرور تنظیم کرد تا بدون نیاز به تنظیم بر روی تک تک دیوایس ها خودکار انجام بشه؟

برای این که از سرور بتونی کنترل کنی، می‌تونی یه سرور ایران بگیری، روش پنل رو نصب کنی و تنظیمات `direct` رو براش فعال کنی
 راهی جز این نیست
