### ISSUE TITLE
Enabled button cannot be closed

### ISSUE THREAD

**Issue by PillerC** [alireza0/x-ui#924]
创建的主节点不可以关闭，图片箭头所指；子节点可以关闭，下面的节点。
Translated by AI: The created main node cannot be closed, as indicated by the arrow in the picture; the child nodes can be closed, as shown below.
![image](https://github.com/alireza0/x-ui/assets/126148420/ceba05c8-1048-4307-b784-cc134f87de81)

**Comment by wulfric93** [comment]
this bug was known on the first day of release and was solved with [30d7376](https://github.com/alireza0/x-ui/commit/30d73764632607727e0657eba5d78f889edb12ac). This will be fixed in the next version.
Use edit for workaround.
