### ISSUE TITLE
ارور 403 گوگل و زیر مجموعه هاش

### ISSUE THREAD

**Issue by mrsalehimr** [alireza0/x-ui#925]
سلام

من مشکل 403 گوگل دارم قبلا روی خود پنل وارپ و طریقه ی نصبش بود اما الان چیزی ندیدم. سرچ هم کردم باز نتیجه ای نگرفتم. راه حلی اگر داره ممنون میشم بذارید.

با تشکر

**Comment by alireza0** [comment]
https://www.youtube.com/watch?v=lT4VdOy5nYc
