### ISSUE TITLE
قطعی اینباند در ساخت اینباند جدید

### ISSUE THREAD

**Issue by roozbeh-m03** [alireza0/x-ui#926]
سلام، من ریورس تانل انجام دادم و خوبه، ولی تو بخش اینباند ها وقتی یه اینباند جدید درست میکنم تمامی کلاینت های اینباند قبلی قطع میشن و دیگه نمیشه وصل شد حتی وقتی میخوام برای ربات تلگرام dokodemo-door درست کنم. باید چیکار کنم که قطع نشه.
ممنون

**Comment by alireza0** [comment]
درود بر شما
من که متوجه نشدم منظور شما چیه.
ولی این موارد هیچ ربطی به هم ندارن. مشکل شما احتمالا از جای دیگه است
