### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by Johnwick-68** [alireza0/x-ui#927]
سلام علیرضا جان وقت بخیر

میخواستم بدونم دامنه Subscription رو چطور میشه تغییر داد که دامنه قبلی از کار نیوفته تا کاربران منتقل بشند به دامنه جدید؟

چون زمانی که دامنه دی دیگری ست میشه.داخل کلاینت آپدیت که میزنیم خطا میده به دلیل اینکه دامنه قبلی اطلاعاتی نمیگیره که بروز بشه

یا اینکه این قسمت رو میشه مولتی دامنه قرار داد؟اگر بله ممنون میشم یه راهنمایی کنی

تشکر برای زحماتی که میکشی

**Comment by wulfric93** [comment]
بعید میدونم امکانش باشه 
وقتی عوض شد ، عوض شده دیگه ، از قبلی نمیگیره

**Comment by Johnwick-68** [comment]
مشکل اینجاست که دامنه های اشتراکی رو بعد از مدتی یا ریپورت میدن یا به دلیل درخواست زیاد سمت یه دامنه فیلترینگ میاد ف.ل.ت.ر میشه داخل ایران.

برای همین بهتره راندوم استفاده بشه یا چند وقت یه بار تغییر کنه که این موارد پیش نیاد.

اگر حالتی قرار بگیره دامنه ست بشه دامنه قبلی از کار نیوفته برای کاربر اعمال بشه خیلی کمک میکنه

**Comment by Ghasem1243** [comment]
ساده است یکی از پورت های کلود فلر رو براش بزار و دامنه رو فقط برا ساب بزار  هیچ وقت فیلتر نمییشه  میتونی از http استفاده کنی فیلتر شدن خیلی کم پیش میاد

**Comment by Johnwick-68** [comment]
دوست عزیز همه اینکار ها انجام شده.منتهی زمانی که ریپورت بشه یا درخواست زیاد باشه باز هم فیلتر میشه.نمونش مدتی پیش شد.!اگر بشه جوری فعال کرد که دامنه قبلی از کار نیوفته و یه دامنه جدید هم فعال کرد موقتی یا روشی تو همین  موارد باشه مشکل حل میشه.

**Comment by Johnwick-68** [comment]
علیرضا جان امکانش هست موردی اضافه کنید که بتونیم دامنه Subscription رو بدون اینکه قبلی از کار بیوفته برای کل کاربران اعمال کنیم؟در صورت فیلتر شدن حتی اگر دامنه رو تغییر بدیم و کاربر با پروکسی بروز کنه چون دامنه جدید ست میشه و قبلی از کار میوفته مشکل ساز هست. عملا همه باید دستی داخل فایل کانفیگک اعمال کنند این تغییرات رو.ممنون میشم تو نسخه جدید یه تغییری در این خصوص هم انجام بدید
