### ISSUE TITLE
Something went wrong! Fail: Duplicate email

### ISSUE THREAD

**Issue by r0zbeh** [alireza0/x-ui#928]
با سلام من یه کد نوشتم برای شارژ اکانت از طریق updateClient/ بیشتر وقت ها اوکیه و کار میکنه ولی بعضی وقتا هم این خطا رو میده 

> {"success":false,"msg":"Something went wrong! Fail: Duplicate email: نام ایمیل کاربر\n","obj":null}

معلومه یوزر وجود داره چون من میخوام ادیت (آپدیتش کنم ) الان مشکل کجاست؟ چرا بعضی وقتا این خطا رو میده؟

**Comment by r0zbeh** [comment]
مشکل حل شد ! برای کسایی که شاید به این خطا بخورن !!
راه حل : بنا به دلایلی uuid که من ارسال میکردم با اونی که تو پنل بود تفاوت داشت و یه جورایی Duplicate ایجاد میشد !! من با همسان سازی اونا قضیه رو اوکی کردم ! شاد باشید

**Comment by mitsukuri** [comment]
IMHO it would be better to check for duplicates in one inbound group and not across all of them. One person can have multiple entries - one for shadowsocks, one for vless, etc...
