### ISSUE TITLE
سوال در رابطه به تایم بکاپ گیری در تلگرام

### ISSUE THREAD

**Issue by blackwolf99f** [alireza0/x-ui#93]
سلام رفیق وقتت بخیر و یه دنیا ممنونم بابت تلاش هات واسه بهبود این پنل عالی

یه سوالی دارم که جایی نتونسم جوابشو پیدا کنم

ما اگه بخوایم فایل بکاپمون روزانه ارسال شه از این کد استفاده میکنیم @daily

اگه ساعتی بخوایم از این @hourly استفاده میکنیم

اگه دقیقه ای یا مثلا 15 دقیقه یه بار بخوایم بکاپ ارسال شه از چه کدی باید استفاده کنیم 
یکی گفت این کد */5 * * * * باعث میشه هر 5 دقیقه ارسال شه که جواب نداد 
ممنون میشم اگه راهنمایی کنی

**Comment by alireza0** [comment]
درود بر شما
برای ایکار بهتره از [متد های از پیش تعریف شده](https://pkg.go.dev/github.com/robfig/cron#hdr-Predefined_schedules) استفاده کنید. برای مثال شما:
```
@every 5m
```
