### ISSUE TITLE
امیدوارم اضافه بشه خوبه

### ISSUE THREAD

**Issue by Ghasem1243** [alireza0/x-ui#932]
با عرض سلام 
این لیستی که میتوانید اضافه کنید 
1.تمدید ، ساخت و حذف کلاینت به ربات اضافه کنید (البته من دارم از api استفاده میکنم رو ربات خودم )
2.بجای ما بیایم پنل ssh جدا بزنیم با همین پنل ادغام بشه 
3.کلاینت بتونه به چنتا اینباند متصل بده یعنی پروتکل جدا براش بیاد وقتی ساب رو آپدیت کنه 
4. موتلی sni و مولتی host همان request host چنتا بزاریم و یا جوری باشه همان uuid + domian  بشه ساب دامین و ما فقط دامنه رو اضافه کنیم و واسه هر یوز ساب دامین جدا میاد من اینکار رو کردم ولی خوب sub دیگه بدرد نمیخوره اینطوری ( من توی ربات تلگرام اینکار رو کردم )  میتوانید از api کلود فلر استفاده کنید یعنی api key و api zone  کلود رو بزنیم هر کلاینت که بسازیم یک ساب دامین مخصوص خودش درست بشه و وقتی کلاینت پاک کنیم ساب دامین پاک پشه این طور دیر فیلتر میشه دامین
ممنون از شما امید وارم تغییرات نزدیک باشه بهترین پنل علی رضا و ثنایی درود بر شما

**Comment by alireza0** [comment]
درود بر شما
۱. این امکان توی اولویت ها نیست
۲. منظورتون رو متوجه نمیشم. پنل فقط پروتکل های XRAY رو قراره ساپورت کنه.
۳. این امکان وجود داره. ولی چند کاربر رو توی یک ساب ارائه بدید. مدل پنل اجازه مولتی پروتکل رو نمیده.
۴. این پیچیدگی بیش از حد تحمل این پنل و نوع کارش هست. میتونید این کار رو خودتون با نرم افزار دیگه ای بنویسید.
