### ISSUE TITLE
قطع و وصل شدن تانل ریورس

### ISSUE THREAD

**Issue by hasan4643** [alireza0/x-ui#933]
سلام مرسی از زحماتت این تانل معکوس گاهی اوقات قطع میشه و بعد چند دقیقه وصل میشه و ارور  EOF میده مشکل چیه و چطور میکتونم حلش کنم؟
و یه مشکل دیگه چند روز یک بار یکی از پورتام از حالت تانل خارج میشه و باید از قسمت معکوس مجدد تیک اون پورتو بزنم

**Comment by alireza0** [comment]
مشکل اول مربوط به پنل نیست و باید با xray-core مطرح بشه.
مشکل دوم بعیده، هیچ روالی توی پنل این کار رو نمیکنه.

**Comment by hasan4643** [comment]
نه چندین بار برا من شده مخصوصا پورت 2096

**Comment by alireza0** [comment]
> نه چندین بار برا من شده مخصوصا پورت 2096

تنظیم ورودی های پورتال توی قوانین مسیریابی تنظیم میشن. حتی بعد از حذف ورودی هم اونجا میمونن و هیچی نباید حذفشون کنه. مطمئن بشید که دسترسی به پنل رو فقط خودتون دارید و بات و یا کسی دیگه دسترسی نداره.

**Comment by alireza0** [comment]
> مشکل اولو چه میشه کرد؟

خطای EOF بیشتر به دلیل دستکاری های فیلترینگ‌روی بسته و یا تنظیمات ناهماهنگ سرور و کلاینت بوجود میاد.
خطای خیلی جدی ای هم نیست و معمولا اگر روشی برای اتصال ناموفق باشه از روش های دیگه استفاده میشه.
