### ISSUE TITLE
مشکل اپلود بزرگتر از ۱۰ مگ در حالت وب سوکت

### ISSUE THREAD

**Issue by adelhoss** [alireza0/x-ui#934]
با سلام
متاسفانه در حالت وب سوکت بروی پروتکل های vmess   vless امکان اپلود فایل بزرگتر از ۱۰ مگ وجود ندارد
خواستم بپرسم ایا کانفیگ خاصی لازم است ؟
متاسفاته در محدوده ما فقط و فقط وب سوکت جوابگو است
هیچ مشکلی نداره فقط اپلود بیش از ۱۰ مگ متاسفانه انجام نمی شود
ممنونم لطفا راهنمایی کنید با تشکر

**Comment by alireza0** [comment]
درود بر شما
این مشکل به پنل ربطی نداره و باید با xray-core مطرح بشه.
