### ISSUE TITLE
X-UI: what ports should be exposed outside Docker container?

### ISSUE THREAD

**Issue by Kenya-West** [alireza0/x-ui#935]
Can somebody provide full list of ports that I should expose in Docker?

I use [docker-compose](https://github.com/alireza0/x-ui/blob/main/docker-compose.yml) file from the project but I do not like when X-UI runs in host's network. I want to isolate it and expose only necessary ports.

What I researched so far:
- Port `54321` to expose dashboard
- Port `2096` to expose subscriptions
- Port `????` to expose connection to Telegram bot
- Port `62789` for so what called `dokodemo-door` (what is even this) I found in X-Ray advanced configs

**Comment by alireza0** [comment]
- Panel port
- Subscription port
- Inound ports you defined for non-local bind ( telegram inbound which uses loopback is unnecessary )
