### ISSUE TITLE
مشکل وصل نشده با ws به سرور

### ISSUE THREAD

**Issue by peyman508** [alireza0/x-ui#936]
با سلام و خسته نباشید خدمت آقا علیرضا گل.کانفیگ ها در حالت ws با تمامی پورت ها تست شده و هیچ کدام متصل نمیشود.فقط با tls کانکت میشود با پینگ بالا

**Comment by alireza0** [comment]
درود بر شما
پنل فقط تنظیمات رو برای xray-core آماده میکنه و اگر مشکلی در پرتکل ها دارید بهتره با xray-core مطرح کنید.
عدم اتصال بیشتر به نحوه تنظیم و فیلترینگ ربط داره
