### ISSUE TITLE
Daily/weekly/monthly/annual limit of by time and/or by traffic?

### ISSUE THREAD

**Issue by Kenya-West** [alireza0/x-ui#939]
**Is your feature request related to a problem? Please describe.**
I have clients that I do not trust so I want to set meaningful limit for traffic.
For some clients, I want to limit their time of using my proxy.

**Describe the solution you'd like**
I want to set a daily limit for traffic and/or time spend using my proxy.

**Describe alternatives you've considered**
No such kind of panels, AFAIK, have feature to set limitations for clients

**Additional context**
I want this limitation to affect:
1. Only client for specific inbound;
2. For all inbounds to specific client (by subscription ID).

**Comment by Kenya-West** [comment]
Please check me. Do I understand it correctly?

If I want to set 1 GB per day for a client, I need to set these two settings:

![image](https://github.com/alireza0/x-ui/assets/12271104/ae69b074-e6c5-4484-88dc-1134c78a3f95)

Am I right?

**Comment by alireza0** [comment]
Correct!

**Comment by Kenya-West** [comment]
Thanks! It works! Closing issue.
