### ISSUE TITLE
Telegram Bot API

### ISSUE THREAD

**Issue by MR-Amoori** [alireza0/x-ui#94]
با سلام و درود خدمت شما .
امکانش هست مستندات کامل API ربات تلگرام برای این پنل رو در اختیار کاربران بذارید که بتونن ربات های متنوع بنویسن؟

**Comment by alireza0** [comment]
درود بر شما
متاسفانه در این نرم افزار برای بات ، API نداریم.
اگر منظورتون API خود نرم افزاره، میتونید توی کدها پیدا کنید. این خاصیت نرم افزار های متن بازه.
