### ISSUE TITLE
Do not allow to set `hostname` for panel with `http://`, `https://` or any other protocol

### ISSUE THREAD

**Issue by Kenya-West** [alireza0/x-ui#940]
**Describe the bug**
I accidentally set hostname in panel settings as `https://hostname` and now panel is inaccessible, thwrowing `403 Forbidden`.

**To Reproduce**
1. Go to panel settings
2. Set hostname as `https://hostname.tld`
3. Set certificates' paths
4. See error 403 when accessing to panel

**Expected behavior**
It should not allow protocol prefixes.

**Comment by Kenya-West** [comment]
**Workaround**

You can `scp` X-UI database to your PC (I use WSL):

```sh
sudo scp -r <host user>@<host IP>:~/x-ui/db/ /mnt/c/Users/<Windows user>/Desktop/Temp/db/
```

Change `hostname` field in database, according to https://github.com/alireza0/x-ui/issues/937#issuecomment-1937822238. Save DB file and then copy it back to host (make backups before that please):

```sh
sudo scp /mnt/c/Users/<Windows user>/Desktop/Temp/db/x-ui.db <host user>@<host IP>:~/x-ui/db/x-ui.db
```

**Comment by Kenya-West** [comment]
Thanks for clarification!

Also, I understand, that:
> X-UI • An Advanced Web Panel

But I think for good UX and security reasons there should be a simple guard preventing to write protocol name to the host, like:

```ts
if (/^\w{1,}\:\/\//i.test(input?.value?.toString()) === true) input.error = true
```

or so.

I know only Angular, and this dashboard is written in Vue, so cannot help for an acceptable free time range... Sadly, I can just post an issue, like I did it there...

**Comment by alireza0** [comment]
You are right.
But there was no check from the beginning of x-ui and no reason to do that.
This panel is not a public website and the admin should know and take care of all inputs.
It is logical to not to taking care, because the power of process will be focused on functionality instead of checking input syntaxes.

Good luck :)

**Comment by Kenya-West** [comment]
Thanks! The issue can be closed now, I think.

--------

My nobody-asked-for-it opinion (6 years in bloody enterprise): if a product is promised to be distributed widely, it should be more and more decent in terms of UI/UX. Whatever the purpose it is served for: public or private dashboard, app or any GUI solution - it must satisfy basic UX/UI requirements (which depend of course).

But you have limited amount of resources, especially time. X-UI serves well and does a job, but it becomes more and more popular as more countries join blocking Internet access, and existing authoritarian regimes are strangling the remnants of freedom.

I promise, if I somehow learn Vue at acceptable level, I pull request changes for this issue.

**Comment by alireza0** [comment]
Thank you so much.
I am open to accept good codes which has less priority in my limited time.
