### ISSUE TITLE
restart xray

### ISSUE THREAD

**Issue by navid4132** [alireza0/x-ui#941]
سلام و عرض خسته نباشید
من از تانل RTT و لودبالانس ترافیک  بین چند سرور خارج استفاده میکنم ، خطاهایی که جدیداً و بعد از بروزرسانی از لاگ xui پنل میگیرم شامل موارد زیر هستش که در اکثر مواقع موجب ارور خوردن هسته xray میشه ، هر چند بعد از چند ثانیه xray بصورت اتوماتیک خودشو ریستارت میکنه ولی ممنون میشم موارد بررسی و راهنمایی کنین.
WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62789: connect: connection refused
get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: read tcp 127.0.0.1:44536->127.0.0.1:62789: read: connection reset by peer"
common/mux: unexpected EOF > common/mux: failed to read metadata > common/mux: invalid metalen 29821

**Comment by alireza0** [comment]
درود بر شما
این خطا مربوط به خوندن اطلاعات مصرف از xray-core میشه و زمانی رخ میده که به هر دلیلی xray-core شما به درخواست جواب نمیده.
عمدتا دلیل این مشکل ریستارت شدن xray-core به دلیل هنگ کردن و یا تنظیم اشتباه میتونه باشه.
سطح این لاگ همونطوری که میبینید Warning هست و مسئله خاصی نیست. مهم اینه که پیدا کنید چرا هسته xray ریستارت میشه

**Comment by zarvan9** [comment]
@navid4132 
منم به این مشکل خوردم طوری که دو، سه دقیقه همه کاربر ها قطع میشدن بعد xray ریبوت میشد ،راهی که من پیدا کردم اینه که مصرف رم مانیتورینگ بشه و اگه بالای 60 درصد رفت سرویس xray رو ریبوت کنه تا کاربر ها قطع نشن یا به دیلی نخورن
اگه کمکت میکنه این اسکریپت رو با nohup اجرا کن 
[ram.zip](https://github.com/alireza0/x-ui/files/14815300/ram.zip)

**Comment by navid4132** [comment]
@zarvan9 
در این خصوص با افزایش منابع سخت افزاری مشکل حل شد - که دقیقا طبق نظر شما درست بود.
با توجه به تعداد زیاد یوزر ها و نوع تانلینگ ، با ارتقا مموری مشکل مرتفع گردید.
