### ISSUE TITLE
استاپ شدن

### ISSUE THREAD

**Issue by ali90500** [alireza0/x-ui#944]
سلام من ریورس پنل به پنل زدم
سرور ایران روی دیتاسنتر لایزر هستش
بعد از چند ساعت پنل استاپ میشه و باید ssh بزنم و گزینه ریستارت رو بزنم تا مجدد استارت بشه بعد چند دقیقه دوباره قطع میشه و ریستارت کخ میکنم یه 6 ساعتی فعاله دوباره دوبار پشت هم استاپ میشه
لاگ هم اینه
![Screenshot_20240212_193647_com server auditor ssh client](https://github.com/alireza0/x-ui/assets/127780080/d5e6930b-5d63-49e1-9045-b46a7060c843)

**Comment by alireza0** [comment]
درود بر شما
این مشکل ممکنه به دلیل ارسال لاگ های غیر استاندارد از طرف xray-core ممکنه رخ بده. اگر لاگ رو لازم ندارید توی تنظیمات پیشرفتی ایکس‌ری اون رو ببندید:
```json
  "log": {
    "loglevel": "none"
  },
```
