### ISSUE TITLE
اضافه شدن فرگمنت به قسمت اینباند

### ISSUE THREAD

**Issue by rezakhosh78** [alireza0/x-ui#945]
سلام و خسته نباشید خدمت شما. لطفا اگر مقدور هست فرگمنت رو به قسمت اینباند اضافه کنید که با فعال کردنش همه کاربرا بتونن ازش استفاده کنن.نشکر

**Comment by alireza0** [comment]
درود بر شما
فرگمنت فقط درoutbound و پروتکل freedom قابل استفاده است.
چیزی که شما دنبالش هستین از این طریق قابل اعمال نیست.
