### ISSUE TITLE
هک شدن سرور توسط یکی از یوزرها

### ISSUE THREAD

**Issue by morteza229866** [alireza0/x-ui#948]
سلام وقت به خیر من یه سرور دارم که روش یوزر دارم به مشتری میدم یکی از یوزرا با ای پی که سرور روش هست و به فیلتر وصل هست کار هک انجام میده و هر چند روز از سایت هیتزنر برام پیام میاد که از سرور شما حمله دریافت شده 80 یوزر هستن نمیدونم کدومشون داره این کار رو میکنه کسی میتونه بهم بگه چطور میتونم ببینم کدوم یوزر داره اینو انجام میده

**Comment by MJamshidnejad** [comment]
@morteza229866 
What is the exact warning of Hetzner?

**Comment by morteza229866** [comment]
> @morteza229866 What is the exact warning of Hetzner?

We have indications that there was an attack from your server.
Please take all necessary measures to avoid this in the future and to solve the issue.

We also request that you send a short response to us. This response should contain information about how this could have happened and what you intend to do about it.
In the event that the following steps are not completed successfully, your server can be blocked at any time
#      Netscan detected from host 91.117.152.222

**Comment by MJamshidnejad** [comment]
> > @morteza229866 What is the exact warning of Hetzner?
> 
> We have indications that there was an attack from your server. Please take all necessary measures to avoid this in the future and to solve the issue.
> 
> We also request that you send a short response to us. This response should contain information about how this could have happened and what you intend to do about it. In the event that the following steps are not completed successfully, your server can be blocked at any time
> 
> # Netscan detected from host 91.117.152.222

I recommend using the access log to find the person. Active access log on your panel, then filter by user names to find any evidence of that. Furthermore, you can contact support via email to obtain more information about the timing. That would be helpful.
