### ISSUE TITLE
کار نکردن iplimit در پنل 3xui

### ISSUE THREAD

**Issue by mohamadn69** [alireza0/x-ui#949]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام 
آخرین ورژن 3xui را روی centos8 نصب کردم و با outbound به سرور خارج وصل کردم و ip لیمیت را هم داخل کنسول نصب کردم و کانکشن را روی 1 لیمیت کردم . ولی همزمان دوتا گوشی با ip مختلف وصلن و تست که میزنم ping دارن و داخل کانکشن دوتا ip مختلفت نشون میده . در ضمت لاگ ip لیمیت empty میزنه و لاگ کنسول app/dispatcher: non existing outTag: blocked
 
 در ضمن فایروال هم غیر فعاله.  فایروال ک فعال بود یوزرها کلا وصل نمیشدن و وب کنسول باز نمیشد  مجبور شدم که firewalld را غیر فعالش کنم. علتش همینه؟
اگر علتش غیر فعال بودن فایرواله راه حلش چیه؟
 کانفیگم اینه
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    },
    {
      "listen": "127.0.0.43",
      "port": 443,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "149.154.167.220",
        "port": 443,
        "network": "tcp"
      },
      "tag": "telegram"
    }
  ],
  "log": {
    "access": "./access.log",
	"error": "./error.log",
    "dnsLog": false,
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "******prx.ir",
            "port": ******,
            "users": [
              {
                "id": "33abc9c8***********-9f60",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "http",
            "request": {
              "version": "1.1",
              "method": "GET",
              "path": [
                "/"
              ],
              "headers": {
                "Host": [
                  ""
                ],
                "User-Agent": [
                  "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                  "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
                ],
                "Accept-Encoding": [
                  "gzip, deflate"
                ],
                "Connection": [
                  "keep-alive"
                ],
                "Pragma": "no-cache"
              }
            }
          }
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true,
      "statsOutboundDownlink": true,
      "statsOutboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "regexp:.*\\.ir$",
          "regexp:.*\\.xn--mgba3a4f16a$",
          "ext:geosite_IR.dat:ir"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "ext:geoip_IR.dat:ir"
        ]
      }
    ]
  },
  "stats": {}
}
### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console

2024/02/12 21:38:09 WARNING - XRAY: [568255808] app/dispatcher: non existing outTag: blocked
2024/02/12 21:38:07 WARNING - XRAY: [1779165151] app/dispatcher: non existing outTag: blocked
2024/02/12 21:38:06 WARNING - XRAY: core: Xray 1.8.7 started
2024/02/12 21:38:05 INFO - X-UI: Sub server run https on[::]:2096
2024/02/12 21:38:05 INFO - X-UI: Starting Telegram receiver ...
2024/02/12 21:38:05 INFO - X-UI: Tg notify enabled,run at @daily
2024/02/12 21:38:05 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/02/12 21:38:05 INFO - X-UI: Remove Inbound User RNIj.love@xray.com due the expire or traffic limit
2024/02/12 21:38:05 INFO - X-UI: web server run https on[::]:2053
2024/02/12 21:38:05 WARNING - X-UI: stop server err:multierr: close tcp [::]:2096: use of closed network connection |
2024/02/12 21:38:05 WARNING - X-UI: stop server err:multierr: close tcp [::]:2053: use of closed network connection |
2024/02/12 21:38:05 INFO - X-UI: Stop Telegram receiver ...
2024/02/12 21:37:56 WARNING - XRAY: [2987919200] app/dispatcher: non existing outTag: blocked
2024/02/12 21:37:53 WARNING - XRAY: [1956002626] app/dispatcher: non existing outTag: blocked
2024/02/12 21:37:50 WARNING - XRAY: [3191740758] app/dispatcher: non existing outTag: blocked
2024/02/12 21:37:47 WARNING - XRAY: [3023233665] app/dispatcher: non existing outTag: blocked
2024/02/12 21:37:45 WARNING - XRAY: [3107566920] app/dispatcher: non existing outTag: blocked
2024/02/12 21:37:44 WARNING - XRAY: [3003692259] app/dispatcher: non existing outTag: blocked
```

</details>

**Comment by alireza0** [comment]
درود بر شما
دوست عزیز ایشو رو جای اشتباهی درست کردین.
