### ISSUE TITLE
Telegram built in socks

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#951]
Hi @alireza0 .
I saw a commit in 3x-ui project which added socks5 proxy for x-ui telegram bot, which makes it easier to config it in domestic servers.
could you please have a look on it in your free time and add it if you see it a good feature.?
Good Luck.

**Comment by alireza0** [comment]
Hello @X-Oracle ,
In 3x-ui, telegram package is `telego` which is not as same as what this panel has.
Telegram features in mentioned panel is more than what we provide here.
Also, advanced users, can find a way to do that. But users always have problems with all the solutions. It is what we can see in issues of 3x-ui!

To be honest, it has no place in my priority list. And I prefer to run a solution without user's input. Sth like a switch.
I will take care if any solution comes to my mind.
