### ISSUE TITLE
روش تانل معکوس (reverse tunnel) با استفاده از tls کار نمی کند

### ISSUE THREAD

**Issue by Cyrus-of-Persia** [alireza0/x-ui#953]
طبق آموزش اخیر یوتیوب ایمان آقاپور، روش تانل معکوس رو انجام دادم فقط با این تفاوت که در رور داخل، inbound پنل و یوزر رو هر از دامنه با و بدون cdn روشن کلودفلر برای فعالسازی tls استفاده کردم ولی نتونستم متصل بشم. روی هیچ نتی کار نکرد. نوع protocol رو روی vless و trojan گذاشتم و transmission رو هم روی ws و هم روی tcp گذاشتم ولی هیچ کدوم کار نکردن.

**Comment by alireza0** [comment]
من چطور میتونم کمک کنم ؟

**Comment by wulfric93** [comment]
اگر دیتاسنتر شاهین هست از میزبان کلاد این روش جوابگو نیست
