### ISSUE TITLE
استپ استارت شدن مداوم

### ISSUE THREAD

**Issue by hasan4643** [alireza0/x-ui#955]
سلام خسته نباشین پنلم یهو قاطی کرده هی تند تند استاپ استارت میشه و این ارور رو هم میده
![photo_2024-02-15_18-57-38](https://github.com/alireza0/x-ui/assets/152972276/1061496d-712a-49db-9ec5-19f0ef4c6154)

**Comment by alireza0** [comment]
درود بر شما
شما از پنل دیگه ای استفاده میکنید، لطفا همونجا ایشو باز کنید.
مشکل شما پکیج و تنظیمات تلگرام هست.
من اطلاع زیادی از روش کار این پکیج تلگرام ندارم
