### ISSUE TITLE
خطای در بات تلگرام روی سرور ایران

### ISSUE THREAD

**Issue by hayousef68** [alireza0/x-ui#957]
سلام اقا علیرضا توروخدا یه راهنمایی کن همه کارهایی که گفتی انجام دادم برای راه اندازی ربات روی سرور ایران ولی این خطا رو میده

curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.telegram.org:443

**Comment by alireza0** [comment]
درود بر شما
لطفا برای سوالاتتون از تگ مناسب استفاده کنید.

بدون اطلاعات کافی از نحوه تنظیم سرور، من و دوستان فعال در این ریو نمیتونیم کمکی بکنیم.

**Comment by hayousef68** [comment]
> Reference in new issue
دقیقا طبق گفته شما یه دکو دمودور ساختم داخل پنل با این مشخصات و دستوری که گفته بودین رو وارد سرور کردم ولی خطای ssl میده
کانفیگ با این مشخصات ساختم
Protocol: dokodemo-door
listen IP: 127.0.0.43
port: 443

Target Address: 149.154.167.220
Destination Port: 443
Network: tcp

اینم داخل سرور زدم
echo "[127.0.0.43](https://127.0.0.43/) [api.telegram.org](https://api.telegram.org/)" >> /etc/hosts

موقع وصل شدن این خطا رو میده 

curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.telegram.org:443

**Comment by hayousef68** [comment]
> درود بر شما لطفا برای سوالاتتون از تگ مناسب استفاده کنید.
> 
> بدون اطلاعات کافی از نحوه تنظیم سرور، من و دوستان فعال در این ریو نمیتونیم کمکی بکنیم.

دقیقا طبق گفته شما یه دکو دمودور ساختم داخل پنل با این مشخصات و دستوری که گفته بودین رو وارد سرور کردم ولی خطای ssl میده
کانفیگ با این مشخصات ساختم
Protocol: dokodemo-door
listen IP: 127.0.0.43
port: 443

Target Address: 149.154.167.220
Destination Port: 443
Network: tcp

اینم داخل سرور زدم
echo "[127.0.0.43](https://127.0.0.43/) [api.telegram.org](https://api.telegram.org/)" >> /etc/hosts

موقع وصل شدن این خطا رو میده

curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.telegram.org:443

**Comment by alireza0** [comment]
تنها مشکلی که میبینم فعال بودن Follow Redirect توی تنظیمات اینباند هست.
بعد از اون باید مطمئن باشید که خروجی پنل برای همه اینباند ها و مخصوصا همین اینباند فعال هست.
یعنی ترافیک دوکودمو دور باید از تانل خارج بشه.

**Comment by hayousef68** [comment]
> اگر سرورتون ایرانه، باید یه تانلی داشته باشید به سمت یه سرور خارج. و ترافیک این دوکودمودور هم باید به اون تانل بره. آیا این رو تنظیم کردین؟

تانل پنل به پنل زدم .پنل اصلیم رو سرور ایران هست .چطوری باید تنظیم کنم این دکو دمو دور رو؟؟؟

**Comment by alireza0** [comment]
همونطوری که گفتم باید چک کنید که قوانین مسیر یابی شما طوری هست که این اینباند بتنه ازش استفاده کنه

**Comment by hayousef68** [comment]
ممنون از راهنماییهاتون .عالی هستین .حل شد برا من

> همونطوری که گفتم باید چک کنید که قوانین مسیر یابی شما طوری هست که این اینباند بتنه ازش استفاده کنه
