### ISSUE TITLE
error on creating warp outbound

### ISSUE THREAD

**Issue by TheyCallMeSecond** [alireza0/x-ui#958]
**Describe the bug**
error on creating warp outbound

**Screenshots**

![240216_15h27m51s_screenshot](https://github.com/alireza0/x-ui/assets/73380906/bf705d5f-df9f-4bd6-8ded-bf87370ae7e9)
![240216_15h29m10s_screenshot](https://github.com/alireza0/x-ui/assets/73380906/c499186b-4d90-41f6-9fff-d3242878fff7)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser Firefox
 - Version 122
 - Panel Version 1.7.0

**Comment by alireza0** [comment]
ArchLinux is not recommended for using this panel. [Link](https://github.com/alireza0/x-ui#recommended-os)
I don't know if this issue is related to the OS or sth else.
But please test it with other OSes and inform me if still you have problems.

**Comment by TheyCallMeSecond** [comment]
i dont think...i test it on ubuntu 22.04 too...its the same

**Comment by alireza0** [comment]
Please run this command on your server and send me the result:
```bash
curl -I -X POST https://api.cloudflareclient.com/v0a2158/reg
```

**Comment by TheyCallMeSecond** [comment]
![image](https://github.com/alireza0/x-ui/assets/73380906/f3d81c08-ab73-4066-aff8-c7cacdd4dc02)

**Comment by TheyCallMeSecond** [comment]
![image](https://github.com/alireza0/x-ui/assets/73380906/705d4386-428d-44ce-8d55-70477eac17ad)

**Comment by alireza0** [comment]
That means, you have a problem to get data from cloudflare.
Check this result with command:

```bash
curl -s -X POST https://api.cloudflareclient.com/v0a2158/reg
```

**Comment by TheyCallMeSecond** [comment]
error code: 1015

**Comment by alireza0** [comment]
The answer should be a `json` to be able to proceed with `x-ui`.
You should find out what is the problem with your server hosting.

**Comment by TheyCallMeSecond** [comment]
it is hosted on DigitalOcean...what do you think?

**Comment by alireza0** [comment]
I don't know if there is any prohibition of usage between DO and CF :/
But normal answer should be a json reply.
Please check your cload firewall first.

**Comment by TheyCallMeSecond** [comment]
ok tnx
