### ISSUE TITLE
More RAM consumption(Mehr RAM-Verbrauch) in Version 1.7.1

### ISSUE THREAD

**Issue by navid4132** [alireza0/x-ui#960]
سلام و خسته نباشید خدمت شما مهندس عزیز
من آپدیت 1.7.1 را انجام داد. چیزی که توجه منو در ابتدا جلب کرد مصرف بیشتر مموری به نسبت ورژن های قبل بود.
صرفاً جهت اطلاع و کسب راهنمایی میخواستم بدونم که این حدود 10 درصد افزایش مصرف مموری در ورژن جدید بابت وب پنل بوده یا مربوط به لاگ های xui و xray-core می باشد؟
پیشاپیش بابت زمان گرانبهایی که در این مسیر صرف میکنین و نسبت به بروزرسانی های بجا و به موقعی که انجام میدین کمال تشکر و امتنان را دارم.

**Comment by alireza0** [comment]
درود بر شما
متد لاگ ها عوض شده و اگر لاگ xray رو استفاده نمیکنید، پیشنهاد میکنم روی none تنظیم کنید.
مصرف رم بیشتر به اندازه تنظیمات شما بستگی داره. چون xray-core به ازای هر ورودی برای خودش استفاده از حافظه داره.
در کل اگر سرور خیلی شلوغی ندارید، و مثلا ۵۰ مگ رم استفاده شده، ۵۵ مگ شدنش خیلی نمیتونه چشمگیر باشه و دلایل زیادی میتونه داشته باشه.

در کل هر نسخه که امکانات جدیدی اضافه میشه، حتما مقدار بیشتری حافظه رو باید مصرف کنه. ولی عموما به ده درصد نمیرسه.
سیستم garbage  در golang به صورت خودکار بهینه عمل میکنه، ولی ممکنه در یک درخواست لحظه ای مصرف رم بیشتر بشه.
اگر این مقدار بدون هرگونه کاربر و استفاده بیشتر بشه، اون موقع باید بهینه سازی انجام بدیم
