### ISSUE TITLE
ربات پنل

### ISSUE THREAD

**Issue by hasan4643** [alireza0/x-ui#962]
سلام خوبین من داخل پنل به یه باگی خوردم که بکاپ به ربات تلگرام نمیفرسته و داخل لاگ خطا دارم

<img width="531" alt="image" src="https://github.com/alireza0/x-ui/assets/152972276/f9e7bd6c-a2fc-4a18-b58f-ed35ea7fa2d0">

**Comment by alireza0** [comment]
درود بر شما
به نظر میاد هم ارتباط سرور با تلگرام مشکل داره
