### ISSUE TITLE
محدودیت دسترسی

### ISSUE THREAD

**Issue by AliHemmati79** [alireza0/x-ui#964]
سلام خسته نباشید
قبلا که مثلا از ایپی تیبل استفاده میکردیم و از داخل پنل x-ui دسترسی به دامنه و ایپی های ایران مسدود میکردیم تا کاربرا نتونن به سایت های داخلی دسترسی داشته باشن چون باعث فیلتر شدن سرور خارج میشد.
الان با روش ریورس که درخواست از سمت سرور خارج ارسال میشه و رو سرور فیلتر شده هم جواب میده ، اگر محدودیت دسترسی به سایت های داخلی آزاد کنیم و کاربرا بتونن با فیلتر وارد بشن امکانش هست سرور ایرانی مشکل براش پیش بیاد یا مشکلی در این زمینه بوجود نمیاد؟
اگر از این موضوع خبر دارین ممنون میشم اطلاع بدین،باتشکر.

**Comment by alireza0** [comment]
درود بر شما
مشکل فیزیکی به وجود نمیاد
ولی ممکنه باعث ایجاد حساسیت بشه.
من در این مورد اطلاعات زیادی ندارم، ولی حرف و حدیث هایی در موردش هست که نمیتونم صحتش رو تایید کنم.

**Comment by AliHemmati79** [comment]
خیلی ممنون
