### ISSUE TITLE
Subscription for multiple nodes and usage for API routes

### ISSUE THREAD

**Issue by MMMMMoris** [alireza0/x-ui#965]
**Is your feature request related to a problem? Please describe.**

Firstly, I usually create multiple nodes of different protocol, while the subscription link contains only the very one node, which confuses me about how to fetch my nodes with just a single subscription link.
Secondly, I am new to x-ui, and not a professional developer, I don't know how to use API routes. So far, what I can tell from reading redme.md is that the API routes are for operating x-ui automatically with program. 

**Describe the solution you'd like**

For the first feature request, I would like to be able to fetch my nodes with just a single subscription link.
For the second one, well, I would  like to ask whether there is an example or something else for guiding? Only the usage of API is some sort of plain, less friendly for noob like me.

**Describe alternatives you've considered**

The alternative I have been considering is to combine both, generate nodes automatically and gather their subscription links, which sounds not so efficient nor realizable.

**Comment by MMMMMoris** [comment]
The sample can be written in python or javascript, I can handle some part of these two languages.

**Comment by MMMMMoris** [comment]
Almost forgotten, there is one more question. Is x-ui.db portable? The one generated automatically after I finished configuration of nodes and other x-ui settings manually, can I copy it to initialize a newly installed x-ui for another VPS ? I did try so once, but I seems to be not workable. This question is to ask for confirmation.

**Comment by alireza0** [comment]
In fact, this pannel is designed to work stand-alone.
In order to connect more panels, you can use API as well.

Regarding samples, a sample project is pinned in issues page.

Regarding database, it is portable. But if your configuration is binded to one server ( for example using IP bind for panel or inbounds and using local certificate file address ), it will cause error in other servers.

**Comment by MMMMMoris** [comment]
Thanks for your reply. But I cannot see your meaning of "work stand-alone", does it mean that one subscription link with multiple nodes is not going to be supported?

**Comment by MMMMMoris** [comment]
What about the configuration part of WARP outbound? Is that portable as well? Or is it possible to generate Wireguard outbound of Cloudflare WARP  using API route?

**Comment by alireza0** [comment]
> Thanks for your reply. But I cannot see your meaning of "work stand-alone", does it mean that one subscription link with multiple nodes is not going to be supported?

Yes! There is no plan to suport external node in X-UI.



> What about the configuration part of WARP outbound? Is that portable as well? Or is it possible to generate Wireguard outbound of Cloudflare WARP using API route?

I didn't get the benefit of this request! You can ask for creating new warp configuration in each server.
If you want to use your Warp+ license, you can change the license in each server.
The limitation number is defined in cloudflare when you buying your license.
