### ISSUE TITLE
پریدن پنل روی ریورس تانل(برای من)

### ISSUE THREAD

**Issue by kamkamini** [alireza0/x-ui#966]
سلام علیرضا جان اول دمت گرم واسه این تانل ریورس خفن ت دوم این که من یه مشکلی دارم

مشکل من اینه که پنل کلا از روی سرور میپره و قطع میشه باید برم دوباره پنل رو بزنم با پورت و رمز اینا تا دوباره بالا بیاد
یعنی xu-i من میپره روی پنل شما ولی روی سنایی اوک بوده تا الان
ولی من همیشه روی پنل شما سما بودم و میخوام بدونم این مشکل چرا پیش میاد واسه من؟

**Comment by alireza0** [comment]
درود بر شما
من درست متوجه نشدم، یعنی تنظیم تانل معکوس، سرور شما رو پاک میکنه ؟

**Comment by kamkamini** [comment]
اطلاعات اینا داخلش هست خب
فقط پنل بالا نمیاد
باید برم دوباره پنل شما رو داخل سرور بزنم  تا بالا بیاد

**Comment by alireza0** [comment]
بدون اطلاعات لازم من و دوستان فعال در این رپو نمیتونیم به شما کمک کنیم.
لطفا لاگ های سرور و نحوه تنظیمات سرور رو اینجا ارسال کنید.

**Comment by kamkamini** [comment]
چیز خاصی روی سرورم نیست خب
خارجم هتزنر ایران اروان یه پورت ۲۰۸۳ یه پورت اتصال دو تا سرور ۴۴۳ همین و بقیه هم دیگه همون تنظیمات ریورس که میزنیم

فعلا من آپدیت جدید رو الان زدم اگر مشکلی بود بازم همین جا اطلاع میدم 
خیلی ممنونم ❤️

**Comment by alireza0** [comment]
لطفا در صورت ادامه مشکل یک ایشو جدید باز کنید.
سپاسگزارم
