### ISSUE TITLE
Wireguard multiaccount error

### ISSUE THREAD

**Issue by polons123** [alireza0/x-ui#968]
Good afternoon. Thank you so much for developing such a good project. In version 1.7.1, you added auto multi-peer and qrcode for wireguard, but when creating multiple peers, only the latter works. A connection is established with the steel ones, but there is no traffic.
<img width="912" alt="2" src="https://github.com/alireza0/x-ui/assets/116712893/892a8461-67bf-49d9-a4aa-6cd00513e6cd">
<img width="912" alt="1" src="https://github.com/alireza0/x-ui/assets/116712893/964c95ea-47b3-4730-96cb-422766029922">
And a wish - can you add sniffing to wireguard inbound?

**Comment by alireza0** [comment]
Regarding Sniffing, I don't know why the creator of x-ui, define it for some special protocols.
Please raise a new Enhancement issue, then I will test and discuss there.

Regarding peers, please don't set same subnet!
If they are only for one client, it is recommended to define peers with separate /32 IPs.
