### ISSUE TITLE
اضافه شدن قابلیت محدود کردن ای پی 

### ISSUE THREAD

**Issue by ARYA-JAVAN** [alireza0/x-ui#97]
ممنونم از زحمات شما و این پنلی که درست کردید
ممکنه که قابلیت محدودیت ای پی رو اضافه کنید چون واقعاً خیلی ضروریه 
چون وقتی کانفیگ به فامیل میدیم بعضیا کانفیگو به بقیه میدن و هم سرعت میاد پایین و هم حجم زیادی مصرف میکنند

شنبدم تو پنل اقای حسین اسدی کار میکنه این قابلیت

**Comment by alireza0** [comment]
این پنل از همین رپوزیتوری که شما اعلام کردین فورک شده. محدودیت IP رو عمدا توی این پنل حذف کردم، اگر لازم دارید میتونید از پنل [3x-ui](https://github.com/MHSanaei/3x-ui) استفاده کنید.

**Comment by ARYA-JAVAN** [comment]
من قبل پنل شما از همین پنل استفاده میکردم.این قابلیت توی پنل سنایی هست ولی کار نمیکنه و هیچ تاثیری در محدودیت ایپی نداره.
به این خاطر خواستم که نسخه سالم این قابلیت رو به پنل خودتون اضافه کنید.
