### ISSUE TITLE
WARP crash

### ISSUE THREAD

**Issue by amirhakimnejad** [alireza0/x-ui#972]
Hello and thank you for your amazing contributions to the free internet.
Sometimes, the VPN stops working for the websites included in the WARP config.

Meanwhile, you can see that `ERROR - X-UI: peer(bmXO…fgyo) ` is throwing frequently, and you must restart XRAY a few times until the error stops.

<img width="617" alt="image" src="https://github.com/alireza0/x-ui/assets/30291162/103a4c1d-14a5-45ae-9c85-0547c6c55fd6">

It happens in both 1.7.0 and 1.7.1 versions.

**Comment by alireza0** [comment]
It seems in new log_write, XRAY logs written by X-UI label. I will fix this bug.

Regarding this XRAY log, it shows that your peer is not configured correctly.
Please check your configuration and following the wireguard inbound rules.

**Comment by amirhakimnejad** [comment]
I am using the default settings
<img width="523" alt="image" src="https://github.com/alireza0/x-ui/assets/30291162/f981e4b1-d6ab-46ec-8e9b-4ecc2e8b497e">
I can only assume that there may be too many users tunneling through warp.

**Comment by alireza0** [comment]
If it is about warp tunnel, please first check if you have access to cloudflare warp in your server.
GFW may drop your packets.
If it is not, raise an issue for xray-core repo
