### ISSUE TITLE
path -درخواست راهنمایی

### ISSUE THREAD

**Issue by ramram2020** [alireza0/x-ui#973]
درود و خسته نباشید علیرضای عزیز.
بنده چند پنل از چند سرور مختلف که پورت و کانفیگ یکسان داشتن به صورتی دستی یوزهاشو منتقل کردم روی یک پنل و همه یوزر ها بدون مشکل وصل شدن.  الان سه تا سوال دارم از خدمتتون.
1  آیا راهی جز انتقال به صورت دستی وجود داره که راحت بشه کانفیگ های دو تا پنل را از دو سرور با پورت و کانفیگ مشترک باهم یکی کرد ؟
2.  آیا در قسمت  path/ راهی دارد که چیزی بزنم که هر مقداری از سمت کاربر قبول بشه ؟ چون میخوام دو تا پنل دیگه را با پورت و کانفیگ یکسان  با هم یکی کنم ولی بخاطر پر بودن مقدار  path/ در یکی از آن ها این امکان برایم وجود ندارد. و اینجوری مجبورم بعد یکی شدن پنل ها به تعدادی از کاربرها بگم قسمت path/ را خالی کنند. 
3. آیا راهی دارد بتوانم  یک سرور ایران را به 5 سرور دیگر که کانفیگ همشون  یکی هست (مثلا 443) تانل کنم ؟ 
ببخشید طولانی شد. واقعا ممنونم

**Comment by ramram2020** [comment]
سوال دوم و سوم برام خیلی مهمه. 
در مورد سوال سومم ساده تر توضیح بدم. من الان میخوام یک سرور ایرانمو تانل کنم به 5 تا سرور خارجم. ولی متاسفانه همه ی سرور های خارجم پورت های شبیه هم دارن.یعنی همشون تک پورت روی مثلا 8080 هستن. !! و اینجوری متاسفانه نمیشه به همشون از یک سرور ایران تانل دکو یا گاست زد .. و اگه بخوام یکی کنم پنل ها را هم مشکلی که دارم روی یکیشون کانفیگش path داره.(سوال دومم)
واقعا ببخشید . ممنون

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم
۱. در حال حاضر این امکان در این پنل نیست.
۲. در بعضی از مدلهای انتقال مثل WebSocket این امکان وجود داره که ادامه path رو میتونید هرچی بخواید بذارید
Main : /path1
Other: /path1/path2
۳. از تانل‌های v2ray و معکوس استفاده کنید.

**Comment by ramram2020** [comment]
مرسی علیرضا جان.
 ففط سوال دوم را درست متوجه نشدم. نمیدونم منظورمو کامل متوجه شدید یا خیر.
هدفم انتقال کانفیگ های هیدفای هست به پنل شما به شکل دستی بدون قظعی و تغییر از سمت کاربر (با پورت و کانفیگ یک شکل که البته قبلا هم انجام دادم)
 اما این بار گیر کردم. همه چیز کانفیگ هام مشترکه غیر از path . یعنی کانفیگم روی هیدفای path داره اما روی پنل شما خالیه و نمیتونم بدون قطعی کاربر کانفیگ های هیدفای را انتقال بدم روی همون پورت مشترک در پنل شما.
گفتم شاید راهی باشه که بشه در قسمت  path مقداری را وارد کنم که path نادیده گرفته بشه از سمت کاربر تا بتونم هر دو پنلو روی یک پورت بدون قطعی کاربر یکی کنم باهم و بیارم روی پنل شما .

**Comment by alireza0** [comment]
اگر روی یک سرور دارین که نمیشه دو نرم افزار از یک پورت استفاده کنن.
ولی این کار رو با نرم افزارهای جانبی مثل nginx و haproxy به راحتی میتونید انجام بدین.

**Comment by ramram2020** [comment]
مرسی علیرضا جان. ولی دو تا برنامه ندارم. عرض کردم میخوام hiddfy را پاک کنم و بعد از اینکه اکانت های hiddify را میارم روی پنل شما و به صورت دستی وارد میکنم چون اکانتهای hiddfy دارای path متفاوتی هستن نمیتونم بزارمشون ادامه اکانت هایی که روی پنل شما دارم. و ترجیحا این بود پورت جدید و اینباند جدید باز نکنم .چون همه چیه کانفیگ ها غیر path مشترک بودن.
ولی گویا نمیشه دو تا path روی یک پورت تعریف کرد یا مثلا کاری کرد که از سمت کاربر گیر نده به مقدار path  و با هر مقداری وصل بشه.
بازم ممنونم . یکم نوشتاری اذیتت کردم سخت بود توضیحش.ولی ۹۰ درصد جوابمو گرفتم.مرسی ازتون

**Comment by alireza0** [comment]
هیدیفای از haproxy استفاده میکنه 😅
