### ISSUE TITLE
ارور در نصب

### ISSUE THREAD

**Issue by zarvan9** [alireza0/x-ui#974]
سلام هنگام نصب با این ارور مواجه میشم

The OS release is: ubuntu
arch: amd64
/dev/fd/63: line 188: syntax error near unexpected token `}'

/dev/fd/63: line 188: `}'

*من هنگام نصب ثنایی اروری ندارم

**Comment by omid650** [comment]
دقیقا همین ارور برای من هم میاد

**Comment by Alikhodayari4** [comment]
من هم همین ارور رو دریافت میکنم

**Comment by ramtiny** [comment]
راه حل چیه

**Comment by X-Oracle** [comment]
Fixed https://github.com/alireza0/x-ui/commit/6b66c250b5e0994db5a129326062461269bed1ff
