### ISSUE TITLE
غیر فعال پنل ایکس یو آی 

### ISSUE THREAD

**Issue by GithubUN89** [alireza0/x-ui#976]
سلام،
من دو سرور رو تانل کردم ،
هر از چند گاهی ، سرور ایران من ، غیر فعال میشه و باید از داخل ssh اون رو restart کرد تا دوباره ران بشه
عکس لاگ رو ضمیمه کردم

مشکل چیه و چطور باید حل کرد ؟
![IMG_20240219_083645](https://github.com/alireza0/x-ui/assets/23716941/c25be42d-18ab-4f6a-a874-848a8029f7d8)

**Comment by alireza0** [comment]
درود بر شما
آیا پنل رو روی کاربری غیر از root نصب کردین ؟
مشخصات سیستمتون رو هم اعلام نکردین

**Comment by GithubUN89** [comment]
> درود بر شما آیا پنل رو روی کاربری غیر از root نصب کردین ؟ مشخصات سیستمتون رو هم اعلام نکردین


روی غیر روت نصب نمیشد اصلا 

اوبونتو هست 
تانل کردم ، پنل به پنل 
سرور ایران از آروان ، بامداد ، یک گیگ

**Comment by alireza0** [comment]
به نظر میاد که نرم افزار یه مشکلی با مجوز های سیستم داره. این لاگ نشون میده این مشکل باعث کرش کردن بخشی از کد میشه که سعی میکنه توی سطح سیستم عامل یک دستور رو اجرا کنه.
به تانل ربطی نداره و مشکل سیستم شماست.

**Comment by GithubUN89** [comment]
> به نظر میاد که نرم افزار یه مشکلی با مجوز های سیستم داره. این لاگ نشون میده این مشکل باعث کرش کردن بخشی از کد میشه که سعی میکنه توی سطح سیستم عامل یک دستور رو اجرا کنه. به تانل ربطی نداره و مشکل سیستم شماست.


منظورتون از نرم افزار چیه مهندس ؟
مشکل از سیستم هست یعنی  سیستم عامل من که اوبونتو 20 هست فکر کنم ،  مشکل داره ؟

**Comment by alireza0** [comment]
منظورم از نرم افزار، پنل بود.
مشکل رو باید با یک ادمین لینوکس مورد اطمینان خودتون بررسی کنید.
کارق از دست من تا اینجا بر نمیاد
