### ISSUE TITLE
خطا در نصب و به روز رسانی

### ISSUE THREAD

**Issue by peyman508** [alireza0/x-ui#977]
با سلام.هنگام نصب با این خطا رو به رو شدم
The OS release is: ubuntu
arch: amd64
/dev/fd/63: line 188: syntax error near unexpected token `}'

/dev/fd/63: line 188: `}'

**Comment by Alexander-McQuen** [comment]
با سلام.هنگام نصب با این خطا رو به رو شدم
The OS release is: ubuntu
arch: amd64
/dev/fd/63: line 188: syntax error near unexpected token `}'

/dev/fd/63: line 188: `}'

دقیقا همین مشکل را منم دارم.

**Comment by matinalma** [comment]
برای منم ارور داده 
The OS release is: ubuntu
arch: amd64
/dev/fd/63: line 188: syntax error near unexpected token `}'
/dev/fd/63: line 188: `}'
root@srv08799851:~#

**Comment by r0zbeh** [comment]
بله مشکل در اسکریپت نصب است

**Comment by Alikhodayari4** [comment]
درست شده الان؟

**Comment by alireza0** [comment]
دوستان مشکل از یکی از PR ها بود که خود ایشون درستش کردن
الان مشل برطرف شده
