### ISSUE TITLE
استفاده از وارپ در ریورس تانل

### ISSUE THREAD

**Issue by h4z4rd95** [alireza0/x-ui#979]
سلام وقتتون بخیر
میخواستم بدونم بنده که از ریورس تانل دارم استفاده میکنم، چطور باید وارپ رو تنظیم کنم ( روی کدوم سرور باشه داخل یا خارج ) و این جایگاهش کجای رول های اینباند یا اوت باند پنلم باید باشه ؟
بنده وارپ رو روی سرور داخل نصب کردم، روی سرور خارج هم نصب کردم، مشکل اصلی بنده این هست که مدیا های واتساپ حالا چه برای ارسال استیکر/عکس چه برای دانلود و چه برای ارسال استتوس، کار نمیکنه و فقط میشه متن ارسال کرد، میخواستم با وارپ و رد کردن رول صحیح حلش کنم.

**Comment by ramtiny** [comment]
ممنون میشم این مشکلات رو پاسخ بدید 
سوالات ما هم هست

**Comment by alireza0** [comment]
درود بر شما
بهتره وارپ رو در سرور خارج استفاده کنید.
ارتباطات ایران به سمت کلادفلر همیشه مشکل داشته و از طرف دیگه، پروتکل وایرگارد هم فیلتر شده.

درنسخه آخر گزینه فعال کردن وارپ برای متا رو گذاشتم که میتونید فعال کنید.

فقط نکته اصلی اینه که قانون مسیریابی رو باید جوری تنظیم کنید که قانون وارپ قبل از قوانین معکوس باشه.

**Comment by h4z4rd95** [comment]
درود بر شما و تشکر ازتون
توی تنظیمات وارپ باید پورتی که تانل رو بر قرار کرده رو انتخاب کنیم دیگه درسته ؟
حالت آیپی رو بزاریم روی ۴ اجبارن باشه توی این تنظیمات یا ترکیب ۴ و ۶؟
نیاز هست توی همین تنظیمات حالتش رو بزاریم روی UDP/TCP یا این موارد رو دست نزنیم و فقط پورت رو انتخاب کنیم و لیست سایت های مورد نظر رو بنویسیم ؟

جسارتا این دکمه فعال کردن برای متا کدوم بخش هست؟

تشکر از شما

**Comment by alireza0** [comment]
برای هدایت پل به وارپ باید در بخش خروجی، برچسب وارپ رو انتخاب کنید.
انتخاب بقیه تنظیمات بستگی به خودتون داره.

فعال کردن متا میتونه توی تنظیمات پایه انجام بشه.
ولی میتونید از تنظیم دامنه geosite:meta در دامنه های قوانین استفاده کنید.

موفق باشید

**Comment by ramtiny** [comment]
من برام ایرانسل بدون هدر کار نمیکنه روی واتس آپ حتماً باید همراه با هدر باشه تا بتونم عکس و فیلم های واتس اپ رو ببینم 
البته روی tcp منظورمه
