### ISSUE TITLE
عدم دسترسی به REST API 

### ISSUE THREAD

**Issue by abbasnazari-0** [alireza0/x-ui#98]
با سلام
من متاسفانه نتوستم با REST API  به این پنل وصل بشم و همچنین به هیچ مستنداتی ارجاعی داده نشده است
ممنون میشم راهنمایی کنید 
با سپاس

**Comment by alireza0** [comment]
درود بر شما
این پروژه کوچک فقط چند API ساده داره که میشه توی کدها به راحتی پیداش کرد.
ترجیح میدم وقت رو برای بهبود یا ارایه پنل جدید بذارم.
اگر پنل جدیدی ایجاد شد، حتما بخش backend مجزایی خواهد داشت و برای اون مستندات ارایه میدم.
ارادتمند

**Comment by abbasnazari-0** [comment]
سپاس از شما
موفق و کامگار باشید
