### ISSUE TITLE
Wireguard peer name

### ISSUE THREAD

**Issue by SimyriK** [alireza0/x-ui#981]
Good afternoon. Thank you so much for developing such a good project. In version 1.7.1, you added auto multi-peer and qrcode for wireguard. But when you have several wireguard clients, it is very difficult to identify them.

**Comment by alireza0** [comment]
Hello @SimyriK ,
Confirmed!
Wireguard inbound in xray-core is designed in a different way that we cannot assume it as multi-user.
It is only multi-peer now.
It is better to wait for further releases if they can define peer as user with stats.
