### ISSUE TITLE
اعمال محدودیت برای اتصال کاربران

### ISSUE THREAD

**Issue by navidmkh** [alireza0/x-ui#982]
من میخوام یک اکانت رو محدود کنم که مثلا فقط یک یا دونفر همزمان بتونن اتصال داشته باشن . در حال حاظر این امکان هست ؟ تو پنل های قبلی همجین ویژگی رو داشتیم .

**Comment by alireza0** [comment]
توی این پنل وجود نداره
متونید از 3x-ui استفاده کنید
