### ISSUE TITLE
ERROR - XRAY: peer(bmXO…fgyo)

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/x-ui#983]
درود ببخشید من توی لاگ پنلم ( پنل آقای سنایی ) یه سری Error بهم نشون میده که از خود آقای سنایی پرسیدم متاسفانه نمیدونستن مشکل از کجاست ممنون میشم بهم بگین مشکل از کجاست و چطور باید حلش کنم :   ERROR - XRAY: peer(bmXO…fgyo)
- توی عکس هم ضمیمه کردم خدمتتون

![Error](https://github.com/alireza0/x-ui/assets/131817501/a5b29b83-18e6-42fe-afd1-7148dc3361b7)

**Comment by roozbehalamdari** [comment]
علیرضا جان من از تنظیمات Xray پنلم هم عکس میدم خدمتتون که بهتر بتونید راهنماییم کنید 

**تنظیمات Outbound و وارپ**
 ![warp 1](https://github.com/alireza0/x-ui/assets/131817501/6bf56b49-69ae-4636-8d3d-7b09511b010d)
 **تنظیمات Outbound 4 ( وارپ )**
![warp 2](https://github.com/alireza0/x-ui/assets/131817501/ce454fa5-1289-4b1a-b9a5-958f3052b861)

**تنظیمات قسمت Routing Rules**
![Routing Rules](https://github.com/alireza0/x-ui/assets/131817501/68539445-7625-4d07-a743-a2e73457dd15)

ممنون میشم اگر جایی مشکلی داره بهم بگین درستش کنم

**Comment by roozbehalamdari** [comment]
سپاس گذارم از راهنماییت من به این مقدار تغییر دادم 
![image](https://github.com/alireza0/x-ui/assets/131817501/e6cd7958-2601-4adb-8478-6f7f99237398)

**`لاگ :** 

`2024/02/20 10:25:56 WARNING - XRAY: [2370086993] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:55 WARNING - XRAY: [3133070466] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:54 WARNING - XRAY: [2201100840] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:53 WARNING - XRAY: [2402497695] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:53 ERROR - XRAY: peer(bmXO…fgyo)
2024/02/20 10:25:52 WARNING - XRAY: [2340319755] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:50 WARNING - XRAY: [1411535536] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:48 ERROR - XRAY: peer(bmXO…fgyo)
2024/02/20 10:25:48 WARNING - XRAY: [4024658687] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:46 WARNING - XRAY: [134382383] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:46 WARNING - XRAY: [2879397174] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:46 WARNING - XRAY: [3502913962] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:45 WARNING - XRAY: [323605593] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:43 WARNING - XRAY: [1082303467] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:43 ERROR - XRAY: peer(bmXO…fgyo)
2024/02/20 10:25:41 WARNING - XRAY: [1955767975] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:41 WARNING - XRAY: [3997449062] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:39 WARNING - XRAY: [729961439] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:39 WARNING - XRAY: [2840168696] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:38 WARNING - XRAY: [3672849801] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict
2024/02/20 10:25:38 WARNING - XRAY: [1394582516] common/mux: XUDP hit [185 21 193 71 253 221 159 54] > conflict

تعداد یوزر های من هم حدودا 80 یوزر هست ( البته بیشترشون تکراری هستن و توی اینباند های دیگه مجبور شدم بسازمشون مثلا یک یوزر رو توی اینباند برای همراه یکی ایرانسل یکی مخابرات ساختم )

**Comment by alireza0** [comment]
برای وارپ ( خروجی) نباید از این مدل استفاده کنید. اونی که توضیح دادم برای تنظیم ورودی هاست

**Comment by roozbehalamdari** [comment]
علیرضا جان سپاسگذارم از راهنماییت ولی حقیقت درست متوجه نشدم باید چجوری کجا رو تغییرات بدم مخصوصا اونجاش که فرمودی هر آدرس رو فقط مخصوص همون کاربر بذارم و تکراری نباید باشه رو متوجه نشدم دقیقا باید چکار کنم 

من میخواهم چندتا سایت رو از وارپ رد کنم ( گوگل ، برنامه Remini ، اسپاتیفای سایت Adobe ، openai ) و از یه طرف هم آی پی سرورم شناسایی نشه برای همین قبلا از وارپی که توی Ssh نصب میشه استفاده میکردم ، این سری اومدم اونو پاک کردم و از طریق خود پنل فعالش کردم که به این مشکل خوردم ، ممنون میشم بهم بگی بهترین کاری که بشه وارپ رو نصب کرد چیه یا اون آموزشی که فرمودی رو دقیقا کجا چی باید بنویسم ، یک دنیا سپاس 🙏

**Comment by alireza0** [comment]
فکر کنم از اول درست متوجه نشدم.
یکی از مشکلات شما عدم رعایت اولویت قوانینه. قانون های وارپ چون از ip invalid استفاده میکنه با قانون دوم شما قابل استفاده نیست.
بهتره قانون وارپ رو بیارید روی اولویت دوم.

اون خطایی که اولین بار فرستادید میتونه مربوط به ارتباط سرور شما با کلادفلر باشه.

**Comment by roozbehalamdari** [comment]
خواهش میکنم ، طبق فرمایش شما همین کارو کردم 
![image](https://github.com/alireza0/x-ui/assets/131817501/c2500763-2db2-4d66-b689-52ddbdc60a1a)

فقط الان سایت های ایرانی رو با اینکه وی پی ان وصله ولی راحت باز میشن در صورتی که من توی پنل تیک مسدود کردنشون رو زدم ، مشکل از کجاست  ؟ ببخشید اذیتتم کردما 

![image](https://github.com/alireza0/x-ui/assets/131817501/48ace870-1e05-4d01-83ac-eb73e87c881b)

**Comment by roozbehalamdari** [comment]
> فکر کنم از اول درست متوجه نشدم. یکی از مشکلات شما عدم رعایت اولویت قوانینه. قانون های وارپ چون از ip invalid استفاده میکنه با قانون دوم شما قابل استفاده نیست. بهتره قانون وارپ رو بیارید روی اولویت دوم.
> 
> اون خطایی که اولین بار فرستادید میتونه مربوط به ارتباط سرور شما با کلادفلر باشه.



خواهش میکنم ، طبق فرمایش شما همین کارو کردم
![image](https://github.com/alireza0/x-ui/assets/131817501/4c6f1864-5977-4313-937f-60b8cd7c2c97)

فقط الان سایت های ایرانی رو با اینکه وی پی ان وصله ولی راحت باز میشن در صورتی که من توی پنل تیک مسدود کردنشون رو زدم ، مشکل از کجاست ؟ ببخشید اذیتتم کردم

![image](https://github.com/alireza0/x-ui/assets/131817501/8cf87b8b-af72-444c-a042-20184a376492)

**Comment by roozbehalamdari** [comment]
> فکر کنم از اول درست متوجه نشدم. یکی از مشکلات شما عدم رعایت اولویت قوانینه. قانون های وارپ چون از ip invalid استفاده میکنه با قانون دوم شما قابل استفاده نیست. بهتره قانون وارپ رو بیارید روی اولویت دوم.
> 
> اون خطایی که اولین بار فرستادید میتونه مربوط به ارتباط سرور شما با کلادفلر باشه.

**یک دنیا سپاس ازت خیلی آقایی ♥
مشکلم تا این لحظه حل شده امیدوارم باز برنگرده ( همون خطای مربوط به عکس اول هم به همین ربط داشت گویا  )**
