### ISSUE TITLE
X-ui security improvement 

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#984]
Hi @alireza0 .

As you know right now x-ui starts with plain text connection then warns users to activate tls for further protections. plain text  can easily identified and server may marked as suspicious, limitations or even block by GFW.

I came across an idea about new x-ui installations.
We could use self-signed certificates till users use a valid certificate.

self-signed certificates is not a good way of using tls and chrom will show red warning which could scare not skilled users, but it does the trick for first runs and hides x-ui panel-path, user, password, configs and more.

Best of luck.

**Comment by alireza0** [comment]
Hi @X-Oracle,
IMHO it is not a good idea to limit admin to choose our way of security.
They might use another way of security.

In another hand, self-signed certificates are not secure enough.
Admins may think that it is enough and will not try to find a correct solution.

**Comment by X-Oracle** [comment]
> IMHO it is not a good idea to limit admin to choose our way of security.
> They might use another way of security.

I did not say enforce admins to choose our way of security.
what I meant way making it an available option in installation script.


> In another hand, self-signed certificates are not secure enough.

it is not secure enough but better than non-tls connections.

> Admins may think that it is enough and will not try to find a correct solution.

we could add warning just like when they did not use tls in first place reminding users that it is not secure to use self-signed certificate. 
it's about securing first connection to make it more secure not having it permanently.
we could also make it a 3- or 7-day certificate. which x-ui would forcibly switch to plain text and permanent disable self-signed option if no valid tls selected.

but I totally understand that users may say " tls is tls whether it is a valid or self-signed " and misunderstand the security level of both of them.

**Comment by alireza0** [comment]
I reckon that security is on the shoulder of admins.
It is better to provide the best solutions.
You can check #865 in this regards.

Consequences of using self-signed certificates will be more in well-known applications like x-ui.

**Comment by X-Oracle** [comment]
> I reckon that security is on the shoulder of admins.
> It is better to provide the best solutions.
> You can check #865 in this regards.
> 
> Consequences of using self-signed certificates will be more in well-known applications like x-ui.

Wow . I didn't know that such people with these opinion exist.

So the idea to making it a x-ui option is cancelled.

Thank you for taking the time for me.
