### ISSUE TITLE
X-UI 1.7.0 /  Xray 1.8.7

### ISSUE THREAD

**Issue by pouriaHemmati** [alireza0/x-ui#985]
When we make a config based on `tls `and optimize it with fragment
This config works correctly on the phone but when we run it with **v2rayn** on windows OS it gives us this error
`Microsoft Windows NT 10.0.19045.0 - 64
Start service (2024/02/20 11:39:11)...
The Core file (file name: xray, wxray) was not found under the folder (C:\Users\afa\Desktop\v2rayN-32\bin\Xray), please download and put it in the folder, download address: https://github.com/XTLS/Xray-core/releases`

version v2rayn : v6.36
version x-ui 1.7.0
version xray 1.8.7

******

update note : update x-ui version to 1.7.1
but there is the same problem again

**Comment by pouriaHemmati** [comment]
it is done , get Xray-core from `https://github.com/XTLS/Xray-core/releases` and update custom bin/xray in v2rayn

**Comment by alireza0** [comment]
It is not related to this app.
Please raise an issue in their repo

**Comment by X-Oracle** [comment]
It seems that you have installed v2rayn but with no cores .

Try update x-ray core in update section of v2rayn.
