### ISSUE TITLE
تفاوت ترافیک مصرفی اینباندها و ترافیک مصرفی کل سرور

### ISSUE THREAD

**Issue by r0zbeh** [alireza0/x-ui#987]
سلام پنل در سرور ایران نصب شده بعد از یک ساعت تست ترافیک مصرفی سرور و ترافیک اینباندها اختلاف 3 برابری دارند ؟ میشه بفرمایید به چه صورته؟
توجه داشته باشید که در طولانی مدت هم به همین صورته یعنی من سرور رو تانل کردم ب خارج  / مصرف سرور خارج 6 گیگ بود ولی مصرف سرور داخلی ایران 14 گیگ ؟؟؟!!!

![trafic q](https://github.com/alireza0/x-ui/assets/25858679/3ca469ff-2df2-4152-ac88-8359d3d4a2fa)

**Comment by alireza0** [comment]
درود بر شما
این داده ها همه از سیستم گرفته میشه و ما دستکاری نمیکنیم.
جواب پرسش های شما در متن پرسش هست.
اگر مصرف چند برابری دارید، بهتره امنیت سرور رو بررسی بیشتری بکنید.

در مورد ترافیک کارت شبکه، باید در نظر بگیرید که درخواست یکبار از کاربر گرفته میشه و یکبار به سرور ارسال میشه. در برگشت هم یکبار دریافت میشه و یکبار به کاربر ارسال میشه.
پس بدون در نظر گرفتن ترافیک پنل، تلگرام و نرم افزار های دیگه، ترافیک آپلود و دانلود هرکدوم میشن کمی بیشتر از مجموع ترافیک دریافت و ارسال.
در ضمن ترافیک سربار tls و هدر بسته ها هم باید در نظر گرفته بشه.

در مورد سرور ایران اگر شما بخشی از ترافیک رو دایرکت کرده باشید این موضوع کاملا منطقیه که همه ترافیک به خارج هدایت نشه. اگر این کار رو نکردین، مسائل امنیتی رو بیشتر بررسی کنید.

**Comment by Constantine262006** [comment]
علیرضای عزیز ، اول بابت زحمات بسیار زیادی که برای این پنل میکشی به شخصه ممنونت هستم و زحمات شما برای من ارزشمنده و شکی در تلاش و وقت و دقتی که برای این پنل گذاشتی ، شکی نیست.

یه پیشنهاد دارم چون تقریبا مربوط به همین عنوان بود گفتم اینجا مطرح کنم : 

بعض تانل ها ممکنه یک کارت شبکه مجازی به سرور اضافه کنند و اون چیزی که شما میگی بابت محاسبه مجموع ترافیک ورودی و خروجی هم کاملا درسته. چون پنل فقط به منابع مصرفی سرور نگاه میکنه و اون گزارش رو می نویسه.

- پیشنهاد :
در صفحه اول پنل در آدیت جدید بطور تفکیکی اگر هر کارت شبکه ای منابع مصرف میکنه چه ورودی و چه خروجی ، در دو حالت cpmpact , Expand بزار بصورتی که حالت پیشفرض مثل الان کامپکت باشه و کل ترافیک رو نشون بده و با کلیک بر روی اون حالت Expand به تفکیک این منابع و مصرفشون رو به تفکیک نشون بده. دقیقا همون چیزی که در nload لینوکس هم موجوده.

باز هم از زحماتت ممنونم.

**Comment by alireza0** [comment]
> * پیشنهاد :
>   در صفحه اول پنل در آدیت جدید بطور تفکیکی اگر هر کارت شبکه ای منابع مصرف میکنه چه ورودی و چه خروجی ، در دو حالت cpmpact , Expand بزار بصورتی که حالت پیشفرض مثل الان کامپکت باشه و کل ترافیک رو نشون بده و با کلیک بر روی اون حالت Expand به تفکیک این منابع و مصرفشون رو به تفکیک نشون بده. دقیقا همون چیزی که در nload لینوکس هم موجوده.

توی پنل ما محدودیت های زیادی داریم و نمیخوایم که یه مانیتورینگ کامل از سرور بذاریم.
هدف این پنل چیز دیگه ایه و این گزارش ها فقط برای عده محدودی میتونه مفید باشه.
بهتره برای این کار از نرم افزار های مانیتورینگ استفاده کنید.
