### ISSUE TITLE
مدیریت  اتصال هر کاربر به یک کانفیگ

### ISSUE THREAD

**Issue by whoo0999** [alireza0/x-ui#989]
سلام وقت بخیر
امکانش هست در اپدیت بعدی داخل قسمت اینباند ها مثل پنل سنایی قابلیت کنترل تعداد کاربر متصل به هر کانفیگ بزارید 
باتشکر

**Comment by alireza0** [comment]
درود بر شما
وقت شما هم به شادی
لطفا قبل از ایجاد ایشو یکبار از تکراری نبودنش مطمئن بشید.
این موضوع رو چندین بار جواب دادم: قرار نیست خارج از امکانات xray-core چیز دیگه ای اضافه کنیم.

**Comment by ramtiny** [comment]
محدودیت کاربری که تو خود پنل هست چرا دقیق نیست.؟
