### ISSUE TITLE
How to use Xray-Core v1.8 reality in vless cofigs

### ISSUE THREAD

**Issue by RezaDorosti** [alireza0/x-ui#99]
سلام خسته نباشین
میخواستم ببینم چطور میشه از این قابلیت جدید توی کانفیگ هایی که ایجاد میکنیم میشه استفاده کرد.

**Comment by ircfspace** [comment]
@alireza0 
ممکنه این سورس برای توسعه پنلتون واسه reality مفید باشه :

https://github.com/sajjaddg/xray-reality

**Comment by alireza0** [comment]
درود بر شما
متاسفانه این پنل برای قابلیت های xray-core تا نسخه `1.7.5` مناسبه و نسخه جدید تغییرات پایه ای زیادی داره که از اول باید پنل دیگه ای براش نوشته بشه

**Comment by xLordHerox** [comment]
> درود بر شما متاسفانه این پنل برای قابلیت های xray-core تا نسخه `1.7.5` مناسبه و نسخه جدید تغییرات پایه ای زیادی داره که از اول باید پنل دیگه ای براش نوشته بشه البته شما میتونید از این خاصیت در الگو تنظیمات xray استفاده کنید که در این صورت باید با بسیاری از ویژگی های این پنل خداحافظی کنید

سلام. 
آیا برنامه ای دارید برای Reality؟ اگر امکانش هست Reality رو هم ساپورت کنید؟ یا یه پنل جداگانه براش طراحی کنید، البته فکر کنم همین x-ui که هست رو هم میشه ادیت زد درسته؟
ممنون.
