### ISSUE TITLE
Observatory object can't be added (to use leastPing strategy for balancer)

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#991]
Xray has a feature (borrowed from v2ray project) to ping outbounds in a set interval and use the best one via balancer routing rules.
I have tested it locally and it works. (by manually editing config.json and running xray)
It needs ObservatoryObject to be added to config.json. but when I add this to xray config in x-ui, it's not added to "/usr/local/x-ui/bin/config.json", therefore this feature does not work.
Please fix this 

observatory settings in config.json:
```
{
    "log": {},
    "api": {},
    "dns": {},
    "routing": {},
    "policy": {},
    "inbounds": [],
    "outbounds": [],
    "transport": {},
    "stats": {},
    "reverse": {},
    "fakedns": [],
    "observatory": {}
}
```
The format of observatory is like this:

```
  "observatory": {
    "subjectSelector": [
          "server1",
          "server2"
    ],
    "probeURL": "https://www.google.com/generate_204",
    "probeInterval": "1m",
    "enableConcurrency": true
  }
```

and the balancer will be like this:

```
  "routing": {
    "balancers": [
      {
        "tag": "balancer",
        "selector": [
          "server1",
          "server2"
        ],
        "strategy": {
          "type": "leastPing"
        }
      }
    ],
    "rules": []
  }
```

**Comment by alireza0** [comment]
This feature is advanced configuration which in this panel, we use it in JSON subscription. But in simple UI like x-ui could not be controlled simply.

It is true that this part is not defined as an object in Backend codes. I will fix it in next version.

**Comment by alireza0** [comment]
Due to some typos I have rebuilt the 1.7.2 tag.
You can now update your installation again and get the most of it ;)

**Comment by ErfanTech** [comment]
Dear @pulsarice 
I'm also using reverse tunnel,
Can you please guide me on how to configure my xray to take advantage of load balance?
How many servers do you have and in each what custome config are you using?

**Comment by ErfanTech** [comment]
Thanks for your detailed explanation❤️, I will try it.
Does `leastPing` method works in the current version of xray?
Can I have your telegram to message you?

**Comment by alireza0** [comment]
It is already added. Closing issue...
