### ISSUE TITLE
سوویچ پنل

### ISSUE THREAD

**Issue by hamed0mh** [alireza0/x-ui#993]
درورد
من الان یوزر فعال روی پنل سنایی دارم و میخوام بیام روی پنل شما 
لطفا راهنمایی کنین ایمن ترین روش برای سوییچ به پنل شما چیه؟

**Comment by Arman-nsb** [comment]
1. بکاپ از وضعیت فعلی سرور ( snapshot )
2. دانلود بکاپ دیتابیس سرور سنایی ( از بخش داشبورد پنل )
3. حذف پنل سنایی با دستور x-ui uninstall
4. نصب پنل علیرضا
5. ایمپورت بکاپ دیتابیس پنل سنایی به علیرضا ( از طریق داشبود پنل )
6. ترجیحا ریست xray و اعمال مجدد تنظیمات پنل
7. تست اینباندها

این مراحلی هست که خودم قبلا انجام دادم و مشکلی پیش نیومده. البته توجه داشته باش که اگر از api پنل استفاده میکنی، روش کار api این 2 پنل یخورده متفاوته و اندپونیت هاشون رو باید تو پروژه ات تغییر بدی.

**Comment by r0zbeh** [comment]
با سلام برعکس این کار هم امکان پذیر هست؟
