### ISSUE TITLE
Wireguard reserved value format is wrong (in quotation marks)

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#995]
I manually enter the wireguard config with reserved values in advanced xray settings.
![image](https://github.com/MHSanaei/3x-ui/assets/5326305/c73bc06a-c8b8-4fa3-a127-ee75fc52500b)
Xray starts and works fine.
and x-ui shows the reserved values properly:
![image](https://github.com/MHSanaei/3x-ui/assets/5326305/738f37e5-7965-48d9-896d-535981bdc0d1)
If i press "Sure" button, reserved values will be put in quotation marks and xray won't start and throws errors.
![image](https://github.com/MHSanaei/3x-ui/assets/5326305/4e47d0eb-735d-43f1-8f9c-b668098e8bbe)

`XRAY: Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: failed to parse to outbound detour config. > json: cannot unmarshal string into Go struct field WireGuardConfig.reserved of type uint8
`

**Comment by alireza0** [comment]
You are right. It is a bug, I will fix it soon.

**Comment by alireza0** [comment]
It is now fixed and will be available in next release.
