### ISSUE TITLE
Routing Rules: Unable to deselect outboundtag/balancertag

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#996]
In routing table, when I want to edit a rule, I can't deselect outbound tag.
For example, I want to clear outbound tag and set a balancer tag.
Also, balancer tag can't be deselected.

![image](https://github.com/alireza0/x-ui/assets/5326305/1537a379-5a74-4ddf-a8b4-0e06464208ae)

From XTLS documentation:
>Tip
balancerTag and outboundTag are mutually exclusive. When both are specified, outboundTag takes effect.

![image](https://github.com/alireza0/x-ui/assets/5326305/aaa8af12-ab1f-429e-a805-9ba419d06a10)

**Comment by alireza0** [comment]
You can find this text when you keep your mouse over question mark.
The simple solution is to delete rule and create new one.
I will check if I could add delete function for it

**Comment by alireza0** [comment]
I will fix it soon

**Comment by alireza0** [comment]
It is now added and will be available in next release
