### ISSUE TITLE
Inbounds: Same port, different listening IPs

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#997]
Is it possible to add a feature so we can use the same port on different inbounds.
For example I want to create two inbounds with the same port but one on IPv4 and the other on IPv6.
It's possible in 3x-ui.
Thanks.

**Comment by alireza0** [comment]
It needs a big change in the inbound-tag creatiion and will cause serious problem in existing inbounds of users. I will check if it is possible to add

**Comment by alireza0** [comment]
It is now added to codes, but please be informed that you can not use it with old database.
It needs new database. If you need just import old inbounds using copied inbounds in new panel.
