### ISSUE TITLE
خطای پنل

### ISSUE THREAD

**Issue by peyman508** [alireza0/x-ui#999]
پنل بعد از نصب شدن با آی پی سرور بالا میاد.اما به محض وارد کردن کلید ها و ذخیره پنل پروکسی کلاد که روشن میشه پنل از دسترس خارج میشه

HTTP ERROR 404

**Comment by alireza0** [comment]
شما از سرویس رایگان کلادفلر استفاده میکنید. پورتهایی که پشتیبانی میکنه محدوده. از اون پورتها باید استفاده کنید.
این باگ نیست و از طرفی ربطی به پنل نداره

**Comment by peyman508** [comment]
*سلام.من خیلی وقته از پنل شما استفاده میکنم و مشکلی نداشتم.پورت ها رو هم به
خوبی میشناسم.مسیر URI و خطا میگرفت روی آپدیت جدید و همچنان خطا رو
داره.ویرایش که میکنیم و ریستارت میکنیم پنل دیگه بالا نمیاد.در صورتی که قبلا
این اخطار و نداشت*

‫‪Alireza Ahmadi‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۲۱ فوریه
۲۰۲۴ ساعت ۱۸:۴۶ نوشت:‬

**Comment by alireza0** [comment]
اون بخشی که دیدید، خطا نیست. هشداره!
اگر Panel Path رو تغییر دادین، دیگه باید بعد از آدرس و پورت پنل، و قبل از x-ui/ اون URI  رو اضافه کنید.
امنیت این حالت به همین دلیل تامین میشه که دیگه کسی با آدرس و پورت پنلتون، بدون داشتن Path نمیتونه پنلتون رو ببینه.

**Comment by peyman508** [comment]
یعنی به این حالت :
2053/ example  /xui/settings
اینجوری اوکیه؟

‫‪Alireza Ahmadi‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۲۱ فوریه
۲۰۲۴ ساعت ۱۹:۳۵ نوشت:‬

**Comment by peyman508** [comment]
مثلا یه اسم بزارم.هر چی که بود

‫‪Peyman Akhavan‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۲۱
فوریه ۲۰۲۴ ساعت ۱۹:۵۹ نوشت:‬
